<?
$descriz = "La versione Nuovo Mondo &egrave; un commentario non una traduzione, per cui non &egrave; inclusa nelle versioni disponibili con questo programma della Bibbia.";
$key = "nuovo mondo,testimoni di geova";
$titolo = "La versione 'Nuovo Mondo'";
$sezione = "Domande comuni";
$sezioneurl = "/faq/";
require("../capo.php");
?>
<h1>La versione 'Nuovo Mondo'</h1>
<p class="primalettera">La versione <em>Nuovo Mondo</em> &egrave; stata tradotta dai Testimoni di Geova, prima in inglese e poi in altre lingue, di cui l'italiano. Ha molti aspetti positivi. Ma quando l'ho studiata, mi sono reso conto che non &egrave; una traduzione precisa del testo greco (i problemi sono soprattutto nel Nuovo Testamento), ma che ci sono dei cambiamenti affinch&eacute; la versione sia conforme alla dottrina dei Testimoni. Alcune persone che non erano d'accordo con questa mia affermazione mi hanno scritto, sempre con gli stessi ragionamenti. Ogni persona poi ha smesso di respondere ai miei messaggi allo stesso punto, non so se sia perch&eacute; non sapevano pi&ugrave; rispondere al mio ragionamento oppure per altri motivi. Ma per evitare di ripetere nuovamente le stesse discussioni, ho deciso di mettere un riassunto qui.</p>
<p>Come ho detto, ci sono diversi versetti in cui la <em>Nuovo Mondo</em> non segue il testo greco che abbiamo. Non parler&ograve; di tutti, ma dar&ograve; tre esempi.</p>

<h2>Colossesi 1:15-17</h2>
<p>In Colossesi 1:15-17 la parola &quot;altro&quot; &egrave; inserita 4 volte. &Egrave; vero, fra parentesi per indicare che &egrave; stata aggiunta, ma di solito le parole fra parentesi completano la traduzione senza cambiare il senso, come &quot;piacer[gli]&quot; nel versetto 10. Ma qui cambiano il senso, perch&eacute; il senso del testo greco non era accettabile ai traduttori. Ci sono due parole greche che vogliono dire &quot;altro&quot;; nessuna delle due &egrave; stata usata qui da Paolo.</p>

<p>Un ragionamento spesso usato per giustificare l'inserimento di &quot;altro&quot; nel versetto 15 &egrave; che negli altri 36 versetti in qui la frase &quot;primogenito di&quot; appare nella Bibbia, quello che &egrave; il primogenito appartiene al gruppo a cui appartiene quello di cui &egrave; il primogenito.
Quindi deve essere cos&igrave; anche in Colossesi 1:15, e il versetto direbbe che Ges&ugrave; appartiene al gruppo delle creature, che giustificherebbe l'aggiunta della parola &quot;altro&quot;.
Oltre alcuni problemi al livello linguistico su come determinare la definizione di una parola, il ragionamento soffre da un errore fatale, in quanto l'analisi &egrave; stata fatta con una Bibbia in inglese. (Ho anche visto traduzioni di questo ragionamento in italiano, dove il numero <i>36</i> non &egrave; vero, non nessuno ha controllato questo fatto.)
In inglese, ci sono tre modi per esprimere il possessivo: X of Y, my X (e gli altri pronomi possessivi) e Y's X. In italiano ci sono solo i primi due modi: X di Y e mio X.
In greco, c'&egrave; solo un modo: X Y dove Y &egrave; nel caso genitivo. Il ragionamento, considerando solo il primo modo di esprimere il possessivo in inglese o italiano, ha trascurato altri versetti che ci aiutano a capire il significato della parola. (In realt&agrave;, il genitivo greco pu&ograve; anche essere tradotto in altri modi con non sono il possessivo, per esempio con la preposizione fra.)
In altre parole, l'affermazione &quot;Negli altri 36 versetti in qui la frase &quot;firstborn of&quot; appare nella Bibbia inglese, quello che &egrave; il primogenito appartiene al gruppo a cui appartiene quello di cui &egrave; il primogenito&quot; &egrave; vera, ma il migliore che pu&ograve; fare &egrave; dimostrare il significato della frase &quot;firstborn of&quot; in inglese, che &egrave; irrilevante per capire il senso di Colossesi 1:15, che &egrave; stato scritto in greco.
Dall'altra parte, l'affermazione &quot;Negli altri versetti in qui la frase &quot;prototokos + genitivo&quot; [dove prototokos &egrave; la parola greca tradotta firstborn/primogenito] appare nella Bibbia, quello che &egrave; il primogenito appartiene al gruppo a cui appartiene quello di cui &egrave; il primogenito&quot; &egrave; falsa; Esodo&nbsp;4:22 &egrave; un esempio e ce ne sono altri.
E se la premessa &egrave; falsa, il ragionamento non &egrave; valido.
Quello che trovo interessante &egrave; che nessun Testimone di Geova mi ha mai ammesso che il ragionamento &egrave; sbagliato. Della decina di persone che mi ha detto questo ragionamento, le risposte migliori che ho avuto quando noto l'errore sono state "E quindi?" (come se non importasse che il ragionamento fosse sbagliato) e "S&igrave; &egrave; difficile determinare il significato di una parola greca dalla sua traduzione" (in realt&agrave; &egrave; impossibile). Ma la risposta tipica &egrave; che non rispondono.</p>    

<p>A questo punto, si potrebbe ragionare, &quot;Ma la Bibbia insegna che Ges&ugrave; &egrave; stato creato, per esempio in questi versetti...&quot;. Io non ci credo, ma non &egrave; rilevante. Se si fa cos&igrave; si cambia il testo per essere conforme alla propria dottrina (anche se vera o biblica), il che significa che &egrave; un commentario (spiega quello che il testo significa) e non una traduzione (riporta quello che il testo dice). Se Ges&ugrave; fosse creato e il testo di Colossesi 1 non lo dice, cambiare il testo o aggiungere una parola per spiegare il testo sarebbe giusto dottrinalmente e come si fa in un commentario, ma non come in una traduzione. Bisogna invece dimostrare che il testo originale di Colossesi 1 include la parola &quot;altro&quot;.</p>

<p>A proposito di questo brano, c'&egrave; un articolo interessante nella <em>Torre di Guardia</em> (la rivista dei Testimoni di Geova) del 15 aprile, 1970.</p>

<p><cite>Considerando tale soggetto &egrave; bene notare che gli scrittori biblici presero
spesso per scontato che certe cose fossero capite, come fanno gli scrittori
del nostro giorno. Per esempio, l'apostolo Paolo, come leggiamo in Colossesi
1:16, dichiara che per mezzo di Ges&ugrave; Cristo furono create tutte le cose nei
cieli e sulla terra. Ma giacch&eacute; da Rivelazione 3:14 sappiamo che anche Ges&ugrave;
stesso fu creato, la Traduzione del Nuovo Mondo aggiunge la parola &quot;altre&quot;,
che &egrave; chiaramente ci&ograve; che aveva in mente l'apostolo. Ma anche in tal caso,
si potrebbe aggiungere che, se non fosse per la prevalenza dell'insegnamento
trinitario che Ges&ugrave; non fosse creato, non sarebbe stato necessario
aggiungere la parola &quot;altre&quot;.</cite></p>

<p>In altre parole, la traduzione di Colossesi 1 &egrave; un commentario su altri versetti (per esempio Apocalisse 3), ed &egrave; stata fatta per motivi
dottrinali (in senso negativo, non per affermare una dottrina dei Testimoni ma per contraddire una dottrina di altri).</p>

<h2>Matteo 26:26-28</h2>

<p>Commenter&ograve; brevemente su questo brano; &egrave; utile soprattutto per spiegare meglio il problema con Colossesi e in che senso la Nuovo Mondo &egrave; un commentario e non una traduzione. Per questi versetti, la Nuovo Mondo ha:</p>
<p><cite><strong>26</strong> Mentre continuavano a mangiare, Ges&ugrave; prese un pane e, dopo aver detto una benedizione, lo spezz&ograve; e, dandolo ai suoi discepoli, disse: &quot;Prendete, mangiate. Questo significa il mio corpo&quot;. <strong>27</strong> E prese un calice e, avendo reso grazie, lo diede loro, dicendo: &quot;Bevetene, voi tutti; <strong>28</strong> poich&eacute; questo significa il mio 'sangue del patto', che dev'essere versato a favore di molti per il perdono dei peccati&quot;.</cite></p>

<p>Il problema &egrave; &quot;Questo <em>significa</em> il mio...&quot; (due volte). Il testo greco ha invece &quot;Questo <em>&egrave;</em> il mio...&quot;. Nessuno dubita che <em>&egrave;</em> possa avere il significato <em>significa</em>; fra altro, ci sono tanti esempi di questo modo di dire nella Bibbia (per esempio Matteo 12:7; 27:33). Se sia il significato in questo versetto &egrave; una questione teologica e dottrinale - non linguistica. Personalmente, credo che la Nuovo Mondo abbia ragione, cio&egrave; che questo sia il significato corretto del brano. Ma sia che il significato sia giusto (come credo qui) sia che il significato sia sbagliato (come altri credono qui, e come credo in Colossesi 1), rimane sempre il significato del versetto, e non quello che il versetto dice. Cio&egrave; la Nuovo Mondo non mette il testo (come una traduzione dovrebbe) ma il significato (come un commentario); la traduzione &egrave; teologica e dottrinale, non linguistica. Dovevano lasciare il verbo <em>essere</em>, che anche in italiano pu&ograve; volere dire <em>significa</em>. Le parole di Ges&ugrave; sono ambigue, e il compito di un traduttore &egrave; di riportare il testo. Il compito di un teologo o di un commentario &egrave; di spiegare il senso, ed &egrave; questo che la Nuovo Mondo fa. Negli altri versetti in cui il verbo greco &egrave; tradotto <em>significare</em> in italiano, &egrave; perch&egrave; la grammatica italiana lo richiede - <em>essere</em> non avrebbe senso in quei versetti. In altre parole, diversamente da Matteo 26, la parola non &egrave; ambigua e va tradotta <em>significare</em>.</p>

<h2>Geova nel Nuovo Testamento</h2>
<p>Nei testi greci che abbiamo del Nuovo Testamento, 'Geova' non appare mai. Nonostante questo, spesso la Nuovo Mondo lo mette, dove i testi hanno <em>kurios</em>, cio&egrave; 'Signore'. Questo &egrave; fatto quando il versetto nel NT &egrave; una citazione di un versetto dell'Antico Testamento (che aveva originalmente Geova), ma anche spesso quando non &egrave; una citazione, per esempio Atti 1:24, Romani 12:11, 1Corinzi 4:19, 2Corinzi 8:21; Giacomo 1:7. Perch&eacute; questo cambiamento? I Testimoni di Geova rispondono che non abbiamo i testi originali, cio&egrave; quelli scritti dagli apostoli. Che &egrave; vero; i primi frammenti che abbiamo sono dell'inizio del secondo secolo, mentre i primi manoscritti pi&ugrave; completi sono del terzo secolo. I Testimoni di Geova sostengono che i testi originali avevano 'Geova', ma che nel secolo che segu&igrave; nelle copie che sono state fatte il nome di Dio, 'Geova', fu sostituito dai titoli 'Dio' e 'Signore'. Quale evidenza hanno per sostenere questo? Ci sono due ragioni. Il primo &egrave; che nel quarto secolo Girolamo (il traduttore della Vulgata) scrisse che &quot;in certi volumi greci [della versione dei Settanta, cio&egrave; la LXX, una traduzione dell'Antico Testamento in greco, fatta prima di Cristo e spesso usata dai cristiani che parlavano greco ma non ebraico] troviamo tuttora le quattro lettere del nome del Signore scritte in caratteri antichi&quot;. Che non mi sembra sufficiente per sostenere l'affermazione che il NT conteneva 'Geova'; fra altro mi chiedo degli altri volumi della LXX che non lo contengono - a quali dobbiamo fidarci? La seconda ragione posso riassumere nel seguente modo:</p>
<ol>
<li>Ges&ugrave; e gli apostoli, essendo seguaci dell'AT (ebraico, con Geova nel testo), usavano il nome di Dio.</li>
<li>Quindi quando gli apostoli scrissero, usarono il nome.</li>
<li>Quindi se non troviamo il nome nel testo greco, &egrave; perch&eacute; &egrave; stato tolto dai cristiani posteriori.</li>
<li>Quindi dobbiamo mettere 'Geova' nel NT</li>
</ol>
<p>Il mio problema con questo ragionamento &egrave; il primo punto. Ammetto che se fosse vero, tutto il resto seguirebbe logicamente. Ma dopo Cristo gli apostoli non seguirono tutte le pratiche dell'AT. Seguirono l'insegnamento dell'AT, nel senso del suo adempimento in Ges&ugrave;, ma non nel senso letterale. Per esempio, continuarono a seguire l'insegnamento o significato dei sacrifici - ma credendo che fossero adempiute in Ges&ugrave;, il nostro unico sacrificio, non facevano pi&ugrave; i sacrifici al tempio nonostante il fatto che erano chiaramente ordinati nell'AT. Trovo un simile cambiamento nel modo in cui si rivolgevano a Dio. Dio &egrave; ancora il grande 'Io sono', si chiama ancora Geova, ma si parla a lui chiamandolo &quot;Padre&quot. I riferimenti sono innumerevoli, ma cito solo uno perch&eacute; i Testimoni citano spesso Matteo 6:9, &quot;Padre nostro [che sei] nei cieli, sia santificato il tuo nome&quot;. Dobbiamo pregare che il nome di Dio sia santificato. Giusto. Ma come lo facciamo? Rivolgendoci a lui come Padre. Il motivo per cui gli apostoli non usavano pi&ugrave; il nome di Dio &egrave; perch&eacute; dopo Ges&ugrave; c'&egrave; un nuovo rapporto fra Geova e il suo popolo. E santifichiamo il suo nome riconoscendo questo, chiamandolo 'Padre'! &Egrave; come uno schiavo che per anni lavora per il suo padrone, chiamandolo 'Signore' e con il suo nome. Poi un giorno il padrone gli dice che l'ha adottato, e adesso vuole essere chiamato 'Padre', o addirittura 'babbo' ('abba' nel greco e di solito nelle versioni italiane). C'&egrave; un nuovo rapporto, e lo schiavo che adesso &egrave; un figlio non user&agrave; pi&ugrave; il nome per rivolgersi all'ex-padrone, ma il termine che esprime questo nuovo rapporto, 'Padre mio'.</p>

<p>Alla fine, l'unico motivo per mettere 'Geova' nel Nuovo Testamento &egrave; che per forza gli apostoli lo usavano. Ma questo &egrave; la dottrina dei Testimoni di Geova, e non necessariamente vero. Per questo dico che la Nuovo Mondo che cambiato il testo biblico che abbiamo, affinch&eacute; sia conforme alla propria dottrina. Per questo non &egrave; una traduzione fedele della Bibbia, e non posso includerla con le altre versioni.</p>

<h2>Cosa dicono gli studiosi</h2>
<p>Infine, un ragionamento sempre citato dai Testimoni &egrave; che ci sono degli studiosi che appoggiano la Nuovo Mondo. E sono sempre gli stessi: Edgar Goodspeed, Alexander Thomson, Benjamin Kedar e Jason BeDuhn. Da parte del fatto che trascurano la maggioranza degli studiosi biblici che afferma il contrario, gli studiosi che citano non sono sempre cos&igrave; positivi. Li ho cercati su Internet, e trovato le seguenti affermazioni:</p>

<p><strong>Goodspeed:</strong> I Testimoni citano una lettera scritta da Goodspeed nel 1950. Dopo questa lettera, Bill Cetnar della sede della Torre di Guardia and&ograve; a trovare il dottore Goodspeed nel 1954 per chiedergli il suo appoggio totale. Cetnar scrisse, &quot;Dr Goodspeed fu chiesto se avrebbe consigliato la traduzione per il pubblico. Rispose, 'Mi dispiace, non posso farlo. La grammatica &egrave; spiacevole. State attenti della
grammatica'&quot;.</p>

<p><strong>Thomson:</strong> Era uno &quot;studioso di ebraico e greco&quot; secondo i Testimoni di Geova. In realt&agrave;, era un redattore di una rivista chiamata <em>The Differentiator</em> (&egrave; un articolo in questa sua rivista che viene citato). La rivista usciva ogni due mesi, con una piccola circolazione, e non &egrave; pi&ugrave; pubblicata. Secondo l'altro redattore della rivista, Frank Neil Pohorlak, Thomson &quot;non aveva neanche studiato formalmente il greco o l'ebraico in qualsiasi scuola&quot;. Cio&egrave; non era uno studioso di ebraico e di greco, come affermano i Testimoni, ma invece &quot;era un impiegato in una banca in Scozia&quot;.<br />
<strong>Nota addizionale:</strong> Nonostante le obbiezioni di molti all'uso di Thomson per sostenere la NM, i Testimoni di Geova continuano a citarlo. Nel numero de <em>La torre di guardia</em> del 15 novembre 2001, in un articolo sulla NM, c'&egrave; scritto, &quot;Vari studiosi sono rimasti colpiti. Per esempio, l'erudito biblico inglese Alexander Thomson...&quot; (la pagina 7).

<p><strong>Kedar:</strong> Essendo ebraista, rifiuta di parlare del NT, dove i cambiamenti della NM sono pi&ugrave; evidenti; sono d'accordo con Kedar che nell'AT la traduzione &egrave; abbastanza fedele.</p>

<p><strong>BeDuhn:</strong> Scrisse (citano i Testimoni): &quot;Sotto molti aspetti &egrave; superiore alle traduzioni di maggior successo in uso oggi&quot;. Di questo non ho dubbi. Ma mi ha fatto pensare: questa frase significa che sotto altri aspetti &egrave; inferiore, e cos&igrave; mi sono chiesto, Sotto quali aspetti &egrave; inferiore? Ho scoperto che &egrave; inferiore sotto proprio gli aspetti che mi preoccupavano, di cui ho scritto qui sopra. Per esempio, bench&eacute; sostenitore della Nuovo Mondo, BeDuhn scrisse, &quot;In realt&agrave;, la Nuova Mondo non traduce 'kurios' come 'Geova', lo sostituisce inserendo il nome di Dio nel testo. I TG fanno molto fatica spiegare perch&eacute; si sentono giustificati a farlo (per esempio, nell'Appendice della Interlineare). Notano giustamente che in molti casi il Nuovo Testamento cita un brano del Vecchio Testamento dove l'ebraico ha il nome di Dio, non la parola 'Signore'. Comunque, come studioso biblico obietto all'introduzione del nome Geova nel testo del Nuovo
Testamento. Bench&eacute; alcuni scrittori del NT dimostrano che conoscono questo nome di Dio, nessuno di loro lo introduce, e non c'&egrave; neanche uno manoscritto greco che sostiene l'inserimento del nome. Quindi questa &egrave; una critica che ho della NM&quot;.</p>

<?
require("../piede.php");
?>
