<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 3]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 3]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Abimelec (Giudici 9)</h1>
<p>Questo capitolo &egrave; insolito, in quanto Abimelec non era un giudice, ma un re usurpatore. Era praticamente un anti-giudice, facendo il contrario di quello che un giudice doveva fare. Invece di liberare Israele, opprimeva Israele. Invece di governare Israele per Dio, allontan&ograve; Israele da Dio. Disfece tutta l'opera di suo padre Gedeone.</p>
<p>Il racconto di Abimelec &egrave; una storia di vendetta umana e di retribuzione divina. La vendetta umana &egrave; quando qualcuno deve pagare per quello che ha fatto, quando gli facciamo lo stesso male o di peggio. Nella retribuzione divina, il male che qualcuno fa ritorna a fare male a lui. Ci sar&agrave; un approfondimento di questi temi di vendetta e retribuzione alla fine di questo capitolo. Intanto, per aiutarci a capire quello che succede mentre leggiamo il capitolo, abbiamo la conclusione dell'autore del libro, che ci spiega chiaramente la causa di tutti gli avvenimenti tristi descritti.</p>
<blockquote>Cos&igrave; Dio fece ricadere sopra Abimelec il male che egli aveva fatto contro suo padre uccidendo i suoi settanta fratelli. Dio fece anche ricadere sul capo degli uomini di Sichem tutto il male che avevano fatto; e su di loro si comp&igrave; la maledizione di Iotam, figlio di Ierubbaal. Giudici 9:56-57</blockquote>
<h2>1. Introduzione: Abimelec e Israele (8:30-35)</h2>
<p>Abbiamo visto nella sezione precedente che Gedeone aveva liberato Israele dai Madianiti, per cui Israele ebbe pace o riposo per 40 anni (Giudici 8:28). Per&ograve;, Gedeone non era perfetto, e ebbe molte mogli, da cui nacquero 70 figli. Inoltre, aveva anche una concubina, che non viveva con lui ma a Sichem. Da questa concubina Gedeone ebbe un figlio, Abimelec (Giudici 8:29-32).</p> 
<p>Dopo la morte di Gedeone, gli Israeliti dimenticarono le loro liberazioni da parte di Dio - dall'Egitto tramite Mos&egrave;, da Mesopotamia tramite Otniel, da Moab tramite Eud, dai Cananei tramite Debora e Barac, e da Madian tramite Gedeone. Decisero di adorare i Baal, gli d&egrave;i dei popoli che li avevano oppressi, piuttosto del vero Dio che li aveva liberati (Giudici 8:33-35).</p>
<p>Di solito a questo punto nei racconti dei giudici, nel ciclo che &egrave; la norma per i giudici, c'&egrave; l'oppressione da parte di un nemico perch&eacute; Israele aveva abbandonato il Signore. Ma questa volta il nemico, l'oppressore, viene dall'interno del popolo. Israele &egrave; caduto cos&igrave; tanto lungo la spirale, che ormai gli Israeliti opprimono s&eacute; stessi. Non aveva bisogno degli altri popoli per farsi del male.</p> 
<h2>2. Abimelec e Sichem (9:1-6)</h2>
<p>Dopo la morte di Gedeone, Abimelec and&ograve; a Sichem per trovare la sua famiglia, dalla parte della madre. Propose alla famiglia di dire agli abitanti di Sichem che invece di avere i 70 figli di Gedeone regnare su di loro, era meglio avere una sola persona regnare. E chi meglio che Abimelec stesso, siccome lui era uno di loro, di Sichem (Giudici 9:1-2). La famiglia convinse i Sichemiti di sostenere Abimelec, e i Sichemiti diedero dei soldi a Abimelec per assumere dei mercenari (Giudici 9:3-4). Ironicamente, presero i soldi dal tempio di Baal-Berit, che era proprio il dio che gli Israeliti avevano preso come loro dio (Giudici 8:33). Cio&egrave;, si erano affidati ad un idolo, un dio che non poteva e non voleva aiutarli, e ricevettero da quell'idolo solo del male. Questo tema di ricevere quello che desideriamo, del male che ricade su una persona, sar&agrave; ripetuto diverse volte in questo capitolo.</p>
<p>Con i mercenari, Abimelec and&ograve; dalla casa di Gedeone, dove abitavano anche i suoi fratellastri. L&igrave;, il primo figlio di Gedeone fu giustiziato. Tolto il corpo, fu ucciso il secondo. Poi un altro, avanti il prossimo, per un totale di 69 volte mentre la montagna di cadaveri cresceva sempre di pi&ugrave; e il sangue scorreva. Solo uno figlio di Gedeone, Iotam, scamp&ograve; al massacro. Poi i Sichemiti proclamarono Abimelec re (Giudici 9:5-6). Siccome Sichem era allora una citt&agrave; importante di Israele, se non la pi&ugrave; importante, Abimelec aveva molta influenza su tutta la nazione, e forse anche regnava su tutti (Giudici 9:22). Infatti, &egrave; scritto in questo versetto che "la quercia del monumento" si trovava a Sichem. Questo monumento &egrave; forse la tomba di Giuseppe (Genesi 33:18-19; Giosu&egrave; 24:32). Sichem stava anche nella valle fra i monti Ebal e Gherizim, dove gli Israeliti guidati da Giosu&egrave; proclamarono le benedizioni e le maledizioni (Giosu&egrave; 8:30-33), ed era dove Giosu&egrave; diede il suo ultimo discorso e rinnov&ograve; il patto (Giosu&egrave; 24:1,25).</p> 
<h2>3. Avvertimento di Iotam (9:7-21)</h2>
<p>Iotam, il superstite allo sterminio dei figli di Gedeone, parl&ograve; ai Sichemiti dal monte Gherizim, cio&egrave; da una distanza di sicurezza. Raccont&ograve; una parabola, degli alberi che cercarono un re. Chiesero all'ulivo, al fico, e alla vite, ma tutti e tre rifiutarono perch&eacute; gi&agrave; producevano buone cose (olio, frutto, vino) e non desideravano agitarsi al di sopra degli uomini. Il pruno, invece, che non aveva niente tranne le spine, rispose di s&igrave;. Per&ograve;, dett&ograve; una condizione. Se avessero chiesto in buona fede, sarebbero potuti rifugiarsi sotto la sua ombra, che comunque faceva male a causa delle spine. Se non fossero in buona fede, sarebbero stati distrutti dal pruno (Giudici 9:8-15).</p>
<p>Iotam poi spieg&ograve; la parabola. Gedeone aveva fatto tanto bene per i Sichemiti (combattuto per loro, liberato loro). Gedeone aveva rifiutato di essere il capostipite di una dinastia di re (Giudici 8:22-23). I Sichemiti ripagarono il bene che Gedeone aveva fatto per loro con il male, uccidendo i suoi figli, e chiesero invece Abimelec, cio&egrave; un pruno, come re. Adesso, dovevano vivere con la scelta che avevano fatto. Se erano in buona fede, dovevano "godere" Abimelec, anche se avrebbe fatto male. Se non erano in buona fede, sarebbero stati distrutti da Abimelec (Giudici 9:16-21).</p>
<h2>4. Sichem contro Abimelec (9:22-29)</h2>
<p>Abimelec era il re di Sichem e signoreggi&ograve; sopra Israele per tre anni. Poi Dio mand&ograve; un cattivo spirito fra Abimelec e i Sichemiti, probabilmente nel senso di creare del rancore, odio, e disprezzo fra le due parti. Cos&igrave; la parola di Iotam era adempiuta, ma Dio lo fece per castigare Abimelec e i Sichemiti per aver ucciso i figli di Gedeone (Giudici 9:22-24).</p>
<p>Il piano dei Sichemiti era di porre dei banditi sui monti vicini a Sichem, forse sperando che Abimelec uscisse contro di loro e venisse ucciso. Inoltre, colsero l'opportunit&agrave; di un nuovo capo quando Gaal arriv&ograve;. Gaal era di Sichem, e di nuovo troviamo l'ironia: il comportamento di Abimelec ritorna contro di lui. Abimelec aveva proposto ai Sichemiti di essere il re, perch&eacute; era di Sichem dalla parte della madre (Giudici 9:2-3). Gaal ragion&ograve; che era meglio che fosse re invece di Abimelec, perch&eacute; era un Sichemita "puro", non come Abimelec che era il figlio di Gedeone. Abimelec fu tradito da Sichem e da Gaal in esattamente lo stesso modo in cui aveva tradito Gedeone (Giudici 9:25-29).</p>
<p>Guai a noi se ci fidiamo delle persone, perch&eacute; non sono affidabili, e hanno sempre delle scuse per cercare i propri interessi. Solo Dio &egrave; degno della nostra fiducia!</p>
<h2>5. Abimelec contro Gaal (9:30-41)</h2>
<p>A questo punto Zebul, che era un alleato di Abimelec e governava la citt&agrave; di Sichem sotto il re, inform&ograve; Abimelec della ribellione di Gaal e i Sichemiti. Lo consigli&ograve; di prepararsi per attaccare la citt&agrave; (Giudici 9:30-33). Cos&igrave; il giorno seguente Abimelec e i suoi seguaci combatterono contro Gaal e i Sichemiti e li sconfissero, scacciando Gaal dalla citt&agrave; (Giudici 9:34-41).</p> 
<h2>6. Abimelec contro Sichem (9:42-49)</h2>
<p>Abimelec volle la vendetta contro Sichem, e non aspett&ograve; per eseguirlo. Il giorno dopo, quando la gente usc&igrave; dalla citt&agrave; per lavorare nei campi, fece un'imboscata nei campi e fece una strage, e si mise anche all'ingresso della citt&agrave; per ammazzare chi cercava di ritornare per rifugiarsi dentro le mura. In questo modo tanti morirono, e Abimelec anche spian&ograve; la citt&agrave; e sparse del sale affinch&eacute; niente potesse crescere (Giudici 9:42-45). I superstiti del massacro si ritirarono in una torre. Per&ograve; la sete di sangue di Abimelec non era appagata, e incendi&ograve; la torre, facendo perire le circa mille persone rifugiate dentro (Giudici 9:46-49).</p>
<h2>7. Abimelec contro Tebes (9:50-55)</h2>
<p>Abimelec allora aveva un problema: era un re senza un regno. Siccome aveva distrutto Sichem, aveva bisogno di una citt&agrave; dove regnare. Quindi and&ograve; a Tebes e se ne impadron&igrave;. Anche qui gli abitanti si rifugiarono in una torre. Siccome incendiare la torre aveva funzionato a Sichem, Abimelec pens&ograve; di ripetere il suo successo. Per&ograve;, quando prov&ograve; a appiccare il fuoco alla base della torre, una donna butt&ograve; una pietra dalla torre e colp&igrave; Abimelec e lo fer&igrave; mortalmente. Abimelec prefer&igrave; essere ucciso da una spada che da una donna, per cui chiese al suo servo di ucciderlo con la sua spada.</p>
<p>Quando tutti videro che Abimelec era morto, tornarono a casa, cio&egrave; Israele era di nuovo senza guida e senza oppressore.</p>
<h2>8. Dio contro gli ingiusti (9:56-57)</h2>
<p>Dopo aver raccontato tutti gli avvenimenti, sia buoni sia brutti, lo scrittore ne spiega il significato negli ultimi due versetti del capitolo. Dio fece ricadere su Abimelec tutto il male che aveva fatto a suo padre uccidendo i figli di Gedeone, e anche fece ricadere sui Sichemiti tutto il male che loro avevano fatto. In questo modo la maledizione di Iotam fu compiuta.</p>
<p>A volte Dio fa la vendetta, e ne parleremo in seguito. Per&ograve; in questi casi &egrave; diverso, Dio fece ricadere il male, cio&egrave; ricevettero la vita (e la morte) che avevano scelto. Scelsero il male e ricevettero le conseguenze di quella scelta. Era giusto adorare Baal-Berit secondo gli Israeliti? Furono abbandonati a Baal-Berit che non pot&eacute; proteggerli. Tradire Gedeone era buono secondo Abimelec? Lui fu tradito nello stesso modo. Sterminare tutta la famiglia andava bene per gli Sichemiti? Loro e le loro famiglie furono sterminati. Come dice il proverbio italiano, "Chi di spade ferisce, di spada perisce", che si base sul detto di Ges&ugrave; in Matteo 26:52, "tutti quelli che prendono la spada, periranno di spada". Lo stesso principio vale anche nella nostra vita. Se facciamo dei lavori in nero, non dobbiamo essere sorpresi che ci imbrogliano. Se raccontiamo pettegolezzi e segreti, &egrave; naturale che la gente non si fider&agrave; pi&ugrave; di noi e dice pettegolezzi di noi. Riceviamo quello che desideriamo. Per Abimelec una vita di tradimento e morte; per noi una vita di disonest&agrave; e sfiducia. Spesso sono le conseguenze naturali delle nostre scelte sbagliate, ma Dio pu&ograve; anche "accelerare" o "incoraggiare" queste conseguenze, come fece in Giudici 9:23 mandando un cattivo spirito fra Abimelec e i Sichemiti.</p>
<p>Cosa diciamo della vendetta? Parliamo prima di tutto della vendetta umana. La mela non cade mai lontano dall'albero. Gedeone fece vendetta contro chi l'aveva insultato o offeso e chi gli aveva fatto male (Giudici 8), e Abimelec fece altrettanto. I Sichemiti cercarono di togliere Abimelec come re, per vendetta Abimelec stermin&ograve; tutti i Sichemiti. Infatti, chi vive per la vendetta muore per la vendetta. Fare del male a qualcuno che ci ha fatto del male vuol dire soltanto che l'altro dovr&agrave; fare vendetta della nostra vendetta e ci far&agrave; ancora pi&ugrave; male. Se al posto di lavoro il collega o il datore del lavoro ci fa del male, pensiamo di fargli pagare? Se in chiesa qualcuno ci fa qualcosa che non ci piace, diventa un nemico?</p>
<p>La vendetta non &egrave; la strada della croce.</p>
<blockquote>Se soffrite perch&eacute; avete agito bene, e lo sopportate pazientemente, questa &egrave; una grazia davanti a Dio. Infatti a questo siete stati chiamati, poich&eacute; anche Cristo ha sofferto per voi, lasciandovi un esempio perch&eacute; seguiate le sue orme.<br /> <i>Egli non commise peccato<br /> e nella sua bocca non si &egrave; trovato inganno.</i><br /> Oltraggiato, non rendeva gli oltraggi; soffrendo, non minacciava, ma si rimetteva a colui che giudica giustamente; egli ha portato i nostri peccati nel suo corpo, sul legno della croce, affinch&eacute;, morti al peccato, vivessimo per la giustizia. 1Pietro 2:20-24</blockquote>
<p>Quindi la vendetta non &egrave; neanche la vita di chi segue il Signore Ges&ugrave; Cristo:</p>
<blockquote>Voi avete udito che fu detto: "Occhio per occhio e dente per dente". Ma io vi dico: non contrastate il malvagio; anzi, se uno ti percuote sulla guancia destra, porgigli anche l'altra; e a chi vuol litigare con te e prenderti la tunica, lasciagli anche il mantello. Se uno ti costringe a fare un miglio, fanne con lui due. Da' a chi ti chiede, e a chi desidera un prestito da te, non voltar le spalle.<br /> Voi avete udito che fu detto: "Ama il tuo prossimo e odia il tuo nemico". Ma io vi dico: amate i vostri nemici e pregate per quelli che vi perseguitano, affinch&eacute; siate figli del Padre vostro che &egrave; nei cieli; poich&eacute; egli fa levare il suo sole sopra i malvagi e sopra i buoni, e fa piovere sui giusti e sugli ingiusti. Matteo 5:38-45</blockquote>
<p>Perch&eacute; anche il nostro Padre celeste &egrave; buono verso tutti, buoni e cattivi, inclusi noi, e noi dobbiamo essere come lui. Ma ci&ograve; vuol dire che Dio non fa mai la vendetta? Che non ripaga mai il male con il male?</p>
<p>L'opera di Dio &egrave; diversa dalla nostra vendetta. Il Dio perfetto, tre volte santo, deve togliere tutto il male e ogni ingiustizia, deve ripristinare il bene e la giustizia. Altrimenti rinnegherebbe il suo carattere e non sarebbe pi&ugrave; il Dio perfetto dell'intero universo. Spesso ci lascia ottenere quello che vogliamo, cio&egrave; fa ricadere su di noi le nostre scelte, come abbiamo gi&agrave; visto. Ma spesso anche distrugge il male per creare un mondo migliore, e sappiamo che quando Ges&ugrave; ritorner&agrave; ogni ingiustizia sar&agrave; rimossa. Questo &egrave; diverso dalla nostra vendetta, che di solito &egrave; per il nostro benessere personale, per imporre i nostri desideri sugli altri. Dio annienta il male per ripristinare un mondo di giustizia. Quando noi subiamo il male, non dobbiamo fare la vendetta o il male, perch&eacute; non sappiamo rispondere al male rimanendo giusti. Per&ograve; Dio sa cosa fa con il male, e possiamo affidare a lui tutto il male che riceviamo.</p>
<blockquote>Non fate le vostre vendette, miei cari, ma cedete il posto all'ira di Dio; poich&eacute; sta scritto: &laquo;A me la vendetta; io dar&ograve; la retribuzione&raquo;, dice il Signore. Anzi, &laquo;se il tuo nemico ha fame, dagli da mangiare; se ha sete, dagli da bere; poich&eacute;, facendo cos&igrave;, tu radunerai dei carboni accesi sul suo capo&raquo;. Non lasciarti vincere dal male, ma vinci il male con il bene. Romani 12:19-21</blockquote>
<p>La retribuzione non sar&agrave; necessariamente subito, come nel caso di Abimelec e Sichem, in cui Dio aspett&ograve; tre anni prima di far ricadere il male su di loro. Non sar&agrave; necessariamente nei nostri tempi. Perch&eacute; Dio &egrave; paziente per dare a tutti un'opportunit&agrave; per ravvedersi, come &egrave; stato paziente verso di noi. La prima volta che noi abbiamo fatto del male, non siamo stati distrutti subito. Abbiamo la stessa pazienza e lo stesso amore per gli altri che Dio ha avuto verso di noi, affidando a lui tutto il male, affinch&eacute; noi non subiamo il destino di tutto il male del cosmo.</p>

<?
$n=10;
require("indice.php");
require("../../piede.php");
?>

