<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Giudici: Situazione storica e teologica";
$key = "giudici,situazione,storica,teologica";
$titolo = "Situazione storica e teologica (Giudici 1:1-2:9)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Debora, Barac, e Iael (Giudici 4-5)</h1>
<p>Questi due capitoli contengono il racconto del giudice Debora, con gli altri due protagonisti Barac e Iael. Il modo utilizzato per raccontare gli avvenimenti &egrave; particolare. Prima di tutto nel capitolo 4 c'&egrave; un racconto in prosa, come in tutti gli altri capitoli del libro. Ma nel capitolo 5 c'&egrave; un cantico di Debora, che racconta gli stessi avvenimenti in poesia. Un caso simile nella Bibbia &egrave; in Esodo 14-15.</p>
<p>Ci sono alcuni dettagli che sono in Giudici 4 che non sono in Giudici 5, e anche il contrario. Inoltre, il cantico del capitolo 5 usa un linguaggio pi&ugrave; poetico. Per&ograve;, il messaggio principale di ognuno dei capitoli &egrave; uguale: Bisogna rispondere con fede alla chiamata di Dio, e ci sono benedizioni per chi partecipa con Dio alla sua opera.</p>
<p>Leggeremo i due capitoli insieme, in ogni sezione considerando prima il capitolo 4 e poi quello che viene aggiunto dal capitolo 5.</p>
<h2>1. Introduzione (4:1-3; 5:1-5)</h2>
<p>Il capitolo 4 inizia con i primi due passi e mezzo del solito ciclo. Dopo la morte del giudice precedente, Israele si ribella contro Dio facendo ci&ograve; che &egrave; male ai suoi occhi; nella sua ira, Dio li abbandona nelle mani dei Canaan; gli Israeliti gridano al Signore a causa dell'oppressione.</p>
<p>Questa volta, il nemico non era una nazione all'estero che invase Israele, come era il caso con i Moabiti che Eud sconfisse. Piuttosto, erano i Cananei che dovevano essere scacciati ma che invece abitavano in mezzo agli Israeliti, che li opprimevano. Il re di Canaan a quel tempo era Iabin, che regnava da Asor, una citt&agrave; al centro del territorio della trib&ugrave; di Neftali, al nord del paese. Il generale del suo esercito era Sisera, che abitava a Aroset-Goim, che era probabilmente nel territorio di Zabulon, pi&ugrave; al sud.</p>
<p>Questa oppressione dur&ograve; 20 anni prima che gli Israeliti gridassero al Signore - un periodo ancora pi&ugrave; lungo dei 18 anni di servit&ugrave; sotto il re Eglon di Moab. Un motivo per cui i Cananei dominavano sugli Israeliti era che avevano 900 carri di ferro. Siamo nell'anno 1200 a.C. all'incirca, a cavallo fra l'et&agrave; del bronzo e l'et&agrave; del ferro. I Cananei sapevano fabbricare e utilizzare gli attrezzi di ferro (come i carri), ma gli Israeliti ancora no, per cui i carri erano molto pi&ugrave; potenti in battaglia di quello che gli Israeliti potevano usare.</p>
<p>Il capitolo 5, invece, introduce il tema di questo cantico di Debora, che Dio va lodato per il popolo volenteroso di servire Dio, e che Dio stava per agire di nuovo (con un linguaggio poetico che descrive il suo arrivo con potenza dal sud).</p>
<h2>2. Debora e Barac (4:4-9; 5:6-12)</h2>
<p>Di solito nel libro, &egrave; solo dopo che gli Israeliti gridano al Signore che lui suscita per loro un giudice come liberatore. In questi capitoli, ci sono due eccezioni - il ciclo inizia a rompersi. Prima di tutto, c'era gi&agrave; un giudice in quel tempo, Debora, che era anche una profetessa; cio&egrave;, comunicava messaggi da Dio agli Israeliti. Secondo, il giudice non liber&ograve;; invece, dopo le grida degli Israeliti, Dio suscit&ograve; Barac (tramite Debora) a liberarli.</p>
<p>L'altra stranezza &egrave; che Debora era una donna. Abbiamo visto che il mancino Eud era anormale, forse anche disprezzato nella sua cultura. Essere una donna era ovviamente non anormale; essere un capo femminile lo era. Non era n&eacute; impossibile n&eacute; proibito avere una donna come responsabile, solo che era raro, anormale. Inoltre, anche Debora probabilmente era disprezzata o non considerata nella sua cultura perch&eacute; era una donna. Approfondiremo il significato di questi giudici anormali e disprezzati in un capitolo seguente.</p>
<p>Giudici 5:6-8 descrive la situazione disperata quando Debora era giudice (ed anche Samgar di Giudici 3:31). Era troppo rischioso viaggiare per strade, per cui chi doveva spostarsi andava per sentieri pi&ugrave; lunghi. I capi non governavano (per paura di essere sottomessi ai Cananei che regnavano) - almeno, non fino a quando arriv&ograve; Debora che, come una madre, incoraggi&ograve; i capi a compiere le loro responsabilit&agrave;. Spiritualmente, seguivano altri d&egrave;i; militarmente erano sull'orlo della guerra ma non avevano armi (forse non armi utili, cio&egrave; di ferro).</p>
<p>Debora poi, in quanto profetessa, ricord&ograve; Barac che doveva liberare Israele (Giudici 4:6-7). Il modo in cui il discorso di Debora &egrave; riportato ("Il Signore, Dio d'Israele, non ti ha forse dato quest'ordine?") suggerisce che Barac era gi&agrave; stato chiamato e suscitato, ma che non aveva risposta alla chiamata. Debora dunque lo sollecit&ograve;, lo spron&ograve; a fare quello che sapeva gi&agrave; che doveva fare. Cio&egrave;, che Barac, che si trovava a Cades nella parte settentrionale del territorio di Neftali, doveva radunare 10.000 uomini delle trib&ugrave; di Neftali e Zabulon e condurli al monte Tabor, che era nel territorio di Zabulon, vicino a Aroset-Goim dove abitava Sisera. Inoltre, Dio avrebbe attirato verso il torrente Chison (anche nella stessa zona di Zabulon) Sisera con i suoi carri temuti e il suo grande esercito, e Dio li avrebbe dati nelle mani di Barac.</p>
<p>Giudici 5:9-12 aggiunge a questo sollecito a Barac che anche dei condottieri, volontari, e ricchi ("che cavalcate asine bianche") risposero alla chiamata di Dio, e soprattutto benedissero, lodarono, e celebrarono il Signore che aveva risposto alle loro grida, e che molti volevano partecipare a questa opera di Dio di liberazione.</p>
<p>Barac, invece, non era ancora cos&igrave; entusiasta. Rispose alla seconda chiamata che avrebbe ubbidito solo se Debora fosse venuta con lui. La parola del Signore gli doveva bastare, bisognava ubbidire al comando di Dio senza se e senza ma. Ma Barac voleva una garanzia ulteriore, la sicurezza di avere Debora con lui. Un segno fisico della presenza e dell'approvazione da parte di Dio, invece di una fede che agisce con una fiducia quando non c'&egrave; una prova visibile (vedi Ebrei 11:1).</p>
<p>Per questa mancanza di fede e di ubbidienza, Debora rimprover&ograve; Barac. "Va bene, vengo con te, per&ograve; non avrai l'onore che ti doveva spettare per aver compiuto i propositi di Dio." L'onore era una qualit&agrave; importante in quella cultura, e perdere l'onore era una vergogna, un castigo grave. Ma perdere l'onore ad una donna, ritenuta nella cultura meno onorevole di un uomo, avere meno onore di una donna, era gravissimo.</p>
<h2>3. La battaglia (4:10-16; 5:13-23)</h2>
<p>Quindi a Cades ci sono Barac, Debora, e 10.000 uomini delle trib&ugrave; di Zabulon e Neftali (Giudici 4:10). In realt&agrave;, c'erano anche alcuni altri (un residuo) che avevano risposto alla chiamata dei nobili, cio&egrave; Debora e Barac. Naturalmente c'era il Signore, ma anche alcune delle trib&ugrave; di Efraim, Beniamino, Issacar, e dei coraggiosi di Ruben. Dall'altra parte, quelli della regione di Galaad (le trib&ugrave; di Manasse e Gad), e delle trib&ugrave; di Dan e Ascer rimasero a casa per pensare al proprio commercio, mentre Zabulon e Neftali rischiarono la vita (Giudici 5:13-18). A questo punto viene menzionato Eber, un Cheneo, che sar&agrave; importante dopo (Giudici 4:11).</p>
<p>Intanto, Sisera sent&igrave; che Barac era arrivato per combattere, e il generale raccolse il suo esercito, inclusi i carri (Giudici 4:12-13). Barac aveva bisogno di essere incitato da Debora di nuovo, per fare quello che Dio gli aveva comandato di fare, e di essere ricordato che Dio andava davanti a lui (Giudici 4:14). Poi, siccome il Signore era andato davanti a Barac (forse perch&eacute; Barac esitava), era il Signore che sconfisse tutto l'esercito con i carri - il ferro non &egrave; niente davanti al creatore di ogni elemento (Giudici 5:19-22). Barac insegu&igrave; i carri del nemico. Forse Sisera cap&igrave; questo fatto, per cui scese dal suo carro e scapp&ograve; a piedi, convinto di non essere inseguito (Giudici 4:15-16).</p>
<p>La conclusione di questa sezione &egrave; una maledizione (Giudici 5:23). Una maledizione di Meroz. Non si capisce che cosa fosse Meroz, ma in qualche modo rappresentava tutti quelli che non vennero in soccorso del Signore insieme con i prodi, per esempio Galaad, Dan, e Ascer. Non partecipare all'opera di Dio &egrave; una cosa terribile!</p>
<h2>4. Iael (4:17-22; 5:24-30)</h2>
<p>Torniamo a Giudici 4:11 e la storia che lo precede. Mos&egrave; scapp&ograve; da Egitto 40 anni prima dell'esodo, e in quel periodo spos&ograve; Sefora, figlia di Ietro, un Cheneo. Molti Chenei in seguito si unirono al popolo di Israele, e si stabilirono nel territorio di Giuda al sud del paese d'Israele (Giudici 1:16). Un discendente di questa famiglia, Eber, si separ&ograve; dei Chenei e si trasfer&igrave; vicino a Cades nel nord. Inoltre, Eber aveva fatto un accordo di pace con il re Iabin. Quindi mentre Sisera scappava, cerc&ograve; di capire dove poteva andare per rifugiarsi, per nascondersi e riposarsi. Decise di andare da Eber, pensando di essere al sicuro, siccome era un alleato del suo re (Giudici 4:17). Alla tenda di Eber incontr&ograve; Iael, la moglie di Eber, che lo tranquillizz&ograve;. Gli diede un letto per dormire, latte da bere, e promise di fare la guardia e di non dire a nessuno che Sisera era nella tenda (Giudici 4:18-20). Quando Sisera era rilassato e dormiva profondamente, Iael prese un piuolo della tenda e trafisse Sisera, che mor&igrave; (Giudici 4:21).</p>
<p>Quando Barac, che aveva cominciato a seguire Sisera, pass&ograve; la tenda, Iael gli fece vedere il suo nemico steso morto (Giudici 4:22). In questo modo fu adempiuta la parola di Debora, perch&eacute; il Signore aveva dato l'onore a Iael invece di Barac, a causa della sua mancanza di fede (Giudici 4:9). Barac era partito da casa a Cades, fece un giro, e ritorn&ograve; a Cades senza aver fatto molto. Dio sconfisse l'esercito e Iael prese l'onore di aver sconfitto il generale dell'esercito. Per Barac era tutto un giro a vuoto, e cos&igrave; &egrave; per quelli che si ritirano indietro dalla partecipazione all'opera di Dio.</p>
<p>Chi agisce con Dio, invece, &egrave; onorato e commendato, come Iael che &egrave; chiamata benedetta fra le donne (Giudici 5:24-27). Dall'altra parte, le donne dei nemici di Dio, come Sisera, sono confusi e perplessi (Giudici 5:28-30).</p>
<p>Il racconto di Iael &egrave; simile a quello di Eud. Sono tutte e due persone inaspettate (un mancino e una donna), che liberano Israele con un'arma che trafigge il nemico. Tutti e due eseguono un piano basato sull'inganno, sulle bugie, e sugli imbrogli, ma Iael aggiunse alla moralit&agrave; dubbia il tradimento dell'accordo di pace che c'era fra la sua casa e quella del re. Tutti e due realizzarono la volont&agrave; di Dio, e furono approvati e benedetti per averlo fatto. Ma non la realizzarono in un modo che Dio aveva detto di usare n&eacute; che approvava. Anche i liberatori discendono la spirale: il primo dice mezzo bugie, il prossimo dice bugie e tradisce.</p>
<p>Cos&igrave; &egrave; anche spesso per noi. Quando ci rendiamo conto che una mancanza di integrit&agrave; (come una bugia) ci porta qualche beneficio nel breve termine, la nostra anima &egrave; contaminata. C'&egrave; una macchia nera dentro di noi che, come un tumore, inizia a crescere. La prossima volta &egrave; pi&ugrave; facile fare, e pi&ugrave; facile giustificare a noi stessi, qualcosa di peggiore.</p>
<h2>5. Conclusione (4:23-24; 5:31)</h2>
<p>Dio dunque umili&ograve; (il contrario di onorare) Iabin. Gli Israeliti continuarono a attaccare i Cananei fino a quando distrusse il potere di Iabin. Ci&ograve; &egrave; quello che accade a tutti i nemici di Dio. Dopo questa liberazione, Israele ebbe pace per 40 anni, e c'&egrave; la fine di un altro ciclo.</p>
<h2>Riflessioni</h2>
<p>Un insegnamento importante di questi capitoli e su cui possiamo riflettere &egrave;:</p>
<blockquote>Non importa chi siamo, dobbiamo essere fedeli risolutamente, senza paura.</blockquote>
<p>Essere fedeli vuol dire, fra l'altro, essere integri e coerenti quando serviamo il Dio santo. Dobbiamo essere fedeli al suo carattere di verit&agrave; e amore, mentre siamo fedeli compiendo la sua volont&agrave;.</p>
<p>Poi, dobbiamo essere fedeli nonostante chi siamo. I mancini che leggono questo testo probabilmente non si sentono disprezzati ed emarginati, ma al tempo dei giudici s&igrave;. Il racconto di Eud ci insegna che Dio pu&ograve; usare addirittura i mancini, se sono disposti a impegnarsi per lui.</p>
<p>Le donne che leggono questo testo forse si sentono disprezzate ed emarginate. Meno che nel passato, ma sono ancora considerate inferiori in alcuni modi nel presente. I racconti di Debora e Iael ci insegnano che Dio usa le donne, se sono disposte a impegnarsi per lui.</p>
<p>Gli stranieri che leggono questo testo forse si sentono disprezzati ed emarginati nella societ&agrave;. Forse anche nella chiesa. I racconti di Samgar e Iael ci insegnano che Dio usa gli stranieri, quelli nella periferia del suo popolo, se sono disposti a impegnarsi, a mettersi in gioco nonostante quello che la societ&agrave; pensa di loro.</p>
<p>Il problema non deve essere quello che gli altri pensano di noi, ma spesso il problema &egrave; quello che noi pensiamo di Dio. Non dobbiamo avere paura di come gli altri ci considerano, ma dobbiamo essere fedeli risolutamente, senza paura dei giudizi degli altri. Quando invece spesso abbiamo paura senza fede.</p>
<p>Abbiamo un esempio negativo di questa paura senza fede in Barac. Sapeva quello che doveva fare, sapeva l'ordine del Signore, ma ben due volte doveva essere spronato da Debora per farlo (Giudici 4:6,15). Barac cerc&ograve; una garanzia, una prova tangibile della presenza e della promessa di Dio (cio&egrave; Debora) prima di agire. Questo &egrave; agire senza fede, e perse l'onore. Sotto questo aspetto, vedremo un'altra spirale in discesa negli altri liberatori. Gedeone e Iefte erano sempre meno disposti a ubbidire, a rischiare per Dio con fede nelle promesse di Dio, senza ulteriori garanzie da parte di Dio. Infine, a Sansone non interessava affatto fare quello che Dio intendeva.</p>
<p>Certo, possiamo esagerare quando agiamo risolutamente per Dio, e fare quello che noi riteniamo meglio nel modo che ci sta bene, come fece Eud. Non dobbiamo esitare a seguire Dio, ma non dobbiamo neanche andare davanti a Dio.</p>

<p>Questo brano insegna anche che chi &egrave; fedele risolutamente, chi partecipa all'opera di Dio, &egrave; onorato e benedetto (Iael, le trib&ugrave; che si unirono all'esercito di Israele), mentre chi non partecipa non lo &egrave; (Barac, le trib&ugrave; che rimasero a casa). Possiamo vedere questa conseguenza anche nella nostra vita.</p>
<p>Quando abbiamo delle opportunit&agrave; per testimoniare delle grandi cose che Dio ha fatto per noi, a volte rimaniamo bloccati per paura della reazione della persona con cui parliamo, o per paura di esporci. Cos&igrave; facendo, perdiamo la benedizione di glorificare Dio e di vedere persone che ricevono la vita eterna.</p>
<p>Pi&ugrave; che siamo coinvolti nelle attivit&agrave; della chiesa - culti, studi biblici, riunioni di preghiera, comunione fraterna, e cos&igrave; vita, pi&ugrave; siamo benedetti in quello che possiamo ricevere dagli altri, e da Dio attraverso i nostri fratelli e sorelle. Pi&ugrave; siamo benedetti in quello che possiamo dare agli altri.</p>
<p>Anche quando vediamo i bisognosi, &egrave; facile passare oltre dal lato opposto per non aiutare. Seguire Dio fedelmente e risolutamente vuol dire non chiedersi, "Posso aiutare? Non sono troppi? Cosa penseranno gli amici se frequento i bisognosi? Lui merita di essere aiutato?", ma affermare, "Dio vuole; lo far&ograve; sapendo che Dio mi aiuter&agrave; e benedir&agrave; me e l'altro".</p>
<p>Certo, abbiamo tutti tanti impegni, nessuno pu&ograve; fare tutto. Non &egrave; una nuova legge da osservare, non sono nuove opere obbligatorie per chi vuole essere accettato da Dio. Quello di cui abbiamo bisogno invece &egrave; Ges&ugrave; Cristo.</p>
<p>Prima di tutto, se non siamo stati fedeli risolutamente nel passato, dobbiamo ricordarci che, se siamo in Cristo, siamo sulla spirale in salita. Siamo mancanti, ma non senza speranza. I nostri sbagli devono portarci al dispiacere ma non alla disperazione. Sono un'opportunit&agrave; per crescere con il potere trasformatore di Ges&ugrave; e verso la perfezione di Ges&ugrave;. Sono anche un'opportunit&agrave; per scendere, se lasciamo questa macchia nera crescere invece di chiedere a Ges&ugrave; tramite lo Spirito Santo che abita in noi di eliminarla.</p>
<p>Inoltre, Ges&ugrave; &egrave; un esempio migliore per noi di Barac, Iael, Debora, e gli altri giudici. In Ebrei 10:5-10 leggiamo questa citazione e riflessione sul Salmo 40:</p>
<blockquote>Ecco perch&eacute; Cristo, entrando nel mondo, disse:<br />
<i>&laquo;Tu non hai voluto n&eacute; sacrificio n&eacute; offerta</i><br />
ma mi hai preparato un corpo;<br />
<i>non hai gradito n&eacute; olocausti n&eacute; sacrifici per il peccato.<br />
Allora ho detto: "Ecco, vengo"</i><br />
(nel rotolo del libro &egrave; scritto di me)<br />
<i>"per fare, o Dio, la tua volont&agrave;"&raquo;.</i><br />
Dopo aver detto:<br />
<i>&laquo;Tu non hai voluto e non hai gradito n&eacute; sacrifici, n&eacute; offerte,<br />
n&eacute; olocausti, n&eacute; sacrifici per il peccato&raquo;</i><br />
(che sono offerti secondo la legge), aggiunge poi:<br />
<i>&laquo;Ecco, vengo per fare la tua volont&agrave;&raquo;.</i><br />
Cos&igrave; egli abolisce il primo per stabilire il secondo. In virt&ugrave; di questa &laquo;volont&agrave;&raquo; noi siamo stati santificati, mediante l'offerta del corpo di Ges&ugrave; Cristo fatta una volta per sempre.</blockquote>
<p>Il modo giusto di seguire Dio non &egrave; pi&ugrave; tramite i sacrifici, neanche quello a cui possiamo rinunciare per Dio, n&eacute; sperando di avere il contraccambio di Dio. Il modo giusto di seguire Dio non &egrave; osservare qualche legge con un elenco di cose da fare e non fare. Il modo giusto di seguire Dio &egrave; fare la sua volont&agrave;. Essere fedeli risolutamente e senza paura, per fare quello che Dio ci chiede di fare.</p>
<p>Potremmo avere paura delle circostanze e delle conseguenze della nostra fedelt&agrave; e ubbidienza. Anche in questo Ges&ugrave; Cristo &egrave; il nostro esempio. Nella notte prima di morire, dopo essere tradito da un amico, nel giardino di Getsemani, leggiamo in Marco 14:33-36:</p>
<blockquote>Ges&ugrave; prese con s&eacute; Pietro, Giacomo, Giovanni e cominci&ograve; a essere spaventato e angosciato. E disse loro: &laquo;L'anima mia &egrave; oppressa da tristezza mortale; rimanete qui e vegliate&raquo;. Andato un po' pi&ugrave; avanti, si gett&ograve; a terra; e pregava che, se fosse possibile, quell'ora passasse oltre da lui. Diceva: &laquo;Abb&agrave;, Padre! Ogni cosa ti &egrave; possibile; allontana da me questo calice! Per&ograve;, non quello che io voglio, ma quello che tu vuoi&raquo;.</blockquote>
<p>Ges&ugrave; era spaventato, angosciato, e molto triste. Per&ograve; non lasci&ograve; quello che gli altri pensavano n&eacute; quello che lui stesso si sentiva determinare le sue azioni. Non aveva paura del proprio spavento! Invece risolutamente, con fede, preg&ograve;, "Non quello che io voglio, ma quello che tu vuoi". In virt&ugrave; di questo sacrificio di s&eacute; da parte di Ges&ugrave; Cristo, del suo corpo offerto una volta per sempre; in virt&ugrave; di questa volont&agrave; di Dio che Ges&ugrave; segu&igrave; costi quello che costi, noi siamo santificati, cio&egrave; siamo resi sempre un po' pi&ugrave; santi e saliamo la spirale ogni volta che torniamo alla morte di Ges&ugrave; sulla croce per essere perdonati e trasformati.</p>

<?
$n=6;
require("indice.php");
require("../../piede.php");
?>

