<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Giudici: Situazione storica e teologica";
$key = "giudici,situazione,storica,teologica";
$titolo = "Situazione storica e teologica (Giudici 1:1-2:9)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Eud e Samgar (Giudici 3:12-31)</h1>
<p>Siccome io sono mancino, Eud &egrave; sempre stato il mio giudice preferito. Eud &egrave; anche il primo dei cinque giudici principali, in quanto c'&egrave; un racconto relativamente lungo delle sue azioni. Samgar invece &egrave; uno dei sette giudici minori, il suo racconto &egrave; composto da un versetto solo. I due giudici sono comunque collegati dal fatto che vediamo l'inizio delle imperfezioni e delle mancanze che caratterizzano la discesa della spirale. Permane qualche perplessit&agrave; per tutti e due.</p>
<h2>1. La retroscena (3:12-14)</h2>
<p>Nei primi versetti del racconto di Eud, abbiamo il solito ciclo di Giudici 2:11-18. Dopo i 40 anni di pace quando Otniel era giudici (Giudici 3:11), gli Israeliti continuarono a fare ci&ograve; che &egrave; male agli occhi del Signore, quindi Dio li abbandon&ograve; e suscit&ograve; Eglon contro di loro (Giudici 3:12). I Moabiti erano i discendenti di Moab, uno dei figli di Lot il nipote di Abraamo, che abitavano nel paese accanto a quello degli Israeliti, ad est del fiume Giordano. Eglon radun&ograve; anche gli Ammoniti e Amalechiti affinch&eacute; combattessero con lui (Giudici 3:13). Gli Ammoniti erano i discendenti dell'altro figlio di Lot, mentre gli Amalechiti erano i discendenti di uno dei nipoti di Esa&ugrave;, figlio di Isacco. Tutte e tre queste nazioni si erano opposte agli Israeliti mentre passavano dall'Egitto alla terra promessa, ed erano spesso i nemici di Israele. In questo caso, sconfissero gli Israeliti e si impadronirono della citt&agrave; delle palme, cio&egrave; Gerico (Giudici 3:13). Gerico era poco a ovest del fiume Giordano, ed era la prima citt&agrave; che gli Israeliti catturarono quando entrarono nel paese - era diventata la citt&agrave; degli oppressori di Israele piuttosto di essere un simbolo della conquista e il possesso del paese da parte degli Israeliti.</p>
<p>Poi gli Israeliti rimasero servi degli invasori per ben 18 anni, che sono tanti (Giudici 3:14).</p>
<h2>2. La chiamata (3:15a)</h2>
<p>Dopo 18 anni, gli Israeliti gridarono a Dio per avere sollievo dalla sofferenza, per essere liberati. Dopo 18 anni, che sono tanti. Perch&eacute; non prima?</p>
<p>Era un segno di quanto lontano, quanto era separato Israele da Dio. Non voleva proprio chiedere aiuto, perch&eacute; sarebbe stata un'ammissione di torto, che si erano ribellati contro il giusto Dio e che la loro unica speranza era colui che avevano respinto.</p>
<p>Anche noi spesso ci comportiamo cos&igrave;. Non tutti i nostri problemi sono a causa del nostro peccato, come &egrave; il caso in questo capitolo. Tuttavia, succede a volte che viviamo con i nostri problemi e difficolt&agrave;. Li sopportiamo, con frasi come "cos&igrave; &egrave; la vita", "capita a tutti", o "poteva andare peggio". Poi quando sono troppo forti, cerchiamo qualche soluzione. Proviamo a fare il nostro meglio per uscire dalle difficolt&agrave;. Poi quando non resistiamo pi&ugrave;, quando non ce la facciamo pi&ugrave;, quando non troviamo nessun modo per uscirne, poi gridiamo a Dio per aiuto.</p>
<p>&Egrave; un esempio banale in confronto con 18 anni di servit&ugrave;, ma quando sono raffreddato, di solito all'inizio non faccio niente. Penso che non sia niente, che sia solo un mal di stagione, che passer&agrave;. Se i sintomi peggiorano, potrei prendere una bustina o una pillola per avere sollievo. Se peggiorano ancora io sono <i>veramente</i> disperato, andr&ograve; dal medico. Solo quando &egrave; l'ultima spiaggia, prego e chiedo ad altri di pregare per la mia salute. Credo che quasi tutti noi preghiamo per le malattie gravi, ma molto di meno per quelle leggere.</p>
<p>Quando gli Israeliti decisero finalmente di chiedere aiuto al Signore, Dio rispose facendo sorgere per loro un liberatore, Eud. Ci viene detto subito due cose di Eud. Prima di tutto, era della trib&ugrave; di Beniamino. Gerico faceva parte del territorio di quella trib&ugrave;, per cui era naturale che il liberatore di Gerico fosse di quella trib&ugrave;. Secondo, era mancino. Potrebbe sembrare a noi un dettaglio insignificante, ma era un fatto importante non solo per il racconto storico, ma anche per l'insegnamento teologico del brano e, infatti, dell'intero libro.</p>
<h2>3. Il primo incontro (3:15b-18)</h2>
<p>Gli Israeliti mandarono Eud dal re Eglon con un regalo. Non dobbiamo pensare che fosse un regalo perch&eacute; lo volessero bene, come un regalo per il compleanno. Era un regalo imposto, cio&egrave; un tributo, una tassa che i conquistati dovevano pagare agli stranieri conquistatori. Probabilmente era un tributo di prodotti agricoli, siccome era normale in quel periodo. Ci sarebbe stato tanto cibo per sostenere gli oppressori, per cui Eud era venuto con tante persone per portare il tributo, che furono rimandate a casa dopo averlo portato (Giudici 3:18).</p>
<p>Intanto, Eud gi&agrave; progettava quello che avrebbe fatto dal re, e fabbric&ograve; una spada lunga circa 30 centimetri (Giudici 3:16). Nascose la spada sotto i vestiti, al fianco destro. Probabilmente era nella parte interna della coscia destra, da dove era facile ritirare con la mano sinistra ma non con la mano destra. Forse quando entr&ograve; nel palazzo del re, controll&ograve; Eud per armi, ma controll&ograve; solo l'esterno della gamba destra o il lato sinistro del corpo, dove si teneva di solito la spada affinch&eacute; fosse facilmente accessibile con la mano destra.</p>
<p>L'altro dettaglio da notare in questa sezione era che Eglon era molto grasso (Giudici 3:17), un fatto che sar&agrave; rilevante per il racconto pi&ugrave; avanti.</p>
<h2>4. Il secondo incontro (3:19-22)</h2>
<p>Dopo aver lasciato il palazzo e rimandato i compagni, quando Eud arriv&ograve; a Ghilgal torn&ograve; indietro a Gerico. Ghilgal era tra Gerico e il fiume Giordano, e viene descritto come un luogo di idoli. Questo fatto in s&eacute; accusa la fede di Israele - perch&eacute; avevano lasciato degli idoli l&agrave;? Era infatti un posto speciale per gli Israeliti. Era il primo accampamento di Israele dopo aver attraversato il Giordano e prima di catturare Gerico. Giosu&egrave; fece rizzare dodici pietre a Ghilgal per ricordare l'opera miracolosa di Dio che permise loro di passare oltre il fiume (Giosu&egrave; 4:19-22). Possibilmente le pietre, collocate per ricordare chi dovevano adorare e perch&eacute;, erano diventate l'oggetto di adorazione, cio&egrave; degli idoli. Non sarebbe stata la prima volta nella Bibbia che un oggetto per ricordare era diventato un idolo da adorare (per esempio il serpente di bronzo Numeri 21:8-9; 2Re 18:4), ed &egrave; anche successo tante volte nella storia della chiesa cristiana. Anche se non erano le pietre che erano gli idoli, il fatto che gli idoli erano nella stessa zona delle pietre voleva dire che quello che le pietre rappresentavano ormai contava poco agli Israeliti.</p>
<p>Arrivato dal re, Eud gli disse di avere un messaggio segreto da dirgli, per cui tutti gli altri presenti uscirono dalla stanza (Giudici 3:19). Poi Eud gli disse di avere un messaggio da Dio, che incurios&igrave; Eglon ancora di pi&ugrave;. Il re si alz&ograve; con tutto il suo grasso per sentire meglio questo messaggio segreto divino, e Eud si avvicin&ograve;, presumibilmente con la mano destra stesa avanti per mostrare che non poteva fare male al re (Giudici 3:20). Per&ograve;, quando Eud era accanto a Eglon, con un movimento rapido e letale estrasse la spada dalla coscia destra e trafisse il re (Giudici 3:21). Il re era cos&igrave; grasso che tutta la spada entr&ograve; nella sua pancia, e Eud la lasci&ograve; l&igrave; (Giudici 3:22).</p>
<p>C'&egrave; un dubbio nella traduzione dell'ultima parte del versetto 22, cio&egrave; cosa usc&igrave; da dietro: per esempio la Nuova Riveduta dice la spada usc&igrave; da dietro di Eglon; la C.E.I. dice che Eud usc&igrave; dalla finestra (cio&egrave;, dalla parte anteriore della stanza); la Nuova Diodati dice che gli intestini (altre versioni gli escrementi) uscirono da dietro del corpo.</p>
<h2>5. La fuga (3:23-26)</h2>
<p>Eud scapp&ograve;, in quello che sembra una scena di un film d'azione o di spionaggio. Silenziosamente chiuse a chiave da dentro la porta di questa sala privata del re, poi and&ograve; dall'altra parte dove usc&igrave; da una finestra o simile, poi si mosse attraverso il palazzo e sui tetti, assicurando di non essere visto, e poi lasci&ograve; la citt&agrave; furtivamente.</p>
<p>Dall'altra parte della porta, sembra di pi&ugrave; una scena di un film comico, una farsa. Chiacchierano insieme per un po' di tempo, e poi qualcuno dice, "Sono l&igrave; dentro da tanto tempo! Forse dovremmo controllare..." Ma non vogliono interrompere il re nel caso che ci siano trattative segrete importanti, dopotutto sono stati mandati fuori. Aspettano ancora un po', qualcun altro pensa che dovrebbero controllare, poi un'altra persona. Tentativamente provano la porta, ma scoprono che &egrave; chiusa a chiave. Meglio aspettare ancora! Inoltre, se la traduzione giusta di Giudici 3:22 &egrave; che gli intestini sono usciti, a questo punto c'&egrave; una puzza tremenda. In ogni caso quelli fuori commentano che senz'altro il re &egrave; andato in bagno. Se nessuno voleva essere il primo a entrare quando non chiamato e possibilmente interrompere importanti affari di stato, senz'altro nessuno si offre per disturbare il re mentre &egrave; in bagno. Aspettano ancora, fino a quando cominciano a preoccuparsi (o forse meglio come traduzione, ad essere confusi). Finalmente prendono coraggio, trovano la chiave, aprono la porta solo un pochino per dare un'occhiata alla stanza... e vedono il re morto, stesso in una pozzanghera del proprio sangue e escrementi.</p>
<p>Tutto questo indugio diede a Eud il tempo necessario di fuggire, arrivando a Seira, una citt&agrave; oltre Ghilgal (Giudici 3:26).</p>
<h2>6. La liberazione (3:27-30)</h2>
<p>Ora che il re era morto, Eud era pronto per attaccare. Radun&ograve; gli Israeliti, e Eud li condusse in battaglia. Promise che il Signore avrebbe dato la vittoria sui loro nemici, i Moabiti, e non solo li sconfissero, ma bloccarono anche l'unica strada per ritornare nel loro paese Moab, cio&egrave; i guadi del fiume Giordano che separava Moab da Israele, in modo che non avessero via di scampo. Quindi Moab era sconfitto e umiliato, gli Israeliti non erano pi&ugrave; servi, oppressi, e umiliati, e Israele era liberato e aveva pace per 80 anni.</p>
<h2>7. Samgar (3:31)</h2>
<p>La vita e le azioni di Samgar sono descritte in un solo versetto, ma ci sono alcune cose che possiamo dire di lui. Era un contemporaneo del giudice Debora (Giudici 5:6), e infatti tutti e due liberarono Israele dopo la morte di Eud (Giudici 3:31; 4:1), Samgar nel sudovest contro i Filistei, Debora nel nord contro i Cananei. In realt&agrave;, Debora era un giudice che non liber&ograve; (Debora chiam&ograve; Barac per liberare Israele, come vedremo nel prossimo capitolo), mentre Samgar liber&ograve; ma non era chiamato un giudice. Anche gli altri giudici con solo un versetto nel libro sono chiamati giudici. Qualche imperfezione nei racconti dei giudici inizia a apparire.</p>
<p>Un'altra peculiarit&agrave; di Samgar era la sua arma: era un pungolo da buoi. Era un bastone appuntito di uno o due metri, utilizzati per spingere i buoi e costringerli a andare dove si voleva. Era un'arma strana per combattere e sconfiggere 600 Filistei! (Non necessariamente tutti nella stessa battaglia, ma era comunque un'impresa.) Non era il tipico soldato esperto ben attrezzato che vorremmo mandare in battaglia per liberarci.</p>
<p>Ancora pi&ugrave; strano &egrave; il suo nome, Samgar, figlio di Anat. Anat era il nome di una dea importante dei Cananei, la moglie del dio principale Baal. Forse "figlio di Anat" era un titolo, forse il nome del padre cananeo, ma in ogni caso Samgar era collegato con i Cananei in qualche modo, quelli che dovevano essere espulsi dal paese, e che in quel tempo opprimevano gli Israeliti al nord. Inoltre, Samgar non era un nome ebraico. Samgar era un Cananeo o mezzo Cananeo, e che liber&ograve; Israele dai Filistei.</p>
<p>Dio pu&ograve; usare chi non &egrave; un seguace perfetto per i suoi propositi. Pu&ograve; usare persone che non ci saremmo aspettati, come Samgar, e mezzi che non ci saremmo aspettati, come un pungolo da buoi. Anzi, spesso Dio preferisce usare tali persone e mezzi. Ritorneremo a questo punto nella conclusione, e ritorneremo spesso nei seguenti capitoli, perch&eacute; &egrave; un tema importante del libro dei Giudici, e una caratteristica fondamentale per il modo in cui Dio ha operato e opera ancora nel mondo.</p>
<h2>8. Conclusione</h2>
<p>Ho gi&agrave; fatto alcune riflessioni a diversi punti di questo capitolo, ma ne voglio approfondire due per riassumere l'insegnamento del capitolo, e dell'intero libro, per noi.</p>
<h3>a) Mancino</h3>
<p>Il fatto che Eud era mancino era ovviamente essenziale per il racconto storico, siccome era il suo modo per superare i controlli e uccidere Eglon. Ma era anche importante teologicamente.</p>
<p>In molte culture antiche, come pure in alcune culture adesso, essere mancino era considerato quasi come un difetto fisico, e i mancini dovevano usare invece la destra. C'era in parte un motivo pratico per questo, di igiene: la mano sinistra era usata per pulirsi, mentre la mano destra era usata per mangiare. Mai mettere la mano sporca in bocca! Tuttavia, non era permesso per un mancino pulirsi con la destra e mangiare con la sinistra. Anche in Italia fino a qualche decennio fa molti mancini erano costretti a usare la mano destra per scrivere, perch&eacute; la sinistra era ritenuta anormale, sconveniente. Questo pregiudizio &egrave; rimasto nella lingua italiana: la mano sinistra &egrave; quella sinistra, cio&egrave; malvagia. Anche in inglese c'&egrave; un pregiudizio linguistico: la parola "right" vuol dire sia destro sia giusto, per cui la mano destra &egrave; quella giusta.</p>
<p>Similmente essere mancino in Israele al tempo dei giudici era sicuramente anormale, se non addirittura ignobile e disprezzato. Ma di tutti gli Israeliti, Dio scelse per liberare il suo popolo un ignobile, un disprezzato, un debole agli occhi degli altri. Poi Dio scelse uno straniero con un pungolo da buoi. Non qualcuno che era popolare e ammirato, il guerriero perfetto agli occhi del popolo. Dio scelse Eud e Samgar per insegnare agli Israeliti e anche a noi che lui salva nel suo modo, non nel nostro. Che sceglie non i bravi secondo il mondo, ma quelli senza l'onore del mondo. Questo tema sar&agrave; approfondito nei seguenti capitoli, dove vedremo Dio scegliere altri disprezzati come giudici. Come tutti i temi e insegnamenti nella Bibbia, giunge al suo adempimento in Ges&ugrave; Cristo, che non era il tipo di liberatore aspettato (n&eacute; dagli Ebrei di allora n&eacute; da noi), ma era un uomo disprezzato, e ci ha salvati nonostante questo disprezzo per vergognare i forti e sapienti.</p> 
<h3>b) L'opera di Dio e l'opera dell'uomo</h3>
<p>Solo due volte &egrave; scritto che Dio fa qualcosa: rese forte Eglon (Giudici 3:12) e fece sorgere Israele un liberatore (Giudici 3:15). Da questi due esempi, si capisce che Dio usa non solo il suo popolo ma anche i malvagi, i nemici del suo popolo, per eseguire i suoi propositi.</p>
<p>Inoltre, Eud afferm&ograve; due altre volte che Dio agiva: che aveva un messaggio per il re (Giudici 3:20) e che aveva dato i Moabiti nelle mani degli Israeliti (Giudici 3:28). La seconda affermazione era vera, ma non &egrave; detta esplicitamente da Dio o dall'autore del libro come era il caso con Otniel (Giudici 3:10). La prima affermazione, invece, probabilmente non era neanche vera. Dal racconto non sembra che Dio avesse una parte nel piano di Eud. </p>
<p>Infatti, il piano di Eud mi mette un po' a disagio. Il piano si basa sull'inganno, sulla mezza bugia di aver un messaggio da Dio. Il Signore non sembra presente quando il piano viene eseguito, dipende piuttosto dall'astuzia di Eud. Inoltre, Eud non fa niente con gli idoli di Ghilgal, che erano un'offesa a Dio. Certo, non era il momento di pensare agli idoli mentre presentava il regalo o era in fuga, ma l'autore afferma che gli idoli erano ancora a Ghilgal quando il libro &egrave; stato scritto, per cui Eud non li tolse neanche dopo la battaglia, durante gli ottant'anni di pace.</p>
<p>In altre parole, Eud non &egrave; un Otniel. Non esegue perfettamente la volont&agrave; di Dio, ma gli manca un po' di coerenza e integrit&agrave; in quello che fa per Dio.</p>
<p>Dall'altra parte, quando Dio fece Eud come liberatore, ag&igrave; senza cercare ulteriori promesse o garanzie da Dio, come fecero gli altri liberatori maggiori (Barac, Gedeone, Iefte). Questa caratteristica sar&agrave; approfondita nel prossimo capitolo.</p>
<p>Quindi Eud cadde un po' dalla perfezione, ma non molto. Inizi&ograve; la discesa della spirale. Dopo questo giro, Israele e i giudici non ritornarono al punto di partenza, ma ad un punto pi&ugrave; basso, leggermente peggiorati in confronto con l'inizio.</p>
<p>Tutto questo &egrave; simultaneamente una sfida e un incoraggiamento per noi.</p>
<p>Una sfida, perch&eacute; per servire il Signore ci vuole l'integrit&agrave;. Anche i piccoli errori di mezze bugie, procedere con i propri piani, e di non pregare, sono i primi passi della discesa. Continuando quella strada di un'imperfetta integrit&agrave; possiamo solo peggiorare.</p>
<p>Un incoraggiamento, perch&eacute; Dio pu&ograve; servirci di noi per eseguire i suoi propositi nonostante le nostre imperfezioni. L'inganno non &egrave; approvato da Dio, ma nonostante la nostra incoerenza e debolezza, Dio pu&ograve; fare grandi cose attraverso noi. Cos&igrave; la gloria va a Dio e non alla nostra astuzia.</p>
<p>Siccome questa &egrave; la prima volta che leggiamo di un giudice imperfetto e anormale, concludiamo con Ebrei 11:32-33,39-40:</p>
<blockquote>Che dir&ograve; di pi&ugrave;? Poich&eacute; il tempo mi mancherebbe per raccontare di Gedeone, Barac, Sansone, Iefte, Davide, Samuele e dei profeti, i quali per fede conquistarono regni, praticarono la giustizia, ottennero l'adempimento di promesse... Tutti costoro, pur avendo avuto buona testimonianza per la loro fede, non ottennero ci&ograve; che era stato promesso; perch&eacute; Dio aveva in vista per noi qualcosa di meglio, in modo che loro non giungessero alla perfezione senza di noi.</blockquote> 
<p>Oltre agli altri quattro liberatori del libro dei Giudici che sono elencati, possiamo aggiungere Eud, che conquist&ograve; un regno e ottenne l'adempimento di promesse. Ma Eud, come gli altri, non era perfetto, e noi abbiamo qualcosa di meglio. Noi possiamo giungere alla perfezione (insieme con i fedeli dell'Antico Testamento) attraverso Ges&ugrave; Cristo, in cui non &egrave; stato trovato nessun inganno, che &egrave; stato disprezzato pi&ugrave; di un mancino, e che con un'arma ancora pi&ugrave; inutile di un pungolo da buoi (cio&egrave;, una croce di legno) ha conquistato il regno diabolico dell'inferno e ci ha liberati dal potere del peccato, affinch&eacute; possiamo iniziare a salire la spirale per giungere alla perfezione.</p>

<?
$n=5;
require("indice.php");
require("../../piede.php");
?>

