<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 3]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 3]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Gedeone [parte 3] (Giudici 8)</h1>
<p>Dopo che Dio vinse la non battaglia contro Madian, era ancora necessaria qualche operazione militare contro il resto dell'esercito e contro i capi, che cercarono di fuggire e ritornare al loro paese. Gedeone li insegu&igrave; e chiam&ograve; in aiuto alcuni altri Israeliti. Cos&igrave; vedremo la risposta della trib&ugrave; di Efraim, delle citt&agrave; di Succot e Penuel, e di suo figlio Ieter, e come Gedeone li tratt&ograve;. Similmente a quello che abbiamo letto nelle altre due parti su Gedeone, scopriremo sia del bene sia del male in Gedeone, come ci aspetteremmo dal giudice che &egrave; a met&agrave; strada fra il giudice esemplare Otniel e il pessimo giudice Sansone. Per questo motivo, Gedeone &egrave; un esempio per noi sia da seguire sia da evitare, ma in ogni caso ci porta verso Ges&ugrave; Cristo che perfeziona le caratteristiche positive e corregge le caratteristiche negative.</p>
<h2>1. Efraim (7:24-8:3)</h2>
<p>Dopo la non battaglia, la trib&ugrave; di Efraim fu convocata per tagliare la strada del ritiro. Riuscirono a catturare e uccidere due principi o capi di Madian, Oreb e Zeeb. Non erano i re di Madian, perch&eacute; scopriremo il loro destino nella prossima sezione.</p>
<p>Come reagirono gli Efraimiti a questa convocazione per partecipare alla liberazione di Israele? Con gratitudine per la salvezza che Dio comp&igrave; tramite Gedeone? Con riconoscenza che anche loro avevano potuto prendere parte all'opera di Dio? No, con ingratitudine e con rancore e con ira. Per la grande battaglia, Gedeone aveva convocato solo le trib&ugrave; di Ascer, Zabulon, e Neftali, e la sua famiglia degli Abiezeriti della trib&ugrave; di Manasse. Gli Efraimiti volevano essere convocati per questa battaglia, non solo per sistemare tutto dopo la parte pi&ugrave; importante. Probabilmente si sentivano disonorati, perch&eacute; non avevano potuto prendere parte alla battaglia che li avrebbe resi famosi e onorati. Sarebbe come organizzare un gran evento in chiesa, in cui molti (altri) predicano e testimoniano e cantano, in cui quelli che assistono all'evento si sentono veramente toccati dalla Parola di Dio... e poi, dopo tutto &egrave; finito, ti chiedono di sistemare le sedie e di pulire per terra. Non ti hanno chiesto di compiere un ruolo visibile, non ti hanno chiesto di servire Dio pubblicamente. Un po' di rancore sarebbe possibile.</p>
<p>Gedeone risponde agli Efraimiti in modo diplomatico, esaltando il loro successo e abbassando il suo. La loro racimolatura (cio&egrave;, la raccolta di quello che &egrave; rimasto dopo la vendemmia) non valeva pi&ugrave; della vendemmia degli Abiezeriti, cio&egrave; di Gedeone e della sua famiglia? Perch&eacute; Dio aveva dato agli Efraimiti i principi Oreb e Zeeb, e avevano servito Dio bene in quello che era stato loro da fare per lui. Gedeone li rassicur&ograve; che valeva pi&ugrave; di quello che lui aveva fatto, che forse esagerava per tranquillizzare le anime.</p>
<p>Per&ograve;, il principio che sta dietro l'affermazione &egrave; giusto. Non dobbiamo misurarci e valutarci in confronto con gli altri. Non dobbiamo paragone il compito che Dio ci ha dato con il compito che Dio ha dato agli altri. Non dobbiamo avere ingratitudine, rancore, o ira perch&eacute; a qualcuno &egrave; chiesto di fare qualcosa e a noi no, in chiesa o al posto di lavoro o altrove. Dobbiamo essere riconoscenti per quello che Dio ci ha dato da fare, e impegnarci fedelmente in quello. Dall'altro punto di vista, non dobbiamo essere orgogliosi pensando di essere migliori degli altri solo perch&eacute; facciamo di pi&ugrave;. In questo modo dobbiamo essere come Gedeone, che esalta l'opera e il servizio degli altri, perch&eacute; in realt&agrave; spostare le sedie e pulire &egrave; onorevole quanto parlare o cantare in pubblico. Dobbiamo non fare nulla per vanagloria, ma con umilt&agrave; stimare gli altri superiori (Fili 2:3), come fece Gedeone, perch&eacute; cos&igrave; abbiamo lo stesso sentimento che &egrave; stato anche in Cristo Ges&ugrave; che, pur essendo in forma di Dio, non consider&ograve; l'essere uguale a Dio qualcosa a cui aggrapparsi gelosamente, ma svuot&ograve; se stesso, prendendo forma di servo, divenendo simile agli uomini; trovato esteriormente come un uomo, umili&ograve; se stesso, facendosi ubbidiente fino alla morte, e alla morte di croce (Fili 2:5-8).</p>
<h2>2. Succot e Penuel (8:4-17)</h2>
<p>Gli abitanti di Succot e Penuel hanno paura di mettersi in gioco. Una paura comprensibile, perch&eacute; qualsiasi decisione che prendono li espone a un grosso rischio. Se aiutano Gedeone e il suo esercito, ma loro vengono sconfitti dai Madianiti, i Madianiti verranno a punire le due citt&agrave;. Ma se non aiutano Gedeone, Gedeone ritorner&agrave; per punirle. Non potevano rimanere neutri. Per forza dovevano scegliere da quale parte stare, e sperare che sarebbe risultato la scelta vincente.</p>
<p>Per&ograve;, dovevano sapere quale era la parte vincente. Dovevano decidere se credere che avrebbe vinto il Dio Creatore dell'intero universo, che aveva scelto Israele come suo tesoro particolare, oppure un dio inventato da Madian, costruito di legno, un idolo. Oltre ad una paura di mettersi in gioco, di sbilanciarsi da una parte o l'altra, era un atto in incredulit&agrave; da Succot e Penuel, che non credevano che Dio avrebbe completato la vittoria e la liberazione che aveva gi&agrave; ottenuto.</p>
<p>Un po' come noi a volte. Quando si presentano delle opportunit&agrave; di testimoniare a qualcuno, abbiamo la scelta di proclamare le virt&ugrave; di colui che ci ha salvati e rischiare una brutta reazione, il disprezzo, essere presi in giro, o l'allontanamento; oppure possiamo stare zitti e continuare come prima. La seconda scelta &egrave; la paura di mettersi in gioco, di far capire da quale parte stiamo. Ma in realt&agrave; &egrave; di pi&ugrave;, &egrave; incredulit&agrave; che Dio &egrave; la parte vincente, che Dio completer&agrave; la vittoria che ha gi&agrave; ottenuto in Cristo, che seguire Dio &egrave; meglio di essere stimati di meno dagli altri.</p>
<p>Oppure quando decidiamo come spendere i nostri soldi. Possiamo usarli per la diffusione del Vangelo, sostenendo un missionario o aiutare i bisognosi; oppure per noi stessi. A volte c'&egrave; la paura di metterci in gioco - non mettere in gioco la reputazione o la figura, ma il portafoglio. Se diamo il 10% o il 20% o di pi&ugrave; di quello che guadagniamo, sono soldi che spariscono dal conto bancario e che non vedremo mai pi&ugrave;. Invece Dio promette che il denaro investito nella sua opera &egrave; un investimento per l'eternit&agrave; e creer&agrave; un guadagno non per noi stessi, ma per la sua gloria.</p>
<p>Similmente per ogni scelta che facciamo nella vita. Non possiamo rimanere neutri. Dobbiamo per forza manifestare da quale parte stiamo, ed &egrave; meglio dichiarare di essere dalla parte del Dio sovrano, santo, che ci ama, e va glorificato da ogni decisione che prendiamo.</p>
<p>Quando Gedeone ritorn&ograve; dalla cattura dei due re Zeba e Salmunna, fece quello che aveva promesso e pun&igrave; le due citt&agrave;. Per&ograve;, Gedeone non esce bene da questo racconto. Gedeone non ag&igrave; per compiere l'opera del Signore n&eacute; per il Signore, ma come vendetta personale. Gli attacchi non facevano parte della liberazione di Israele da parte di Dio, ma di una crociata da parte di Gedeone per soddisfare il proprio onore. Questo &egrave; chiaro da Giudici 8:15, in cui Gedeone disse a Succot che "mi insultaste" e non che "non credeste in Dio". Sar&agrave; anche pi&ugrave; evidente nel prossimo paragrafo del capitolo. Certo, Succot e Penuel non avevano fatto bene rifiutando di aiutare Gedeone per l'incredulit&agrave;. Ma la punizione che subirono era da Gedeone e non da Dio.</p>
<p>Questa &egrave; la prima volta che gli Israeliti combattono contro altri Israeliti, anche se c'&egrave; stata un'anticipazione nel lamento di Efraim nella sezione precedente. Inoltre, da questo punto la spirale scende sempre pi&ugrave; in basso. Nel libro dei Giudici, vedremo sempre pi&ugrave; disunit&agrave; nella nazione, fino ad arrivare alla guerra civile. Oltre ai problemi politici nella nazione, &egrave; anche evidenza dei problemi spirituali. Ogni idea di essere il popolo speciale di Dio, per essere una luce per le altre nazioni, sparir&agrave;. Le citt&agrave;, le trib&ugrave;, e addirittura i giudici penseranno sempre di pi&ugrave; ai propri interessi e non agli interessi del popolo di cui fanno parte, e soprattutto non del Dio che dovrebbero servire e onorare. Ne approfondiremo mentre scenderemo la spirale nei seguenti capitoli, ma &egrave; anche un avvertimento per noi. Quando litighiamo con i nostri fratelli, quando facciamo male a loro, quando diciamo come Gedeone "mi hai insultato" e quindi facciamo vendetta, cosa stiamo facendo veramente? Stiamo dimenticando l'onore che Dio ci ha dato, tutti insieme e non individualmente, di essere il popolo di Dio, e la responsabilit&agrave; che questo onore ci d&agrave; di essere la luce delle nazioni.</p>
<blockquote>Fratelli, voi siete stati chiamati a libert&agrave;; soltanto non fate della libert&agrave; un'occasione per vivere secondo la carne, ma per mezzo dell'amore servite gli uni agli altri; poich&eacute; tutta la legge &egrave; adempiuta in quest'unica parola: &laquo;Ama il tuo prossimo come te stesso&raquo;. Ma se vi mordete e divorate gli uni gli altri, guardate di non essere consumati gli uni dagli altri. (Galati 5:13-15)</blockquote>
<p>C'&egrave; un'altra riflessione sul comportamento di Gedeone, quando pensiamo all'atteggiamento di Dio verso di lui nei capitoli precedenti. Quando Dio lo chiam&ograve;, Gedeone aveva paura, esitava, era riluttante, e cercava delle scuse. Eppure, Dio non lo scart&ograve;, non si stuf&ograve; mai di Gedeone, non lo pun&igrave; per la sua incredulit&agrave;, non decise che era inutile per cercarne un altro. Piuttosto era paziente e compassionevole, simpatizzava con lui nelle sue debolezze. Anzi, piace a Dio usare le persone proprio quando si sentono deboli e incapaci.</p>
<p>Quando Succot e Penuel erano riluttanti ad aiutare Gedeone, quando avevano paura di mettersi in gioco, Gedeone condann&ograve; le citt&agrave; senza compassione o pazienza, le scart&ograve;.</p>
<p>Somiglia alla parabola del servo ingrato in Matteo 18:21-35. Quando Pietro chiese a Ges&ugrave; quante volte doveva perdonare a suo fratello, Ges&ugrave; raccont&ograve; di un servo che doveva ad un re una somma enorme, milioni di euro. Il servo chiese al re di avere pazienza, e il re, mosso a compassione, gli condon&ograve; il debito. Il servo poi trov&ograve; un altro servo che gli doveva alcuni euro. L'altro servo gli chiese di avere pazienza, ma il primo servo non volle e lo fece imprigionare. Il re sent&igrave; quello che il servo aveva fatto, e lo diede in mano degli aguzzini fino a quando non avesse pagato tutto quello che gli doveva. "Cos&igrave;", concluse Ges&ugrave;, "vi far&agrave; anche il Padre mio celeste, se ognuno di voi non perdona di cuore al proprio fratello".</p>
<p>Quando noi critichiamo gli altri per le loro mancanze, quando ripaghiamo quelli che ci insultano o ci offendono, siamo come Gedeone e come il servo della parabola. Dove sono la pazienza e la compassione che noi abbiamo ricevuto dal nostro Padre in cielo per le nostre mancanze, incredulit&agrave;, paura, e offese contro il Dio onnipotente? Abbiamo dimenticato che il Signore Ges&ugrave; Cristo ha portato tutti questi nostri peccati nel suo corpo per la sua compassione? Abbiamo dimenticato l'esempio del giusto atteggiamento nella sofferenza che Ges&ugrave; ci ha lasciato? Non di vendetta, ma di mettere tutto nelle mani di Dio? Come scrisse lo stesso Pietro,</p>
<blockquote>Se soffrite perch&eacute; avete agito bene, e lo sopportate pazientemente, questa &egrave; una grazia davanti a Dio. Infatti a questo siete stati chiamati, poich&eacute; anche Cristo ha sofferto per voi, lasciandovi un esempio perch&eacute; seguiate le sue orme.<br />
<i>Egli non commise peccato<br />
e nella sua bocca non si &egrave; trovato inganno.<br /></i>
Oltraggiato, non rendeva gli oltraggi; soffrendo, non minacciava, ma si rimetteva a colui che giudica giustamente; egli ha portato i nostri peccati nel suo corpo, sul legno della croce, affinch&eacute;, morti al peccato, vivessimo per la giustizia, e <i>mediante le sue lividure siete stati guariti</i>. Poich&eacute; eravate erranti come pecore, ma ora siete tornati al pastore e guardiano delle vostre anime. (1Pietro 2:21-25)</blockquote>
<h2>3. Ieter (8:18-21)</h2>
<p>In questo brano le motivazioni di Gedeone sono pi&ugrave; chiare. Sembra che sapesse, o almeno che sospettasse fortemente, che Zeba e Salmunna avevano ucciso i suoi fratelli. Sapeva che i re avevano ucciso degli uomini sul monte Tabor, presumibilmente sapeva anche dove erano morti i suoi fratelli. In quel caso, tutto l'inseguimento dopo la non battaglia era per eseguire una vendetta personale per la morte dei suoi fratelli.</p>
<p>Ieter, il figlio di Gedeone, &egrave; poi menzionato inaspettatamente. Perch&eacute; lui &egrave; importante? Ieter &egrave; un paragone e contrasto con Gedeone. Ieter somiglia a Gedeone all'inizio del racconto, quando aveva paura di eseguire la chiamata del Signore, quando cercava delle scuse o agiva di notte per non essere visto. Quando sapeva di essere debole. Similmente, Ieter sapeva di essere giovane e non forte, non riusciva a ammazzare una persona.</p>
<p>Per&ograve; ora Gedeone &egrave; il liberatore del paese, il capo militare, potente; anzi, prepotente. Poteva fare tutto quello che voleva fare per i propri interessi (per una vendetta, per ripagare un insulto) senza che nessuno lo criticasse o punisse. Non dipendeva pi&ugrave; da Dio, ma faceva quello che gli pareva meglio per s&eacute; stesso.</p>
<p>Ironicamente, Gedeone era pi&ugrave; bravo moralmente quando era meno bravo come combattente. Per&ograve; non sorprendentemente, perch&eacute; Dio usa i deboli per eseguire la sua volont&agrave;, affinch&eacute; la gloria vada a lui. Quelli che sono forti spesso fanno quello che vogliono perch&eacute; riescono a fare quello che vogliono, piuttosto che fare la volont&agrave; del Signore.</p>
<h2>4. Gedeone (8:22-32)</h2>
<h3>Re? No (22-23)</h3>
<p>Israele voleva un re ereditario, cio&egrave; non soltanto che Gedeone avrebbe regnato su di loro, ma anche nel futuro il figlio e il nipote di Gedeone. Gedeone giustamente rifiut&ograve; quest'offerta. Doveva essere il Signore che regnava su Israele, e quando era necessario avere un capo umano, il Signore nominava come giudice chi voleva. Per&ograve;, quando qualcuno diventava re solo perch&eacute; era il figlio del re precedente, non &egrave; pi&ugrave; Dio che sceglie i suoi servi ma solo la generazione umana. Questo tema &egrave; approfondito in 1Samuele 8, quando Israele scelse il suo primo re, Saul. In realt&agrave;, un figlio di Gedeone regn&ograve; dopo di lui, ossia Abimelec, che and&ograve; male, come vedremo nel prossimo capitolo.</p>
<p>Per&ograve;, anche se Gedeone rifiut&ograve; di avere il titolo di re, inizi&ograve; a agire e vivere come se fosse il re. Governava in modo di aumentare il proprio onore, potere, e prestigio,&euro; tutto senza Dio. Lo vedremo in tre sfere: le ricchezze, la religione, e la famiglia.</p>
<h3>a) Re? S&igrave; - ricchezze (24-26)</h3>
<p>Gedeone non voleva essere chiamato re, ma voleva avere la ricchezza che spetterebbe a un re. Chiese l'oro del bottino. Solo l'oro degli anelli ammontava a 1600 sicli, cio&egrave; 26 chilogrammi o circa, &euro;1,5 milione ai prezzi attuali. Ricevette anche "le mezzelune, i pendenti e le vesti di porpora che i re di Madian avevano addosso", cio&egrave; anche i simboli di potere che i re indossavano. Non era il re, ma aveva tutti i tratti caratteristici di un re.</p>
<h3>b) Re? S&igrave; - religione (27)</h3>
<p>In antichit&agrave; i re spesso decidevano la religione. I faraoni d'Egitto si consideravano degli d&egrave;i. I re dell'Assiria erano anche i sommi sacerdoti. In ogni caso, controllare l'accesso agli d&egrave;i del popolo centralizzava il potere e dava al re ulteriore autorit&agrave;. Quindi Gedeone, con l'oro del bottino, fece fabbricare un efod, che era il vestito rituale di un sacerdote. In realt&agrave;, non serviva un altro efod, perch&eacute; ce n'era gi&agrave; uno che Mos&egrave; aveva fabbricato, seguendo le istruzioni dettagliate di Dio. Per&ograve;, invece di seguire la religione divinamente istituita, Gedeone volle che la gente si avvicinasse a Dio tramite i riti che stabil&igrave; nella sua citt&agrave; di Ofra. Come conseguenza, tutto Israele si prostitu&igrave; all'efod, adorando Dio nel modo sbagliato attraverso l'efod, che divent&ograve; un'insidia.</p>
<p>Per la prima volta, un capo di Israele portava gli Israeliti all'idolatria. La discesa lungo la spirale prosegue, e ora anche il giudice &egrave; coinvolto nella discesa e la promuove.</p>
<h3>c) Re? S&igrave; - famiglia (28-32)</h3>
<p>I re dell'antichit&agrave; spesso avevano anche un harem. Gedeone non voleva essere di meno, e aveva tante mogli e una concubina, da cui ebbe 70 figli. Come re, aveva il potere di prendere in moglie chiunque voleva, e sembra che esercitasse questo potere. Cos&igrave; manifest&ograve; il suo potere e la sua importanza a tutti.</p>
<p>Per&ograve;, anche questa grande famiglia fu un'insidia, e cre&ograve; tanti guai nella famiglia stessa e per tutto Israele, come vedremo nel prossimo capitolo del libro dei Giudici. Vivere contrario ai modi stabiliti da Dio per quanto riguarda la famiglia (un marito e una moglie, da cui provengono i figli) potrebbe sembrare piacevole al momento, ma non &egrave; il modo corretto per gestire la famiglia n&eacute; la vita, e creer&agrave; problemi nel futuro.</p>
<p>In Giudici 8:28 c'&egrave; il solito riassunto della vita del giudice, che &egrave; una valutazione positiva della liberazione che Gedeone aveva ottenuto. Ma in realt&agrave; Gedeone regn&ograve; per 40 anni sull'apostasia nazionale, che venne fuori dopo la sua morte (Giudici 8:33). Non solo Gedeone prese le caratteristiche di un re, ma prese le caratteristiche di un re cananeo, cio&egrave; come quelli di Canaan. Come conseguenza, Israele stava diventando sempre meno come popolo di Dio, e sempre di pi&ugrave; come Canaan.</p>
<h2>5. Conclusione</h2>
<p>Quando la Bibbia parla di un giudice o di un re (finto o vero), &egrave; anche per insegnarci che i sistemi politici umani e i grandi personaggi della storia non possono risolvere i nostri problemi con Dio. Perch&eacute; anche loro sono umani, e soggetti allo stesso problema di ribellione contro il Dio sovrano.</p>
<p>Cos&igrave; ci spingono a considerare Ges&ugrave; Cristo, il Re dei re - di tutti i re, veri e finti! - e il Signore dei signori. Infatti, Ges&ugrave; come il perfetto re aveva tutte le caratteristiche che voleva Gedeone - ricchezza, religione, famiglia. Per&ograve; mentre Gedeone le voleva per mostrare la sua grandezza e per aumentare il suo potere, Ges&ugrave; le aveva per fare bene ai suoi sudditi. Perch&eacute;</p>
<blockquote>Voi sapete che quelli che sono reputati pr&igrave;ncipi delle nazioni le signoreggiano e che i loro grandi le sottomettono al loro dominio... Il Figlio dell'uomo [il Re dei re] non &egrave; venuto per essere servito, ma per servire, e per dare la sua vita come prezzo di riscatto per molti. (Marco 10:42,45)</blockquote>
<h3>a) Ricchezze</h3>
<p>Il nostro Signore Ges&ugrave; Cristo, essendo ricco, si &egrave; fatto povero per voi, affinch&eacute;, mediante la sua povert&agrave;, voi poteste diventare ricchi. (2Corinzi 8:9)</p>
<h3>b) Religione</h3>
<p>Nessuno viene al Padre se non per mezzo di me... Chi ha visto me, ha visto il Padre. (Giovanni 14:6,9)</p>
<h3>c) Famiglia</h3>
<p>Sia colui che santifica [Ges&ugrave; Cristo] sia quelli che sono santificati provengono tutti da uno; per questo egli non si vergogna di chiamarli fratelli. (Ebrei 2:11)</p>
<p>Ges&ugrave; spende la sua ricchezza per noi non per s&eacute; stesso; rivela il Padre non per ottenere pi&ugrave; potere ma per darci un libero accesso a lui; ha una famiglia grande non per manifestare la sua grandezza ma perch&eacute; ci ama e vuole includerci nella sua famiglia.</p>
<p>Possiamo anche raccogliere alcune delle riflessioni su questo capitolo sotto gli stessi titoli, per riflettere su quando somigliamo al nostro Re e Signore. Perch&eacute;, aggiungendo le parole dietro i puntini di sospensione della citazione precedente,</p>
<blockquote>Voi sapete che quelli che sono reputati pr&igrave;ncipi delle nazioni le signoreggiano e che i loro grandi le sottomettono al loro dominio. Ma non &egrave; cos&igrave; tra di voi; anzi, chiunque vorr&agrave; essere grande fra voi, sar&agrave; vostro servitore; e chiunque, tra di voi, vorr&agrave; essere il primo sar&agrave; servo di tutti. (Marco 10:42-44)</blockquote>
<h3>a) Ricchezze</h3>
<p>Ci mettiamo in gioco per quanto riguardo il denaro? Crediamo che il migliore investimento che possiamo fare sia per il destino eterno degli altri e per i loro bisogni, o crediamo che sia per i nostri piaceri?</p>
<h3>b) Religione</h3>
<p>Il nostro interesse &egrave; portare le persone al vero Dio in Ges&ugrave;? Anche se Dio ci chiama a un compito poco riconosciuto? Lo facciamo con tutta la forza che Dio provvede, o siamo limitati dalle nostre capacit&agrave;?</p>
<h3>c) Famiglia</h3>
<p>Amiamo veramente i nostri fratelli? Abbiamo la gioia invece del rancore per quello che fanno o hanno che noi non abbiamo? Quando ci offendono o ci fanno del male, abbiamo la stessa pazienza e compassione che il Signore ha mostrato verso di noi?</p>
<p>Se cresciamo in questo, con l'aiuto e la potenza dello Spirito Santo, invece di scendere lungo la spirale in gi&ugrave; come Israele che diventava sempre pi&ugrave; come Canaan, saliremo lungo la spirale in su per diventare sempre pi&ugrave; come il Re dei re Ges&ugrave; Cristo.</p>

<?
$n=9;
require("indice.php");
require("../../piede.php");
?>

