<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 2]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 2]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Gedeone [parte 2] (Giudici 7)</h1>
<p>Nella sezione precedente di questo testo, abbiamo saltato alcuni versetti del capitolo 6, perch&eacute; descrivevano i preparativi per la battaglia, che stavano fra alcuni casi della riluttanza di Gedeone, che abbiamo considerato insieme. In questa sezione, leggeremo tutti i preparativi e la battaglia stessa (anzi, la non battaglia) contro i Madianiti, e riflettiamo sul modo in cui Dio agisce, scegliendo le cose deboli, disprezzate, e ignobili, affinch&eacute; non ci vantiamo.</p>
<h2>1. Convocazione (6:33-35)</h2>
<p>Come succedeva in modo regolare in quel periodo, i Madianiti e i loro alleati, nemici di Israele, arrivarono per fare razzia e depredare gli Israeliti. Anche se Gedeone era riluttante, si ritenevano un nulla, e aveva paura, abbiamo visto che zero pi&ugrave; infinito fa infinito, e cos&igrave; quando lo Spirito Santo si impossess&ograve; di Gedeone, il giudice era in grado di fare grandi cose. A Dio non era difficile usare una persona cos&igrave; problematica, perch&eacute; sarebbe stato Dio che avrebbe vinto non Gedeone.</p>
<p>Gedeone poi convoc&ograve; la sua famiglia (gli Abiezeriti), la sua trib&ugrave; (Manasse), e le trib&ugrave; vicine (Ascer, Zabulon, Neftali) per partecipare alla liberazione che Dio avrebbe compiuto.</p> 
<h2>2. Prima riduzione (7:1-3)</h2>
<p>32.000 Israeliti risposero alla convocazione. In realt&agrave;, non sembrava un numero grande contro le truppe innumerevoli del nemico. Comunque, Dio poi fece una cosa strana, e mand&ograve; a casa tutti gli Israeliti che avevano paura, che non erano completamente convinti, o che non volevano combattere. Due terzi dell'esercito accolsero l'invito e se ne andarono, lasciando solo 10.000.</p>
<p>Questo non era un atto di compassione verso i dubbiosi n&eacute; per mantenere alto il morale dell'esercito togliendo quelli che potevano ritirarsi durante la battaglia. Piuttosto, era perch&eacute; forse 32.000 soldati potevano vincere, ma non potevano vincere bene. L'esercito avrebbe potuto pensare di aver vinto perch&eacute; era forte o grande, perch&eacute; i soldati erano pi&ugrave; bravi e valorosi dei nemici. Cos&igrave; si sarebbero vantati che per la propria mano avrebbero salvato se stessi. Era invece fondamentale che riconoscessero la verit&agrave;: solo Dio poteva salvarli dalla loro miseria, e che solo lui andava glorificato.</p>
<h2>3. Seconda riduzione (7:4-8)</h2>
<p>Per&ograve; c'era ancora un problema: anche con 10.000 soldati gli Israeliti sarebbero potuti vantarsi! Ci voleva un'altra riduzione nel numero, e Dio fece una selezione in modo arbitrario, tranne per il fatto che ne voleva pochi. Chi beveva l'acqua da un fiume in piedi, portando l'acqua alla bocca con la mano andava bene; chi si metteva in ginocchio per bere andava mandato a casa.</p>
<p>Con questo processo, rimasero solo 300 uomini. Cosa possiamo dire? Era un modo pazzo per creare un esercito! Gi&agrave; prendere i 300 invece dei 9.700 non ha senso, ma scegliere i 300 in base a come beveva piuttosto di, per esempio, la bravura con la spada, era una pazzia. Per&ograve; questa pazzia &egrave; il messaggio centrale del capitolo, se non di tutti i giudici che abbiamo visto finora, ed anche di tutta la Bibbia. Lo approfondiremo alla fine di questa sezione, ma prima vediamo che cosa Dio fece tramite questi 300 uomini.</p>
<h2>4. Conferma della promessa (7:9-14)</h2>
<p>Dio comand&ograve; a Gedeone di piombare sull'accampamento, per&ograve; sapeva che Gedeone aveva ancora paura e quindi nella sua misericordia diede un'ulteriore conferma che avrebbe vinto. Come abbiamo visto nel capitolo precedente, Dio non ci scarta quando siamo mancanti, perplessi, o dubbiosi, ma ci aiuta nella nostra debolezza. Dio sa comunque che, come non era il coraggio di Gedeone n&eacute; la grandezza dell'esercito che avrebbero vinto la battaglia, cos&igrave; non &egrave; la nostra perfezione che compir&agrave; i suoi propositi per il suo regno, ma la sua onnipotenza, onniscienza, e pazzia che scelgono strumenti deboli come noi e Gedeone. Invece di scartarci o buttarci via come inutili per lui, Dio ci incoraggia, Dio conferma la promessa fatta a noi ripetutamente, anche se abbiamo l'abitudine di ripetutamente dimenticare la promessa o di non ubbidire al suo comandamento.</p>
<p>Quindi Gedeone e suo servo Pura andarono di nascosto nell'accampamento dei Madianiti, e scoprirono la paura dei Madianiti, la consapevolezza di essere gi&agrave; spacciati perch&eacute; Dio era con Gedeone.</p>
<h2>5. La non battaglia (7:15-23)</h2>
<p>Prima di tutto, Gedeone divise il suo esercito in tre gruppi di cento persone. Poi distribu&igrave; delle trombe e delle brocche con fiaccole, che sarebbero state le armi che avrebbero usato.</p>
<p>Al cambio della guardia a mezzanotte, tutti e 300 fecero un casino, suonando le trombe, alzando le fiaccole, e gridando pi&ugrave; forte che potevano, "La spada per il Signore e per Gedeone". In questo modo, senz'altro sembravano pi&ugrave; numerosi di quanto fossero in realt&agrave;, e creavano confusione nell'accampamento dei Madianiti. Nella confusione, nel buio, nella sonnolenza, e soprattutto per l'opera del Signore (Giudici 7:22), tutti i Madianiti si rivolsero la spada contro gli altri, e quelli che rimasero vivi fuggirono dal campo di non battaglia.</p>
<p>In questo modo, Israele vinse e fu liberato. In realt&agrave;, non era cos&igrave;. Dio vinse e liber&ograve; Israele.</p>
<h2>6. Conclusione: Per non vantarsi</h2>
<p>Abbiamo gi&agrave; visto il motivo della doppia riduzione dell'esercito, da 32.000 a 300 uomini. Altrimenti, Israele si sarebbe potuto vantare di fronte a Dio, e dire: "&Egrave; stata la mia mano a salvarmi" (Giudici 7:2). Cio&egrave;, Israele doveva essere debole per non solo vincere, ma vincere bene, glorificando Dio (vantandosi di Dio) per la sua opera piuttosto che glorificare s&eacute; stesso (vantarsi di s&eacute; stesso). Questo &egrave; il significato e l'insegnamento della riduzione e della non battaglia. Infatti, &egrave; uno degli insegnamenti principali del libro dei Giudici, oltre al ciclo della vita che &egrave; in realt&agrave; una spirale verso il basso. Non soltanto, &egrave; uno degli insegnamenti principali di tutta la Bibbia. Guardiamo come vediamo questo tema in Giudici, e poi nella Bibbia.</p>
<p>Abbiamo notato che, dopo Otniel (che &egrave; presentato come giudice modello, perfetto), c'&egrave; sempre stato qualcosa di strano o di particolare negli altri giudici. Eud era un mancino: senz'altro insolito, probabilmente anche disprezzato nella sua cultura. Inoltre, era un uomo di dubbia integrit&agrave;.</p>
<p>Samgar us&ograve; un pungolo da buoi invece di una spada - non un'arma che avremmo scelto di usare, ma un'arma che Dio poteva usare affinch&eacute; fosse chiaro che la sua potenza aveva liberato e non la potenza dell'arma. Inoltre, Samgar era collegato con i Cananei in qualche modo, e quindi non un esempio perfetto di Israelita.</p>
<p>Il giudice Barac soffriva da una mancanza di fede, ma Dio lo us&ograve; comunque per liberare Israele. Il suo onore fu comunque dato a Iael, una donna, e un'altra donna (Debora) era la profetessa che lo guidava. Donne, che erano un'altra classe di persone disprezzate nella cultura.</p>
<p>Gedeone confess&ograve; di essere il pi&ugrave; piccolo nella casa di suo padre, e la sua famiglia la pi&ugrave; povera della sua trib&ugrave; Manasse (Giudici 6:15). Era debole, in questo senso. Inoltre, era riluttante e spaventato. Non aveva la stoffa di campioni.</p>
<p>Tante volte, ogni volta, Dio scelse il debole, il disprezzato, il disonorato, l'ignobile per compiere i suoi propositi. Non &egrave; come noi avremmo pianificato o fatto, non ha senso per noi, &egrave; una pazzia. Perch&eacute; fa cos&igrave;? Sappiamo la risposta: affinch&eacute; nessuno si vanti di fronte a Dio.</p>
<p>Dio ag&igrave; cos&igrave; non soltanto all'epoca dei giudici, ma da sempre. Per questo motivo &egrave; un tema di tutta la Bibbia. Ci sono molti brani che spiegano e approfondiscono questo tema, ma ne ho scelto soltanto uno:</p>
<blockquote>Dio ha scelto le cose pazze del mondo per svergognare i sapienti; Dio ha scelto le cose deboli del mondo per svergognare le forti; Dio ha scelto le cose ignobili del mondo e le cose disprezzate, anzi le cose che non sono, per ridurre al niente le cose che sono, affinch&eacute; nessuno si vanti di fronte a Dio. Ed &egrave; grazie a lui che voi siete in Cristo Ges&ugrave;, che da Dio &egrave; stato fatto per noi sapienza, giustizia, santificazione e redenzione; affinch&eacute;, com'&egrave; scritto:<br />
&laquo;Chi si vanta, si vanti nel Signore&raquo;. (1Corinzi 1:27-31)</blockquote>
<p>L'apostolo Paolo ribadisce quello che abbiamo gi&agrave; visto in Giudici: Dio sceglie le cose pazze (secondo il punto di vista umano), deboli, ignobili, e disprezzate. Il motivo di questa scelta &egrave; di svergognare i bravi e importanti e potenti di questo mondo, quelli che pensano di poter fare tutto senza l'aiuto di altri, e soprattutto senza Dio. La conseguenza &egrave; che nessuno si pu&ograve; vantare di fronte a Dio (1Cor 1:29). Davanti al Dio Creatore, onnipotente e onnisciente, quello che provvede ogni cosa per noi, non possediamo niente che possiamo dire che abbiamo guadagnato, non facciamo niente che possiamo dire che era solo per il nostro lavoro, non otteniamo niente che Dio non ci abbia dato. Quindi se noi ci sentiamo deboli o disprezzati, Dio pu&ograve; usarci per compiere i suoi propositi, e ci rallegriamo in questo. Quelli bravi, quelli forti, quelli che riescono a fare tutto, che non hanno mai problemi, non sono utili a Dio perch&eacute; s&igrave;, possono vincere, ma non possono vincere bene. Fanno tanto, ma &egrave; merito della loro bravura.</p>
<p>Questo fatto ci libera dall'ansia, dalla preoccupazione, da sentimenti di colpa, dalla disperazione di essere incapaci di cambiare la situazione - nella famiglia, al posto di lavoro, in chiesa - perch&eacute; sappiamo che il risultato di tutto quello che facciamo &egrave; nelle mani di Dio. Ci libera dall'ansia all'impegno per Dio. Diamo il tutto, tutto il nostro essere, tutti i doni di abilit&agrave; e di beni materiali e di altro, anche se imperfetti, perch&eacute; sappiamo che Dio pu&ograve; usare le nostre debolezze, e cos&igrave; lo glorifichiamo quando diamo tutto a lui e ci vantiamo di lui e di quello che fa attraverso noi, i suoi umili strumenti.</p>
<p>Questo modo di operare da parte di Dio &egrave; dappertutto nella Bibbia. Lo vediamo nel fatto che portiamo il tesoro del Vangelo in vasi di terra (la nostra esistenza debole), affinch&eacute; la grande potenza sia attribuita a Dio e non a noi (2Cor 4:7-11). Lo vediamo nella spina nella carne di Paolo, perch&eacute; la potenza di Dio si dimostra perfetta nella debolezza (2Cor 12:7-10). Lo vediamo nella nascita del Signore Ges&ugrave; Cristo, il re dei re, il Creatore dell'universo, che entr&ograve; nel mondo non con la sua grandezza e il suo potere e la sua gloria, ma come un bambino impotente e indifeso, in una mangiatoia, in una famiglia povera.</p>
<p>E lo vediamo soprattutto nella nostra salvezza, perch&eacute; &egrave; solo per la grazia di Dio che noi siamo salvati, perch&eacute; in Cristo Ges&ugrave; riceviamo la sapienza, la giustizia, la santificazione e la redenzione (1Cor 1:30). Quindi quando ci vantiamo, ci vantiamo solo del Signore (1Cor 1:31), cio&egrave; glorifichiamo Dio Padre nel Signore Cristo Ges&ugrave; tramite lo Spirito Santo per tutto quello che &egrave; e che fa. E quale modo ha scelto Dio di salvarci? Con grandi opere miracolosi? Con bei discorsi? Con un grande esercito? Con spettacoli divertenti? Con la politica e le leggi? Con bella musica? No! Con un disgraziato torturato e schernito mentre era appeso per essere ucciso. Pazzia! Noi non avremmo mai fatto in quel modo. Infatti, Paolo scrive nel paragrafo precedente a quello citato qui sopra:</p>
<blockquote>Poich&eacute; il mondo non ha conosciuto Dio mediante la propria sapienza, &egrave; piaciuto a Dio, nella sua sapienza, di salvare i credenti con la pazzia della predicazione. I Giudei infatti chiedono segni miracolosi e i Greci cercano sapienza, ma noi predichiamo Cristo crocifisso, che per i Giudei &egrave; scandalo e per gli stranieri pazzia; ma per quelli che sono chiamati, tanto Giudei quanto Greci, predichiamo Cristo, potenza di Dio e sapienza di Dio; poich&eacute; la pazzia di Dio &egrave; pi&ugrave; saggia degli uomini e la debolezza di Dio &egrave; pi&ugrave; forte degli uomini. (1Corinzi 1:21-25)</blockquote>
<p>A Dio sia la gloria per la sua potenza e sapienza, ma anche per la sua "pazzia" e "debolezza".</p>

<?
$n=8;
require("indice.php");
require("../../piede.php");
?>

