<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Giudici: Situazione storica e teologica";
$key = "giudici,situazione,storica,teologica";
$titolo = "Situazione storica e teologica (Giudici 1:1-2:9)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Gedeone [parte 1] (Giudici 6)</h1>
<p>Il racconto del giudice Gedeone contiene tre capitoli. Inoltre, il capitolo successivo parla di suo figlio Abimelec, che non era un giudice e di cui il racconto appartiene in realt&agrave; alla storia di Gedeone. Per questo motivo, il racconto di Gedeone sar&agrave; diviso in diverse parti. In questa prima parte, vedremo la sua chiamata, e in modo particolare scopriremo le sue contraddizioni. Contraddizioni che spesso noi condividiamo, e cos&igrave; il modo in cui Dio si relaziona con Gedeone ci aiuter&agrave; a capire come Dio si relaziona con noi.
<h2>1. Retroscena (6:1-10)</h2>
<p>Anche il racconto di questo giudice inizia con una spiegazione della situazione in cui si trovava Israele, una spiegazione che &egrave; ancora una volta la prima met&agrave; del ciclo che viene ripetuto diverse volte nel libro. Gli Israeliti si ribellano contro Dio facendo ci&ograve; che &egrave; male ai suoi occhi (Giudici 6:1), Dio li abbandona dandoli nelle mani dei nemici (Giudici 6:1-5), e gli Israeliti gridano a Dio per essere liberati (Giudici 6:6).</p>
<p>Questa volta, il nemico e oppressore &egrave; il popolo di Madian. Erano i discendenti di un figlio di Abraamo con la sua seconda moglie, e abitavano all'est del fiume Giordano. Si opposero spesso agli Israeliti. Per esempio, durante i 40 anni nel deserto fra l'esodo e il possesso della terra promessa, i Madianiti pagarono Balaam per maledire Israele (Num 22) e una donna di Madian trascin&ograve; gli Israeliti in idolatria (Num 25; vedi anche Num 31:16). Questa volta si erano alleati con gli Amalechiti (discendenti di Esa&ugrave;, gemello di Giacobbe) e dei popoli dell'oriente (forse Moab e Ammon, i discendenti di Lot).</p>
<p>L'oppressione era pi&ugrave; forte questa volta. Invece di essere conquistato, occupato, e dominato, Israele era devastato. I nemici facevano razzia per prendersi e distruggere tutti i prodotti agricoli e tutti gli animali da fattoria degli Israeliti. Cos&igrave; agli Israeliti rimaneva poco da mangiare e per vivere, e si dovevano nascondere dai Madianiti in grotte e caverne.</p>
<p>Poi succede qualcosa di diverso nel racconto (Giudici 6:7-10). Dio mand&ograve; un profeta per ricordare agli Israeliti perch&eacute; erano in grande miseria. Dio li aveva liberati dall'Egitto, dalla schiavit&ugrave; e dall'oppressione. Dio aveva dato loro un nuovo paese in cui vivere, e Dio aveva comandato loro di adorare solo lui e non gli altri d&egrave;i. Ma non l'avevano fatto.</p>
<h2>2. Chiamata e riluttanza di Gedeone (6:11-24, 36-40)</h2>
<p>In questo brano, c'&egrave; un dialogo tra l'angelo del Signore (che chiama Gedeone a eseguire la volont&agrave; di Dio) e Gedeone (che &egrave; riluttante a fare quello che il Signore vuole). Seguiremo queste botte e risposte.</p>
<h3>a) Chiamata (11-12)</h3>
<p>In questo contesto di grande miseria e disgrazia, l'angelo del Signore incontra Gedeone, lo saluta come uomo forte e valoroso, e afferma che il Signore &egrave; con lui. Il fatto che &egrave; forte e valoroso ci fa pensare che &egrave; simile a un guerriero, uno che combatter&agrave; bene per Dio e per il Signore. Ma non solo con la propria forza, ma anche con il Signore che &egrave; con lui. Queste qualit&agrave; sembrano ottime per un giudice, &egrave; un liberatore che ci aspetteremmo. Per&ograve;, come spesso nel libro dei Giudici, Gedeone &egrave; un uomo di contraddizioni, e c'&egrave; altro da dire su di lui.</p>
<h3>b) Riluttanza (13)</h3>
<p>L'angelo aveva affermato che il Signore era con Gedeone; Gedeone mise in dubbio che Dio era con Israele. Gedeone conosceva la storia di Israele, le grandi opere potenti e le meraviglie di Dio, come nell'esodo (e il fatto che Gedeone la conosceva &egrave; un'altra sua qualit&agrave; positiva), ma conosceva anche la disgrazia attuale di Israele. "Dove &egrave; questo Dio di cui ci hanno parlato? Questo Dio ci ha abbandonati dandoci nelle mani di Madian", chiede Gedeone.</p>
<p>In realt&agrave;, Gedeone aveva tutti i fatti corretti, ma gli mancavano due cose. Prima di tutto, Dio li aveva abbandonati temporaneamente, era il momento per un'altra sua meraviglia per liberarli dall'oppressione. E anche se Dio non era con Israele in quel momento, aveva appena promesso di essere con Gedeone. Dio avrebbe fatto questa meraviglia con Gedeone perch&eacute; era con Gedeone, e Gedeone avrebbe liberato il suo popolo.</p>
<p>Forse anche noi pensiamo nello stesso modo di Gedeone a volte. Conosciamo i grandi miracoli di Dio e di Ges&ugrave; nel passato. Abbiamo sperimentato la salvezza nella nostra vita. Ma poi ci guardiamo intorno alla nostra vita, e ci chiediamo, "Se il Signore &egrave; con noi, perch&eacute; ci &egrave; accaduto tutto questo?" Lottiamo con una malattia, non riusciamo a gestire la famiglia, siamo preoccupati per i genitori, non troviamo un lavoro o abbiamo un lavoro noioso o pesante, non riusciamo ad arrivare a fine mese con lo stipendio, non vediamo crescita spirituale nella chiesa e nei credenti che serviamo con tanta fatica. "Dove sono tutte quelle sue meraviglie che il pastore e i predicatori ci narrano ogni domenica?" Se &egrave; cos&igrave;, Gedeone &egrave; il giudice per noi, possiamo capire quello che lui sperimentava. E la risposta di Dio a Gedeone &egrave; la risposta di Dio a noi.</p>
<h3>c) Chiamata (14)</h3>
<p>Dio ribadisce che Gedeone &egrave; forte. Ma quello che &egrave; pi&ugrave; importante, come impareremo in modo particolare nel prossimo capitolo, &egrave; che Dio lo manda. Dio &egrave; con lui e lo manda, non servirebbe altro.</p>
<p>Nella nostra disperazione e disgrazia, nella nostra perplessit&agrave; della differenza apparente fra le promesse di Dio e quello che sperimentiamo nella vita materiale, Dio ci chiede di ricordare che siamo comunque mandati da lui per servirlo, con quello che siamo e abbiamo, come Dio ci ha fatti affinch&eacute; utilizziamo queste qualit&agrave; per lui e non per noi stessi.</p>
<h3>d) Riluttanza (15)</h3>
<p>Gedeone risponde con una seconda scusa. Lui non era nessuno, un nulla, il pi&ugrave; piccolo della famiglia pi&ugrave; piccola della sua trib&ugrave;. Non aveva niente con cui salvare Israele.</p>
<p>Forse anche noi pensiamo nello stesso modo di Gedeone a volte. Chi siamo noi a fare la differenza nella mia famiglia, dove tutti si oppongono a me? Chi sono io, l'ultimo arrivato, a cambiare il posto di lavoro? Chi sono io a impegnarmi nella comunit&agrave;? Chi sono io, che non ho nessun potere e non possiedo niente, a trasformare la societ&agrave;, a prendere cura dei bisognosi, a difendere i diritti degli oppressi? Se &egrave; cos&igrave;, Gedeone &egrave; il giudice per noi, possiamo capire quello che lui sperimentava. E la risposta di Dio a Gedeone &egrave; la risposta di Dio a noi.</p>
<h3>e) Chiamata (16)</h3>
<p>Dio risponde con un'affermazione semplice e potente: "Io sar&ograve; con te e tu sconfiggerai i Madianiti come se fossero un uomo solo". Questa &egrave; la terza volta che una frase simile a "io sar&ograve; con te" appare in questo dialogo, ed &egrave; una frase abbastanza comune nella Bibbia (spesso collegata con "non temere"), perch&eacute; fa un'enorme differenza nella vita. S&igrave;, Gedeone era piccolo, non importante. Piccolo in Israele, piccolissimo in confronto con la moltitudine innumerevole dei Madianiti. Ma non aveva importanza, perch&eacute; il Dio infinito era con lui. E uno pi&ugrave; infinito fa infinito, che &egrave; pi&ugrave; di 10, di 100, di mille, di un milione, di un miliardo. Dall'altra parte, le migliaia di Madianiti sarebbero sconfitte da Gedeone come se fossero un uomo solo, perch&eacute; migliaia davanti all'infinito &egrave; come uno, mentre uno con Dio &egrave; come l'infinito.</p>
<p>C'&egrave; opposizione in famiglia? &Egrave; come zero in confronto con Dio. Subiamo discriminazione dagli altri? &Egrave; come nulla. Le migliaia o i milioni che abitano nel nostro paese? Non sono niente in confronto con te con Dio.</p>
<h3>f) Riluttanza (17-18)</h3>
<p>Il terzo problema di Gedeone non &egrave; tanto una scusa, ma incredulit&agrave;, una mancanza di fede nella Parola di Dio e di ubbidienza al suo comando. La chiamata da parte di Dio, la Parola di Dio, gli doveva bastare, doveva ubbidire subito. Come Barac esit&ograve; a ubbidire e chiese una conferma della presenza di Dio con lui, cos&igrave; pure anche Gedeone, che per&ograve; chiese di pi&ugrave;, un segno soprannaturale per confermare che era la Parola di Dio.</p>
<h3>g) Il sacrificio (19-24)</h3>
<p>Dio spesso viene incontro alla nostra incredulit&agrave;. Non la approva, ci dice di credere invece, ma pu&ograve; comunque darci qualche segno per aiutarci e incoraggiarci a seguire e ubbidire, come fece con Gedeone. Per&ograve; non dobbiamo mai chiedere un segno come prova, come fece Gedeone.</p>
<h3>h) Il vello (36-40)</h3>
<p>Saltiamo alcuni versetti per considerare l'ultimo esempio della riluttanza di Gedeone. Il brano dal versetto 25 al versetto 32 sar&agrave; considerato nella prossima sezione, mentre i versetti dal 33 al 35 (la convocazione degli Israeliti da parte di Gedeone) saranno spiegati insieme con il capitolo seguente.</p>
<p>Il fuoco miracoloso che consum&ograve; il sacrificio nella sezione precedente non bast&ograve; a Gedeone, e sugger&igrave; a Dio una prova pi&ugrave; difficile: un vello messo per terra, che durante la notte doveva diventare bagnato per la rugiada mentre il terreno restava asciutto. Cos&igrave; avvenne; Dio lo fece. Per&ograve; Gedeone poteva ragionare in modo perverso che era una conseguenza naturale delle diverse capacit&agrave; del vello e del terreno di assorbire l'acqua. Oppure non voleva proprio eseguire la volont&agrave; di Dio. Quindi chiese pure il contrario. Per&ograve; Dio fece anche cos&igrave; quella notte.</p>
<p>Da questo racconto vediamo la terza scusa di Gedeone: non lo voglio fare!</p>
<p>Fra parentesi, da questo brano viene una pratica che &egrave; stata utilizzata nel passato da molti Cristiani, anche se &egrave; molto meno comune adesso. Si chiama "mettere un vello". In questa pratica, quando non si sa cosa fare, si impone una condizione o una circostanza per decidere. Per esempio, se vedr&ograve; una macchina rossa nei prossimi 5 minuti, far&ograve; A; se non, far&ograve; B. O se il cellulare squilla, o se qualche altro evento casuale accade. L'idea &egrave; che se Dio vuole che io faccia A, far&agrave; in modo che vedr&ograve; una macchina rossa e cos&igrave; mi potr&agrave; guidare alla scelta giusta.</p>
<p>Questa pratica &egrave; sbagliata e sconsigliata! Gedeone utilizz&ograve; il vello non per sapere la volont&agrave; di Dio (che sapeva gi&agrave;), ma per evitare di fare la volont&agrave; di Dio. Infatti, alcuni usavano questa tecnica per evitare di fare quello che sapevano era giusto. Per esempio, "Io dar&ograve; questi soldi per aiutare i bisognosi nella mia citt&agrave; invece di comprare una nuova Playstation perch&eacute; il mio amico ce l'ha e io ho ancora il modello dell'anno scorso, se la mia zia americana che non vedo da 10 anni bussa alla porta nei prossimi cinque minuti". Forse un caso esagerato, ma non molto! In ogni caso, la pratica rischia di diventare un esempio di mettere alla prova Dio, che non &egrave; mai giusto.</p>
<p>Dio non ha mai promesso di guidarci cos&igrave;. Invece noi abbiamo lo Spirito Santo e la saggezza che ci guidano, anche se una spiegazione di come ci guidano ci allontanerebbe troppo dal brano che abbiamo letto. Per&ograve; c'&egrave; un modo in cui Dio ci guida che &egrave; rilevante al vello, cio&egrave; attraverso le circostanze e le porte aperte e chiuse. Se dico che mi trasferir&ograve; in una nuova citt&agrave; se trover&ograve; un appartamento adatto, o che cambier&ograve; lavoro se ne trovo un altro che mi dar&agrave; pi&ugrave; tempo per la famiglia e per impegnarmi nella chiesa, non &egrave; "mettere un vello". Con un vello, ci sono condizioni che non hanno niente a che fare con la scelta. Con condizioni rilevanti, stiamo usando la saggezza per decidere quale scelta &egrave; migliore, lasciando a Dio la possibilit&agrave; di aprire e chiudere le porte quando ha qualcosa per noi che &egrave; migliore di quello che la nostra saggezza limitata pu&ograve; capire.</p>
<h3>i) Riassunto</h3>
<p>Oltre alla mancanza di fede e di ubbidienza alla Parola di Dio, Gedeone fece tre scuse per evitare di fare quello che Dio lo aveva chiamato a fare: Dio ci ha abbandonati, non sono nessuno, non lo voglio fare! In questo, &egrave; simile a Mos&egrave; quando venne chiamato da Dio a liberare il suo popolo in Esodo 3-4: Mos&egrave; fece diverse scuse (incluso "Chi sono io?" che ricevette la stessa risposta "Io sar&ograve; con te" Esodo 3:13), e poi concluse con l'esclamazione, "Manda un altro!".</p>
<p>Come Dio non scart&ograve; Mos&egrave;, non scart&ograve; neanche Gedeone. Non li butt&ograve; via come servi inutile nonostante le loro mancanze. Dio ha compassione per chi non ce la fa, per chi &egrave; in avversit&agrave;, per chi riconosce i propri limiti. Certo, Gedeone and&ograve; oltre a riconoscere i suoi limiti, c'era anche una riluttanza di servire Dio. Ma Dio pu&ograve; accogliere queste debolezze e usare noi nonostante le nostre mancanze di fede, i nostri sentimenti di inferiorit&agrave; o di incapacit&agrave;. Anzi, Dio ama usare chi non ce la fa, perch&eacute; in questo modo tutta la gloria va a lui e non a noi. Impariamo che senza di lui non possiamo fare niente (Giovanni 15:5) mentre i forti imparano (erroneamente) che anche con le proprie forze possono fare qualcosa. Questo &egrave; un messaggio importante del libro dei Giudici (e di tutta la Bibbia), &egrave; un messaggio a cui abbiamo fatto un accenno nei capitoli precedenti con i giudici strani e disprezzati, e che sar&agrave; approfondito nel prossimo capitolo.</p>
<h2>3. Zelo e paura di Gedeone (6:25-32)</h2>
<p>Anche se Gedeone aveva delle debolezze e una fede imperfetta, dobbiamo ricordare che aveva alcune caratteristiche positive. L'angelo del Signore afferm&ograve; che era forte e valoroso (Giudici 6:12,14), e Gedeone conosceva il passato e come Dio era stato con Israele (Giudici 6:13). Gedeone mise in pratica queste qualit&agrave; nello zelo che esercit&ograve; contro l'idolatria della sua casa in questi versetti.</p>
<p>S&igrave;, proprio della sua casa. Perch&eacute; seguire e servire Dio deve iniziare con noi stessi. Dio pu&ograve; usarci nonostante le nostre imperfezioni, ma dobbiamo riconoscere le nostre imperfezioni e combattere contro di esse. Prima di annunciare il vero Dio tre volte santo, dobbiamo combattere contro la nostra idolatria e la nostra immoralit&agrave;.</p>
<p>Quindi Gedeone demol&igrave; l'altare di Baal e abbatt&eacute; l'idolo di Baal che erano del padre. Us&ograve; il legno dell'ex-idolo per fare il fuoco per il sacrificio al vero Dio. Questa era l'unica utilit&agrave; spirituale di una statua di legno, perch&eacute; un pezzo di legno non ci pu&ograve; mai aiutare.</p>
<p>Tuttavia, l'ambiguit&agrave; in Gedeone rimaneva. Lo fece di notte, perch&eacute; aveva paura di come la gente avrebbe reagito (Giudici 6:27). Giustamente, perch&eacute; quando gli altri lo scoprirono, volevano appunto ucciderlo (Giudici 6:30).</p>
<p>Questo racconto ricorda quando Ges&ugrave; scacci&ograve; i mercanti dal tempio, quando lo zelo per la casa di Dio lo consumava (Giovanni 2:17). Nel racconto di Marco 11:15-19, leggiamo:</p>
<blockquote>Ges&ugrave;, entrato nel tempio, si mise a scacciare coloro che vendevano e compravano nel tempio; rovesci&ograve; le tavole dei cambiavalute e le sedie dei venditori di colombi; e non permetteva a nessuno di portare oggetti attraverso il tempio. E insegnava, dicendo loro: &laquo;Non &egrave; scritto: "La mia casa sar&agrave; chiamata casa di preghiera per tutte le genti"? Ma voi ne avete fatto un covo di ladroni&raquo;.<br />
I capi dei sacerdoti e gli scribi udirono queste cose e cercavano il modo di farlo morire. Infatti, avevano paura di lui, perch&eacute; tutta la folla era piena d'ammirazione per il suo insegnamento.<br />
Quando fu sera, uscirono dalla citt&agrave;.</blockquote>
<p>I capi volevano uccidere Ges&ugrave;, proprio come nel caso di Gedeone. Per&ograve;, questo non imped&igrave; a Ges&ugrave; di fare con zelo quello che era giusto; anzi, loro avevano paura di lui piuttosto di Ges&ugrave; di loro. Quindi Ges&ugrave; ag&igrave; di giorno e non di notte, e poi la sera usc&igrave;.</p>
<p>Tuttavia, nonostante la riluttanza della sua ubbidienza e la sua paura della gente, Gedeone fece quello che era giusto. In questo &egrave; un esempio imperfetto per noi, di come noi dobbiamo comportarci. Solo il Signore Ges&ugrave; Cristo &egrave; il nostro esempio perfetto.</p>
<p>Per&ograve;, Gedeone &egrave; un esempio perfetto di come Dio chiama e usa noi persone imperfette. Nonostante i sentimenti di inferiorit&agrave;, di essere abbandonato da Dio, una riluttanza di ubbidire, una fede debole, una paura della gente, anche noi possiamo e dobbiamo servire il nostro Dio, perch&eacute; Dio ha usato e usa sempre persone cos&igrave;. Certo, non &egrave; un motivo per giustificare le nostre mancanze. Il nostro obiettivo e desiderio deve rimanere di servire come Ges&ugrave; e non come Gedeone. Ma mentre aspettiamo la nostra completa trasformazione all'immagine di Ges&ugrave;, mentre siamo sulla via della santificazione, non dobbiamo proporre queste mancanze come scuse. Dobbiamo invece lodare Dio che ci ritiene degni di servirlo, e che siccome Dio &egrave; con noi, noi possiamo ringraziarlo perch&eacute; possiamo fare tanto, perch&eacute; &egrave; l'onnipotente Dio che agisce, non noi esseri imperfetti.</p>

<?
$n=7;
require("indice.php");
require("../../piede.php");
?>

