<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 3]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 3]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Iefte (pi&ugrave; cinque) (Giudici 10-12)</h1>
<p>Quasi tre capitoli sono dedicati al giudice Iefte. Inoltre, ci sono dei cosiddetti giudici minori - chiamati cos&igrave; non perch&eacute; sono meno importanti, ma perch&eacute; sono descritti con meno testo, un massimo di tre versetti. Dopo il giudice minore Samgar alla fine del capitolo 3, ci sono due giudici minori all'inizio del capitolo 10 e tre giudici minori alla fine del capitolo 12. Per questi motivi, la spiegazione di questo brano sar&agrave; diversa: prima un riassunto degli avvenimenti nel racconto di Iefte, e poi quattro riflessioni su quello che possiamo imparare dal racconto, inclusi dei confronti con i cinque giudici minori.</p>
<h2>Racconto di Iefte</h2> 
<p>Dopo Gedeone e i giudici minori Tola e Iair, gli Israeliti abbandonarono di nuovo il Signore, facendo ci&ograve; che era male ai suoi occhi. Per&ograve;, facevano ancora pi&ugrave; male di prima, stavano sempre peggiorando. C'&egrave; un lungo elenco di idoli e falsi d&egrave;i che servivano invece del Signore: Baal e Astarte, gli d&egrave;i della Siria, di Sidone, di Moab, degli Ammoniti e dei Filistei. Per questo motivo c'&egrave; l'inizio del solito ciclo che si trova spesso nel libro dei Giudici: l'ira di Dio contro gli Israeliti, e Dio li abbandon&ograve; ai nemici per 18 anni. In questo caso, non &egrave; un popolo che li opprimeva, ma due: i Filistei dal sud-ovest e gli Ammoniti dal nord-est. Gli Israeliti erano intrappolati fra i due che li angariavano. Nella loro grande angoscia, gli Israeliti gridarono al Signore.</p>
<p>A questo punto, il ciclo si ruppe. Ci saremmo aspettati che Dio suscitasse un giudice che avrebbe liberato Israele dagli oppressori. Per&ograve;, in realt&agrave; Israele non faceva un giro di un ciclo ma scendeva una spirale, peggiorando sempre, e il ciclo &egrave; sempre pi&ugrave; incompleto. Questa volta, Dio rifiut&ograve; di liberare il suo popolo. Dio rispose agli Israeliti che li aveva liberati diverse volte, prima di tutto dagli Egiziani con Mos&egrave;, poi durante i 40 anni nel deserto, e diverse volte al tempo dei giudici. Eppure, dopo ogni liberazione, gli Israeliti servirono gli altri d&egrave;i. Basta! Il Signore non li avrebbe pi&ugrave; liberati. Avevano scelto di seguire altri d&egrave;i; dovevano chiedere a quei d&egrave;i di salvarli dalla loro angoscia.</p>
<p>Dopo il rifiuto da parte di Dio, gli Israeliti capirono il loro errore e (solo allora) tolsero gli idoli che adoravano. Per&ograve;, era troppo tardi; Dio non rispose pi&ugrave;. Bench&eacute; il Signore si addolorasse per l'afflizione di Israele, non promise la loro liberazione n&eacute; suscit&ograve; un liberatore.</p>
<p>Intanto, gli Ammoniti si accamparono in Galaad, una parte del territorio di Israele all'est del fiume Giordano. Anche gli Israeliti si accamparono in Galaad, ma non avevano ancora qualcuno per comandare l'esercito, siccome Dio non aveva nominato un giudice. Per&ograve;, decisero che chi avrebbe cominciato l'attacco contro gli Ammoniti sarebbe stato il capo di tutto il Galaad.</p>
<p>Il racconto biblico, a questo punto, fa un salto indietro, per parlare delle origini di Iefte. Iefte era un uomo forte e valoroso, e viveva con la sua famiglia. Per&ograve;, diversamente dagli altri figli di suo padre, era il figlio del padre con una prostituta. I suoi fratellastri, figli della moglie del padre, scacciarono Iefte dalla famiglia, togliendo la sua eredit&agrave;. Era, quindi, un uomo senza niente, senza famiglia e senza onore. Fra parentesi, vediamo ancora una volta come Dio usa quelli disprezzati dal mondo. Come conseguenza, Iefte fugg&igrave; dalla sua famiglia ad un paese lontano, e si mise al capo di una banda di avventurieri che faceva incursioni. In questo modo Iefte impar&ograve; come combattere e come condurre dei soldati.</p>
<p>Ritorniamo alla situazione disperata degli Israeliti: gli Ammoniti erano alla porta e gli Israeliti erano senza condottiero. Si ricordarono di Iefte, scacciato via tempo fa, andarono a cercarlo, e gli chiesero di guidarli in battaglia. Iefte rispose, naturalmente, "Ma mi avete odiato e scacciato via! Siete qui solo perch&eacute; siete nell'angoscia!" Gli Israeliti accordarono, "S&igrave;, &egrave; proprio perch&eacute; siamo nell'angoscia che te lo stiamo chiedendo". Iefte mise una condizione: "Se il Signore mi dar&agrave; la vittoria, io sar&ograve; il capo di tutto il territorio". Gli Israeliti non avevano scelta e promise, "Sarai il nostro condottiero per la battaglia, e poi il nostro capo dopo la vittoria".</p>
<p>A questo punto, Iefte intraprese una strategia diplomatica. Mand&ograve; un messaggio agli Ammoniti per chiedere perch&eacute; volessero combattere contro gli Israeliti. Gli Ammoniti risposero che quando Israele usc&igrave; dall'Egitto, si impadron&igrave; del loro territorio. Se Israele avesse restituito quel territorio agli Ammoniti, non avrebbero combattuto.</p>
<p>Per&ograve;, Iefte conosceva la storia del suo popolo. Durante i 40 anni nel deserto dopo l'esodo, Israele voleva attraversare quel territorio in pace, ma c'erano gli Amorei (e non gli Ammoniti) che rifiutarono e che combatterono contro Israele. Israele vinse la battaglia e si impadron&igrave; del territorio, che quindi non era mai stato di Ammon. Cos&igrave; il Signore aveva dato quel territorio a Israele, Chemos il Dio di Ammon (prosegu&igrave; Iefte) vi aveva dato il vostro. Israele ci aveva abitato da 300 anni, e non l'avrebbe restituito. Il Signore avrebbe giudicato che aveva ragione!</p>
<p>Il re degli Ammoniti non diede ascolto a Iefte, e la guerra era inevitabile.</p>
<p>Lo Spirito del Signore poi venne su Iefte, come era normale per i giudici, anche se non era suscitato n&eacute; nominato giudice da Dio. Per&ograve;, Dio pu&ograve; usare chiunque vuole. Iefte port&ograve; l'esercito di Israele verso Ammon. Con la battaglia imminente, e consapevole che &egrave; Dio che d&agrave; la vittoria, fece un voto al Signore: "Se tu mi dai nelle mani i figli di Ammon, chiunque uscir&agrave; dalla porta di casa mia per venirmi incontro, quando torner&ograve; vincitore sugli Ammoniti, sar&agrave; del Signore e io l'offrir&ograve; in olocausto".</p>
<p>Quindi Iefte marci&ograve; contro Ammon, il Signore gli diede la vittoria, e ci fu una grandissima sconfitta e umiliazione per Ammon.</p>
<p>Iefte torn&ograve; a casa tutto contento per la vittoria... fino a quando dalla casa usc&igrave; sua figlia, la sua unigenita, con grande gioia in musica e danza. Voleva celebrare l'impresa del padre, invece fu sacrificata dal padre.</p>
<p>Iefte era angosciato a causa di quello che era successo, perch&eacute; aveva fatto il voto di offrire in olocausto chi sarebbe uscito di casa. La figlia gli disse che doveva adempiere la sua promessa, siccome Dio gli aveva permesso di sconfiggere gli Ammoniti. Voleva solo che suo padre le concedesse due mesi di lutto con le amiche, che Iefte permise. Cos&igrave; avvenne, e poi fu uccisa in olocausto. In seguito, fu ricordata ogni anno dalle donne d'Israele.</p>
<p>L'ultimo avvenimento descritto &egrave; la lite con la trib&ugrave; di Efraim. Gli Efraimiti si lamentarono con Iefte che non avevano combattuto contro Ammon, come avevano fatto anche con Gedeone (Giudici 8:1-3). Iefte rispose che li aveva chiamati ma non vennero. Invece, lui aveva posto a repentaglia la sua vita e Dio gli aveva dato la vittoria. Diversamente da quello che era successo con Gedeone, la risposta non calmarono gli Efraimiti, che mossero guerra contro Iefte e quelli di Galaad, il suo territorio. Iefte sconfisse gli Efraimiti, e mentre scappavano fece una strage. Siccome quelli di Efraim avevano un certo accento e non potevano pronunciare il suono "sci", a quelli trovati durante la fuga dal campo di battaglia fu chiesto di pronunciare la parola "scibbolet". Chi la pronunciava "sibbolet" venne scannato.</p>
<p>Questo avvenimento era l'inizio dello smantellamento della nazione d'Israele, il popolo scelto da Dio e speciale per Dio. Invece di adorare solo il Signore che li aveva liberati per essere il suo possesso, adoravano tanti altri d&egrave;i e idoli. Invece di essere un popolo unito per Dio e come testimonianza alle altre nazioni, era trib&ugrave; contro trib&ugrave;. Erano scesi tanto sulla spirale della ribellione, ma purtroppo non erano neanche arrivati in fondo. L'auto-distruzione del popolo di Dio aumenter&agrave; molto prima di arrivare alla fine del libro dei Giudici.</p>
<p>Intanto, Iefte fu giudice d'Israele per sei anni, poi mor&igrave; e fu sepolto in una citt&agrave; di Galaad, anche se non &egrave; detto in quale.</p>
<h2>1. Dio ci d&agrave; quello che desideriamo</h2>
<p>La prima riflessione su quello che possiamo imparare dalla vita di Iefte &egrave; che spesso Dio ci abbandona ai nostri desideri. Non sempre, perch&eacute; nella sua grazia ci pu&ograve; dare di pi&ugrave; o di meglio di quanto desideriamo. Molti, per esempio, sono toccati da Dio e sono salvati da lui proprio quando non lo cercavano, ma desideravano tutt'altro. Per&ograve;, spesso succede come in Giudici 10:11-15:</p>
<blockquote>Il SIGNORE disse ai figli d'Israele: &laquo;Non vi ho liberati dagli Egiziani, dagli Amorei, dai figli di Ammon e dai Filistei? Quando i Sidoni, gli Amalechiti e i Maoniti vi opprimevano e voi gridaste a me, non vi liberai dalle loro mani? Eppure, mi avete abbandonato e avete servito altri d&egrave;i; perci&ograve; io non vi liberer&ograve; pi&ugrave;. Andate a gridare agli d&egrave;i che avete scelto; vi salvino essi nel tempo della vostra angoscia!&raquo; I figli d'Israele dissero al SIGNORE: &laquo;Abbiamo peccato; facci tutto quello che a te piace; soltanto, te ne preghiamo, liberaci oggi!&raquo;</blockquote>
<p>Abbiamo visto qualcosa di simile nel racconto di Abimelec: Dio fa ricadere il male che si fa, e abbiamo le conseguenze delle nostre scelte. Qui invece Dio lasci&ograve; agli Israeliti gli idoli che avevano scelto.</p>
<p>Pu&ograve; succedere anche a noi. Se decidiamo di mettere la nostra fiducia in un idolo, forse avremo solo l'aiuto dell'idolo e non del Dio onnipotente. Per esempio, spesso pensiamo di essere capaci e competenti, per cui non preghiamo quanto dovremmo. Tanto riusciamo a gestire la propria vita senza Dio! Come conseguenza, Dio non ci d&agrave; niente che non possiamo ottenere da soli, perch&eacute; in realt&agrave; non lo desideriamo. Preferiamo vivere orgogliosamente con la delusione che possiamo fare del tutto, e ci accontentiamo di una vita normale. E quando arrivano la difficolt&agrave; e la disgrazia, magari gridiamo al Dio, ma ci risponde di farcela con le proprie forze, perch&eacute; di esse ci siamo fidati. Quello che dobbiamo fare invece &egrave; fidarci del Dio che pu&ograve; fare infinitamente pi&ugrave; di quanto possiamo immaginare o desiderare, per vivere una vita che solo lui pu&ograve; darci quando affidiamo tutto a lui in preghiera.</p>
<h2>2. La pazienza di Dio non &egrave; infinita</h2>
<p>Sempre in Giudici 10:11-15:</p>
<blockquote>Il SIGNORE disse ai figli d'Israele: &laquo;Non vi ho liberati dagli Egiziani, dagli Amorei, dai figli di Ammon e dai Filistei? Quando i Sidoni, gli Amalechiti e i Maoniti vi opprimevano e voi gridaste a me, non vi liberai dalle loro mani? Eppure, mi avete abbandonato e avete servito altri d&egrave;i; perci&ograve; io non vi liberer&ograve; pi&ugrave;. Andate a gridare agli d&egrave;i che avete scelto; vi salvino essi nel tempo della vostra angoscia!&raquo; I figli d'Israele dissero al SIGNORE: &laquo;Abbiamo peccato; facci tutto quello che a te piace; soltanto, te ne preghiamo, liberaci oggi!&raquo;</blockquote>
<p>Dopo diversi giri del ciclo, Dio ebbe abbastanza e dichiar&ograve; che non avrebbe pi&ugrave; liberato Israele. Dobbiamo stare attenti a come esprimiamo questo punto, perch&eacute; dobbiamo anche affermare che la misericordia di Dio &egrave; invece infinita. Il Signore non si stufa mai di perdonare, non c'&egrave; nessuno peccato troppo grande che non pu&ograve; essere perdonato n&eacute; nessuna quantit&agrave; di peccati troppo grande da essere perdonati. Il motivo per cui Dio disse che non li avrebbe pi&ugrave; liberati era l'insincerit&agrave; degli Israeliti. Il loro ravvedimento era un ravvedimento di convenienza. Erano in angoscia e decisero di chiedere aiuto a Dio; dopo la liberazione sarebbero ritornati ai loro idoli, come avevano fatto diverse volte nel passato. Dio era anche misericordioso e poteva perdonarli e salvarli, ma la sua pazienza verso questo ravvedimento insincero era finita.</p>
<p>&Egrave; simile a qualcuno a cui non piace andare dal dentista. Quando ha mal di dente, prende delle bustine antidolorifici fino a quando non ce la fa pi&ugrave;, e poi si arrende e va dal dentista per sistemare i denti. Il dentista fa delle raccomandazioni di pulire bene i denti, di usare il filo interdentale, e cos&igrave; via, che la persona ignora e invece fa quello che gli pare meglio. Fino a quando arriva la prossima caria. La persona non va dal dentista per avere denti sani e vivere nel modo giusto, non c'&egrave; un rapporto appropriato con il dentista, ma il dentista esiste solo per aiutare nella difficolt&agrave;.</p>
<p>Cos&igrave; facciamo anche noi confessiamo a Dio ogni settimana o addirittura ogni giorno, e poi non pensiamo pi&ugrave; a Dio fino alla prossima volta. C'&egrave; la stessa insincerit&agrave;. Inoltre, il fatto che Dio non punisce subito per i nostri sbagli non vuol dire che non lo far&agrave; mai. Sta solo aspettando il nostro ravvedimento (2P 3:9). Mentre la sua misericordia davanti a un ravvedimento sincero &egrave; infinito, la sua pazienza non lo &egrave; e nessuno ce la far&agrave; franca davanti alla sua giustizia perfetta.</p>
<h2>3. Non manipolare Dio</h2>
<p>Sebbene Dio non suscitasse un giudice n&eacute; un liberatore, n&eacute; chiamasse Iefte a guidare il suo popolo, leggiamo in Giudici 11:29-32</p>
<blockquote>Allora lo Spirito del SIGNORE venne su Iefte, che attravers&ograve; Galaad e Manasse, pass&ograve; a Mispa di Galaad e da Mispa di Galaad mosse contro i figli di Ammon. Iefte fece un voto al SIGNORE e disse: &laquo;Se tu mi dai nelle mani i figli di Ammon, chiunque uscir&agrave; dalla porta di casa mia per venirmi incontro, quando torner&ograve; vincitore sugli Ammoniti, sar&agrave; del SIGNORE e io l'offrir&ograve; in olocausto&raquo;.</blockquote>
<p>La vittoria sugli Ammoniti apparteneva al Signore, ed era possibile solo perch&eacute; Dio, attraverso il suo Spirito, operasse tramite Iefte. Anche Iefte diverse volte afferm&ograve; che era Dio che gli diede la vittoria. Aveva una fede, pur una fede imperfetta, abbastanza fede per essere incluso nell'elenco degli eroi della fede in Ebr 11:32-33: "Il tempo mi mancherebbe per raccontare di Gedeone, Barac, Sansone, Iefte, Davide, Samuele e dei profeti, i quali per fede conquistarono regni, praticarono la giustizia, ottennero l'adempimento di promesse...". Per&ograve;, la fede che aveva era messa in secondo piano da questo voto sciocco di sacrificare una persona se Dio gli avrebbe dato la vittoria.</p>
<p>Dobbiamo essere chiari: n&eacute; il voto n&eacute; l'olocausto erano buoni o giusti. Erano un abominio per il Signore, mai voluti e mai richiesti. Dobbiamo essere inorriditi da quello che &egrave; successo. Era forse un voto avventato, impulsivo, imprudente, o senza riflettere? Non sembra, perch&eacute; non era una cosa da dire o da fare alla leggera, se non era una pratica comune. Infatti, i sacrifici umani erano un modo per guadagnare il favore degli d&egrave;i dei Cananei, che (come abbiamo visto) Israele adorava. Iefte, abituato ai modi degli idoli, pens&ograve; che per ottenere un grosso favore da Dio, doveva fare un'offerta enorme a lui. E cos&igrave; sarebbe stato, pi&ugrave; grande di quanto si aspettasse: non solo una vita umana qualsiasi, ma di sua figlia, di sua figlia unigenita. Aveva una fede in Dio, voleva affidare a Dio la battaglia, ma non conosceva bene il vero Dio e ha pensato di manipolare Dio, di costringerlo a agire come voleva, di comprare il suo favore.</p>
<p>Noi non vogliamo sacrificare nessuno. Ma affermazioni come "Dio, se tu mi dai questo (un lavoro, un marito, una guarigione, o altro), io ti far&ograve; questo o io ti dar&ograve; quello" &egrave; sempre manipolazione. Non abbiamo niente da dare a Dio che lui non abbia gi&agrave;. Non &egrave; mai tentato dalle nostre promesse. &Egrave; come se un nostro figlio dicesse, "Se mi lasci guardare la TV per tutto il giorno, io ti dar&ograve; 50 centesimi". Rifiuteremmo perch&eacute; sappiamo che non gli farebbe bene, e una promessa di spiccioli non ci interessa.</p>
<p>A volte facciamo in altri modi, per essere "Dio, siccome non mi hai dato quello che volevo, non andr&ograve; pi&ugrave; in chiesa" o "Perch&eacute; non hai risposto alla mia preghiera? Io ho fatto cos&igrave; tanto per te e ho sempre fatto quello che volevi". Dio non pu&ograve; essere manipolato!</p>
<h2>4. L'onore di una fede umile</h2>
<p>Come &egrave; andato a finire per i protagonisti di questo racconto? Abbiamo gi&agrave; visto che Israele perse la sua identit&agrave; come popolo unito e popolo di Dio.</p>
<p>La fine di Iefte &egrave; descritta in Giudici 12:7: "Iefte fu giudice d'Israele per sei anni. Poi Iefte, il Galaadita, mor&igrave; e fu sepolto in una delle citt&agrave; di Galaad". Dopo tutti i suoi sforzi per diventare capo, fu il giudice per soli sei anni, il periodo pi&ugrave; breve di tutti i giudici. Non &egrave; neanche scritto che Israele ebbe pace in questo periodo, forse era ancora attaccato dai suoi nemici. Era senza discendenza, avendo ucciso la sua unigenita figlia che era ancora vergine - nessuno avrebbe portato avanti il suo nome, la sua famiglia era estinta con lui. Non si sa neanche dove fosse sepolto, solo che era in qualche citt&agrave; di Galaad. Non c'era neanche una tomba per ricordare le sue imprese.</p>
<p>Come detto prima, il racconto di Iefte &egrave; in mezzo ai racconti di cinque giudici minori. Minori perch&eacute; ci sono solo due o tre versetti per ognuno, ma in realt&agrave; ai loro tempi erano pi&ugrave; importanti di Iefte.</p>
<p>Iefte fu giudice per sei anni, ma prima di lui Tola fu giudice per 23 anni e Iair per 22 anni; dopo di Iefte i periodi erano pi&ugrave; brevi (il ciclo &egrave; sempre in realt&agrave; una spirale in discesa) ma comunque pi&ugrave; lunghi di Iefte - Ibsan per sette anni, Elon per dieci, Abdon per otto.</p>
<p>Iefte non aveva nessuna discendenza. Ma Iair ebbe 30 figli che cavalcavano 30 asini (un simbolo di potere, siccome gli Israeliti non usavano i cavalli) e governavano 30 citt&agrave; che portavano il nome di Iair. Ibsan 30 figli e 30 figlie con alleanze con 60 citt&agrave;, Abdon 40 figli e 30 nipoti su 70 asini.</p>
<p>Iefte fu sepolto in una citt&agrave; sconosciuta, ma Tola a Samir, Iair a Camon, Ibsan a Betlemme, Elon ad Aialon, Abdon a Piraton.</p>
<p>Iefte cerc&ograve; il potere (forse perch&eacute; si trovava importante quando scacciato dai fratelli), sulle persone e anche su Dio tramite le sue manipolazioni, per&ograve; alla fine non aveva niente: poco tempo come capo, che era quello che desiderava, nessuna famiglia, e una tomba dimenticata.</p>
<p>Della figlia &egrave; scritta invece in Giudici 12:7,</p>
<blockquote>Alla fine dei due mesi, torn&ograve; da suo padre; ed egli fece di lei quello che aveva promesso. Lei non aveva conosciuto uomo. Di qui venne in Israele l'usanza che le figlie d'Israele vadano tutti gli anni a celebrare la figlia di Iefte, il Galaadita, per quattro giorni.</blockquote>
<p>La figlia fu ricordata e celebrata ogni anno. Aveva una fede che non cerc&ograve; il proprio benessere, che sapeva che Dio era sovrano su tutto, e che era disposta a pagare il prezzo per gli errori altrui. Questa fede umile che va onorata ci porta verso Ges&ugrave;, che &egrave; onorato per gli stessi motivi.</p>
<blockquote>Ciascuno, con umilt&agrave;, stimi gli altri superiori a se stesso, cercando ciascuno non il proprio interesse, ma anche quello degli altri. Abbiate in voi lo stesso sentimento che &egrave; stato anche in Cristo Ges&ugrave;... Trovato esteriormente come un uomo, umili&ograve; se stesso, facendosi ubbidiente fino alla morte, e alla morte di croce. Perci&ograve; Dio lo ha sovranamente innalzato e gli ha dato il nome che &egrave; al di sopra di ogni nome. Fili 2:3-5,8-9</blockquote>
<p>Dobbiamo avere lo stesso sentimento di Cristo Ges&ugrave;, che umilmente stimava altri superiori a se stesso e si umili&ograve; fino alla morte. Perci&ograve; Dio l'ha onorato pi&ugrave; di chiunque altro.</p>
<blockquote>Diceva: &laquo;Abb&agrave;, Padre! Ogni cosa ti &egrave; possibile; allontana da me questo calice! Per&ograve;, non quello che io voglio, ma quello che tu vuoi&raquo;. Mc 14:36</blockquote>
<p>Dio &egrave; sovrano anche nella morte di Ges&ugrave;, e la sua volont&agrave; va seguita.</p>
<blockquote>Oltraggiato, non rendeva gli oltraggi; soffrendo, non minacciava, ma si rimetteva a colui che giudica giustamente; egli ha portato i nostri peccati nel suo corpo, sul legno della croce, affinch&eacute;, morti al peccato, vivessimo per la giustizia. 1P 2:23-24</blockquote>
<p>Ges&ugrave; era umile verso il Padre affidando la sua vita e la sua morte a lui, e cos&igrave; ha pagato il prezzo per i nostri errori, i nostri peccati.</p>
<p>Come tutti i giudici, Iefte era un uomo di fede imperfetta. Vediamo quello che Dio pu&ograve; fare attraverso le persone, ma vediamo anche la necessit&agrave; di desiderare solo Dio per ricevere lui, di essere sinceri nel nostro ravvedimento, e di non manipolare Dio.</p>
<p>Ma soprattutto, anche noi dobbiamo ricordare la figlia di Iefte, dobbiamo ricordare e celebrare Ges&ugrave; Cristo, esempi di una fede umile, una fiducia in Dio, e un sacrificio di s&eacute; per il bene degli altri.</p>

<?
$n=11;
require("indice.php");
require("../../piede.php");
?>

