<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 3]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 3]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Un Levita, i Beniaminiti, e tutto Israele (Giudici 19-21)</h1>
<p>Questi sono forse i tre capitoli pi&ugrave; brutti della Bibbia, perch&eacute; illustrano quello che succede quando si arriva in fondo alla spirale, quando si &egrave; senza freno e senza Dio (anche se c'&egrave; una certa religiosit&agrave; in questo brano, ma non &egrave; seguire il Dio vero e vivente), quando si fa quello che pare meglio a s&eacute;.</p>
<p>Infatti siamo ricordati che questo &egrave; il messaggio dei capitoli, perch&eacute; il primo versetto e l'ultimo versetto ripetono il tema:</p>
<blockquote>In quel tempo, non vi era re in Israele; ognuno faceva quello che gli pareva meglio. Giudici 19:1; 21:25</blockquote>
<p>dove la seconda met&agrave; del versetto &egrave; implicito in Giudici 19:1, come lo era in Giudici 18:1. Mentre i capitoli 17-18 descrivono il crollo spirituale di Israele (faceva quello che gli pareva meglio per adorare Dio, che era l'idolatria), in questi capitoli c'&egrave; il crollo morale (faceva quella che gli pareva meglio agli altri, che era il male). Il crollo morale &egrave; spesso la conseguenza naturale del crollo spirituale.</p>
<p>Inoltre, viene descritti in questi capitoli la fine della nazione unita di Israele, del popolo di Dio, e che ormai gli Israeliti sono oppressi dagli Israeliti stessi, e non c'&egrave; pi&ugrave; un liberatore n&eacute; un desiderio di essere liberati dallo stato di poter fare quello che pare meglio per s&eacute; stessi.</p>
<h2>1. Il Levita (19:1)</h2>
<p>Un Levita non era un sacerdote, ma un aiutante nel santuario o al tabernacolo, o aveva qualche altro compito religioso secondario in diverse citt&agrave; sparse per il territorio di Israele. Dovevano avere, quindi, una buona conoscenza di Dio e come servirlo e ubbidirgli. Questo Levita, per&ograve;, abitava in qualche paese sperduto e sconosciuto in montagna, e non in una delle citt&agrave; levitiche. Aveva anche una concubina, per cui non si teneva al comandamento di una moglie sola. Perch&eacute; no? Perch&eacute; faceva quello che gli pareva meglio.</p>
<h2>2. La concubina (19:2)</h2>
<p>La concubina per&ograve; fu infedele al Levita, cio&egrave; commise adulterio. Alcuni invece traducono la frase, "si arrabbi&ograve; con il marito". In ogni caso, se ne and&ograve; a casa sua a Betlemme, lasciando il marito dopo aver sbagliato. Perch&eacute; fece cos&igrave;? Perch&eacute; faceva quello che le pareva meglio.</p>
<h2>3. Tu</h2>
<p>Vorrei fare una pausa di riflessione a questo punto, perch&eacute; da qui in poi quello che verr&agrave; descritto sembrer&agrave; sempre pi&ugrave; lontano dalla tua esperienza personale. Certo, non sar&agrave; molto lontano da quello che vediamo nel telegiornale, che parla spesso di femminicidi, guerre, e stupri. Ma raramente succedono a te direttamente, e almeno tu non li farai mai. Per questo motivo, &egrave; facile pensare che questi capitoli non hanno niente a che fare con la tua esperienza.</p>
<p>Per&ograve;, tutto il resto dei capitoli sar&agrave; la conseguenza delle scelte apparentemente insignificanti di persone anonime in un paesino sperduto e sconosciuto. Forse seguire Dio nel tuo modo, o avere rapporti sessuali con qualcuno che non &egrave; il marito o la moglie, e addirittura arrabbiarti, non sembrano cos&igrave; gravi. Dopotutto, non fanno male a nessun altro, potresti ragionare. In realt&agrave;, come vedremo in questi capitoli, possono avere risultati gravissimi, e possono provocare tanto male nella famiglia, ma anche nella tua citt&agrave;, e addirittura nell'intera nazione.</p>
<h2>4. Il padre della concubina (19:3-9)</h2>
<p>Dopo quattro mesi, il Levita and&ograve; a Betlemme per parlare con la sua concubina e per riportarla a casa. Il padre della concubina lo accolse a casa sua, e per tre giorni fecero festa mangiando e bevendo.</p>
<p>In italiano, esiste il detto, "L'ospite &egrave; come il pesce - dopo tre giorni puzza". Una frase simile non potrebbe esistere in una cultura di onore e vergogna, in cui l'ospitalit&agrave; &egrave; molto importante. Piuttosto, in questo caso &egrave; pi&ugrave; come, "Colui che ospita &egrave; come il pesce - dopo tre giorni puzza." Infatti, il quarto giorno il Levita cerca di partire presto, ma il padre della concubina dice di mangiare qualcosa prima di partire per fortificarsi per il viaggio. Alla fine, mangiano e bevono tutto il giorno, e poi il padre insiste che rimanga anche quella notte.</p>
<p>Il quinto giorno, il Levita cerca di partire presto, ma il padre della concubina dice di mangiare qualcosa prima di partire per fortificarsi per il viaggio. Alla fine, mangiano e bevono tutto il giorno, e poi il padre insiste che rimanga anche quella notte. Per&ograve; questa volta il Levita decide di partire, anche se faceva tardi.</p>
<p>L'ospitalit&agrave; &egrave; giusta. Per&ograve;, qui &egrave; una scusa per la baldoria eccessiva piuttosto di fare quello che si doveva fare. Potrebbe sembrare poco, ma di nuovo le conseguenze erano gravi perch&eacute; il Levita non riusc&igrave; a ritornare a casa in una giornata. Perch&eacute; si davano al divertimento invece di ritornare a casa? Perch&eacute; ognuno faceva quello che gli pareva meglio.</p>
<h2>5. Il viaggio (19:10-15)</h2>
<p>Il Levita, la concubina, e il servo partirono, ma riuscirono solo a arrivare a Gerusalemme, che era 10 chilometri al nord. Era gi&agrave; tardi, ma siccome era ancora una citt&agrave; dei Gebusei e non degli Israeliti (Israele l'avrebbe catturata all'inizio del regno di Davide), il Levita decise di passare oltre, fino a Ghibea, che stava altri 6 chilometri a nord. Quindi arrivarono dopo il tramonto, e si fermarono nella piazza della citt&agrave;, sperando di trovare ospitalit&agrave; oppure di dormire proprio l&igrave; nella piazza.</p>
<p>L'ironia &egrave; che non volevano restare a Gerusalemme perch&eacute; era dei Cananei, che Israele aveva dovuto scacciare perch&eacute; malvagi. Ma ormai Israele era pi&ugrave; malvagio dei Cananei, e sarebbe stato pi&ugrave; sicuro stare la notte a Gerusalemme.</p>
<p>Perch&eacute; in Israele ognuno faceva quello che gli pareva meglio.</p>
<h2>6. Quelli di Ghibea (19:15-26)</h2>
<p>Nessuno di quelli di Ghibea offr&igrave; ospitalit&agrave; ai tre viaggiatori. Potresti pensare che era ovvio, non si pu&ograve; permettere che sconosciuti restino in casa tua. Per&ograve;, nelle culture antiche era una situazione vergognosa e scioccante. Dovevano essere tutti un popolo unico di Dio, dei fratelli spirituali, ma gli Israeliti avevano perso questa loro identit&agrave;. Perch&eacute; ognuno faceva quello che gli pareva meglio.</p>
<p>Per&ograve;, c'era un uomo, un vecchio, che era della stessa parte (la zona montuosa) della trib&ugrave; di Efraim. Era quindi uno "straniero" a Ghibea in mezzo ai Beniaminiti. Quest'uomo accolse il Levita, la concubina, e il servo in casa sua - forse non perch&eacute; era pi&ugrave; accogliente verso gli sconosciuti, ma perch&eacute; voleva aiutare qualcuno della sua zona.</p>
<p>Mentre facevano festa, mangiando e bevendo, alcuni uomini perversi della citt&agrave; arrivarono e comandarono al vecchio di far uscire il suo ospite, il Levita, perch&eacute; volevano abusare di lui. Cio&egrave;, volevano commettere lo stupro, l'omosessualit&agrave;, e l'inospitalit&agrave;. Quello che chiesero &egrave; orrendo e dobbiamo essere sconvolti. Ma facevano semplicemente quello che pareva meglio a loro.</p>
<p>Il vecchio rispose che non dovevano commettere un'azione cos&igrave; malvagia e un'infamia. Propose invece agli uomini perfidi di prendere sua figlia vergine e la concubina da abusare. In questo modo sarebbe stata solo un'infamia (stupro) invece di tre - la concubina non contava come ospite agli occhi del vecchio. Certo, non &egrave; meglio cos&igrave; al livello morale, ma il vecchio avrebbe potuto almeno giustificarsi, e dire che non era colpevole di inospitalit&agrave;. Perch&eacute; voleva fare quello che pareva meglio per lui, mica per la figlia o per la concubina.</p>
<p>Quando i perfidi di Ghibea rifiutarono la controproposta, il Levita risolse il problema a modo suo. Condusse fuori la sua concubina e la abbandon&ograve; alla folla. Loro abusarono di lei tutta la notte, fino alla mattina. Perch&eacute; il Levita fece una cosa cos&igrave; terribile alla sua concubina? Per salvare la propria pelle, perch&eacute; faceva quello che gli pareva meglio per lui.</p>
<p>La concubina, dopo questa notte da incubo, con le ultime forze che le erano rimaste, all'alba si trascin&ograve; fino alla porta del vecchio e croll&ograve;. Non riusc&igrave; neanche a gridare n&eacute; a bussare.</p>
<h2>7. Il Levita (19:27-30)</h2>
<p>Pi&ugrave; tardi quella mattina, con calma e apparentemente poco preoccupato, il Levita si alz&ograve; e usc&igrave; per proseguire il suo viaggio, e trov&ograve; la sua concubina sulla soglia della porta. L'unico motivo per cui si ricord&ograve; di lei era perch&eacute; si era quasi inciampato!</p>
<p>Con tutta la compassione di un sasso, senza rimorso, disse, "Alzati, andiamocene". Lei, quasi morta o forse gi&agrave; morta, non poteva rispondere. Il Levita quindi la caric&ograve; sull'asino e torn&ograve; a casa.</p>
<p>Perch&eacute; aveva un cuore cos&igrave; freddo, perch&eacute; era cos&igrave; incurante della sua concubina? Perch&eacute; faceva quello che gli pareva meglio.</p>
<p>Ritornato a casa, tagli&ograve; la concubina in 12 pezzi, che mand&ograve; alle 12 trib&ugrave; di Israele. Capirono che era successa una cosa terribile, e decisero di riunirsi per parlarne insieme.</p>
<p>Ovviamente, dobbiamo condannare il Levita che guardava solo ai suoi interessi personali, che non si interessava dei guai dei deboli, maltrattati, impotenti, e incapaci di difendersi. Per&ograve;, dobbiamo anche riflettere sul nostro atteggiamento e sul nostro comportamento verso i deboli e impotenti della nostra societ&agrave;: gli immigrati, gli zingari, i senzatetto, gli anziani, e tanti altri.</p>
<p>Nel giugno 2023, un sommergibile turistico imploso mentre portava cinque persone per guardare il relitto del Titanic. Nove aerei, due sottomarini a comando remoto, e circa &euro;6 milioni furono usati per cercarli. Se ne parlava molto allora. Quattro giorni prima, un peschereccio affond&ograve; vicino alla Grecia, con 500 profughi uccisi. Quattro giorni dopo, un barchino si ribalt&ograve; fra la Libia e Lampedusa: 40 morti e solo 5 sopravvissuti. Non molto fu speso per cercarli e salvarli, e se ne parlava poco. Perch&eacute;? Perch&eacute; non erano importanti secondo il mondo, mentre quelli del sommergibile erano ricchi e pi&ugrave; degni (secondo i valori comuni) di essere salvati.</p>
<h2>8. Gli Israeliti e i Beniaminiti (20:1-48)</h2>
<p>Quindi gli Israeliti si riunirono, o almeno 11 delle 12 trib&ugrave; si presentarono. Il Levita raccont&ograve; quello che era successo - dal suo punto di vista, tralasciando le sue colpe - e chiese agli Israeliti quello che avrebbero fatto. Chiaramente, il Levita non era interessato alla giustizia (che lo avrebbe messo in una cattiva luce) ma alla vendetta. Perch&eacute; faceva quello che gli pareva meglio, per soddisfare il suo desiderio di vendetta. Tutti gli Israeliti presenti decisero di distruggere la citt&agrave; di Ghibea.</p>
<p>Di nuovo, c'&egrave; tanta ironia in questi avvenimenti. Nessuno dei 12 giudici riusc&igrave; a radunare tutto Israele per liberare la nazione dai nemici. Nessuno dei 12 giudici riusc&igrave; a scacciare tutti i popoli dal paese, come Dio aveva comandato.</p>
<p>Ma questo Levita, egoista, spietato verso la concubina moribonda, si fece giudice e riusc&igrave; a radunare tutto Israele contro Israele stesso. Aveva sacrificato la sua concubina per salvare s&eacute; stesso; allora era disposto a sacrificare tanti Israeliti per ottenere la sua vendetta. Il pi&ugrave; grande nemico di Israele era Israele stesso.</p>
<p>Per&ograve;, in realt&agrave; non tutto Israele era presente. La trib&ugrave; dei Beniaminiti, la trib&ugrave; di quelli di Ghibea, non vennero all'incontro, e decisero invece di difendere Ghibea (e l'infamia che ci era commessa) invece di unirsi al resto di Israele.</p>
<p>Per questo motivo inizi&ograve; una guerra civile: 11 trib&ugrave; di Israele contro una trib&ugrave;, Beniamino. Ma Dio non aveva mai deciso e rivelato di agire in questo modo. Non era la sua guerra. Gli Israeliti si comportavano come pareva meglio a loro. Con la decisione gi&agrave; fatta, gli Israeliti chiesero soltanto, "Chi di noi salir&agrave; per primo a combattere contro i figli di Beniamino?" Dio rispose semplicemente, senza promettere niente, "Giuda salir&agrave; per prima" (Giudici 20:18). E Israele fu sconfitto da Beniamino.</p>
<p>La seconda volta, gli Israeliti piansero davanti al Signore, chiedendo, "Devo continuare a combattere contro i figli di Beniamino, mio fratello?" Dio rispose semplicemente, senza promettere niente, "Salite contro di loro" (Giudici 20:23). C'era pi&ugrave; ricerca di Dio e dipendenza da Dio, ma ancora fecero quello che gli pareva meglio. E Israele fu sconfitto da Beniamino.</p>
<p>La terza volta, gli Israeliti piansero, rimasero davanti al Signore, digiunarono, offrirono olocausti e sacrifici di riconoscenza davanti al Signore, chiedendo, "Devo continuare ancora a combattere contro i figli di Beniamino mio fratello, o devo cessare?" Questa volta, c'era pi&ugrave; dipendenza da Dio, pi&ugrave; desiderio di sapere quello che Dio voleva che facessero. E Dio rispose, promettendo, "Salite, poich&eacute; domani ve li dar&ograve; nelle mani" (Giudici 20:26-28). Israele fece un'imboscata e sconfisse Beniamino.</p>
<p>Solo quanto ti avvicini umilmente a Dio per fare la sua volont&agrave;, non per informarlo di quello che ti pare meglio, puoi sapere che Dio &egrave; dalla tua parte.</p>
<p>La giustizia di Dio &egrave; che chi sbaglia, paga. Per&ograve;, Israele ebbe una risposta inappropriata e esagerata. Cercarono di distruggere l'intera trib&ugrave; di Beniamino. Neanche tutti i nemici di Israele, tutti gli altri popoli di cui abbiamo letto nel libro dei Giudici, provarono a fare cos&igrave;. E gli Israeliti ci riuscirono, ammazzando non soltanto tutti i soldati, ma anche le donne e i bambini, tranne 600 uomini che si nascosero. Perch&eacute; fecero cos&igrave;? Forse per vendetta per gli Israeliti uccisi nelle prime due battaglie, forse per malvagit&agrave; (perch&eacute; il pi&ugrave; grande nemico di Israele era Israele), ma sicuramente perch&eacute; facevano quello che pareva meglio a loro e non a Dio.</p>
<p>Similmente, il pi&ugrave; grande nemico della fede spesso non &egrave; fuori di noi, ma dentro di noi. Non &egrave; la tentazione che ci allontana, ma il cuore che accoglie la tentazione per fare quello che gli pare meglio. Io ho visto alcuni allontanarsi dal Signore per la pressione o per l'influenza della mondanit&agrave;. Ho visto molti di pi&ugrave; allontanarsi dal Signore perch&eacute; volevano fare quello che pareva meglio a loro, nei campi della sessualit&agrave;, del tempo per il divertimento piuttosto che per il culto, dei soldi investiti per i propri interessi, dell'orgoglio di non cercare riconciliazione o perdono.</p>
<h2>9. Gli Israeliti e i pochi Beniaminiti (21:1-25)</h2>
<p>Dopo il massacro dei Beniaminiti, gli Israeliti ebbero rimorso e misericordia per la trib&ugrave;. Ebbero anche la faccia tosta per quasi incolpare Dio per quello che era successo: "Signore, Dio d'Israele, perch&eacute; mai &egrave; avvenuto questo in Israele? Perch&eacute; oggi c'&egrave; in Israele una trib&ugrave; di meno?" (Giudici 21:3). Non c'era nessuna risposta da Dio, ma la risposta sarebbe stata, "Perch&eacute; avete fatto quello che vi pareva meglio, non quello che io volevo".</p>
<p>Per questo motivo, gli Israeliti decisero di ripopolare la trib&ugrave; di Beniamino. Il primo problema era che c'erano soltanto 600 maschi rimasti e nessuna femmina. Il secondo problema era che avevano fatto un giuramento avventato: "Nessuno di noi dar&agrave; sua figlia in moglie a un Beniaminita" (Giudici 21:1,7).</p>
<p>Risolsero il giuramento sbagliato sfruttando un altro giuramento sbagliato. Avevano anche giurato che chi non era salito contro Ghilbea doveva essere messo a morte (Giudici 21:6). Fecero qualche ricerca, e scoprirono che quelli di Iabes in Galaad non erano venuti all'incontro. Quindi mandarono 12.000 soldati per uccidere tutti i maschi, i bambini, e le donne sposate di Iabes. Rimasero 400 femmine vergini.</p>
<p>Cos&igrave; sistemarono la cattiveria di violenza eccessiva e omicidi con ulteriori violenza e omicidi. Avevano ucciso tutte le donne di Beniamino; per correggere il loro errore bastava uccidere tutti gli uomini di Iabes! Perch&eacute; facevano cos&igrave;? Perch&eacute; facevamo quello che pareva meglio a loro.</p>
<p>Per&ograve; mancavano ancora 200 donne. Ecco il secondo schema malvagio e perverso. C'era una festa di paese a Silo. Gli altri 200 Beniaminiti furono mandati per rapire 200 ragazze che danzavano per le festivit&agrave;. Per gli Israeliti, tutto era risolto e si sentivano giustificati. Loro non avevano dato una moglie ai Beniaminiti. Ai padri che si lamentavano, dissero che le ragazze furono rapite e quindi i padri erano innocenti di aver dato una moglie ai Beniaminiti. Cio&egrave;, se non avessero accettato passivamente i rapimenti, sarebbero stati considerati colpevoli e puniti dagli altri Israeliti. E le donne rapite? Nessuno pensava a loro, perch&eacute; ogni immoralit&agrave; andava bene se metteva a posto la coscienza dei pi&ugrave; potenti. Doveva fare quello che pareva meglio per loro.</p>
<p>Tutto era cominciato con il rapimento e stupro di una concubina, che non era considerata neanche dal marito. Port&ograve; a tanta malvagit&agrave;, tanti morti, tanta infamia, e fin&igrave; con il rapimento e stupro di 200 ragazze. Gli Israeliti punirono il rapimento di una donna, ma loro fecero 200 volte peggio. Per salvarsi, buttarono via 200 donne, come il Levita per salvarsi butt&ograve; fuori la sua concubina. Perch&eacute; ognuno faceva quello che gli pareva meglio, non quello che era giusto. Guardavano la pagliuzza nell'occhio del fratello, ma non scorgevano la trave nel proprio occhio. O meglio: guardavano la trave nell'occhio del fratello, ma non le 200 trave nel proprio occhio.</p>
<h2>10. Conclusione</h2>
<p>Il libro dei Giudici termina cos&igrave; nel buio totale. Pi&ugrave; in fondo di cos&igrave;, Israele non poteva arrivare. Ma se leggiamo il resto della Bibbia, capiamo che c'era una piccola luce di speranza.</p>
<p>Ci voleva un re, ma un re giusto.</p>
<p>La trib&ugrave; di Beniamino era quasi distrutta per la loro malvagit&agrave;. Eppure il primo re di Israele, Saul, era da questa trib&ugrave;. Per&ograve;, siccome Israele voleva un "re come le altre nazioni", &egrave; quello che Dio gli diede, come si poteva aspettare dalla trib&ugrave; di Beniamino. Un re che si metteva sopra Dio, che faceva quello che gli pareva meglio e non quello che Dio voleva. Tuttavia, 1000 anni pi&ugrave; tardi, un altro Saul, sempre della trib&ugrave; di Beniamino, che si riteneva il principe dei peccatori perch&eacute; perseguitava la chiesa, ebbe gli occhi aperti da Ges&ugrave;. &egrave; conosciuto anche come Paolo, e dimostra che nessuno &egrave; oltre la misericordia di Dio, nonostante quanta malvagit&agrave; &egrave; stata fatta nel passato dalla persona o dagli antenati.</p>
<p>A causa dei due racconti alla fine di Giudici, la citt&agrave; di Betlemme ebbe una cattiva reputazione per molti anni. Era il paese dell'altro Levita che serv&igrave; Mica e poi i Daniti, e che era idolatra. Era il paese della concubina del Levita di questi capitoli. Proprio da l&igrave; venne Davide, il re secondo il cuore di Dio. Proprio da l&igrave; venne Ges&ugrave; Cristo, il re di cui avevamo bisogno, che faceva sempre la volont&agrave; di Dio, non quello che voleva lui ma quello che voleva il Padre celeste. Noi non diciamo, "Nel nostro tempo, non c'era re; ognuno faceva quello che gli pareva meglio", ma "Nel nostro tempo, c'era il Re dei re nel mondo, e noi facciamo quello che gli (al Re) pare meglio". E un giorno, ogni ginocchio si piegher&agrave; a lui e ogni lingua confesser&agrave; che Ges&ugrave; Cristo &egrave; il Signore, il Re dei re. Tutti faranno quello che pare meglio al Signore Cristo Ges&ugrave;, e ci sar&agrave; il regno perfetto in tutto il cosmo.</p>

<?
$n=16;
require("indice.php");
require("../../piede.php");
?>

