<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 3]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 3]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Mica e i Daniti (Giudici 17-18)</h1>
<p>Non ci sono pi&ugrave; giudici. C'&egrave; invece un epilogo al libro che contiene due racconti, quello di Mica, un Levita, e la trib&ugrave; di Dan nei capitoli 17 e 18, e quello di un Levita e la trib&ugrave; di Beniamino nei capitoli 19, 20, e 21. Non &egrave; chiaro in quale parte del periodo dei giudici si siano svolti questi racconti, ma &egrave; chiaro che il redattore del libro li abbia messi alla fine del libro per descrivere lo stato di Israele quando giunse in fondo alla spirale, quanto ognuno faceva quello che gli pareva meglio. Questi due capitoli descrivono il crollo religioso del popolo, mentre gli altri tre capitoli descrivono il crollo morale.
<p>Per&ograve;, questi capitoli non descrivono solo Mica e i Daniti in fondo alla spirale, ma anche l'esperienza universale dell'umanit&agrave; senza Dio. Di ognuno di noi quando respingiamo Dio come fecero gli Israeliti. Sicuramente abbiamo tutti subito le azioni di qualcuno che pensava di essere legge a s&eacute;, di poter fare quello che gli pareva. Forse un capo a lavoro che ti sfrutta. Se non ti piace, dice solo "Vattene, ci sono migliaia di persone pronte per prendere il tuo lavoro". O un collega che lavora male o &egrave; spesso assente per finte malattie, e tu devi sempre fare anche il suo lavoro. Forse qualcuno che ha danneggiato la tua macchina, strisciandola con una chiave e poi sparendo, o tamponandola mentre la macchina &egrave; parcheggiata e poi facendo finta di lasciare i propri recapiti su un biglietto sotto i tergicristalli. Forse ci sono cause legali contro di te e non sai difenderti. Forse qualcuno ti ha fregato illegalmente ma non puoi riottenere quello che hai perso. Forse hai subito attacchi fisici da persone pi&ugrave; forti di te (per esempio dei delinquenti, o anche il marito, un fatto che purtroppo succede troppo spesso), a cui non potevi rispondere. Forse sei stato bullizzato a scuola (oppure da adulti) da prepotenti che sapevano che potevi solo subire senza difenderti e che nessun altro ti avrebbe aiutato. Ti sei impotente, in bal&igrave;a dei capricci e dell'autogratificazione degli altri.
<p>Questi capitoli spiegano bene la causa di queste difficolt&agrave;, con un coro ripetuto due volte (Giudici 17:6; 21:15) e la prima met&agrave; del coro altre due volte (Giudici 18:1; 19:1).
<blockquote>In quel tempo non vi era re in Israele, ognuno faceva quello che gli pareva meglio.</blockquote>
<p>Ci sono alcuni modi per spiegare questa frase. Prima di tutto, che non c'era nessun re umano. Per&ograve;, l'autore del libro aveva gi&agrave; descritto il regno disastroso dell'usurpatore Abimelec, e scrisse dopo aver visto quello che tutti i malvagi re d'Israele avevano fatto (Giudici 18:30). Sapeva che i re umani non impedivano alle persone di peccare, anzi spesso erano peggiori dei sudditi e li trascinavano al peccato e all'idolatria. Un'altra spiegazione &egrave; che anche se non c'era un giudice o un re che li allontanava da Dio, gli Israeliti ce la facevano da soli. Ognuno faceva quello che voleva senza l'esempio di un re empio. La terza spiegazione &egrave; che avevano respinto Dio come re, tutti si comportavano come re della propria vita, potevano fare quello che volevano anche a danno degli altri.
<p>In ogni caso, il senso &egrave; chiaro per tutte e tre le spiegazioni. C'era un popolo senza costrizioni, senza limiti. Dio non era pi&ugrave; il loro re, ed erano come un cavallo selvatico senza freno in bocca, o forse meglio come un cane pericoloso, come un rottweiler, senza guinzaglio. Erano liberi di fare tutto quello che gli pareva meglio, tutto quello che volevano, senza che nessuno o niente potessero fermarli. E con questa libert&agrave;, il cuore umano inclina sempre verso il male.
<p>Questo spiega i casi che sono stati descritti all'inizio di questa sezione, quando non ti potevi difendere contro i prepotenti. Ma spiega anche il tuo cuore. Hai mai riflettuto su come saresti se non ci fosse un Dio a cui dovevi rendere conto? Io s&igrave;. Avrei iniziato con la mia educazione di essere gentile verso gli altri. Ma pian piano mi sarei reso conto che non aveva senso. Se siamo solo tante molecole in un sacco di pelle, perch&eacute; dovrei occuparmi degli altri? La mia coscienza mi avrebbe permesso di fare un po' di male, e quando ottenevo quello che volevo, avrei fatto di peggio, e cos&igrave; via lunga la spirale in discesa. Questo &egrave; l'unico atteggiamento coerente per qualcuno che non crede che ci sia un Re in cielo che ha sovrana autorit&agrave;. Se non c'&egrave; un Re divino, viviamo come se non ci fosse, e diventiamo re di noi stessi facendo quello che ci pare meglio. Certo, le leggi del paese ci limiterebbero, ma quando potremmo eludere o aggirare la legge, lo potremmo fare, e sarebbe giusto farlo per ottenere quello che noi desideriamo. Cos&igrave; pensano tanti, come dimostrato dal fatto che abbiamo migliaia di leggi e milioni di comma per regolare quasi ogni aspetto della nostra vita. Perch&eacute; se non ci fossero, tanti farebbero come pareva meglio a loro. Se tutto il mondo avesse Dio come re, servirebbero solo due leggi:
<blockquote>Ama il Signore Dio tuo con tutto il tuo cuore, con tutta l'anima tua, <br />con tutta la mente tua, e con tutta la forza tua. <br />Ama il tuo prossimo come te stesso. Marco 12:30-31</blockquote>
<p>In questo epilogo di cinque capitoli, vediamo Israele in fondo alla spirale, senza Dio. Non sono pi&ugrave; oppressi dai nemici ma da s&eacute; stessi. Non vogliono pi&ugrave; la liberazione, non vogliono Dio, vogliono solo fare quello che gli pare meglio. Ma non &egrave; solo una descrizione di un popolo antico. &Egrave; una descrizione di come sono tutti adesso, gli altri ma anche me e te, se non c'&egrave; il Re dei re nella propria vita.
<h2>1. Quando decidi la tua legge (17:1-6)</h2>
<p>&Egrave; pi&ugrave; comune che leggi o comandamenti o norme siano considerati giusti quando ci proteggono che quando li dobbiamo osservare. Qualche anno fa ho avuto una conversazione con un amico che era furibondo che era stato fregato dal datore di lavoro che non lo aveva pagato quello che gli spettava, ma allo stesso tempo l'amico riteneva che non fosse sbagliato lavorare in nero per non pagare le tassi che spettavano al governo. Non sono mai riuscito a fargli vedere la contraddizione. Similmente, spesso "non rubare" &egrave; considerato giusto se sono le nostre cose che non vanno rubate, ma non se si tratta di pirateria informatica, di cancelleria presa dal lavoro, del nostro tempo per cui siamo pagati, e mille altri modi in cui possiamo prendere quello che non &egrave; nostro.
<p>In questo brano, la madre di Mica scopr&igrave; che 1100 sicli d'argento (circa &euro;200.000) le furono rubati. Per lei, era un atto sbagliato e maledisse il ladro. Mica, suo figlio, che aveva rubato l'argento, forse spaventato dalla maledizione, confess&ograve;. Non c'era rimorso, e sicuramente non ravvedimento. Solo la paura della punizione, della maledizione. Anche la madre ad un tratto cambi&ograve; idea, in un completo rovesciamento ipocrita, convert&igrave; la maledizione in benedizione. Rubare &egrave; sbagliato se succede a lei, ma se suo figlio ruba non &egrave; un problema, anzi bisogna complimentarsi con lui perch&eacute; &egrave; stato bravo!
<p>In seguito a questa ambiguit&agrave; morale, c'&egrave; il crollo religioso. Non c'&egrave; il Re dei re che decide che &egrave; sbagliato rubare, quindi posso adorare Dio come voglio. Mica aveva gi&agrave; messo da parte l'ottavo dei 10 comandamenti ("Non rubare"); perch&eacute; non mettere da parte anche il secondo ("Non farti scultura e non ti prostrare davanti a loro")?
<p>Perch&eacute; capit&ograve; tutto questo? La sezione conclude con il riassunto:
<blockquote>In quel tempo non vi era re in Israele, ognuno faceva quello che gli pareva meglio. Giudici 17:6</blockquote>
<h2>2. Quando decidi il tuo rapporto con Dio (17:7-13)</h2>
<p>Credi che il Signore ti far&agrave; del bene, giusto? Forse vai spesso in chiesa, la chiesa giusta con un pastore bravo, dai dei soldi alla chiesa, magari i muri di casa sono pieni di targhe con versetti biblici, tutti vedono quanto religioso sei. Proprio come Mica.
<p>Un giorno un Levita arriv&ograve; a casa di Mica, cercando un luogo adatto per stabilirsi. Mica non riusc&igrave; a credere alla sua fortuna: assunse il levita come sacerdote personale, e per la modica cifra di &euro;2.000 per anno. Cos&igrave; aveva non soltanto un idolo personale ma anche un sacerdote personale. Sicuramente il Signore l'avrebbe benedetto, ragion&ograve;, quando avrebbe visto chi e cosa erano in casa sua (Giudici 17:13).
<p>Dall'altra parte il Levita, pur sapendo che il modo per un Levita di servire Dio era stabilito nella legge (al tabernacolo o nelle citt&agrave; levitiche delle varie trib&ugrave;, vivendo delle offerte libere del popolo), se ne era andato da casa sua per cercare un posto migliore. Neanche lui riusc&igrave; a credere alla sua fortuna: aveva trovato il posto fisso a tempo indeterminato, uno stipendio costante, ed era trattato come figlio e non come servo n&eacute; impiegato (Giudici 17:11).
<p>In tutto questo, Mica, sua madre, e il Levita sembravano sinceri nell'impegno religioso. Volevano la benedizione di Dio. Il problema era che erano diventati come i Cananei che dovevano scacciare. Invece di seguire il Re dei re nel modo che lui aveva stabilito, avevano deciso come gli parevano meglio come manipolare Dio e costringerlo a benedirli.
<p>Per&ograve;, come vedremo nel capitolo 18, Dio non era convinto che doveva benedire o ricompensare n&eacute; Mica n&eacute; il Levita per quello che avevano fatto. Dio non benedici te per il portafortuna, per il santino in macchina, per il crocifisso che indossi, per il pastore che segui (in presenza o su YouTube), per l'impegno, per la sincerit&agrave; o per le buone intenzioni. Il Re dei re richiede l'adorazione in verit&agrave;, come lui ci ha rivelato, e tu non puoi decidere come seguirlo nel modo che ti pare meglio.
<p>Infatti, per quale motivo Mica, sua madre, e il Levita avevano inventato la propria religione invece di seguire la legge rivelata? Il prossimo versetto, che &egrave; all'inizio del capitolo 18 ma in realt&agrave; &egrave; la conclusione di questo episodio, ce lo spiega:
<blockquote>In quel tempo, non vi era re in Israele. Giudici 18:1</blockquote>
<h2>3. Cosa ricevi quando fai quello che ti pare meglio (18:1-31)</h2>
<p>A questo punto, il racconto inizia a parlare dei Daniti, cio&egrave; la trib&ugrave; di Israele composta da tutti i discendenti di Dan, uno dei figli di Giacobbe. Dice che "cercava un suo territorio per stabilirvisi, perch&eacute;, fino a quei giorni, non le era toccata alcuna eredit&agrave; fra le trib&ugrave; d'Israele" (Giudici 18:1).
<p>In realt&agrave;, ai Daniti fu assegnato un territorio, ma non lo ricevettero perch&eacute; non ne presero possesso. Giosu&egrave; 19:40-48 spiega esattamente il loro territorio originale, ma aggiunge che avevano anche preso la citt&agrave; di Lesem (ossia Lais), un avvenimento che viene raccontato in questo capitolo. Per&ograve;, i Daniti non riuscivano a prendere possesso del territorio che Dio aveva dato a loro in eredit&agrave;; infatti, "gli Amorei respinsero i figli di Dan nella regione montuosa e non li lasciarono scendere nella valle" (Giudici 1:34).
<p>A questo punto, invece di impegnarsi per ottenere quello che Dio aveva promesso, oppure perch&eacute; non interessava quello che aveva promesso loro, mandarono degli esploratori per cercare un luogo che gli pareva meglio (Giudici 18:2). Questo &egrave; lo stesso atteggiamento quando Dio ti promette di dare tutto quello di cui hai bisogno, ma cerchi invece i soldi per avere tutto quello che vuoi. Oppure quando non ti interessa la promessa che Dio sar&agrave; con noi per sempre e che il suo amore ti basta, e cerchi rapporti, anche non sani, con altri per riempire il vuoto nel tuo cuore del bisogno di essere amato.
<p>Gli esploratori giungono alla casa di Mica, dove conoscono il Levita e chiedono se il viaggio avr&agrave; successo; lui risponde di s&igrave; (Giudici 18:3-6). Poi viaggiano verso nord, all'estremit&agrave; settentrionale del paese, e trovano la citt&agrave; di Lais. Gli abitanti vivevano al sicuro e tranquilli perch&eacute; lontani da altri nemici, ma erano anche lontani da eventuali alleati come i Sidoni (Giudici 18:7). Era un paese bello e facile da conquistare, ma anche fuori della terra promessa, fuori della benedizione divina. Nello stesso modo che molti oggi preferiscono avere una vita tranquilla e facile, come gli pare meglio, piuttosto di vivere in sottomissione a Dio con la benedizione di Dio.
<p>Quindi gli esploratori ritornano dagli altri Daniti, raccontano loro quanto bella era Lais, e li incoraggiano ad andare a prendere possesso della citt&agrave; (Giudici 18:8-10). La trib&ugrave; &egrave; d'accordo, e manda un piccolo esercito a Lais. Quell'esercito, mentre sta andando verso nord, passa la casa di Mica (Giudici 18:11-13). Quando sono arrivati alla casa, i cinque esploratori accennano ai soldati che c'erano un efod, degli idoli domestici, e un'immagine scolpita nella casa. Non serve dirlo due volte, i soldati capiscono, e eseguono un furto poco sottile. Mentre i cinque esploratori salutano il Levita e poi gli sottraggono tutto, i 600 uomini armati rimangono davanti alla porta come un ricordo silenzioso di chi era in comando in quella situazione, che possono fare quello che gli pare meglio. Il Levita protesta, chiedendo, "Che fate?", a cui riceve la risposta minacciosa, "Taci, mettiti la mano sulla bocca". Cio&egrave;, se sai quello che &egrave; meglio per te, sta zitto (Giudici 18:14-19). Non &egrave; una situazione completamente estranea a noi! Quando vedi l'ingiustizia o la prepotenza contro di te stesso o contro gli altri, alzare la voce per fermare l'ingiustizia pu&ograve; essere pericoloso. L'omert&agrave; non &egrave; n&eacute; nuova n&eacute; italiana!
<p>Poi la situazione peggiora - o migliora, dipende dal punto di vista. I Daniti offrono al Levita un nuovo lavoro. Invece di essere il sacerdote di una famiglia sola, poteva essere il sacerdote di un'intera trib&ugrave;. Una grande opportunit&agrave; per una promozione, un aumento di livello, magari anche un aumento di stipendio! Per lui, sicuramente un miglioramento dell'aspetto lavorativo. Per&ograve; per andare con i Daniti doveva rompere il suo impegno verso Mica, tradirlo, e collaborare con il furto contro cui un minuto prima protestava perch&eacute; ingiusto. Un dilemma difficile: tenere fermo ai suoi principi, alla giustizia, e all'ubbidienza a Dio, oppure unirsi ai prepotenti e diventare un oppressore piuttosto di un oppresso. In meno che non si dica, il Levita decise e si rallegr&ograve; nella nuova svolta nella sua vita, e rub&ograve; l'efod, gli idoli, e l'immagine scolpita (Giudici 18:19-20). Perch&eacute; fece questa scelta? Perch&eacute; faceva quello che gli pareva meglio per s&eacute; stesso, non quello che era meglio per Mica, neanche meglio per i Daniti, e sicuramente non meglio per Dio, il Re dei re.
<p>Che cosa ne pensa Mica di tutto questo? I Daniti si aspettano una reazione, e proteggono i loro bambini e i loro beni. Infatti, Mica insegue i ladri con alcuni vicini e si lamenta, "Avete portato via gli d&egrave;i che mi ero fatti e il mio sacerdote e ve ne siete andati. Che cosa mi rimane?" Per&ograve;, Mica non ha radunato abbastanza gente e i Daniti sono pi&ugrave; forti di lui, e i Daniti lo avvertono di stare zitto, minacciando di scagliarsi su di lui. Mica non pu&ograve; fare niente e se ne torna a casa sua (Giudici 18:21-26). Come negli esempi elencati all'inizio di questa sezione, &egrave; impotente contro la prepotenza dei pi&ugrave; forti che fanno quello che gli pare meglio.
<p>Per&ograve;, Mica &egrave; anche angosciato, perch&eacute; ha perso quello in cui sperava per essere benedetto da Dio - "Che cosa mi rimane?" Se decidi tu il modo di aver un rapporto di Dio, ricevi quello in cui hai posto la speranza, che delude sempre. Mica si &egrave; fidato di un idolo e di una statua, che non potevano salvare n&eacute; proteggere n&eacute; benedire. Inoltre, l'idolo era fatto di soldi rubati; era buono solo per essere rubato! Rubato dai Daniti, e poi sarebbe stato anche portato via dagli Assiri. Questo &egrave; anche un altro esempio di decidere la propria legge: Mica non aveva un problema quando lui ha rubato i soldi dalla madre (solo delle conseguenze della maledizione), ma era convinto che non era giusto rubare l'immagine fatta da quei soldi quando capit&ograve; a lui.
<p>In seguito, i Daniti arrivarono a Lais, che attaccarono. Come gli esploratori avevano detto, non c'era nessuno che la difendesse e i Daniti lo conquistarono (Giudici 18:27-28). Quindi i Daniti la ricostruirono  e ci abitarono. Inoltre, rizzarono l'immagine scolpita e il Levita fu il loro sacerdote. L'immagine rimase e i discendenti del Levita rimasero fino alla deportazione da parte degli Assiri circa 400 anni pi&ugrave; tardi (Giudici 18:29-31). Infatti, nel regno settentrionale di Israele, che si svi&ograve; dalla vera adorazione di Dio abbastanza velocemente, questo idolo fu uno dei due centri di culto del regno (1R 12:25-33), e fu un'insidia per secoli. Non solo la trib&ugrave; fu deportata come punizione, ma la trib&ugrave; di Dan non appare neanche nella descrizione del popolo di Dio in Apoc 7:4-8.
<p>Perch&eacute; i Daniti fecero tutto questo, rubando, minacciando, e stabilendo una falsa religione? Il prossimo versetto ce lo ricorda:
<blockquote>In quel tempo, non vi era re in Israele. Giudici 19:1</blockquote>
<p>Cosa ricevi quando fai quello che ti pare meglio? Mica non ricevette niente, anzi perse poco tempo dopo la sua falsa speranza, i suoi soldi e il suo Levita. I Daniti persero tutto, anche se secoli dopo alla deportazione, e poi anche per eternit&agrave;.
<p>Il Signore dei signori, il Re dei re, si far&agrave; esaltare, annienter&agrave; ogni falso re e signore nella tua vita. Ecco cosa ricevi quando fai quello che ti pare meglio! Se fai quello che ti pare meglio, questo &egrave; il tuo destino. Ma se hai la vera speranza, in Ges&ugrave; il Re che ti salva dalla tua prepotenza di non trattare il Signore come il tuo re, non sarai mai deluso. E cosa puoi fare quando sei impotente davanti alla prepotenza di altri che fanno come gli pare meglio? In realt&agrave;, niente, perch&eacute; sei impotente. Ma Dio pu&ograve; fare tutto! Ges&ugrave;, il Re dei re, il Signore dei signori ritorner&agrave; non solo per salvarti, ma anche per abbattere ognuno che non lo accetta come re. Forse ci vorr&agrave; poco tempo, forse ci vorr&agrave; tanto tempo, ma Ges&ugrave; non delude e distrugger&agrave; ogni ingiustizia e ogni prepotenza.

<?
$n=15;
require("indice.php");
require("../../piede.php");
?>

