<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Giudici: Situazione storica e teologica";
$key = "giudici,situazione,storica,teologica";
$titolo = "Situazione storica e teologica (Giudici 1:1-2:9)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>La prova (Giudici 3:1-6)</h1>
<p>In questa sezione del libro c'&egrave; un approfondimento del fatto che Dio mise alla prova Israele, che &egrave; gi&agrave; stato menzionato in Giudici 2:1-5 e Giudici 2:20-23. Vengono descritti le caratteristiche della prova, lo scopo della prova, e i risultati della prova. Poi ci sono delle riflessioni per noi sul significato della prova da parte di Dio.</p<<>
<h2>1. Le caratteristiche della prova (3:1-3)</h2>
<p>Le persone che furono messe alla prova erano gli Israeliti della generazione successiva a quella che aveva conquistato il paese promesso. Senz'altro, sapevano di Dio e di quello che aveva fatto per Israele, i genitori avevano raccontato loro delle battaglie vinte in Canaan, ma non avevano sperimentato personalmente queste grandi opere di Dio e soprattutto non avevano avuto l'opportunit&agrave; di esercitare la fede in un Dio santo che punisce l'empiet&agrave;, n&eacute; di un Dio potente che pu&ograve; distruggere qualsiasi ostacolo all'adempimento della sua promessa. Avevano bisogno di una prova per capire quanto grande era la loro fede e quanto grande era il loro Signore. Inoltre, la nuova generazione avrebbe potuto pensare, "Io sono nato in questa terra, io sono cresciuto qui, &egrave; la mia, ho lavorato sodo per ottenere quello che possiedo, per cui posso fare quello che mi pare meglio".</p>
<p>Dall'altra parte della prova c'erano diversi popoli intorno e in mezzo agli Israeliti. I Filistei erano emigrati attraverso il mar Mediterraneo per prendere possesso del territorio vicino alla costa al sud-ovest del Canaan, soprattutto in cinque citt&agrave; di quel territorio. Sarebbero stati i principali nemici di Israele dal tempo di Sansone, l'ultimo dei giudici, fino ai primi re Saul e Davide. Poi i Cananei erano vari popoli (per esempio gli Ittiti, gli Amorei, i Ferezei, e i Gebusei) che rimasero nel paese di Canaan dopo la conquista (parziale) da parte di Israele. I popoli di Moab e Ammon, all'est del Canaan oltre il fiume Giordano, sono spesso inclusi nei Cananei. I Sidoni erano della citt&agrave; di Sidone, sulla costa del Mediterraneo a nord-ovest di Canaan, e poi gli Ivvei erano al nord del paese, nel territorio che sarebbe diventato la Siria. In altre parole, gli Israeliti erano circondati da possibili nemici militari, oltre a quelli che abitavano in mezzo a Israele che erano un problema diverso, come vedremo.</p>
<h2>2. Lo scopo della prova (3:4)</h2>
<p>Lo scopo della prova era per vedere se Israele avrebbe ubbidito ai comandamenti di Dio. Naturalmente, Dio lo sapeva gi&agrave;; la prova era per far vedere agli Israeliti stessi ed anche agli altri, inclusi noi. Quindi il senso &egrave; per rivelare o manifestare l'ubbidienza o la disubbidienza, che fino a quel punto era rimasta nascosta.</p>
<p>La prova degli Israeliti era come una prova o esame a scuola. Esiste per rivelare la nostra conoscenza, per far vedere se abbiamo studiato o no. &Egrave; vero che ci siano dei professori cattivi che fanno gli esami o interrogazioni difficili per far bocciare gli alunni, oppure fanno domande facili al cocco dell'insegnante e domande impossibili agli studenti che gli stanno antipatici. Ma Dio non &egrave; cos&igrave;. Semplicemente rivela quanto abbiamo studiato, e ci sprona a studiare di pi&ugrave; dal desiderio di superare l'esame. Cos&igrave; l'esame aiuta anche a migliorare la nostra conoscenza. Nello stesso modo, il fatto che Dio ci mette alla prova serve anche a migliorare la nostra fede, oltre a rivelarla.</p>
<h2>3. I risultati della prova (3:5-6)</h2>
<p>Continuando l'analogia scolastica, nella pagella degli Israeliti c'era la bocciatura. Nello specifico, erano mancanti in tre modi. Prima di tutto, abitarono in mezzo ai Cananei. In realt&agrave;, questo non &egrave; necessariamente un male (anche se nel loro caso tutto il paese era promesso agli Israeliti). Poteva essere un'opportunit&agrave; per far conoscere il vero Dio agli altri popoli. Ma gli altri popoli erano anche un'insidia (Giudici 2:3), un'opportunit&agrave; per conoscere gli idoli degli altri popoli. Il prossimo passo era sposare quelli del posto, che era un mescolamento culturale, oltre a quello geografico. Anche se Dio mise Israele alla prova lasciando gli altri popoli nel paese, gli Israeliti misero s&eacute; stessi alla prova sposandosi con loro. Questi due passi portarono al terzo e pi&ugrave; grave, l'idolatria di servire gli d&egrave;i degli altri popoli, un abbandono del Dio vero che li aveva salvati per essere testimoni del suo carattere a tutti gli altri.</p>
<p>I Cristiani adesso si trovano in una situazione diversa dagli Israeliti; non hanno un paese particolare e per forza vivono in mezzo ai non credenti. Anzi, devono essere la luce e sale del mondo (Matteo 5:13-16; vedi anche Giovanni 17:11-23) piuttosto che ritirarsi dagli altri. Per&ograve; la realt&agrave; &egrave; che vivere in mezzo ai non credenti a volte non porta la luce a loro, ma porta i Cristiani ad adorare i loro d&egrave;i, che non &egrave; giusto. Sposare i non credenti rende questo errore ancora pi&ugrave; facile.</p>
<h2>4. Riflessioni sulla prova</h2>
<p>Di solito consideriamo le prove come cose brutte che ci capitano, le difficolt&agrave; in cui ci troviamo. E spesso lo sono. Per&ograve; parliamo qui di prove nel senso di un test o di un esame, per rivelare e migliorare la nostra fede, che possono anche essere delle cose belle.</p>
<p>La prima prova nella storia era nel giardino di Eden, dove Dio mise l'albero della conoscenza del bene e del male. Poteva collocare quell'albero in qualsiasi luogo, ma era nel giardino per dare l'unica proibizione ad Adamo e Eva. Potevano fare tutto, tranne mangiare di quell'albero. Senza l'albero, non avrebbero potuto mostrare l'ubbidienza ad un divieto, era un'opportunit&agrave; per Adamo e Eva di rivelare e imparare l'ubbidienza e cos&igrave; crescere nel loro cammino con Dio. Ma fallirono.</p>
<p>Dio mise alla prova Abraamo quando gli chiese di uccidere suo unico figlio, Isacco. Poi lo blocc&ograve; prima che potesse compiere l'atto che stava per fare. Lo scopo della prova non era per far soffrire Abraamo n&eacute; Isacco, ma per fare del bene ad Abraamo, facendo vedere a lui ed anche agli altri la profondit&agrave; della vera fede. Fa vedere anche a noi, perch&eacute; la fede di Abraamo &egrave; spesso presentata nel Nuovo Testamento come modello per noi.</p>
<p>Satana derise Giobbe (e cos&igrave; anche la fede che aveva in Dio), affermando che temeva Dio solo per quello che riceveva come conseguenza. Quindi Dio permise tanta sofferenza a Giobbe, per rivelare l'integrit&agrave; della sua fede, e che non credeva solo per il tornaconto.</p>
<p>Ges&ugrave; fu tentato, per rivelare a tutti, incluso Satana, la sua perfezione.</p>
<p>Anche le cose buone, le benedizioni che riceviamo da Dio, possono essere una prova per noi. Nella chiesa primitiva a Gerusalemme, tanti possedevano una propriet&agrave;. Barnaba vendette il suo campo per aiutare gli altri (Atti 4:26-27). Maria la madre di Marco tenne la sua casa per aiutare gli altri (Atti 12:12). Anania e Saffira vendettero la loro propriet&agrave; per fare bella figura davanti alla chiesa, e cos&igrave; fallirono la prova di possedere qualcosa (Atti 5:1-11).</p>
<p>Anche Simone Mago fu messo alla prova dei doni spirituali, che voleva usare per il proprio tornaconto (Atti 8:14-24). In questa maniera, non solo le benedizioni materiali ma anche le benedizioni spirituali possono essere una prova per noi, quando le usiamo per il nostro vantaggio e non per fare bene agli altri e per glorificare Dio.</p>
<p>Quindi, noi siamo e saremo messi alla prova, sia dalle difficolt&agrave; sia dalle belle cose che possono diventare insidie e idoli per noi. Senza le prove, non apprezzeremmo la sovranit&agrave;, la cura, e i doni di Dio. Non impareremmo mai a fidarsi di Dio perch&eacute; potremmo cavarsela da soli senza la grazia di Dio, senza capire quanto forte &egrave; Satana a cui dobbiamo resistere, senza capire quando forti sono i nostri desideri naturali contro cui dobbiamo combattere.</p>
<p>In Giudici 3:2, leggiamo che Dio mise alla prova Israele perch&eacute; voleva soltanto che le nuove generazioni dei figli d'Israele conoscessero e imparassero la guerra. Naturalmente, non era per sapere come utilizzare le armi n&eacute; come uccidere le persone, ma come Dio vince la battaglia e noi partecipiamo, come Giosu&egrave; e la generazione precedente avevano sperimentato e imparato durante la conquista del paese. Similmente, quando Efesini 6 parla del combattimento spirituale del Cristiano, l'unica arma offensiva &egrave; la spada - &egrave; anche quella non &egrave; la nostra capacit&agrave; ma la Parola di Dio. Dio mette noi alla prova affinch&eacute; conosciamo e impariamo la guerra spirituale, cio&egrave; che impariamo a fidarci del Dio che vince per noi come la vinse per gli Israeliti.</p>
<p>Per concludere questa sezione, alcuni brani su cui riflettere, che possiamo riassumere con le frasi che Dio ci prova per migliorarci; Satana ci tenta per farci cadere; e noi ci tentiamo per avere piaceri effimeri.</p>
<blockquote>Fratelli miei, considerate una grande gioia quando venite a trovarvi in prove svariate, sapendo che la prova della vostra fede produce costanza. E la costanza compia pienamente l'opera sua in voi, perch&eacute; siate perfetti e completi, di nulla mancanti. (Giacomo 1:2-4)</blockquote>
<blockquote>Beato l'uomo che sopporta la prova; perch&eacute;, dopo averla superata, ricever&agrave; la corona della vita, che il Signore ha promessa a quelli che lo amano. Nessuno, quando &egrave; tentato, dica: &laquo;Sono tentato da Dio&raquo;; perch&eacute; Dio non pu&ograve; essere tentato dal male, ed egli stesso non tenta nessuno; invece ognuno &egrave; tentato dalla propria concupiscenza che lo attrae e lo seduce. (Giacomo 1:12-14)</blockquote>
<blockquote>Nessuna tentazione vi ha c&ograve;lti, che non sia stata umana; per&ograve; Dio &egrave; fedele e non permetter&agrave; che siate tentati oltre le vostre forze; ma con la tentazione vi dar&agrave; anche la via di uscirne, affinch&eacute; la possiate sopportare. (1Corinzi 10:13)</blockquote>

<?
$n=1;
require("indice.php");
require("../../piede.php");
?>

