<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 3]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 3]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Sansone [parte 3] (Giudici 16)</h1>
<p>Sansone era forte fisicamente, ma aveva una debolezza verso le donne. In questo capitolo, vediamo il suo rapporto con due: una prostituta a Gaza e poi Dalila, che port&ograve; alla sua morte. Mentre riflettiamo su Sansone, vedremo alcune caratteristiche del suo peccato, e anche del nostro. Per&ograve;, il messaggio del capitolo in realt&agrave; &egrave; che Dio si ricorda del disperato, di colui che &egrave; caduto nelle profondit&agrave; del peccato. Ci vuole una lunga descrizione della caduta di Sansone per capire quanto profondo era il suo peccato, e cos&igrave; quanto profonda &egrave; la grazia di Dio.<p>
<h2>1. La progressione del peccato (16:1-3)</h2>
<p>Raramente il peccato appare dal nulla. Di solito ci avviciniamo al peccato pian piano, prima con azioni che non sono sbagliate in s&eacute;, ma non con le migliori intenzioni.<p>
<p>Sansone and&ograve; a Gaza. Era una citt&agrave; filistea, ma non c'era niente di sbagliato in questo. Magari solo un comportamento ambiguo. Che cosa doveva fare l&igrave;? Di tutte le citt&agrave; filistee, perch&eacute; scelse proprio quella pi&ugrave; lontana? Forse per non essere visto. Comunque, come dice Paolo, "Ogni cosa &egrave; lecita, ma non ogni cosa &egrave; utile, non ogni cosa edifica" (1Cor 10:23). Non era sbagliato andare a Gaza, ma probabilmente non era utile n&eacute; a Sansone n&eacute; agli Israeliti.<p>
<p>A Gaza vide una prostituta. Non era colpa sua, era l&igrave; a essere vista, forse si faceva vedere anche. Ma poi Sansone entr&ograve; da lei, che non era una visita per prendere il t&egrave;, ma un modo di dire per i rapporti sessuali. Sansone aveva trascorso la spirale, come aveva fatto Israele durante tutto il libro dei Giudici, e si era allontanato da Dio: prima un'ambiguit&agrave;, poi un piccolo sbaglio, fino a arrivare al peccato grosso. Per&ograve;, non arriv&ograve; fino in fondo; questo lo far&agrave; nel prossimo racconto del capitolo.<p>
<p>Questa progressione del peccato &egrave; l'esperienza tipica di come il peccato ci sopraff&agrave;. Sulla televisione, &egrave; difficile trovare dei programmi senza riferimento al sesso immorale: i film ne sono pieni, negli spettacoli serali le donne sono poco vestite per attirare i pensieri. Li guardiamo, che di solito non &egrave; sbagliato in s&eacute;. Ma poi cerchiamo i programmi pi&ugrave; adulti. Dopo un po' non ci danno abbastanza soddisfazione e troviamo i programmi pi&ugrave; spinti. Forse ci scusiamo, "&egrave; solo per conoscere come sono i programmi". E alla fine arriviamo alla pornografia.<p>
<p>Ogni dipendenza, anche di cose buone, inizia con qualche piccolo assaggio innocente. Ci piace qualche piccolo dolce dopo la cena, ma dobbiamo avere sempre di pi&ugrave; per ottenere lo stesso piacere, fino a quando dipendiamo dagli zuccheri. Ci divertiamo un po' sul computer per rilassarci, poi ci rimaniamo per sempre pi&ugrave; tempo trascurando gli altri impegni della vita.<p>
<p>Iniziamo con un gran amore per il coniuge. Poi passano gli anni, ci abituiamo alla sua presenza, non facciamo pi&ugrave; i piccoli atti di apprezzamento, doni, parole, carezze, ci allontaniamo e finiamo come coinquilini invece di sacrificare tutto per il bene dell'altro.<p>
<p>Anche peccati come l'orgoglio o la ricerca dell'approvazione altrui iniziano con i piccoli atteggiamenti ambigui, prima di crescere in peccati in cui il nostro benessere diventa la cosa pi&ugrave; importante della nostra vita.<p>
<h2>2. Prendere alla leggera il peccato (16:4-19)</h2>
<p>Il rapporto tra Sansone e Dalila &egrave; patetico. Tutti e due usano l'altro per i propri fini, piuttosto di cercare il bene dell'altro, che &egrave; il vero amore.<p>
<p>Sansone vuole solo il piacere. Prende alla leggera la sua situazione pericolosa (fisicamente e spiritualmente), gioca con il peccato - e perder&agrave; tutto con questo gioco.<p>
<p>Dalila vuole la ricchezza. A lei sono promessi 1100 sicli d'argento da ognuno dei cinque principi dei Filistei, che sono circa un milione di euro. Lei non &egrave; neanche sottile nascondendo il suo vero desiderio, non inganna Sansone. Tre volte usa subito le informazioni che Sansone le d&agrave; per provare a farlo catturare. Utilizza anche il ricatto emotivo (Giudici 16:15), l'insistenza e il tormento (Giudici 16:16).<p>
<p>Sansone doveva capire quello che succedeva, ma lo prendeva alla leggera. Non importava secondo lui, non succedeva niente siccome riusciva a liberarsi ogni volta, e intanto stava con Dalila. Era tutto un gioco per lui.<p>
<p>Anche dopo che Sansone aveva spiegato che la sua forza veniva da Dio (Giudici 16:17), &egrave; rimasto l&igrave; con Dalila, si &egrave; addormentato con lei (Giudici 16:19), pur sapendo che Dalila avrebbe fatto tagliare i capelli e che i Filistei sarebbero venuti.<p>
<p>Perch&eacute;? Perch&eacute; non credeva che facesse una differenza se rimanesse o andasse. L'immoralit&agrave;? Non importa. Perdere la consacrazione a Dio? Tanto, sono scampato le altre volte, sono pi&ugrave; forte dei Filistei. Ci&ograve; &egrave; la presunzione del peccato che vedremo nella prossima sezione.<p>
<p>Ecco la fine della progressione del peccato, ecco dove arriva la spirale in fondo, considerare che il peccato non importi. Possiamo fare mille scuse, che non &egrave; cos&igrave; grave, che non riusciamo a smettere, che &egrave; cos&igrave; bello, che tutti lo fanno, che siamo fatti cos&igrave;, che &egrave; colpa di qualcun altro, che &egrave; impossibile ubbidire al giorno d'oggi, e cos&igrave; via, ma in ogni caso stiamo prendendo alla leggera il peccato. Piuttosto, se siamo consapevoli del peccato, se siamo all'inizio della spirale rischiando di scendere o se siamo in fondo alla spirale, dobbiamo prestare attenzione agli avvertimenti:<p>
<blockquote>Vegliate e pregate, affinch&eacute; non cadiate in tentazione; lo spirito &egrave; pronto, ma la carne &egrave; debole. Matteo 26:41</blockquote>
<blockquote>Siate sobri, vegliate; il vostro avversario, il diavolo, va attorno come un leone ruggente cercando chi possa divorare. Resistetegli stando fermi nella fede. 1Pietro 5:8-9</blockquote>
<p>Quando Sansone inizi&ograve; a contendere contro i Filistei, fu subito attaccato da un leone. Non poteva vincere, ma lo Spirito Santo lo invest&igrave; e sconfisse il leone (Giudici 14:1-6). Anche noi, quando attaccati dal diavolo, non possiamo vincere. Non dobbiamo arrenderci prendendo alla leggera il peccato, ma dobbiamo resistere al diavolo stando fermi nella fede e, senza la presunzione di pensare di vincere senza Dio, lasciare che il Signore sconfigga il nostro avversario per noi.<p>
<h2>3. La presunzione del peccato (16:20)</h2>
<p>Tre volte Sansone vinse contro il tranello di Dalila e l'agguato dei Filistei. Ruppe le corde fresche, ruppe le funi nuove, strapp&ograve; via il subbio del telaio. Quindi la quarta volta, anche se sapeva di aver rivelato il suo segreto a Dalila, si svegli&ograve; e ragion&ograve;, "Io ne uscir&agrave; come le altre volte, e mi liberer&ograve;".<p>
<p>Si era gi&agrave; liberato ben tre volte. Aveva gi&agrave; ucciso un leone, aveva gi&agrave; ucciso 1000 uomini con la mascella d'asino, aveva gi&agrave; portato sulle spalle in cima al monte la porta della citt&agrave;. Non sarebbe stato difficile, era convinto di essere forte, pi&ugrave; forte di 1000 filistei, poteva sconfiggere quella manciata di uomini come gli altri.<p>
<p>Sansone si ricordava di tutte le grandi vittorie. Ma aveva dimenticato che era forte, ma non cos&igrave; forte per fare tutte queste imprese. Dio era forte, ed era Dio che gli dava la protezione, la potenza, e la provvisione che gli servivano (Giudici 13:25; 14:6,19; 15:14).<p>
<p>Questa volta, comunque, era diversa. Era diversa perch&eacute; lasci&ograve; che tagliassero i suoi capelli. I capelli non erano magici, non gli davano la forza. Invece Sansone era consacrato a Dio prima della sua nascita, e il segno della sua consacrazione era di non tagliare mai i capelli (Giudici 13:5; 16:17). Lasciandosi tagliare i capelli, Sansone abbandon&ograve; Dio, afferm&ograve; che non gli interessava essere consacrato a Dio, poteva farcela da solo. Come conseguenza, come abbiamo visto altre volte in questo libro, Dio gli diede quello che voleva, "il Signore si ritir&ograve; da lui" e quindi "la sua forza lo lasci&ograve;". Cos&igrave; fu facilmente catturato e imprigionato dai Filistei.<p>
<p>Sansone era in uno stato spaventoso. Pensare di restare in un rapporto con Dio, pensare di servire il Signore, senza il suo aiuto. Senza la sua protezione, senza la sua potenza, senza la sua provvisione. Pu&ograve; succedere che presumiamo il favore di Dio piuttosto di umilmente cercare il favore di Dio.<p>
<p>Anche noi possiamo cadere in questo stato spaventoso, anche se di solito &egrave; una progressione graduale piuttosto che un cambiamento da un giorno all'altro. Se serviamo Dio con un ministero pubblico regolare, dopo un po' diventa un'abitudine, diventiamo abbastanza bravi a causa dell'esperienza accumulata. Ma il momento che pensiamo, come Sansone, "L'ho gi&agrave; fatto nel passato, so come fare", e agire senza Dio, lui ci lascia a fare da soli. Le conseguenze non sono cos&igrave; drastiche come lo erano per Sansone, per&ograve; anche se saremo bravi in quello che faremo, non ci sar&agrave; il Signore e vedremo i risultati della nostra bravura e delle nostre mancanze, non vedremo mai i risultati soprannaturali che vengono dall'opera di Dio. Servire il Signore senza la presenza del Signore &egrave; veramente spaventoso.<p>
<p>Lo stesso principio vale in tutta la vita, non solo al ministero pubblico. Se pensiamo di lavorare con le nostre capacit&agrave; acquisite, lo faremo e magari anche bene, ma senza i risultati che solo Dio pu&ograve; dare. Forse pensiamo di poter educare i figli, prenderci cura di altri familiari, aiutare gli amici, e forse riusciamo in qualche modo. Ma se pensiamo di saper fare senza l'aiuto del Signore, lo faremo purtroppo senza l'aiuto del Signore. Come disse Ges&ugrave;, "senza di me non potete fare nulla" (Giovanni 15:5).<p>
<h2>4. Il prezzo del peccato (16:21-25)</h2>
<p>Il peccato &egrave; piacevole. Per&ograve;, il piacere &egrave; temporaneo. Come la Bibbia dice di Mos&egrave;, "Prefer&igrave; essere maltrattato con il popolo di Dio che godere per breve tempo i piaceri del peccato" (Ebrei 11:25). Perch&eacute; Satana ci fa vedere la bella esca, ma non l'amo n&eacute; il pescatore che vuole toglierci dalla vera bellezza di restare nelle benedizioni dell'acqua.<p>
<p>Oltre al piacere temporaneo, c'&egrave; un costo a lungo termine del piacere. Per Sansone, il prezzo da pagare era di essere catturato, accecato, legato, schiavizzato. Sansone che terrorizzava i Filistei &egrave; ora preso in giro dai Filistei come buffone, pagliaccio, e fenomeno da baraccone.<p>
<p>Inoltre, c'&egrave; anche un costo a Dio, che rischia molto associando il suo onore al comportamento dei suoi seguaci e servitori peccaminosi, noi che possiamo screditare il suo nome, la sua grandezza, la sua perfezione. Cos&igrave; tutti i Filistei potevano lodare Dagon, il loro dio, con sacrifici e feste. Secondo loro, Dagon li aveva liberati (mentre altrove nel libro dei Giudici, &egrave; sempre Yahweh, il Dio sovrano degli Israeliti che liberava), per cui Dagon aveva vinto perch&eacute; pi&ugrave; forte di Yahweh. Il costo del peccato di Sansone alla gloria di Dio era altissimo.<p>
<h2>5. La preghiera nel peccato (16:26-31)</h2>
<p>Le conseguenze del peccato sono spesso irreversibili, con danni alla salute, al ministero, alla famiglia che non possono essere cancellati. Cos&igrave; con Sansone, che non aveva pi&ugrave; niente.<p>
<p>Nell'edificio a Gaza, tutti i nobili erano radunati per festeggiare la vittoria del loro dio. Era l'evento dell'anno, tutti volevano partecipare per prendere in giro Sansone, il loro tormentatore. Era simile alle scene che vediamo quando una squadra vince lo scudetto: tutti i tifosi sono nella piazza principale della citt&agrave; per celebrare questo grande evento, questa vittoria, questa realizzazione della loro speranza. E se per caso si trovasse in mezzo a questa folla un tifoso di una squadra rivale, guai a lui! Sarebbe deriso, preso in giro, forse anche maltrattato.<p>
<p>In mezzo a tutta questa gente gioiosa, si trovava un povero relitto di un uomo che aveva fatto naufragio della sua fede, parcheggiato tra le due colonne. Mentre tutti i Filistei gridavano "Dagon, Dagon", lo lodavano e celebravano, &egrave; uscito un piccolo sussurro dalla bocca di Sansone, "Signore, Dio, ti prego, ricordati di me". Sansone aveva perso tutto, anzi aveva buttato via tutto. Non aveva niente da offrire, non trattava con Dio, aveva disonorato Dio con il suo peccato e non aveva pi&ugrave; nessun diritto di chiedergli qualcosa. Era la preghiera del ladrone sulla croce, similmente dopo una vita di furti, quando non poteva offrire niente a Ges&ugrave; perch&eacute; sul punto di morire, che poteva solo dire, "Ges&ugrave;, ricordati di me quando entrerai nel tuo regno" (Luca 23:42).<p>
<p>Finalmente, Sansone aveva capito che non era forte, ma che Dio (tramite il suo Spirito) gli dava la potenza necessaria e che Sansone aveva bisogno di lui. Quindi prosegu&igrave;, "Dammi forza per questa volta soltanto, o Dio". Quando abbiamo fatto un gran casino o quando abbiamo iniziato la spirale con una piccola bugia, preghiamo, chiediamo solo la grazia e il favore di Dio. E Dio sente, Dio ascolta, Dio risponde.<p>
<p>&Egrave; il contrario della presunzione di farcela senza Dio. Quando riconosciamo che solo Dio pu&ograve; e noi non, Dio agisce per portare l'onore a s&eacute; stesso.<p>
<p>Come risposta a Sansone, Dio rivel&ograve; la verit&agrave;. La realt&agrave; non era che Sansone era il buffone per migliaia di Filistei, ma che i Filistei facevano i buffoni festeggiando e celebrando quello che loro pensavano fosse la vittoria di un pezzo di legno o di pietra, un dio immaginario, sul sovrano Creatore dell'universo. E questo grande Dio si glorific&ograve; a scapito di quell'idolo, dimostrando che era il vincitore e che, finalmente, Sansone era il suo servo.<p>
<p>Come la nascita e la vita di Sansone sono modelli della nascita e vita di Ges&ugrave; Cristo, come abbiamo visto nei capitoli precedenti, cos&igrave; anche la morte di Sansone &egrave; un modello della morte di Ges&ugrave; Cristo. Perch&eacute; il Signore Ges&ugrave; fu catturato, reso debole, umiliato, preso in giro e deriso, apparentemente sconfitto. Fu abbandonato dal Padre - grid&ograve; sulla croce "Dio mio, Dio mio, perch&eacute; mi hai abbandonato?" (Marco 15:34). Per&ograve;, non fu abbandonato per il proprio peccato, come era il caso per Sansone, ma per il nostro peccato, che Ges&ugrave; port&ograve; mentre moriva. Poi, quando Ges&ugrave; tocc&ograve; il fondo (il fondo del nostro peccato), alla sua morte, ottenne una vittoria maggiore di tutte quelle ottenute durante la sua vita, liber&ograve; pi&ugrave; persone di quante aveva liberato durante la sua vita.<p>
<h2>Conclusione</h2>
<p>L'ultima parola di questo capitolo o di questo racconto di Sansone non &egrave; il suo fallimento n&eacute; la sua immoralit&agrave;. L'ultima parola non &egrave; che il Signore si era ritirato da lui.<p>
<p>L'ultima parola &egrave; che Dio si ricord&ograve; di Sansone, non disprezz&ograve; quest'uomo che aveva fallito e che l'aveva tradito, abbandonato, e disonorato. Non disprezz&ograve; n&eacute; trascur&ograve; la sua preghiera. Invece sent&igrave;, ascolt&ograve;, e si ricord&ograve;. Che il Dio di Sansone, che &egrave; il Dio di Ges&ugrave; Cristo, che ci sente e si ricorda di noi quando siamo umili invece di presuntuosi, sia sempre con noi.<p>

<?
$n=14;
require("indice.php");
require("../../piede.php");
?>

