<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 3]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 3]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Sansone [parte 1] (Giudici 13)</h1>
<p>A Sansone, l'ultimo giudice del libro dei Giudici, sono dedicati quattro capitoli del libro, pi&ugrave; di tutti i giudici. Consideriamo questi capitoli in tre sezioni. La prima sezione, in Giudici 13, racconta le circostanze della sua nascita, o meglio l'annuncio della sua nascita. Solo negli ultimi due versetti del capitolo appare Sansone: dopo un versetto di introduzione sullo stato d'Israele, il resto del capitolo parla dei genitori di Sansone. Anzi, parla di Dio che si rivela ai genitori, un Dio che prepara in modi apparentemente insignificanti i suoi grandi interventi.</p>
<h2>Israele e Dio (13:1)</h2>
<p>Il capitolo inizia con il solito ciclo che abbiamo gi&agrave; visto diverse volte nel libro, ma &egrave; presto interrotto. Il ciclo &egrave; in realt&agrave; una spirale in discesa in cui la situazione peggiora in ogni giro. Con Iefte, Israele si ribell&ograve; a Dio, Dio li diede nelle mani dei nemici, gli Israeliti gridarono al Signore, ma poi Dio rifiut&ograve; di liberarli (Giudici 10:6-14). Questa volta ci sono il peccato e l'abbandono, ma nessuno grido a Dio (Giudici 13:1). Furono dominati dai Filistei per 40 anni fino al tempo di Sansone, e in realt&agrave; per molto pi&ugrave; tempo, perch&eacute; il dominio prosegu&igrave; durante il tempo di Samuele e di Saul, fino all'inizio del regno di Davide. Israele doveva impadronirsi di questo territorio, ma invece i Filistei erano i padroni degli Israeliti. E agli Israeliti andava bene. Quando Sansone attacca i Filistei, alcuni Israeliti gli dicono, "Non sai che i Filistei sono nostri dominatori? Che &egrave; dunque questo che ci hai fatto?" Cio&egrave;, per loro era meglio essere sotto il giogo dei Filistei che essere liberati.</p>
<p>Similmente per noi, che dobbiamo portare la luce nella citt&agrave; dove viviamo, al nostro posto di lavoro, nella nostra famiglia, ma spesso non riusciamo. Spesso accade invece il contrario: sono le tenebre che invadono la nostra vita, la nostra famiglia, la nostra chiesa. Sembra che il male abbia il sopravvento nel mondo. Peggio ancora, sembra di non importare a nessuno. Ci abituiamo, rinunciamo a poter fare la differenza, a trasformare gli altri, preghiamo e ci impegniamo di meno, e cadiamo lungo la spirale in discesa mentre somigliamo agli altri sempre di pi&ugrave;.</p>
<p>Ma a Dio importa che noi siamo dominati dal male, come pure gli importava che gli Israeliti fossero sotto il dominio dei Filistei. E Dio prepara. Dio prepar&ograve; per la salvezza, ancora quando non era richiesta.</p>
<p>Dobbiamo pregare il nostro Signore in ogni situazione. Ma ringraziamo Dio che la sua opera non &egrave; limitata alle risposte alle nostre preghiere. Lodiamo Dio che interviene e che salva anche quando nessuno lo vuole. Dio opera per aiutarci, Dio prepara per aiutarci, anche decenni prima che il problema si manifesti.</p>
<h2>I genitori di Sansone (13:2-23)</h2>
<p>Israele non chiese n&eacute; un liberatore n&eacute; un giudice, ma Dio lo avrebbe mandato comunque. Ma prima, prepar&ograve; l'arrivo del giudice. Venne ad una donna per annunciare che avrebbe partorito un figlio.</p>
<p>Sembra che Dio abbia sbagliato casa. Di tutte le donne israelite che potevano essere la madre del liberatore, ne scelse una che era "sterile e non aveva figli" (Giudici 13:2). Lei era completamente inadeguata per il compito affidato a lei. Come Sara la madre di Isacco, come Anna la madre di Samuele, e come Maria la madre di Ges&ugrave;. Abbiamo visto spesso nel libro che Dio us&ograve; i deboli e i disprezzati per compiere i suoi propositi di liberare Israele. Questa volta, quando siamo quasi in fondo alla spirale, us&ograve; non il debole ma l'impossibile. Perch&eacute; cos&igrave; piace a Dio operare, affinch&eacute; tutta la gloria sia attribuita solo a lui. Ti senti inadeguato, incapace di fare quello che Dio richiede, quello che Dio ha affidato a te? Bene! Cos&igrave; Dio &egrave; contento di usarti.</p>
<p>Anche se Dio prende l'iniziativa nella sua opera e tutto dipende da lui - senza il suo intervento la donna rimane sterile - il ruolo della moglie &egrave; centrale al piano di Dio. Lei deve rimanere pura e consacrare il figlio (Giudici 13:4-5), lei lo spiega al marito (Giudici 13:7), e quando il marito chiede quello che debba fare l'angelo ribadisce che era come aveva detto alla moglie (Giudici 13:13-14). Non &egrave; "Dio mi user&agrave; nonostante la mia inadeguatezza, quindi mi posso rilassare e non fare niente", ma "Dio mi user&agrave; nonostante la mia inadeguatezza, quindi devo fare tutto quello che Dio mi dice con tutta la mia forza, sapendo che Dio user&agrave; la mia debolezza per fare grandi cose".</p>
<p>Impariamo anche da questo brano l'importanza di quelli che educano i figli, che possono fare la differenza per tutta la vita dei bambini e di tutti quelli che i bambini conosceranno. Onoriamo chi sta a casa con i bambini e chi li insegna, anche se &egrave; un ministero poco visibile, e preghiamo per loro che possano educare delle donne e degli uomini maturi in Cristo.</p>
<p>Il marito, Mano&agrave;, &egrave; presentato in modo positivo. Quando sente la notizia da sua moglie, crede e prega per sapere come educare il bambino (Giudici 13:8), e quando l'angelo gli parla, &egrave; sempre convinto (dice "quando", non "se", si saranno adempiute le sue parole in Giudici 13:17) e vuole adorare. Questa fede semplice nella parola &egrave; diversa da, per esempio, quella dei giudici Barac e Gedeone, o di Sara che rise o di Zaccaria il padre di Giovanni il battista.</p>
<p>Anche se l'adorazione di Mano&agrave; non era propria corretta, perch&eacute; non doveva chiedere il nome dell'angelo n&eacute; offrirgli del cibo (Giudici 13:15-18), Dio onor&ograve; l'offerta di Mano&agrave; e si rivel&ograve; in una cosa prodigiosa, da cui Mano&agrave; e sua moglie avevano capito che era l'angelo del Signore (Giudici 13:19-21). Cos&igrave; anche nonostante le nostre limitazioni della fede e adorazione imperfetta, Dio accetta la nostra lode sincera.</p>
<p>Mano&agrave; e sua moglie erano dunque centrali per i propositi di Dio. Ma loro non fecero niente contro i Filistei. Dovevano "solo" educare un figlio nelle vie del Signore, un ministero che doveva essere praticamente invisibile e poco evidente agli altri. Similmente, probabilmente nessuno di chi legge questo testo sar&agrave; uno dei "grandi" del Cristianesimo, che cambier&agrave; la storia e porter&agrave; molti a Dio. Probabilmente molti hanno un ministero poco evidente agli altri - magari visibile nella propria chiesa, ma sconosciuto alla stramaggioranza del popolo di Dio. Chi sapr&agrave; quello che facciamo nel nostro piccolo angolo del mondo? Dio lo sa! Chi sa se da uno di noi nascer&agrave; un gran servitore di Dio? Dio lo sa! Siamo fedeli nel nostro rapporto con i bambini, colleghi, famigliari, contatti, ed altri. Li prepariamo non sapendo il loro futuro; intanto Dio sta gi&agrave; preparando sapendo cosa servir&agrave; nel futuro.</p>
<h2>Sansone (13:24-25)</h2>
<p>Dopo la gravidanza, la moglie di Mano&agrave; partor&igrave; un figlio, Sansone. Dio continu&ograve; a preparare per la sua opera tramite Sansone, benedicendolo e sospingendolo con il suo Spirito.</p>
<p>Dio prepara la sua opera anche prima che sia richiesta. Dio prepara sia noi sia per noi per il futuro che desidera. Per&ograve;, non con i nostri tempi n&eacute; con i nostri mezzi.</p>
<p>Da quando l'angelo apparve a Mano&agrave; e a sua moglie, passarono almeno vent'anni prima che Sansone fosse preparato e pronto per il compito a cui Dio lo aveva chiamato. Durante quel tempo, i Filistei continuarono a dominare gli Israeliti.</p>
<p>Giuseppe fu gettato in una cisterna dai suoi fratelli, che lo vendettero come schiavo. Fu messo in prigione a causa della falsa testimonianza della moglie di Potifar. Fu dimenticato in prigione dal capo dei coppieri per due anni. Poi venne una carestia, e pot&eacute; salvare la sua famiglia dalla fame perch&eacute; distribuiva il cibo di Egitto. Tante disavventure e tanti anni della sua vita, perch&eacute; Dio sapeva molto tempo fa che ci sarebbe voluto qualcuno nella corte del faraone per sfamare il suo popolo. Dio impieg&ograve; tanto tempo e us&ograve; la malvagit&agrave; umana per compiere i suoi propositi! Come Giuseppe disse ai suoi fratelli,</p>
<blockquote>Voi avete pensato del male contro di me, ma Dio ha pensato di convertirlo in bene per compiere quello che oggi avviene: per conservare in vita un popolo numeroso. Genesi 50:20</blockquote>
<p>Ester divent&ograve; la regina della Persia in circostanze particolari. Quando fu deciso il genocidio dei Giudei, lei esit&ograve; di usare la sua posizione per salvarli. Ma suo cugino Mardocheo la ricord&ograve;</p>
<blockquote>Se oggi tu taci, soccorso e liberazione sorgeranno per i Giudei da qualche altra parte; ma tu e la casa di tuo padre perirete; e chi sa se non sei diventata regina appunto per un tempo come questo? Ester 4:14</blockquote>
<p>Chi sapeva perch&eacute; Ester era regina? Dio lo sapeva! Era per salvare il suo popolo, e Dio aveva preparato Ester per quel momento. Per&ograve;, i propositi di Dio non dipendono dalla nostra ubbidienza. Dio avrebbe potuto salvare il suo popolo in un altro modo se Ester avesse rifiutato, come Dio avrebbe potuto suscitare un altro giudice se la madre di Sansone avesse disubbidito alle istruzioni che le erano date.</p>
<p>Nello stesso modo, Dio sta preparando noi e sta preparando delle opere buone che noi potremo fare, e di cui siamo ignari.</p>
<blockquote>Siamo opera sua [di Dio], essendo stati creati in Cristo Ges&ugrave; per fare le opere buone, che Dio ha precedentemente preparate affinch&eacute; le pratichiamo. Efesini 2:10 </blockquote>
<p>Non saranno grandi opere come salvare tutto il suo popolo, ma anche un'opera apparentemente insignificante come educare un figlio o testimoniare a un collega. Chi sa quali conseguenze nella storia, e nell'eternit&agrave;, una tale piccola opera potr&agrave; avere? Dio lo sa!</p>
<p>Dio non usa neanche i nostri mezzi, preferendo i deboli, i disprezzati, e gli impossibili. Anche quando noi avevamo bisogno della salvezza, il messaggio che abbiamo ricevuto era: "Un bambino ci &egrave; nato, un figlio ci &egrave; stato dato, e il dominio riposer&agrave; sulle sue spalle" (Isaia 9:5). La speranza e l'attesa di migliaia di anni furono compiute nella nascita di Ges&ugrave; Cristo, un bambino indifeso. Un esercito di angeli era accampato fuori di Betlemme lodando e glorificando Dio per un piccolo bambino, un bambino benedetto dal Signore e che era sospinto dallo Spirito Santo per compiere la volont&agrave; del Padre. Nei momenti pi&ugrave; oscuri, come gli Israeliti che erano dominati dai Filistei oppure noi che giacevamo nelle tenebre spirituali, Dio &egrave; all'opera per preparare la nostra salvezza.</p>

<?
$n=12;
require("indice.php");
require("../../piede.php");
?>

