<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Gedeone [parte 3]";
$key = "giudici,situazione,storica,teologica,gedeone";
$titolo = "Gedeone [parte 3]";
$sezione = "Gedeone";
require("../../capo.php");
?>
<h1>Sansone [parte 2] (Giudici 14-15)</h1>
<p>Quando leggiamo questi capitoli, possiamo rimanere delusi, se non perplessi, scioccati, o in disaccordo. Dopo il grande annuncio in Giudici 13 e l'opera dello Spirito Santo in Giudici 13:25, sembra che Sansone sia un disastro. Vuole spostare una donna filistea, tocca un cadavere (che contamina) sebbene sia nazireo (consacrato al Signore), propone un enigma impossibile, si lascia manipolare dalla donna, uccide 30 uomini di Ascalon che non c'entrano niente, &egrave; crudele verso gli sciacalli, manca di rispetto verso la propriet&agrave; altrui, si scatena e uccide 1000 uomini con una mascella d'asino. Sembra una violenza incontrollabile. Eppure tre volte lo Spirito Santo investe Sansone per fare tutto questo (Giudici 14:6,19; 15:14); cio&egrave;, non solo Dio era con lui ma Dio lo faceva attraverso Sansone. Inoltre, questo veniva dal Signore (Giudici 14:4), Dio rispose in modo miracoloso alla preghiera di Sansone (Giudici 15:18-19), e Sansone fu giudice d'Israele per 20 anni (Giudici 15:20).</p>
<p>Dobbiamo leggere questi brani non come il racconto di Sansone il delinquente, ma come il racconto di Dio il liberatore. Dio, in un modo caotico, con tanta malvagit&agrave;, in mezzo ad una vita difficile e ambigua, non sta da parte al bordo campo, ma entra nella mischia per salvare in e mediante il caos, il male, e le difficolt&agrave;. In modo particolare, dopo aver visto nel capitolo precedente la preparazione di Dio per la liberazione, in questi capitoli vediamo il proposito sovrano di Dio, la protezione di Dio, la potenza di Dio, e la provvisione di Dio per liberare.</p>
<h2>1. Proposito sovrano</h2>
<p>Il programma di Dio, che esegue con il suo proposito sovrano, &egrave; chiaro da Giudici 13:5: Sansone comincer&agrave; a liberare Israele dalle mani dei Filistei. Perch&eacute; i Filistei dominavano Israele (Giudici 14:4; 15:11,20), come avrebbero fatto fino al tempo del re Davide. I Filistei si erano infiltrati nel paese promesso, la terra promessa da Dio agli Israeliti affinch&eacute; ci abitassero in pace, ma a nessuno interessava, tutti vivevano tranquilli nel regno dei Filistei piuttosto che nel regno di Dio. A nessuno interessava, tranne a Dio. Dio ha una grande passione per il suo popolo, pi&ugrave; che la sua passione per gli sciacalli o addirittura per i Filistei. Forse saremmo meno scandalizzati da questo brano se avessimo la stessa passione per il popolo di Dio di quanto abbiamo per la moda, il calcio, la televisione, il gioco, una vita migliore, e tutto il resto.</p>
<p>Il desiderio di Sansone di avere una certa donna filistea come moglie era ambiguo, se non proprio sbagliato. Nessuno che vuole seguire e servire il Signore pu&ograve; avere una visione comune della vita con qualcuno che non lo vuole. Per&ograve;, leggiamo in Giudici 14:4 che fu fatto per provocare, per cercare un'occasione di contesa da parte dei Filistei, per togliere il senso di benessere di essere dominati dai Filistei. Giusto o sbagliato che sia, fece scatenare una catena di avvenimenti, come una cascata di domino messi in piedi, ogni domino facendo cadere il prossimo. Vuole sposare la donna quindi va a Timna. Quindi un leone attacca e viene ucciso. Quindi Sansone lo usa per un enigma. Quindi la donna insiste per saperne la risposta e tradire Sansone. Quindi Sansone la abbandona (una cosa buona!). Quindi 30 uomini sono uccisi e la donna &egrave; data ad un altro. Quindi i covoni di grano sono distrutti. Quindi la donna e suo padre sono uccisi dai Filistei. Quindi Sansone fa una grande strage di chi li ha uccisi. Quindi &egrave; preso dai Giudei e consegnato ai Filistei. Quindi uccide 1000 uomini con una mascella d'asino. Quindi diventa giudice d'Israele per 20 anni.</p>
<p>Se guardiamo un evento da vicino, non ha molto senso, possiamo anche essere offesi dalla violenza e dalla crudelt&agrave;. Guardato nell'insieme, &egrave; il processo in cui un giovane sconosciuto diventa il giudice. In cui la sottomissione al dominio straniero diventa una sfida e una ribellione al dominio. S&igrave;, sembra un disastro, un caos, un casino. Ma il Dio sovrano era l&igrave; per eseguire il suo proposito sovrano attraverso il disastro, il caos, il casino, il male del mondo e della vita. E se Dio sa e pu&ograve; eseguire il suo proposito sovrano partendo dal desiderio sbagliato di sposare una donna filistea; se Dio pu&ograve; eseguire il suo proposito sovrano della salvezza attraverso il caos del tradimento di Giuda, il rinnegamento di Pietro, la codardia dei discepoli, la gelosia dei capi dei Giudei, e la crudelt&agrave; dei Romani; quando noi guardiamo la nostra vita, la nostra chiesa, forse sembra un disastro, un caos, un casino, ma solo perch&eacute; noi vediamo solo un domino alla volta del proposito sovrano di Dio. Noi dobbiamo essere convinti che Dio sta attuando il suo proposito sovrano prima e dopo quel domino, e lodare lui.</p>
<h2>2. Protezione</h2>
<p>Sansone inizi&ograve; a contestare i Filistei all'inizio del capitolo 14. Per&ograve;, non aveva ancora neanche toccato un Filisteo, quando venne attaccato da un leone. Anche in questo c'&egrave; un parallelo con la vita di Ges&ugrave;. Subito dopo la sua nascita, Erode fece una strage di tutti i bambini di Betlemme. Subito dopo il suo battesimo, quando Ges&ugrave; inizi&ograve; a contestare il diavolo, Satana lo attacc&ograve; con le tre tentazioni.</p>
<p>Il leone, per&ograve;, fece una grave errore di valutazione. Sansone era forte, ma probabilmente comunque non abbastanza forte per battere un leone. Il leone non aveva calcolato che Dio protegge colui che esegue il suo proposito sovrano. Per questo leggiamo in Giudici 14:6, "Lo Spirito del Signore invest&igrave; Sansone, che, senza aver niente in mano, squart&ograve; la belva come uno squarta un capretto". Non era la grande forza umana di Sansone che vinse, ma la sovrumana forza che Dio gli diede. Cos&igrave;, Sansone impar&ograve; la protezione divina, che Dio d&agrave;, attraverso lo Spirito Santo, una capacit&agrave; soprannaturale per eseguire il proposito sovrano di Dio.</p>
<p>Molti, subito dopo aver deciso di seguire il Signore o di impegnarsi completamente per lui, hanno subito degli attacchi di vari tipi - attacchi fisici in alcuni casi, ma anche verbali, oppure una malattia seria o altre difficolt&agrave;. Questo &egrave; normale! Ma Dio ci protegge in tutto questo, anche pi&ugrave; di quanto ci rendiamo conto. Possiamo vedere la protezione di Dio quando c'&egrave; un incidente vicino a noi o quando ci aiuta a superare una tentazione, ma tantissime volte Dio impedisce che un incidente succeda o che subiamo una tentazione perch&eacute; troppo forte per noi, senza che ce ne rendiamo conto.</p>
<h2>3. Potenza</h2>
<p>Questi sono dei capitoli molto violenti. Un leone &egrave; squartato, 30 uomini a Ascalon uccisi per prendere le loro vesti, una strage per vendicare chi aveva ucciso la moglie e il suocero, le funi rotte, 1000 filistei uccisi con una mascella d'asino. Sansone sembra un delinquente, un violento, un mostro che non sa controllare la propria rabbia. Ma in tutto questo, dobbiamo ricordarci di Giudici 14:6,19; 15:14:</p>
<blockquote>Lo spirito del SIGNORE invest&igrave; Sansone, che, senza aver niente in mano, squart&ograve; la belva, come uno squarta un capretto; ma non disse nulla a suo padre n&eacute; a sua madre di ci&ograve; che aveva fatto. Giudici 14:6</blockquote>
<blockquote>Lo Spirito del SIGNORE invest&igrave; Sansone ed egli scese ad Ascalon, vi uccise trenta uomini, prese le loro spoglie e diede le vesti a quelli che avevano spiegato l'enigma. Poi, acceso d'ira, risal&igrave; a casa di suo padre. Giudici 14:19</blockquote>
<blockquote>Quando giunse a Lechi, i Filistei gli si fecero incontro con grida di gioia, ma lo Spirito del SIGNORE invest&igrave; Sansone, e le funi che aveva alle braccia divennero come fili di lino a cui si appicchi il fuoco; e i legami gli caddero dalle mani. Giudici 15:14</blockquote>
<p>Era lo Spirito del Signore che rendeva possibili questi grandi atti. Perch&eacute; per liberarci dalla malvagit&agrave;, per sconfiggere il male, ogni nemico di Dio dovr&agrave; essere distrutto. La domanda non &egrave; se Dio abbia sbagliato o no; la domanda &egrave; da quale parte stiamo: i ribelli a Dio, quelli non del suo popolo, i malvagi, oppure fra quelli che vengono liberati da Dio dal male e dalla punizione della ribellione.</p>
<p>In ogni caso, questa grande violenza non &egrave; la norma, per due motivi. Prima di tutto, fra l'Antico Testamento e il Nuovo Testamento &egrave; apparso il Signore Ges&ugrave; Cristo. Ges&ugrave; ha sconfitto il male alla croce e alla risurrezione; Ges&ugrave; distrugger&agrave; il male al suo ritorno. Quindi noi non dobbiamo mostrare questa violenza ma piuttosto l'amore, e Dio sta aspettando di eseguire la sua punizione affinch&eacute; tutti abbiano la possibilit&agrave; di ravvedersi (2Pietro 3:9).</p>
<p>Il secondo motivo &egrave; che un uomo cos&igrave; forte (e violento) &egrave; unico anche nell'Antico Testamento. Se consideriamo solo i giudici, Eud, Barac, Gedeone, e Iefte, tutti loro radunarono un esercito tramite cui Dio liber&ograve; Israele. Sansone non aveva un esercito, non aveva neanche uno soldato con lui. Nessun altro voleva combattere contro i Filistei. Quando un "esercito" di Giudei venne da lui, non era per combattere con lui ma per tradirlo (Giudici 15:11). Siccome non c'era nessun altro, Dio aveva preparato uno forte che poteva cominciare a liberare da solo.</p>
<p>Anche quando Ges&ugrave; &egrave; venuto sulla terra, ha trovato che non c'era nessuno giusto, neppure uno (Rom 3:10-18). Per questo motivo, Ges&ugrave; ci ha liberati da solo, senza il nostro aiuto. Anzi, fu tradito da Giuda Iscariota e consegnato dai capi dei Giudei ai Romani. Inoltre, come i legami delle funi furono sciolti dallo Spirito Santo, cos&igrave; anche Dio risuscit&ograve; Ges&ugrave;, avendolo sciolto dagli angosciosi legami della morte (Atti 2:24). Ges&ugrave; ha fatto tutto per noi, perch&eacute; non volevamo la salvezza.</p>
<p>Quando leggiamo gli elenchi dei doni dello Spirito Santo nel Nuovo Testamento, non troviamo la forza sovrumana. Ma era esattamente il dono di cui Sansone aveva bisogno per liberare Israele da solo in quel momento, e lo Spirito del Signore gli diede la potenza necessaria. Servire Dio e annunciare Ges&ugrave; nella nostra citt&agrave; e nella nostra famiglia sembra un compito impossibile? Forse lo dobbiamo anche fare da soli. Ricordiamoci che lo Spirito Santo pu&ograve; darci esattamente il dono necessario per farlo, la potenza divina per trasformare gli altri nella nostra citt&agrave; e nella nostra famiglia.</p>
<h2>4. Provvisione</h2>
<p>Nella sezione precedente abbiamo visto la provvisione spirituale, dei doni necessari per compiere i propositi sovrani di Dio, in questo caso per cominciare a liberare Israele. In questi capitoli, c'&egrave; anche la provvisione materiale. Dopo la grande impresa con la mascella, Sansone &egrave; in crisi fisicamente, &egrave; stanco e disperato. Cos&igrave; leggiamo</p>
<blockquote>Poi Sansone ebbe molta sete, invoc&ograve; il SIGNORE, e disse: &laquo;Tu hai concesso questa grande liberazione per mano del tuo servo; ora, dovr&ograve; forse morire di sete e cadere nelle mani degli incirconcisi?&raquo; Giudici 15:18</blockquote>
<p>Notiamo la teologia: Dio aveva provveduto spiritualmente, per cui era in grado di provvedere materialmente. E Dio rispose che era vero:</p>
<blockquote>Allora Dio fend&egrave; la roccia concava che &egrave; a Lechi e ne usc&igrave; dell'acqua. Sansone bevve, il suo spirito si rianim&ograve; ed egli riprese vita. Perci&ograve; quella fonte fu chiamata En-Accore; essa esiste anche al giorno d'oggi a Lechi. Giudici 15:19</blockquote>
<p>Vediamo la stessa provvisione materiale da parte di Dio in brani come Matteo 6:31-32; 2Cor 9:8; Luca 12:24.</p>
<p>Hudson Taylor, un famoso missionario in Cina alla fine del 19o secolo, che non chiese mai un sostengo per la sua opera, scrisse, "L'opera di Dio fatta nel modo di Dio non mancher&agrave; mai della provvisione di Dio". E ricevette sempre quello di cui aveva bisogno. Perch&eacute; Dio esegue sempre il suo proposito sovrano nella nostra vita complicata e nel nostro mondo caotico. Chi segue il suo proposito avr&agrave; sempre la sua provvisione, non solo dei bisogni materiali ma anche della potenza e della protezione per compiere quello che Dio vuole.</p>

<?
$n=13;
require("indice.php");
require("../../piede.php");
?>

