<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Il frutto dell'amore (Rut 2:13-23)";
$key = "amore,frutto,produrre,Rut 2:13-23";
$titolo = "Il frutto dell'amore (Rut 2:13-23)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Il frutto dell'amore (Rut 2:13-23)</h1>
<p>Finora in queste riflessioni abbiamo visto alcune caratteristiche dell'amore sacrificale, l'amore <i>hesed</i> o <i>agape</i>. Questa volta, consideriamo il frutto dell'amore, quello che produce. Cio&egrave;, non quello che produce in chi ama, ma in chi &egrave; amato. Anche se ci sar&agrave; qualche accenno a quello che il tuo amore pu&ograve; produrre in altri e a quello che l'amore di altri pu&ograve; produrre in te, l'enfasi sar&agrave; il frutto prodotto in te dall'amore di Dio verso di te.</p>
<h2>Il frutto dell'amore &egrave; l'umilt&agrave; (Rut 2:13-14)</h2>
<p>Rut sopraffatta e travolta dall'amore che riceve da Boaz. Anche se &egrave; possibile sentirsi cos&igrave; per un amore romantico, non &egrave; il caso qui. Rut &egrave; travolta dalla speranza, dalla protezione, e dalla benedizione che riceve, dall'interessamento per il suo bene.</p>
<p>&egrave; vero che Boaz sapeva che Rut ha aiutato Naomi. Per&ograve;, anche gli altri lo sapevano, ma non la trattavano cos&igrave; bene. Per loro, Rut era una vedova, senza protettore, e in pi&ugrave; una straniera, e peggio ancora di un popolo nemico. Per loro, Rut non era nessuna, non era da considerare. Anche Boaz avrebbe potuto trattarla cos&igrave;, ma non la fece.</p>
<p>Rut afferma di aver trovato grazia da Boaz, cio&egrave; un dono immeritato. ("Possa io trovare grazia" nel testo italiano pu&ograve; sembrare un desiderio o un augurio, ma il senso &egrave; invece un riconoscimento di aver trovato grazia.) Si considera pi&ugrave; bassa della pi&ugrave; bassa delle serve di Boaz. Inoltre, quando si siede per pranzo, si mette "accanto" ai mietitori, non nel senso di essere con o in mezzo a loro, ma di essere separata, in un altro posto (accanto) da loro. Infatti, Boaz deve porre del grano a lei, perch&eacute; Rut non &egrave; con gli altri con il pranzo servito in mezzo, ma da parte dove qualcuno deve portarle del cibo.</p>
<p>Questa umilt&agrave; &egrave; un bello stato in cui ricevere l'amore, e Rut afferma di essere consolata e che Boaz (cio&egrave;, il suo amore) ha parlato al suo cuore.</p>
<p>L'orgoglio, invece, non pu&ograve; portare il peso dell'amore sacrificale e non meritato. Se Rut avesse l'atteggiamento da vittima, sarebbe amareggiata per essere trascurata nonostante l'aiuto che aveva dato a Naomi. Sarebbe irritata con Dio, un po' come lo era Naomi. Non avrebbe risposto bene a Boaz, che non poteva capire la sua vita difficile. Certo, Boaz aveva la vita facile e gioiosa. E niente che Boaz fa avrebbe potuto ripagare Rut abbastanza per tutte le sue sofferenze. Avrebbe meritato molto di pi&ugrave;! Cos&igrave; risponde l'orgoglio all'amore sacrificale e immeritato.</p>
<p>L'amore di Dio verso di te deve produrre umilt&agrave;, umilt&agrave; verso Dio e umilt&agrave; verso gli altri. Devi essere sopraffatto dal travolgente, audace amore di Dio. In questo modo, il Dio di ogni consolazione ti consola in ogni tua afflizione (2Cor 1:3-4), e mentre rifletti sui doni che ricevi (e non su quello che non ricevi), troverai che il cuore viene consolato da questo amore misericordioso.</p>
<p>Ma purtroppo spesso non &egrave; cos&igrave;. Per esempio, i Corinzi ricevettero molti doni da Dio. Ma il frutto in loro non era l'umilt&agrave;, ma le divisioni, la ricerca di potere nella chiesa, e l'orgoglio verso gli altri (verso Paolo e verso Dio). Quindi Paolo li avverte:</p>
<blockquote>"Non gonfiatevi d'orgoglio esaltando l'uno a danno dell'altro. Infatti, chi ti distingue dagli altri? E che cosa possiedi che tu non abbia ricevuto? E se l'hai ricevuto, perch&eacute; ti vanti come se tu non l'avessi ricevuto?" (1Cor 4:6-7)</blockquote>
<p>Sentimenti di superiorit&agrave; vogliono dire che non hai capito l'amore immeritato di Dio in Cristo verso di te; qualsiasi cosa di cui vorresti vantarti &egrave; invece solo un motivo di ringraziare e lodare Dio.</p>
<h2>Il frutto dell'amore &egrave; la comunit&agrave; (Rut 2:15-16)</h2>
<p>Dopo il pranzo, Rut si alza per continuare a spigolare ancora prima dei servi. Lei non si riposa nella generosit&agrave; di Boaz n&eacute; si accontenta dei doni ricevuti ma vuole continuare ad amare Naomi. Cos&igrave; anche per te: ricevere l'amore di Dio non vuol dire smettere di amare, ma dovrebbe spingerti ad amare, cio&egrave; a dare e a fare, ancora di pi&ugrave; (2Cor 5:13-14).</p>
<p>Anche per Boaz l'amore non finisce qui. Non &egrave; che lui abbia fatto un dono e cos&igrave; abbia adempiuto le sue responsabilit&agrave;. L'amore non smette mai di dare, ma d&agrave; e d&agrave; e d&agrave;. Cos&igrave; &egrave; l'amore di Dio verso di te: "Dio che non ha risparmiato il proprio Figlio, ma lo ho dato per noi tutti, non ci doner&agrave; forse anche tutte le cose con lui? (Romani 8:32).</p>
<p>Per&ograve;, il punto di questa sezione della riflessione &egrave; che Boaz include altri nel suo amore, crea una comunit&agrave; di amore. La sua generosit&agrave; a Rut avrebbe potuto produrre gelosia e risentimento fra i servi e i mietitori. "Io ho lavorato tutto il giorno e ho preso quello che ho raccolto; Rut riceve tutto abbondantemente come regalo. Perch&eacute; non anch'io?" Questo &egrave; l'atteggiamento del figlio maggiore nella parabola del figlio prodigo (Lc 15:28-30), e di chi ha lavorato per tutto il giorno nella parabola delle diverse ore (Mt 20:1-16). Secondo la legge, Rut poteva solo raccogliere le spighe lasciate per terra dai mietitori. Quindi Boaz dice ai mietitori di togliere delle spighe dai covoni e di "accidentalmente" farle cadere. In questo modo loro diventano lo strumento dell'amore di Boaz e anche loro iniziano ad amare, con un amore che non gli costa niente (tanto, sono le spighe del padrone) e fanno bella figura. Ma adesso c'&egrave; una comunit&agrave; in cui regna l'amore verso i bisognosi.</p>
<p>Cos&igrave; &egrave; l'amore di Dio verso di te. Prima di tutto, crea una comunit&agrave; fra te e il Dio triuno. Per tutto l'eterno, il Padre, Figlio e Spirito hanno vissuto nel perfetto amore. Ma l'amore perfetto non &egrave; mai esclusivo perch&eacute; guarda sempre fuori e non a s&eacute; stesso. Vuole aggiungere altri alla comunit&agrave; di amore, e ti porta alla comunione con la comunit&agrave; della Trinit&agrave;.</p>
<p>Poi ti dovrebbe costringere a creare una comunit&agrave; mentre condividi e spargi l'amore di Dio. Spesso, invece, si cerca una comunit&agrave; invece di creare una comunit&agrave;. Quando si entra in un luogo, si chiede: "Chi conosco? Dove &egrave; il mio amico? Con chi mi trovo bene? Chi &egrave; come me? Chi mi &egrave; simpatico, mi fa sentire bene?" Questo tipo di comunit&agrave; che si cerca delude velocemente, perch&eacute; siamo tutti imperfetti e prima o poi succede qualcosa in modo che non ci sentiamo pi&ugrave; bene con loro.</p>
<p>Si deve chiedere, invece, "Chi posso amare? Chi &egrave; in bisogno? Chi non conosco?" Cos&igrave;, piuttosto di cercare una comunit&agrave;, crei una comunit&agrave;, una comunit&agrave; di amore che dura. Non pu&ograve; deludere perch&eacute; non dipende da quello che ricevi, ma dal tuo amore che non smette mai di dare.</p>
<h2>Il frutto dell'amore &egrave; la vita (Rut 2:17-20)</h2>
<p>Rut fece un giorno intero di lavoro spigolando, dalla mattina (Rut 2:7) fino alla sera (Rut 2:17). Non bastava, perch&eacute; poi doveva battere l'orzo raccolto, per separare la testa dal gambo. Rimase un efa di orzo, che &egrave; circa 30 litri, cio&egrave; praticamente abbastanza cibo (o soldi se lo vendesse) per vivere per un mese.</p>
<p>Naomi scorge Rut che ritorna a casa, forse si aspetta che venga con due manciate di orzo, una a testa per sopravvivere fino al giorno successivo. Mentre Rut si avvicina, Naomi si rende conto che &egrave; curva, poi vede l'enorme carico che porta sulle spalle. Finalmente Rut arriva e getta tutto l'orzo per terra. 30 litri di orzo. Come se non bastasse, poi dice che non serve cucinare stasera, e tira fuori la borsa con con gli avanzi del cibo da pranzo (Rut 2:14).</p>
<p>Naomi &egrave; sopraffatta e travolta da tutto questo. Sembra una persona diversa dalla Naomi di Rut 1:20-21, dove era amareggiata, poich&eacute; Dio le aveva riempita di amarezza, riteneva di essere spoglia di tutto, e che Dio l'aveva resa infelice. Sapeva di Boaz, ma non aveva detto a Rut, perch&eacute; era senza speranza. Ora per&ograve; non riesce a contenersi, e fa una serie di domande a raffica senza aspettare la risposta: Dove hai spigolato? Dove hai lavorato? Chi ti ha accolto?</p>
<p>Rut mostra amore <i>hesed</i> a Naomi, e riempie il vuoto della vita di Naomi con l'abbondanza. Trasforma la sua vita morta alla vera vita. Ma Naomi sa che Rut era lo strumento affinch&eacute; Dio mostrasse il suo amore <i>hesed</i>. Naomi esplode di gioia, e esclama, "Sia egli (cio&egrave; Boaz) benedetto dal Signore, perch&eacute; non ha rinunciato a mostrare ai vivi la bont&agrave; che ebbe verso i morti". Una domanda qui &egrave;, "Chi non ha rinunciato?" La frase &egrave; ambigua grammaticalmente, poteva essere o Boaz o Dio. Ma l'affermazione &egrave; vera di tutti e due, e forse Naomi si riferiva ad entrambi, perch&eacute; Dio aveva mostrato la sua bont&agrave; tramite la bont&agrave; di Boaz.</p>
<p>Un esempio umano &egrave; in un matrimonio "morto". Se il coniuge insiste con l'amore sacrificale, porta la vita al matrimonio. L'altro &egrave; amareggiato? Critico? Sempre arrabbiato? Distante e freddo? Non &egrave; la fine della storia, perch&eacute; abbiamo visto che le persone non rimangono sempre cos&igrave; come sono. Dio pu&ograve; trasformare il cuore, e un modo in cui lo fa &egrave; attraverso il tuo amore che sopraff&agrave; e travolge con la bont&agrave;.</p>
<p>Questa &egrave; anche come sperimenti l'amore da Dio. Se vai da un benzinaio con un mezzo serbatoio di benzina, fai il pieno e vai avanti come prima, non &egrave; cambiato niente. Ma quando il serbatoio &egrave; completamente vuoto, la macchina non va pi&ugrave; (come se fosse morta), sei bloccato senza forza, magari in mezzo al nulla, senza possibilit&agrave; di andare avanti. Poi arriva un'altra macchina, e il conducente trasferisce tutta la sua benzina dalla sua macchina alla tua, e la tua macchina &egrave; trasformata in vita dall'amore sacrificale dell'altro. Cos&igrave; Dio in Cristo ha agito verso di noi, quando il suo grande amore ha prodotto la vita in noi quando eravamo morti.</p>
<blockquote>"Dio ha vivificato anche noi, voi che eravate morti nelle vostre colpe. Dio, che &egrave; ricco in misericordia, per il grande amore con cui ci ha amati, anche quando eravamo morti nei peccati, ci ha vivificati con Cristo e ci ha risuscitati con lui e con lui ci ha fatti sedere nei luoghi celesti in Cristo Ges&ugrave;". (Efesini 2:1-6)</blockquote>
<h2>Il frutto dell'amore &egrave; il riscatto (Rut 2:20-23)</h2>
<p>Naomi spiega a Rut che Boaz &egrave; uno di quelli che ha il diritto di riscatto, che &egrave; un diritto nella legge di Mos&egrave;. Quando qualcuno era in difficolt&agrave;, un parente poteva difenderlo e aiutarlo. Per esempio, se la persona diventa povera e deve vendere la sua propriet&agrave;, quello con il diritto di riscatto pu&ograve; ricomprare o riscattare la propriet&agrave; (Lev 25:25-30). Cos&igrave; la propriet&agrave; rimane in famiglia. Similmente, se si vende come schiavo, ricompra o riscatta la persona (Lev 25:47-55). Pu&ograve; anche fungere da vendicatore quando qualcosa &egrave; ucciso (Num 35:12-37), e cos&igrave; difende il diritto di chi non pu&ograve; pi&ugrave;. Il matrimonio levitico (in cui ci si sposa la vedova del fratello defunto) &egrave; un concetto collegato, ma diverso.</p>
<p>Avere il diritto di riscatto era diverso dall'essere un aiuto. Qualcuno che aiuta d&agrave; dei soldi; un riscattatore o redentore prende possesso del problema, in modo che diventi il suo problema. Per esempio, se vediamo un senzatetto per strada, possiamo dargli dei soldi, magari anche suggerire dove andare per trovare un posto letto per la notte, che &egrave; un aiuto e una cosa positiva. Ma dato l'aiuto, lo dimentichiamo. Chi fa il redentore prende in carico le difficolt&agrave; dell'altro: d&agrave; anche un pasto, lo porta a casa per lavarsi, cerca un lavoro per lui, e cos&igrave; via. Non &egrave; facile!</p>
<p>Il buon samaritano (Luca 10:25-37) &egrave; un altro esempio. Avvicinandosi e fasciando le piaghe ha aiutato l'uomo, e ha gi&agrave; fatto pi&ugrave; del sacerdote e del Levita. Ma poi &egrave; diventato il suo problema: ha condotto l'uomo a una locanda dove si &egrave; preso cura di lui. Ha dato soldi all'oste per la cura. Ha promesso di ritornare. Ha redento l'uomo dalla sua situazione.</p>
<p>Pi&ugrave; avanti nel libro troviamo questa differenza (Rut 4:1-6). C'era un parente pi&ugrave; stretto di Boaz, che era disposto ad aiutare, comprando il terreno del marito di Naomi. Forse era anche un affarone per questo parente, un vantaggio per lui. Ma non era disposto a entrare nella vita di Naomi, prendendo i suoi problemi per s&eacute;, sposando Rut. Voleva riscattava il terreno, ma non riscattare Naomi e Rut. Per questo rinunci&ograve; al suo diritto di riscattato, e Boaz subentr&ograve;.</p>
<p>L'amore <i>hesed</i> non solo aiuta, ma riscatta e redime dalle difficolt&agrave;. Il suo frutto &egrave; il riscatto o la redenzione.</p>
<p>Nelle culture antiche, di cui gli studiosi hanno trovato diversi codici legali, quello del diritto di riscatto sembra un concetto unico al popolo di Israele. Dio aveva stabilito questo diritto in Israele, affinch&eacute; il suo unico popolo mostrasse il suo carattere. Infatti, Dio mostra l'amore <i>hesed</i>, che produce il riscatto e la redenzione. Giobbe lo sapeva nei suoi guai:</p>
<blockquote>"Ma io so che il mio Redentore vive e che alla fine si alzer&agrave; sulla polvere. E quando, dopo la mia pelle, sar&agrave; distrutto questo corpo, senza la mia carne, vedr&ograve; Dio." (Giobbe 19:25-26)</blockquote>
<p>Anche nell'oppressione dell'esilio, Geremia sapeva che Dio aveva il diritto di riscatto per il suo popolo, che avrebbe esercitato:</p>
<blockquote>"I figli d'Israele e i figli di Giuda sono oppressi insieme; tutti quelli che li hanno deportati li tengono e rifiutano di lasciarli andare. Il loro vendicatore (redentore/riscattatore) &egrave; forte, si chiama SIGNORE degli eserciti; certo egli difender&agrave; la loro causa, dando riposo alla terra e gettando lo scompiglio fra gli abitanti di Babilonia." (Ger 50:33-34)</blockquote>
<p>Questo amore che redime ci porta a Ges&ugrave; Cristo, alla sua incarnazione e morte. Quando tu eri senza speranza, non ti ha mandato dei consigli, dei soldi, o delle istruzioni. Ti ha dato s&eacute; stesso. Non ti ha fatto vedere come fare, l'ha fatto lui stesso. Il tuo problema &egrave; diventato il suo problema, di cui ha preso la responsabilit&agrave; e che ha preso in carico</p>
<p>Come quello con il diritto di riscatto comprava il terreno per pagare i debiti, cos&igrave; Ges&ugrave; Cristo ha comprato te per pagare il tuo debito, con la sua morte sulla croce. Ges&ugrave; il tuo redentore ha dato la sua vita come prezzo di riscatto per te (Mc 10:45; 1Tim 2:6; 1Cor 7:23), per riscattarti dalla condanna della legge e dall'iniquit&agrave; (Gal 3:13; 4:5; Tito 2:14).</p>
<h2>Conclusione</h2>
<p>Il vero amore &egrave; potente. Trasforma quelli che lo d&agrave; e quelli che lo ricevono. Quando riflettiamo sull'amore di Dio, alcuni di questi frutti sono la nostra giusta risposta, come l'umilt&agrave; e la comunit&agrave;. Se non abbiamo questi frutti, non abbiamo capito sufficientemente la natura gratuita, misericordiosa, e inclusiva dell'amore immeritato che abbiamo ricevuto. Dobbiamo imparare a credere, non solo professando questo amore ma vivendo l'amore. E l'amore di Dio &egrave; abbastanza grande che anche quando non abbiamo il frutto dell'umilt&agrave; e della comunit&agrave;, c'&egrave; il perdono di Ges&ugrave;. Perch&eacute; gli altri frutti dell'amore sono automatici, come la vita e riscatto. La nostra nuova vita e la nostra redenzione non dipendono dai nostri fallimenti, ma solo dall'amore di Dio che ha agito per il nostro bene.</p>
</p>

<?
$n=4;
require("indice.php");
require("../../piede.php");
?>
