h<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "La forma dell'amore (Rut 2:1-12)";
$key = "amore,forma,Rut 2:1-12";
$titolo = "La forma dell'amore (Rut 2:1-12)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>La forma dell'amore (Rut 2:1-12)</h1>
<p>Nelle due riflessioni precedenti, abbiamo visto varie caratteristiche dell'amore: l'impegno per l'altro, con il sacrificio. Che &egrave; pi&ugrave; evidente nelle difficolt&agrave;. Per&ograve;, bisogna mettere Dio prima dell'amore o dell'amato. Infine, l'amore &egrave; la morte e la gloria. In questa riflessione, vedremo la forma dell'amore: speranza, protezione, benedizione, e Ges&ugrave; Cristo.</p>
<h2>La forma dell'amore &egrave; la speranza (Rut 2:1-3)</h2>
<p>Naomi, nelle sue difficolt&agrave;, sembra depressa. Dovrebbe fare qualcosa per risolvere o alleviare la sua situazione, ma non ha pi&ugrave; energia per fare qualcosa. Anche se ha parenti ricchi che potrebbero aiutare. Non riesce neanche a mandare Rut a fare qualcosa, &egrave; Rut che deve chiedere permesso a Naomi di andare nei campi.</p>
<p>La depressione &egrave; complicata. Non puoi dire ad una persona depressa, "Alzati, fai qualcosa per risolvere il problema". Anche se sarebbe il comportamento giusto, &egrave; l'impossibilit&agrave; di alzarsi che &egrave; precisamente il problema. Questa depressione pu&ograve; essere causata dalle circostanze esterne ma anche dai livelli chimici o ormonali nel corpo, per cui uscirne non &egrave; semplice. Per&ograve;, il consiglio che tutti gli esperti danno &egrave; di parlarne con qualcuno. Sei ti trovi in uno stato di stanchezza mentale, non stare l&igrave; da solo ma trova delle persone che possono stare con te e accompagnarti.</p>
<p>Nelle stesse difficolt&agrave;, anzi con difficolt&agrave; maggiori (perch&eacute; non ha una famiglia a Betlemme ed &egrave; straniera, del popolo nemico) Rut risponde diversamente, spinta e costretta dall'amore. Si d&agrave; da fare per risolvere almeno un problema, la fame. Va in un campo a caso durante il tempo della mietitura dell'orzo. Non pu&ograve; mietere perch&eacute; non &egrave; il suo campo, ma raccoglie i pezzi rimasti sulle piante o per terra che non erano raccolti dei mietitori. Questa pratica, di lasciare una parte della raccolta, dove i poveri e bisognosi la potevano raccogliere, era stabilita dalla legge di Mos&egrave;.</p>
<p>Rut, che si &egrave; rifugiata sotto le ali di Dio (Rut 2:12), aveva speranza per il futuro. Questa speranza le ha dato l'amore e la forza per fare qualcosa. E Dio c'era quando si &egrave; buttata nello sconosciuto. Il testo dice "per caso si trov&ograve;...", che ha il senso "per caso &egrave; capitato che..." La Nuova Diodati legge, "le capit&ograve; per caso di trovarsi" nel campo di Boaz. Viene detto due volte che era casuale il fatto che Rut and&ograve; nel campo di Boaz. Ma gli ebrei non credevano nel caso. Era invece lo stile della letteratura ebraica di non menzionare Dio, ma lasciare intendere che Dio era dietro gli avvenimenti racconti. Cos&igrave; anche per prendere una decisione importante, usavano l'urim e il turrim, in pratica tiravano a sorte per lasciare a Dio esprimere la sua volont&agrave;.</p>
<p>L'autore qui vuole che noi vediamo la mano di Dio dietro le circostanze. Se ti metti in gioco, se agisci in amore e speranza, puoi incontrare Dio. Se non fai niente, se fai quello che fai sempre, se pianifichi tutto secondo le tue risorse, incontrerai te stesso. L'amore pu&ograve; sacrificare s&eacute; stesso, buttandosi nel buio, perch&eacute; sa che l&igrave; ci sar&agrave; Dio.</p>
<h2>La forma dell'amore &egrave; la protezione (Rut 2:4-10)</h2>
<p>Boaz viene dalla citt&agrave;, dove abita, per vedere come vanno le cose nei suoi campi. "Ecco che Boaz giunse" &egrave; un altro avvenimento che &egrave; capitato cos&igrave;, ma Dio sta operando affinch&eacute; giungesse proprio in quel giorno.</p>
<p>Boaz vede nella distanza una signora che non conosce. Il fatto che sa gi&agrave; che non &egrave; un suo dipendente, uno dei suoi mietitori, che Boaz avrebbe riconosciuto, vuol dire che Boaz &egrave; una persona interessata negli altri, sa chi lavora per lui - che non &egrave; sempre il caso al giorno d'oggi.</p>
<p>Il responsabile dei mietitori dice che, in pratica, non &egrave; nessuno. Non ha un nome. Solo che &egrave; una donna, &egrave; moabita. Siccome non ha una famiglia o un protettore, &egrave; da trascurare. (Puoi leggere Giudici 19 per capire come trattavano le donne in quel periodo.) Sa solo che era tornata con Naomi, ma quello non le d&agrave; nessuna importanza al responsabile. Come Naomi non la prendeva in considerazione (Rut 1:21 - Naomi pensava di essere spoglia di tutto, anche se Dio le aveva dato Rut che era accanto a lei), cos&igrave; pure anche il responsabile.</p>
<p>Ma Boaz &egrave; diverso. Non dobbiamo pensare che abbia preso una cotta perch&eacute; era bella, perch&eacute; era lontana. Non dobbiamo pensare che aiutava Rut a causa di quello che aveva fatto per Noami, perch&eacute; si interessava di lei prima di sapere. Invece, Boaz ha visto una persona marginalizzata, sola (dietro ai mietitori), e ha pensato ai suoi bisogni, come fare del bene a lei.</p>
<p>E il suo bisogno era la protezione. Qualcuno che non &egrave; nessuno, non considerato da nessuno, &egrave; preda facile. "Non ha diritti qui, nessuno la difender&agrave;." Come molti adescano i deboli oggi per i propri interessi, cos&igrave; anche allora. Di nuovo, Giudici 19 illustra cosa pensavano delle donne e degli stranieri. Quindi (Rut 2:8-9), Boaz d&agrave; ordini che rimanga con le altre, che non sia toccata, e che abbia diritto all'acqua come gli altri.</p>
<p>Rut riconosce l'importanza di questa protezione nella sua situazione, e riconosce la grazia da parte di Boaz che gliela concede, perch&eacute; da straniera non le spettava, e lei non la meritava (Rut 2:10).</p>
<p>Come vedremo in Rut 2:12, Rut cerc&ograve; la protezione di Dio. Come Dio mostr&ograve; il suo amore <i>hesed</i> a Naomi dandole l'amore <i>hesed</i> di Rut, cos&igrave; Dio mostr&ograve; la forma dell'amore della protezione a Rut dandole la forma dell'amore della protezione di Boaz.</p>
<p>Anche noi, nel nostro amore per gli altri, dobbiamo essere sempre pronti a difendere e a proteggere i deboli, gli indifesi, quelli che nessun considera. E ce ne sono tanti nella societ&agrave;.</p>
<h2>La forma dell'amore &egrave; la benedizione (Rut 2:11-12)</h2>
<p>Quando Boaz si inform&ograve; di Rut, non sapeva chi fosse. Nonostante ci&ograve;, voleva proteggerla, perch&eacute; era debole e indifesa.</p>
<p>Ma poi seppe che aveva accompagnato Noemi, e fece del bene a lei. Inoltre, in questi due versetti, chiese la benedizione di Dio per lei. La benedizione del contraccambio da Dio di quello che aveva fatto, nonostante i sacrifici (per esempio l'abbandono della famiglia e del proprio paese).</p>
<p>Anche noi dobbiamo essere convinti che Dio benedir&agrave; il nostro amore. &Egrave; un aspetto della vita cristiana di cui parliamo poco, forse per non pensare alla salvezza per opere oppure perch&eacute; ci sembra sbagliato fare del bene per ricevere una ricompensa. Ma se ci rifugiamo sotto le ali di Dio nelle difficolt&agrave;, deve voler dire qualcosa. Nell'amore <i>hesed</i> ci saranno delle difficolt&agrave; - sacrifici, critiche (che non dobbiamo fare del bene all'altro perch&eacute; non lo merita, ti devi proteggere, non puoi permettere di fare dei sacrifici per l'altro) - ma oltre alle difficolt&agrave; ci sar&agrave; anche il nascondiglio delle braccia di Dio. Che siamo protetti (non da Boaz ma in realt&agrave; da Dio) e che Dio non dimenticher&agrave; questa fiducia. Forse avrai un'abbondanza del bene in paradiso, forse in questa vita, ma Dio si ricorda che hai fatto del bene, che hai amato, e benedir&agrave;.</p>
<blockquote>Chi semina scarsamente mieter&agrave; scarsamente; e chi semina abbondantemente mieter&agrave; altres&igrave; abbondantemente. (2Cor 9:6)</blockquote>
<blockquote>Quando tu fai l'elemosina, sia fatta in segreto, e il Padre tuo, che vede nel segreto, te ne dar&agrave; la ricompensa. (Mt 6:4)</blockquote>
<blockquote>Non vi ingannate, non ci si pu&ograve; beffare di Dio; perch&eacute; quello che l'uomo avr&agrave; seminato, quello pure mieter&agrave;. Perch&eacute; chi semina per la sua carne, mieter&agrave; corruzione dalla carne; ma chi semina per lo Spirito mieter&agrave; dallo Spirito vita eterna. Non ci scoraggiamo di fare il bene; perch&eacute;, se non ci stanchiamo, mieteremo a suo tempo. (Gal 6:7-9)</blockquote>
<h2>La forma dell'amore &egrave; Ges&ugrave;</h2>
<p>La forma della vita per molti &egrave; il cerchio. Nelle civilt&agrave; antiche era spesso cos&igrave;, ma anche in quelle orientali oggi, per esempio la credenza nella reincarnazione.</p>
<p>Anche per molti adesso pu&ograve; sembrare cos&igrave;: ci si alza, si va a lavorare, si torna a casa, ci si addormenta, poi tutto da capo, giorno dopo giorno. Poi anno dopo anno, sempre lo stesso ritmo. Non c'&egrave; speranza di uscire da questo ciclo. Alcuni cercano di celebrare il fatto che si nasce e si muore e basta, come nel film Re Leone, dove si canta in Cerchio della vita, " &Egrave; una giostra che va, questa vita che; Gira insieme a noi e non si ferma mai; E ogni vita lo sa che rinascer&agrave;; In un fiore che fine non ha". Ma la realt&agrave; &egrave; che dopo un secolo, quasi tutti noi saremo completamente dimenticati, anche dai nostri discendenti, e non vivremo pi&ugrave; in nessun senso per un altro giro.</p>
<p>Gli ebrei erano diversi. Per loro, la storia era una linea, la storia aveva uno scopo perch&eacute; Dio lo stava portando alla giusta conclusione. Per&ograve;, se vogliamo essere pi&ugrave; precisi, possiamo affermare che &egrave; una linea nella forma della i lunga. Dio ha stabilito l'universo in modo che l'alto passa attraverso il basso, la gloria viene dalla sofferenza. "Se il granello di frumento caduto in terra non muore, rimane solo; ma se muore, produce molto frutto" (Gv 12:24). &Egrave; il racconto che fa appello alla nostra coscienza, perch&eacute; sappiamo dentro di noi che deve essere cos&igrave;. Quasi tutti i romanzi iniziano bene, poi c'&egrave; una crisi, poi una risoluzione. I film romantici hanno sempre la stessa trama: si conoscono, si lasciano, si rimettono insieme e tutto &egrave; meglio di prima.</p>
<p>Per esempio, uno dei pi&ugrave; grandi racconti, <i>Il Signore degli anelli</i>, segue questa linea i lunga. Inoltre, ad un certo punto c'&egrave; anche un discorso da uno dei protaganisti che la spiega. Nella versione cinemagrafica:<br /> 
<b>Sam:</b> &Egrave; tutto sbagliato. Di diritto non dovremmo nemmeno essere qui. Ma ci siamo. &Egrave; come nelle grandi storie, signor Frodo. Quelle che contavano davvero. Piene di oscurit&agrave; e pericolo erano, e a volte non volevi conoscere la fine. Perch&eacute; come poteva la fine essere felice? Come poteva il mondo tornare come era prima quando era successo cos&igrave; tanto male?
Ma alla fine, &egrave; solo una cosa passeggera, questa ombra. Anche l'oscurit&agrave; deve passare. Arriver&agrave; un nuovo giorno. E quando il sole splender&agrave;, splender&agrave; pi&ugrave; chiaro. [La fine &egrave; migliore dell'inizio, anche se passa per il punto basso.]
Quelle erano le storie che ti rimanevano dentro. [Fanno appello al nostro cuore.] Che avevano un significato. Anche se eri troppo piccolo per capire perch&eacute;. Ma penso, signor Frodo, che io capisca. Ora lo so. La gente in quelle storie aveva molte possibilit&agrave; di tornare indietro, solo che non lo fecero. [Perch&eacute; in fondo alla linea i lunga c'&egrave; speranza.] Perch&eacute; si stavano aggrappando a qualcosa.<br />
<b>Frodo:</b> A cosa ci stiamo aggrappando, Sam?<br />
<b>Sam:</b> Che c'&egrave; del bene in questo mondo, signor Frodo. E vale la pena combattere per esso. [Noi ci aggrappiamo a Dio, per cui vale la pena combattere, perch&eacute; Dio &egrave; il bene e non &egrave; il bene che &egrave; Dio.]</p>
<p>Questa &egrave; la forma del pi&ugrave; grande racconto di tutti i tempi, quello di Ges&ugrave; Cristo. In altre lingue, &egrave; ancora pi&ugrave; evidente, perch&eacute; l'i lunga in inglese, spagnolo e portoghese &egrave; di Jesus o Jes&uacute;s. La forma dell'amore &egrave; l'i lunga; la forma dell'amore &egrave; Ges&ugrave;.</p>
<p>Nella versione breve, leggiamo:</p>
<blockquote>Cristo mor&igrave; per i nostri peccati, secondo le Scritture; fu seppellito, &egrave; stato risuscitato il terzo giorno. (1Cor 15:3-4)</blockquote>
<p>Nella versione lunga, leggiamo:</p>
<blockquote>Cristo Ges&ugrave;, pur essendo in forma di Dio, non consider&ograve; l'essere uguale a Dio qualcosa a cui aggrapparsi gelosamente, ma svuot&ograve; s&eacute; stesso, prendendo forma di servo, divenendo simile agli uomini; trovato esteriormente come un uomo, umili&ograve; s&eacute; stesso, facendosi ubbidiente fino alla morte, e alla morte di croce. Perci&ograve; Dio lo ho sovranamente innalzato e gli ha dato il nome che &egrave; al di sopra di ogni nome, affinch&eacute; nel nome di Ges&ugrave; si pieghi ogni ginocchio nei cieli, sulla terra, e sotto terra, e ogni lingua confessi che Ges&ugrave; Cristo &egrave; il Signore, alla gloria di Dio Padre. (Fili 2:5-11)</blockquote>
<p>La forma dell'amore di Ges&ugrave; Cristo &egrave; una i lunga. Rut lo capisce, pur vivendo 1300 anni prima, e la forma dell'amore di Rut &egrave; una i lunga. E, Paolo dice in Fili 2:3-5, che il nostro amore deve avere la stessa forma: "Abbiate in voi lo stesso sentimento che &egrave; stato anche in Cristo", cio&egrave; "con umilt&agrave;, stima gli altri superiori a te stesso, cercando non il proprio interesse, ma quello degli altri". Questo porta alla morte di te stesso, perch&eacute; in fondo alla i lunga l'amore &egrave; pi&ugrave; evidente. Non puoi sapere come o quando ci sar&agrave; il ribaltamento, la parte in salita. Ma porta anche alla vera vita nascosta in Cristo, nascosta in cima alla i lunga, dove sta Cristo adesso. Nonostante tutto quello che ti possono fare o dire, sei protetto da Dio (se ti rifugi sotto le sue ali) e sei benedetto da Dio.</p>

<?
$n=3;
require("indice.php");
require("../../piede.php");
?>
