<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "La gloria dell'amore al secondo posto (Rut 1:15-22)";
$key = "amore,gloria,Rut 1:15-22";
$titolo = "La gloria dell'amore al secondo posto (Rut 1:15-22)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>La gloria dell'amore al secondo posto (Rut 1:15-22)</h1>
<p>In questo brano vedremo alcune altre caratteristiche del vero amore: di Rut, ma anche di Dio e di te. I punti principali sono che c'&egrave; gloria nell'amore vero, ma alla fine non &egrave; la cosa principale nella vita. Rivedremo anche alcune delle caratteristiche del primo studio, dell'amore nelle difficolt&agrave; che richiede impegno e sacrificio.</p>
<h2>L'amore non &egrave; Dio (Rut 1:15-16)</h2>
<p>Anzi, l'amato non &egrave; Dio.</p>
<p>Naomi, nel suo amore, giustamente voleva il meglio per Rut, anche se voleva dire sacrificare il suo bene. Per&ograve;, ha sbagliato nella sua valutazione di quello che era il meglio per Rut. Pensava che stesse meglio con un marito, ma anche con il proprio popolo e con i suoi d&egrave;i (Rut 1:15).</p>
<p>Il vero amore, abbiamo visto nello studio precedente, &egrave; non mettere te stesso al primo posto, ma di cercare prima di tutto gli interessi degli altri. Questa volta, vediamo che gli interessi sentiti dell'altro non sono la priorit&agrave;. Dio lo &egrave;. Gli interessi dell'altro sono in realt&agrave; che stanno in un buon rapporto con Dio.</p>
<p>Rut lo capisce, perch&eacute; afferma che il Duo di Naomi sar&agrave; il suo Dio (Rut 1:16). Non ama solo Naomi, anzi non ama prima di tutto Naomi. Il suo amore principale &egrave; per Yahweh, il Dio di Israele, il popolo nemico di lei e di tutti i Moabiti, anche prima del suo amore per s&eacute; stessa e i suoi interessi di trovare un marito e il sostegno di una famiglia.</p>
<p>Purtroppo, l'atteggiamento di cercare l'amore a tutti i costi &egrave; ancora molto comune. C'&egrave; in alcuni il desiderio di un amore ideale che diventava un idolo. C'&egrave; il concetto romantico del matrimonio perfetto che soddisfa tutti i bisogni per sempre e senza mai una difficolt&agrave;. Basta l'amore e andr&agrave; tutto bene. Tanti miei amici hanno cercato il matrimonio a tutti i costi, hanno sposato il primo possibile anche se non seguiva Dio. Il risultato era un disastro per la fede. C'&egrave; che dopo due divorzi ha capito che l'amore da Dio e per Dio &egrave; pi&ugrave; importante. Ma c'&egrave; anche chi non ama pi&ugrave; Dio, trascinato dall'incredulit&agrave; del coniuge. Per altri, la felicit&agrave; dei figli &egrave; lo scopo primario della vita, forse dando loro tutto quello che vogliono, forse non disciplinandoli, forse mancando al culto perch&eacute; hanno altri interessi, con la conseguenza che Dio non fa parte della loro vita. Per&ograve;, come ha detto Ges&ugrave;,</p>
<blockquote>Chi ama padre o madre pi&ugrave; di me, non &egrave; degno di me; e chi ama figlio o figlia pi&ugrave; di me, non &egrave; degno di me. (Matteo 9:37)</blockquote>
<p>Ancora pi&ugrave; comune al giorno d'oggi &egrave; un amore centrato su di s&eacute;. Quello che &egrave; importante, secondo questo amore, &egrave; sentirsi bene, realizzarsi. Bisogna ubbidire ai propri sentimenti. Se non sei pi&ugrave; innamorato della moglie, cercane un'altra. Non importa quello che pensano gli altri; anzi, &egrave; importante che gli altri affermino quello che tu vuoi sentire, altrimenti sono tossici. Quello che pensa Dio &egrave; assolutamente da non considerare.</p>
<h2>L'amore &egrave; la morte (Rut 1:17-18)</h2>
<p>Come abbiamo visto nello studio precedente, l'amore a senso unico vuol dire spesso la morte dell'io per dare vita agli altri.</p>
<p>In questo brano, troviamo Naomi &egrave; senza marito e senza figli; &egrave; senza lavoro e senza il supporto dalla famiglia; &egrave; in lutto e depressa. Come risponderesti ad una situazione del genere? Forse metteresti a distanza il bisognoso, forse daresti un po' di soldi, forse diresti che andr&agrave; meglio, forse consiglieresti un aiuto professionale.</p>
<p>Rut invece d&agrave; la sua vita. Rut &egrave; disposta a morire per sua nuova, sia letteralmente sia metaforicamente, rinuncia a tutto quello che ha e quello che &egrave;. Rut diventa senza speranza (di una propria famiglia e una propria vita) affinch&eacute; Naomi possa avere una speranza per il futuro.</p>
<p>Che cosa riceve in contraccambio? Il silenzio. Niente ringraziamento, niente incoraggiamento reciproco. Niente 104 con qualche aiuto per assistere Naomi. Niente di niente. Ecco l'amore, non della Disney, ma l'amore <i>hesed</i> / <i>agape</i>.</p>
<p>Forse tu hai sperimentato un rapporto cos&igrave;, o lo stai sperimentando, o lo sperimenterai. Non sto parlando di un rapporto abusivo, quando il marito colpisce la moglie o i figli, in cui la risposta giusta &egrave; chiamare la polizia o gli assistenti sociali. Ma ci sono rapporti difficili per motivi fisici o caratteriali, in cui ricevi silenzio piuttosto che intimit&agrave; per il tuo amore. Forse i figli sono difficili o diversi, e ricevi critiche per come li educhi piuttosto di comprensione delle difficolt&agrave; o incoraggiamento a perseverare. Forse il marito o la moglie non restituisce il tuo amore nel modo in cui vorresti. Forse i genitori sono anziani, forse con Parkinson o Alzheimer, e bisogna sacrificare tanto tempo e tanta energia per aiutarli.</p>
<p>In ogni caso, pu&ograve; sembrare che tu sia in un vicolo cieco, senza via di scampa. Come puoi sopravvivere in quei casi, se l'amore &egrave; la morte?<br />
1. Ricordarti che Dio ti ha amato e ti ama nello stesso modo. Quando eri difficile, peccatore, dicevi di no o niente a Dio, Cristo &egrave; morto per noi. L'amore suo &egrave; la morte.<br />
2. Rifugio nell'amore di Dio, come faceva Rut in Rut 1:16 e come Boaz afferm&ograve; che faceva in Rut 2:12. Grida a Dio che non ce la fai, che &egrave; troppo pesante. Getta le preoccupazioni su Dio che ha cura di te (1P 5:7), e tuffati nell'amore di Cristo che sorpassa ogni conoscenza, affinch&eacute; tu sia ricolmo di tutta la pienezza di Dio (Efes 3:17-19).</p>
<h2>L'amore per il cuore infranto (Rut 1:19-21)</h2>
<p>Finalmente Naomi e Rut arrivano a Betlemme. Naomi ritorno dopo pi&ugrave; di anni e la citt&agrave; &egrave; commossa, cio&egrave; agitata. Sono sbalorditi e si meravigliano. "&Egrave; veramente lei?" Come &egrave; possibile?</p>
<p>Ci doveva essere una festa, ma Naomi ha stroncato i festeggiamenti con il suo lamento. La sua vita non era pi&ugrave; dolce (il significato di Naomi) ma amara (il significato di Mara), perch&eacute; Dio le aveva riempito di amarezza e testimoniava contro di lei.</p>
<p>Abbiamo considerato i lamenti nello studio precedente. Nessuno ha criticato Naomi per il suo lamento, n&eacute; i Betlemmiti, n&eacute; l'autore del libro, neanche Dio. &Egrave; santo esprimere a Dio i propri sentimenti, come succede spesso nei Salmi.</p>
<p>Per&ograve;, bisogna stare attenti che il lamento non si trasformi in amarezza o critica verso Dio, oppure che venga girato verso le altre persone piuttosto che a Dio, quando il lamento pu&ograve; diventare pettegolezzi, critiche, o un ritiro nel silenzio.</p>
<p>Il problema principale di Naomi era l'impazienza. Non aveva aspettato abbastanza tempo per capire come Dio era presente con lei e usava le sue circostanze per i suoi buoni propositi.<br />
1. Dio ha mostrato il suo amore di <i>hesed</i> mandandole Rut, che trasmetteva questo amore da Dio verso di Naomi. Il vero amore per le persone in difficolt&agrave; &egrave; spesso non un'esortazione ad essere felice, n&eacute; un'affermazione superficiale, ma entrare nel loro mondo, e condividere e portare le loro sofferenze. Cio&egrave;, morire per loro, come fece Rut. Ecco l'amore per il cuore infranto.<br />
2. Se avesse aspettato ancora un centinaio di anni, avrebbe scoperto che tutto questo avrebbe portato alla nascita di Davide, il pi&ugrave; grande re di Israele. E se avesse aspettato altri mille anni, avrebbe scoperto che tutte queste difficolt&agrave;, tutta questa morte, avrebbe portato alla nascita di Ges&ugrave; Cristo, il re dei re.</p>
<h2>L'amore &egrave; gloria (Rut 1:22)</h2>
<p>Consideri questo versetto in confronto con il precedente. Naomi disse, "Il Signore mi riconduce spoglia di tutto". L'autore invece scrisse, "Naomi se ne torn&ograve; con Rut, la Moabita, sua nuora, venuta dalle campagne di Moab".</p>
<p>Naomi era cos&igrave; avvolta nel suo dolore che non riconobbe Rut n&eacute; il suo amore, n&eacute; come Dio la sosteneva tramite Rut. Dio non si arrabbi&ograve; verso Naomi per il suo lamento n&eacute; la sgrid&ograve; per la sua dimenticanza, ma continu&ograve; ad amarla con <i>hesed</i>.</p>
<p>Considera invece Rut. Naomi almeno &egrave; tornata a casa, alla cultura e alle persone che conosceva. In realt&agrave;, &egrave; Rut che arriva a niente, spoglia di tutto, senza marito, una straniera in un paese strano, di un popolo nemico e odiato ai Giudei. Poteva aspettarsi solo di subire la discriminazione, la povert&agrave;, e la solitudine. Addirittura, Naomi la ignorava. Forse secondo Rut 1:19, Naomi non le parl&ograve; fino da quando Rut aveva deciso di accompagnare Naomi. Poi, Naomi afferm&ograve; di essere spoglia di tutto. Che cosa doveva pensare Rut? "Eccomi! Sono qui! Ti sembro trasparente?" Rut e il suo amore non erano apprezzati e neanche riconosciuti.</p>
<p>&Egrave; questo quello che Rut si aspettava quando decise di vivere una vita di amore totale? S&igrave;! Perch&eacute; era disposta ad amare fino alla morte. Ed anche quello che tu ti devi aspettare se segui la via dell'amore <i>hesed</i>, e segui la via dell'amore di Dio. Come abbiamo visto nello studio precedente, &egrave; l'amore del cristiano a senso unico:</p>
<blockquote>Noi che viviamo siamo sempre esposti alla morte per amore di Ges&ugrave;, affinch&eacute; anche la vita di Ges&ugrave; si manifesti nella nostra carne mortale. (2Corinzi 4:11)</blockquote>
<p>Se ami come Rut, se ami come Ges&ugrave; Cristo, soffrirai alle mani di chi si approfitta, di chi non risponde, di chi vuole rimanere con cuore duro. Come puoi resisti? Le lettere del Nuovo Testamento danno diversi incoraggiamenti e esortazioni all'amore che persevera davanti a chi ti fa male:</p>
<blockquote>Con ogni umilt&agrave; e mansuetudine, con pazienza, sopportatevi gli uni gli altri con amore. (Efesini 4:2)<br />
Sopportatevi gli uni gli altri e perdonatevi a vicenda, se uno ha di che dolersi di un altro. Come il Signore vi ha perdonati, cos&igrave; fate anche voi. (Colossesi 3:13)<br />
Abbiate amore intenso gli uni per gli altri, perch&eacute; l'amore copre una gran quantit&agrave; di peccati. (1Pietro 4:8)<br />
L'amore &egrave; paziente, &egrave; benevolo; l'amore non invidia; l'amore non si vanta, non si gonfia, non si comporta in modo sconveniente, non cerca il proprio interesse, non si inasprisce, non addebita il male, non gode dell'ingiustizia, ma gioisce con la verit&agrave;; soffre ogni cosa, crede ogni cosa, spera ogni cosa, sopporta ogni cosa. (1Cor 13:4-7)</blockquote>
<p>Ecco la tua gloria. Non quando fai grandi cose per Dio, ma quando ami in silenzio, quando ami eppure disprezzato, quando ami e rimani solo. Come Ges&ugrave; ha amato te.</p>
<p>Il momento di gloria di Rut non era il suo matrimonio con Boaz, non era essere la bisnonna del re Davide, non era appare nella genealogia del Messia, ma quando stava alla porta di Betlemme, ignorata dai Giudei, dimenticata dalla suocera, vedova e straniera, senza protettore - tranne il Dio d'Israele sotto le cui ali era venuta a rifugiarsi (Rut 2:13) - e con un amore totale, di impegno e sacrificio, verso Naomi.</p>
<p>Il tuo momento di gloria non &egrave; quando fai una grande predica, non &egrave; quando conduci 10 persone a Cristo, non &egrave; quando diventi pastore o missionario, ma &egrave; quando perdoni per la millesima volta qualcuno che non sa quanto male ti ha fatto, quando preghi per il tuo perseguitore, quando fai gioiosamente le faccende domestiche senza essere apprezzato ma forse criticato, quando vai a trovare qualcuno in difficolt&agrave; e nessun altro lo sa.</p>
<p>Come pure il momento di gloria di Ges&ugrave; Cristo non era i tanti miracoli che fece, non era la risurrezione di Lazzaro, non era il Sermone sul monte, ma la croce. Ges&ugrave; stesso disse:</p>
<blockquote>L'ora &egrave; venuta, che il Figlio dell'uomo deve essere glorificato. In verit&agrave;, in verit&agrave; vi dico che se il granello di frumento caduto in terra non muore, rimane solo; ma se muore, produce molto frutto. (Giovanni 12:23-24)</blockquote>
<p>Perch&eacute; la sua gloria era la sua morte, verso quelli senza speranza verso Dio, verso te, quando era solo e disprezzato, abbandonato dai discepoli che lui amava. Eppure, nella sua morte, nel suo amore, c'&egrave; il frutto dell'amore e della vita per te.</p>
<p>Che anche il nostro amore, in cui moriamo a noi stessi, produca la vita in Cristo negli altri.</p>

<?
$n=2;
require("indice.php");
require("../../piede.php");
?>
