<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Posto per un proposito (Genesi 41)";
$key = "Posto per un proposito,Genesi 41,giuseppe,genesi,riflessioni";
$titolo = "Posto per un proposito (Genesi 41)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Posto per un proposito (Genesi 41)</h1>
<p>Passarono due anni dopo i sogni dei due servi di faraone (Gen 41:1). Nello studio precedente, &egrave; stata considerata la questione perch&eacute; Dio fece aspettare altri due anni - senza una risposta chiara, perch&eacute; Dio non lo disse come non spiega neanche a noi nel presente tutti i motivi per cui ci fa aspettare. Infatti, passarono 13 anni dai 17 anni di Giuseppe quando ebbe i sogni della sua famiglia (Gen 37:2) fino ai 30 anni quando apparve davanti al faraone (Gen 41:46). Non sappiamo in quale modo sono divisi questi 13 anni fra il tempo in famiglia prima di essere venduto, il tempo come schiavo e il tempo come prigioniere, solo che i servi del faraone era in prigione "per un certo tempo" prima di fare i loro sogni.</p>
<p><i>Come reag&igrave; il faraone ai sogni e perch&eacute;? (Gen 41:8)</i></p>
<p>Era turbato e chiam&ograve; i saggi del regno per un'interpretazione, perch&eacute; prendeva sul serio il fatto che i sogni potevano essere una rivelazione da parte degli d&egrave;i (in cui credeva). Il fatto che fece due sogni simili sottolineava (secondo lui) la loro importanza - ci sono diversi documenti di altri popoli di antichit&agrave; che attestano al fatto che credevano che un sogno ripetuto fosse particolarmente significativo. Inoltre, la fine dei due sogni non prometteva niente di buono.</p>
<p><i>Come reag&igrave; il capo dei coppieri? (Gen 41:9-13)</i></p>
<p>Dopo essere rilasciato dal prigione, non si ricord&ograve; pi&ugrave; di Giuseppe (Gen 40:23). Riconobbe di aver sbagliato (era una sua colpa) e raccont&ograve; che "un giovane ebreo", cio&egrave; Giuseppe, aveva correttamente interpretato il suo sogno e quello del capo panettiere.</p>
<p>Giuseppe venne chiamato dal faraone e fu preparato (Gen 41:14-15). Essere rasi era normale per gli egizi, anche se era vergognoso per gli ebrei che preferivano la barba (per esempio Amos 8:10; Giobbe 1:20). &Egrave; l'inizio del processo di Giuseppe di diventare egiziano, che considereremo pi&ugrave; avanti.</p>
<p><i>Come poi Giuseppe rispose al faraone? (Gen 41:16)</i></p>
<p>Attribu&igrave; l'abilit&agrave; di interpretare sogni al suo Dio. Era implicito un confronto con gli d&egrave;i egizi, che non potevano aiutare i maghi e saggi ad interpretare i sogni. Fa ricordare il confronto fra Mos&egrave; e i maghi di Egitto, che potevano riprodurre i primi segni e piaghe, ma non le zanzare, quando dichiararono al Faraone, "Questo &egrave; il dito di Dio" (Es 8:18-19). Infatti, uno scopo delle piaghe era di insegnare al faraone (che si considerava un dio) che c'era solo uno vero Dio.</p>
<p><i>Dopo che faraone raccont&ograve; i sogni a Giuseppe, ribadendo che nessuno sapeva spiegarli (Gen 41:17-24), come rispose Giuseppe? (Gen 41:25-32)</i></p>
<p>Per Giuseppe, la ripetizione dei sogni voleva dire che era sicuro, che Dio aveva deciso sette anni di abbondanza e poi sette anni di carestia che avrebbero consumato il paese, e che sarebbe successo presto. Infatti, non era una decisione recente, ma Dio da anni aveva preparato per questa carestia, mandando Giuseppe in Egitto per conservare il suo popolo durante la carestia (Gen 45:5-8).</p>
<p>In realt&agrave;, Dio non rivel&ograve; il suo decreto a faraone, rivel&ograve; piuttosto il suo decreto (la spiegazione del sogno) a Giuseppe. Il sogno a faraone era un mezzo per portare Giuseppe dal faraone affinch&eacute; le sue capacit&agrave; fossero riconosciute da lui.</p>

<p><i>Quello che Giuseppe aveva imparato gestendo la casa di Potifar e la prigione venne fuori nel suo piano per contrastare la carestia. Proposi anche la nomina di una persona per sorvegliare tutto (Gen 45:33-36). Non era chiaro se fosse un modo per proporre s&eacute; stesso o se Giuseppe almeno sperava in qualche liberazione, ma come risposero faraone e i suoi servi? (Gen 41:37-39)</i></p>
<p>Giuseppe aveva suggerito un uomo intelligente e saggio; il faraone cap&igrave; che Giuseppe era cos&igrave;, dall'interpretazione e dal piano proposto. Pi&ugrave; dei saggi del regno. Inoltre, in lui c'era lo Spirito di Dio: se questo Dio aveva fatto conoscere a Giuseppe tutto questo, avrebbe potuto rivelare altre cose per la gestione della carestia nel futuro.</p>
<p>Faraone poi diede a Giuseppe il potere quasi completo sul paese, secondo solo al faraone stesso (Gen 41:40-44). La sua esperienza gestendo la casa di Potifar e la prigione senza dubbio aiutava: aveva imparato nelle cose piccole, cos&igrave; gli poteva affidato un compito grande. Pi&ugrave; importante, aveva imparato la fiducia in Dio e quindi la via dell'integrit&agrave; durante gli anni difficili: siccome Dio era rimasto con lui in quei 17 anni, sarebbe stato con lui anche in questi 14 anni. &Egrave; facile immagine un altro nella posizione di Giuseppe che avrebbe usato questo potete per arricchirsi. Non Giuseppe, era integro nelle scelte che fece. Forse in questo &egrave; la risposta perch&eacute; Dio mise 17 anni per mettere Giuseppe nella corte di faraone: il Giuseppe diciasettenne di Gen 37, se fosse ingenuo o se fosse arrogante, non aveva la fede provata per poter svolgere questo compito in modo integro. I 17 anni di difficolt&agrave; hanno preparato la sua anima mentre Dio preparava gli eventi che lo portarono al faraone.</p>
<p>Ci sono molti paralleli fra questo capitolo &egrave; il racconto di Daniele che interpreta il sogno del re in Dan 2. Dall'altra parte, Mos&egrave; visse un'esperienza inversa: inizi&ograve; nella coorte del faraone, ma pian piano si identific&ograve; sempre di pi&ugrave; con gli Israeliti affinch&eacute; li potesse portare fuori dall'Egitto prima di rivelarsi pi&ugrave; potente dei maghi d'Egitto (anzi, il suo Dio era pi&ugrave; potente).</p>
<p><i>In quali modi Giuseppe venne parzialmente trasformato in un egiziano? (Gen 41:43-46,50-52)</i></p>
<p>Faraone fece s&igrave; che tutti sapessero che aveva autorit&agrave; su Egitto. Inoltre, gli diede un nome egiziano e una moglie egiziana, che era figlia di un sacerdote. Giuseppe entr&ograve; in pieno titolo nella societ&agrave; egiziana.</p>
<p>I figli, per&ograve;, avevano nomi ebraici, anche se il significato dei nomi indicava un certo allontanamento dalle sue radici: Dio gli aveva fatto dimenticare la sua famiglia ma lo aveva reso fecondo nel suo paese (che era un paese di afflizione, come schiavo e prigioniero, pur non essendolo pi&ugrave;).</p>
<p>Alcuni hanno avuto problemi con questo processo in cui Giuseppe diventava sempre pi&ugrave; egiziano. Per esempio, c'&egrave; una legenda chiamata Giuseppe e Asenat, scritta a qualche punto fra il 100 a.C. e il 200 d.C., in cui Asenat si convert&igrave; dagli idoli egizi al Dio d'Israele prima di sposare Giuseppe. In ogni caso, da quello che abbiamo visto di Giuseppe finora, probabilmente mantenne la sua integrit&agrave; e la sua fiducia in Yahweh anche se aveva l'aspetto di un egiziano. E per l'Autore, &egrave; chiaro che &egrave; interamente l'opera di Dio e che gli d&egrave;i dell'Egitto non avevano niente a che fare con quello che &egrave; successo.</p>
<p>Infine, gli eventi si svolsero proprio come Dio aveva rivelato a Giuseppe: setti anni di abbondanza in cui Giuseppe accumul&ograve; tanto grano, poi sette anni di carestia in cui Giuseppe vendette il grano agli egiziani e agli stranieri che venivano per comprarlo (Gen 41:47-49,53-57). Dopo i primi due di quegli anni di carestia, vennero anche i fratelli di Giuseppe, che verr&agrave; raccontato nel prossimo capitolo.</p>
<p>Gli ultimi versetti devono essere considerati il modo in cui Dio benedisse tutte le nazioni attraverso Giuseppe., similmente alla benedizione dalla parte del Signore della casa di Potifar "per amore di Giuseppe" (Gen 39:5). Questo &egrave; un adempimento parziale della promessa ad Abraamo che in lui "saranno benedette tutte le famiglie della terra" (Gen 12:3). Ma &egrave; solo parziale, e cos&igrave; &egrave; un segno dell'adempimento totale che si trova in Ges&ugrave; Cristo, attraverso cui Dio benedice tutte le nazioni.</p>
<p>Noi similmente dobbiamo sopportare i periodi difficile con una fiducia nel proposito di Dio. Dobbiamo avere pazienza, perch&eacute; i tempi di Dio sono diversi dai nostri. Dobbiamo essere fedeli e ubbidienti ancora quando Dio sembra distante o non capiamo quello che sta facendo. Dobbiamo credere che Dio opera le nostre circostanze per la sua gloria, e il suo proposito di benedire tutte le nazioni, e che ci promette la corona della vita (Giac 1:12).</p>

<?
$n=4;
require("indice.php");
require("../../piede.php");
?>
