<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Abraamo e Lot si separano (Gen 13)";
$key = "lot,Genesi 13,abraamo,genesi,riflessioni";
$titolo = "Abraamo e Lot si separano (Gen 13)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Abraamo e Lot si separano (Gen 13)</h1>
<h2>Scopo</h2>
<p>Riflettere sulla nostra vita per fede e per visione, le scelte che facciamo secondo quello che vediamo, e come possiamo usare i nostri beni per scopi spirituali piuttosto di essere dominati da essi.</p>
<h2>Appunti</h2>
<p>Questo capitolo segue lo schema di molti dei racconti nella storia di Abraamo: Abraamo mette in pericolo le promesse o c'&egrave; un avvenimento che mette in pericolo il modo in cui Abraamo pensava di adempire le promesse, e poi Dio frusta i tentativi di Abraamo o riafferma che le promesse saranno adempiute nel modo suo non quello di Abraamo. Per esempio, nello studio precedente Abraamo ha lasciato la terra promessa e ha permesso che Sara avesse figli da un altro uomo. In questo studio, Abraamo pensava che Lot sarebbe stato il suo erede, e cos&igrave; il 'figlio promesso'. Ma questa possibilit&agrave; viene rimossa.</p>

<p>Abraamo &egrave; ritornato a dove era prima del disastro di Egitto (Gen 12:8; 13:1-4). &Egrave; ritornato con Lot, che era il nipote di Abraamo. Siccome era orfano e Abraamo era senza figli (Gen 11:27-31), sembra che Abraamo l'avesse adottato come erede. Sicuramente l'ha portato con s&eacute; quando Dio gli ha detto di partire (Gen 12:4-5). Questo era probabilmente il primo errore, perch&eacute; Dio gli aveva detto, "Va' via dal tuo paese, dai tuoi parenti e dalla casa di tuo padre" (Gen 12:1). Eppure, Abraamo non ha lasciato i parenti e la casa di suo padre, portando con s&eacute; un parente. Forse questo &egrave; il senso di Gen 12:4: "Abramo part&igrave;, come il Signore gli aveva detto, e Lot and&ograve; con lui (che non era come il Signore gli aveva detto)". Abraamo poteva ragionare che Lot non era pi&ugrave; parente ma famiglia, come Sara, in quanto figlio adottato ed erede. Ma non era il ragionamento di Dio, che voleva una separazione netta dalla famiglia, e di fare di Abraamo una grande nazione nel modo suo, che dipendeva solo da lui e non dallo sforzo umano (vedi Rom 9:7-16). La decisione di portare Lot con s&eacute; ha creato tante difficolt&agrave; per Abraamo, non solo in questo capitolo ma anche nei seguenti.</p>

<p>Anche se Dio non agisce esplicitamente nella prima parte del capitolo, possiamo vedere la sua sovranit&agrave; o provvidenza quando crea le circostanze o usa la situazione per adempiere i suoi propositi, di allontanare Lot da Abraamo affinch&eacute; la promessa sia adempiuta in modo suo. Non solo Lot &egrave; allontanato, che dal punto di vista di Abraamo era un passo indietro per diventare il padre di una grande nazione, ma Lot ha preso la terra che appariva la migliore. "Appariva", perch&eacute; &egrave; meglio stare non nella terra pi&ugrave; fertile, ma nella terra dove si viene benedetti - che era nella terra montuosa di Canaan ad ovest del fiume Giordano, non nella fertile pianura di Sodoma e Gomorra all'oriente del Giordano. Vedremo che Sodoma non era il posto per ricevere la benedizione di Dio, e le conseguenze negative per Israele di questa scelta di Lot, nel capitolo 19, anche se c'&egrave; gi&agrave; un indizio dello sbaglio di Lot in Gen 13:13. Questo &egrave; un chiaro esempio di camminare per visione e non per fede 2Cor 5:7. [Ci sono molte parole in comune fra Gen 13:10-11, e Gen 3:6; 6:2, e il desiderio di ritornare in Egitto prefigura quello degli Israeliti dopo l'Esodo Es 16:3; 11:5; 14:2.]</p>

<p>La risposta esplicita da parte di Dio ai piani infranti di Abraamo era un rinnovo della promessa. Gen 13:14-15,17 ripete Gen 12:7, con l'aggiunta di "per sempre". Gen 13:16 &egrave; pi&ugrave; specifico di Gen 12:2: non solo Dio far&agrave; di Abraamo una grande nazione, ma anche la sua discendenza sar&agrave; molto numerosa. Poi Abraamo ha costruito un altro altare per ricordarsi della promessa Gen 13:18.</p>

<p>La differenza fra Abraamo e Lot era che, anche se tutti e due avevano i propri progetti, Abraamo &egrave; rimasto dentro la promessa, e quindi la benedizione, di Dio - anche se &egrave; stato costretto da Dio ad abbandonare il suo piano e ritornare a quello (in parte sconosciuto) di Dio. Lot &egrave; andato verso la rovina, e i suoi progetti erano andati in fumo.</p>

<p>Anche per noi la nostra fede e ubbidienza non sono sempre perfette. Spesso siamo attaccati al vecchio modo di pensare, al nostro piano per la nostra vita, invece di seguire il piano che Dio ha per noi - anche se non sappiamo esattamente tutti i dettagli del piano di Dio. Ma di solito sappiamo abbastanza per prendere le decisioni giuste. Il problema &egrave; piuttosto che spesso preferiamo la nostra strada, preferiamo la fertilit&agrave; che vediamo che le montagne della promessa (cio&egrave; la via della croce, di rinnegare s&eacute; stesso). Lot (e spesso noi) avrebbe scelto il Paradiso piuttosto che l'Inferno, ma non il Paradiso piuttosto che la terra. Camminare per fede non significa vivere in un mondo di fantasia, n&eacute; nelle cose false, ma fare le scelte migliori anche se non sono le migliori secondo quello che vediamo.</p>

<p>Lot ha alzato gli occhi e ha visto una terra fertile (Gen 13:10). Abraamo ha alzato gli occhi e ha visto una terra promessa (Gen 13:14-15). Noi dobbiamo vedere Ges&ugrave; (Ebr 2:9; anche Ebr 12:2-3) che per visione ha sofferto ed &egrave; morto, ma per fede vediamo la sua gloria e onore.</p>

<p>Abraamo &egrave; ritornato dall'Egitto benedetto da Dio materialmente (Gen 12:16; 13:2). Ma dopo la tentazione della carestia, arriva la tentazione del benessere e della ricchezza. Infatti, questa &egrave; la prima volta che la ricchezza &egrave; menzionata nella Bibbia. La differenza fra Abraamo e Lot era che Abraamo aveva molti possessi, ma Lot aveva molte cose che possedevano lui. Non poteva togliere gli occhi dalla possibilit&agrave; di aumentare ancora la sua ricchezza, costi quello che costi per la sua vita spirituale. &Egrave; una buona opportunit&agrave; riflettere sul nostro rapporto con i tanti beni che abbiamo (che possediamo o che ci possiedono). Il nostro lavoro, la nostra casa, i nostri beni, la citt&agrave; dove viviamo, la persona che sposiamo, il lavoro che vorremmo per i nostri figli, sono buoni per la nostra vita spirituale e quella della famiglia e quella degli altri, o un impedimento? &Egrave; vero che a volte Ges&ugrave; ci chiama a vivere con i peccatori (Mt 9:10-13), ma Lot &egrave; andato a vivere con i peccatori non per salvarli ma per essere come loro. Come possiamo usare il lavoro e i beni per scopi spirituali, invece di essere dominati da loro? Abraamo invece non era molto attaccato ai suoi possessi. Ha lasciato a Lot decidere dove andare, anche se aveva il diritto di scegliere prima. Aveva imparato che Dio avrebbe provveduto (quello che non sapeva quando &egrave; andato in Egitto a causa della carestia). Se Lot avesse scelto la terra fertile, Dio avrebbe dato a Abraamo quello che aveva promesso. Se Lot avesse scelto la terra promessa, Dio avrebbe fatto in modo a restituirla ad Abraamo. (Questo era il ragionamento di Abraamo quando Dio gli ha comandamento di sacrificare il figlio della promessa, Isacco Ebr 11:19.) In altre parole, Abraamo ha lasciato che Dio scegliesse per lui. Dio avrebbe preso cura di Abraamo, per cui non doveva preoccuparsi di essere troppo generoso n&eacute; dei suoi diritti. E neanche noi 1Cor 9:14-18; Fili 2:4-11. Se abbiamo fede in quello che Dio ha promesso (come Abraamo) che Dio provveder&agrave; a ogni nostro bisogno (Fili 4:19), possiamo accettare di ricevere meno di quello che desideriamo (ma mai meno del nostro bisogno secondo Dio) - non la migliore, ma la seconda o addirittura la peggiore macchina, tecnologia, vestito, casa, citt&agrave; in cui vivere, ecc - e cos&igrave; avremo pi&ugrave; soldi per essere pi&ugrave; generosi. Quando Dio &egrave; al primo posto nella tua vita, non importa se tu sia secondo o ultimo Mt 6:33.</p>

<p>Per riassumere: Abraamo &egrave; vissuto per fede, era generoso, cercava la citt&agrave; di Dio, ha ereditato il mondo; Lot &egrave; vissuto per visione, era avaro e mondano, ha preso casa in una citt&agrave; fatta dall'uomo e distrutta da Dio, ha perso tutti i beni e doveva vivere in una caverna.</p>

<?
$n=5;
require("indice.php");
require("../../piede.php");
?>
