<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Abraamo intercede (Gen 18:1-8,16-33)";
$key = "intercede,pregare,Genesi 18,abraamo,genesi,riflessioni";
$titolo = "Abraamo intercede (Gen 18:1-8,16-33)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Abraamo intercede (Gen 18:1-8,16-33)</h1>
<h2>Scopo</h2>
<p>Pregare meglio, lottando per conoscere meglio la giustizia e la misericordia di Dio.
</p>
<h2>Appunti</h2>
<p>Questo &egrave; un racconto corto e semplice, ma con molti spunti per riflettere sul rapporto di Abraamo con Dio, e cos&igrave; anche sul nostro.</p>

<p>La prima domanda &egrave; chi sono questi tre uomini. Ci sono diverse spiegazioni: le tre persone della Trinit&agrave; (perch&eacute; Yahweh apparve ad Abraamo Gen 18:1), Dio e due angeli (Gen 18:22; 19:1), o tre angeli. A me sembra che la seconda possibilit&agrave; sia pi&ugrave; probabile, ma dovrai essere pronto a rispondere a questa domanda con la interpretazione che tu ritieni giusta, e perch&eacute;.</p>

<p>Nella prima parte dell'incontro, vediamo l'ospitalit&agrave; di Abraamo, a cui Ebr 13:2 probabilmente si riferisce. Almeno in parte sembra comunque l'ospitalit&agrave; tipica di quella cultura, per cui non &egrave; un insegnamento principale del brano. Invece l'umilt&agrave; di Abraamo davanti ai tre (per esempio 18:8), che probabilmente Abraamo ha riconosciuto, sembra pi&ugrave; importante.</p>

<p>Una conseguenza di essere il portatore, il messaggio e il canale dei propositi e delle promesse di Dio (Gen 18:18-19) &egrave; che Dio confida ad Abraamo anche altri suoi piani (Gen 18:17). Infatti, Abraamo &egrave; chiamato l'amico di Dio (Is 41:8; 2Cr 20:7 (nella Nuova Diodati e nella CEI; altre versioni dicono 'solo' che Abraamo am&ograve; Dio); Giac 2:23). Dobbiamo stare attenti a trasferire questo insegnamento a noi. Certo, Dio rivela pi&ugrave; ai credenti che ad altri (per esempio Mt 11:25; Gv 15:15), ma non ci rivela tutto quello che far&agrave; nella nostra vita, perch&eacute; non soddisfacciamo i criteri di Gen 18:18-19. Infatti, Abraamo &egrave; l'<b>unica</b> persona chiamata amico di Dio nella Bibbia. Invece &egrave; Ges&ugrave; che &egrave; veramente l'amico del Padre come Abraamo, e il Padre non gli nasconde niente. Pi&ugrave; che persone che salvano altri tramite le nostre preghiere, siamo prima di tutto i peccatori (come quelli di Sodoma) che Ges&ugrave; salva tramite le sue preghiere. Ma in modo limitato Dio ci rivela di pi&ugrave; che agli altri.</p>

<p>La parte pi&ugrave; interessante del brano &egrave; probabilmente la 'trattativa' fra Abraamo e il Signore. Prima di tutto, vediamo quello che il brano ci insegna di Dio. Bisogna notare che Abraamo non ha costretto Dio a cambiare idea. Le citt&agrave; sono state distrutte comunque (Gen 19), e il giusto non &egrave; perito insieme con l'empio (Gen 18:23), perch&eacute; un massimo di 4 persone giuste sono state trovate, e Dio li ha aiutati a scappare prima della distruzione. Probabilmente costringere Dio a cambiare idea non era l'intento di Abraamo; invece, cercava di capire come era possibile che Dio avrebbe distrutto le citt&agrave;. Abraamo chiama in causa la giustizia e la misericordia di Dio, come &egrave; giusto. Il problema &egrave; che spesso questi attributi di Dio richiedono azioni contrarie. O punisce il male o perdona il male. In questo caso, per Abraamo c'erano due possibilit&agrave;: o distruggere la citt&agrave; e l'innocente soffre, o risparmiare la citt&agrave; e il colpevole rimane impunito. In realt&agrave;, in Gen 19 Dio ha un'altra soluzione: punire la citt&agrave; e risparmiare i giusti, facendoli scappare. Per&ograve;, Soar &egrave; risparmiata per aiutare Lot (Gen 19:17-22), e quindi &egrave; anche vero che a volte Dio "perdona tutto il luogo (incluse gli ingiusti) per amore dei giusti" (Gen 18:26). Ma non sempre, come a Sodoma. Quello che impariamo (e che Abraamo doveva imparare per praticare la giustizia Gen 18:19) &egrave; che Dio &egrave; giusto e misericordioso, ma la giustizia e la misericordia di Dio sono inscrutabili (Rom 11:33), non sempre quello che ci aspetteremo. La misericordia deve essere inaspettata, altrimenti non &egrave; misericordia, e la giustizia non si rivela sempre come ci aspetteremo, come Giobbe ha imparato. E che noi dobbiamo imparare, quando subiamo l'ingiustizia, quando vediamo il male fiorire non punito, o il male ricevere la misericordia di Dio. Dio sente il grido dei maltrattati (Gen 18:20), e risponder&agrave; a suo tempo nel suo modo. Ricordiamoci anche che noi siamo spesso fra gli ingiusti (non ci sono 10 giusti neanche in tutta la terra Rom 3:10), e Ges&ugrave;, la discendenza di Abraamo, ha fatto quello che Abraamo non ha potuto fare, prendendo la giustizia punitiva su di s&eacute; per fare misericordia anche agli ingiusti, e cos&igrave; benedire tutte le nazioni.</p>

<p>In ogni caso, se ci fossero 10 giusti, Dio non avrebbe distrutto la citt&agrave;, per amor dei giusti. Certo, li avrebbe potuti aiutare scappare come Lot, ma con 10 giusti non avrebbe voluto distruggere anche le loro case, i loro amici, ecc. La presenza del bene in una citt&agrave; pu&ograve; portare la grazia di Dio all'intera citt&agrave; - non &egrave; la presenza del male che determina la fine della grazia e della pazienza di Dio, ma l'assenza del bene. Anche se &egrave; poco - non dobbiamo misurare l'impatto con i numeri, ma con gli occhi di Dio. Nella vita della citt&agrave;, gli eventuali 10 giusti non avrebbero potuto cambiare la cultura delle migliaia di sodomiti, ma avrebbero salvato la citt&agrave; dalla distruzione. Ci sono altri esempi in Gen 30:27; 39:5; Ger 5:1; At 27:24. Sarebbe opportuna una riflessione sul nostro ruolo nella nostra citt&agrave;.</p> 

<p>Perch&eacute; Abraamo ha pregato in questo modo? Diversi motivi: compassione per quelli di Sodoma (o forse solo per Lot), franchezza e tenacit&agrave; e libert&agrave; nella preghiera, umilt&agrave;, intimit&agrave; con Dio.<br />
a) <b>compassione:</b> in Es 32:11-14; Am 7:1-6 c'&egrave; intercessione per Israele, ma solo qui intercessione per pagani malvagi. In questo vediamo il suo ruolo di benedizione per le nazioni. La sua compassione &egrave; diversa dal comportamento di molti credenti verso gli omosessuali oggi. Forse noi potremo pensare di come mostrare la stessa compassione verso politici, mafiosi, o altre classi disprezzate, invece di condannarli o desiderare che Dio li condanni.<br />
b) <b>franchezza, tenacit&agrave;, libert&agrave;</b> (Lu 18:1-8; Ebr 4:16): a volte troppo facilmente aggiungiamo alle nostre preghiera la frase "se &egrave; la tua volont&agrave;" quando dobbiamo lottare per capire meglio cosa sia la volont&agrave; di Dio<br />
c) <b>umilt&agrave;:</b> Abraamo era franco, ma non troppo. Presentava le sue richieste, forse anche le sue perplessit&agrave;, ma sapeva che Dio era Dio e Abraamo non lo era (Gen 18:27,30,32).<br />
d) <b>intimit&agrave;:</b> la franchezza e libert&agrave; di parlare cos&igrave; erano possibili a causa del rapporto intimo con Dio, e l'umilt&agrave; una conseguenza di conoscere la grandezza di Dio. Abraamo conosceva Dio, sapeva che era giusto, che non avrebbe fatto morire il giusto con l'empio (Gen 18:25), e cos&igrave; era fiducioso di poter pregare come ha fatto. C'era perplessit&agrave; su come Dio avrebbe realizzato questa giustizia, ma Abraamo voleva conoscere Dio e le sue vie sempre di pi&ugrave; - la preghiera ha iniziato come intercessione, ma &egrave; conclusa con un rapporto pi&ugrave; intimo con Dio. Dio ha invitato Abraamo a partecipare ai suoi piani, e ha accolto la risposta di Abraamo con la sua perplessit&agrave;, anche obiezioni. Dio ascolta i nostri sentimenti, paure, dubbi su Dio, quando presentati con umilt&agrave;. Non ci d&agrave; sempre una spiegazione dettagliata, ma ci rassicura rivelandosi come un Dio che sa, che prende cura, che &egrave; giusto, e in controllo.
</p>

<?
$n=10;
require("indice.php");
require("../../piede.php");
?>
