<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Il sacrificio di Isacco (Gen 22)";
$key = "isacco,sacrificio,Genesi 22,abraamo,genesi,riflessioni";
$titolo = "Il sacrificio di Isacco (Gen 22)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Il sacrificio di Isacco (Gen 22)</h1>
<h2>Scopo</h2>
<p>Capire come rispondere nelle prove, ricordandosi della provvisione di Dio futura in base a quella passata, e accogliere per fede il sacrificio provveduto per i momenti quando non abbiamo fede.
</p>
<h2>Appunti</h2>
<p>Dio non tenta le persone per cercare di farle cadere, ma prova le persone per rivelare e migliorare la loro fede (1P 1:6-7; Giac 1:2-4). Vedi la <a href="/brani/brani.php?r=Genesi%2022">spiegazione di Gen 20</a> e di <a href="/brani/brani.php?r=Giacomo%201:13">Giacomo 1:13</a> per un approfondimento della questione. Cosa significa per noi? Non credo che sia normale che Dio ci chiede di fare qualcosa di sbagliato e poi ci ferma all'ultimo momento. Ma Dio pu&ograve; chiederci di fare cose "impossibili", che sono troppo difficili per noi, per far vedere se dipendiamo da lui oppure dalle nostre capacit&agrave;. Per esempio, per servire Dio meglio, un cambio di citt&agrave; o di lavoro (magari anche con uno stipendio pi&ugrave; basso), un ministero nella chiesa o fuori che non sappiamo fare, una persona da aiutare che ci sta antipatica. Oppure, Dio ci toglie qualcosa su cui dipendevamo per stare bene, affinch&eacute; impariamo e mostriamo di trovare la nostra gioia solo in Dio che ci d&agrave; ogni cosa - la prova di Abraamo era se amava il dono pi&ugrave; del donatore del dono. Queste sono le cose a cui si riferiscono le persone di solito quando dicono che stanno sperimentando una prova - una malattia di s&eacute; stesse o di parenti, disoccupazione, eccetera. In questi casi la prova &egrave; per far crescere la fede esercitandola in una situazione in cui non poteva essere esercitata prima, perch&eacute; altri oggetti della 'fede' sono tolti (come la salute, la famiglia, il lavoro). Ameremmo Dio se togliesse la casa, i tre pasti ogni giorno, anche il nostro unico e amato figlio? Si pu&ograve; chiedere al gruppo le prove che hanno subito (di tutti e due i tipi), e come la fede &egrave; stata rivelata oppure &egrave; cresciuta come conseguenza. Alternativamente, si pu&ograve; iniziare discutendo di quello che le persone vogliono dire quando dicono di essere provate, e poi fare il confronto con la prova di Abraamo.

<p>In realt&agrave;, la prova di Abraamo era ancora pi&ugrave; forte. Dio non ha tolto Isacco ad Abraamo, ha chiesto ad Abraamo di rinunciare ad Isacco, di dargli via. Molto pi&ugrave; difficile. Adoniram Judson, un missionario che ha fondato la chiesa in Birmania/Myanmar, ha scritto ai genitori della sua fidanzata per chiedere di sposarla:</p>
<blockquote>Chiedo se acconsentiate di separarvi da tua figlia, di non vederla mai pi&ugrave; in questo mondo; se acconsentiate alla sua partenza per un paese pagano, dove sar&agrave; soggetta alle sofferenze di una vita missionaria; se acconsentiate alla sua esposizione ai pericoli del mare, all'influenza fatale del clima, agli insulti, alla persecuzione, e forse ad una morte violenta. Potete acconsentire a tutto questo per il bene di colui che ha lasciato la sua dimora celeste, ed &egrave; morto per lei e per voi, per il bene delle anime che stanno perendo, per la gloria di Dio? Potete acconsentire nella speranza di incontrare presto vostra figlia nel mondo della gloria, con una corona di giustizia, illuminata dalle acclamazioni di lode al suo Salvatore dai pagani salvati, tramite lei, dalla punizione eterna?</blockquote>
<p>Cosa faremmo se ricevessimo una lettera del genere? In realt&agrave;, non lo sappiamo, per questo abbiamo bisogno di essere provati.</p>

<p>Questo insegnamento &egrave; approfondito in due brani del Nuovo Testamento. Prima di tutto, in Ebr 11:17-19 vediamo quale aspetto della fede di Abraamo fu rivelato: credeva (anzi, era persuaso) che Dio &egrave; molto potente. &Egrave; inteso che era convinto anche che Dio manteneva la sua promessa, e la fede si basa sulle promesse e l'ubbidienza ai comandi senza chiedere spiegazioni. Ma secondo Ebr 11:17-19 sembra che abbia fatto il seguente ragionamento:<br />
<i>Premessa:</i> Dio ha detto che avr&ograve; una discendenza attraverso Isacco.<br />
<i>Premessa:</i> Dio mantiene sempre le sue promesse.<br />
<i>Premessa:</i> Dio vuole che io uccida Isacco.<br />
<i>Conclusione:</i> Dio risusciter&agrave; Isacco, per poter adempiere la sua promessa. (Forse l'aveva gi&agrave; dedotto durante il viaggio - ha detto "torneremo [plurale] da voi" Gen 22:5; forse anche Gv 8:56 si riferisce a questa convinzione.)</p>
<p>La conclusione era sbagliata, ma le prime due premesse erano giuste! Cos&igrave; Abraamo ha potuto mostrare quanto grande era la sua fede - ha potuto credere in un Dio potente, ma non ha avuto l'opportunit&agrave; prima di credere in un Dio cos&igrave; potente da risuscitare le persone. Purtroppo, molti fanno il ragionamento: Dio ha promesso cosa X (salute, benessere, lavoro, un marito), e Dio mantiene le sue promesse; ma quando non ricevono X mettono in dubbio la seconda premessa (la fedelt&agrave; di Dio) invece della prima (l'ha veramente promesso?). Anche quando Dio l'ha promesso (come nel caso di questo capitolo), dobbiamo fidarci di Dio che ha una soluzione anche se non sappiamo cosa sia.</p>

<p>Il secondo brano &egrave; Giac 2:20-24. Avendo letto tutta la storia di Abraamo, possiamo capire meglio questo brano di Giacomo. Abraamo fu giustificato (nel senso teologico, contato come se fosse giusto) in Giac 2:23 = Gen 15. Pi&ugrave; di 20 anni dopo, Abraamo fu giustificato (nel senso comune della giustificazione dell'assenza dalla scuola - diamo un motivo per cui il figlio che era assente era nel giusto e non marinava) in Giac 2:21 = Gen 22. &Egrave; come se Dio scrivesse una giustificazione per Abraamo, "Volete vedere che Abraamo ha fede? Ecco la sua ubbidienza". La fede agisce con le opere, e le opere completano la fede (Giac 2:22; = Gal 5:6 Paolo e Giacomo sono d'accordo), perch&eacute; una fede senza opere &egrave; senso valore o morta (Giac 2:20,26; questa &egrave; la differenza fra Paolo e Giacomo - quello che Giacomo chiama 'fede morta' Paolo chiama 'non fede', ma &egrave; una differenza di terminologia non di teologia). Vedi anche la <a href="/brani/brani.php?r=Giacomo%202">spiegazione di Giacomo 2</a>.</p>

<p>Un altro tema importante del brano &egrave; che Dio provvede (Gen 22:8,14). In Gen 22:14, Iav&egrave;-Ir&egrave; &egrave; di solito conosciuto come Jehovah Jireh, (come &egrave; tradotto nella Nuova Diodati e nella Riveduta/Luzzi) che vuol dire 'Dio provvede'. Questa convinzione permette a Dio di essere Dio. Abraamo non sa rispondere alla domanda di Isacco in Gen 22:7, ma con fiducia dice che ci penser&agrave; Dio. Calvino ha commentato, "Questo esempio &egrave; da imitare. In tali difficolt&agrave;, l'unico rimedio &egrave; lasciare l'evento a Dio, affinch&eacute; lui possa aprire una via per noi quando non ce n'&egrave; una. Gli diamo il pi&ugrave; alto onore quando, nella perplessit&agrave;, cediamo internamente alla sua provvidenza". Nella prova, Dio provvede; la fede e la prova ci mettono in posizioni dove possiamo osservare l'incredibile capacit&agrave; di Dio di provvedere tempestivamente. La provvisione di Dio a Moria &egrave; diventata un proverbio (Gen 22:14) - si guardava indietro a come Dio ha provveduto, ma si ricorda che Dio provveder&agrave; anche adesso. Anche noi dobbiamo costruire delle pietre miliari, dove Dio ha provveduto nel passato e di cui possiamo ricordarci, per avere questa fiducia per il futuro. Il gruppo ha degli esempi? Hudson Taylor, un missionario pionieristico in Cina, che non ha mai chiesto soldi per il sostegno, aveva due targhe nella sua casa: 'Eben-ezer' ('fin qui il Signore ci ha soccorsi' 1Sam 7:12) e 'Jehovah-Jireh': sia che guardava indietro sia che guardava avanti sapeva che c'era Dio, e non doveva preoccuparsi.</p>

<p>L'ubbidienza di Abraamo &egrave; stata ricompensata in alcuni modi. Dio gli parla di nuovo, e non solo ripete le benedizioni di Gen 12 e altre volte, ma lo fa con giuramento (Gen 22:16; vedi anche Ebr 6:13 18). Questo giuramento, pi&ugrave; che la promessa iniziale, era la sicurezza per Israele dopo, per esempio Es 6:8; Num 32:11; Dt 1:8; Mic 7:20. L'altra ricompensa &egrave; quello che gli hanno detto alcune persone: Naor, il fratello di Abraamo (Gen 11:27,29) aveva avuto tanti figli. Cos&igrave; sarebbe stato possibile continuare la discendenza trovando una moglie per Isacco fra i suoi parenti. E infatti cos&igrave; &egrave; successo, Isacco ha sposato il suo cugino di secondo grado Rebecca (Gen 22:23; Gen 24). Dio provvede!</p>

<p>Ci sono anche connessioni tipologiche con il resto della Bibbia. Il monte di Moria (Gen 22:2) era appena fuori la citt&agrave; Gerusalemme di allora, ed &egrave; stato scelto come il luogo del tempio (2Cr 3:1), dove si facevano i sacrifici. Vicino al monte, un altro "figlio, unico, amato" (Gen 22:2; Ebr 11:17; Mt 3:17; Gv 3:16; Rom 8:32 con Gen 22:12,16 dove nel greco lo stesso verbo &egrave; usato per risparmiare/rifiutare) &egrave; stato sacrificato, volentieri senza opporsi (Is 53:7). [I Padri dalla fine del secondo secolo (Ireneo, Tertulliano) paragonava la legna che Isacco ha portato (Gen 22:6) con la croce che Ges&ugrave; ha portato, ma secondo me &egrave; troppo!] Ma mentre Dio ha fermato Abraamo, non ha fermato s&eacute; stesso - ma il Padre ha riavuto il Figlio per risurrezione (Ebr 11:19). Ges&ugrave; &egrave; simile non solo al figlio, ma anche all'animale sacrificato (Gv 1:29; Ap 5:6,9-10; 13:8) che sostituisce le persone (Isacco in Genesi, noi nel NT). Quello che Dio non ha permesso ad Abraamo di fare, il Padre ha fatto per noi. Veramente al monte del Signore &egrave; stato provveduto (Gen 22:8,14) il sacrificio di cui abbiamo bisogno! &Egrave; importante capire questo, perch&eacute; parlando della fede, dell'ubbidienza e della risposta alla prova da parte di Abraamo, abbiamo creato degli standard molto alti. Quando siamo provati, falliamo. Nessuno di noi ha sempre fede in Dio per tutto. Anche nelle nostre vittorie di fede, non cancelliamo i fallimenti del passato, come Gen 22 non cancella i capitoli Gen 12 e Gen 20 per Abraamo. Ma Dio provvede il sacrificio che cancella le nostre mancanze, e la fede nella promessa che quel sacrificio canceller&agrave; tutto viene contato a noi come giustizia.
</p>

<?
$n=13;
require("indice.php");
require("../../piede.php");
?>
