<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "La nascita di Ismaele (Gen 16)";
$key = "ismaele,nascita,Genesi 15,abraamo,genesi,riflessioni";
$titolo = "La nascita di Ismaele (Gen 16)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>La nascita di Ismaele (Gen 16)</h1>
<h2>Scopo</h2>
<p>Riflettere sulla necessit&agrave; della pazienza nel credere nelle promesse di Dio, e quando cerchiamo di fare cose a modo nostro invece di aspettare Dio.
</p>
<h2>Appunti</h2>
<p>Una delle promesse di Dio ad Abraamo era che avrebbe avuto una grande discendenza. Una grande discendenza?! Ma come? Abraamo era vecchio, Sara era sterile: addirittura uno figlio era impensabile, figuriamoci una grande discendenza. La prima idea di Abraamo era di portare Lot con lui, che sarebbe stato il suo erede. Questa possibilit&agrave; &egrave; stata eliminata dalla scelta di Lot di non rimanere nella sfera delle benedizioni divine. Poi l'erede di Abraamo era un suo servo. Ma Dio ha detto che il servo non sarebbe stato l'erede; invece, sarebbe stato un figlio di Abraamo (Gen 15:4). In questo studio, vediamo la terza idea di Abraamo, la soluzione al problema di lui e Sara.</p>

<p>Il ragionamento era molto logico e comprensibile. Dio ha fatto la promessa, e 10 anni sono passati (Gen 12:4; 16:3,16) senza che lui avesse fatto qualcosa. Se Dio non ha fatto qualcosa, probabilmente vuole che noi troviamo la soluzione. Siccome Dio ha detto che l'erede sarebbe il figlio di Abraamo, ma non ha detto che sarebbe il figlio di Sara (Gen 15:4), la soluzione sembra essere che Abraamo doveva avere un figlio con una serva di Sara, che secondo i costumi della cultura (per esempio Gen 30:1-7) sarebbe contata come se fosse la figlia di Sara (Gen 16:2). Come sempre, l'autore non si intromette nel racconto per dire che era giusto o sbagliato, ma usa il racconto stesso. Quando Abraamo sbaglia, ci sono effetti negativi nella sua vita e nella famiglia. [Come pure succede a noi - viviamo con dolore e difficolt&agrave; spesso (ma non sempre) per decisioni passate in cui ci siamo ritenuti pi&ugrave; saggi di Dio.] C'&egrave; il disprezzo di Agar verso Sara (Gen 16:4), di cui Sara d&agrave; la colpa ad Abraamo anche se era la sua idea (Gen 16:5) [&egrave; tipico di noi: quando i nostri piani vanno storti, biasimiamo Dio o altri invece di considerare con il nostro piano era sbagliato], e Sara maltratta Agar e la fa scappare (Gen 16:6). Anche il figlio di Agar causer&agrave; problemi (Gen 16:13, 21:9-21). Se quindi era uno sbaglio, quale era il problema?</p>

<p>Il problema sembra di essere in una mancanza di fede, di dubitare quello che Dio ha detto. [Ci sono alcuni paralleli fra questo racconto e la caduta a Eden, per esempio Gen 3:17 / Gen 16:2; Gen 3:6 / Gen 16:3]. Probabilmente il fatto vero che Sara ha affermato nel secondo versetto ("Il Signore mi ha fatta sterile") era in realt&agrave; un'accusa - "&egrave; la colpa di Dio se non ho un figlio, Dio ha sbagliato, quindi devo fare qualcosa io". Dio aveva promesso un figlio ad Abraamo, ed anche se non aveva mai detto esplicitamente che sarebbe stato anche di Sara, quello che Abraamo e Sara sapevano gi&agrave; di Dio in generale (sul matrimonio) doveva bastare per capire che un figlio di Agar non era quello che Dio aveva in mente. Anche se 10 anni erano passati senza che Dio avesse dato un figlio. Non dobbiamo cercare di affrettare l'adempimento delle promesse e dei propositi di Dio. Il tempo di Dio &egrave; quello giusto, anche se ci vuole una settimana, un anno, un decennio, o di pi&ugrave;. Quando abbiamo la promessa di Dio, dobbiamo aspettare pazientemente certi dell'adempimento, senza ricorrere a piani discutibili per "aiutare" Dio. Ci sono motivi per cui abbiamo pregato per molti anni e per cui non abbiamo ancora ricevuta una risposta? O abbiamo ricevuto una risposta dopo tanti anni?</p>

<p>Possiamo anche dire che Abraamo, dopo aver sentito Dio diverse volte, che gli ha sempre indicato la strada da percorrere, doveva chiedere a Dio se fosse giusto, doveva aspettare di ascoltare lui. Invece ha dato ascolto alla voce di Sara (Gen 16:2).</p>
 
<p>Ci&ograve; non vuol dire che non dobbiamo fare niente. Una teoria della santificazione &egrave; "Let go e let God" - "lascia stare e lascia a Dio". Cio&egrave;, non dobbiamo fare niente tranne aspettare che Dio faccia quello che vuole. Ma &egrave; una teoria sbagliata. Dobbiamo impegnarci per la santificazione personale e per l'adempimento della volont&agrave; di Dio, ma in dipendenza da Dio. Per esempio, non dobbiamo pregare per la conversione dei parenti e degli amici, e poi dire che non dobbiamo testimoniare perch&eacute; dipende da Dio. Quello che non dobbiamo fare &egrave; pensare che Dio ritarda nella risposta alla preghiera e che dobbiamo quindi fare a modo nostro per costringere le persone a credere, n&eacute; pensare che serve solo qualche tecnica o capacit&agrave; nostra per convertire gli altri.</p>

<p>&Egrave; difficile pensare di paralleli precisi per noi (e quindi di un'applicazione precisa), perch&eacute; di solito non abbiamo promesse per la nostra vita personale, solo promesse per l'umanit&agrave; e la storia (per esempio Ges&ugrave; sar&agrave; con noi, ritorner&agrave;, eccetera). Ma quello che vedo (in me e in altri) &egrave; che quando non abbiamo quello che vogliamo (che spesso Dio non ci ha promesso), come Sara ci rivolgiamo ai piani discutibili e ci accontentiamo di meno del piano perfetto che Dio ha riservato per noi. Per esempio, se non riceviamo quello che riteniamo di meritare, lo prendiamo con forza o con inganno, o cominciamo a dire bugie. Oppure prendiamo un lavoro o un marito con cui &egrave; difficile servire Dio completamente. Pi&ugrave; in generale, Dio ha promesso che abbiamo tutto in Cristo. Per&ograve; spesso la vita sembra meno di questo, &egrave; molto 'quotidiana', banale, anche difficile. Cos&igrave; cerchiamo altri modi per darci piacere o soddisfazione, invece di considerare Cristo il nostro tesoro. Cerchiamo soprattutto dei modi normali nella cultura (come avere un figlio da una serva nella cultura di Abraamo), per esempio il sesso non con il coniuge, la pornografia, il materialismo, l'autorealizzazione, anche se contrari ai modi di Dio.</p>

<p>Non &egrave; esattamente la stessa cosa, ma Hudson Taylor (uno dei primi missionari in Cina) ha detto, "Al lavoro di Dio fatto nel modo di Dio non mancher&agrave; mai la provvisione di Dio. Lui &egrave; troppo saggio da frustrare i suoi propositi per una mancanza d fondi, ed &egrave; tanto facile per lui provvedere prima che dopo, e preferisce fare cos&igrave;". Per Abraamo, doveva continuare a servire Dio fedelmente seguendo Dio, e Dio avrebbe provveduto un figlio nel suo tempo nel suo modo. Per noi, dobbiamo fedelmente usare i metodi di Dio, e Dio penser&agrave; al resto.</p>

<p>La nascita di Ismaele &egrave; anche ripresa, con un insegnamento diverso, in Gal 4:21-31. In realt&agrave;, bisognerebbe anche leggere della nascita di Isacco prima di considerare Gal 4, ma probabilmente &egrave; pi&ugrave; facile parlare di Gal 4 in questo studio che durante lo studio su Gen 21, che &egrave; pi&ugrave; lungo. In Gal 4:21-31, Paolo dice che quelli che fisicamente sono figli di Isacco (cio&egrave; la nazione di Israele in generale) sono metaforicamente figli di Ismaele, in quanto schiavi alla legge di Mos&egrave;. Sono del popolo di Dio solo secondo la carne (cio&egrave; per discendenza fisica). Per&ograve;, i Cristiani sono i figli di Isacco metaforicamente (che comunque &egrave; il senso vero di essere figli di Isacco), perch&eacute; liberi. Sono del popolo di Dio secondo la sua promessa e secondo lo Spirito Santo, e perseguitati. L'applicazione &egrave; in Gal 4:30-31: non dobbiamo pi&ugrave; vivere come schiavi alla legge.</p>

<p>C'&egrave; un punto simile in Rom 9:6-8: non &egrave; sufficiente essere un discendente fisico di Abraamo (lo era Ismaele ma non ha ricevuto la promessa), quindi il fatto che non tutti gli Israeliti erano convertiti a Cristo non significava che la promessa di Dio ad Abraamo non era adempiuta. In tutti e due i brani, la promessa viene ereditata per fede, non per discendenza, che &egrave; una conseguenza dall'insegnamento principale di Gen 16, che la promessa di Dio viene adempiuta dall'opera di Dio nel tempo di Dio, non dagli sforzi umani quando vogliamo noi. In realt&agrave;, siccome le azioni di Abraamo e Sara non sono esplicitamente condannate e sono quasi ragionevoli, e non &egrave; facile capire la natura precisa del loro sbaglio, ho il dubbio che stiamo ponendo la domanda sbagliata quando chiediamo del peccato di Abraamo e Sara. Forse dobbiamo chiederci qui non quello che hanno fatto di giusto o sbagliato, ma cosa vediamo dei propositi di Dio e il suo modo di compierli. Anche perch&eacute; cos&igrave; il brano &egrave; interpretato due volte nel NT. Cio&egrave;, l'insegnamento principale forse &egrave; che la scelta e la promessa di Dio contano per adempiere i propositi di Dio, non l'opera e i piani umani (come essere Giudei, circoncisi, adempiere la legge).</p>

<p>La seconda parte del capitolo insegna almeno tre cose. Ho gi&agrave; accennata alla prima, che non seguire Dio porta delle conseguenze negative (Gen 16:12), come &egrave; successo con il fatto che Abraamo ha portato Lot con s&eacute;. Infatti, gli Ismaeliti hanno spesso creato problemi per Israele (Gen 37:25-29; Giudici 8:24; Sal 83:4-6), e Ismaele &egrave; di solito considerato l'antenato degli Arabi, e cos&igrave; dei Musulmani.</p>

<p>Per&ograve;, quello che &egrave; maggiormente insegnato &egrave; la benedizione ad Agar e Ismaele (Gen 16:10; 17:20; 21:13,18). Anche se era non era il figlio promesso e non faceva parte del piano di Dio, rimaneva comunque un figlio di Abraamo. Dio aveva promesso di benedire Abraamo, e quindi ha benedetto anche Ismaele (anche se non con le promesse di Gen 12:1-3 che portavano a Ges&ugrave; e alla salvezza del mondo). Ma solo mentre Agar (ed Ismaele) mantenevano il loro collegamento con Abraamo (16:9). Come detto gi&agrave; qualche volta, la disubbidienza umana non &egrave; una barriera per la benedizione di Dio - anche se non &egrave; una scusa per disubbidire!</p>

<p>Il terzo insegnamento della seconda parte del capitolo &egrave; che Dio sente (il nome Ismaele) e vede (il nome Atta-El-Roi), anche chi ha subito l'ingiustizia (anche se in questo caso Agar non era del tutto senza colpa Gen 16:4), anche (o soprattutto?) chi ha subito l'ingiustizia dal popolo di Dio. Dopo questo Agar ha fatto la cosa giusta, accettando e ubbidendo umilmente alla Parola di Dio. In alcuni rispetti, questo incontro con Agar &egrave; simile all'incontro con Maria in Lu 1:26-55.
</p>

<?
$n=8;
require("indice.php");
require("../../piede.php");
?>
