<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Il patto rinnovato (Gen 17:1-18:15)";
$key = "patto,Genesi 17,Genesi 18,abraamo,genesi,riflessioni";
$titolo = "Il patto rinnovato (Gen 17:1-18:15)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Il patto rinnovato (Gen 17:1-18:15)</h1>
<h2>Scopo</h2>
<p>Imparare che niente nella vita &egrave; troppo difficile per Dio, e come vivere per fede in un tale Dio.
</p>
<h2>Appunti</h2>
<p><b>Nota:</b> Il brano Gen 18:1-8, inclusa l'identit&agrave; dei tre uomini, sar&agrave; considerato nello <a href="abraamo10.php">studio successivo</a>, per concentrare la discussione durante questo studio sulle promesse e sulla fede.</p>

<p>Nel primo discorso di Dio ad Abraamo (Gen 17:1-8), Dio ribadisce le promesse di prima (padre di molte nazioni, possesso del paese di Canaan), e che ha fatto un patto con Abraamo (gi&agrave; 'firmato' da Dio in Gen 15:17-18). Aggiunge che sar&agrave; un patto e un possesso eterni. Comanda ad Abraamo la sua integrit&agrave; in risposta al patto. Nel secondo discorso (Gen 17:9-14), Dio spiega come Abraamo deve osservare il patto, cio&egrave; la circoncisione di tutti i maschi. Il patto c'&egrave; gi&agrave;, e la circoncisione non &egrave; quello che Abraamo e i suoi discendenti devono fare per mantenere il patto, ma &egrave; il un segno del patto, come l'arcobaleno era il segno del patto con No&egrave; (Gen 9:13) e il sabato del patto con Mos&egrave; (Es 31:16-17). Nel terzo discorso (Gen 17:15-22), Dio rivela di pi&ugrave; del suo modo per adempiere la promessa di una grande discendenza: sar&agrave; attraverso un figlio nato a Sara che ci sar&agrave; un patto eterno. Anche Ismaele sar&agrave; benedetto, perch&eacute; figlio di Abraamo, ma il patto sar&agrave; con Isacco. Un po' pi&ugrave; tardi, Dio parla di nuovo con Abraamo (Gen 18:1-15). Ripete che Sara avr&agrave; un figlio, ed anche lei lo sente questa volta. Oltre a questi discorsi, ci sono le risposte di Abraamo e Sara. Al comando di circoncidere tutti, Abraamo ubbidisce (Gen 17:23-27). Alla promessa di un figlio, Abraamo e Sara ridono (Gen 17:17; 18:12 15) - vedi la spiegazione nei <a href="/brani/brani.php?r=Genesi%2017:17">Brani difficili</a> per la differenza.</p>

<p>Ci sono quindi due punti principali che possono essere sviluppati: la circoncisione e i segni del patto in generale, e come Dio adempie le sue promesse e come noi rispondiamo.</p>

<p>Sarebbe possibile fare uno studio intero, o di pi&ugrave;, sulla circoncisione, ma probabilmente non serve. Ma per spiegare in breve, si pu&ograve; iniziare con Rom 4:9-12. Abraamo non &egrave; stato benedetto, non &egrave; stato giustificato, e non &egrave; entrato nel patto con Dio, quando &egrave; stato circonciso, ma la circoncisione era dopo la benedizione, la giustificazione e il patto. La circoncisione era prima di tutto il segno da Abraamo del patto. Per spiegare, un patto &egrave; come un contratto per comprare una casa. Ci sono delle cose che noi promettiamo di fare come nostra parte del patto (pagare i soldi), e c'&egrave; la firma che mettiamo per dire che siamo d'accordo. La circoncisione &egrave; come la firma, non come i promessi impegni. Gli Israeliti dovevano 'firmare' il patto con la circoncisione. Chi non firmava rifiutava il patto (Gen 17:14), ma la circoncisione non era l'impegno umano del patto. Oltre ad essere la firma (risposta) <i>di Abraamo</i> al patto, la circoncisione era anche il segno e il sigillo della giustizia dato <i>da Dio</i> del patto (Rom 4:11). Cio&egrave;, era sia un modo visibile per ricordare di essere stato giustificato per la fede, sia una garanzia da Dio di essere stato giustificato per la fede. Cos&igrave;, non &egrave; importante essere circoncisi o incirconcisi, ma essere giustificati per fede. Siamo discendenti di Abraamo (e quindi eredi delle sue promesse) perch&eacute; seguiamo le sue orme della fede non perch&eacute; siamo circoncisi (Rom 4:12). Vedi anche Rom 3:30; 1Cor 7:18-19; Gal 5:6; 6:15; Fili 3:3; Col 3:11. Per quanto riguardo la circoncisione come risposta di Abraamo al patto stabilito da Dio, possiamo dire che per noi la risposta &egrave; la circoncisione del cuore in cui spogliamo il corpo della carne cio&egrave; della natura peccaminosa (Rom 2:29; Col 2:11 - in realt&agrave;, era importante anche nell'AT Lev 26:41; Dt 10:16; 30:6; Ger 4:4). Inoltre, se la circoncisione era il segno e sigillo del patto di Abraamo, possiamo chiederci quali siano il segno e il sigillo del nuovo patto in cui noi viviamo? [Il patto di Abraamo &egrave; eterno e vale ancora per noi, in quanto ereditiamo l'adempimento delle promesse fatte a Ges&ugrave; nel patto di Abraamo, ma c'&egrave; anche un nuovo patto in Cristo che &egrave; pi&ugrave; specifico.] Come segni, abbiamo il battesimo e la Santa Cena che sono modi visibili per ricordarci di essere stati giustificati per la fede, mentre lo Spirito &egrave; il pegno della nostra eredit&agrave; (2Cor 1:21-22; Ef 1:13-14).</p>

<p>Facciamo un ripasso per ricordarci di come Dio adempie le sue promesse. Abraamo gi&agrave; era vecchio (75 anni) e Sara sterile quando Dio ha promesso che avrebbe fatto di Abraamo una grande nazione. Abraamo ha portato Lot con s&eacute; (anche se avrebbe dovuto lasciare i suoi parenti), pensando che sarebbe stato il suo erede. Ma questo piano &egrave; stato frustrato dalle scelte di Lot. Poi ha pensato che il suo schiavo Eliezer sarebbe stato il suo erede. Ma Dio ha chiuso quella porta. Era difficile aspettare ancora 10 anni dopo la promessa, e Sara ha avuto l'idea di avere un figlio tramite Agar, ma Dio ha detto che non sarebbe stato lui il figlio della promessa e della benedizione. Era difficile aspettare 10 anni, ma Dio ha fatto aspettare 24 anni, come se i 75 anni di Abraamo e i 65 anni pi&ugrave; sterilit&agrave; di Sara non fossero abbastanza. Ora, Abraamo ne ha 99 anni, Sara 89, e inoltre non ha pi&ugrave; i corsi ordinari delle donne (Gen 18:11), cio&egrave; era dopo la menopausa, e Abraamo &egrave; abituato all'idea che Ismaele sarebbe stato il suo erede (Gen 17:18). Ora, quando non c'&egrave; pi&ugrave; nessun piano o modo umano, quando non c'&egrave; pi&ugrave; assolutamente nessuna speranza, quando &egrave; pi&ugrave; che impossibile, Dio agisce, e d&agrave; il figlio promesso. Perch&eacute; Dio ha adempiuto la sua promessa in questo modo? Il proposito di Dio &egrave; di fare quello che &egrave; umanamente impossibile, affinch&eacute; dobbiamo fidarci della sua potenza e della sua gloria, affinch&eacute; lui sia glorificato. Questo non &egrave; per orgoglio o arroganza divini, ma per amore: la cosa pi&ugrave; amorevole che Dio pu&ograve; fare per noi non &egrave; esaltare noi ma rendersi indispensabile per noi affinch&eacute; godiamo la sua potenza e la sua grazia. Il fondamento qui &egrave; Gen 17:7 - l'Onnipotente Signore &egrave; il <i>nostro</i> Dio: colui che ha creato le galassie e gli atomi &egrave; Dio per noi, la sua gioia &egrave; fare del tutto per farci del bene (Ger 32:38-41). Addirittura, ereditiamo il mondo (Rom 4:13). &Egrave; il Dio dei vivi, per cui neanche la morte pu&ograve; interrompere il nostro rapporto con lui, se &egrave; un Dio per noi (Mt 22:32) - &egrave; un patto <i>eterno</i> con Abraamo. Eppure, nonostante tutto questo...</p>

<p>Eppure, non ci piace molto dipendere da Dio, e cerchiamo modi per realizzare i piani di Dio (o i nostri piani) con mezzi ordinari e umani. Dovremmo invece rispondere con la fede, una fiducia in Dio che far&agrave; quello che ha promesso. Che tutte le promesse di Dio sono adempiute in Cristo (2Cor 1:20), che i suoi propositi sono realizzati in Ges&ugrave;. Questa fede l'abbiamo vista in Gen 15:6, ma in Gen 17:17-18 la fede manca ad Abraamo, che supplica Dio di adempiere la sua promessa in un modo ordinario, di usare il piano umano. Ma Ismaele era umanamente possibile, per cui non poteva essere il figlio della promessa. Cos&igrave; Abraamo e Sara, e noi, capiamo che non c'&egrave; niente che sia troppo difficile per il Signore (Gen 18:14; anche Giob 42:2; Zac 8:6; Mc 10:27).</p>

<p>Per noi, questo brano spiega:<br />
1) come diventiamo figli di Dio. Non &egrave; per discendenza, o in generale per qualsiasi azione umana, che siamo figli di Abraamo/figli di Dio. Ma gli eredi della promessa vengono solo dalla promessa di Dio e per l'intervento di Dio (Rom 9:6-9) perch&eacute; &egrave; impossibile per l'uomo (Mc 10:26-27).<br />
2) come dobbiamo vivere nelle difficolt&agrave;. Se Dio ha fatto l'impossibile salvandoci, possiamo affidare a lui:<br />
- altre cose impossibili (la conversione di amici, parenti, popoli lontani);<br />
- le difficolt&agrave; della vita che per noi sono frustranti (famiglia, abuso passato o presente, lavoro o mancanza) ma per Dio strumenti da usare per i suoi propositi;<br />
- i peccati e le dipendenze da cui non riusciamo a sbarazzarci;<br />
- i piani grandi che sono oltre le nostre capacit&agrave; da realizzare.<br />
Se non abbiamo quello che vorremmo, se le cose non vanno come vorremmo, non &egrave; perch&eacute; Dio non &egrave; capace di darci quello che vorremmo, ma perch&eacute; Dio pu&ograve; realizzare i suoi propositi meglio senza darcelo o facendoci aspettare.<br />
3) perch&eacute; e come pregare. Ogni volta che non preghiamo per una cosa nella nostra vita o in quella degli altri, significa che crediamo che non abbiamo bisogno di Dio per realizzare quella cosa.<br />
4) come pensare al futuro della nostra vita: non possiamo vivere senza piani e progetti per la nostra vita, e di solito Dio non ci promette cose specifiche per la nostra vita. Dobbiamo fare i nostri piani comunque (fino a quando Dio interviene per dirci di no o di s&igrave;), ma sottometterli a Dio perch&eacute; la loro realizzazione dipende solo da lui e non dai nostri sforzi (Giac 4:13-16).
</p>

<?
$n=9;
require("indice.php");
require("../../piede.php");
?>
