<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "La risposta di Abraamo (Gen 12:4-9)";
$key = "risposta,Genesi 12,abraamo,genesi,riflessioni";
$titolo = "La risposta di Abraamo (Gen 12:4-9)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>La risposta di Abraamo (Gen 12:4-9)</h1>
<h2>Scopo</h2>
<p>Riflettere su come noi dobbiamo avere una fede come quella di Abraamo - e quando non ci serve avere la fede che Abraamo aveva.</p>
<h2>Appunti</h2>
<p>La fede vuol dire ubbidienza (ed anche altre cose che vedremo in questa serie di studi), e non solo affermare che qualcosa &egrave; vero senza cambiare vita.</p>

<p>La risposta fondamentale di Abraamo era l'ubbidienza - "part&igrave; come il Signore gli aveva detto" (Gen 12:4). Era un'ubbidienza 'cieca' - sembrava di viaggiare senza m&egrave;ta (da Caran, al Canaan, fino a Sichem), fino a quando Dio gli ha detto che quello era il paese. Per&ograve;, Dio non gli ha dato il paese, come forse Abraamo si aspettava, ma ha detto che la sua discendenza l'avrebbe ricevuto (Gen 12:7). Nonostante ci&ograve;, c'era la risposta della lode (Gen 12:7-8). Infine, anche se la terra di Canaan gli era promessa, non ne ha posseduto niente, e viveva come nomade in tende (Gen 12:8-9) - aveva la promessa ma non l'adempimento.</p>

<p>Ebr 11:8-10 riprende gli stessi elementi della sua risposta alla chiamata. Per fede Abraamo ubbid&igrave; (Ebr 11:8), part&igrave; senza sapere dove andava (Ebr 11:8), e soggiornava nella terra come se non fosse la sua, in tende (Ebr 11:9). Aggiunge per&ograve; che il motivo per cui &egrave; riuscito a fare cos&igrave; era che si aspettava qualcosa di pi&ugrave; della promessa, si aspettava la vera citt&agrave; di Dio (Ebr 11:10), non la citt&agrave; che gli uomini hanno cercato di costruire a Babele, e neanche il paese che gli era promesso.</p>

<p>Potrebbe essere utile riflettere su quello che significava veramente ad Abraamo ubbidire, non solo affermarlo in modo teoretico. Ur era la citt&agrave; pi&ugrave; avanzata del mondo, avevano anche inventato la vasca del bagno. Sembra che Abraamo fosse benestante (Gen 12:5; 14:14). Doveva lasciare questa bella citt&agrave; per una vita in tende, senza casa e senza terra. Ha lasciato anche la sua famiglia, sapendo che non avrebbe mai pi&ugrave; sentito di loro. Per&ograve;, &egrave; andato con la promessa di un nuovo paese e una nuova famiglia (la discendenza) - anche se la promessa era "irrazionale" e impossibile umanamente (perch&eacute; straniero, vecchio, con moglie sterile). Suo fratello Naor (Gen 11:26) ha costruito una citt&agrave; (Gen 24:10). Se avessimo chiesto ad Ur dei figli di Tera, avrebbero detto che Naor ha avuto tanto successo, ma l'altro se ne &egrave; andato chi sa dove e non ha mai fatto niente. Ma &egrave; Abraamo che adesso ha il nome grande. Calvino ha sottolineato che Abraamo ha creduto al "verbo nudo" del Signore (senza evidenza), mentre Lutero ha detto che Abraamo "ha semplicemente afferrato questo unico pensiero: Ecco, Dio lo promette. Non ti inganner&agrave;, anche se non vedi il modo n&eacute; la maniera neanche il tempo dell'adempimento della promessa".</p>

<p>In Ebr 11, Abraamo &egrave; presentato a noi come un modello della fede, ma anche come la nostra fede deve essere diversa.<br />
a) la fede &egrave; ubbidienza: &egrave; fare quello che Dio vuole, anche se non sappiamo le conseguenze dell'ubbidienza: anche se quello che noi vogliamo &egrave; pi&ugrave; comodo, o ci sembra un'idea migliore, o &egrave; come noi risolveremmo il problema. Sappiamo solo la promessa di Ges&ugrave;, che sar&agrave; sempre con noi dovunque la sua chiamata ci porta. [Quali altre promesse ci accompagnano?] Conviene cercare esempi su come e perch&eacute; evitiamo di ubbidire nella nostra vita. Per esempio, ci trasferiamo per motivi di lavoro/studio, o famiglia, o clima, o per evitare problemi, che possono essere validi motivi. Per&ograve; trasferirsi per rispondere a quello che Dio ci dice dei suoi propositi eterni e al ruolo che lui si aspetta che noi abbiamo nei suoi propositi non &egrave; solo per gli intrepidi missionari, ma per tutti. Per&ograve;, non solo per un trasloco, ma dobbiamo essere disposti a lasciare qualsiasi cosa e di fare qualsiasi cosa per seguire la chiamata di Dio (qualunque sia), adorando e proclamando Dio mentre andiamo. I nostri istinti sono di risparmiare tutto, creare protezione e sicurezza per noi stessi, cercare pi&ugrave; comfort, ma spesso seguendo Dio perdiamo tutto questo. "Possiamo affidare un futuro sconosciuto ad un Dio conosciuto" - Corrie Ten Boom. In realt&agrave; ogni giorno &egrave; un passo nello sconosciuto, anche se preferiamo fare finta che possiamo controllare il nostro futuro e che lo conosciamo. Nonostante la nostra sicurezza di poter controllare il nostro futuro, spesso l'impedimento pi&ugrave; grande alla nostra ubbidienza alla chiamata &egrave; il dubbio che possiamo fare quello che Dio ci chiede di fare: ma dimentichiamo che dipende dalla promessa di Dio e non dalla nostra capacit&agrave; o dalla nostra perfezione.<br />
b) la fede a volte &egrave; non sapere: a volte noi sappiamo anche se Abraamo non sapeva (come nel punto c qui sotto), ma a volte non vediamo (Ebr 11:1; 2Cor 5:7). &Egrave; sottomettersi a Dio anche se i sensi fisici non danno evidenza di lui o che non sappiamo cosa ci succeder&agrave; se ubbidiamo (2Cor 5:1-10). Conviene cercare esempi pratici.<br />
c) quello in cui Abraamo ha avuto fede senza riceverlo (Ebr 11:9-10,39), noi abbiamo ricevuto, cio&egrave; la salvezza in Ges&ugrave; (Ebr 11:40; 12:2). Quindi abbiamo ancora pi&ugrave; motivo di perseverare che i testimoni della fede che ci hanno preceduto (Ebr 12:1), siccome noi conosciamo il traguardo che loro non conoscevano (cio&egrave; Ges&ugrave; Ebr 12:2). Cio&egrave;, Abraamo ha avuto fede in qualcosa che non conosceva (come Dio avrebbe adempiuto la sua promessa); noi dobbiamo avere fede in qualcosa che conosciamo ma non vediamo.</p>

<p>Infine, vedremo nel prossimo studio, e spesso in questa serie di studi, che la fede di Abraamo era imperfetta, che sbagliava. Quello che garantiva i propositi di Dio era la fedelt&agrave; di Dio alle sue promesse, non la costanza delle fede di Abraamo. Ma come &egrave; chiaro da Genesi e da Ebrei 11, Abraamo era un uomo di fede e dipendeva da Dio. Viveva come nomade ma costruiva altari fissi (non una citt&agrave; n&eacute; una torre, neanche una casa per se stesso) per testimoniare a Dio ai popoli residenti in Canaan (Gen 12:7-8). L'umanit&agrave; voleva farsi un nome, Dio ha promesso di rendere il nome di Abraamo grande, ma Abraamo ha invocato il nome di Dio (Gen 12:8). In tutte le sue difficolt&agrave; e perplessit&agrave; su come Dio avrebbe adempiuto la sua promessa, non ha mai smesso di credere in quella promessa, e di ubbidire senza sapere quando o come Dio l'avrebbe adempiuta.</p>

<?
$n=3;
require("indice.php");
require("../../piede.php");
?>
