<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Il patto con Abraamo (Gen 15)";
$key = "patto,Genesi 15,abraamo,genesi,riflessioni";
$titolo = "Il patto con Abraamo (Gen 15)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Il patto con Abraamo (Gen 15)</h1>
<h2>Scopo</h2>
<p>Capire meglio la giustizia contata a chi crede.<br />
Riflettere sul significato di Dio come nostro scudo personalmente, soprattutto quando siamo confusi o perplessi da quello percepiamo dell'operato di Dio.
</p>
<h2>Appunti</h2>
<p>Abraamo inizia a disperarsi. Dopo una battaglia contro 4 eserciti, teme (Gen 15:1) - non ha paura degli eserciti, ma di rimanere senza figli. Ha cercato di salvarsi (mettendo a rischio la discendenza) andando in Egitto, ed &egrave; ritornato vergognato. Pensava di passare la sua eredit&agrave; a Lot, ma Lot l'ha deluso. Pensava poi che il suo erede sarebbe stato un suo schiavo, Eliezer (Gen 15:2-3). Ma Dio ha risposto che, prima di tutto, il piano di Abraamo non si sarebbe realizzato, e secondo, aggiunge qualcosa alla promessa spiegando (in parte) come sarebbe adempiuta. In modo particolare, Abraamo avrebbe avuto un figlio (nonostante la sua vecchiaia e la sterilit&agrave; di Sara) e la discendenza sarebbe stata enorme (Gen 15:4 5; una promessa ripetuta in Gen 22:17; 26:4; ricordata in Es 32:13; 1Cr 27:23; adempiuta in Dt 1:10; 10:22; 28:62; Ne 9:23, Ebr 11:12; ma veramente adempiuta nel punto (b) qui sotto). Poi c'&egrave; uno dei versetti pi&ugrave; importanti della Bibbia: Abraamo ha creduto alla promessa di Dio, e Dio ha contato (o accreditato, o imputato piuttosto che infuso nei termini della Riforma) questo atto di fede come giustizia. Dio ha sovranamente scelto Abraamo, senza che Abraamo avesse fatto qualcosa (neanche credere); solo dopo aver ricevuto la promessa divina Abraamo crede, e poi ubbidisce (Gen 15:10).</p>

<p>L'importanza del versetto &egrave; vista in come &egrave; citato nel Nuovo Testamento, come fondamento di come si pu&ograve; avere un rapporto con Dio. [Invece, per gli ebrei il capitolo 17 &egrave; il fondamento, per i Testimoni di Geova il capitolo 22, e per i Musulmani il capitolo 16.]<br />
a) Rom 4:18-22 approfondisce la difficolt&agrave; della promessa, e la convinzione della fede di Abraamo - nota tutte le espressioni usate: "sperando contro speranza", "credette", "senza venir meno nella fede", "non vacill&ograve; per incredulit&agrave;", "fu fortificato nella sua fede", "pienamente convinto";<br />
b) Rom 4:16-18; Gal 3:8-9,14 spiega la promessa di aver una discendenza enorme: i molti di molte nazioni che hanno la fede come Abraamo (per questo punto, anche Lu 19:9; Rom 9:7);<br />
c) Rom 4:1-8 approfondisce "contato come giustizia": ci sono due tipi di giustizia: giustizia acquistata con le proprie opere (ma Rom 3:9) e giustizia regalata. Qui c'&egrave; la giustizia regalata, &egrave; una grazia; Dio ci tratta come giusti (anche se non lo siamo), cio&egrave; siamo perdonati perch&eacute; il peccato non &egrave; addebitato; &egrave; una beatitudine per tutti quelli che credono;<br />
d) Giac 2:20-24 spiega come la fede opera, cio&egrave; in ubbidienza (come Gen 12:4; Ebr 11:8 nel <a href="abraamo03.php">terzo studio</a>). Questo aspetto della fede non &egrave; in Gen 15, perch&eacute; parla di come Abraamo ha risposto subito alla promessa di Dio, non come ha risposto durante la vita in seguito. Parleremo quindi di questo brano in Giacomo nel <a href="abraamo13.php">13o studio</a> (sul sacrificio di Isacco), ma potrebbe convenire accennare al brano di Giacomo qui, dicendo che sar&agrave; spiegato maggiormente pi&ugrave; avanti negli studi.<br />
e) Rom 4:9-12, 23-25; Gal 3:6-7 spiega l'applicazione per noi: la stessa benedizione &egrave; per tutti quelli che credono in Ges&ugrave;.</p>

<p>Possiamo anche notare alcuni altri aspetti della fede di Abraamo, oltre a quelli che abbiamo gi&agrave; visto. Non era senza paura (Gen 15:1), n&eacute; frustrazione alla lentezza dell'adempimento o alla difficolt&agrave; di credere nella promessa (Gen 15:2-3), n&eacute; il desiderio di una conferma (Gen 15:8). Sembra simile all'uomo che ha esclamato, "Io credo, vieni in aiuto alla mia incredulit&agrave;" (Mc 9:24). Non &egrave; sbagliato esprimere il nostro timore o la nostra incertezza a Dio. A volte le circostanze della vita sembrano smentire quello che Dio ci ha promesso, e siamo perplessi, confusi. La realt&agrave; &egrave; che siamo in attesa dell'adempimento della promessa (Rom 8:23-25; 2Cor 5:2). Ma Dio pazientemente viene in aiuto ai suoi servi: per Abraamo, era prima di tutto con il ricordo che Dio era il suo scudo. Moody ha detto, "Preferirei avere quella promessa che tutti gli eserciti del mondo per proteggermi - aver il Dio del cielo come mio Protettore. Dio insegnava ad Abraamo che era il suo Scudo, se si sarebbe arreso completamente alla sua cura e affidato alla sua bont&agrave;". Secondo, ha aiutato Abraamo con un'altra rivelazione; per noi, potrebbe essere con una parola che leggiamo o sentiamo dalla Bibbia, o in un altro modo, per confermare la promessa. In modo particolare, ci aiuta con lo Spirito Santo (Rom 8:26; 2Cor 5:5). Ma l'importante &egrave; credere (Gen 15:6), anche se abbiamo ancora paura o siamo ancora incerti o frustrati. Si potrebbe chiedere quando la nostra fede contiene anche timore o frustrazione, e cosa abbiamo fatto e facciamo in quelle circostanze.</p>

<p>Il terzo aiuto ad Abraamo era un patto. Abraamo aveva gi&agrave; ricevuto la promessa, sia in Gen 12:1-3 sia in Gen 15:4-6. Ora chiede a Dio di confermare o ratificare la promessa (Gen 15:7-8), che Dio fa con un patto (Ebr 6:13-20 e una cinquantina di brani nell'AT lo chiamano un giuramento). C'erano degli atti simbolici usati in quelle culture per fare un patto (Gen 15:9-11), come tagliare degli animali [infatti in ebraico per dire "fare un patto" si dice "tagliare un patto"] e camminare in mezzo a essi, come per dire, "Che io diventi come questi animali se io rompessi il patto" come Ger 34:18-19. Ma invece di tutte e due le parti che camminano in mezzo agli animali tagliati, lo fa solo Dio (Gen 15:17), perch&eacute; la permanenza del patto dipende solo dalla fedelt&agrave; di Dio, non da Abraamo - perch&eacute; il patto era una conferma della promessa gi&agrave; data, che non dipendeva da Abramo per il suo adempimento. [Altri patti erano diversi, per esempio quello con Mos&egrave; a Sinai dipendeva anche dall'ubbidienza di Israele, ma qui l'adempimento della promessa non dipendeva dalla risposta di Abraamo n&eacute; dai suoi discendenti; anche i patti con No&egrave;, Davide e con noi sono unilaterali.] In seguito, Dio dar&agrave; anche un segno del suo patto (Gen 17). Oltre a confermare la promessa, Dio spiega un po' come sar&agrave; adempiuta: i discendenti saranno schiavi fuori del paese promesso per 400 anni (cio&egrave; in Egitto, fino all'esodo), prima di ritornare in Canaan, mentre Abraamo morir&agrave; vecchio e in pace (Gen 15:13-15; vedi anche At 7:5-7). Il motivo per questa attesa nell'adempimento era che l'iniquit&agrave; degli Amorei non era ancora arrivata al massimo, e Dio doveva dare alla discendenza di Abraamo tutta la terra degli Amorei (e degli altri popoli di Canaan) (Gen 15:16,18-19; Ne 9:7-8).</p>

<p>Anche con noi Dio ha fatto un patto per confermare la sua promessa. Invece di fare un patto con il sangue degli animali, che &egrave; simbolico, lo fa con il sangue del proprio Figlio, che &egrave; veramente efficace per il perdono dei peccati. I segni per noi sono il battesimo e la Santa Cena.</p>

<p>Gen 15:13-16 sottolinea anche la sovranit&agrave; e pazienza di Dio. Dio non &egrave; stato colto impreparato dal soggiorno in Egitto, ma faceva sempre parte del suo piano. Inoltre, il paese era promesso ad Abraamo ed ai suoi discendenti. Ma Dio non era ingiusto verso gli abitanti attuali, dando tempo a loro, fino a quando la loro iniquit&agrave; andava giudicata, ma anche per il loro ravvedimento (Rom 2:4; 2P 3:8-9). Ci&ograve; si collega con il "lamento" di Abraamo in Gen 15:2. A volte noi dobbiamo aspettare l'adempimento della promessa, un'attesa che pu&ograve; essere dolorosa. L'attesa pu&ograve; essere perch&eacute; Dio sta compiendo i suoi propositi anche per altri, e ci chiede di aspettare. O perch&eacute; Dio vuole provare (nel senso di migliorare) la nostra fede. O per altri motivi che non conosciamo. Possiamo esprimere le nostre perplessit&agrave; in tali momenti ("Fino a quando, o Signore..."), e allo stesso tempo mantenere una ferma fiducia in Dio, il nostro scudo, che far&agrave; quello che ha promesso, dandoci una ricompensa grandissima. Siamo mai rimasti perplessi dal tempo di Dio per adempiere le sue promesse? Come ci aiuta in tali momenti il fatto che Dio &egrave; il nostro scudo? Che lui &egrave; paziente e sovrano?
</p>

<?
$n=7;
require("indice.php");
require("../../piede.php");
?>
