<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "La distruzione di Sodoma e Gomorra (Gen 19)";
$key = "gomorra,sodoma,distruzione,Genesi 18,abraamo,genesi,riflessioni";
$titolo = "La distruzione di Sodoma e Gomorra (Gen 19)";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>La distruzione di Sodoma e Gomorra (Gen 19)</h1>
<h2>Scopo</h2>
<p>Essere ricordati che il giudizio e la condanna di tutti da parte di Dio sono sicuri, ma che Dio ci pu&ograve; salvare. Riflettere su quanto il nostro essere nel mondo ci ha influenzati.
</p>
<h2>Appunti</h2>
<p>Il primo terzo del capitolo (Gen 19:1-11) presenta un Lot ambiguo - &egrave; ospitale e vuole proteggere gli angeli (forse Ebr 13:2), ma avrebbe dato le sue figlie vergini alla folla. Lot non &egrave; n&eacute; un esempio da seguire n&eacute; un esempio da evitare, anche se 2P 2:7-8 afferma che era giusto in mezzo alla dissolutezza, scelleratezza e iniquit&agrave;. Questa parte del capitolo serve invece per spiegare la gravit&agrave; del peccato di Sodoma, che era arrivato il momento della distruzione perch&eacute; il grido contro i suoi abitanti (da parte di chi &egrave; stato abusato?) era troppo grande (Gen 18:20; 19:13). Per una spiegazione della natura di questo peccato, vedi i commenti sui <a href="/brani/brani.php?r=Genesi%2019:8">brani difficili</a>.</p>

<p>Nel secondo terzo del capitolo (Gen 19:12-29), Dio salva i giusti dalla condanna degli empi (Gen 19:16). (Anche se, per amor dei giusti, salva anche gli empi di Soar, che era discusso nello <a href="abraamo10.php">studio precedente</a>.) 2P 2:7-8 afferma che era (almeno in parte) per la giustizia di Lot che era salvato, ma fondamentalmente era per amore di Abraamo che Lot era salvato (Gen 19:29). Alcuni che erano vicini a Lot (i generi), anche quando avvertiti, non volevano scappare, mentre la moglie &egrave; scappata, ma era troppo attratta dalla vita che stava lasciando e ha ignorato l'avvertimento (Mt 6:21). Neanche Lot aveva ancora capito bene: Dio l'aveva salvato da Sodoma ma Lot non credeva che Dio potesse salvarlo da essere travolto (Gen 19:19), e voleva ancora partecipare ad una piccola parte della vita di Sodoma (Gen 19:20). C'&egrave; un parallelo qui con la nostra situazione. La distruzione di Sodoma e Gomorra &egrave; un esempio per gli empi adesso (Mt 10:15; 11:23; Lu 17:28-32; 2P 2:6; Giuda 7; Is 1:9; 13:19; Ger 49:18; 50:40; Lam 4:6; Am 4:11), che Dio distrugger&agrave; anche loro nel giorno del giudizio. Ma dalla punizione degli empi Dio sa liberare i pii (2P 2:9) - che sappiamo non sono quelli che sono pi&ugrave; bravi degli empi, ma quelli che seguono Ges&ugrave; e trovano la propria giustizia in lui. E ci sono quelli che, anche se vicini a noi, addirittura con rapporti stretti, che vedono la piet&agrave;, che sentono gli avvertimenti, che sono fisicamente costretti a sperimentare la salvezza (19:16 - per esempio, vengono sempre in chiesa con noi), rifiutano la salvezza perch&eacute; guardano indietro con il desiderio dell'empiet&agrave; - dentro non sono cambiati. Non &egrave; un motivo per orgoglio o disprezzo verso gli altri, ma di tormento nella nostra anima a motivo delle loro opere inique.</p>

<p>Nell'ultimo terzo (Gen 19:30-39), l'origine delle nazioni di Moab e Ammon &egrave; spiegata, nazioni che si sono spesso opposte a Israele durante la sua storia (Num 22-25; Dt 23:3-6; Giudi 3:13; Giudi 10-11; 1Sam 11:2; 2Sam 10; 2R 3; Ne 2:10; Sal 83:5-8; Am 1:13-2:3; Is 15:1-16:14; Ger 48:1-49:6; Ez 25:2-11; Sof 2:8-11), ma che comunque erano protette in quanto parenti di Abraamo (Dt 2:9,19,37; vedi anche Rut 1:4). L'autore vuole sottolineare che non era un'origine nobile, diversamente dall'origine di Israele attraverso la nascita di Isacco. Fa vedere anche che la giustizia di Lot e delle sue figlie era forse solo relativa a quella dei Sodomiti - forse Lot era parzialmente innocente della nascita, ma non dell'ubriachezza, e le figlie non erano affatto pie. Ironicamente, Lot ha compiuto l'atto vergognoso che lui stesso aveva suggerito ai Sodomiti. Sodoma aveva influenzato Lot e soprattutto le sue figlie, come purtroppo succede anche spesso a noi perch&eacute; viviamo nel mondo.</p>

<p>Lot non &egrave; mai pi&ugrave; menzionato nell'Antico Testamento (solo tre riferimenti ai figli (cio&egrave; discendenti) di Lot), e possiamo riassumere la sua vita qui. &Egrave; stato portato da Abraamo in Canaan, ma forse non ha condiviso la sua visione. Nel nuovo paese beneficiava delle benedizioni di Abraamo, e ha prosperato - almeno materialmente. Ma voleva di pi&ugrave; della vita da nomade, e ha desiderato (Gen 13:10) prima la terra fertile intorno a Sodoma (Gen 13:12), e poi la vita della citt&agrave; (Gen 14:12). Sempre passi in disceso. Ormai &egrave; fuori dalla sfera di benedizione di Abraamo, e subisce la sconfitta di Sodoma, fino a quando Abraamo allarga la sua influenza di nuovo a Sodoma salvando i suoi abitanti. Ma Lot non ha imparato, e rimane a Sodoma, anzi lo troviamo in un posto fra i capi della citt&agrave; - il significato di sedersi alla porta (Gen 19:1). La sua assimilazione nella societ&agrave; era completa - anche se era ancora disprezzato dai Sodomiti (Gen 19:9,14). Ma anche se voleva tutto il meglio che la vita poteva offrire, ha finito in una caverna con solo le figlie che lo maltrattano. Questa &egrave; la vita del credente compromesso, che &egrave; attratto dal mondo. Anche se &egrave; giusto entrare nel mondo per influenzarlo (come ha fatto Giuseppe, Daniele, Ester, e Ges&ugrave;), alla fine il mondo &egrave; entrato in Lot e ha influenzato lui. Il cuore di Lot era a Sodoma molto prima del suo corpo. La storia di Lot &egrave; simile a quella del figlio prodigo in molti modi - tranne che Lot non ha mai ammesso il suo errore e non &egrave; mai ritornato alla fonte della benedizione.</p>

<p>Questo capitolo parla molto della mondanit&agrave;, dell'influenza del mondo sul credente (e magari del credente sul mondo). &Egrave; facile condannare Lot per essere vissuto a Sodoma, ma l'insegnamento della Bibbia &egrave; pi&ugrave; profondo. Noi siamo chiamati ad essere nel mondo (Gv 17:15-18) e a frequentare i grossi peccatori (Lu 5:29-32), non ad essere del mondo (partecipare agli stessi peccati) ma neanche a ritirarsi dal mondo. Quale era quindi il problema di Lot, e di pi&ugrave; della famiglia? Non era il suo indirizzo, ma il suo cuore. Nota che le figlie nella caverna si sono ritirate dal mondo, ma non per questo sono diventate non del mondo, vivevano ancora da Sodoma. La moglie di Lot si &egrave; ritirata dal mondo con il corpo, ma non con il cuore, il desiderio. Come dobbiamo quindi vivere nel mondo ma non del mondo? Non &egrave; solo evitare certi comportamenti che noi identifichiamo come mondani (che dipende dalla nostra cultura e dalla nostra et&agrave;, per esempio fumare, alcool, cinema, modi di vestiti, divorzio, giochi d'azzardo, sesso fuori del matrimonio, discoteca). Ma &egrave; avere il cuore che non desidera quello che desiderano gli altri - materialismo, il piacere, il divertimento, essere approvati dagli altri - almeno non avere questi desideri staccati da Dio. (<b>Dobbiamo</b> cercare il piacere, ma il nostro pi&ugrave; grande desiderio deve essere di godere Dio.) Se evitiamo questi desideri, avremo una vita sessuale pura (evitando non solo rapporti sbagliati ma anche la concupiscenza), vestiremo nel modo giusto, e cos&igrave; via. Poi, dobbiamo essere tormentati (2P 2:8), predicare il ravvedimento come ha fatto Ges&ugrave; vivendo nel mondo, e pregare per protezione mentre siamo nel mondo (Gv 17:15).</p>

<p>Quando Ges&ugrave; ha parlato del suo ritorno, che sar&agrave; simile alla distruzione di e alla salvezza da Sodoma, ha avvertito, "Ricordatevi della moglie di Lot" (Lu 17:28-33). Il nostro desiderio deve essere di stare con Ges&ugrave;, senza uno sguardo indietro alle cose di minor valore. Dobbiamo perdere la nostra vita per perseverare la nostra vita. Possiamo anche dire, "Ricordatevi di Rut". Rut, di Moab, una figlia di questa dissolutezza, ha rinunciato alla sua vita da Moabita per unirsi al popolo di Dio. E Dio sa salvare i pii, e non solo l'ha fatto, ma ha compiuto i suoi propositi della salvezza di ogni persona attraverso la sua esperienza, siccome Rut era l'antenata di Ges&ugrave;.
</p>

<?
$n=11;
require("indice.php");
require("../../piede.php");
?>
