<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Salmo 16";
$key = "Salmo 16";
$titolo = "Salmo 16";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Salmo 16</h1>

<p>Quando riflettiamo sulla morte, la nostra o altrui, possiamo sperimentare sentimenti profondi. Quanto pi&ugrave; quando riflettiamo sulla risurrezione: la sconfitta della morte e la vita eterna. Noi possiamo rallegrarci, esultare, e gioire quando pensiamo a quello che Ges&ugrave; Cristo ha fatto, ma anche Davide ha espresso questi sentimenti, anche prima di Cristo, nel Salmo 16. Noi ci concentreremo sugli ultimi tre versetti del Salmo, ma prima qualche breve commento sui primi otto versetti.</p>

<h2>1. Non hai nessun bene all'infuori di Dio (Sal 16:1-8)</h2>
<p>Questo Salmo &egrave; principalmente un Salmo di fiducia. Davide confida in Dio nelle difficolt&agrave; e nella perplessit&agrave;, perch&eacute; sa che tutto &egrave; nelle mani di Dio e che Dio lo pu&ograve; proteggere (Salmo 16:2). Ma Davide confida in Dio anche nel benessere e nella gioia, perch&eacute; sa che il bene &egrave; in lui (Salmo 16:2). Non solo perch&eacute; ogni cosa buona viene da lui (che &egrave; vero, Giac 1:17), ma che l'ultimo bene &egrave; Dio stesso e stare in un rapporto con lui.</p>
<p>Se il vero bene &egrave; Dio stesso, le persone con cui Davide si trova meglio sono gli altri che hanno scoperto che la ragione della vita &egrave; amare Dio, adorarlo, servirlo, e lodarlo (Salmo 16:3). Davide, che desidera glorificare Dio, &egrave; entusiasta di poterlo glorificare con altri, e gioire in Dio con altri, di sostenersi nella prova. Se non ti piace stare con altri credenti in chiesa, forse non ti piacer&agrave; stare con loro per sempre in cielo.</p>
<p>Dall'altra parte, se il Signore &egrave; il solo vero bene, quelli che non lo conoscono riceveranno i dolori piuttosto del bene, e Davide non far&agrave; niente per esaltare questi falsi d&egrave;i (Salmo 16:4).</p>
<p>Dio era l'unico bene che Davide desiderava, era quello che voleva ereditare, non la casa dei genitori n&eacute; dei soldi da qualche parente (Salmo 16:5-6). Questa eredit&agrave; era deliziosa e bella.</p>
<p>Siccome Dio &egrave; il vero bene, sono i suoi consigli che devi cercare e a cui devi ubbidire (Salmo 16:7). La seconda met&agrave; del versetto non &egrave; una contraddizione - non &egrave; che il Signore consiglia di giorno ma il tuo cuore istruisce di notte. Invece, il cuore di Davide era cos&igrave; trasformato che gli istruiva con i consigli di Dio. Quando fai la notte in bianco, quando non riesci a dormire perch&eacute; stai pensando al giorno dopo o rimpianti per il giorno prima o qualche preoccupazione o ansia, cerca Dio il tuo bene, pi&ugrave; meraviglioso di qualsiasi desiderio che hai, in cui puoi confidare perch&eacute; ti protegge da qualsiasi ansiet&agrave;.</p>
<p>Se Davide non aveva bene alcuno all'infuori di Dio, su che cosa doveva riflettere? Se tu non hai bene alcuno all'infuori di Dio, di che cosa pensi, che cosa cerchi, in che cosa trovi piacere, quale momento della settimana non vedi l'ora che arrivi? Davide poneva sempre il Signore davanti agli occhi suoi (Salmo 16:8). Che cosa poni davanti ai tuoi occhi? Possono essere i desideri e le tentazioni: il prossimo acquisto (un nuovo vestito, una nuova tecnologia) o una bella donna che vedi. Possono essere le preoccupazioni per i figli. Possono essere le cose che riesci a fare a lavoro oppure i tuoi ministeri in chiesa oppure i servizi che provvedi per gli altri. Potresti avere sempre Facebook o un nuovo gioco sul cellulare sempre davanti agli occhi. Quello che questo Salmo ci insegna &egrave; che &egrave; meglio avere il nostro Signore davanti agli occhi. Quando sei tentato da qualcosa che vedi che senza dubbio daresti piacere, poni invece Dio in tutta la sua potenza e bellezza fra te e la tentazione, che godi ancora pi&ugrave; piacere. Quando quello che Dio ha creato per il nostro godimento domina la tua vita, metti invece Dio invece davanti agli occhi, per godere ancora di pi&ugrave; il Creatore piuttosto che la creatura.</p>

<h2>2. Non sarai abbandonato alla morte (Sal 16:10)</h2>
<p>Leggiamo prima il versetto 10, perch&eacute; d&agrave; un motivo per la gioia del versetto 9.
<p>Quanto forte era la fiducia di Davide in Dio? Confidava in lui davanti a proprio tutto? Anche in confronto con la morte? E quanto forte &egrave; la tua fiducia in Dio?
<p>Davide sapeva che sarebbe morto. Come guerriero, ha visto tanti cadaveri. Ha visto morire cari e familiari. Ha messo molte persone in una tomba. Sapeva che un giorno sarebbe toccato anche a lui. Ma sapeva che anche nella tomba, non sarebbe stato in potere della morte, ma ancora nella mano di Dio. Confidava in Dio, che non lo avrebbe lasciato decomporre a niente.
<p>In realt&agrave;, sappiamo che Davide &egrave; morto e il suo corpo decomposto. Anche 1000 anni dopo Davide, 2000 anni fa, l'apostolo Pietro lo sapeva, e quindi nella sua predica a Pentecoste ha affermato:
<p>Si pu&ograve; ben dire liberamente riguardo al patriarca Davide che egli mor&igrave; e fu sepolto; e la sua tomba &egrave; ancora al giorno d'oggi tra di noi. Egli dunque, essendo profeta e sapendo che Dio gli aveva promesso con giuramento che sul suo trono avrebbe fatto sedere uno dei suoi discendenti, previde la risurrezione di Cristo e ne parl&ograve; dicendo che non sarebbe stato lasciato nel soggiorno dei morti, e che la sua carne non avrebbe subito la decomposizione. Questo Ges&ugrave;, Dio lo ha risuscitato; di ci&ograve; noi tutti siamo testimoni. (Atti 2:29-32; vedi anche Atti 13:34-37)
<p>Questo Salmo 16 &egrave; stato adempiuto completamente in Ges&ugrave; Cristo, che ha confidato in Dio anche alla sua morte. Era il Santo di Dio, con la S maiuscola, e Dio non poteva permettere che il suo Santo finisse nel nulla. Ma tutto ci&ograve; non pu&ograve; negare o rendere falsa la fiducia, la gioia, e l'esultanza di Davide. Se i Salmi, nella Parola di Dio, contengono dei sentimenti autentici, anche la sua fiducia &egrave; stata posta bene. Perch&eacute; il Santo di Dio non ha subito nessuna decomposizione; il santo di Dio non sar&agrave; distrutto dalla decomposizione.
<p>Ci sono diversi motivi per cui puoi essere sicuro di non essere distrutto dalla decomposizione. Il primo &egrave; il prezzo pagato, il secondo &egrave; la natura di Dio che ha rapporti veri e vivi.
<p>Quando ho un mal di testa, prendo un'aspirina o una bustina. Per pochi centesimi, ho il sollievo per qualche ora. Se invece costasse &euro;1000, penserei due volte. Non varrebbe la pena. Se Dio non avesse dovuto fare niente per ripristinare il suo rapporto con te, avrebbe potuto anche finire con la morte. Ma sei stato comprato a caro prezzo, il tuo riscatto &egrave; costato la sofferenza e morte orrenda di suo Figlio. Non lo fa solo per adottarti come suo figlio per qualche anno. In 1Cor 15:19 &egrave; scritto, &ldquo;Se abbiamo sperato in Cristo per questa vita soltanto, noi siamo i pi&ugrave; miseri fra tutti gli uomini.&rdquo; Io aggiungerei: &ldquo;Se Cristo &egrave; morto per noi per questa vita soltanto, lui sarebbe il pi&ugrave; deluso fra tutti&rdquo;.
<p>Il rapporto di Dio con Ges&ugrave;, con Davide, e con te, non pu&ograve; terminare con la morte.
<p>Quando Ges&ugrave; &egrave; stato interrogato dai Sadducei, che non credevano nella risurrezione, rispose:
<blockquote>&ldquo;Voi errate, perch&eacute; non conoscete le Scritture, n&eacute; la potenza di Dio&hellip;<br />
Non avete letto quello che vi &egrave; stato detto da Dio:<br />
&ldquo;Io sono il Dio di Abraamo, il Dio di Isacco e il Dio di Giacobbe&rdquo;?<br />
Egli non &egrave; il Dio dei morti, ma dei vivi&rdquo;. (Matteo 22:29,31-32)</blockquote>
<p>Con un morto, neanche Dio ha un rapporto.
<p>Il santo di Dio &egrave; messo da parte da Dio, per avere un rapporto speciale con lui. Dio lo farebbe solo per 10 anni, o 30, o 80 anni, e poi dimenticarlo per il resto dell'eternit&agrave;? Vuole mostrare il suo amore per te solo per qualche decennio? Dio merita che tu lo glorifichi solo per il tempo che l'erba cresce poi si secca, che il fiore fiorisce e appassisce? &Egrave; troppo poco che Dio sia glorificato per cos&igrave; poco!
<p>Noi abbiamo un libro degli ospiti, per quelli che mangiano a casa nostra. A volte guardo indietro qualche anno, vedo la foto e il nome di qualche ospite, e mi chiedo, &ldquo;Chi era?&rdquo; Non mi ricordo pi&ugrave;. Qualche conoscente, amico di un amico che passava da me. Non &egrave; un problema, la vita &egrave; piena di persone che conosciamo per qualche tempo, che aiutiamo e poi dimentichiamo. Sarebbe invece un problema se aprisse alla pagina di mia figlia quando &egrave; nata, e non ricordarmi pi&ugrave; di lei siccome abita pi&ugrave; con noi.
<p>Anche Dio ha un libro, si chiama il libro della vita. Noi siamo i figli di Dio, con un rapporto speciale. Pensi che un anno dopo la tua morte Dio legger&agrave; il libro della vita, vedr&agrave; il tuo nome, e penser&agrave;, &ldquo;Ho un vago ricordo di lui, ma non sono sicuro&rdquo;. O 100 o 1000 anni dopo la morte, &ldquo;Non ho la minima idea di chi sia&rdquo;. Se tu sei suo figlio, non pu&ograve; dimenticarsi di te per 1000 o milioni di anni, per tutta l'eternit&agrave;.

<h2>3. Rallegrati nella sicurezza (Sal 16:9)</h2>
<p>Quale deve essere la tua risposta a tutto questo, che Dio &egrave; il tuo bene e che non sarai abbandonato alla morte? Quale deve essere il tuo sentimento? Rallegrarti! Esultare! Questo versetto iniziare con la parola &ldquo;perci&ograve;&rdquo;, per cui &egrave; la conclusione di quello che precede. Il versetto successivo inizia con la parola &ldquo;poich&eacute;&rdquo;, per cui d&agrave; il motivo per la grande gioia espressa in questo versetto.</p>
<p>Perch&eacute; non solo il cuore si rallegra e l'anima esulta, ma ci sono benefici anche per il corpo. Il tuo corpo dimorer&agrave; al sicuro. Certo, ci sar&agrave; qualche momento di dolore, di malattia, e poi un breve periodo (in confronto con l'eternit&agrave;) in cui il corpo non funzioner&agrave;. Ma in tutto questo, il corpo sar&agrave; al sicuro, perch&eacute; Dio non permetter&agrave; al suo santo di sparire decomponendo.</p>
<p>Se devi sostituire il ginocchio perch&eacute; non funziona bene, c'&egrave; un periodo di difficolt&agrave; mentre ti abitui al ginocchio migliore. Ma poi tutto va meglio di prima. Cos&igrave; &egrave; con il tuo corpo, che va sostituito e perfezionato. E deve passare attraverso un intervento che pu&ograve; fare male, ossia la morte.</p>
<p>Quello che tu semini non &egrave; vivificato se prima non muore; e quanto a ci&ograve; che tu semini, non semini il corpo che deve nascere, ma un granello nudo, di frumento per esempio, o di qualche altro seme; e Dio gli d&agrave; un corpo come lo ha stabilito; a ogni seme, il proprio corpo. (1Cor 15:36-38).</p>
<p>Il corpo &egrave; seminato corruttibile e risuscita incorruttibile; &egrave; seminato ignobile e risuscita glorioso; &egrave; seminato debole e risuscita potente; &egrave; seminato corpo naturale e risuscita corpo spirituale. Se c'&egrave; un corpo naturale, c'&egrave; anche un corpo spirituale&hellip; Ora io dico questo, fratelli, che carne e sangue non possono ereditare il regno di Dio; n&eacute; i corpi che si decompongono possono ereditare l'incorruttibilit&agrave;. (1Cor 15:42-44,50)</p>
<p>La garanzia che hai di tutto questo, la primizia che ti fa vedere che &egrave; tutto vero e come funziona e la risurrezione del Signore Ges&ugrave; Cristo, il Santo a cui Dio non ha permesso subire la decomposizione. E neanche a te, perci&ograve; il tuo cuore si rallegra, l'anima tua esulta, e la tua carne dimorer&agrave; al sicuro.</p>

<h2>4. Impari la via della vita (Sal 16:11)</h2>
<p>Ritorniamo a Davide, lo scrittore del Salmo. Lui sapeva che il suo destino era la morte, come per tutti, ma non che sarebbe stato abbandonato al potere della morte. Il suo vero destino era la vita! Per questo motivo sa che Dio gli insegna come ricevere questa vita.</p>
<p>Dio insegna anche a te come ottenere questo destino, la via per raggiungere la vera vita. Noi sappiamo che Ges&ugrave; &egrave; risorto e il corpo non decomposto, il primo a essere risuscitato. Per ricevere questa stessa vita, dobbiamo seguire la sua via; lui &egrave; la vita della vita.</p>
<p>     <i>Io sono la via, la verit&agrave; e la vita. (Gv 14:6)</i></p>
<p>Approfondendo, Ges&ugrave; ha detto, &ldquo;Io sono la risurrezione e la vita&rdquo;, cio&egrave;, lui ha la vera vita in s&eacute;, e &ldquo;chi crede in me, anche se muore, vivr&agrave;&rdquo; (Gv 11:25), cio&egrave;, la via che dobbiamo seguire per ottenere questa vita, la via che Dio ci insegna, &egrave; credere in Ges&ugrave;.</p>
<p>Puoi confidare in Dio, che non sei un suo giocattolo con cui gioca per 50 o 80 o 100 anni e poi butta via. Invece ti ama con un amore eterno, perch&eacute; lui &egrave; eterno. Per questo motivo non hai bene alcuno all'infuori di lui.</p>
<p>Lungo quale via stai camminando? Quella che porta all'abbandono al potere della morte e alla decomposizione, oppure la via della vita di Ges&ugrave; in noi. La vera vita ora e la vita nella presenza di Dio adesso e in eterno, in cui ci sono gioia, saziet&agrave;, e delizie.</p>

<?
$n=7;
require("indice.php");
require("../../piede.php");
?>

