<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Salmo 22";
$key = "Salmo 22";
$titolo = "Salmo 22";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Salmo 22</h1>


<p>In questo Salmo, leggiamo di Davide che si trovava in difficolt&agrave;. Anche in alcuni Salmi precedenti in questa serie abbiamo trovato il salmista in difficolt&agrave;. Per&ograve;, i sentimenti espressi in questo Salmo sono diversi da quelli espressi negli altri Salmi, perch&eacute; persone diverse rispondono diversamente, e anche tu puoi rispondere in modo diverso in diverse fasi della vita o in diverse circostanze. Per questo motivo abbiamo 150 Salmi.</p>
<p>In questo Salmo, Davide si rivela come perplesso, confuso, e deluso, con dei dubbi. Nonostante ci&ograve;, riesce a esprimere la sua perplessit&agrave; e la sua lode allo stesso tempo, e possiamo imparare dal suo esempio che la perplessit&agrave; e la confusione possono vivere insieme con la fede.</p>

<h2>1. Struttura del Salmo 22</h2>
<p>Il Salmo 22 &egrave; composto da tre sezioni: le grida da parte di Davide della sua perplessit&agrave; nelle difficolt&agrave; (Sal 22:1-18), la preghiera di Davide per essere liberato (Sal 22:19-21), e la lode di Davide al Signore (Sal 22:22-31). Prima di considerare il contenuto di queste tre sezioni, vorrei spiegare questa struttura.</p>
<p>Ci sono alcuni modi in cui i credenti rispondono alle difficolt&agrave;, proprie o altrui.</p>
<ol><li>    Stavo male, Dio mi ha liberato, quindi lo lodo e lo ringrazio. Inoltre, in base a questa esperienza, mi aspetto la liberazione dalle difficolt&agrave; attuali e future. Salmo 40:1 &egrave; un esempio di questo sentimento.</li>
<li>    Sto male adesso, ma andr&agrave; tutto bene, Dio mi liberer&agrave;. Salmo 42:5 ne &egrave; un esempio.</li>
<li>    Sto male, ma Dio sta usando queste circostanze brutte per il bene, come in Romani 8:28.</li>
<li>    Sto male, ma non devo lamentarmi ma lodare, non posso sentirmi male se credo in Dio, quasi devo fare finta che il male nella mia vita non esista. Questa risposta non si trova nella Bibbia.</li>
<li>    Sto male, ma per forza deve essere colpa mia, ci deve essere un peccato nella mia vita o una mancanza di fede da parte mia che mi ha portato questa disgrazia. I discorsi degli amici di Giobbe sono un esempio di questo pensiero - ma Dio ha detto che aveva sbagliato. &Egrave; vero che a volte Dio ci corregga o ci disciplini (Ebr 12:4-11), ma ci&ograve; non spiega tutto il male che subiamo.</li>
<li>    Sto male, ma grido a Dio e lodo Dio allo stesso tempo. Questa risposta &egrave; quello che troviamo nel Salmo 22. Perch&eacute; non c'&egrave; un passaggio dalle grida alla lode come in altri Salmi, ma semplicemente io grido / io prego / io lodo.</li></ol>
<p>Le grida e la lode simultanee possono sembrare confusionarie, ma &egrave; perch&eacute; il Salmista &egrave; confuso. Quando qualcuno ci chiede, &ldquo;Come stai&rdquo;, rispondiamo, &ldquo;Sto bene&rdquo; o &ldquo;Sto male&rdquo;, ma quasi mai &ldquo;Sono confuso&rdquo;. Ma &egrave; spesso vero. Stiamo male o subiamo il male, ma sappiamo che la vita va bene nonostante questo momento difficile che stiamo passando. Ci sentiamo bene e male allo stesso tempo. Ma siamo confusi o perplessi quando non stiamo bene quanto ci aspetteremo.</p> 

<h2>2. Le grida nelle difficolt&agrave; (Salmo 22:1-18)</h2>
<p>Il Salmista, Davide, ha qualche problema sconosciuto. Per&ograve;, il problema non &egrave; la difficolt&agrave;. Il problema &egrave; che Dio gli sembra lontano (Sal 22:1-2). Non nel senso che Dio l'abbia abbandonato del tutto, perch&eacute; Dio aveva fatto delle promesse di essere sempre con Davide, come lo &egrave; sempre a noi. Sembra invece che Dio non operi nella vita di Davide, l'aiuto da parte di Dio &egrave; lontano, e Dio non risponde alle preghiere di Davide.</p>
<p>In realt&agrave;, neanche questo &egrave; il vero problema. Se Dio fosse indifferente o incapace di fronte al male, potresti solo scrollare le spalle, farti una ragione, e cercare di sopravvivere il meglio che puoi con quello che hai. Il problema era che Davide sapeva che Dio &egrave; il Santo e Dio del suo popolo Israele (Sal 22:3). Dio non sopporta il male e non si lascia sconfiggere, e si impegna per il bene del suo popolo che lo loda. Questa divergenza fra quello che Davide sa di essere vero di Dio e quello che sta sperimentando crea sentimenti di confusione e perplessit&agrave; in Davide, e questo &egrave; il vero problema.</p>
<p>Inoltre, Davide conosce la storia, sa che Dio pu&ograve; fare grandi prodigi, sa che vuole liberare chi grida a lui perch&eacute; l'ha fatto nel passato (Sal 22:4-5). Quelli che confidarono nel Signore non erano delusi; &egrave; implicito che Davide sia deluso per la mancanza di risposta, per aggiungere alla sua perplessit&agrave; e confusione. &Egrave; facile per te avere sentimenti simili:</p>
<p>Forse hai visto delle guarigioni miracolose, ma tu soffri di dolori o di una malattia cronica. Perch&eacute; gli altri sono stati guariti e tu no?</p>
<p>Forse hai sentito di risposte a preghiere, ma tu gridi continuamente a Dio e non vedi cambiamenti,</p>
<p>Forse conosci delle famiglie con dei bravi ragazzi, ma i tuoi figli sono lontani dal Signore.</p>
<p>Forse hai degli amici che stanno bene economicamente, ma tu hai difficolt&agrave; ad arrivare a fine mese.</p>
<p>Il Salmista invece &egrave; disprezzato dalla gente, non tanto perch&eacute; sta male nelle difficolt&agrave; ma perch&eacute; si &egrave; affidato a Dio che non l'ha aiutato (Sal 22:6-8). Pensava di essere gradito a Dio, ma ovviamente (secondo la gente) non lo era, era solo presunzione da parte di Davide. Abbiamo di nuovo il pensiero degli amici di Giobbe.</p>
<p>Eppure, Davide &egrave; convinto che non sia cos&igrave; (Sal 22:9-10). Davide ha sempre avuto un rapporto di fiducia verso Dio, addirittura dal grembo e dalla nascita.</p>
<p>Quindi Davide ha bisogno di Davide, perch&eacute; la situazione &egrave; grave e nessun altro lo aiuta (Sal 22:11-16). Gli altri aspettano solo la sua morte e sono gi&agrave; pronti a appropriarsi dei suoi possessi (Sal 22:17-18).</p>
<p>Davide non &egrave; l'unico personaggio biblico che ha gridato a Dio nella confusione riguardo all'opera di Dio. Abraamo aspett&ograve; 25 anni per l'adempimento della promessa di un figlio, e intanto ricord&ograve; Dio che il suo erede sarebbe stato uno schiavo (Gen 15:1-3). Mos&egrave; disse a Dio del suo disaccordo con le vie di Dio (Es 33:12-23). Abacuc protest&ograve; che Dio avrebbe usato i Babilonesi malvagi per castigare Giuda (Ab 1:12-17). Questo tipo di onest&agrave;, raccontando quello che pensi e senti, porta a una vulnerabilit&agrave; che porta a un rapporto pi&ugrave; profondo. Dio non &egrave; distante che ti dimentica, ma interagisce con noi nella nostra perplessit&agrave;. Il problema &egrave; che spesso vogliamo un rapporto superficiale con Dio, che non tocca quello che siamo veramente in profondit&agrave; o come ci sentiamo davvero, preferendo un rapporto a distanza con il semplice scambio di qualche messaggino.</p>
<p>Prima di proseguire nell'esposizione del Salmo, c'&egrave; qualcosa da notare. Non &egrave; la lezione principale che volevo sottolineare in questo Salmo, ma &egrave; importante.</p>
<p>Diversi versetti in questo Salmo sono citati nel Nuovo Testamento, riguardo alla crocifissione di Ges&ugrave; Cristo. Altri versetti descrivono altri elementi della crocifissione, anche se non citati. Qualcuno ha detto che &egrave; come se Davide fosse l&igrave; in piede alla croce, dipingendo un ritratto della morte di Ges&ugrave;. Per&ograve;, Davide sperimentava e descrisse veramente i suoi sentimenti, ma prefigurava, come una profezia, quello che Ges&ugrave; avrebbe sperimentato 1000 anni pi&ugrave; tardi. Ges&ugrave; poi attinse al pozzo dei sentimenti autentici dei Salmi per esprimere i suoi sentimenti. Come anche tu puoi cercare nei Salmi delle parole per esprimere a Dio i tuoi sentimenti in modo onesto e giusto.</p>
<ol><li>    Secondo Marco 15:34, &ldquo;All'ora nona, Ges&ugrave; grid&ograve; a gran voce: &#171;Elo&igrave;, Elo&igrave; lam&agrave; sabact&agrave;ni?&#187; che, tradotto, vuol dire: &#171;Dio mio, Dio mio, perch&eacute; mi hai abbandonato?&#187;&rdquo;, che &egrave; una chiara citazione di Sal 22:1. Anche Ges&ugrave; non sperimentava l'opera di Dio nelle sue difficolt&agrave;.</li>
<li>    Matteo 27:41-43 racconta che &ldquo;i capi dei sacerdoti con gli scribi e gli anziani, beffandosi, dicevano: &#171;Ha salvato altri e non pu&ograve; salvare se stesso! Se lui &egrave; il re d'Israele, scenda ora gi&ugrave; dalla croce, e noi crederemo in lui. Si &egrave; confidato in Dio: lo liberi ora, se lo gradisce, poich&eacute; ha detto: "Sono Figlio di Dio"&#187;. Presero in giro Ges&ugrave; per la sua fiducia in Dio, proprio come Davide in Sal 22:8.</li>
<li>    Sal 22:16 non &egrave; citato nel Nuovo Testamento, ma il discorso fra Tommaso e Ges&ugrave; dopo la risurrezione si base sul fatto che le mani di Ges&ugrave; sono state forate: &ldquo;Tommaso disse: &#171;Se non vedo nelle sue mani il segno dei chiodi e se non metto il mio dito nel segno dei chiodi, e se non metto la mia mano nel suo costato, io non creder&ograve;&#187;... Ges&ugrave; disse a Tommaso: &#171;Porgi qua il dito e guarda le mie mani; porgi la mano e mettila nel mio costato; e non essere incredulo, ma credente&#187;. (Giovanni 20:25-27).</li>
<li>    Anche le guardie inconsapevolmente seguirono la profezia del Salmo 22, perch&eacute; in Giovanni 19:23-24 leggiamo che &ldquo;i soldati, quando ebbero crocifisso Ges&ugrave;, presero le sue vesti e ne fecero quattro parti, una parte per ciascun soldato, e anche la tunica. La tunica era senza cuciture, tessuta per intero dall'alto in basso. Dissero dunque tra di loro: &#171;Non stracciamola, ma tiriamo a sorte a chi tocchi&#187;; affinch&eacute; si adempisse la Scrittura che dice:&hellip;&rdquo; &hellip;quello che Salmo 22:18 dice.</li></ol>
<p>Se sono esperienze autentiche di Ges&ugrave; e Davide, non dobbiamo vergognarci di esprimere gli stessi sentimenti a Dio, piuttosto di nasconderli e di fare finta che non esistono.</p>
<p>Naturalmente, ci sono anche delle differenze fra le nostre esperienze e quelle di Ges&ugrave; Cristo. Noi non decidiamo di sperimentare le difficolt&agrave;, non &egrave; il nostro desiderio. Dall'altra parte, Ges&ugrave; accett&ograve; volutamente la sua sofferenza, non perch&eacute; gli piaceva il dolore, ma affinch&eacute; potesse portare le tue difficolt&agrave;, potesse sostituirti nel tuo allontanamento da Dio, potesse mettere il tuo peccato sulle sue spalle.</p>
<p>Capiamo comunque che possiamo sottometterci alla volont&agrave; di Dio (come Ges&ugrave; in Mc 14:36), e allo stesso tempo chiedere il motivo di quello che succede. Quando guardi il telegiornale e vedi delle guerre, dei disastri naturali, dei bambini che muoiono di fame, dovremmo gridare a Dio, &ldquo;Perch&eacute; l'hai permesso? Per quanto tempo ancora, Signore?&rdquo; Anzi, se non piangiamo a Dio davanti a queste sciagure, non abbiamo lo stesso cuore amorevole di Dio per le persone.</p>
<p>Quindi quando siamo in difficolt&agrave;, puoi gridare e lodare allo stesso tempo. Ricordati anche di Ges&ugrave; che ha espresso gli stessi sentimenti ma che ha anche subito molto di pi&ugrave; per colpa nostra, per condurci al Padre.</p>

<h2>3. La preghiera di liberazione (Salmo 22:19-21)</h2>
<p>Nel primo versetto del Salmo, Davide chiese a Dio perch&eacute; l'avesse abbandonato, siccome non lo soccorreva. Nel versetto 19, Davide chiese a Dio di non allontanarsi e di affrettarsi a soccorrerlo. Davide sapeva che il Signore era la sua forza, e che aveva bisogno di Dio per uscire da queste difficolt&agrave;. Perch&eacute; le difficolt&agrave; erano pi&ugrave; forti di lui - le potenze opposte a lui che sono menzionate in Sal 22:12-16 sono quelle da cui vuole essere liberato in Sal 22:20-21, perch&eacute; sapeva che la sua unica via di uscita era Dio.</p>
<p>Similmente, quando le difficolt&agrave; sono pi&ugrave; forti di te, quando hai la fede di essere convinto che solo Dio &egrave; pi&ugrave; potente, puoi e devi gridare a Dio, che venga a soccorrerti, e ti liberi, che ti tolga la confusione.</p>
<p>Non c'&egrave; niente di male gridare a Dio &ldquo;perch&eacute; capita a me?&rdquo;, ma allo stesso tempo devi anche pregare il Dio sovrano che ti ama di liberarti.</p>

<h2>4. La lode a Dio (Salmo 22:22-31)</h2>
<p>Subito, come se la sua preghiera fosse gi&agrave; esaurita, Davide scoppia in lode a Dio. Non vuole lodare Dio solo, ma vuole che tutti sappiano quanto grande &egrave; il suo Dio (Sal 22:22). Per&ograve;, glorificare Dio &egrave; meno di quello che merita, glorificare Dio agli altri &egrave; meno di quello che merita, tutti devono glorificare Dio, che ne &egrave; degno (Sal 22:23).</p>
<p>Nel periodo di un minuto, Davide si lamenta che non sperimenta l'opera del grande Dio nella sua vita, chiede che il grande Dio sia la sua forza, e loda il grande Dio. Perch&eacute;? Perch&eacute; sa che Dio &egrave; grande e meraviglioso, degno di ogni lode, anche se in quel momento non c'&egrave; evidenza nella sua vita dell'opera di Dio che libera. E perch&eacute; lo sa? Perch&eacute; l'ha visto. Non in questo momento della sua vita, ma nel passato. Forse altre volte nella sua vita e forse nella vita degli altri, Dio ha liberato e esaudito chi ha gridato a lui (Sal 22:24). Quindi Davide ha fiducia per il futuro, come tutti gli umili possono avere fiducia in Dio, come tu puoi avere fiducia per il tuo futuro se cerchi il Signore (Sal 22:25-26). Perch&eacute; solo Dio veramente regna e domina, e sar&agrave; glorificato dai vivi e dai morti (Sal 22:27-29).</p>
<p>Infine, Dio &egrave; troppo grande per ricevere la tua lode solo da te. Anche annunciare agli altri quando stupendo &egrave; Dio affinch&eacute; anche loro lo glorifichino non &egrave; sufficiente. Invece, Dio &egrave; cos&igrave; grande che devi fare s&igrave; che sia lodato anche dalle generazioni future, dai figli e dai figli dei figli (Sal 22:30-31). Dio non &egrave; il Dio solo dell'inizio del 21o secolo. Dio &egrave; il Dio dell'eternit&agrave;, dei secoli in secoli.</p>
<p>Per riassumere, lo lode &egrave;:</p>
<ol><li>annunciare a altri quello che Dio ha fatto (Sal 22:22);</li>
<li>incoraggiare altri a lodare Dio (Sal 22:23-26);</li>
<li>ingrandire la lode in tutta la terra e in tutte le et&agrave; (Sal 23:27-31).</li></ol>

<h2>5. Conclusione</h2>
<p>Perch&eacute; viviamo a volte nella confusione e nella perplessit&agrave;? Il motivo &egrave; che viviamo nel periodo fra la prima venuta e la seconda venuta di Ges&ugrave; Cristo. Dio ha gi&agrave; perdonato il nostro peccato quando Ges&ugrave; l'ha portato per noi sulla croce; Ges&ugrave; ha gi&agrave; sconfitto la morte con la sua risurrezione. Ma aspettiamo la piena realizzazione e rivelazione di quello che abbiamo gi&agrave; se siamo uniti con Cristo, che succeder&agrave; quando Ges&ugrave; ritorner&agrave; nella sua gloria. Per questo motivo non &egrave; sorprendente che viviamo allo stesso momento nella gioia del rapporto autentico con il nostro Padre celeste e anche nelle difficolt&agrave; di un mondo caduto in cui sbagliamo ancora. Per questo motivo, le grida di perplessit&agrave; e le richieste di aiuto possono fare parte della nostra lode, e la lode deve fare parte delle nostre suppliche.</p>

<?
$n=4;
require("indice.php");
require("../../piede.php");
?>

