<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Salmo 42";
$key = "Salmo 42";
$titolo = "Salmo 42";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Salmo 42</h1>

<h2>1. Va bene non stare bene (Salmo 42:1-3)</h2>
<p>Quando leggo il primo versetto, ho sempre un'immagine di un bellissimo paesaggio verdeggiante e fiorente, con un fiume tranquillo da cui la cerva beve. Ci sono anche delle canzoni cristiane che utilizzano questo primo versetto per descrivere la bellezza della vita in comunione con Dio, in cui cerchiamo tutti i suoi doni e la sua grazia e lui provvede tutto quello di cui abbiamo bisogno. Come conseguenza, abbiamo tanti motivi e tanto desiderio di adorarlo.</p>
<p>Anche il Salmista conosceva questa bellezza. Per&ograve;, la sua esperienza in quel momento era diversa. Desiderava l'acqua ma non la trovava; era assetato di Dio. Anelava a Dio, ma non riusciva a trovarsi nella sua presenza. Si sentiva lontano da Dio, senza Dio nella sua vita. L'unica acqua che aveva da bere era le sue lacrime. L'immagine che dovremo avere da questo Salmo &egrave; di una cerva nel deserto, che desiderava disperatamente l'acqua ma non la trova.</p>
<p>Questo non &egrave; per dire che l'immagine della cerva al fiume &egrave; sbagliata o che le canzoni basate sul primo versetto non vanno bene. Descrivono la verit&agrave;, e sentimenti che potresti avere in altri momenti della vita. Ma se volessimo cantare il Salmo 42 con i sentimenti che aveva il Salmista, e che forse tu hai a volte, dovremmo cantare il Salmo piangendo per la disperazione.</p>
<p>A volte siamo come la cerva soddisfatta, a volte siamo come la cerva assetata. Quello che impariamo dal Salmo &egrave; che va bene non stare bene. A volte stai bene, a volte non stai bene. Certo, non siamo abituati a pensare cos&igrave;, e soprattutto a ammettere di non stare bene. Se qualcuno ti chiedi, &ldquo;Come stai&rdquo;, probabilmente rispondi sempre, &ldquo;Bene&rdquo;, anche se non &egrave; vero.</p>
<p>Lo stigma sociale contro l'ammissione di non stare bene esiste anche fra i Cristiani. Se abbiamo tutte le ricchezze e ogni benedizione spirituale in Cristo, se dobbiamo rallegrarci sempre nel Signore, se una parte del frutto dello Spirito &egrave; la gioia, come &egrave; possibile che vivi nella siccit&agrave; emotiva e spirituale? Possiamo pensare di aver sbagliato o addirittura peccato se non sperimentiamo le gioie del nuovo rapporto con Dio in Cristo, se non sperimentiamo la sua presenza, e quindi per la vergogna non lo ammettiamo n&eacute; a Dio n&eacute; agli altri Cristiani, che dovrebbero sostenerci. &Egrave; vero, sentire come il Salmista non &egrave; normale nella vita cristiana, ma &egrave; possibile che ci siamo periodi nella tua vita in cui ti senti cos&igrave;. Se qualcuno ti dice che &egrave; sbagliato, digli di leggere il Salmo 42. Va bene non stare bene. E va bene ammetterlo a te stesso, a Dio, e agli altri, anche ai milioni di persone che hanno letto il Salmo 42.</p>

<h2>2. Non stare bene (Salmo 42:3-4,6-10)</h2>
<p>In questi versetti il Salmista spiega perch&eacute; non sta bene. Potrebbero essere i motivi per cui qualcun altro sta male, ma ci sono anche altri possibili motivi.</p>
<p>Mentre il Salmista era in difficolt&agrave; e non stava bene, gli altri lo prendevano in giro, chiedendogli dove fosse il suo Dio in cui si fidava. Non poteva aiutare, non poteva risolvere i problemi? Il suo potere e il suo amore non bastavano per farlo stare bene di nuovo?</p>
<p>Per il Salmista, era come mettere un dito nella piaga. Il suo problema era precisamente la sua fede e il suo Dio. Secondo Salmo 23:4, aveva bellissimi ricordi del tempo trascorso nel tempio con il popolo di Dio, della gioia e dell'adorazione comunitaria. La distanza da questa esperienza rendeva la sua attuale siccit&agrave; spirituale ancora pi&ugrave; grave, mentre qualcuno che non ha mai sperimentato le benedizioni di Dio (come i derisori) non perde niente quando in uno stato simile. Se anche tu puoi ricordare con profonda commozione dei momenti in cui hai vissuto la bellezza della vita cristiana, i giorni in cui non la sperimenti sono ancora pi&ugrave; difficili, perch&eacute; sai che c'&egrave; di meglio. Hai avuto un saggio del Paradiso, e lo desideri e lo aneli di nuovo disperatamente.</p> 
<p>Saltiamo per il momento il Salmo 23:5, e lo considereremo pi&ugrave; tardi.</p>
<p>Mentre i versetti Salmo 23:2-4 parlano di sentirsi lontano da Dio, da Salmo 23:6 il Salmista parla della sua esperienza di essere travolto da quello che gli &egrave; intorno.</p>
<p>Prima di tutto, il Salmista riconosce e ammette di essere abbattuto. Il significato dei luoghi geografici in Salmo 23:6 non &egrave; chiaro, in parte perch&eacute; il monte Misar &egrave; sconosciuto adesso. Per&ograve;, una spiegazione probabile &egrave; che i luoghi sono dove il Salmista vive. Vuole pensare a Dio non solo nel tempio (come in Salmo 23:4) ma anche a casa, nella vita quotidiana. Il fiume Giordano &egrave; quello principale della Palestina, scorrendo dal nord al sud. Il monte Ermon invece &egrave; la montagna pi&ugrave; grande della Palestina, con quasi 3000 metri di altezza, ed &egrave; sempre coperto di neve. Per lo scioglimento della neve e la rugiada che &egrave; molto comune, produce tanta acqua, e infatti &egrave; una delle fonti principali del fiume Giordano.</p>
<p>Per&ograve; l'acqua, per scendere da 3000 metri di altezza a quasi il livello del mare, e poi al punto pi&ugrave; basso della terra (il mar Morto), fa una discesa ripida. Verso la fine della discesa c'&egrave; la cascata Banias (o Panias). Forse il Salmista pensava a questa cascata quando ha scritto Salmo 23:7. Era travolto dalle onde e dai flutti dell'acqua della cascata che passava su di lui. Forse anche tu ti senti cos&igrave; a volte. Vuoi pensare a Dio non solo la domenica in chiesa, ma anche durante il giorno, a lavoro e con la famiglia e con amici. Ma sei travolto dagli impegni e dalle richieste, dalla malattia tua o dei cari, della preoccupazione o dall'ansia per il futuro. Cerchiamo solo di tenere la testa sopra l'acqua, e non riusciamo a pensare a altro.</p>
<p>In Salmo 23:8, il Salmista si ricordava i tempi di comunione con Dio - la grazia, l'adorazione, e la preghiera. Non gli manca la fede, solo che quelle belle esperienze della vita normale con Dio rendono pi&ugrave; difficile i momenti in cui &egrave; abbattuto perch&eacute; si sente separato da Dio o perch&eacute; si sente travolto dagli impegni quotidiani. In quel momento, si sentiva dimenticato da Dio, oppresso e trafitto dai nemici che lo scherniscono (Salmo 23:9-10).</p>

<h2>3. Come pensare</h2>
<p>Che cosa devi fare quando ti senti cos&igrave;, abbattuto, lontano da Dio, travolto? Qual &egrave; la soluzione? In realt&agrave;, non c'&egrave; un trucco o metodo per ritornare allo stato normale di un rapporto con Dio. Non c'&egrave; una bacchetta magica o una via d'uscita segreta da scoprire.</p>
<p>Quello che impari da questo Salmo &egrave; invece come devi pensare mentre sei abbattuto. Abbiamo gi&agrave; visto che va bene non stare bene. Non &egrave; lo stato normale, sicuramente non &egrave; piacevole, ma non &egrave; peccato n&eacute; una mancanza di fede. Poi, l'insegnamento principale del Salmo &egrave; chiaro dalla sua struttura. I versetti Salmo 23:5,11 sono identici, e formano un coro nel canto del Salmo, seguendo una prima strofa nei versetti Salmo 23:1-4 e una seconda strofa nei versetti Salmo 23:6-10. Inoltre, il Salmo 43 &egrave; una continuazione del Salmo 42, in cui i versetti Salmo 43:1-4 formano una terza strofa e il Salmo 43:5 lo stesso coro.</p>
<blockquote>Perch&eacute; ti abbatti, anima mia?<br />
Perch&eacute; ti agiti in me?<br />
Spera in Dio, perch&eacute; lo celebrer&ograve; ancora;<br />
egli &egrave; il mio salvatore e il mio Dio.</blockquote>
<p>Quando sei abbattuto, come il Salmista, parlati. Perch&eacute; ti senti gi&ugrave;? Perch&eacute; ti abbatti? Non per sgridarti n&eacute; per comandarti di uscire da quello stato d'animo, ma per simpatizzare con te stesso, per ricordarti che non ti sentirai cos&igrave; per sempre, &egrave; uno stato temporaneo, perch&eacute; celebrerai Dio di nuovo, perch&eacute; &egrave; il tuo Salvatore e Dio. Intanto, va bene non stare bene.</p>
<p>Quando ti senti abbattuto, &egrave; importante ricordare anche che non sei solo. Spesso non te ne rendiamo conto, perch&eacute; raramente se ne parla, di solito pochi ammettono di non stare bene, per cui quando stai male puoi pensare di aver sbagliato perch&eacute; pensi (erroneamente) di essere l'unico in quello stato. Per questo motivo &egrave; bello avere i Salmi nella Bibbia, dove puoi trovare persone ispirate da Dio che si sentivano come ti senti adesso.</p>
<p>Inoltre, ci sono persone nella Bibbia come Mos&egrave;, che era abbattuto diverse volte di fronte alla ribellione degli Israeliti. O Elia, che dopo una grande vittoria sull'idolatria, cadde in una grande depressione. O Geremia, che era spesso triste per la mancanza di risposta alle sue profezie. Ma soprattutto, per non sentirti solo, puoi pensare a Ges&ugrave;, che nel giardino di Getsemani, la notte prima della sua morte, esclam&ograve;, &ldquo;L'anima mia &egrave; oppressa da tristezza mortale&rdquo; (Matteo 26:38). Non era solo triste, ma disperato con una tristezza mortale - la stessa parola che viene usata nella traduzione greca dell'Antico Testamento per tradurre &ldquo;abbattuto&rdquo; nel Salmo 42.</p>
<p>Ges&ugrave; non tenne la sua tristezza mortale a s&eacute; stesso, non lo nascose, non se ne vergogn&ograve;. Anzi, lo ammise ai suoi amici, perch&eacute; non voleva rimanere solo quando abbattuto. &ldquo;L'anima mia &egrave; oppressa da tristezza mortale; rimanete qui e vegliate con me&rdquo; (Matteo 26:38). Nella sua tristezza mortale, voleva la compagnia dei suoi amici, voleva le loro preghiere, voleva il loro sostegno. Cos&igrave; anche tu, nella tristezza, dovresti cercare la compagnia, preghiere, e sostegno degli altri.</p>
<p>Un'ultima parola se non ti senti cos&igrave; o quando non ti senti cos&igrave;. Non essere come i discepoli, che abbandonarono Ges&ugrave; nel momento del suo bisogno. Non disprezzare, criticare, o giudicare gli altri se non stanno bene; non risolvere i loro problemi. Anzi, come dice Romani 12:15, &ldquo;Rallegratevi con quelli che sono allegri; piangete con quelli che piangono&rdquo;.</p>
<p>La vita &egrave; difficile a volte, anche la vita cristiana. Riconosciamo che altri possono stare male - va bene! Piangiamo con loro nella loro afflizione, ricordiamo le grandi verit&agrave; del Vangelo. E quando non stai bene, speri nel giorno in cui Dio asciugher&agrave; ogni lacrima dai nostri occhi, non ci sar&agrave; pi&ugrave; il cordoglio, e berremo (invece delle nostre lacrime) abbondantemente dal fiume dell'acqua della vita, che aneliamo.</p>

<?
$n=1;
require("indice.php");
require("../../piede.php");
?>

