<?
include("../../conn.php");
include("../../vistesto.php");

$descriz = "Salmo 46";
$key = "Salmo 46";
$titolo = "Salmo 46";
$sezione = "Strumenti";
require("../../capo.php");
?>
<h1>Salmo 46</h1>


<p>Questo Salmo &egrave; un inno di lode e di ringraziamento a Dio, che aveva aiutato il Salmista in un periodo di difficolt&agrave;. &Egrave; qui il prodotto di una riflessione su quello che aveva sperimentato durante una difficolt&agrave;, e non dei suoi sentimenti mentre stava nella difficolt&agrave;. Spesso, quando stiamo bene, non riflettiamo abbastanza sull'aiuto di Dio quando eravamo nelle difficolt&agrave;, siamo contenti di esserne usciti e non vogliamo ricordare pi&ugrave; di tanto le difficolt&agrave; passate. Questo Salmo, quindi, &egrave; per tutti quelli che hanno passato un momento di difficolt&agrave; (che dovrebbe essere quasi tutti), e ci aiuta a esprimere i sentimenti appropriati di lode e di ringraziamento a Dio.</p>
<p>Come molte canzoni moderne, il Salmo ha la struttura di due strofe (versetti 1-3 e 4-6) seguite da un coro (7), poi una terza strofe (8-10), e il coro di nuovo (11). Siccome il coro d&agrave; il messaggio principale che il salmista vuole sottolineare, inizieremo da quello.</p>

<h2>1. Dio il tuo rifugio &egrave; con te (Salmo 46:7,11)</h2>
<p>Il coro &egrave; composto da due righe parallele. Ogni riga ha una descrizione di Dio e quello che &egrave; per noi.</p>
<p>SIGNORE degli eserciti: Quando vediamo &ldquo;Signore&rdquo; scritto in lettere maiuscole, come qui, vuole dire che nel testo ebraico c'&egrave; il nome divino Yahweh, cio&egrave; l'Io sono, l'unico che ha la propriet&agrave; intrinseca dell'esistenza. Eppure &egrave; il Dio sovrano che si &egrave; rivelato a Mos&egrave; come Yahweh, per mandarlo a salvare il suo popolo Israele. &Egrave; il Dio supremo che si &egrave; unito al suo popolo, che si &egrave; unito a te in un nuovo rapporto. Lui &egrave; il Signore degli eserciti, non degli eserciti umani ma del suo esercito, gli angeli e altri esseri spirituali e celesti che combattono per lui (e per te) affinch&eacute; la volont&agrave; di Dio sia eseguita. Questo Dio unico e potente, non un vecchietto pigro o impotente di fronte al male, &egrave; con te. Non &egrave; seduto su qualche nuvola distante, ma &egrave; presente nella tua vita. Ti conosce, sa quello che ti succede. Inoltre, non &egrave; solo con te ma per te, combatte con il suo esercito anche per proteggerti. Quasi sempre nella Bibbia, l'affermazione che Dio &egrave; con noi &egrave; seguita dall'imperativo di non temere. Anche qui &egrave; presente, nel versetto 2, che considereremo nella prossima sezione.</p>
<p>Dio &egrave; anche il Dio di Giacobbe. Perch&eacute; Giacobbe qui? Forse ci aspetteremo i grandi servitori e seguaci di Dio, cio&egrave; una descrizione come &ldquo;Dio di Abraamo&rdquo;, o &ldquo;di Mos&egrave;&rdquo;, o &ldquo;di Davide&rdquo;. Infatti, la descrizione &ldquo;Dio di Giacobbe&rdquo; non &egrave; comune nella Bibbia, appare meno di 20 volte. Giacobbe veniva da una famiglia disfunzionale, ed era il padre di una famiglia disfunzionale. Era un imbroglione e truffatore, che fu imbrogliato da suo suocero. Tuttavia, un giorno Dio lo incontr&ograve;, e promise che come era stato il Dio del nonno Abraamo, come era stato il Dio del padre Isacco, cos&igrave; anche era il suo Dio, di Giacobbe - nonostante il disastro della sua educazione, il casino che aveva fatto nella sua famiglia, nonostante la fiducia nella propria furbizia. Questo &egrave; il Dio che &egrave; con te, che nonostante il tuo passato, nonostante i casini che hai fatto: il Dio degli eserciti, potente e forte per proteggerti, che &egrave; il tuo rifugio nelle difficolt&agrave;.</p>


<h2>2. La sua protezione ti rende coraggioso (Salmo 46:1-3)</h2>
<p>Il Salmista aveva attraversato un momento di difficolt&agrave;. Non sappiamo la natura di questa difficolt&agrave;, neanche se fosse personale o nazionale. Ma la difficolt&agrave; c'era. Non dobbiamo negare le difficolt&agrave; nella vita, neanche nella vita cristiana. Ci possono essere sempre dei momenti difficili nella tua vita per tantissimi motivi, e non ci aiuta fare finta che tutto andr&agrave; bene. Se non ci fossero delle difficolt&agrave;, Dio non sarebbe descritto come rifugio o aiuto. Un rifugio esiste solo perch&eacute; i pericoli esistono.</p>
<p>Non possiamo essere sicuri di quale tipo di difficolt&agrave; il Salmista attraversava, ma era o un disastro naturale o era cos&igrave; grave da essere descritto metaforicamente come un disastro naturale. La terra era sconvolta come un terremoto, e il movimento sotto il mare poteva creare maremoti e onde anomali. Pi&ugrave; di 220.000 persone intorno all'Oceano indiano morirono in quel modo nel 2004.</p>
<p>Per&ograve;, anche in mezzo a questi grandi e pericolosi avvenimenti, non devi temere, perch&eacute; Dio &egrave; per te un rifugio e una forza. &Egrave; come se ti trovassi in montagna in mezzo a una bufera di neve. Intorno &egrave; tutto bianco, fa freddissimo, ma a malapena scorgi quello che potrebbe essere un edificio. Combatti contro il vento contrario, arrivi alla porta, la apri, e ti trovi in mezzo ad un rifugio, con un camino che riscalda tutto l'ambiente e alcune bevande calde che ti aspettano.</p>
<p>Sarebbe il colmo arrivare al rifugio in quelle condizioni e trovare una cartella sulla porta, &ldquo;Chiuso per l'inverno&rdquo;. A che cosa servirebbe un rifugio chiuso? Per questo Dio &egrave; descritto come un rifugio, un aiuto sempre pronto nelle difficolt&agrave;. Dio &egrave; sempre pronto a accoglierti e aiutarti, non chiude mai, non va mai in vacanza, &egrave; sempre fornito di tutto quello di cui hai bisogno.</p>
<p>Per&ograve;, l'immagine del rifugio alpino per proteggere dal pericolo non &egrave; del tutto corretta. &ldquo;Non temiamo&rdquo; nel senso che abbiamo ogni comodit&agrave; mentre quelli fuori subiscono le conseguenze della bufera di neve. Piuttosto, non temiamo le conseguenze della bufera perch&eacute; Dio &egrave; con noi nella bufera. Non temiamo, e quindi siamo coraggiosi e non comodi. Usciamo nella bufera per testimoniare, per amare, per aiutare i deboli, per impegnarci nella comunit&agrave;, perch&eacute; Dio &egrave; per noi un rifugio e una forza, un aiuto sempre pronto nelle difficolt&agrave;. Infatti, anche i Cristiani muoiono nei disastri naturali e per altre sciagure. Ma non temiamo perch&eacute; nell'instabilit&agrave;, Dio &egrave; stabile, &egrave; un rifugio che non si muove. Abbiamo la certezza che Dio sta adempiendo i suoi propositi stabili anche nelle difficolt&agrave;, anche nell'instabilit&agrave; del mondo. Non dobbiamo temere che la situazione sia sfuggita da mano a Dio. Invece, quando sembra che il tuo mondo stia cadendo intorno a te, possiamo rifugiarci in Dio che ci d&agrave; coraggio per vivere in questo mondo.</p>
<p>Questi versetti possono anche descrivere, in modo metaforico, altri aspetti dell'instabilit&agrave; della vita.</p>
<p><i>La guerra:</i> Esistono abbastanza armi per smuovere i monti e fare rumoreggiare le acque; anzi, per distruggere il mondo diverse volte. Dio non permetter&agrave; che succeder&agrave; fuori della sua volont&agrave;.</p>
<p><i>La vita quotidiana:</i> Possiamo essere travolti dagli avvenimenti della vita (come in Salmo 42:7), come la malattia, i problemi della famiglia, o semplicemente le migliaia di impegni della vita normale. Dio sa tutto di tutto questo ed &egrave; un aiuto sempre pronto. Porta a lui, il tuo rifugio, le preoccupazioni. Non ce la fai? Certo, non devi pensare che puoi farcela. Solo Dio pu&ograve; tutto. Devi avere una fiducia in Dio stabile, non nella tua capacit&agrave; di controllare la tua vita.</p>
<p><i>Attacchi spirituali:</i> Martin Lutero, fra le altre cose che fece, scrisse anche molti inni. Il suo inno pi&ugrave; famoso &egrave; &ldquo;Forte rocca&rdquo;, che si ispira a Salmo 46:1. La prima strofa dice (in italiano):</p>
<blockquote>Forte rocca &egrave; il nostro Dio,<br />
Nostra speme in Lui si fonda.<br />
Ne sostien benigno e pio,<br />
Nell'angoscia pi&ugrave; profonda.</blockquote>
<p>Quando lui pensava alle difficolt&agrave; e all'instabilit&agrave;, pensava agli attacchi di Satana e dei demoni, che sentiva fortemente. Le altre strofe del suo inno raccontano che Dio lo difendeva, che Ges&ugrave; era vittorioso sul male e gli dava vigore. Quindi non tremava, nonostante tutto quello che gli succedeva, e poteva andare avanti coraggiosamente.</p>

<h2>3. La sua presenza ti rende gioioso (Salmo 46:4-6)</h2>
<p>Abbiamo, nel versetto 4, una bella immagine pacifica e paradisiaca nella dimora di Dio. Come nel giardino di Eden, c'&egrave; un bellissimo fiume che d&agrave; vita al terreno circostante. Per&ograve;, diversamente da Eden, la dimora di Dio non &egrave; pi&ugrave; un giardino ma una citt&agrave;. Il giardino andava bene quando il popolo di Dio consisteva di due persone che dovevano solo fare il giardinaggio per custodire la terra, e poteva chiacchierare con Dio mentre passeggiava la sera. Ma al tempo del Salmista, il popolo di Dio era pi&ugrave; grande, e Dio dimorava in mezzo al suo popolo nel tempio a Gerusalemme, la citt&agrave; di Dio. Noi invece, con un popolo ancora pi&ugrave; grande, pensiamo alla nuova Gerusalemme, la Gerusalemme celeste che &egrave; enorme, e di Dio che si trova in essa. Invece della passeggiata serale, Dio si trover&agrave; al bar per un aperitivo con i suoi, nella fabbrica per lavorare per la gloria di Dio, nell'atelier per creare nuove opere d'arte per adorare Dio. E la sua presenza ti render&agrave; (e di solito ti rende gi&agrave; adesso) gioioso in tutto quello che fai.</p>
<p>La citt&agrave; dove Dio dimora non pu&ograve; vacillare, &egrave; stabile, perch&eacute; il Signore la protegge e la soccorre, e niente pu&ograve; far tremare Dio. Nel caso della nuova Gerusalemme, &egrave; stabile per sempre. Anche se altri vogliono gridare, se vogliono combattere o fare rumore di guerra, la citt&agrave; di Dio non pu&ograve; vacillare. Il Salmista pensava alle nazioni intorno a Israele, che erano sempre pronte a combattere. Noi possiamo pensare alle nazioni attuali che vogliono fare la guerra, a tutte le minacce alla pace e al popolo di Dio. Ma la citt&agrave; di Dio non pu&ograve; vacillare, Forse dipendiamo dalla buona volont&agrave; di altri stati, per&ograve; anche quelli vacilleranno e cadranno. Noi dobbiamo essere contenti di stare in Italia, che ci d&agrave; la tranquillit&agrave; per vivere una vita pia e la libert&agrave; di testimoniare, e dobbiamo pregare per i nostri governanti. Ma la nazione di Italia non esister&agrave; per sempre, non pu&ograve; soccorrerci e proteggerci per sempre, ma la citt&agrave; di Dio non pu&ograve; vacillare. Infatti, spesso &egrave; Dio che fa vacillare le nazioni che rumoreggiano. Il Signore fa sentire la sua voce e le nazioni sono sconfitte e spariscono, addirittura la terra si scioglie.</p>
<p>Per questi motivi, ripetiamo e ribadiamo il coro. Nonostante le incertezze, i pericoli dei disastri naturali, delle nazioni e della societ&agrave;, Dio &egrave; con noi ed &egrave; il nostro rifugio, e non vacilla mai.</p>

<h2>4. La sua potenza ti fa glorificare (Salmo 46:8-10)</h2>
<p>Abbiamo visto quello che Dio fa e che &egrave; stabile, diversamente dal mondo della Natura e dell'umanit&agrave;. Quindi, che cosa devi fare tu?</p>
<p>Devi venire e guardare le cose stupende che Dio fa, il suo controllo totale su tutto, la sua potenza. Devi meravigliarti, rimanere a bocca aperta per le sue opere. Fra altro, Dio decide quando le guerre cessano. Vuoi una fine ai conflitti che ci sono sempre? Prega, perch&eacute; &egrave; Dio che distrugge le armi.</p>
<p>Poi arriver&agrave; il giorno in cui Dio far&agrave; cessare tutte le guerre una volta per sempre. Il Signore dir&agrave;, &ldquo;Basta, fermatevi! Riconoscete che io sono Dio, sovrano, il pi&ugrave; potente&rdquo;. Perch&eacute; si combatte per prevalere sugli altri, per dimostrare di essere pi&ugrave; forti e quindi in grado di imporre la propria volont&agrave;. Ma il giorno verr&agrave; in cui Dio sar&agrave; glorificato (volente o nolente) da tutti, da tutte le nazioni sulla terra. Tutti riconosceranno che Dio &egrave; supremo e si renderanno conto che non devono combattere per la supremazia; tutti glorificheranno Dio e non s&eacute; stessi.</p>
<p>&ldquo;Fermatevi&rdquo; &egrave; un invito, anzi un comando, non solo alle nazioni, ma anche a te. Solo Dio non vacilla, solo Dio &egrave; stabile per sempre. Quindi anche tu devi fermarti e riconoscere che solo lui &egrave; sovrano nell'universo. Devi smettere di temere (come nella prima strofa), devi smettere di stare in ansia (come nella seconda strofa). Devi cessare di litigare con gli altri per prevalere e per avere la superiorit&agrave;, devi smettere di criticare per umiliare, devi fermare la prepotenza e la violenza (di ogni forma) verso gli altri. Perch&eacute; non devi vincere o essere superiore in casa, a lavoro, o in chiesa. Solo Dio pu&ograve; e deve vincere e essere esaltato in ogni sfera della tua vita. Glorifica Dio e non te stesso.</p> 

<h2>5. Conclusione</h2>
<p>Nelle situazioni difficili, a volte create da noi stessi, il potente Signore degli eserciti, il Dio di Giacobbe (l'imbroglione che ha fatto disastri nella sua famiglia) &egrave; il nostro rifugio. Non dobbiamo vincere contro la tempesta n&eacute; contro le guerre che subiamo, perch&eacute; solo questo Dio vince e sicuramente vincer&agrave;, ma intanto &egrave; anche il nostro rifugio durante la battaglia, per proteggerti, affinch&eacute; tu possa essere coraggioso, per stare con te e per sempre affinch&eacute; tu possa essere gioioso, e per farsi glorificare da te a da tutte le nazioni.</p>
<?
$n=2;
require("indice.php");
require("../../piede.php");
?>

