<?
include("../conn.php");
include("../vistesto.php");

$descriz = "La caduta (Genesi 3); una parte di una panoramica della Bibbia";
$key = "caduta, genesi, panoramica, storia, racconto";
$titolo = "La caduta (Genesi 3)";
$sezione = "Strumenti";
require("../capo.php");
?>
<h1>2. La caduta (Genesi 3)</h1>
<p class="primalettera">Alla fine dello <a href="creazione.php">studio precedente</a>, la creazione era perfetta, con tutto (Dio, l'uomo, il creato) nei rapporti giusti l'uno con l'altro. Cos&igrave; inizia questo capitolo della Bibbia. Per&ograve;, alla fine del capitolo tutto sar&agrave; rovinato. La causa di questo cambiamento &egrave; il peccato dell'uomo, che non era altro che un tentativo di rovesciare questi rapporti, cercando di decidere quello che era giusto e sbagliato quando &egrave; Dio che fa questo per l'uomo. Prima del peccato c'era la tentazione, che sar&agrave; il tema di questo studio, mentre il <a href="peccato.php">prossimo studio</a> parler&agrave; della crescita del peccato.</p>

<h2>Tentazione (Gen 3:1-6)</h2>
<p>Ci furono tre passi nella tentazione da parte del serpente: discussione, contraddizione, e sfiducia.</p>
<p>Prima di tutto, il serpente <strong>mise in discussione</strong> il comando di Dio: "Dio ha veramente detto di non mangiare nessun albero del giardino?" (Gen 3:1). Naturalmente, non l'aveva detto, come Eva rispose (Gen 3:2-3). Ma il serpente era riuscito a fare una testa di ponte nei pensieri di Eva, che cominci&ograve; ad analizzare e valutare i comandi di Dio. Lei dovere invece rispondere, "Sei un idiota. Io vivo in una creazione perfetta, siamo fatti poco inferiori agli angeli, ho un marito che pensa che io sia fantastica, sotto un Dio meraviglioso che mi benedice. Non voglio discutere dei suoi comandi".</p>
<p>Il secondo passo era <strong>contraddire</strong> Dio, accusare Dio di non essere veritiero (Gen 3:4). Se Dio non dice la verit&agrave;, perch&eacute; dobbiamo fidarci di lui quando dice che una cosa &egrave; sbagliata? Forse non lo &egrave;, e se non dice la verit&agrave; sar&agrave; meglio che decidiamo noi quello che &egrave; giusto e sbagliato</p>
<p>Il terzo passo era <strong>sfiduciare</strong> Eva nei confronti di Dio, accusare Dio di aver motivi sbagliati, di essere egoista (Gen 3:5). Se Dio non vuole benedirci, perch&eacute; dobbiamo sottometterci a lui? Se Dio vuole solo il proprio bene sar&agrave; meglio che decidiamo noi quello che &egrave; giusto e sbagliato, cos&igrave; noi saremo il dio della nostra vita invece di Dio.</p>
<p>Poi la donna vide che l'albero era buono e bello (Gen 3:6) - non &egrave; una sorpresa, perch&eacute; Dio l'aveva fatto buono, come ogni cosa nella creazione. Il problema invece era che lei desiderava qualcosa che non le apparteneva, acquistare la conoscenza, cio&egrave; la conoscenza del bene e del male. Questo non era sapere che cosa era giusto e sbagliato, lo sapevano gi&agrave; perch&eacute; Dio aveva detto. Era conoscere nel senso di decidere, poter scegliere autonomamente da Dio le proprie azioni. Questo era il desiderio di Eva.</p>
<p>Questo &egrave; anche il nostro desiderio. Ogni volta che pecchiamo, mettiamo in discussione il comando di Dio, non crediamo che sia la cosa migliore da fare, e decidiamo noi quello che facciamo. Soppiantiamo Dio, volendo essere supremi sulla nostra vita - e spesso anche sulla vita degli altri.</p>
<p>Cos&igrave; la donna prese e mangi&ograve;, che nel piano di Dio sono anche le azioni che sono diventate simboli della nostra salvezza (Mt 26:26).</p>
<h2>I rapporti sbagliati dell'uomo (Gen 3:7-24)</h2>
<p>Al posto dei rapporti giusti dell'uomo, ci sono i rapporti sbagliati con Dio, con la creazione, e con gli altri. La ribellione contro la supremazia di Dio ha un effetto non solo sul rapporto con Dio, ma sottopone tutta la creazione alla vanit&agrave; e alla corruzione (Rom 8:20-21).</p>
<h3>Con Dio</h3>
<p>Il rapporto con Dio &egrave; <strong>compromesso</strong>. Per l'uomo, Dio non &egrave; pi&ugrave; il benevolo sovrano di tutto l'universo. Invece l'uomo valuta e giudica Dio, dubitando della sua parola e dei suoi motivi. Invece della fiducia, c'&egrave; la disubbidienza e il desiderio di usurpare Dio nel governo della propria vita (Gen 3:6).</p>
<p>Dopo aver mangiato il frutto, il rapporto &egrave; rotto e l'uomo si nasconde <?bd("Gen3:8");?> per la <strong>vergogna</strong> e per la <strong>paura</strong> (Gen 3:7-10) - due conseguenze del peccato che saranno approfondite nello <a href="chiesa.php">studio 18</a>.</p>
<p>Come punizione (ma anche per grazia, come sar&agrave; descritto nella prossima sezione), l'uomo &egrave; <strong>allontanato</strong> dal giardino (Gen 3:22-24). Non c'&egrave; pi&ugrave; la comunione della presenza di Dio che camminava con l'uomo nel giardino - anche questa conseguenza sar&agrave; approfondita, nello <a href="dio_con_noi.php">studio 17</a>.</p>
<p>Per&ograve; l'uomo non &egrave; maledetto, come succede al serpente e alla terra. Dio ha ancora dei propositi per l'umanit&agrave;, che saranno rivelate nel resto della Bibbia, e la maledizione sulla terra aspetta la redenzione dell'uomo per essere tolta.</p>
<h3>Con la creazione</h3>
<p>Il risultato del peccato dell'uomo &egrave; che il suolo &egrave; stato maledetto, in modo che anche se continuer&agrave; a provvedere per l'uomo, sar&agrave; con l'<strong>affanno</strong> (Gen 3:17-19; vedi anche Rom 8:19-23). L'uomo ha ancora il compito di custodire la terra, ma &egrave; un compito che viene eseguito con sudore, mentre nel giardino non era difficile. Ci&ograve; spiega perch&eacute; per noi adesso spesso il lavoro &egrave; faticoso: tutto non funziona pi&ugrave; come dovrebbe. Questo aspetto della vita sar&agrave; approfondito nello <a href="saggezza.php">studio 13</a>, sul libro di Ecclesiaste.</p>
<p>In un certo senso, l'uomo che ha peccato &egrave; pi&ugrave; attaccato alla terra. Anche se era formato dalla terra in quanto una parte della creazione (Gen 2:7), mentre era nel giardino poteva vivere per sempre - non perch&eacute; aveva una natura immortale ma perch&eacute; mangiava il frutto dell'albero della vita (Gen 3:22). Dio lo teneva in vita. Ma secondo la promessa che l'uomo sarebbe morto se mangiasse dell'albero della conoscenza del bene e del male (Gen 2:17), dopo il peccato l'uomo &egrave; cacciato dal giardino e non pu&ograve; pi&ugrave; mangiare dell'albero della vita, per cui morir&agrave;, <strong>ritornando alla polvere</strong> da cui &egrave; stato formato (Gen 3:19). La terra, che doveva essere la nostra casa perfetta, diventa la nostra tomba.</p>
<h3>Con altri</h3>
<p>Invece di un rapporto di sostengo reciproco, ora c'&egrave; un rapporto di <strong>accusa</strong>. Piuttosto di difendere o proteggere sua moglie, Adamo cerca di passare la colpa ad Eva (Gen 3:12). Dice quasi che &egrave; colpa di Dio - Eva &egrave; chiamata "la donna che tu [cio&egrave; Dio] mi hai messa accanto", come se Dio avesse sbagliato. Adamo ed Eva non sono pi&ugrave; una stessa carne (Gen 2:24), ma ognuno fa quello che &egrave; meglio per se stesso, anche se fa male all'altro.</p>
<p>Per la donna, la gravidanza e il parto, quel periodo meraviglioso in cui c'&egrave; un nuovo rapporto con una nuova vita, diventano <strong>dolorosi</strong> (Gen 3:16) <?bd("Gen3:16")?>. Inoltre, l'uomo <strong>dominer&agrave;</strong> sulla donna piuttosto di amarla e dare se stesso per lei (Ef 5:25,28), come Adamo ha gi&agrave; cominciato a fare accusando Eva.</p>
<h2>Grazia</h2>
<p>Nonostante il peccato e conseguenti condanna e punizione, Dio mostra <strong>grazia in mezzo al giudizio</strong>. Anche nelle piccole cose, come fare delle tuniche di pelle per vestire Adamo ed Eva (Gen 3:21). Pi&ugrave; importante &egrave; il fatto che vengono scacciati dal giardino. &egrave; una punizione, perch&eacute; vivono ora in un mondo ostile piuttosto del paradiso, ma il motivo &egrave; per il bene dell'uomo (Gen 3:22-24). Invece di lasciarlo dove avrebbe potuto mangiare dell'albero della vita e vivere per sempre in un rapporto sbagliato con Dio, con la creazione, e con altri, Dio lo manda via per lasciare la possibilit&agrave; di ripristinare questi rapporti, e poi vivere per sempre in uno stato giusto.</p>
<p>Sar&agrave; possibile ritornare ad un rapporto giusto con Dio? Tutto il resto della Bibbia, e gli altri studi di questo testo, risponderanno a questa domanda. Per&ograve; ci sono gi&agrave; un indizio e una promessa. Dio dice che la progenie della donna schiaccer&agrave; il capo del serpente, ma il serpente ferirai il calcagno della progenie (Gen 3:15). Il male sar&agrave; sconfitto, anche se ci sar&agrave; un prezzo da pagare. Questa promessa &egrave; stata adempiuta da Ges&ugrave; Cristo, nato da donna (Gal 4:4), anche se abbiamo molta strada da percorrere nella Bibbia prima di arrivare a quel punto. Intanto, nella prossima parte della Bibbia ci sar&agrave; la ricerca della progenie che liberer&agrave; l'umanit&agrave;.</p>
<h2>Nella Bibbia: La tentazione</h2>
<p>In Gen 3, il serpente, che rappresenta Satana, tenta Adamo ed Eva. Il ruolo di Satana nella tentazione &egrave; comune nella Bibbia (1Cr 21:1; Giob 1-2; 1Cor 7:5). Per&ograve; anche noi tentiamo noi stessi (Giac 1:14): la nostra concupiscenza, cio&egrave; desiderio di aver qualcosa che non dovremmo avere, ci seduce e ci tenta di fare o pensare qualcosa che non dobbiamo. Quello che non dobbiamo fare &egrave; cedere alla tentazione (Mt 26:41); solo quando la seduzione della concupiscenza ha avuto effetto e prendiamo quello che desideriamo c'&egrave; il peccato (Giac 1:14-15). Da questo segue un principio importante: essere tentati non &egrave; sbagliato, solo cedere alla tentazione &egrave; sbagliato. Non possiamo evitare la tentazione - dopotutto, viene in parte da fuori di noi - ma dobbiamo cercare con tutta la nostra forza di evitare di cedere alla tentazione.</p>
<p>Dall'altra parte, Dio non ci tenta mai (Giac 1:13) <?bd("Giac1:13");?>. Ci manda delle prove, che a volte somigliano ad una tentazione (infatti la stessa parola greca vuol dire sia provare sia tentare), ma lo scopo della prova &egrave; di farci del bene (Giac 1:2-4,12) mentre lo scopo della tentazione &egrave; di farci del male (facendoci cadere), che Dio non pu&ograve; mai fare. Invece Dio pu&ograve; limitare la tentazione: dobbiamo pregare di non essere tentati (Mt 6:13; 26:41) che presuppone che Dio pu&ograve; togliere la tentazione; e Dio non permette che siamo tentati oltre quanto possiamo sopportare (1Cor 10:13).</p>
<p>Ges&ugrave; fu condotto dallo Spirito Santo per essere tentato da Satana (Mt 4:1). Ci&ograve; ribadisce che Satana tenta e non Dio, ma Dio pu&ograve; permettere o portarci alla tentazione (come &egrave; successo a Giobbe in Giob 1-2). Ribadisce anche il fatto che la tentazione non &egrave; un peccato, perch&eacute; anche Ges&ugrave; fu tentato. Non solo questa volta, ma &egrave; stato tentato come noi in ogni cosa (Ebr 4:15). La differenza fra Ges&ugrave; e noi non &egrave; nella tentazione, ma nel fatto che Ges&ugrave; non &egrave; caduto, n&eacute; nella tentazione nel deserto (Mt 4:1-11) n&eacute; in nessuna altra circostanza (Ebr 4:15). Siccome Ges&ugrave; &egrave; simile a noi nel fatto di aver sofferto la tentazione, pu&ograve; venire in aiuto a noi quando siamo tentati (Ebr 2:17-18). Senza l'incarnazione del Figlio in Ges&ugrave;, Dio non avrebbe potuto simpatizzare con noi nella nostra debolezza (Ebr 4:15).</p>
<p>Quindi adesso viviamo in un tempo di tentazione, con l'aiuto di Dio che riduce la tentazione e di Ges&ugrave; che simpatizza con noi. Ora aspettiamo la fine, quando il gran tentatore sar&agrave; distrutto (Ap 12:9; 20:10).</p>
<h2>Domande</h2>
<p>1. Pensa ad un tuo peccato: in quale modo dubitavi che Dio diceva quello che era giusto o che era buono; in quale modo volevi comandare tu sulla tua vita invece di Dio?</p>

<p>2. Che cosa dice Rom 8:19-23 di quello che &egrave; successo in Gen 3, e che cosa aggiunge?</p>

<p>3. In quali modi, nel tuo lavoro o in quello che fai a casa, sperimenti la maledizione che il lavoro viene svolto con affanno e sudore?</p>

<p>4. Qual &egrave; il tuo atteggiamento verso la tentazione? Disperazione, indifferenza, resistenza, arresa, una spinta a chiedere per cercare l'aiuto di Dio, o altro? Qual &egrave; l'atteggiamento biblico?</p>



<?
$n=2;
require("indice.php");
require("../piede.php");
?>
