<?
include("../conn.php");
include("../vistesto.php");

$descriz = "La chiesa (Atti e Lettere); una parte di una panoramica della Bibbia";
$key = "chiesa, atti, lettere, epistole, paolo, pietro, panoramica, storia, racconto";
$titolo = "La chiesa (Atti e Lettere)";
$sezione = "Strumenti";
require("../capo.php");
?>
<h1>19. La chiesa (Atti e Lettere)</h1>
<p class="primalettera">Alla morte e risurrezione di Ges&ugrave;, tutte le promesse ad Eva, ad Abraamo, e a Davide furono adempiute, tutti i propositi di Dio furono compiuti. Tranne una promessa, tranne un proposito: che tutte le nazioni sarebbero state benedette (Gen 12:3). Il libro degli Atti e le lettere nel Nuovo Testamento descrivono l'inizio dell'adempimento di questa promessa.</p>

<h2>Contenuto</h2>
<p>Il libro degli Atti &egrave; stato scritto dalla stessa persona che ha scritto il Vangelo secondo Luca, e ne &egrave; una continuazione (Lu 1:1-4; At 1:1-2). Il Vangelo conclude con l'<b>ascensione</b> di Ges&ugrave; (Lu 24:50-53), e Atti inizia con lo stesso avvenimento (At 1:9-11) <?bd("Lu24:50")?>. Prima di andare in cielo, Ges&ugrave; spieg&ograve; agli apostoli il loro compito, che &egrave; anche un riassunto di Atti: avrebbero ricevuto lo Spirito Santo, e sarebbero stati testimoni in Gerusalemme, in tutta la Giudea e Samaria, e poi fino all'estremit&agrave; della terra (At 1:8).</p>
<p>Dopo l'ascensione, gli apostoli e gli<i></i> altri Cristiani (circa 120) aspettarono in preghiera, e scelse qualcuno per sostituire Giuda che aveva tradito Ges&ugrave; (At 1:12-26) <?bd("At1:24-26")?>. Poi, nel giorno della Pentecoste, lo <b>Spirito Santo</b> scese su tutti loro, e non solo su loro ma su circa 3000 persone di praticamente tutto il mondo conosciuto che si ravvidero alla predicazione di Pietro (At 2). Questo fu l'adempimento della promessa del nuovo patto, che Dio avrebbe dato un nuovo cuore tramite il dono del suo Spirito a tutti, non solo a qualche persona speciale per un compito particolare <?bd("At2:19-20")?>. Rovesci&ograve; anche la maledizione di Babele (tutti capivano Pietro nonostante le diverse lingue della gente) e cos&igrave; inizi&ograve; la benedizione di tutte le nazioni (Gal 3:8,14). Il compito del popolo di Dio era quindi di portare questa benedizione a tutte le nazioni fino all'estremit&agrave; della terra, e ne vediamo i primi passi nel resto di Atti.</p>
<p>Pietro e Giovanni continuarono a predicare e a guarire gli ammalati a <b>Gerusalemme</b> (nonostante il fatto che furono arrestati due volte), mentre la chiesa pregava, ascoltava gli apostoli, aveva comunione <?bd("At2:44-45")?>, e testimoniava (At 3-6). Stefano fu ucciso per la sua testimonianza, con l'approvazione di Paolo (At 7), e si scaten&ograve; una grande persecuzione contro la chiesa. Cos&igrave; i Cristiani si dispersero <b>nella Giudea e nella Samaria</b>, e la seconda fase della testimonianza inizi&ograve;, cio&egrave; in quella regione (At 8). Mentre Paolo andava a Damasco per arrestare i Cristiani l&igrave;, Ges&ugrave; gli apparve e gli diede il compito di portare il suo nome davanti ai popoli, cio&egrave;, a tutte le nazioni oltre ai Giudei (At 9; 22:15,21; 26:17-18) <?bd("At22:10")?>. Poi Dio apparve a Pietro e ad un centurione romano chiamato Cornelio affinch&eacute; Pietro gli annunciasse il Vangelo, nonostante il fatto che non era lecito ad un Giudeo aver relazioni con un non Giudeo o di entrare in casa sua. Quando anche Cornelio ricevette lo Spirito Santo, Pietro cap&igrave; che Dio aveva concesso il ravvedimento anche ai non Giudei affinch&eacute; avessero la vita, adempiendo cos&igrave; le promesse dell'Antico Testamento, anche se Pietro doveva ancora convincere gli altri Cristiani di questo fatto (At 10-11; 15).</p>
<p>La terza fase, di essere testimoni <b>fino all'estremit&agrave; della terra</b>, ebbe il suo inizio con Cornelio, ma in realt&agrave; cominci&ograve; a succedere con i viaggi di Paolo. Per il suo <b>primo viaggio missionario</b>, Paolo fu mandato dallo Spirito Santo da Antiochia a Cipro e al sud-est della odierna Turchia (At 13-14). Di solito predic&ograve; prima ai Giudei (alla sinagoga quando c'era), ma quando i Giudei respinsero il Vangelo si rivolse ai non Giudei, come era il proposito di Dio (per esempio At 13:45-48). La lettera ai <i>Galati</i> fu forse scritta dopo il ritorno da questo viaggio, alle chiese fondate in quel viaggio, ma forse fu scritta qualche anno pi&ugrave; tardi. Per il <b>secondo viaggio,</b> Paolo ritorn&ograve; al sud-est della Turchia per rafforzare le chiese, poi prosegu&igrave; verso il nord-ovest della Turchia, dove in una visione Dio gli disse di andare in Europa. Cos&igrave; Paolo pass&ograve; per tutta la Grecia predicando e fondando chiese, prima di ritornare ad Antiochia (At 16-18). Durante questo viaggio, scrisse le lettere <i>1Tessalonicesi</i> e <i>2Tessalonicesi</i>. Per il <b>terzo viaggio,</b> percorse la Turchia fino ad Efeso, nel sud-ovest, dove rimase per due anni, scrivendo <i>1Corinzi</i> e <i>2Corinzi</i>. Poi and&ograve; nella Grecia, dove scrisse la lettera ai <i>Romani,</i> prima di ritornare e andare a Gerusalemme, dove fu arrestato (At 19-21). Quando cerc&ograve; di difendersi davanti ai Giudei, lo ascoltarono fino a quando rifer&igrave; che Ges&ugrave; gli aveva detto, "Io ti mander&ograve; lontano, tra i popoli" - era questo rifiuto da parte dei Giudei di adempire la benedizione promessa ad Abraamo che port&ograve; alla nascita della chiesa come popolo di Dio (At 22). Poi Paolo si difese davanti al sinedrio (At 23) e al governatore romano, che lo lasci&ograve; in prigione per due anni (At 24). In seguito, Paolo si difese davanti al nuovo governatore, quando si appell&ograve; a Cesare, e poi al re Agrippa (At 25-26). Fu portato quindi come prigioniero a Roma, incluso qualche mese a Malta quando la nave che lo portava naufrag&ograve; (At 27-28). Il libro conclude con Paolo agli arresti domiciliari <b>a Roma</b> per due anni, proclamando il regno di Dio con tutta franchezza e senza impedimento (At 28:30-31). Mentre era incarcerato, scrisse <i>Efesini,</i> <i>Filippesi,</i> <i>Colossesi,</i> <i>Filemone,</i> e pi&ugrave; tardi <i>1Timoteo,</i> <i>Tito,</i> e <i>2Timoteo</i>. Il Vangelo non era giunto fino all'estremit&agrave; della terra come noi la conosciamo, n&eacute; tutti i popoli che noi conosciamo furono benedetti, ma l'era degli apostoli era conclusa dopo che lo Spirito Santo aveva fatto tutto quello che era necessario in quella generazione. La storia continua da 2000 anni con la chiesa che porta la testimonianza in tutta la terra e a tutti i popoli.</p>
<p>Altre lettere che sono nel Nuovo Testamento furono scritte da altri apostoli (<i>1Pietro,</i> <i>2Pietro,</i> <i>1Giovanni</i>, <i>2Giovanni,</i> <i>3Giovanni</i>) e due fratelli di Ges&ugrave; (<i>Giacomo,</i> <i>Giuda</i>). C'&egrave; anche la lettera agli <i>Ebrei,</i> di cui non sappiamo con certezza l'autore. &Egrave; pi&ugrave; difficile dare una data e un luogo a queste lettere, perch&eacute; non abbiamo la storia dei viaggi di queste persone come abbiamo per Paolo.</p>
<p>&nbsp;</p>
<p>In realt&agrave;, il popolo, il luogo, e il regno di Dio rimangono Ges&ugrave;, sia nel periodo di Atti e delle lettere, sia adesso. Per&ograve; i Cristiani, essendo uniti a Cristo e in Cristo (sia individualmente sia collettivamente come la chiesa), ereditano alcune caratteristiche di Ges&ugrave;. In modo particolare, la chiesa prende le caratteristiche di Israele come <b>popolo di Dio</b> (Gal 3:29; 6:16; Giac 1:1; 1P 2:9 citando Es 19:6). Come abbiamo visto nello <a href="regni.php">studio 10</a>, Dio dimora in ogni Cristiano, nella chiesa locale, e nella chiesa universale. Dio dimora in Ges&ugrave; e Ges&ugrave; nei Cristiani tramite lo Spirito (Gv 14:10-11,17-20; 15:1-11), e in questo modo i Cristiani diventano il <b>luogo di Dio</b>. Infine, il <b>regno di Dio</b> &egrave; dove Dio regna e mostra il suo regno. Questo succederebbe nella chiesa ideale - fino a quando la chiesa sar&agrave; perfezionata al ritorno di Cristo il vero regno rimane solo Ges&ugrave; - ma il ruolo della chiesa &egrave; sempre di proclamare Dio e il suo regno a tutto e a tutti (Ef 3:10-11; Rom 14:17; 1Cor 4:20).</p>

<table border="1" style="border-collapse: collapse;">
<tr><td></td><th>Il popolo di Dio</th><th>Il luogo di Dio</th><th>Il regno di Dio</th></tr>
<tr><td>Genesi 1-2</td><td>Adamo e Eva</td><td>Il giardino</td><td>Dio parla</td></tr>
<tr><td>Genesi 3-6</td><td colspan="3" style="text-align: center;">Un regno umano in opposizione a Dio</td></tr>
<tr><td>Genesi 6-9</td><td>No&egrave; e famiglia</td><td>L'arca, terra restaurata</td><td>La parola, patto di Dio</td></tr>
<tr><td>Genesi 10-11</td><td colspan="3" style="text-align: center;">Confusione, nessun regno</td></tr>
<tr><td>Genesi 12-50</td><td>Abraamo e discendenti</td><td>Il paese (Canaan)</td><td>Patto</td></tr>
<tr><td>Esodo 1-15</td><td>Israele</td><td>Temporaneamente fuori</td><td>Segni miracolosi</td></tr>
<tr><td>Esodo 16-Deuteronomio</td><td>Israele</td><td>Sinai, tabernacolo</td><td>Legge</td></tr>
<tr><td>Giosu&egrave;</td><td>Israele</td><td>Canaan</td><td>Legge, combattimento</td></tr>
<tr><td>Giudici-Rut</td><td>Israele</td><td>Canaan</td><td>Legge, giudici (persone scelte con lo Spirito)</td></tr>
<tr><td>1,2Samuele, 1Cron</td><td>Israele -> Re davidico</td><td>Canaan -> tempio</td><td>Re ubbidiente alla legge</td></tr>
<tr><td>1,2Re, 2Cron</td><td>Israele -> Giuda -> Re</td><td>Tempio</td><td>Re ubbidiente alla legge</td></tr>
<tr><td>Profeti</td><td>Nuovo Israele (Messia, resto)</td><td>Nuova creazione, nuovo tempio</td><td>Dio, Messia</td></tr>
<tr><td>Salmi</td><td colspan="3" style="text-align: center;">L'aspetto interiore del rapporto con Dio</td></tr>
<tr><td>Giobbe, Prov, Ecc, Cant</td><td colspan="3" style="text-align: center;">Ordine e disordine in questa creazione, quindi saggezza</td></tr>
<tr><td>Daniele, Ezech, Ester</td><td>Il resto</td><td>Dappertutto</td><td>Vita quotidiana</td></tr>
<tr><td>Esdra-Neemia, Aggeo</td><td>Giuda ma...<br />Nuovo Israele</td><td>Tempio ma...<br />Nuova Gerusalemme</td><td>Legge ma...<br />Dio</td></tr>
<tr><td>Apocrifa</td><td colspan="3" style="text-align: center;">Dio prepara</td></tr>
<tr><td>Vangeli</td><td>Ges&ugrave;</td><td>Ges&ugrave;</td><td>Ges&ugrave;</td></tr>
<tr><td>Atti e Lettere</td><td>Chiesa</td><td>Chiesa</td><td>Chiesa</td></tr>
</table>

<h2>Nella Bibbia: Onore</h2>
<p>Un tema molto importante nella Bibbia &egrave; quello dell'onore e della vergogna. Come vedremo, erano concetti fondamenti per le culture della Bibbia, e quindi le verit&agrave; nella Bibbia vengono espresse usando queste idee. Siccome le culture della Bibbia non sono le nostre culture, a volte non cogliamo bene quello che gli scrittori dicono. Per questo motivo, dobbiamo prima di tutto capire le diverse culture e il significato di onore e vergogna in quelle culture, e poi vedremo come l'onore e la vergogna sono usati nella Bibbia.</p>
<h3>Onore nella societ&agrave;</h3>
<p>Ci sono diversi tipi di cultura, e diversi modi per descriverle. Un modo per categorizzare le culture &egrave; in base al metodo che le persone di quella cultura usano per decidere quello che devono fare e non fare.</p>
<p><i>Giustizia/colpevolezza:</i> Esiste un codice che conosco che mi dice quello che &egrave; giusto. Questo codice &egrave; esterno a me e condiviso dagli altri nella societ&agrave;. Per esempio, potrebbe essere la legge del paese, oppure il comportamento imposto dalla religione. Questo &egrave; tipicamente la cultura del nord Europa e degli Stati Uniti, dove la Riforma protestante (con la sua enfasi sulla colpa e sul perdono individuale) ha avuto un forte effetto per cambiare la cultura.</p>
<p><i>Paura:</i> Ci sono conseguenze per le mie azioni, e non faccio certe cose per paura della punizione, a prescindere dal fatto che penso che siano giuste o sbagliate. I paesi dittatoriali sono spesso cos&igrave;. Anche in alcune tribù, dove c'&egrave; la paura degli spiriti o degli antenati.</p>
<p><i>Onore/vergogna:</i> Faccio quello che mi porta onore e non vergogna secondo gli altri nella societ&agrave;, e non secondo me. Un modo importante per ottenere onore &egrave; essere un benefattore (nella letteratura inglese su questo tema: patron). Un benefattore &egrave; qualcuno che ha qualcosa in eccesso e che d&agrave; liberamente, con grazia, e non necessariamente in modo equo. Un esempio nella Bibbia &egrave; il padrone nella parabola degli operai di diverse ore (Mt 20:1-16), e uno che non lo fa &egrave; il ricco che costruisce pi&ugrave; granai invece di aiutare altri (Lu 12:15-21). Quelli che ricevono dal benefattore sono i suoi clienti. I clienti "pagano" il benefattore restituendo onore. Quindi una descrizione pi&ugrave; precisa &egrave; che in una cultura di onore, faccio quello che porta onore a me, al benefattore, e al gruppo del benefattore composto da tutti i suoi clienti. La vergogna pu&ograve; essere ottenuta quando il mio comportamento (che forse &egrave; contro i valori della societ&agrave;, &egrave; sbagliato, o &egrave; sciocco) diventa pubblico e gli altri mi disprezzano. Anche il comportamento di altri nel mio gruppo pu&ograve; portarmi vergogna, per esempio il comportamento di un figlio pu&ograve; dare vergogna ai genitori e a tutta la famiglia. Questa &egrave; di solito la cultura dei paesi arabi e asiatici, che ha conseguenze importanti per il nostro rapporto con profughi da questi paesi, e la nostra testimonianza a persone di altre religioni.</p>
<p></p>
<p>In Italia, la situazione &egrave; interessante. Anche i paesi mediterranei in generale hanno una cultura di onore/vergogna, e cos&igrave; tradizionalmente anche Italia. Possiamo pensare al concetto di "bella figura" - quello che &egrave; importante &egrave; come appaiamo agli altri, non quello che c'&egrave; dentro oltre alla figura. Le raccomandazioni funzionano solo in una cultura di onore con benefattore e clienti. Purtroppo, la manifestazione pi&ugrave; chiara di questa cultura &egrave; nella mafia: delle persone che formano un gruppo per proteggersi, di cui il capo funziona come benefattore agli altri. Se tocchi qualcuno del clan, disonori tutti. Per&ograve;, nel nord d'Italia c'era l'influenza delle culture della colpevolezza, e si potevano vedere alcune differenze fra il nord e il sud per quanto riguardo il tipo di cultura. Pi&ugrave; recentemente, anche la globalizzazione ha mescolato le culture, e quello che Italia ha importato dagli Stati uniti (per esempio la musica, i film, i modelli di business, la filosofia academica) ha portato anche ad una parziale trasformazione della cultura verso la colpevolezza. Negli ultimi anni, la societ&agrave; occidentale ha fatto un salto verso una cultura di fama/vergogna. Il giusto e lo sbagliato hanno molto meno importanza adesso, con l'effetto del postmodernismo. Quello che &egrave; importante &egrave; essere conosciuti, meglio ancora una celebrit&agrave;. Seguiamo persone normali che riescono a farsi vedere ad un grosso pubblico. Cos&igrave; la televisione &egrave; piena di programmi di reality, e almeno i giovani sono alla caccia di like sui social media. Per&ograve; i social rende ancora pi&ugrave; facile vergognare qualcuno. Anche questo ha conseguenze importanti per la nostra testimonianza agli Italiani, soprattutto ai giovani.</p>
<p></p>
<p>Tutte le culture della Bibbia (principalmente ebraica e greco-romana, ma anche egiziana, babilonese, e cos&igrave; via) erano del tipo onore-vergogna. Per questo motivo la Bibbia parla tre volte di pi&ugrave; dell'onore e della vergogna che della giustizia e della colpevolezza. Per&ograve; spesso i nostri schemi mentali non trovano posto per l'insegnamento sull'onore, e trascuriamo quei brani. Lo scopo in questo studio &egrave; di spiegare solo un po' come la Bibbia usa i concetti dell'onore e della vergogna per interpretare quello che succede, affinch&eacute; tu possa trovare questi concetti pi&ugrave; spesso mentre leggi la Bibbia.</p>

<h3>Onore nell'Antico Testamento</h3>
<p>Dopo che Adamo ed Eva mangiarono il frutto della conoscenza del bene e del male e si resero conto di quelli che avevano fatto (Gen 3:7-10), come si sentirono? Quello che &egrave; detto esplicitamente &egrave; che avevano paura (Gen 3:10), cio&egrave; delle conseguenze delle loro azioni. Siccome prima non avevano vergogna quando erano nudi (Gen 2:25), e dopo si nascosero perch&eacute; erano nudi (Gen 3:7), possiamo supporre che si sentivano anche vergognati. Quello che non &egrave; detto &egrave; che si sentivano colpevoli, anche se era una trasgressione contro il comando di Dio che port&ograve; ad una condanna (Gen 3:11; Rom 5:18). Quello che &egrave; chiaro &egrave; che era il peccato che era il problema. Per&ograve;, il peccato porta molte conseguenze, non solo la colpevolezza verso Dio, ma anche la vergogna verso Dio, la paura verso Dio, e la separazione da Dio (come abbiamo visto nello <a href="dio_con_noi.php">studio precedente</a>).</p>
<p>Quello che Ges&ugrave; ha fatto per noi era togliere tutti gli effetti del peccato: non solo la nostra colpa, ma anche la nostra vergogna (come sar&agrave; spiegato nella prossima sezione), la nostra paura, e la nostra separazione. In molti ambienti cristiani, si &egrave; abituati a parlare solo della colpevolezza che Ges&ugrave; ci ha tolto facendoci perdonare. In realt&agrave;, la sua opera &egrave; molto pi&ugrave; profonda (e meravigliosa!) di questo, e dobbiamo parlare di <b>tutto</b> quello che Ges&ugrave; ha compiuto per noi. Anche se &egrave; naturale sottolineare quegli aspetti che sono pi&ugrave; compresi nella nostra cultura - che con la base di una cultura mediterranea, e poi con gli immigranti e i giovani, forse dovrebbe essere l'onore e la vergogna pi&ugrave; di quanto ne parliamo abitualmente.</p>
<p>Nelle tabelle di ogni studio, c'&egrave; un riassunto di come Dio ha creato un suo popolo dove Dio regna e dimora. Per&ograve;, &egrave; possibile leggere la Bibbia in un modo complementare. Dio crea un nuovo popolo, di cui lui &egrave; il benefattore e le persone del popolo i suoi clienti. Dio liberamente d&agrave; al suo popolo, e il popolo d&agrave; gloria e onore a Dio, affinch&eacute; tutti gli altri vedano il grande onore di Dio.</p>
<p>Un esempio fra migliaia nell'Antico Testamento &egrave; il Salmo 44. Una lettura di questo salmo attraverso lo schema dell'onore &egrave;:<br />
<i>Sal 44:1-8</i> Dio, come benefattore, ha dato tante cose ad Israele nel passato, soprattutto la vittoria militare, e ha fatto vergognare chi era contro i suoi clienti. Per questo motivo Israele gli dar&agrave; sempre onore.<br />
<i>Sal 44:9-16</i> Per&ograve; adesso Dio fa vergognare Israele non proteggendolo, in modo che gli altri lo disonorino.<br />
<i>Sal 44:17-22</i> Israele &egrave; rimasto fedele, ed &egrave; quasi un'accusa per svergognare Dio.<br />
<i>Sal 44:23-26</i> Cos&igrave; il salmista chiede a Dio di guardare il disonore di Israele e di agire da benefattore liberandolo. Per&ograve; siccome il benefattore non &egrave; mai obbligato a fare qualcosa per i suoi clienti, il salmista chiede a Dio di agire nella sua bont&agrave; (Sal 44:26), cio&egrave; per la sua grazia.</p>

<h3>Onore e Ges&ugrave;</h3>
<p>Ges&ugrave;, durante la sua vita, fu disonorato e trattato in modo vergognoso. Fu insultato pubblicamente, per provare a disonorarlo: mangione, beone, blasfeme, uno che infrangeva il sabato, amico di pubblicani e peccatori. Dai suoi amici, fu tradito, rinnegato e abbandonato. Dalla sua famiglia fu considerato pazzo. Al suo processo gli sputarono adesso, lo schernirono, e gli misero una corona di spine. Ci furono altri tentavi (falliti) di togliergli l'onore, per esempio le domande per provarlo, che erano una sfida di cui il vincitore riceveva onore agli occhi di chi assisteva. Infine, mor&igrave; in un modo calcolato per massimizzare la vergogna di chi lo subiva - la crocifissione. Mor&igrave; come un criminale, nudo, e uno spettacolo pubblico.</p>
<p>Per&ograve; Ges&ugrave; disprezz&ograve; il disprezzo, l'infamia, la vergogna (Ebr 12:2). Poi il Padre lo risuscit&ograve;, e lo glorific&ograve; e lo onor&ograve; in cielo con lui (Ebr 12:2; 2:5-9; Fili 2:6-11). Essendo stato coperto di una vergogna che non era sua alla croce, poteva portare la nostra vergogna affinch&eacute; noi ne fossimo liberati. Soprattutto la vergogna che abbiamo verso Dio, perch&eacute; non lo trattiamo in modo onorevole e noi mostriamo il suo onore agli altri. Ges&ugrave; pu&ograve; anche portare via la vergogna che sentiamo verso gli altri. Probabilmente abbiamo fatto nel passato delle cose di cui ci vergogniamo, che non abbiamo mai raccontato a nessuno. Se ci uniamo a Cristo, se ci affidiamo a lui per avere onore, il suo onore che otteniamo essendo i suoi fratelli (siamo collegati dal fatto che abbiamo lo stesso benefattore) &egrave; pi&ugrave; grande di qualsiasi vergogna che possiamo sentire per quello che abbiamo fatto nel passato (Ebr 2:11; 11:16).</p>

<h3>Onore in Paolo</h3>
<p>Quando Paolo voleva che i Cristiani a cui scriveva si comportassero in un certo modo, disse (a volte) che erano vergognati piuttosto che avevano sbagliato (1Cor 11:4-6; 15:34; 2Te 3:14). Cio&egrave;, usava la terminologia attuale e il modo di pensare della cultura per ottenere un cambiamento nei lettori.</p>
<p>Per&ograve; pi&ugrave; spesso nelle sue lettere, Paolo rovesci&ograve; l'idea culturale della vergogna. Non us&ograve; i soliti termini per rapporti in associazioni o benefattore/clienti (membro, amico) per descrivere il suo rapporto con altri o i rapporti fra Cristiani, ma termini non gerarchici come fratello, collaboratore, e compagno. &Egrave; vero che Paolo avesse avuto un'autorit&agrave; apostolica che us&ograve; a volte, ma non era per il proprio onore. Noi, come Paolo, dobbiamo stimare gli altri migliori di noi invece di cercare una (vana)gloria (Fili 2:3). Non dobbiamo cercare il proprio onore, ma solo l'onore di Dio, il nostro grande benefattore.</p>
<p>Solo seguire Cristo invece di un benefattore umano dava il vero onore. Questo era il motivo per cui il messaggio del Vangelo era una vergogna nella cultura. Anche se il messaggio del Vangelo sembrava una vergogna, Paolo non se ne vergognava (Rom 1:16; 1Cor 1:23; 4:10; 2Cor 6:8).</p>
<p>Alla fine, Ges&ugrave; ritorner&agrave; e dar&agrave; l'onore a cui lo spetter&agrave; veramente, vedremo il vero onore e la vera vergogna di ogni persona come li vede Dio (1Cor 4:5).</p>

<h3>Onore in Ebrei</h3>
<p>In questa analisi della lettera agli Ebrei, seguo l'articolo di David A. Desilva, "Despising Shame: A Cultural-Anthropological Investigation of the Epistle to the Hebrews", Journal of Biblical Literature 113, no. 3 (1994): 439-461, che pu&ograve; essere letto a <a href="https://www.jstor.org/stable/3266781">https://www.jstor.org/stable/3266781</a> per un approfondimento.</p>
<p>La lettera agli Ebrei &egrave; piena di riferimenti ai concetti di onore e di vergogna, perch&eacute; sono fondamentali per il ragionamento dell'autore durante la sua esposizione. Lo possiamo riassumere in questo modo: i Cristiani che ricevettero la lettera avevano perso il loro onore quando si convertirono, ma allora desideravano nuovamente l'onore dalla societ&agrave;. Questo creava una tentazione di abbandonare il gruppo dei Cristiani. L'autore propose un sistema alternativo di onore, cio&egrave; di dimenticare la valutazione dell'onore da parte della societ&agrave; per ricevere un onore maggior da Dio.</p>
<h4>L'onore di Ges&ugrave;</h4>
<p>L'autore sottolinea lo stato esaltato di Ges&ugrave; Cristo, per ricordare il suo onore, nonostante il disonore durante la vita e morte di Ges&ugrave;. Ges&ugrave; &egrave; alla destra di Dio (Ebr 1:3; 8:1; 10:12; 12:2), coronato di gloria e di onore (Ebr 2:7,9), e sar&agrave; glorificato per sempre (Ebr 13:21). &Egrave; il Figlio e l'erede di tutte le cose (Ebr 1:2). &Egrave; superiore agli angeli (Ebr 1:4-2:9). &Egrave; superiore alle persone molto onorate come Mos&egrave; (Ebr 3:1-6, soprattutto Ebr 3:3), Melchisedec <?bd("Gen14:18-20")?> e i sommi sacerdoti (Ebr 5:1-10; 7:1-28, soprattutto Ebr 5:4-5). &Egrave; superiore ai suoi nemici (Ebr 1:13; 2:8; 10:13).</p>
<h4>Disprezzare la vergogna</h4>
<p>Disprezzare il disprezzo (o la vergogna o l'infamia) degli altri era impensabile in quella cultura. Per&ograve; era proprio quello che l'autore propose. Ges&ugrave; era il loro modello, che "per la gioia che gli era posta dinanzi sopport&ograve; la croce, disprezzando l'infamia, e si &egrave; seduto alla destra del trono di Dio" (Ebr 12:2). Non era che sopportasse la vergogna stoicamente o che fosse indifferente alla morte e alla vergogna. Piuttosto, disprezz&ograve; la vergogna (e l'onore) secondo l'opinione pubblica, perch&eacute; voleva l'onore secondo la valutazione di Dio ("per la gioia che gli era posta dinanzi"). Secondo la cultura, aveva una "sedia" vergognosa (la croce), ma in realt&agrave; aveva una sedia in un posto di onore "alla destra del trono di Dio".</p>
<p>Ci sono anche altri esempi di persone che disprezzarono il disprezzo, soprattutto in Ebr 11, il capitolo degli eroi della fede. Abraamo disprezz&ograve; lo stato basso di straniero e pellegrino (Ebr 11:8-13), perch&eacute; dimostrava di aver una patria migliore in cielo (Ebr 11:14-16; per i destinatari Ebr 13:13-14 &egrave; simile). Mos&egrave; rifiut&ograve; l'onore di essere della casa del faraone, perch&eacute; stimava il "disonore" (secondo gli Egiziani) del popolo di Dio maggior dell'"onore" di Egitto, anche se voleva dire essere maltrattato (Ebr 11:24-27; anche chi ricevette la lettera aveva sperimentato un simile maltrattamento Ebr 10:33-34 e doveva identificarsi con i maltrattati Ebr 13:3). Similmente, ci sono tanti esempi in Ebr 11:32-38 di persone che soffrirono come persone disonorate perch&eacute; sapevano di avere un onore migliore - di loro il mondo non era degno (Ebr 11:38), cio&egrave; aveva meno onore vero.</p>
<p>L'altro esempio di disprezzare il disprezzo era i destinatari stessi. L'autore li esort&ograve; a perseverare ricordando loro come avevano agito nel passato (Ebr 10:32-34).</p>
<h4>Disprezzare Dio</h4>
<p>La lettera contiene anche degli esempi negativi, di persone che disprezzarono Dio. Il primo era la generazione di Israeliti che gir&ograve; nel deserto per 40 anni (Ebr 3:7-4:11). Non credettero nella bont&agrave; e nella sufficienza di Dio come benefattore, provocando la sua ira. Esa&ugrave; invece scambi&ograve; la benedizione e la promessa eterne per una pietanza (Ebr 12:16-17) - il contrario degli esempi della sezione precedente che respinsero gli onori e i piaceri presenti per un onore maggior con Dio.</p>
<p>Negli avvertimenti ai destinatari, anche loro potevano essere un esempio negativo se stimassero l'onore della societ&agrave; pi&ugrave; dell'onore di Dio. Se disonorassero Cristo, sarebbe stato impossibile ricondurli al ravvedimento (Ebr 6:6; 10:29) <?bd("Ebr6:4-6")?>.</p>
<h4>Come essere onorati</h4>
<p>Con questo insegnamento come base, l'autore esorta i suoi lettori a interpretare il disonore del mondo come segno di onore agli occhi di Dio. Come avevano fatto nel passato (Ebr 10:32-34), dovevano continuare con costanza non tirandosi indietro (Ebr 10:35-39,23). Dovevano non abbandonare la comunit&agrave; cristiana, ma continuare ad aiutare gli altri a perseverare nella fede (Ebr 10:24-25). Dovevano fissare lo sguardo su Ges&ugrave;, che disprezz&ograve; l'infamia, per non stancarsi durante l'ostilit&agrave; dei non Cristiani e nella lotta contro il peccato (Ebr 12:2-4). Perch&eacute; erano dello stesso "clan" di Cristo, della casa di Dio (Ebr 3:6), partecipi di Cristo (Ebr 3:14), e Ges&ugrave; non si vergognava di chiamarli fratelli (Ebr 2:11). Il loro destino, quindi, era la gloria (Ebr 2:10). Con questa convinzione, dovevano identificarsi con i disonorati (Ebr 13:3), anche se voleva dire prendere il loro disonore, e dovevano onorare il matrimonio (Ebr 13:4) anche se non era (come non lo &egrave; neanche adesso) una norma della societ&agrave;.</p>
<p>Quello che l'autore disse ai destinatari, lo dice anche ai noi. Quale onore vogliamo e cerchiamo?</p>

<h2>Domande</h2>
<p>1. Nei discorsi di Pietro e Paolo in At 2:14-40 e At 13:16-41, come &egrave; presentato Ges&ugrave; Cristo come l'adempimento delle promesse di Dio?</p>

<p>2. Come vedi onore e vergogna, benefattori e clienti, manifestarsi nella cultura in cui vivi?</p>

<p>3. Nel tuo cammino con Dio, che cosa ti motiva di pi&ugrave; per fare quello che Dio vuole: la paura della punizione, la conoscenza di ci&ograve; che &egrave; giusto, il desiderare di trattare Dio come Dio, o altro?</p>

<p>4. Scrivi un piccolo discorso, con riferimenti biblici appropriati, per spiegare il Vangelo, cio&egrave; come qualcuno pu&ograve; ottenere un rapporto con Dio, a qualcuno che non crede che il giusto e lo sbagliato esistano, ma che &egrave; molto preoccupato/a riguardo a quello che gli altri pensano di lui o lei.</p>

<p>5. Leggi la lettera agli Efesini, e cerca i versetti che parlano di grazia, misericordia, supplica, benedizione, bont&agrave;, gloria, lode, vanto, ricchezza, onore, vergogna, sconvenienza, servi di Dio, e cos&igrave; via. Non solo i versetti che usano queste parole, ma anche quelli che parlano di questi concetti con altre parole, per esempio Cristo fu onorato quando il Padre lo fece sedere alla sua destra nel cielo al di sopra di ogni altra cosa (Ef 1:20-22). Riassumi il ragionamento della lettera in questi termini. Che cosa aggiunge alla spiegazione qui sopra di onore e vergogna nella Bibbia?</p>

<?
$n=18;
require("indice.php");
require("../piede.php");
?>
