<?
include("../conn.php");
include("../vistesto.php");

$descriz = "La creazione (Genesi 1-2); una parte di una panoramica della Bibbia";
$key = "creazione, genesi, panoramica, storia, racconto";
$titolo = "La creazione (Genesi 1-2)";
$sezione = "Strumenti";
require("../capo.php");
?>
<h1>1. La creazione (Genesi 1-2)</h1>
<h2>La creazione (Gen 1:1-2:3)</h2>
<p class="primalettera">Nel principio <strong>Dio cre&ograve; tutto</strong> (Gen 1:1). Prima non c'era niente di materiale, e poi ci fu (Ebr 11:3). Questo fatto ci dice che la creazione e la storia non sono ciclici, come alcune filosofie e religioni insegnano. Invece c'&egrave; un inizio, che suggerisce un motivo o proposito per questo inizio, e una storia lineare.</p>
<p>Il mezzo della creazione &egrave; il <strong>decreto verbale di Dio</strong>. Dio disse che ci fosse qualcosa, e quella cosa fu. A questo punto nella rivelazione, vuol dire che Dio aveva autorit&agrave; su tutto, anche su quello che non esisteva. Gli bastava parlare per esprimere la sua volont&agrave;, e quello che voleva cominci&ograve; ad esistere (Sal 33:6,9). Poi nel Nuovo Testamento, la parola che era il comando di Dio, viene spiegata come il Figlio, Ges&ugrave; Cristo - ogni cosa &egrave; stata fatta per mezzo di lui, e in lui sono state create tutte le cose (Gv 1:3; Col 1:16). Non solo, Ges&ugrave; anche sostiene tutte le cose con la sua parola (Ebr 1:3; 2P 3:5-7). Se Ges&ugrave; fosse disattento per solo un attimo, noi e tutto quello che vediamo scompariremmo!</p>
<p>La creazione ci insegna anche molte qualit&agrave; di Dio, per esempio la sua <strong>potenza, sovranit&agrave;, unicit&agrave;, e trascendenza</strong> (Sal 19:1; Rom 1:20). Quando guardiamo intorno a noi, vediamo le sue opere grandissime e meravigliose nella natura. Quando guardiamo in su, possiamo vedere (nelle migliori condizioni atmosferiche) migliaia di stelle. Per&ograve; questo &egrave; solo nel nostro "quartiere" della nostra galassia - gli astronomi stimano che in tutte le galassie ci siano un quadrilione di stelle, cio&egrave; uno e poi 24 zeri. All'incirca il numero di granelli di sabbia in tutte le spiagge del mondo. Non solo Dio le ha create, ma le conta e le chiama tutte per nome (Sal 147:4). Siccome Dio ha creato tutte queste cose, e per la sua volont&agrave; furono create ed esistono, &egrave; degno di ricevere la gloria, l'onore e la potenza (Ap 4:11), e la nostra risposta deve essere di adorarlo sempre e per sempre.</p>
<p>Quello che questi capitoli sottolineano della creazione &egrave; <strong>la separazione e la struttura</strong>, il movimento dal caos all'ordine. All'inizio della creazione, non aveva n&eacute; forma n&eacute; contenuto (Gen 1:2). Poi nei primi tre giorni Dio cre&ograve; struttura o forma, separando la luce dalle tenebre, le acque di sotto il cielo dalle acque di sopra, e i mari dalla terraferma (Gen 1:4,7,9). Cos&igrave; la creazione non era pi&ugrave; informe. Dal quarto al sesto giorno, Dio riemp&igrave; la struttura: mise le stelle, il sole e la luna nel cielo, i pesci nel mare e gli uccelli nel cielo, e gli animali e umani sulla terra (Gen 1:17,20,24,27). I pesci, gli uccelli e gli animali ricevettero il comando esplicito di riempire il proprio ambiente (Gen 1:22,28). Cos&igrave; la terra non era pi&ugrave; vuota.</p>
<p>Un'altra caratteristica della creazione &egrave; che &egrave; <strong>buona</strong>. Sei volte Dio vide che quello che aveva fatto era buono (Gen 1:4,10,12,18,21,25), e alla fine della creazione afferm&ograve; che tutto quello che aveva fatto era molto buono (Gen 1:31). L'unica eccezione alla bont&agrave; della creazione era che non era bene che l'uomo fosse solo (Gen 2:18), un fatto di cui parleremo nella prossima sezione. Un'osservazione importante a questo punto &egrave; che non c'&egrave; uno standard esterno con cui Dio misur&ograve; la bont&agrave; della sua creazione. Ci&ograve; renderebbe Dio non sovrano e non supremo su tutto, perch&eacute; ci sarebbe un principio ("la bont&agrave;") a cui Dio si sarebbe dovuto sottomettere, con cui avrebbe dovuto misurare la sua creazione. Invece, una cosa &egrave; buona nella misura in cui riflette la natura di Dio. Dio definisce il buono, non perch&eacute; decide in modo arbitrario quello che &egrave; buono o cattivo, ma perch&eacute; Dio &egrave; buono e quello che dimostra la grandezza e la perfezione di Dio &egrave; quindi buono. Per quanto riguardo la creazione, capiamo quindi che la struttura e l'attivit&agrave; del paragrafo precedente sono buone, perch&eacute; riflettono il carattere di Dio - non &egrave; un Dio capriccioso o caotico, ma fa le cose con un suo ordine. Inoltre, tutto il creato lavorava insieme in modo armonioso, con rapporti giusti fra i diversi elementi, come vedremo nella prossima sezione. Dio era preminente in questi rapporti, come era giusto, e anche in questo modo la creazione era buona.</p>
<p>L'ultimo elemento della creazione era il <strong>riposo</strong>. Dopo che comp&igrave; la creazione dell'universo, si ripos&ograve; il settimo giorno da tutta l'opera che aveva creata (Gen 2:2-3). Il significato di questo riposo in tutta la Bibbia sar&agrave; spiegato nello <a href="conquista.php">studio 7 di questo testo</a>.</p>
<h2>I rapporti giusti dell'uomo (Gen 1:26-31; 2:7-25)</h2>
<p>L'uomo &egrave; il pinnacolo della creazione. Questo &egrave; visto non solo dall'ordine del racconto in Gen 1 (in cui l'uomo &egrave; l'ultima cosa creata) e dallo spazio dedicato all'uomo in Gen 2, ma dai rapporti dell'uomo con Dio e con il resto della creazione.</p>
<h3>Con Dio</h3>
<p>La prima caratteristica descritta dell'uomo &egrave; che fu creato a <strong>immagine di Dio</strong> (Gen 1:26-27; 5:2). <?bd("Gen1:26-27")?> C'&egrave; molta discussione sul senso preciso di questo termine, ma &egrave; probabilmente meglio capirlo nel senso "come immagine di Dio". Infatti, il termine &egrave; approfondito in Gen 1:26 con due altre frasi, "conforme alla nostra somiglianza" e "avere dominio" su tutti gli animali. L'uomo ricevette alcuni aspetti di Dio, che potevano essere visualizzati da altri. Gli unici "altri" a questo punto erano gli animali, per cui l'uomo doveva mostrare l'autorit&agrave; di Dio agli animali; in altre parole, l'uomo ebbe dominio su di essi. Era una sorte di vicer&eacute; di Dio, governando il creato per lui. Ci sar&agrave; un approfondimento sull'utilizzo del termine "immagine di Dio" in tutta la Bibbia nelle domande per la riflessione.</p>
<p>Poi Dio <strong>benedisse</strong> l'uomo e la donna (Gen 1:28; 5:1). Non &egrave; una caratteristica solo dell'umanit&agrave;, ma anche dei pesci e degli uccelli (Gen 1:22). Vuol dire che Dio vuole bene alle persone, ma anche che &egrave; superiore perch&eacute; &egrave; in grado in benedirle.</p>
<p>Dio anche <strong>comand&ograve;</strong> l'uomo e la donna, dett&ograve; quello che potevano e non potevano fare (Gen 1:28-30; 2:16-17). Di nuovo, dimostra la sua autorit&agrave; sulla sua creatura.</p>
<h3>Con la creazione</h3>
<p>All'uomo fu dato il <strong>dominio</strong> sugli animali (Gen 1:26,28; Sal 8:6-8), con il compito di <strong>lavorare e custodire</strong> il giardino di Eden (Gen 2:15). <?bd("Gen1:28")?> Questo "dominio" non era nel senso di dominare, per sfruttare per trarne il proprio vantaggio. Piuttosto era governare e avere autorit&agrave;, un'autorit&agrave; manifestata nel fatto che l'uomo diede i nomi agli animali (Gen 2:19). Come immagine di Dio, l'uomo doveva riflettere la natura di Dio agli animali, che vuol dire avere autorit&agrave; sopra di essi, ma un'autorit&agrave; esercitata per fare il bene agli animali e benedirli. Questo tipo di autorit&agrave; era visto nel giardino, dove l'uomo prendeva cura delle piante. Come Dio oper&ograve; nella creazione, cos&igrave; anche l'uomo lavor&ograve; nel paradiso di Eden - ma era un lavoro piacevole senza le difficolt&agrave; che vedremo nel <a href="caduta.php">prossimo studio</a>.</p>
<p>All'uomo fu dato il comando anche di <strong>riempire la terra e rendersela soggetta</strong> (Gen 1:28). Questo &egrave; simile al paragrafo precedente, e infatti sono insieme nel versetto Gen 1:28. L'idea non &egrave; di rendere la terra soggetta affinch&eacute; possiamo farne quello che vogliamo, riempiendola per sfruttare ancora di pi&ugrave; della terra, ma di renderla soggetta alla nostra cura, lavorando e custodendo tutta la terra. Solo in quel modo l'umanit&agrave; sar&agrave; l'immagine di Dio, sar&agrave; come Dio alla terra, quando la trattiamo come Dio la tratterebbe.</p>
<p>Anche se l'uomo ha uno stato privilegiato nella creazione, rimane <strong>una parte della creazione</strong> e cos&igrave; una creatura di Dio, completamente dipendente da Dio per tutto. Infatti, in Gen 2:7 Dio form&ograve; l'uomo dalla polvere della terra (siamo una parte della creazione; vedi anche Gen 3:19), e Dio gli soffi&ograve; nelle narici un alito vitale affinch&eacute; diventasse un'anima vivente (dipendiamo da Dio - la vita viene da Dio).</p>
<h3>Con altri</h3>
<p>L'unica cosa non buona nella creazione era che <strong>l'uomo era solo</strong> (Gen 2:18). Dio &egrave; un Dio con rapporti, sia con s&eacute; stesso (anche se questa caratteristica non &egrave; ancora spiegata a questo punto della Bibbia) sia con altri esseri (Gen 1:26). L'uomo, in quanto l'immagine di Dio, dovrebbe avere dei rapporti. Fu creato per avere rapporti non solo con Dio e con la creazione, ma con i suoi simili. Quindi Dio form&ograve; dall'uomo (non dalla polvere) una donna (Gen 2:21-22). La distinzione fondamentale nell'umanit&agrave; e che Dio la cre&ograve; <strong>maschio e femmina</strong> (Gen 1:27; 5:1). Il rapporto fondamentale &egrave; quando l'uomo lascia la sua famiglia per unirsi alla moglie diventando una stessa carne (Gen 2:24). <?bd("Gen2:18-23")?></p>
<h2>Nella Bibbia: La creazione</h2>
<p>In questa sezione (e in simili sezioni negli altri studi), esamineremo un tema che viene sviluppato nella Bibbia. Perch&eacute; la Bibbia contiene una rivelazione progressiva: non tutto &egrave; rivelato subito all'inizio, ma di solito c'&egrave; una spiegazione generale iniziale, che viene approfondita nel corso della storia, e soprattutto dalla rivelazione di Ges&ugrave; Cristo. Spesso ci sar&agrave; un commento molto sintetico. Bisogna leggere i brani biblici per capire esattamente quello che viene insegnato. Inoltre, molte volte gli studi successivi spiegheranno quello che &egrave; detto qui in poche parole.</p>
<p>&nbsp;</p>
<p>La prima creazione era molto buona (Gen 1:31). Per&ograve;, a causa del peccato dell'uomo, venne maledetta e corrotta, e ora aspetta la liberazione (Gen 3:17-19; Rom 8:19-23). Dopo il diluvio, ci fu una nuova creazione simile alla prima, come se fosse una ripartenza (Gen 8:15-19; 9:1-7). Ma di nuovo il peccato rovin&ograve; la creazione. Dopo la creazione della nazione di Israele come popolo di Dio, Dio promise di portare il popolo ad un paese paradisiaco, un "buon" paese (Dt 8:6-10). Sempre a causa del peccato, questa volta degli Israeliti che dimenticarono Dio, il paese risult&ograve; non cos&igrave; perfetto come fu promesso. Cos&igrave; i profeti cominciarono a promettere un nuovo paradiso, una pace futura e il restauro di Israele (Is 11:1-10; 51:3; 65:17-25; Ez 36:33-36).</p>
<p>Quando Ges&ugrave; venne, ebbe dominio sulla creazione e mostr&ograve; di aver autorit&agrave; su tutte le maledizioni - la natura, il diavolo, la malattia e la morte (Mc 4:35-5:43) - perch&eacute; &egrave; il capo della creazione (Col 1:16-17). In un certo senso, Cristo &egrave; l'inizio di una nuova creazione (1Cor 15:42-49). Cos&igrave; quelli che sono in Cristo diventano nuove creature, una parte della nuova creazione (2Cor 5:17; Gal 6:15). Noi viviamo in un'epoca di sovrapposizione fra la vecchia creazione e la nuova creazione.</p>
<p>Per&ograve; nel futuro, al giorno del Signore, la creazione si dissolver&agrave; e ci sar&agrave; una nuova creazione di giustizia (2P 3:10-13), una nuova creazione perfetta (Ap 21:1-8; 22:1-5).</p>
<h2>Domande</h2>
<p>1. Adoriamo Dio quando osserviamo la grandezza e la bont&agrave; della creazione? Come possiamo creare questa abitudine?</p>

<p>2. In quale misura quello che facciamo (al posto di lavoro, in casa, nei luoghi pubblici con altri) &egrave; per custodire la creazione? Come pu&ograve; cambiare il nostro atteggiamento quando ci rendiamo conto che anche i lavori banali o noiosi fanno parte dal compito affidatoci da Dio per servire la sua creazione?</p>

<p>3. Il matrimonio &egrave; il rapporto fondamentale dell'umanit&agrave;. Come l'immagine di Dio, riflette anche alcuni rapporti che ha Dio (in modo particolare, Cristo). Secondo Ef 5:22-33, cosa ci insegna il rapporto ideale di Dio (cio&egrave; Cristo con la sua sposta, la Chiesa)?</p>

<p>4. Come abbiamo seguito il tema della creazione nella Bibbia (e seguiremo molti altri temi negli altri studi), nello stesso modo seguirai il tema dell'immagine di Dio nella Bibbia.<br />
a) Che cosa impariamo dell'immagine di Dio in Gen 1:26-28?<br />
b) Quali sono le conseguenze in Gen 9:6; Giac 3:8-10?<br />
c) Chi &egrave; l'immagine di Dio in 2Cor 4:3-4; Col 1:15? Qual &egrave; il rapporto con l'immagine di Dio in Gen 1:26?<br />
d) Quale cambiamento ci sar&agrave; secondo Rom 8:29; 1Cor 15:42-49; 2Cor 3:18? Quando?<br />
e) Quindi che cosa dobbiamo fare adesso secondo Ef 4:21-24; Col 3:9-10? Che cosa dovresti cambiare adesso per fare questo? Ef 4:25-32 e Col 3:5-8 danno alcuni suggerimenti.</p>

<?
$n=1;
require("indice.php");
require("../piede.php");
?>
