<?
$descriz = "Assistente: uno dei Racconti della Giustizia";
$key = "assistente, racconti della giustizia";
$titolo = "Assistente";
$sezione = "Strumenti";
$sezioneurl = "/racconti_giustizia/";
require("../capo.php");
?>
<h1>Assistente</h1>
<p>L'assistente si avvicinava alla citt&agrave; troppo rapidamente. Il rientro nell'atmosfera era difficilissimo. Faceva caldo, troppo caldo, e sudava tanto. Ce la far&agrave;? Guard&ograve; fuori della finestra, e vide vari pezzi staccarsi dall'ala dell'astronave, e il metallo rovente per il calore. Le difese automatiche della citt&agrave;, vedendo l'astronave avvicinarsi pericolosamente veloce, iniziarono a sparare. L'assistente, che gi&agrave; tirava la cloche indietro con tutti i suoi sforzi, dovette anche girarla a sinistra e a destra per evitare i colpi. Si gir&ograve; verso la co-pilota alla sua destra e grid&ograve; disperatamente, "Non ce la faccio!" L'altra co-pilota aggiunse, "Non dimenticate, se muoio io, morirete anche voi con me!" L'assistente disper&ograve;, "Che cosa sto facendo qui? Come mai mi trovo in questa situazione impossibile?" In realt&agrave; sapeva la risposta. Tutto ebbe inizio qualche giorno fa, anche se ormai non riusciva pi&ugrave; a capire quanti giorni fossero passati.
</p><p>&nbsp;
</p><p>L'assistente era a casa sua, pensando con nostalgia dei bei tempi trascorsi insieme con il detective PM. Certo, all'inizio il loro rapporto era stato un po' strano, quasi malsano, ma tutti e due erano cresciuti come persone, e alla fine l'assistente poteva essere un aiuto adatto e utile per lui, non solo sul piano lavorativo, ma anche personale. Che uomo formidabile! L'assistente non smetteva mai di meravigliarsi del suo intelletto. In tutti gli anni di indagini, riusc&igrave; a risolvere ogni caso - tranne uno. Il suo primo caso, dell'albero aggressivo, il caso dell'uomo normale, della zucchina rossa, dell'ex Direttore della Giustizia, le false accuse contro il propiziatore, &hellip; Erano troppo numerosi da contare, figuriamoci elencare. L'unico caso che non risolse era la propria scomparsa. Aveva comunque una malattia terminale con pochi giorni di vita rimasti, era costretto a rimanere a letto con poca lucidit&agrave;, ma ci&ograve; non consolava l'assistente. Voleva solo dire che lo aveva perso due volte. Un giorno, l'assistente gli diede un bacio di buon giorno, and&ograve; nella cucina che era accanto alla camera da letto per preparare la colazione, e quando ritorn&ograve; c'era solo il letto vuoto, con la forma del suo corpo ancora riconoscibile nel materasso. Tutte le finestre rimasero chiuse a chiave da dentro e nessuno aveva passato per la porta che lei poteva vedere dalla cucina. Sul comodino c'era la forchetta di plastica con un rebbio mancante del detective PM, che lui portava sempre con s&eacute; quando usciva. Una forchetta che l'assistente aveva lasciato accanto al letto per questi lunghi anni, sperando contro ogni speranza che il detective PM sarebbe ritornato per prenderla.
</p><p>Era ancora un mistero tre anni dopo il fatto. Il giudice non era di nessun aiuto, nessuno poteva spiegare quello che era successo. Neanche l'assistente. Perch&eacute; non aveva imparato dal detective PM a ragionare sui casi e a risolverli, invece di credere che lui ci sarebbe stato sempre, e avrebbe pensato a tutto? Nessuno poteva spiegare la scomparsa, tranne il suo caro detectivino, e lui non c'era pi&ugrave;.
</p><p>"Ma perch&eacute;, perch&eacute; mi hai abbandonata?!", grid&ograve; piangendo. Come sempre, i pochi momenti di felice nostalgia si erano trasformati in dolorosa disperazione. Ogni pensiero del detective PM alla fine portava al fatto che lui non c'era pi&ugrave;, e che lei era senza di lui. "La morte non &egrave; giusta, fa schifo", url&ograve; alla casa vuota. "E soprattutto, perch&eacute; il mio detectivino? Era bravo, giusto, aiutava tanti con il suo intelletto. Era ingiusto che lui se ne andasse prima delle persone cattive! Se non c'&egrave; giustizia nella vita e nella morte, che cos'&egrave; la giustizia?"
</p><p>Alcune delle sue amiche avevano cercato inutilmente a consolarla.
</p><p>Zafile le disse di non preoccuparsi, sarebbe andato tutto bene. L'assistente non sapeva da dove avesse ottenuto queste informazioni privilegiate sul futuro.
</p><p>Dadlib afferm&ograve; che tutto fa parte del cerchio della vita. Se avesse avuto dei figli, il detective avrebbe anche potuto continuare a vivere tramite loro. Per l'assistente, voleva dire comunque che il detective PM non c'era, non potevano parlare e condividere insieme, e che tutto la sua conoscenza e le sue esperienze erano perse, anche se era ancora 'vivo' nei pensieri e nei geni.
</p><p>Rafoz la critic&ograve; per essersi lamentata, perch&eacute; era colpa sua. Ovviamente lei o il detective PM erano stati ingiusti, e questa era la giusta punizione; doveva stare attenta a fare la brava essendo giusta o capiter&agrave; anche a lei. L'assistente non pensava di essere pi&ugrave; ingiusta degli altri, n&eacute; il detective PM. Non aveva vinto un premio dalla Nazione per il suo impegno per la giustizia?
</p><p>&nbsp;
</p><p>Anussen, una giovane donna, viveva in una baracca un po' fuori del paese, sola, senza famiglia, amareggiata per i pessimi numeri dei dadi della vita che aveva tirato. Volse lo sguardo in su, alla collina pi&ugrave; alta del paese, dove il tribunale veniva ampliato e abbellito. Il nuovo giudice era appena arrivato nel paese, e - secondo Anussen - voleva solo lasciare un segno nel paese, un monumento a s&eacute; stesso per essere ricordato dalla gente per sempre. Come tutti, era interessato solo a s&eacute; stesso, non agli altri (e soprattutto non agli emarginati come lei), e sicuramente non alla giustizia.
</p><p>&nbsp;
</p><p>L'aiutante cominciava a sentire il peso dei suoi 50 anni. Non tanto per i cambiamenti fisici, anche se i dolori e i mali del corpo iniziarono ad apparire e aggravarsi. Invece, era la stanchezza degli ultimi dodici anni dedicati al servizio degli altri, che ha drenato e prosciugato tutta la sua energia emotiva. Inoltre, c'era sempre il ricordo di quell'avventura fantastica che aveva cambiato la sua vita. Forse era il momento di ricominciare quell'avventura, fare un viaggio, per&ograve; il problema era che non sapeva come. Come poteva partire, senza il mezzo di trasporto adatto? "Boh, arriver&agrave;, anche se non so quando", si consol&ograve;, "di questo posso essere sicura in mezzo a tutte le incertezza della vita". Pass&ograve; dalla cucina alla camera di letto, dove trov&ograve; inaspettatamente una sua vecchia conoscenza: una cabina alta quasi due metri, costruita su una base di circa tre per due metri, con un'unica porta e nessun altro segno all'esterno. Piuttosto, di fuori c'era un miscuglio di colori contrastanti e insensati. L'aiutante riflett&eacute; con tristezza che solo una persona poteva creare una combinazione di colori cos&igrave; orrenda, per lo pi&ugrave; per sbaglio. Poi esclam&ograve; felice, "Ecco, finalmente sei arrivata, amica mia? Non c'eri un'ora fa. Qualcuno mi ha letto la mente per capire che questo era il momento giusto. Chi sar&agrave; stato?"
</p><p>Si sbrig&ograve; per raccogliere tutto l'occorrente. Le provviste, certo, e non potevano mancare le due cose essenziali per il viaggio: la forchetta di plastica con un rebbio mancante del detective PM, e un foglio di carta ingiallito con una serie di numeri scritta, che aveva attentamente conservato per diversi anni. Raccolto tutto, entr&ograve; nella cabina, che era esattamente come si ricordava dopo tutti quegli anni: pulsanti di diversi colori, leve, manopole, quadranti, schermi con informazioni che scorrevano, tastiere, e al centro della cabina un cubo di colore argento che fluttuava nell'aria.
</p><p>L'aiutante salut&ograve; la casa, chiuse la porta dietro di lei, digit&ograve; una data nel pannello di controllo, e schiacci&ograve; un grosso pulsante verde. La cabina scomparve senza un rumore.
</p><p>&nbsp;
</p><p>L'assistente era a casa, depressa e sdraiata nel letto. Forse se avrebbe dormito per un po' di tempo, non sarebbe avvilita dai ricordi del detective PM, almeno per un breve periodo. Per&ograve; in realt&agrave; i pensieri non la lasciavano neanche nel sonno, perch&eacute; sognava il detective PM. Nella sua insonnia, girava qua e l&agrave; nel letto senza riuscire a dormire. Durante uno di questi giri, vide con la coda dell'occhio un enorme&hellip; un enorme non sapeva cosa fosse. Sembrava un armadio gigante, ma nessuno che conosceva l'avrebbe mai dipinto con quei colori in quel modo. Anzi, forse una persona&hellip; ma era al letto per cercare di toglierselo dalla testa, non per essere ricordata! Quando ebbe raccolto il coraggio di alzarsi ed esaminare l'oggetto, un'apertura apparve in uno dei lati, e usc&igrave; una donna. L'aspetto della donna era familiare all'assistente&hellip;
</p><p>"So quello che stai pensando", interruppe la donna prima che l'assistente potesse aprire la bocca. "Per evitare lunghi discorsi di spiegazioni e sorprese, e perch&eacute; so che puoi sopportare la verit&agrave;, ti dico subito quello che hai gi&agrave; sospettato ed escluso. Io sono infatti tu, il futuro tu fra 12 anni. Sono l'aiutante - meno male che ho cambiato il nome dall'assistente, altrimenti ci sarebbe stata ancora pi&ugrave; confusione."
</p><p>La bruschezza della donna sembrava infatti familiare, ma in ogni caso l'assistente non sapeva cosa dire o rispondere ad una tale rivelazione. Cos&igrave; l'aiutante prosegu&igrave;. "So che sei ancora disperata per la mancanza del nostro detectivino. Mi dispiace dirtelo, ma la separazione rimarr&agrave; ancora per almeno 12 anni. Per&ograve; un giorno capirai quello che &egrave; successo. Capirai, e poi a volte starai bene, ma spesso ti sentirai ancora male. Ma avrai un motivo concreto e reale per sperare per il futuro, non solo discorsi belli e vuoti, non solo desideri deludenti e vani, ma la realt&agrave;."
</p><p>"Ma perch&eacute; sei venuta, anzi perch&eacute; sono venuta, caspita non capisco neanche quale pronome usare! Come potr&ograve; capire tutto questo? Perch&eacute; siamo qui insieme?"
</p><p>"Credo che ci confonderemo di meno se ci diamo del tu invece di darci dell'io", ridacchi&ograve; l'aiutante. "Comunque, sono venuta perch&eacute; ho bisogno del tuo aiuto per mettere in moto una serie di eventi, eventi a cui devi partecipare e che devi osservare, affinch&eacute; tu possa risolvere l'ultimo caso."
</p><p>L'affermazione che poteva risolvere il caso della scomparsa del detective PM era tutto l'incoraggiamento di cui l'assistente aveva bisogno. Se ci fosse qualsiasi possibilit&agrave; di terminare i tre anni di miseria, i tre anni di ignoranza brancolando nel buio non riuscendo a aggrapparsi a nessun punto di appoggio che potesse sostenerla nel suo lutto, avrebbe fatto qualsiasi follia pur di non perdere l'opportunit&agrave;. "Ci sto, quando partiamo e a quando partiamo?"
</p><p>"Possiamo partire subito se sei pronta, e dobbiamo fare un salto di 18 anni nel passato per incontrare qualcuno."
</p><p>&nbsp;
</p><p>Il primo giorno dopo aver concluso i suoi studi, lo scienziato rimase a casa per la prima volta dopo tanti anni, perch&eacute; non sapeva cosa fare. Cinque lauree, ed era impossibile trovare un lavoro. Nessuno voleva assumerlo: "troppo qualificato", "troppo intelligente", "non possiamo permetterci uno come te". Riflett&eacute; che anche la reputazione che si era guadagnato con le sue ricerche non fosse di aiuto. Quando present&ograve; le sue conclusioni sui viaggi nel tempo, tutti lo derisero e lo sbeffeggiarono perch&eacute; erano ritenuti impossibili. Eppure si pu&ograve;! Tuttavia, era stufo di subire tutto lo scherno dei cosiddetti cervelloni. Se non volevano accettare le sue stupende scoperte, le avrebbe buttate tutte e trovato un altro mestiere. Ma che cosa?
</p><p>In quel momento lo scienziato sent&igrave; qualcuno bussare, e fu preso dal panico. "Sono le dieci di mattina e sono ancora in pigiama! Che figura far&ograve; se apro la porta, sembrerei un pigrone che non fa niente tutto il giorno. Forse se faccio finta di non essere a casa, andranno via." Rimase in silenzio, ma inutilmente.
</p><p>Sent&igrave; bussare di nuovo, e in aggiunta una voce. "Scienziato, vogliamo fare una proposta interessante e molto conveniente per Lei."
</p><p>"Peggio ancora, una donna. In pigiama non &egrave; il modo di presentarsi ad una donna. E ha detto 'vogliamo', forse sono due donne! Che figuraccia, che figuraccia!" Cap&igrave; comunque che non andavano via, non c'era modo di evitarle, e grid&ograve;, "Un attimo! Arrivo".
</p><p>Lo scienziato cerc&ograve; con furia qualsiasi stoffa per coprire il suo pigiama. I suoi occhi si posero sulla sua sedia, che aveva un copripoltrona viola. Non un colore che gli stava bene, ma doveva bastare. In meno che non si dica, lo scienziato spogli&ograve; la sedia del copripoltrona e lo avvolse intorno al suo corpo, attaccando insieme i due lati sotto il collo con una molletta. Si guard&ograve;: non era molto elegante, ma aveva indossato vestiti peggiori nel passato.
</p><p>Cerc&ograve; di tranquillizzarsi, e cammin&ograve; verso la porta con calma. Per&ograve; calpest&ograve; una forchetta di plastica che era rimasta per terra dalla cena della sera precedente, che gli fece malissimo e si mise a urlare.
</p><p>"Sta bene?", domand&ograve; la voce, preoccupata, dall'altra parte della porta.
</p><p>"S&igrave;, s&igrave;, tutto bene", rispose reprimendo ulteriori grida di dolore. Aveva dimenticato di essere scalzo, ma era troppo tardi per rimediare. Esamin&ograve; il piede, e trov&ograve; un rebbio che si era staccato della forchetta schiacciata. Tolse il rebbio e lo butt&ograve; in un angolo della stanza, raccolse la forchetta, zoppic&ograve; fino alla porta e la apr&igrave;.
</p><p>L'assistente sussult&ograve; per la sorpresa. Il suo cuore perse un colpo. La noncuranza per i vestiti, la forchetta di plastica con un rebbio mancante in mano, gli occhi intelligenti che percepiva tutto. Non era uno scienziato, ma il suo caro, scomparso, detectivino. Certo, era diverso, era pi&ugrave; giovane, sui 25 anni, come quando l'aveva conosciuto, ma era lui. Dopo tre anni senza di lui, tre anni in cui aveva vissuto nel dubbio se l'avrebbe mai rivisto, tre anni di lutto senza la possibilit&agrave; di chiusura, l'emozione la sopraffece. Svenne.
</p><p>Mentre l'assistente veniva colpita dall'apparizione inaspettata dal suo amore, lo scienziato esamin&ograve; le due donne che si trovavano davanti a lui. Si somigliavano tanto - la pi&ugrave; giovane con capelli lunghi, l'altra con capelli corti e leggermente pi&ugrave; bianchi, ma per il resto molto simili. Erano probabilmente parenti. Per&ograve; la differenza in et&agrave; - circa 10 anni, massimo 15 - era troppo poco affinch&eacute; potessero essere madre e figlia. Possibilmente sorelle, pi&ugrave; probabilmente cugine o comunque parenti strette. Vestite in modo strano, probabilmente di un paese distante, o forse della capitale, magari andava di moda. Lo scienziato fece un appunto mentale di aggiornarsi sulla moda, non per s&eacute; stesso ma per capire gli altri in base a come si vestivano. La donna pi&ugrave; giovane aveva chiari segni intorno agli occhi di aver pianto molto recentemente - qualcosa la turbava. E poi svenne. Ovviamente una disposizione debole, emotivamente instabile. Quella pi&ugrave; grande aveva invece - ecco, quello era interessante&hellip;
</p><p>Le sue riflessioni furono interrotte dalla richiesta, "Mi pu&ograve; aiutare a portarla in casa sua, se non La disturba? Ha bisogno di riposarsi per un po' di tempo."
</p><p>Trasportarono il corpo inconscio dell'assistente fino alla sedia. Lo scienziato sper&ograve; che non sporcasse, siccome il copripoltrona lo portava lui piuttosto della sedia. Con un bicchiere d'acqua e qualche carezza gentile di incoraggiamento, l'assistente si svegli&ograve;, e disse, "Ho pensato di non vedere pi&ugrave;&hellip;", prima che l'aiutante la zittisse, e spieg&ograve; allo scienziato, "&Egrave; ovviamente ancora leggermente confusa."
</p><p>"Capisco, &egrave; normale dopo uno svenimento necessitare di qualche secondo per riorientarsi. Allora, voi siete venute da lontano. Gestite un'attivit&agrave; familiare insieme. Avete un rapporto molto stretto, avete subito la perdita di un parente stretto di recente, e vi impegnate per la giustizia. Per quest'ultimo motivo, mi sembrate persone di cui mi posso fidare. Ditemi quello che volete."
</p><p>"Come hai capito tutto questo?", chiese l'aiutante sorpresa ma non completamente, perch&eacute; conosceva come il suo detectivino ragionava e parlava, anche se non l'aveva sentito da 15 anni.
</p><p>"Semplice, signore. Avete vestiti strani, non di moda nel nostro paese o regione, per cui da lontano." L'assistente sorrise dentro di s&eacute;, perch&eacute; qualcuno che indossava un copripoltrona aveva descritto i suoi vestiti come strani. "Poi fisicamente vi assomigliate tanto e pensate nello stesso modo. La cosa pi&ugrave; sorprendete &egrave; che indossate spille identiche, spille che si vedono raramente. Sono premi assegnati dalla nostra Nazione della Giustizia alle persone pi&ugrave; meritevoli, che si sono impegnate per promuovere e creare la giustizia. Avete fatto insieme qualcosa di straordinariamente giusto!"
</p><p>L'aiutante era scioccata perch&eacute; aveva dimenticato la spilla - che si raddoppi&ograve; perch&eacute; l'aiutante aveva portato la sua nel passato e l'assistente portava la stessa spilla. Avrebbero dovuto togliersela, per non essere cos&igrave; uguali e svelare la propria identit&agrave;. Era in realt&agrave; un premio dato al detective PM poco dopo la sua scomparsa, per tutti i casi che aveva risolto e portato alla giustizia, e che l'assistente (e in seguito l'aiutante) si era messo per ricordarlo e onorarlo.
</p><p>Gli occhi dell'assistente, invece, si spalancarono, e si riprese sentendo il suo detectivino parlare cos&igrave;. Si sentiva innamorata di nuovo, come tanti anni fa.
</p><p>Per&ograve; fu l'aiutante che rispose prima, dicendo, "Sono impressionata dalle tue capacit&agrave; intellettuali e di osservazione. Ha mai considerato essere un detective?"
</p><p>"Direi di no", replic&ograve; subito. Continu&ograve; a pensare tra s&eacute; e s&eacute;, "Per&ograve;, non &egrave; male come suggerimento, sarebbe una buona possibilit&agrave;. Invece di 'scienziato', potrei chiamarmi 'detective'. &Egrave; un po' semplice, generico cos&igrave;, forse con un'aggiunta o suffisso per spiccare, per distinguermi dagli altri. Perch&eacute; voglio essere il migliore detective, unico del mio genere, non uno di tanti. Ci penser&ograve; dopo." Poi chiese ad alta voce, "Cosa posso fare per voi signore?"
</p><p>"Come ha giustamente capito, lavoriamo insieme. In modo particolare, siamo interessate nella scienza, e abbiamo sentito delle Sue ricerche."
</p><p>"E suppongo che riteniate le mie ricerche non scientifiche, e mi vogliate prendere in giro."
</p><p>"Niente di pi&ugrave; ingiusto! Da dove proveniamo, Lei &egrave; considerato un mito, una leggenda della giustizia."
</p><p>L'assistente pens&ograve;, e a stento riusc&igrave; a non dire, "S&igrave;, da noi nel lontano futuro, sei un mito per tutto quello che hai fatto, e la tua reputazione cresce ogni giorno dopo la tua scomparsa. Quanto vorrei, e quanto tutti vorrebbero, che tu fossi ancora con noi! E che tu sapessi quanto la gente ti vuole bene."
</p><p>"Noi gestiamo un museo" - a quel punto serviva qualche bugia - "e quando abbiamo deciso di allestire una mostra sui sogni futuristici, era naturale pensare alle tue idee sulle macchine del tempo."
</p><p>"Che tipo di museo sarebbe che vorrebbe mostrare un mucchio di rottami? Non mi importa, sono stufo di tutti i guai che queste idee mi hanno portato. Da oggi giro pagina! Ecco, qui ci sono tutti i piani e progetti, con una descrizione di come funzionerebbe", tirando fuori una risma di carta da un cassetto. "Fuori, dietro la casa, c'&egrave; tanta cianfrusaglia che potete portare via. Ho cominciato a costruire la macchina del tempo, e quello che ho gi&agrave; fatto &egrave; l&igrave;." Si ricord&ograve; del casino che aveva creato quando inciamp&ograve; e rovesci&ograve; diversi secchi dei colori sulle parti esterne della macchina del tempo, ma non voleva ammettere un suo errore. Disse invece sfacciatamente, "Attenzione ai muri, i colori caleidoscopici sono molto importanti per il buon funzionamento della macchina."
</p><p>"La ringraziamo infinitamente. Questa macchina del tempo porter&agrave; molta gioia a tante persone."
</p><p>"Ma sapete che la macchina non potr&agrave; mai funzionare?", chiese curioso lo scienziato. "Ci sono alcuni materiali che sono impossibili da reperire adesso, e ci vuole qualche tecnologia non ancora inventata. Forse nel futuro si troveranno, ma per ora non c'&egrave; speranza." Poi gli venne in mente un pensiero divertente, "Se aveste una macchina del tempo, potreste viaggiare nel futuro per completare questa macchina del tempo", e scoppi&ograve; a ridere.
</p><p>L'assistente e l'aiutante fece una risata forzata, sia perch&eacute; era troppo vicino alla verit&agrave; (l'intuito del detective stava per rovinare tutto?), sia perch&eacute; era la prima (oppure era l'ultima? comunque era l'unica) volta che hanno sentito il detective PM provare a fare una battuta.
</p><p>Quando lo scienziato ebbe un'idea, rimaneva sempre con lui e non poteva fare altro prima di realizzarla. Questa risolutezza quasi monomaniaca l'aveva spinto e aiutato molto come scienziato, e sarebbe stato fondamentale per risolvere molti casi come detective PM. In quel momento, aveva l'idea di diventare un detective, e doveva farlo subito.
</p><p>"Io vi devo salutare adesso, ho delle commissioni da fare. Potete rimanere fuori, e mi far&agrave; piacere se tutti i pezzi saranno spariti al mio ritorno." Usc&igrave; e corse verso il tribunale, sempre con il pigiama coperto dal copripoltrona, e in mano la forchetta di plastica con un rebbio mancante. Il suo ultimo pensiero prima di concentrarsi a diventare un detective e decidere quale suffisso usare era, "Che maleducato che ero! Ho dimenticato di chiedere come si chiamassero. Boh, probabilmente non era importante, non le vedr&ograve; mai pi&ugrave;."
</p><p>&nbsp;
</p><p>La partenza improvvisa del detective era troppo per l'assistente, che si mise a piangere a dirotto di nuovo. Ancora una volta, non pot&eacute; salutare il suo amore; ancora una volta lui era scomparso e l'assistente sapeva che non l'avrebbe visto mai pi&ugrave;. Rivederlo cos&igrave; era una presa in giro, non aveva risolto niente. Si rivolse all'aiutante, "Perch&eacute; non mi hai detto che andavamo dal mio detectivino? Perch&eacute; mi hai dato questa falsa speranza che poi mi &egrave; stata strappata? Sto peggio di prima, con tutti i ricordi con cui ho imparato a vivere, ora in primo piano di nuovo."
</p><p>"Mi dispiace davvero, ma era veramente necessario venire dal nostro detectivino, &egrave; l'unico che ci pu&ograve; aiutare a fare quello che dobbiamo fare, ci serve la macchina del tempo. Un giorno capirai. Non ho voluto avvertirti perch&eacute; ritenevo che sarebbe stato peggio. Saresti stata troppo agitata e fuori di testa anche prima di rivederlo. Gi&agrave; hai quasi spifferato e rovinato tutto. Comunque, so come ti senti. Ho e ho avuto gli stessi sentimenti anch'io. Anche a me parlare nuovamente con il detectivino mi dava gioia e mi faceva male allo stesso tempo. Certo, in questi 12 anni ho imparato un pochino a gestire il dolore, ma rimane comunque. Tuttavia, ho anche imparato in questi anni che c'&egrave; una speranza giusta e vera, e quella speranza mi ha accompagnata e sostenuta in questi anni e in questo tempo con il detectivino.
</p><p>Il carattere dell'assistente di qualche anno fa, quando era sarcastica e cinica, venne a galla con questo discorso sulla speranza, dopo tutte le sue delusioni. "Speranza?! Ti inganni! Stai solo attualizzando i tuoi desideri vuoti."
</p><p>L'aiutante si gir&ograve; per rivolgere la schiena verso l'assistente, affinch&eacute; non potesse vedere le lacrime che scendevano lentamente anche sulle sue guance. "Mi dispiace veramente, mi dispiace per la sofferenza che hai sperimentato nel passato e che ti ho fatto sperimentare adesso."
</p><p>L'assistente non si riconosceva nella sua battuta, anzi si riconosceva come la persona che ha deciso diversi anni fa di non voler essere pi&ugrave;. "Chiedo scusa, quello che ho detto era sbagliato, ingiusto, e non voglio pi&ugrave; dire qualcosa del genere."
</p><p>L'aiutante si asciug&ograve; la faccia velocemente e di nascosto, e cambi&ograve; discorso. "Bene. Dobbiamo mettere tutti questi componenti, e i piani, dentro la nostra macchina del tempo prima che ritorni il detectivino."
</p><p>&nbsp;
</p><p>Per velocizzare l'operazione, tornarono a dove avevano lasciato la macchina del tempo e la spostarono alla casa del detective, cinque secondi dopo che partirono dalla casa per prendere la macchina del tempo. Cominciarono a spostare tutti i pezzi dentro la macchina del tempo. Non era pi&ugrave; grande all'interno che all'esterno, per cui era difficile trovare spazio per tutto. Per&ograve;, siccome era completamente smontata, e i pannelli dei lati potevano stare diagonalmente, alla fine riuscirono a caricare tutto, anche se era molto stretto dentro. Quando avevano finito, si resero conto che ci sarebbe voluto molto tempo per assemblare tutto, e dovevano anche raccogliere i materiali non ancora esistenti.
</p><p>"Ci servir&agrave; una mano per fare tutto questo", afferm&ograve; l'assistente.
</p><p>"S&igrave;, ma a chi possiamo chiedere? Di chi ci possiamo fidare? Non possiamo raccontare in giro che stiamo costruendo una macchina del tempo."
</p><p>"Hmm&hellip; Un'idea avrei, siccome non lo possiamo dire a nessun altro. Conosco una piccola baracca un po' fuori del paese dove potremo trovare qualcuno", ridacchi&ograve;.
</p><p>&nbsp;
</p><p>Anussen non sapeva cosa fare. Non aveva un lavoro, non aveva amici (e non era molto interessata ad averli, tanto tutti gli altri erano cattivi). Forse poteva uscire per scroccare qualcosa da mangiare. Rimase sorpresa quando qualcuno la salut&ograve; dalla tenda che faceva finta di essere la porta principale della baracca. Non ha mai visite o ospiti!
</p><p>"Chi sei? Cosa vuoi?"
</p><p>"Salve", disse la donna che spost&ograve; la tenda per entrare, seguita da una donna pi&ugrave; anziana. "Io sono l'assistente e&hellip;"
</p><p>"L'assistente di chi?", interruppe Anussen sgarbatamente.
</p><p>"Questo &egrave; un po' complicato da spiegare. Diciamo che adesso sono l'assistente di lei", indicando l'altra donna, "che &egrave; l'aiutante".
</p><p>"Chi aiuti?"
</p><p>"Anche questo &egrave; piuttosto difficile. Per&ograve; adesso aiuto l'assistente."
</p><p>"A che gioco state giocando?! Dite solo sciocchezze. Andate via se non volete dire niente di sensato."
</p><p>Mentre Anussen le spingeva fuori, l'assistente proposi, "Vogliamo offrirti un piccolo lavoro, se vuoi darci una mano."
</p><p>Un lavoretto sicuramente le interessava, qualche soldo serviva sempre. Per&ograve;, piuttosto di dire di s&igrave;, osserv&ograve;, "L'assistente e l'aiutante hanno bisogno di una mano? Chi sarei io, l'ausiliare?"
</p><p>"Se vuoi, va bene. Potremo essere le tre sorelle A."
</p><p>"Come ti permetti? Non puoi presumere un rapporto cos&igrave; stretto, non ci conosciamo affatto!"
</p><p>"Chiedo scusa, sono stata presuntuosa. Ma credo che con il passare del tempo, ci avvicineremo", rispose l'assistente.
</p><p>"Boh, non credo, non sembrate proprio il tipo di persona che mi piace. Comunque, quando cominciamo? Cosa facciamo?"
</p><p>"Se vuoi seguirci fuori, abbiamo un laboratorio in una cabina proprio qui fuori nella strada, dove spiegheremo quello che dovremo fare."
</p><p>L'ausiliare usc&igrave; dietro l'assistente e l'aiutante (che si dissero sottovoce che non si ricordavano di essere cos&igrave; antipatiche), e insieme entrarono nella macchina del tempo. Mentre l'assistente spieg&ograve; superficialmente che dovevano montare i componenti sparpagliati dentro la cabina, l'aiutante impost&ograve; le coordinate per tornare a casa sua, e senza un movimento n&eacute; un rumore percepibili, viaggiarono.
</p><p>&nbsp;
</p><p>L'aiutante, l'assistente, e l'ausiliare iniziarono a costruire la macchina del tempo mentre erano ancora dentro. L'ausiliare, vivendo da sola da molti anni e senza amici di cui fidarsi, aveva imparato a cavarsela con tanti lavori manuali. L'assistente, mentre era con il detective PM, doveva fare il tuttofare, qualsiasi cosa che serviva per portare avanti le indagini. L'aiutante dovette fare tanti lavori diversi per soccorrere la gente, secondo il bisogno e non secondo le sue conoscenze. Inoltre, avevano non soltanto le istruzioni dello scienziato, ma anche la macchina del tempo gi&agrave; costruita da seguire come modello, e ben tre brugole - difficile da credersi, ma possibilmente ancora pi&ugrave; utili di una forchetta di plastica con un rebbio mancante. Cos&igrave;, riuscirono a montare velocemente il pannello di controllo, segnalando i componenti mancanti (perch&eacute;, come l'assistente e l'aiutante sapevano, non erano disponibili al tempo dello scienziato). Come sempre quando si monta un mobile, c'erano alcuni pezzi rimasti inutilizzati, ma ritennero che fossero superflui.
</p><p>Quando decisero di cominciare a montare i muri, si resero conto di non poterlo fare mentre erano dentro la cabina. Uscirono, e subito l'ausiliare esclam&ograve;, "Che stregoneria &egrave; questo?! Eravamo in strada davanti a casa mia, e adesso siamo dentro una casa che io non ho mai visto in tutta la mia vita! Chi siete in realt&agrave;? Cosa mi avete fatto? So che non dovevo fidarmi di voi, siete malvagie come tutti gli altri."
</p><p>"Abbiamo magari tralasciato qualche dettaglio del nostro lavoro", raccont&ograve; l'aiutante con un sorriso. "Forse non avresti accettato il lavoro se avessimo detto tutto. Per&ograve;, so per esperienza che ti piacer&agrave; questo lavoro. Ti spiego tutto adesso senza usare mezzi termini, perch&eacute; so che vuoi solo i fatti. Vedi, questa cabina &egrave; in realt&agrave; una macchina del tempo, e ti abbiamo portata 30 anni nel futuro, a casa mia. Il nostro obiettivo &egrave; di costruire una macchina del tempo, dai componenti e dei piani che hai visto."
</p><p>"Cos&igrave; ne avremo due, giusto? Perch&eacute; volete un'altra se ne avete gi&agrave; una?", interrog&ograve; l'ausiliare.
</p><p>"S&igrave;, due, ma non esattamente. Dobbiamo costruire questa macchina per avere quella macchina l&igrave;", indicando la cabina in cui avevano viaggiato.
</p><p>"Ma non la avete gi&agrave;? Non l'avete gi&agrave; costruita?"
</p><p>"Non l'ho costruita (almeno non ancora), l'ho&hellip; trovata. Mi &egrave; stata mandata."
</p><p>"Da chi?"
</p><p>"Questo non lo so, &egrave; apparsa qui stamattina, che per me &egrave; gi&agrave; ieri." In realt&agrave;, aveva cominciato a sospettare chi gliela avesse mandato, cio&egrave; avrebbe mandato, o forse avrebbe avuto mandare. Avrebbe potuto aver mandato? Insomma, era difficile sapere quale tempo dei verbi usare con i viaggi nel tempo! Lo sospettava, ma non lo voleva dire.
</p><p>"Quindi hai viaggiato nel passato con una macchina del tempo che uno sconosciuto futuro, passato, futuro nel mio passato, passato nel mio futuro, o congiuntivo, ti ha mandato, per costruire nel mio futuro, che &egrave; il tuo presente, non una copia ma la stessa macchina che esiste gi&agrave;?"
</p><p>"Giusto", replicarono le due sorelle in coro.
</p><p>"Sono pazze queste ragazze", mormor&ograve; a s&eacute; stessa.
</p><p>"Per&ograve;, per chiarire", aggiunse l'assistente, "anch'io sono adesso nel futuro, perch&eacute; del tuo futuro anteriore. Prima l'aiutante mi ha presa, cio&egrave; per te mi prender&agrave;, cio&egrave; sarei stata essere presa prima che avessimo potuto averti presa. Forse," spieg&ograve; con uno sguardo sempre pi&ugrave; dubbioso che coniugava bene i verbi.
</p><p>&nbsp;
</p><p>Essendo 30 anni nel futuro dello scienziato, non ebbero problemi recuperare il materiale mancante, tranne il cubo di colore argento che fluttuava nell'aria al centro della cabina. Leggendo la descrizione della macchina del tempo, capirono che era un cubo di mendelevio, un elemento artificiale che &egrave; stato prodotto in minuscole quantit&agrave; sulla terra. Fungeva da fonte di energia per i viaggi nel tempo.
</p><p>"Allora, come facciamo?", si chiese l'assistente. "Abbiamo seguito un vicolo cieco e hai sprecato il mio tempo."
</p><p>"Non esistono vicoli ciechi per una macchina del tempo", sorrise l'aiutante. "Capita che io possiedo", tirando fuori il foglio di carta ingiallito con una serie di numeri scritta, "le coordinate di un posto che ci porter&agrave; a una fornitura di mendelevio."
</p><p>"Che coincidenza", intervenne l'ausiliare, incerta e confusa per quello che stava succedendo.
</p><p>"Siamo pronte? Andiamo?", propose l'aiutante. "Quasi mi dimenticavo. Assistente, saresti cos&igrave; gentile di prendere un foglio e una matita dalla cucina?"
</p><p>Entrarono di nuovo nella cabina, impostarono le coordinate, e partirono. Quando arrivarono, l'aiutante chiese all'assistente di scrivere le loro coordinate attuali sul foglio, e di conservare il foglio come un tesoro.
</p><p>"Perch&eacute; non mi dai piuttosto il tuo foglio da conservare?", controbatt&eacute; l'assistente.
</p><p>"Perch&eacute; non funzionerebbe. Significherebbe che fra 12 anni, quando ritorni nel passato per trovarti, il foglio avrebbe 24 anni, e magari sarebbe poco leggibile. Poi darai il foglio al te passata&hellip;"
</p><p>"L'ausiliare?", chiese l'assistente, cominciando a perdersi e non comprendere.
</p><p>"No, tu adesso ma fra 12 anni. Poi quando quella tu tiene il foglio per 12 anni, avr&agrave; 36 quando viene passato al tu attuale ma passata. Pi&ugrave; chiaro di cos&igrave;&hellip;"
</p><p>"Scrivo e basto", si arrese l'assistente.
</p><p>Dopo qualche secondo di riflessione, l'ausiliare si ferm&ograve; e disse, "Aspettate un attimo voi due. Perch&eacute; ha detto che lei passata sono io, l'ausiliare? Io sono Anussen, non sono te n&eacute; lei". E poi aggiunse, "N&eacute; voi".
</p><p>Le altre due si sentirono imbarazzate, perch&eacute; avevano lasciato trapelare la parte della verit&agrave; che non avevano detto all'ausiliare.
</p><p>"In realt&agrave;, tu sei noi", ammise l'aiutante. "Fra 18 anni, tu sarai lei", indicando l'assistente, "e fra oltre 12 anni sarai me. Ti abbiamo presa proprio per questo motivo, per limitare il numero di persone che sanno della macchina del tempo. E non te l'hanno detto per non confonderti pi&ugrave; del dovuto. Scusaci, ma l'abbiamo fatto in buona fede, ritenendo di fare la cosa giusta."
</p><p>"Se diventer&ograve; voi, sar&ograve; davvero cos&igrave; antipatica da vecchia?"
</p><p>"Mature, siamo mature non vecchie", precis&ograve; l'aiutante.
</p><p>"Come volete, illudetevi pure. A 30 anni &egrave; come se si fosse gi&agrave; morti. Finiamo questa macchina del tempo e andiamo a casa, sono un po' stufa di stare con voi, vorrei stare da sola con solo me stessa," comment&ograve; l'ausiliare, non rendendosi conto dell'ironia dell'osservazione.
</p><p>"Va bene, usciamo, e preparatevi per una sorpresa", disse l'aiutante.
</p><p>&nbsp;
</p><p>Le tre donne si trovarono nella stiva di un mezzo di trasporto, con la macchina del tempo ordinatamente parcheggiata in un angolo. Per&ograve;, non percepivano l'ondulare del mare, n&eacute; sentivano l'aria che passava sopra le ali. Se non era una nave n&eacute; un aereo&hellip; L'ausiliare diede un'occhiata fuori attraverso una piccola finestrino, e fu colta alla sprovvista e fece un salto indietro di due metri. "C'&egrave; un pianeta arancione l&igrave; fuori! Siamo su un'astronave!", esclam&ograve;.
</p><p>"Giusto", conferm&ograve; l'aiutante. "Per la precisione, siamo in un'astronave da carico automatica, in orbita sopra l'unico pianeta che commercia in mendelevio. Dobbiamo solo atterrare (&egrave; la parola giusta per raggiungere un pianeta che non &egrave; la terra?) all'unico porto sul pianeta, fare la transazione, e partire con la nostra macchina del tempo."
</p><p>"Ma se &egrave; automatica, come facciamo a portare l'astronave al porto?", chiese l'aiutante.
</p><p>"Facile, prima annullerai il pilota automatico, poi prenderai i controlli, e infine ci guiderai fino al porto."
</p><p>"Va bene. Non mi sembrava molto complicato", rispose l'ausiliare sarcasticamente.
</p><p>"E quando usi, nel tuo piano, la seconda persona singolare, &egrave; una di quelle complicazioni dei viaggi in tempo, giusto? 'Tu', nel senso di tu che sei in realt&agrave; me e lo far&ograve; io, cio&egrave; tu l'aiutante."
</p><p>"In questo caso, non &egrave; cos&igrave;. Lo devi fare tu, l'assistente. Ma te lo posso insegnare e ti aiuter&ograve;. Aiutare &egrave; quello che mi viene meglio!"
</p><p>"Ma se la sai pilotare tu, perch&eacute; non lo fai tu?", rispose l'assistente cercando una scappatoia. Anche il suo detectivino l'aveva fatto fare delle cose spericolate necessarie per risolvere dei casi, con qualche scusa inverosimile, che doveva osservare o qualcosa del genere. Il nuovo ricordo del detective PM la fece rattristare di nuovo, ma poi si ricord&ograve; che faceva tutto questo per lui, ed era pronta a fare tutto, anche a rischio della propria vita, per lui. Decise che avrebbe provato.
</p><p>"Secondo te, come ho imparato a pilotare un'astronave? Non c'&egrave; un corso nel nostro paese, neanche nei prossimi 12 anni! Ho imparato guardando te adesso, cos&igrave; anche tu, quando sarai me, potrai dirti cosa fare. Basta chiacchiere, il ponte ci aspetta."
</p><p>&nbsp;
</p><p>L'assistente si avvicinava alla citt&agrave; troppo rapidamente. Il rientro nell'atmosfera era difficilissimo. Faceva caldo, troppo caldo, e sudava tanto. L'aiutante speriment&ograve; un momento di d&eacute;j&agrave; vu. Non fece caso, perch&eacute; era tutto d&eacute;j&agrave; vu da quando era arrivata alla casa dell'assistente. Mentre rifletteva su questi ricordi, l'assistente si gir&ograve; verso di lei e grid&ograve; disperatamente, "Non ce la faccio!" L'ausiliare aggiunse, " Non dimenticate, se muoio io, morirete anche voi con me!"
</p><p>L'aiutante incoraggi&ograve; tutte e due, "Non preoccupatevi. Ce la faremo, andr&agrave; tutto bene. Vedrete!"
</p><p>"Come puoi dire che andr&agrave; tutto bene?", url&ograve; l'assistente sopra il rumore del vento e delle esplosioni. "Non puoi sapere che numero c'&egrave; sui dadi della vita che abbiamo tirato. Non puoi garantire quello che succeder&agrave; nel futuro." Nel momento in cui lo disse, l'assistente si rese conto che la sua obiezione, pur giusta in generale, in questo caso era falsa.
</p><p>"Altroch&eacute;! Io so esattamente come finir&agrave;, perch&eacute; ho gi&agrave; sperimentato questa situazione e sono sopravvissuta. Vi dico, andr&agrave; tutto bene."
</p><p>L'assistente cap&igrave; che se qualcuno veramente sapesse il futuro, varrebbe la pena porre la propria fiducia in quello che dice e promette.
</p><p>&nbsp;
</p><p>Trovare un cubo di mendelevio in vendita risult&ograve; molto pi&ugrave; semplice che guidare l'astronave. Riuscirono addirittura a trovare un cubo economico perch&eacute; di seconda mano, utilizzato solo una volta la settimana per un mese. Il venditore assicur&ograve; loro che il mendelevio aveva un'emivita di pi&ugrave; di 50 giorni, per cui avrebbe funzionato ancora per un bel po' di tempo. Non avendo soldi, barattarono l'astronave per il cubo, e tutti erano contenti dell'affare. Portarono il cubo nella cabina (dove notarono che somigliavano al cubo che gi&agrave; fluttuava dentro la cabina), e ritornarono alla casa dell'aiutante. A questo punto, fu facile completare il montaggio della macchina del tempo, e guardarono compiaciute le due cabine identiche fianco a fianco. Anzi, la coppia di copie identiche della stessa cabina.
</p><p>&nbsp;
</p><p>Avendo finito il compito, era giunto il momento per l'ausiliare ritornare al suo tempo. L'assistente e l'aiutante proposero che lei prendesse la macchina del tempo originale, cio&egrave; la versione pi&ugrave; vecchia che l'aiutante aveva usato per i primi viaggi. L'aiutante avrebbe portato l'assistente al suo tempo con la macchina del tempo nuova appena costruita, e poi doveva sbrigare alcuni altri compiti. Le tre donne dunque si salutarono. Ci fu un momento di imbarazzo e goffaggine, come &egrave; normale in tali situazioni. Non vollero dire "arrivederci"; decisero che "arriesserci" era pi&ugrave; appropriato. Dopo un paio di abbracci - pi&ugrave; stretti quelli dell'assistente e dell'aiutante all'ausiliare che quelli dell'ausiliare alle altre due - l'ausiliare entr&ograve; nella macchina del tempo e spar&igrave;.
</p><p>"Ho per&ograve; ancora una curiosit&agrave;", afferm&ograve; l'assistente. "Anzi, diverse cose che non capisco, ma una principale in questo momento. Perch&eacute; non ci ricordiamo di questo viaggio quando eravamo giovani? Io mi ricordo di tutto il resto che io ho fatto, prima e dopo questo viaggio. Ma del viaggio, ho un vuoto completo."
</p><p>"Anch'io me lo chiedevo. Forse non lo sapremo mai."
</p><p>"Ma tu ti ricordi tutto? Sai gi&agrave; tutto quello che penso, quello che far&ograve; e dir&ograve;?"
</p><p>"Senz'altro dopo 12 anni non mi ricordo tutto. Nessuno si ricorda ogni parola e azione di tanto tempo fa. Ma s&igrave;, sapevo come si sarebbero svolti gli eventi principali del nostro viaggio, anche se qualche dettaglio mi sfuggiva."
</p><p>"E sai quello che mi spetter&agrave; dopo questo?"
</p><p>L'aiutante esit&ograve;. "S&igrave;, ma non mi chiedere. Capirai quello che succeder&agrave; quando succeder&agrave;."
</p><p>"Non mi piace, ma capisco. &Egrave; l'ora anche per me tornare a casa. Mi dai un passaggio?"
</p><p>&nbsp;
</p><p>Le tre versioni dell'assistente non conoscevano il proverbio galattico, "Fidati di un venditore affurtano quanto un origgar", ma anche se lo avessero conosciuto non avrebbero capito. Il porto dove avevano comprato il mendelevio era noto come una tana di imbroglioni. Infatti, il mendelevio non era stato utilizzato da un mese, come il negoziante del pianeta Affurt affermava, ma da quasi quattro mesi, per cui la sua produzione di energia era gi&agrave; meno di un quarto del massimo e in rapida discesa. Furono fortunate ad essere riuscite a fare tutti i viaggi che avevano fatto, ma la fortuna e il carburante finirono quando l'ausiliare stava per apparire nel suo tempo. Quindi invece di trovarsi in un luogo deserto vicino al paese, la macchina del tempo comparve a 10 metri di altezza, sopra una collina che portava gi&ugrave; ad un lago. Nel secondo e mezzo di caduta libera, tutti i componenti collegati alla fonte di energia ormai esaurita si spensero, altri scoppiarono, e ci fu un principio di incendio. Quando la cabina schiant&ograve; contro il terreno, la porta si apr&igrave; e Anussen fu buttata fuori violentemente e batt&eacute; la testa. Mentre rimaneva stesa per terra inconscia, la macchina del tempo rotol&ograve; gi&ugrave; la collina prima di affondare nel lago, dove un'esplosione distrusse le ultime tracce dell'invenzione.
</p><p>&nbsp;
</p><p>Le altre due donne ritornarono alla casa dell'assistente, che provocava dolore anche per l'aiutante. Quanti brutti ricordi di quei tre anni! Per&ograve; l'aiutante sapeva allora quello che doveva fare. "Veramente, andr&agrave; tutto bene", pens&ograve; tra s&eacute; e s&eacute;. "Sistemer&ograve; tutto, e capirai."
</p><p>Si salutarono, ma invece di ritornare al suo tempo, l'aiutante immise le coordinate dello stesso luogo, ma tre anni prima.
</p><p>&nbsp;
</p><p>Il detective si sentiva compiaciuto di s&eacute; stesso. In poche ore si era sbarazzato di tanta spazzatura (facendo lavorare gli altri), aveva cambiato mestiere, e gli era stato affidato il suo primo caso (seppure di prova) dal nuovo giudice del paese. Aveva il sospetto che fosse solo per toglierlo di mezzo, ma era contento lo stesso di aver un caso. Mentre il giudice investigava un furto importante del giorno precedente, aveva mandato il detective in questo luogo deserto vicino al paese per investigare l'affermazione da parte di un uomo, che era ritornato in paese bagnato fradicio e con fango sulle mani e sui pantaloni dal ginocchio in gi&ugrave;, che diceva di essere stato aggredito da un albero da queste parti.
</p><p>Mentre cercava degli indizi, il detective not&ograve; il cadavere di una donna stesa per terra su una collina. "&Egrave; veramente il mio giorno fortunato", esclam&ograve; felice. "Ho pure scoperto da solo la vittima di un crimine, un altro caso da risolvere! Forse &egrave; stata un'altra aggressione da parte degli alberi!" And&ograve; a indagare, e dopo aver determinato che era di una giovane donna, rimase deluso che era solo inconscia, non morta. "Che strano, la seconda donna svenuta della giornata! Sarebbe un caso interessante se fossero collegate, ma ovviamente non lo sono." Il detective cerc&ograve; di ricordare quello che aveva fatto la donna all'amica svenuta quella mattina, e quindi butt&ograve; dell'acqua in faccia alla giovane e la scosse, fino a quando si riprese. "Chi sei? Cosa fai inconscia sulla collina? Per caso un albero ti ha aggredita?", interrog&ograve; il detective.
</p><p>"Ah&hellip; che dolore. Ma dove sono? Non so quello che mi sia successo. L'ultima cosa che mi ricordo &egrave; che era a casa mia, e adesso mi trovo qui. Mi ricordo comunque che mi chiamo Anussen. E cosa fai tu qui, nel bel mezzo di niente?"
</p><p>"Sto investigando un'aggressione."
</p><p>"Magari da parte di un sasso? Perch&eacute; qui non c'&egrave; altro che questi sassolini circolari."
</p><p>"In realt&agrave; da parte di un albero, laggi&ugrave; in fondo alla collina."
</p><p>"Di che cosa deliri?"
</p><p>"Elucido. Stamattina qualcuno &egrave; arrivato in paese dicendo di essere stato aggredito da, secondo lui, un albero. Le mani e le gambe erano sporche, probabilmente perch&eacute; era stato a quattro zampe sul terreno bagnato - infatti, come sai, ha piovuto stanotte. Aspetta - cosa hai detto dei sassi?"
</p><p>"Che qui sulla collina ci sono solo questi sassolini."
</p><p>"Che qui vicino a te sono tutti circolari. Per&ograve; i sassi circolari vengono dal fiume di l&agrave;, che scende gi&ugrave; sulla collina e si riversa nel lago - l'acqua che scorre nel fiume modella i sassi. Sulla collina i sassi dovrebbero avere altre forme, come su tutto il resto della collina. Solo qui sono circolari, perch&eacute; qualcuno li ha portati dal fiume. Probabilmente per nascondere qualcosa."
</p><p>Il detective scav&ograve; furiosamente, mentre Anussen lo guard&ograve; con curiosit&agrave; e divertimento. In un paio di minuti, il detective scopr&igrave; una scatola, e aprendola trov&ograve; il denaro rubato nel furto del giorno precedente.
</p><p>"Ecco, ho risolto due casi nel mio primo giorno! &Egrave; andato cos&igrave;", spieg&ograve; il detective soddisfatto di aver un pubblico. "Il ladro ha scavato un buco qui durante la pioggia di questa notte. Ha preso dei sassi dal fiume per coprire il terreno, cos&igrave; tutta la collina &egrave; coperta di sassi - anche se qui della forma sbagliata. Ritornando in paese, &egrave; sceso dalla collina, e probabilmente nel buio ha battuto la testa contro il ramo basso di uno degli alberi. Proseguendo in stato confusionale, &egrave; arrivato in paese dove ha raccontato invece di essere stato aggredito dall'albero."
</p><p>Anussen rimase impressionata dal ragionamento del detective, e voleva complimentarsi con lui. Per&ograve;, non riusciva a fare complimenti alle persone, perch&eacute; cos&igrave; facendo avrebbe ammesso che erano brave, che era contro la sua filosofia. Quindi invece di dire, "Sei un detective bravo", pot&eacute; solo affermare, "Sei un detective poco male".
</p><p>"Hmm, un detective PM. Suona bene, anche se mi piace di meno 'poco male'. Ma tutti potranno decidere per s&eacute; stessi il significato. Grazie per il suggerimento, penso che lo user&ograve;. Mi puoi chiamare il detective PM."
</p><p>"Stai scherzando! Ti chiamer&ograve; invece detectivino."
</p><p>"Non mi piace quel nome. Detective PM per favore. Comunque, sono gi&agrave; due volte in cinque minuti che mi hai assistito. Vuoi venire con me? Torniamo in paese."
</p><p>"Va bene, mi va."
</p><p>"Potresti anche portare la mia cartella, che contiene tutto l'occorrente per fare il detective PM. Grazie, assistente."
</p><p>"Se insisti, ma a me sembra pigrizia da parte tua. E la forchetta di plastica con un rebbio mancante che hai in mano? A che cosa serve?"
</p><p>Il detective PM non voleva confessare che l'aveva rotta quella mattina mentre cercava di indossare il copripoltrona (che indossava ancora), e che non gli era venuto in mente di buttarla via. Disse invece in un tono serio, "Questo &egrave; l'attrezzo pi&ugrave; importante e utile del detective PM! Conservala con cura nella cartella e non dimenticarla mai!"
</p><p>"A me pare invece che tu l'abbia rotta per sbaglio, e che non ti sia venuto in mente di buttarla via."
</p><p>&nbsp;
</p><p>La camera era esattamente come l'aiutante si ricordava. Si possono dimenticare tante cose in 15 anni, ma l'immagine della camera era fissa nella sua testa. I muri di colore giallo chiaro (era riuscita a decidere i colori senza l'interferenza del detective PM), l'armadio con i vestiti esotici e particolari del detective PM che lei non aveva mai voluto cambiare, lo spazio vuoto che non avevano mai deciso come utilizzare (ma che il detective di solito riempiva con i vestiti sporchi indossati qualche giorno prima), ma che era la giusta grandezza per parcheggiare la macchina del tempo. Infine, l&igrave; sul letto, il suo detectivino, dimagrito e pallido, ma sempre lui. L'uomo che aveva catturato il suo cuore con il suo fascino e intelletto, che lei non aveva visto da tanti anni. "Ciao, mio detectivino, sono io."
</p><p>Il detective PM era poco consapevole di quello che gli succedeva intorno, ma rispondeva sempre alla voce dall'assistente.
</p><p>"Ciao cara, sei venuta per assistermi?"
</p><p>"S&igrave;, detectivino, ti aiuter&ograve; a fare un viaggio oggi."
</p><p>"No, non voglio muovermi. Sono stanco, lasciami stare sul letto. Voglio dormire."
</p><p>"Dai, c'&egrave; un caso molto interessante. Qualcuno sta per scomparire, e nessuno sa come accadr&agrave;."
</p><p>Gli occhi brillarono come una volta, anche se il resto del corpo era senza forza. "Non &egrave; ancora sparito? Se fosse gi&agrave; sparito, non sarebbe cos&igrave; interessante. Ma risolvere una scomparsa prima che succeda&hellip; Prover&ograve;."
</p><p>L'aiutante lo aiut&ograve; ad alzarsi, e lo accompagn&ograve; verso la macchina del tempo. "Siediti qui dentro un attimo." Usc&igrave; di nuovo, e pos&ograve; gentilmente sul comodino, con un piccolo bacio, la forchetta di plastica con un rebbio mancante che aveva portato da casa sua. Disse alla camera vuota, "Chiedo scusa assistente, per gli anni di dolore che ti ho creato, perch&eacute; non sapevi che fine abbia fatto il nostro amato detectivino. Per&ograve; ti ho lasciato un indizio, e fra pochissimo capirai che l'ho fatto affinch&eacute; andr&agrave; tutto bene. A dopo."
</p><p>Poi l'aiutante e il detective PM partirono insieme per l'ultimo viaggio.
</p><p>&nbsp;
</p><p>L'assistente era nuovamente da sola nella grande casa. Ma stranamente si sentiva ringiovanita, rifiorita. C'era una giusta speranza per il futuro. Anche se non sapeva tutto, sapeva che si poteva fidare. Era quindi il momento di voltare pagina. Invece di ruminare sempre del suo detectivino (che non avrebbe mai dimenticato), voleva invece iniziare ad aiutare tutti gli altri. S&igrave;, voleva diventare l'aiutante. Non sarebbe stata pi&ugrave; concentrata su s&eacute; stessa, ma sui bisogni altrui.
</p><p>Poi, era inutile continuare a sperare che il detective PM sarebbe riapparso. Adesso, purtroppo, ne era sicura. Doveva chiudere quel capitolo della sua vita, per iniziare quello nuovo. Prese la vecchia cartella del detective PM, che era rimasta non toccata per tre anni in attesa del suo ritorno, e si mise a svuotarla e sistemarne il contenuto. Lente di ingrandimento, enciclopedia, telescopio, forchetta di plastica con un rebbio mancante, &hellip; "Ma cosa fa la forchetta del detectivino qui? &Egrave; stata sul comodino tutto questo tempo! Ed &egrave; ancora sul comodino. Per&ograve; se la stessa forchetta era nella cartella e sul comodino allo stesso tempo&hellip;" Poi cap&igrave; come la forchetta era arrivata e dove era scomparso il detective PM, sorrise, e sper&ograve; una speranza sicura e giusta.
</p><p>&nbsp;
</p><p>L'aiutante gir&ograve; tutte le manopole completamente a destra, per scegliere la data pi&ugrave; futura possibile. "Vediamo cosa ci aspetter&agrave; nel futuro", disse al detective PM. Arrivarono in un batter d'occhio, e l'aiutante usc&igrave; lentamente. Fu accecata dalla brillantezza che la colp&igrave;. Quando gli occhi si aggiustarono alla luce, scorse una magnifica citt&agrave; tutta bianca, con un palazzo glorioso e splendente, sembrava di perla e cristallo, posto sulla collina pi&ugrave; alta. Una strada portava alla citt&agrave;. L'aiutante non aveva parole per descrivere l'aspetto della strada, sembrava di essere d'oro puro, simile a cristallo trasparente.
</p><p>C'erano due persone con vesti bianche vicino alla macchina del tempio che salutarono, "Benvenuti alla Nazione Giustissima, vi stavamo aspettando."
</p><p>"G-g-grazie per il benvenuto", balbett&ograve; l'assistente. Non sapeva quello che doveva aspettarsi, per cui una sorpresa era garantita, ma fu comunque una sorpresa a cui non capiva come rispondere. Si riprese, e si ricord&ograve; della domanda pi&ugrave; importante. "Il mio&hellip; mio marito qui &egrave; molto malato, potete fare qualcosa per lui?"
</p><p>"Certo, nella Nazione Giustissima non c'&egrave; pi&ugrave; la malattia, n&eacute; il dolore, n&eacute; l'ingiustizia. Lo porteremo noi e sar&agrave; guarito. Vedrai che tutto sar&agrave; sistemato, e riavrai il tuo amore. Vieni."
</p><p>L'aiutante scoppi&ograve; a piangere dalla felicit&agrave;, che tutto il dolore era finito. Finalmente avrebbe goduto di nuovo la presenza del suo detectivino. Se solo lei l'avesse saputo e l'avesse sperato prima, una speranza giusta e vera e cos&igrave; meravigliosa avrebbe ammorbidito tanti anni di dolore&hellip; Tra le lacrime, disse, "Un momento, c'&egrave; un'ultima cosa che devo fare." Rientr&ograve; nella macchina del tempo, gir&ograve; le manopole affinch&eacute; ritornassero ai valori di prima, e mise l'autopilota in modo che la macchina del tempo arrivasse a casa sua quando aveva 50 anni. Solo un paio di giorni fa, ma sembrava tutta la sua vita. Non volle girarsi per vedere la macchina del tempo sparire; la Nazione Giustissima e la vita che le stavano davanti erano troppo gloriose per distogliere lo sguardo.
</p>
<h2>Note su "Assistente"</h2>

<p>I viaggi nel tempo appaiono spesso nella letteratura e nei film. Ci sono diversi modi per spiegare come sono possibili.
</p><p><b>Solo futuro:</b> Il modo pi&ugrave; semplice &egrave; di permettere solo viaggi nel futuro, che non creano problemi logici. Infatti, tutti noi stiamo gi&agrave; viaggiando nel futuro! Per velocizzare il viaggio, si possono usare i veri effetti relativistici di una velocit&agrave; vicina a quella della luce oppure i buchi neri (come <i>Interstellar</i>), l'ibernazione (<i>Futurama</i>), o un'invenzione (<i>La macchina del tempo</i> di H. G. Wells). Se per&ograve; si pu&ograve; ritornare dal futuro, si possono creare dei paradossi, come descritti qui sotto.
</p><p><b>Cambiare il passato:</b> Se si viaggia nel passato, il pi&ugrave; piccolo cambiamento pu&ograve; cambiare il futuro. I protagonisti della trilogia <i>Ritorno al futuro</i> all'inizio cercano di non cambiare il futuro, ma dopo averlo fatto inavvertitamente, devono cercare di ripristinare la loro linea temporale. Questo &egrave; il modo pi&ugrave; comune nei film, ma porta al cosiddetto paradosso del nonno: se qualcuno va nel passato e uccide il proprio nonno con la conseguenza che il viaggiatore non era mai nato, come ha potuto uccidere suo nonno? Qualsiasi atto nel passato pu&ograve; rendere il viaggio e l'atto nel viaggio o impossibile o non necessario, creando un paradosso.
</p><p><b>Universi paralleli o multiverso:</b> Per aggirare il paradosso, alcuni usano il concetto di universi paralleli. Quando qualcuno cambia il passato, l'universo inizia una nuova traiettoria, e la persona ritorna non all'universo originale (dove &egrave; scomparsa) ma all'universo parallelo. I nuovi film di <i>Star Trek</i> usano questa idea per raccontare nuove storie dei personaggi originali.
</p><p><b>Curva causale o consistenza logica:</b> Un modo per evitare queste complicazioni &egrave; che il viaggio nel passato non cambia il passato, ma lo determina. Per esempio, in <i>Harry Potter e il prigioniero di Azkaban</i> il protagonista viene salvato da una figura misteriosa che vede di sfuggita a distanza. Pi&ugrave; tardi, viaggia nel passato ed &egrave; lui stesso a salvare la versione pi&ugrave; giovane di s&eacute; stesso. Questo &egrave; come i viaggi nel tempo funzionano in questo racconto. Per&ograve;, non &egrave; senza problemi e possibili paradossi. Per esempio, in questo racconto, come ha imparato l'assistente a pilotare un'astronave? Ha imparato dall'aiutante, che ha imparato quando era pi&ugrave; giovane cio&egrave; l'assistente, che ha imparato dall'aiutante&hellip; L'assistente ha cercato di capire (senza successo) questo paradosso quando ha chiesto del foglio con le coordinate.
</p><p>&nbsp;
</p><p>"Essere un aiuto adatto e utile per lui" - Genesi 2:18. Questo racconto spiega perch&eacute; il detective PM non poteva licenziare l'assistente anche se voleva - in <i>Detective PM</i> c'era "qualche connessione intangibile che li legava" e in <i>Direttore della Giustizia</i> ha pensato, "La vorrei licenziare, ma non ci riesco".
</p><p>&nbsp;
</p><p>"Sperando contro ogni speranza". Una citazione di Romani 4:18, che parla di Abraamo che credette nella promessa di Dio, anche se non c'era nessuna possibilit&agrave; naturale che la promessa sarebbe stata adempiuta. Ci voleva un intervento da parte di Dio. Similmente, l'aiutante desiderava il ritorno del detective PM, anche se era impossibile. Diversamente da Abraamo, l'aiutante non aveva nessun motivo per pensare che il suo desiderio sarebbe stato soddisfatto. Questo introduce uno dei temi di questo racconto: come possiamo essere sicuri di quello che ci succeder&agrave; nel futuro? Che la vita andr&agrave; per il verso giusto?
</p><p>&nbsp;
</p><p>Zafile, Dadlib, e Rafoz sono un riferimento ai tre amici di Giobbe in Giobbe 2:11, e i loro tentativi inutili nei capitoli dal 4 al 31 di spiegare quello che era successo a Giobbe. La spiegazione di Rafoz, con il suo karma, &egrave; quella pi&ugrave; simile a quelle degli amici di Giobbe. Anche se potrebbe sembrare quella pi&ugrave; sbagliata, ha comunque degli elementi giusti. In Luca 13:1-5, Ges&ugrave; spiega perch&eacute; 18 persone sono morte quando una torre &egrave; caduta su di loro. Erano peccatori, e hanno sofferto per la loro ingiustizia. Per&ograve;, non erano pi&ugrave; ingiusti degli altri, n&eacute; di noi. Loro hanno ricevuto quello che meritavano; erano gli altri (come noi) che "ingiustamente" (nel senso legale) non hanno ricevuto quello che meritavano, cio&egrave; non erano gi&agrave; morti. La morte degli altri serve come avvertimento a noi, affinch&eacute; ci ravvediamo, non come incoraggiamento di pensare di essere pi&ugrave; giusti degli altri, come ha pensato l'assistente. Vedi anche 2Pietro 3:9. Questa "ingiustizia" della grazia &egrave; un tema che &egrave; considerato negli altri <i>Racconti della Giustizia</i>.
</p><p>&nbsp;
</p><p>"I dadi della vita che aveva tirato" - un modo di dire nella Nazione della Giustizia, che sta per la fortuna o la sfortuna che una persona ha avuto nella sua vita.
</p><p>&nbsp;
</p><p>"Non era pi&ugrave; grande all'interno che all'esterno" - diversamente da un'altra macchina del tempo, il TARDIS di Doctor Who.
</p><p>&nbsp;
</p><p>"Sono pazze queste ragazze" - un piccolo accenno ai fumetti di Asterix, in cui Obelix dice a volte, "Sono pazzi questi romani", riferendosi alla sigla romana SPQR.
</p><p>&nbsp;
</p><p>Il mendelevio &egrave; l'elemento numero 101, il primo che non pu&ograve; essere prodotto in quantit&agrave; macroscopiche dal bombardamento con neutroni di elementi pi&ugrave; leggeri. Per questo motivo &egrave; pi&ugrave; difficile da creare in confronto agli altri elementi artificiali che lo precedono nella tavola periodica, dall'americio (95) al fermio (100). Siccome non sono ancora conosciuti usi pratici per il mendelevio (oltre alla macchina del tempo!) e decade relativamente velocemente, &egrave; raramente prodotto sulla terra e quello che &egrave; prodotto non rimane per molto tempo.
</p><p>&nbsp;
</p><p>"L'assistente cap&igrave; che se qualcuno veramente sapesse il futuro, varrebbe la pena porre la propria fiducia in quello che dice e promette." Naturalmente quel qualcuno &egrave; Dio. Solo lui pu&ograve; dire "andr&agrave; tutto bene", anche se la sua definizione di 'bene' - la propria gloria, tutto sottomesso a Ges&ugrave; Cristo (Efesini 1:3-14) - non &egrave; forse la nostra definizione di 'bene' - che noi riceviamo tutto quello che vogliamo.
</p><p>&nbsp;
</p><p>La descrizione della Nazione Giustissima somiglia a quella della Nuova Gerusalemme in Apocalisse 21:1-22:5. Il problema con il racconto a questo punto &egrave; che persone ingiuste (imperfette) come l'aiutante e il detective PM non potrebbero entrare in un mondo giusto (perfetto) senza rovinarlo. Per questo noi abbiamo Ges&ugrave; Cristo, in cui siamo dichiarati giusti da Dio, anche se siamo in realt&agrave; ancora ingiusti. Inoltre, Ges&ugrave; ci sta trasformando, e dopo la nostra morte oppure al suo ritorno ci trasformer&agrave; completamente (1Corinzi 15:50-53), in modo che quando entriamo nella Nuova Gerusalemme (cio&egrave; il paradiso o il cielo), saremo veramente giusti.
</p><p>&nbsp;
</p><p>Per capire meglio gli eventi del racconto, &egrave; possibile riordinarli nella linea temporale dell'assistente:
<br /><i>Da piccola:</i>
<br />La famiglia perde tutto, i genitori si separano, diventa cinica.
<br /><i>20 anni:</i>
<br />Vive in una baracca e si chiama Anussen. Conosce l'assistente e l'aiutante, e parte con loro.
<br />Va 30 anni nel futuro (nella casa dell'aiutante), costruisce la macchina del tempo.
<br />Va nell'astronave per prendere il mendelevio.
<br />Ritorna a 30 anni nel suo futuro.
<br />Ritorna al suo tempo, schianta e perde i ricordi del viaggio.
<br />Conosce il detective PM, diventa l'assistente.
<br /><i>27 anni:</i>
<br />Il racconto Detective PM.
<br /><i>30 anni:</i>
<br />Si ravvede del suo atteggiamento sarcastico verso il detective PM e gli altri, nel racconto Direttore della Giustizia.
<br /><i>32 anni:</i>
<br />Sposa il detective PM (dopo che anche il detective PM cambia atteggiamento verso di lei).
<br /><i>35 anni:</i>
<br />Scomparsa del detective PM.
<br /><i>38 anni:</i>
<br />Incontra l'aiutante.
<br />Partono insieme, vanno 18 anni nel passato per prendere l'ausiliare, 12 anni nel futuro per costruire la macchina del tempo, sull'astronave, 12 anni nel futuro, e poi nel suo tempo.
<br />Scopre che la forchetta sul comodino non era del detective PM, e capisce che era lasciata dall'aiutante che aveva preso il detective PM.
<br />Cambia nome in aiutante.
<br /><i>50 anni:</i>
<br />Appare una macchina del tempo, che si aspettava (perch&eacute; aveva gi&agrave; fatto un viaggio 12 anni fa con s&eacute; stessa quando aveva quell'et&agrave;).
<br />Parte per prendere l'assistente e poi l'ausiliare, poi torna a casa sua, nell'astronave, a casa sua, poi accompagna l'assistente a 12 anni prima.
<br />Va a 15 anni prima del suo tempo, quando aveva 35 anni, e prende il detective PM, lasciando una forchetta.
<br />Va nel lontano futuro, nella Nazione Giustissima, dove il detective PM &egrave; guarito e vivono insieme.
<br />Manda la macchina del tempo indietro, affinch&eacute; lei la trovi quando aveva 50 anni.
</p><p>Oppure la linea temporale della macchina del tempo:
<br />Lo scienziato la progetta, ma non la pu&ograve; costruire.
<br />L'aiutante, l'assistente, e l'ausiliare portano i componenti e piani 30 anni nel futuro, dove la costruiscono.
<br />Vanno nel futuro per prendere il mendelevio scaduto, e ritornano al tempo dell'aiutante per completarla.
<br />L'aiutante la usa per riportare l'assistente al suo tempo, prendere il detective PM, e andare alla Nazione Giustissima.
<br />La manda a s&eacute; stessa quando aveva 50 anni.
<br />L'aiutante la usa per prendere l'assistente e poi l'ausiliare. Ritornano insieme per costruire la macchina del tempo, incluso un viaggio nell'astronave.
<br />L'ausiliare la usa per ritornare al suo tempo, ma manca l'energia e la macchina del tempo si schianta e viene distrutta.
</p>
<?
require("../piede.php");
?>
