<?
$descriz = "Detective PM: uno dei Racconti della Giustizia";
$key = "detective pm, racconti della giustizia";
$titolo = "Detective PM";
$sezione = "Strumenti";
$sezioneurl = "/racconti_giustizia/";
require("../capo.php");
?>
<h1>Detective PM</h1>
<p>"S&igrave; che questa &egrave; la vita giusta!", url&ograve; l'uomo con entusiasmo. Era un uomo molto anormale, in quanto esattamente normale sotto ogni aspetto. Aveva un quoziente d'intelligenza di 100 precisi. L'altezza e il peso erano la media per il suo paese. Non aveva nessuna qualit&agrave; che lo faceva notare. Dopo che usciva con una comitiva, gli altri non si ricordavano se fosse stato presente o no. Semplicemente, era straordinariamente ordinario.
</p><p>L'uomo si sentiva limitato dalla sua normalit&agrave;. La sua natura garantiva che non poteva mai fare qualcosa di straordinario. Ma finalmente, mentre si avvicinava alla citt&agrave;, sperimentava la libert&agrave;, la libert&agrave; dalla normalit&agrave;. Era anche un modo anormale per entrare in citt&agrave;, quasi verticalmente e a velocit&agrave;. L'uomo era emozionato da fatto che faceva una cosa diversa dagli altri. Mentre volava in aria, era lontano dalle aspettative altrui. Non c'era nessun altro di cui essere la media, c'era solo lui. Dopo anni di non spiccare, era riuscito a spiccare in volo.
</p><p>Sfortunatamente per l'uomo medio, i suoi sentimenti di libert&agrave; non erano giusti e non corrispondevano alla realt&agrave;. Non era ancora del tutto libero dalla forza di gravit&agrave;, che era un'occasione di caduta per lui. Cos&igrave;, dopo aver goduto la sua ingannevole libert&agrave; per troppo poco tempo, la terra venne a trovarlo rapidamente in un incontro terrificantemente violento e assolutamente normale per qualcuno che cade da una grande altezza.
</p><p>&nbsp;
</p><p>Il detective fu svegliato da un bussare indesiderato. Aveva scoperto tanto tempo fa che il modo migliore per evitare una cosa non voluta era di decidere che non esisteva. Se per il detective non esisteva, non poteva disturbarlo pi&ugrave;. Quindi si rotol&ograve; nel letto e si riaddorment&ograve;. Per&ograve; era un bussare inesistente insistente, e fu risvegliato di nuovo.
</p><p>"Detective? &Egrave; a casa? Risponda subito per favore!"
</p><p>Il detective riconobbe la voce; era il giudice. Probabilmente un nuovo caso noioso che il giudice non era in grado di risolvere.
</p><p>"Detective? C'&egrave; un nuovo caso che non sono in grado di risolvere. Potrebbe sembrare noioso, ma proprio per questo motivo &egrave; molto interessante."
</p><p>Il detective non ci credeva, ma cap&igrave; che non c'era modo per ignorare il giudice per sempre. Si rotol&ograve; dal letto e apr&igrave; la porta.
</p><p>"Che cos'&egrave; questa volta?", chiese al giudice con la voce di qualcuno che &egrave; stato trascinato involontariamente dal suo dolce sonno.
</p><p>"Detective, &egrave; stato trovato&hellip;"
</p><p>"Detective PM, per favore, signor giudice."
</p><p>Il giudice sospir&ograve; per questa pedanteria che insisteva sul suo titolo completo, che occorreva ogni volta che si parlavano.
</p><p>"Detective PM, &egrave; stato trovato un cadavere in un campo appena fuori della citt&agrave;. Non siamo riusciti a capire niente di quello che &egrave; successo. Per&ograve; io devo far valere la giustizia in questo nostro paese, e per fare ci&ograve; devo sapere se &egrave; stato un incidente, un suicidio, o un omicidio."
</p><p>Il detective si trattenne&hellip;
</p><p>"Detective PM, per favore", mi interruppe maleducatamente. "Vale anche per te."
</p><p>Mi scuso, detective PM. Come dicevo&hellip;
</p><p>Il detective PM si trattenne un momento, aspettando ulteriori dettagli del caso. Avendo percepito che il giudice aveva esaurito tutta la sua conoscenza dei particolari, rispose, "E che cosa c'&egrave; di cos&igrave; interessante di questo caso?"
</p><p>"Assolutamente niente. Questo &egrave; quello che lo rende cos&igrave; interessante."
</p><p>Di nuovo una piccola pausa imbarazzante, mentre l'incomprensione e la mancava di spiegazioni giravano nell'aria come una puzza di cui nessuno vuole dire qualcosa. Finalmente il detective PM cedette e chiese in che senso.
</p><p>"Il cadavere &egrave; di un uomo, siamo riusciti a stabilire questo fatto."
</p><p>"Meno male", pens&ograve; il detective PM, "non &egrave; del tutto senza cervello."
</p><p>"Per&ograve;, del resto non c'&egrave; praticamente niente da dire. L'uomo &egrave; assolutamente normale. Praticamente impossibilmente normale. Cos&igrave; il caso diventa forse, magari, possibilmente interessante?" Il giudice sperava in una risposta positiva, per allettarlo affinch&eacute; decidesse di esaminare il caso.
</p><p>"Non c'&egrave; molto su cui lavorare, ma probabilmente siete arrivati a questa conclusione perch&eacute; non avete fatto un buon lavoro. A volte ci vuole un esperto come me per vedere quello che l'occhio dilettante non vede. Siccome mi ha gi&agrave; svegliato, tanto vale sprecare il resto della giornata seguendo questo caso. Per&ograve; non posso senza la mia assistente, per cui se non Le dispiace, approfitter&ograve; di questo tempo per dormire ancora. A dopo!"
</p><p>"Mi sono permesso di far chiamare la Sua assistente, fiducioso della Sua buona volont&agrave; per aiutarci."
</p><p>Proprio allora, l'assistente gir&ograve; l'angolo e il detective PM la scorse. "Ha l'abitudine di apparire sempre nei momenti inopportuni", pens&ograve; il detective PM tra s&eacute; e s&eacute;. "Se non fosse stata cos&igrave; veloce, avrei potuto dormire ancora un pochino. E poi, dice sempre delle cose inappropriate. Non so perch&eacute; non la licenzio."
</p><p>"Buon giorno, mio detectivino", lo salut&ograve; l'assistente con una voce allegra. "Hai un bellissimo aspetto stamattina. Oppure &egrave; gi&agrave; pomeriggio?"
</p><p>Il detective PM si ricord&ograve; subito perch&eacute; non riusciva a licenziarla: era troppo cattiva con lui. Non solo non aggiungeva PM al suo titolo, ma si permetteva di inventare e usare quel diminutivo che tanto odiava. Inoltre, il sarcasmo e cinismo&hellip; Appena svegliato, il detective PM non era affatto di bell'aspetto, con i capelli in aria. Indossava dei vestiti variopinti per dormire che aveva trovato per terra in due stanze diverse la sera prima (oppure due sere fa? non si ricordava pi&ugrave;) di colore rosa fluorescente, blu fosforescente, e verde che appariva efflorescente, con tanti grandi cerchi di altri colori. Aveva una sola scarpa, quello che sembrava un pezzo di pane verde attaccato alla guancia, e una forchetta di plastica con un rebbio mancante che spuntava fuori dalla tasca di quello che poteva possibilmente essere una camicia. Certo, l'assistente lo trattava male, ma come si sarebbe comportata se fosse la sua ex-assistente? Forse ancora pi&ugrave; cattiva. Meglio non pensarci e sopportarla cos&igrave; come era. Inoltre, c'era qualche connessione intangibile che li legava, che il detective PM non poteva identificare ma neanche rompere.
</p><p>"Buon giorno, assistente." Cerc&ograve; di ristabilire l'ordine giusto del rapporto, cio&egrave; che lui era superiore, facendole fare qualche compito servile. "Assistimi gentilmente&hellip;ah", guardandosi intorno per un compitino banale adatto al suo scopo, "&hellip;ah&hellip;", guardando ancora, "ah&hellip;prendendo la posta? Poi seguimi mentre accompagno il giudice a dove inizier&ograve; le mie indagini su un nuovo caso."
</p><p>"Sissignore, subito capo!" L'assistente prese qualche lettera e pubblicit&agrave;, ci diede un'occhiata, poi conserv&ograve; tutto con cura nella sua cartella, prima di correre dietro al detective PM e al giudice, che erano gi&agrave; avviati.
</p><p>&nbsp;
</p><p>Arrivarono al prato dove era stato trovato il cadavere. Il giudice sapeva che il detective PM avrebbe fatto uno spettacolo per mostrare a tutti la sua bravura nell'osservazione, nella raccolta di indizi, e nelle deduzioni, costruendo tutta la storia di una persona dai minimi dettagli. Era fastidioso, ma era un prezzo che doveva sopportare se voleva l'aiuto del detective PM. Almeno oggi forse era giusto, pens&ograve; con un piccolo sorriso: si sarebbe comportato da pavone, tale come era vestito.
</p><p>Il detective PM gir&ograve; intorno al cadavere, che giaceva pancia in gi&ugrave;. "Ecco un uomo&hellip;"
</p><p>"Fin qui ci sono arrivato anch'io", gli ricord&ograve; il giudice.
</p><p>"&hellip;di mezz'et&agrave;. Il corpo manifesta ferite nella faccia, addome, e la parte anteriore delle gambe, come se fosse caduto cos&igrave; da una grande altezza."
</p><p>"Chiaramente &egrave; morto di cause naturali", decise l'assistente. Tutti la guardarono con stupore.
</p><p>"Cosa dici?! Si capisce perch&eacute; io sono il Detective PM e tu solo un'assistente. Guarda queste ferite, ovviamente &egrave; stata una caduta che l'ha ucciso."
</p><p>"Infatti, &egrave; molto naturale. L'uomo si trovava in aria, e forse non capiva la gravit&agrave; della sua situazione. La causa naturale del suo decesso &egrave; l'attrazione che la terra ha verso tutti gli oggetti nella natura che si trovano in aria."
</p><p>Gli sguardi di stupore si trasformarono in sguardi di sdegno per questo intervento, e il detective PM prosegu&igrave; come se niente fosse. "Quindi basta capire da che cosa era caduto."
</p><p>Guard&ograve; in su, ma non c'era neanche una nuvola nel cielo.
</p><p>"Che in questo momento non &egrave; evidente, per cui ritorneremo all'origine della caduta in un secondo momento. Vediamo invece quello che il cadavere mi rivela dell'identit&agrave; dell'uomo."
</p><p>Il detective esamin&ograve; attentamente ogni aspetto del corpo. "Segni particolari&hellip; nessuno. Fango sulle scarpe&hellip; nessuno. Vestiti&hellip; tipici. Tasche&hellip; vuote. Profumo&hellip; niente di particolare."
</p><p>Il giudice si godeva lo spettacolo, mentre il detective PM diventava sempre pi&ugrave; disperato. 
</p><p>"Unghie&hellip; normali, senza sporcizia. Capelli&hellip; niente di particolare. Abbronzatura&hellip; nessuna."
</p><p>"Come sta andando, Detective PM, qualche grosso indizio?", chiese innocentemente il giudice, sapendo che non c'era.
</p><p>"Ancora no. Assistente, senza dire una parola, aiutami a girarlo un po' affinch&eacute; io possa vedere meglio la faccia."
</p><p>Con qualche sforzo, riuscirono a sollevare leggermente la testa. Il detective chiese all'assistente di prendere il suo righello dalla cartella, e inizi&ograve; a misurare le dimensioni della faccia. "Inter occhi: normale. Larghezza bocca: tipica. Lunghezza naso: nella norma. Circonferenza testa: regolare. Insomma, niente di particolare, questa faccia non mi dice niente."
</p><p>Il giudice era contento: il detective PM era ovviamente perplesso e a suo disagio, ma non lo voleva ancora ammettere.
</p><p>"Tieni", disse il detective PM consegnando il righello all'assistente, che lo rimise nella cartella. Allo stesso tempo, prese la posta e disse al detective PM, "Se posso dire qualcosa&hellip;"
</p><p>"No, non puoi. Ti ho detto di non dire una parola, non ho tempo per le tue sciocchezze, devo concentrarmi."
</p><p>Il giudice invece non si era divertito cos&igrave; tanto da molto tempo. "Quel presuntuoso sar&agrave; sgonfiato questa volta."
</p><p>Il detective PM gir&ograve; intorno al corpo, guard&ograve; in alto, sempre pi&ugrave; disperato per qualsiasi indizio. Chiese la lente di ingrandimento dall'assistente, che gli diede invece la posta.
</p><p>"Cosa fai?! Come posso risolvere il caso se non mi aiuti. Concentrati! Lente di ingrandimento, ho detto." L'assistente riprese la posta e consegn&ograve; la lente, con cui il detective PM esamin&ograve; ogni centimetro quadrato della pelle. Niente. Tagli&ograve; un angolo dai vestiti e lo bruci&ograve;: la stoffa era un materiale tipico senza contaminazione esterna.
</p><p>"Dammi subito l'enciclopedia!", grid&ograve; il detective PM alla sua assistente. Secondo il giudice, non avrebbe trovato niente da controllare nell'enciclopedia, ma doveva pure fare qualcosa per continuare lo spettacolo.
</p><p>Di nuovo l'assistente gli pose la posta, tentando un semplice, "Per&ograve; detectivino&hellip;"
</p><p>"Basta con questa posta!", strill&ograve; buttando tutta per terra. "Quando voglio leggere la posta, te lo chieder&ograve;. L'enciclopedia! E non interrompere."
</p><p>Mentre l'assistente dava silenziosamente l'enciclopedia, il giudice raccolse la posta sparsa, e diede un'occhiata alla pubblicit&agrave; per passare un po' di tempo mentre il detective PM faceva una brutta figura.
</p><p>Il detective PM prosegu&igrave; con i suoi esperimenti e ispezioni sempre pi&ugrave; improbabili e incredibili. Mormor&ograve; briciole di frasi come "vento dal sud, quanto forte&hellip;", "distanza dalla strada&hellip;", "velocit&agrave; della rotazione della terra a questa latitudine&hellip;", "avvistamenti di oggetti volanti nelle ultime 24 ore&hellip;", mentre gesticolava con le mani, le gambe, e qualsiasi altro membro del corpo che riusciva a muovere. Dopo ulteriori dieci minuti, il detective PM raggiunse il giudice come uomo battuto. "Mi dispiace, ma proprio non riesco a capire niente di questo caso. N&eacute; chi &egrave; l'uomo n&eacute; come &egrave; morto. Lui &egrave; assolutamente&hellip; normale."
</p><p>"Sicuramente &egrave; pi&ugrave; dispiaciuto perch&eacute; deve ammetterlo piuttosto che per il fatto non capisce niente", pens&ograve; il giudice mentre cercava di nascondere il suo sorriso e la sua felicit&agrave;. "Posso invece proporre qualche piccola osservazione, che potrebbe essere di aiuto per le indagini?"
</p><p>"S&igrave; certo, anche se senz'altro io ci ho gi&agrave; pensato ma ho ritenuto che non fosse abbastanza importante da riferire a tutti", rispose il detective PM.
</p><p>"Allora, si chiamava Norm. Non era del nostro paese, infatti non aveva una dimora fissa. Ma si trovava qua da&hellip;" Una pausa per fare un effetto drammatico. "&hellip;pochi giorni."
</p><p>Il detective PM rimase bloccato, sbalordito. Il giudice non si divertiva cos&igrave; da anni.
</p><p>"Posso provare anch'io?", chiese contenta l'assistente.
</p><p>"Certo, ci sono abbastanza indizi per tutti", rispose con gioia il giudice.
</p><p>"Allora giudice, se esaminiamo pi&ugrave; attentamente l'evidenza e facciamo dei ragionamenti pi&ugrave; precisi, credo che possiamo essere pi&ugrave; specifici e dire che era nel nostro paese da tre giorni precisi. Inoltre, molte persone venivano a trovarlo anche se aveva pochi amici."
</p><p>"Basta voi due. Mi prendete in giro! State inventando tutto questo."
</p><p>"Niente affatto, mio caro detectivino. Nella posta che mi hai fatto raccogliere oggi c'era anche la pubblicit&agrave;, inclusa quella del circo che &egrave; appena arrivato in paese. Ho cercato di dartela diverse volte. Tieni."
</p><p>Nel foglietto c'era infatti l'annuncio degli spettacoli del circo, che si era stabilito nel campo adiacente ad una distanza di una cinquantina di metri da dove era ritrovato il corpo, e che avrebbe fatto il primo spettacolo quella sera. Oltre alle immagini degli acrobati, il domatore di leoni, i pagliacci, l'uomo pi&ugrave; forte del mondo, la donna pi&ugrave; bassa, i gemelli siamesi, c'era anche lui: "Norm, l'uomo pi&ugrave; normale del mondo." C'era anche la lista di tutte le citt&agrave; della tourn&eacute;e, che erano tanti. Lo spettacolo precedente era stato cinque giorni prima, in una citt&agrave; che ci voleva un giorno per raggiungere.
</p><p>Il giudice cerc&ograve; di sopprimere il fatto che ridacchiava, ma con poco successo. Pens&ograve; che la giustizia per la presunzione del detective fosse stata fatta.
</p><p>"Allora, come pensa di procedere con l'indagine", chiese il giudice al detective PM. "Magari un'uscita al circo?"
</p><p>Il detective PM si riprese e mise il suo atteggiamento migliore da detective, come qualcuno che indossa i suoi vestiti migliori per un matrimonio. Che non era facile, dato che era ancora vestito in quello in cui si era imbattuto per dormire. Non dava proprio l'impressione di un detective serio, tanto meno un detective PM.
</p><p>"S&igrave;, andiamo al circo e vediamo quello che possiamo scoprire di Norm."
</p><p>"Io devo tornare adesso in tribunale per rendere la giustizia in alcuni processi", si scus&ograve; il giudice. "Voi continuate con il caso, e torner&ograve; stasera per sapere quello che avrete scoperto. Si ricordi, devo sapere se era un omicidio, un suicidio, o un incidente. E se un omicidio, chi l'ha fatto. Solo cos&igrave; sar&agrave; fatta la giustizia. E lo voglio sapere prima che la voce del cadavere si sparga e che arrivi qualche mercenario di giustizia."
</p><p>"O peggio ancora, un propiziatore, a cui non interessa che il colpevole &egrave; punito", aggiunse l'assistente.
</p><p>Subito la faccia del giudice si oscur&ograve;, e minacci&ograve;, "Non parli male del Propiziatore, non lo permetter&ograve; mai. Intesi?" Poi part&igrave;.
</p><p>&nbsp;
</p><p>Il direttore del circo stava all'entrata del circo, dirigendo tutti mentre preparavano e provavano per lo spettacolo di quella sera. Scorse il detective PM e l'assistente mentre si avvicinavano, e mormor&ograve; a bassa voce, "Pare che costui aspiri ad un provino come pagliaccio, ma ignoro quello che voglia colei."
</p><p>"Signoooora e signore", strill&ograve; quando lo raggiunsero, "benvenuti all'ottava meraviglia del mondo, il pi&ugrave; stupefacente, strabiliante, emozionante circo di tutto il mondo! Sarete stupiti dall'entusiasmante spettacolo&hellip;"
</p><p>"Grazie", interruppe il detective PM, "ma non siamo qui n&eacute; per lo spettacolo n&eacute; per la pubblicit&agrave;. Io sono il Detective PM e questa &egrave; la mia assistente."
</p><p>"La supplico di espormi il significato di PM."
</p><p>"Secondo Lei, cosa pu&ograve; essere?"
</p><p>Il direttore riflett&eacute; per alcuni secondi, pensando quanto arduo fosse pronosticare in una questione di cui si era ignoranti. Cionondimeno, ispezion&ograve; nuovamente la sembianza del detective PM, e azzard&ograve;, "Pagliaccio mediocre?"
</p><p>"Se questo &egrave; giusto secondo Lei, va bene. Come dico sempre, ogni gusto &egrave; giusto. Allora, sono il Detective PM. Sto indagando&hellip;"
</p><p>"&hellip;cio&egrave; stiamo indagando", profer&igrave; l'assistente.
</p><p>"Io sto indagando con l'aiuto della mia assistente per conto del giudice di questa citt&agrave;. C'&egrave; qualcuno che lavora nel circo di nome Norm?"
</p><p>"Affermativo. Si esibisce come 'L'uomo pi&ugrave; normale del mondo'. Principia a riscuotere il successo e la popolarit&agrave;, e contribuisce a rendere il nostro circo il pi&ugrave; prodigioso, eccezionale, strord&hellip;".
</p><p>L'assistente, piuttosto stufa del dizionario vivente, tronc&ograve; la discussione. "Per&ograve;, Norm &egrave; ora normalmente, prodigiosamente, e eccezionalmente morto."
</p><p>Il direttore si ferm&ograve;, stupito, sorpreso e stupefatto. "Ma non doveva&hellip; cio&egrave; non &egrave; possibile&hellip; cio&egrave;&hellip; Ritengo che sia meglio discorrere con il domatore di leoni. Lo troverete nel tendone. &Egrave;&hellip; cio&egrave;, era il suo amico migliore, e vi riveler&agrave; tutto quello che volete sapere. In questo momento, devo sbrigare alcune faccende per preparare il grandioso spettacolo staserale. Se vi necessita di qualsivoglia cosa, sopraggiungetemi."
</p><p>Cos&igrave; dicendo, si precipit&ograve; verso una delle piccole tende raggruppate intorno al tendone. Il detective PM e l'assistente si guardarono, e non avendo altre possibilit&agrave;, si avviarono verso il tendone.
</p><p>&nbsp;
</p><p>"Devo sbrigarmi, se il Direttore trova tutta questa roba per terra, saranno guai!" L'uomo mormorava tra s&eacute; e s&eacute; per incoraggiarsi nel suo ingrato compito di raccogliere tutti i pezzi colorati all'entrata del tendone. Non gli piaceva farlo, ma toccava a lui. Vide l'uomo, vestito in modo simile alla spazzatura che prendeva, e la donna fare i 10 metri dall'entrata del circo, che gli diede abbastanza tempo per prepararsi.
</p><p>"Uomo della pulizia, mi pu&ograve; indicare dove potr&ograve; trovare il domatore di leoni?", chiese educatamente l'uomo.
</p><p>"Ti sbagli, non sono l'uomo della pulizia, sono solo il palloncinista."
</p><p>"Palloncinista? Che cosa sarebbe?", chiese la donna.
</p><p>"Grazie per avermelo chiesto! Posso creare qualsiasi forma con i palloncini." Gonfi&ograve; con un soffio veloce i tre palloncini che aveva appena preso, li chiuse e li leg&ograve; fra di loro per creare un cagnolino.
</p><p>"Vuoi un regalo per la tua ragazza?", chiese al detective PM. "Un cuoricino, un mazzo di fiori, un cupido&hellip;".
</p><p>"Non sono mica la sua ragazza!", rispose l'assistente subito, ma si arross&igrave; leggermente, che sperava non fosse visibile.
</p><p>"Allora abbiamo sbagliato tutti e due con le nostre supposizioni. Per farmi perdonare, vi offro un animale a vostra scelta. Giraffa, coccodrillo, vombato, dinosauro, bruco, &hellip; Che cosa volete?"
</p><p>"Grazie, ma non &egrave; necessario, invece ci pu&ograve; aiutare&hellip;".
</p><p>"Va bene, niente animale. Un edificio? Taj Mahal, teatro dell'opera di Sydney? Personaggi famosi? Giulio Cesare, &hellip;"
</p><p>Mentre parlava, le mani volavano per creare tutti questi oggetti con i palloncini. Il detective PM dovette troncare l'elenco, altrimenti sarebbe rimasto l&igrave; per ore.
</p><p>"Tutti belli, ma non possiamo portare in giro dei palloncini in questo momento, dobbiamo lavorare."
</p><p>"Se aspettate qui un minuto, prendo la mia bombola di elio, che uso di solito per gonfiare i palloncini. Cos&igrave; la forma galleggia in aria, che &egrave; molto pi&ugrave; facile portare in giro."
</p><p>"Purtroppo, dobbiamo comunque rifiutare la sua generosa offerta. Ci pu&ograve; invece indicare dove possiamo trovare il domatore di leoni?"
</p><p>"Va bene", rispose il palloncinista evidentemente deluso, "volevo solo farvi un piacere. Comunque, il domatore sta provando il suo numero per stasera alla pista centrale del tendone."
</p><p>Con un saluto e un ringraziamento, ma senza un palloncino, il detective PM e l'assistente andarono a trovare il domatore.
</p><p>&nbsp;
</p><p>Il domatore di leoni era un uomo alto e snello. La sua maglia monospalla lasciava intravedere molti graffi e cicatrici sul corpo. La maglia era di color giallo con macchie nere e marroni. Aveva l'aspetto di una pelle di un animale, ma in realt&agrave; la stoffa era di cotone. Il domatore era molto sensibile verso gli animali. Non voleva fare male a loro in nessun modo: non solo non avrebbe mai indossato vestiti fatti da animali, ma era pure vegano. Aveva la frusta in mano, ma gli si stracciava il cuore ogni volta che la doveva usare. C'erano due leoni fuori dalla gabbia, che esercitavano il loro spettacolo saltando fra gli sgabelli. Il domatore era concentrato e non si rese conto dell'arrivo del detective PM e dell'assistente. I leoni erano pi&ugrave; percettivi e ruggirono quando il detective PM era a distanza di un balzo. Ci&ograve; disturb&ograve; i tempi della prova, in modo che i due leoni si scontrassero in aria mentre facevano il prossimo salto. Il domatore vers&ograve; una lacrima quando diede un colpo con la frusta; piangendo, supplic&ograve; i leoni, "Per favore, non sbagliate cos&igrave;, non voglio farvi male."
</p><p>"Con permesso", il detective PM si fece notare. "Vorrei parlarle del Suo amico Norm."
</p><p>"Sa dov'&egrave;? Non l'ho visto stamattina. Di solito facciamo la colazione insieme."
</p><p>"Non so in quale modo dirle questo ma&hellip;".
</p><p>"&hellip;ma &egrave; morto in un modo terribile", concluse la frase l'assistente.
</p><p>"&hellip;ma sicuramente non era quello il modo in cui gliel'avrei detto", spieg&ograve; il detective PM all'assistente, che ancora una volta non fu di gran aiuto.
</p><p>Il domatore svenne.
</p><p>Quando si riprese, vide due facce brutte e sconosciute, di persone che gli davano degli schiaffi e versavano acqua sulla sua testa. "Basta", strill&ograve;. Il suo secondo pensiero era per i leoni. "Micio? Sofficina? Dove siete?"
</p><p>Salt&ograve; in piedi, anche se gli girava ancora la testa. Per&ograve; era il pensiero che i suoi amati felini mancavano che gli faceva pi&ugrave; male. Guard&ograve; in ogni direzione. Finalmente li trov&ograve;. Micio aveva i peli della criniera imbrogliati con le strisce di un mocio che era l&igrave; vicino, e ogni volta che si muoveva o si girava veniva colpito dal manico. Sofficina invece aveva le zampe annodate intorno ad una sbarra della gabbia. Tutti e due piagnucolavano.
</p><p>"Ah, Micio, Sofficina, mi dispiace, arriva pap&agrave;!" Poi rivolgendosi al detective PM e all'assistente, "Cosa avete fatto ai miei gattini, voi mostri!"
</p><p>"Per forza abbiamo dovuto difenderci, non era colpa nostra", si difese il detective PM preso alla sprovvista. "Quando Lei &egrave; svenuto, ci siamo trovati davanti due leoni sconosciuti. Dovevamo assicurare in qualche modo non solo la nostra incolumit&agrave;, ma anche quella di tutto il circo. Per fortuna aveva con me questa forchetta", continu&ograve; sventolando la forchetta di plastica con un rebbio mancante, "altrimenti saremo stati in pasto ai leoni."
</p><p>Il domatore non era ancora molto contento per quello che avevano fatto ai suoi leoni, ma si ammorbid&igrave; leggermente, simpatizzando con loro per la situazione critica in cui si erano trovati. "Mi dispiace per lo spavento, ma in realt&agrave; Micio e Sofficina non vi avrebbero fatto del male, sono troppo gentili. Potete aiutarmi a liberarli, e anche raccontarmi quello che &egrave; successo a Norm?"
</p><p>Mentre l'assistente snodava Micio, il detective PM aiut&ograve; il domatore a slegare i peli di Sofficina. Poi gli spieg&ograve;, "Il corpo di Norm &egrave; stato trovato stamattina nel campo accanto al circo, non c'&egrave; nessun segno nell'erba di impronte, nessuno era andato a quel posto."
</p><p>"Ma come &egrave; morto?"
</p><p>"Noi abbiamo da poco iniziato le indagini, per cui non lo possiamo dire ancora."
</p><p>"Voi indagate? Ma chi siete?"
</p><p>"Chiedo scusa, con lo svenimento e il panico della battaglia con i leoni, ci siamo dimenticati di presentarci. Io sono il Detective PM, e questa &egrave; la mia assistente."
</p><p>L'assistente fece un saluto, proprio nel momento in cui riusc&igrave; a liberare Micio.
</p><p>"PM? Cio&egrave; un pubblico ministero?"
</p><p>"Se vuole che io sia cos&igrave;, va bene. Come dico sempre, ad ogni gusto il proprio giusto. Comunque, il direttore di circo ci ha detto che era l'amico di Norm. Da quanto tempo vi conoscevate?"
</p><p>"Da quando eravamo a scuola insieme."
</p><p>"Quale scuola?"
</p><p>"Elementare, mio caro detective PM."
</p><p>"Lo pu&ograve; descrivere? Che tipo di persona era? Che cosa faceva nel circo?"
</p><p>Il domatore fece una breve pausa. Gli veniva da piangere pensando di nuovo al suo amico. Gli gir&ograve; la testa, ma riusc&igrave; a sedersi sullo sgabello da cui aveva appena liberato Sofficina, e inizi&ograve; a dare al leone delle coccole, che lo rafforz&ograve;. "&Egrave; difficile descrivere Norm. Era cos&igrave;&hellip;".
</p><p>"Normale?", sugger&igrave; l'assistente.
</p><p>"S&igrave;, normale, ecco la parola che cercavo. Non c'era niente che lo faceva notare. Non era n&eacute; fra i migliori n&eacute; fra i peggiori della classe. Anche per lo sport. Anche, dopo la scuola, a lavoro."
</p><p>"Dove lavorava?", approfond&igrave; il detective PM.
</p><p>"In un negozio."
</p><p>"E che tipo di negozio?"
</p><p>"Alimentare, mio caro detective PM. Comunque, se posso proseguire, era normale in tutto quello che faceva. Tutto questo gli pesava. Voleva essere importante per qualcosa, farsi notare. Cos&igrave; si &egrave; unito al circo, per fare parte di uno spettacolo in cui tutti lo avrebbero guardato e ammirato la sua normalit&agrave; piuttosto di ignorarlo. Naturalmente, non poteva esibirsi nello spettacolo, non essendo abbastanza bravo in niente (pur non essendo totalmente negato in tutto, era sempre nella media). Era invece uno dei fenomeni da baraccone, 'l'uomo pi&ugrave; normale del mondo'. Ha cominciato ad avere un modesto successo, n&eacute; poco n&eacute; troppo."
</p><p>"Con questo successo era pi&ugrave; felice?"
</p><p>"Felice no, ma non era mai triste neanche. Il problema a questo punto era che aveva realizzato il suo sogno di entrare nel circo, di essere notato, ma il sogno non gli aveva dato la soddisfazione che cercava. Sapete, l'unica cosa peggiore di non raggiungere il proprio obiettivo, &egrave; di raggiungerlo e scoprire di rimanere insoddisfatto."
</p><p>"Posso dire che la sua idea era fallimentare, mio caro domatore?", l'assistente inser&igrave; con un sorrisetto.
</p><p>"No, non pu&ograve;", rispose il domatore, stufo delle interruzioni e delle battute dell'assistente, che si riteneva spiritosa e intelligente. Poi continu&ograve; come se niente fosse. "Norm ha cos&igrave; cominciato quindi a parlare sempre di libert&agrave;. Voleva essere libero, di poter fare quello che voleva."
</p><p>"Ma era libero, non era mica in prigione, aveva scelta di fare parte del circo, e poteva lasciarlo quando voleva."
</p><p>"La libert&agrave; non &egrave; l'assenza di sbarre. Considerate questi bellissimi leoni. Sono pi&ugrave; liberi adesso che sono con me di quanto lo siano in gabbia con la porta chiusa? O quando sono nella savana? Nella savana possono correre, ma possono correre dove vogliono? No, devono andare alla caccia altrimenti muoiono di fame."
</p><p>"Per&ograve;, nella savana sarebbero liberi di essere leoni", disse il detective PM.
</p><p>"Oppure, da un altro punto di vista, sarebbero costretti a comportarsi da leoni. Non sono liberi di comportarsi in un altro modo che quello che la loro natura determina. Il paragone con i leoni a questo punto non regge pi&ugrave;, ma se non volessero essere leoni? Possono cambiare? Sono liberi di diventare giraffe se volessero? Ovviamente no. Come si dice, un leopardo non pu&ograve; cambiare le sue macchie. Considerate invece quello che io ho fatto: con tanto amore per i miei carissimi felini, sono riuscito a cambiare il loro carattere. Adesso trovano piacere nelle coccole, negli abbracci, nello stare nella mia presenza. Sono liberi di essere diversi da come erano prima, sbranando altri animali, combattendo con gli altri leoni per il dominio del branco."
</p><p>"Ma non sono pi&ugrave; leoni, &egrave; un'abominazione costringerli a comportarsi in questo modo. Lei &egrave; un uomo molto crudele verso gli animali."
</p><p>Il domatore fu scosso dall'accusa e per un attimo cominci&ograve; a piangere, ma riusc&igrave; a malapena a trattenersi. "Non credo che sia giusto dire che io sia crudele, io che adoro gli animali pi&ugrave; di tutti. Comunque, ho detto che il paragone non era buono. Invece voi, pensate di essere liberi? Lei, detective PM, perch&eacute; &egrave; qui?"
</p><p>"Perch&eacute; il mio lavoro &egrave; di indagare sui casi criminali, e cos&igrave; il giudice mi ha chiesto di cercare di capire quello che &egrave; successo."
</p><p>"Non mi pare molto libero. E Lei?", rivolgendosi all'assistente.
</p><p>"Ho un'attrazione fatale per gli uomini con il pigiama tricolore o con monospalla dalla giungla."
</p><p>"Sempre la battuta pronta, cos&igrave; non deve esprimere la propria opinione, non deve mai esporsi. Anche Lei sembra imprigionata dal proprio carattere, in modo di non poter avere una discussione sana con un'altra persona. Qualcosa &egrave; successo nel suo passato per renderla cos&igrave;, oppure &egrave; nata cinica e sarcastica?"
</p><p>Il domatore cap&igrave; subito che, per quanto era possibile, aveva ferito l'assistente con queste parole. La freccia aveva colpito troppo in fondo, pi&ugrave; di quanto l'assistente potesse assorbire. Il domatore non volle farle del male, ma a volte la sua natura gli faceva fare quello che non voleva fare, cio&egrave; di essere sempre gentile con le persone e con gli animali. Che ci fosse un domatore di umani, che con amore potesse cambiare la sua natura in meglio! "Chi mi liberer&agrave;?", grid&ograve; dentro di s&eacute;.
</p><p>"Mi dispiace tanto, non volevo essere cos&igrave; cattivo e maleducato. Chiedo scusa!" Si avvicin&ograve; per abbracciare l'assistente, ma lei si ritir&ograve; per istinto dal domatore, in modo che le braccia del domatore sbattessero inutilmente in aria. Imbarazzato, il domatore cambi&ograve; discorso. "Parlavamo di Norm. Voleva essere libero, e ha scoperto che girare la nazione senza dimora fissa non era la libert&agrave; che voleva. Era sempre Norm, si comportava in modo normale, tutti lo trattavano nel solito modo, anche se voleva essere diverso, libero di fare qualcosa di diverso, insolito. Ma non ci riusciva."
</p><p>"Capito. Mi dica", chiese il detective PM, "Norm aveva dei nemici?"
</p><p>"Il suo nemico pi&ugrave; grande ieri &egrave; stato la terra", sugger&igrave; l'assistente.
</p><p>Il domatore di leoni pens&ograve; che l'assistente si fosse ripresa velocemente dal suo momento di insicurezza di s&eacute;, e poi rispose, "Nemici forse no. Per&ograve; non era compreso da tutti perch&eacute;, siccome non aveva caratteristiche particolari, era difficile confrontarsi e cos&igrave; relazionarsi con lui. Io, che lo conosco da una vita, so il tipo di amicizia che ci vuole. Altri trasformano questa difficolt&agrave; di rapportarsi in distacco. A tre in particolare non piaceva: la palla di cannone umana, l'uomo pi&ugrave; forte del mondo, e la trapezista."
</p><p>"La ringrazio per il suo tempo. Andiamo a parlare con alcune altre persone, ma forse ritorneremo."
</p><p>&nbsp;
</p><p>La palla da cannone umana preparava il suo atto dall'altra parte del tendone. Il suo nome lo descriveva: era quasi una sfera. Era basso e grasso, con piccole appendici per gli arti e la testa. Era vestito completamente di nero con una stoffa totalmente aderente alla pelle, che sottolineava la sua rotondezza. Parlava con il direttore del circo quando vide avvicinarsi il detective PM e l'assistente. Il direttore scapp&ograve;, e la palla umana li salut&ograve;. "Salve, Lei &egrave; il detective di cui mi ha parlato il direttore del circo?"
</p><p>"In realt&agrave; sono il detective PM, ma s&igrave;, probabilmente sono io, e questa &egrave; la mia assistente."
</p><p>"Quale differenza fa 'PM'?"
</p><p>"Che cosa pensa?"
</p><p>La palla umana consider&ograve; come era vestito e quello che aveva sentito dal direttore, riflett&eacute; un po', e propose, "Primadonna maschile?"
</p><p>Il detective PM fu preso alla sprovvista, ma riusc&igrave; comunque a rispondere, "Non &egrave; proprio gentile, ma come dico sempre, il suo gusto &egrave; quello giusto. Allora, mi pare che sappia gi&agrave; della morte di Norm e che siamo qui per indagare sulla causa della sua morte. Quando &egrave; l'ultima volta che l'ha visto?"
</p><p>"Allora, siamo arrivati tre giorni fa. Mettiamo due giorni per montare le tende e il tendone, cio&egrave; fino a ieri sera. Poi ci riposiamo insieme, mangiano e giocando, prima di fare le prove per il primo spettacolo la terza sera. Cos&igrave; l'ultima volta che l'ho visto &egrave; stato ieri, quando eravamo tutti insieme."
</p><p>"A che ora ha lasciato gli altri?"
</p><p>"Non mi ricordo esattamente, &egrave; difficile notare quello che fa Norm perch&eacute; non si fa notare, ma a un certo punto non era pi&ugrave; con noi. Forse &egrave; stato uno dei primi ad andare alla sua tenda per dormire."
</p><p>"Capito. Sono curioso, come funziona il suo atto? Fa tanto rumore?", chiese con aria innocente il detective PM camminando intorno al cannone.
</p><p>"Facciamo un'esplosione con un forte boato e fumo che esce. Ma in realt&agrave; &egrave; solo per fare spettacolo, c'&egrave; l'aria compressa che mi spinge fuori."
</p><p>"Quanto lontano pu&ograve; arrivare? Fuori della tenda?"
</p><p>"Neanche per sogno. Il mio massimo &egrave; una quarantina di metri, cio&egrave; la lunghezza del tendone. Vedete quella rete dall'altra parte del tendone? Ecco dove posso arrivare."
</p><p>"E se mettesse pi&ugrave; aria compressa? O aumentasse l'angolo del cannone?", chiese invece l'assistente.
</p><p>"Posso cambiare l'angolo, ma non lo so, a me &egrave; stato insegnato cos&igrave;, non voglio mettere la mia vita a repentaglio facendo esperimenti o cose spericolate."
</p><p>"Le hanno insegnato bene, palla umana. La fisica dice cos&igrave;. Pu&ograve; ottenere la massima distanza quando il cannone ha un angolo di 45 gradi rispetto alla terra. Inoltre&hellip;"
</p><p>Presa la forchetta di plastica con un rebbio mancante, si accovacci&ograve; e inizi&ograve; a fare scarabocchi nella sabbia per terra, girando intorno al cannone alla ricerca di ulteriore spazio per i suoi calcoli. "Se la velocit&agrave; iniziale era V, Pitagora ci dice che la velocit&agrave; verticale era V sulla radice quadrata di 2. Con un'accelerazione costante nella direzione contraria di 9,8 - diciamo 10 per una risposta approssimativa - metri per secondo per secondo&hellip;" Simboli e numeri volarono dalla sua forchetta mentre la sabbia fu sollevata in aria e il detective PM mormor&ograve;, ignaro a tutto quello che era intorno a lui. La palla umana si stup&igrave; di questo comportamento. Piuttosto di usare carta e penna, il detective PM stava facendo calcoli con solo una forchetta rotta.
</p><p>Qualche parola comprensibile scapp&ograve; dalla bocca del detective PM: "tempo in aria V per radice di 2 su 10&hellip; distanza uguale velocit&agrave; orizzontale per tempo&hellip; V quadrato su 10&hellip; Velocit&agrave; iniziale &egrave; radice quadrata di 10 per distanza&hellip; distanza percorsa &egrave; 40 metri, quindi velocit&agrave; iniziale&hellip; per 3,6 per convertire a chilometri per ora&hellip;"
</p><p>"Quindi nell'esplosione iniziale", concluse il detective PM mentre la palla umana si meravigliava di quella magia arcana, "si va da 0 a 72 chilometri per ora in un attimo, e c'&egrave; un atterraggio con lo stesso cambio di velocit&agrave;. Per arrivare ben fuori della tenda, diciamo una distanza di 100 metri, richiederebbe una velocit&agrave; di&hellip;". Altri scarabocchi. "&hellip;quasi 115 chilometri per ora, e un'accelerazione mortale."
</p><p>"Sono impressionato", disse la palla umana, che l'avrebbe anche detto con bocca aperta se fosse possibile parlare senza chiudere la bocca. "Mi sbagliavo su di Lei, PM vuole dire sicuramente prodigioso matematico."
</p><p>Il detective PM sorrise leggermente, contento di essere onorato in quel modo.
</p><p>"Per&ograve; non sono sicuro&hellip; posso fare una prova? Senza l'esplosione aggiunta."
</p><p>"Cosa, vuole lanciarsi dal cannone?"
</p><p>"In realt&agrave;, devo osservare il cannone e il soggetto, che non potr&ograve; fare a 70 chilometri per ora. La mia assistente sar&agrave; lanciata."
</p><p>"Cosa? Sei fuori di testa?"
</p><p>"Niente affatto, &egrave; cos&igrave; che mi assisti con le indagini. Allora, cosa deve fare per prepararsi. Serve un casco?"
</p><p>"In realt&agrave; no", rispose la palla umana. "Quando si arriva alla rete, il casco non aiuta affatto. Di nuovo, &egrave; solo per fare spettacolo. Magari", con un'ulteriore riflessione, "potrebbe servire se si manca la rete, ma ho sempre cercato di evitare quella possibilit&agrave;."
</p><p>"Prendo il casco, prendo il casco! E le gomitiere e le ginocchiere. E tutti i cuscini che trovate!" url&ograve; l'assistente presa dal panico.
</p><p>Riuscirono a preparare l'assistente e infilarla dentro nonostante la sua mancanza di entusiasmo. Il detective con il suo righello prese alcune misure mentre l'assistente continuava ad obiettare. La palla umana inizi&ograve; il conto alla rovescia, e l'assistente vol&ograve;. Mentre era in aria, il detective PM chiese, "Secondo Lei, &egrave; necessario aggiustare la distanza alla rete, perch&eacute; l'assistente ha un peso e una forma diversi da Lei? Siete aerodinamicamente differenti, e non ho preso in considerazione la resistenza dell'aria."
</p><p>"Non saprei, io non cambio mai la distanza fra il cannone e la rete. So che &egrave; giusta per me e basta. Stiamo per scoprire se la misura giusta per me &egrave; anche giusta per gli altri."
</p><p>Scoprirono che l'assistente era pi&ugrave; aerodinamica e viaggi&ograve; qualche metro di pi&ugrave;, ma riusc&igrave; ad aggrapparsi al bordo della rete all'ultimo momento, prima di cadere a terra.
</p><p>"Grazie, palla umana, &egrave; stato molto interessante. Un'ultima domanda: come pu&ograve; sapere se qualcuno sposta il cannone a sua insaputa?"
</p><p>"Guardi, non &egrave; cos&igrave; facile! &Egrave; pesantissimo ed &egrave; attaccato ad una base affinch&eacute; non si muovi quando spara."
</p><p>"Come fa quindi a portarlo qui? E in ogni citt&agrave;?"
</p><p>"Va smontato e montato ogni volta. Con i muscoli del circo, delle corde, leve e carrucole, riusciamo in un paio di giorni. Ormai sappiamo bene la procedura e non &egrave; difficile."
</p><p>"Molto gentile. Adesso vado a recuperare l'assistente e chiacchierare con gli altri, magari ci rivedremo pi&ugrave; tardi."
</p><p>"&Egrave; stato un piacere. Quando vuole fare un'altra magia con quei simboli, venga pure!"
</p><p>&nbsp;
</p><p>"Vieni", comand&ograve; il detective PM all'assistente quando raggiunse la rete.
</p><p>"S&igrave; detectivino, sono tutta intera, anche se non ti interessa", rispose l'assistente, sentendosi trascurata.
</p><p>"Non sei affatto in terra, sei ancora nella rete. Per&ograve;, dovresti ormai essere in terra per assistermi piuttosto di riposarti sulla rete."
</p><p>"Ho detto intera, non in terra! Se non ti dispiace, preferirei essere intera in terra."
</p><p>Mentre il detective PM la aiutava a scendere dalla rete, l'assistente scosse la testa per riprendersi e comment&ograve; sarcasticamente, "Spero che il mio volo sia stato utile per capire la traiettoria, detectivino".
</p><p>"In realt&agrave;, avevo gi&agrave; capito la distanza possibile, volevo solo sentire quanto rumore il cannone faceva. Non ha fatto tanto rumore, sarebbe potuto essere utilizzato senza che sia sentito in tutta la zona."
</p><p>"Ma se era cos&igrave;, non poteva chiedere di far sparare il cannone senza mettermi dentro?", rispose l'assistente scioccata.
</p><p>"Ah&hellip; pu&ograve; darsi&hellip; non ci avevo pensato. La prossima volta non lo far&ograve;!"
</p><p>"La prossima volta che serve lanciare qualcuno da un cannone&hellip; quando mai?", mormor&ograve; l'assistente. "In ogni caso, mi pare che anche tu abbia pensato che Norm sarebbe potuto essere lanciato dal cannone per arrivare al campo."
</p><p>"S&igrave;, &egrave; vero. Per&ograve; il campo &egrave; troppo distante."
</p><p>"E se qualcuno avesse spostato il cannone?"
</p><p>"Ancora troppo lontano. Inoltre, mentre giocavi nella rete, ho chiesto alla palla umana, che ha detto che era troppo pesante da spostare. Naturalmente, poteva essere una bugia, ma mica mi sono messo a scrivere nella sabbia per fare dei calcoli. Li potevo fare nella testa. In realt&agrave; esaminavo il terreno tutto intorno al cannone, e non c'era nessuno segno che fosse stato spinto o spostato. Se qualcuno l'avesse fatto, io avrei potuto vedere l'evidenza di un tale movimento. Poi, c'era un'altra cosa. Mentre ci avvicinavamo alla palla umana, ho sentito l'ultima cosa che il direttore del circo gli ha detto prima di scappare. Era, 'Che cosa hai fatto con la casa di Norm'. Non so ancora il significato della frase, ma qualche domanda in giro potr&agrave; aiutarmi a capire l'indizio."
</p><p>Mentre camminavano, videro una mano guantata spuntare dall'entrata di una tenda. Faceva segno di entrare.
</p><p>Il detective PM e l'assistente si guardarono, e senza una parola decisero di seguire la mano nella tenda.
</p><p>&nbsp;
</p><p>L'uomo, con la faccia tutta bianca e maglietta a righe, raccont&ograve; che aveva sentito qualcosa di importante. Gli altri due, che stavano davanti di lui, lo guardavano perplessi, come se non comprendessero la sua lingua. L'uomo ripet&eacute; quello che aveva detto. Gli altri due non risposero, ma invece si presentarono, anche se non c'era tempo per tali gentilezze. Nessuno avrebbe dovuto sapere quello che stava per raccontare.
</p><p>"Buon giorno, io sono il detective PM e questa &egrave; la mia assistente. Come si chiama? Che cosa vuole da noi?
</p><p>L'uomo ribad&igrave; quello che aveva detto, ma ancora non rispondevano. Forse non erano molto intelligenti. Lo disse una quarta volta, ma questa volta pi&ugrave; lentamente. Un dito verso il petto tre volte, poi pian piano spost&ograve; la mano intorno all'orecchio.
</p><p>"Detectivino, credo che sia mimo", disse l'assistente.
</p><p>"Che strano trovare un personaggio importante con un nome. Buon giorno Mimmo, che cosa ci vuole dire?"
</p><p>"Non Mimmo, detectivino, mimo. Parla con le gesta invece delle parole. Credo che abbia detto che lui aveva sentito qualcosa."
</p><p>Il mimo sospir&ograve; e fece il segno di un pollice in su. Finalmente avevano capito. Non era ancora convinto a proposito della loro intelligenza, ma forse se avesse parlato con parole semplici avrebbe potuto farsi capire. Come poteva dirlo affinch&eacute; anche gli idioti potessero intendere&hellip; Mise un pugno dentro l'altra mano e separ&ograve; le mani con uno scatto.
</p><p>Il detective PM e l'assistente cercarono di indovinare quello che il mimo voleva dire. "Ha tolto un guanto? No, ha ancora tutti e due i guanti sulle mani. Ah&hellip; &egrave; un uovo che esce da una gallina? La terra che perde la sua atmosfera? No? Una palla tolta da&hellip; da&hellip; una sfera? Palla &egrave; quasi giusta? Palla che esce da un tubo? Un contenitore di palle da tennis? Una palla espulsa da un tubo? S&igrave;? Con un'esplosione? Una pallottola? Pi&ugrave; grande? Artiglieria? S&igrave;? Una palla da un cannone? Ho capito, la palla da cannone umana!"
</p><p>"Finalmente," pens&ograve; il mimo. Poi indic&ograve; la parte sinistra del petto.
</p><p>"Piace essere toccato? Ha una tasca segreta? Ha un cuore? O, siamo vicini! Ha problemi di cuore? Ha subito un infarto? Non ha un cuore - &egrave; un robot! No, non &egrave; quello. Cosa fa il cuore? &Egrave; innamorato? S&igrave;, per&ograve; di&hellip;"
</p><p>Il mimo strofin&ograve; il pollice contro le dita, e poi fece finta di dare qualcosa per ricevere qualcosa.
</p><p>"La palla umana adora toccarsi le dita? Regalare qualcosa? No, riceve anche. Scambiare qualcosa? D&agrave;&hellip; una crema per le mani? Riceve una crema? No&hellip; Soldi, d&agrave; soldi! La palla umana ama il denaro!"
</p><p>"Che fatica", pens&ograve; il mimo. "E abbiamo appena cominciato. Devo sbrigarmi."
</p><p>Agit&ograve; le braccia sopra la testa e ball&ograve; con le gambe, poi fece una curva con la mano, e poi un pugno con la mano destra mentre l'altra mano rimase normale, e le agit&ograve;. La mano sinistra strofin&ograve; le dita e tocc&ograve; l'altra mano, che fu agitata ancora di pi&ugrave;.
</p><p>"Vediamo se ho capito, dopo la festa ieri sera ha visto la palla umana parlare con Norm. Norm gli ha dato dei soldi - non ho sentito bene, 5000 o 6000? Erano 5000, ok - dopo di cui la palla umana era molto contenta."
</p><p>"Forse sono pi&ugrave; bravi di quanto sembrano, forse prima fingevano di essere stupidi per depistare chiunque origliava", ragion&ograve; il mimo. "Vedremo." Fece una serie lunga di movimenti e gesta complicati che il detective PM guard&ograve; con attenzione.
</p><p>"Allora, l'uomo pi&ugrave; forte del mondo &egrave; invidioso (mi piace il suo gesto per l'invidia) del presunto successo di Norm, mentre la trapezista cercava vendetta perch&eacute; Norm non si complimentava con lei in modo esagerato. Quindi tre sospettati, tre moventi diversi. Interessante. Grazie per le informazioni, mimo. Mi pu&ograve; dire qualcosa sulla casa di Norm? Dove &egrave;?"
</p><p>Il mimo indic&ograve; le direzioni per arrivare alla tenda di Norm. Aveva un'ultima curiosit&agrave;, e chiese il significato di PM. Quando il detective PM chiese quello che lui pensasse, rispose subito con un indice alzato e poi alcuni passi laterali con i palmi delle mani in avanti. Il mimo era contento quando il detective afferm&ograve; che andava bene, e poi tocc&ograve; la lingua e mise il pollice in su. Poi conged&ograve; il detective PM e l'assistente che uscirono dalla tenda, proprio nel momento in cui il direttore del circo usc&igrave; dalla tenda di fronte con l'uomo pi&ugrave; forte del mondo. Il direttore salut&ograve; freddamente il detective PM e l'assistente, che andarono a parlare con l'uomo pi&ugrave; forte. Diedero un'ultima occhiata indietro prima di entrare nella sua tenda, e scorsero la silhouette del direttore nella tenda del mimo, che imprecava e urlava al mimo con le sue mani, il suo corpo, e le sue gambe.
</p><p>&nbsp;
</p><p>L'uomo pi&ugrave; forte del mondo vide i due deboli avvicinarsi, e pens&ograve; di non aver niente da temere da loro. Non solo era pi&ugrave; forte fisicamente, ma senza dubbio anche mentalmente. Era lui il migliore di tutti! Non sarebbe stato costretto a rivelare niente. And&ograve; subito all'attacco.
</p><p>"Siete voi i due delinquenti che stanno disturbando tutti noi del circo, mentre cerchiamo solo di prepararci per dare un po' di gioia alla gente stasera?"
</p><p>"S&igrave;, cio&egrave; non siamo delinquenti, ma dobbiamo fare qualche domanda. Sono il detective PM e questa &egrave; la mia assistente."
</p><p>"PM? Sembra un titolo inventato per farsi sembrare pi&ugrave; importante di quanto Lei non &egrave; in realt&agrave;. Cosa vuol dire?"
</p><p>"Secondo Lei?"
</p><p>L'uomo pi&ugrave; forte ragion&ograve;, "Pensa che girare la domanda a me invece di rispondere mi metter&agrave; in difficolt&agrave;. Forse funzionerebbe con una mente inferiore, ma non con me."
</p><p>Poi rispose, "Lei &egrave; un pezzo di m&hellip;".
</p><p>"Se vuole pensare cos&igrave;, per&ograve; non bisogna essere volgare! Come dico sempre, ogni giusto ha buon gusto."
</p><p>"Io direi piuttosto, qualche gusto &egrave; disgustoso, ma so che non lo puoi dire, detectivino", inser&igrave; l'assistente.
</p><p>"Comunque", continu&ograve; il detective PM, "volevo chiedere di Norm. &Egrave; bravo al suo lavoro nel circo?"
</p><p>"So benissimo quello che vuole fare, cerca di fregarmi! Con queste domande trappole, secondo Lei io mi incastrer&ograve; con qualche risposta con troppe informazioni, e Lei dir&agrave;, 'Io non l'ho mai detto, solo l'omicida poteva sapere quelle informazioni'. Sappi che io sono pi&ugrave; furbo di Lei! Tutti sanno ormai che Norm &egrave; morto, ed &egrave; stato trovato nel campo accanto. Non mi pu&ograve; ingannare parlando di Norm nel presente."
</p><p>"Veramente notevole", rispose il detective PM. "Mi arrendo davanti alla sua bravura e intelligenza smisurata, e non Le chieder&ograve; altro di Norm."
</p><p>"Lo sapevo", riflett&eacute; l'uomo pi&ugrave; forte, compiaciuto. "Questi deboli non possono mai battermi in nessun modo."
</p><p>"Pu&ograve; invece", prosegu&igrave; il detective PM, "farci vedere quanto forte &egrave; veramente? Vorrei essere colpito dalla sua forza. Colpito nel senso metaforico, naturalmente! Riesce a sollevare, per esempio, la mia assistente? E magari lanciarla molto lontano?"
</p><p>"Eh, perch&eacute; sempre io?", obiett&ograve; l'assistente.
</p><p>"Quello stuzzicadenti? Non mi insulti insinuando che potrebbe essere remotamente difficile. Potrei sollevare voi due insieme, uno con la sinistra e uno con la destra. E potrei buttarvi almeno tre metri." Ecco, questo doveva umiliarlo.
</p><p>"Impressionante! Anche un cavallo?"
</p><p>"Senta, venga allo spettacolo stasera e vedr&agrave; quanto forte &egrave; l'uomo pi&ugrave; forte del mondo. Prima sollever&ograve; un bilanciere con ben 400 kg di pesi, poi far&ograve; alzare un furgone con le corde. Questo &egrave; quello che fa il numero di maggior successo del circo! Non come Norm, che faceva e che era niente, e la gente veniva per vedere quella nullit&agrave;."
</p><p>"Incredibile, non avevo idea che fosse possibile essere cos&igrave; forte. La ringrazio molto per la sua disponibilit&agrave;."
</p><p>Il detective PM e l'assistente ritornarono al tendone, sperando di trovare l'ultimo artista circense a cui era antipatico Norm.
</p><p>&nbsp;
</p><p>I due pappagalli volavano nella parte superiore del tendone, godendo la loro rara libert&agrave;. Sfrecciavano fra i pali e le corde che sostenevano il tendone, tuffavano e salivano, giocando a prendi e scappa. All'improvviso, Pappa scorse dei cerchi colorati entrare nella tenda, e subito si precipit&ograve; verso il bersaglio. "Gallo, cibo!", garr&igrave; all'altro pappagallo, che cambi&ograve; direzione per accompagnare il compagno in discesa. Insieme iniziarono a beccare i cerchi, senza per&ograve; sentire lo scoppio previsto che segnalava la comparsa del cibo. Perplessi, colpirono pi&ugrave; forte, ma ancora niente scoppio. Intanto, sentirono una voce, "Ahhh, aiuto, via!" I pappagalli risposero a modo loro, "Via! Via! Aiuto!", che alimentava la confusione, ma purtroppo non alimentava i pappagalli, una cosa che li avrebbe tranquillizzati. Mentre volarono intorno ai cerchi, si resero conto che erano attaccati ad un umano, uno di quella specie che i pappagalli cercavano di addomesticare. Forse non era ancora addestrato e non sapeva che il prossimo passo era di dare loro da mangiare. Quindi per aiutarlo strillarono, "Pappagallo mangia, pappagallo mangia". Ancora niente cibo, solo una raffica di braccia con in pugno una forchetta di plastica con un rebbio mancante. Arriv&ograve; invece la signora che avevano addomesticata. Non era bravissima - i pappagalli sapevano pi&ugrave; parole di lei - ma almeno capiva quando era il momento di dare del cibo.
</p><p>"Pappagalli, cibo", disse la signora, e porse una mano con dei semi verso di loro. Mangiarono volentieri, e quando furono sazi entrarono nella loro casetta che la signora aveva portato.
</p><p>"Dispiace", disse la signora rivolgendosi allora all'uomo. "Pappagalli trucchi circo." Fece vedere un minuscolo monopattino, vari cerchi e bastoni, ed altra attrezzatura per il suo numero. Poi pens&ograve; ma non le veniva la parola, cos&igrave; soffi&ograve; e indic&ograve; con le mani un'espansione.
</p><p>"Palloncino?"
</p><p>La signora annu&igrave; entusiasticamente. "Pappagallo palloncino", poi un'esplosione con le mani e "cibo". Indic&ograve; i cerchi colorati sul vestito dell'uomo e disse di nuovo, "palloncini".
</p><p>"Capito, i cerchi somigliano a dei palloncini, e i pappagalli sono stati addestrati per ricevere del cibo quando scoppiano dei palloncini. I pappagalli di Pavlov."
</p><p>Non piacque alla signora che l'aveva chiamata con il nome sbagliato, e rispose decisivamente, "No Pavlov, io pappagallista".
</p><p>"La ringrazio lo stesso per avermi salvato. Vorrei tanto continuare a chiacchierare con lei&hellip;"
</p><p>"&hellip;ma sarebbe una pena&hellip;", inser&igrave; la signora che accompagnava l'uomo.
</p><p>"&hellip;ma dobbiamo andare a parlare con gli altri."
</p><p>&nbsp;
</p><p>La trapezista era una giovane donna, che stava per cominciare le sue prove. Era salita una decina di metri sulla scala che portava alla sua postazione in cima al tendone quando vide il detective PM e l'assistente raggiungere la base della scala dall'altra parte del tendone. Il direttore l'aveva avvertita che sarebbero venuti, e non voleva perdere tempo scendere e risalire per un dialogo inutile con loro. Riprese quindi la sua salita. Raggiunta la piattaforma in alto, 20 metri sopra la terra, sleg&ograve; il trapezio e prese la barra, fece un bel respiro, mormor&ograve; fra s&eacute; e s&eacute;, "Tutti si meraviglieranno di me, tutti penseranno che sono brava, tutti mi applaudiranno", come ripeteva ogni volta che si lanciava. Convinta di essere apprezzata per la sua acrobazia, si inclin&ograve; e fece un piccolo salto in avanti. Acceler&ograve; subito mentre cadeva, e poi le corde attaccate al punto pi&ugrave; alto del tendone la tir&ograve; in un'arca, verso l'orizzontale. Mentre si avvicinava al punto pi&ugrave; basso del giro, si accorse con sorpresa che era troppo in basso. Pieg&ograve; le ginocchia. Non bastava. Alz&ograve; le gambe sopra l'anca. Ancora no. Il sedere atterr&ograve;, e la trapezista scivol&ograve; sulla sabbia ad alta velocit&agrave;. Poi perse l'equilibrio e rotol&ograve; lateralmente, e infine fece tre salti mortali con tre avvitamenti e mezzo carpiato, fermandosi proprio ai piedi del detective PM.
</p><p>"Impressionante! Fa cos&igrave; in tutti gli spettacoli?", chiese l'assistente. La trapezista non era sicura se era curiosit&agrave; sincera oppure sarcasmo.
</p><p>"No, certo di no", scuotendo la testa e cercando di alzarsi tre volte. "Qualcosa &egrave; andato storto. Di solito passo con i piedi 10 centimetri sopra la terra, le corde hanno la lunghezza giusta per farlo. Forse non sono state legate nel posto giusto ieri quando abbiamo montato il tendone. Eppure, ieri&hellip;". Lasci&ograve; il suo pensiero inespresso.
</p><p>La trapezista cambi&ograve; volto e mise il suo sorriso da artista per il pubblico. "Spero che vi sia piaciuto lo spettacolo comunque!"
</p><p>Rispose il detective PM con un altro sorriso, "Certo, &egrave; stato molto&hellip;"
</p><p>"Originale!", propose l'assistente.
</p><p>"S&igrave;, originale e spettacolare&hellip; &egrave; stata bravissima. Io sono il detective PM e questa &egrave; la mia assistente, e stiamo cercando di capire come &egrave; morto Norm ieri sera - ormai credo che tutti sappiano del suo decesso."
</p><p>La trapezista, contenta per il complimento e quindi disposta a collaborare, rispose, "Certo, non si parla di altro. Ma lo spettacolo deve continuare. PM - perch&eacute; ormai &egrave; pomeriggio o perch&eacute; lavora solo nel pomeriggio?"
</p><p>"Lavorare solo nel pomeriggio non sarebbe male, ma purtroppo mi tocca anche la mattina presto a volte, quando non sono al mio meglio. Mi piace questa spiegazione, e se funziona per Lei va bene. Come dico sempre, giusto &egrave; il proprio gusto. Possiamo farle qualche domanda?"
</p><p>"Non &egrave; un buon momento. C'&egrave; lo spettacolo fra qualche ora e devo ancora provare, come avete visto bisogna aggiustare e collaudare il trapezio. Se volete unirvi a me, potremo fare qualche chiacchierata mentre provo."
</p><p>"Non osare neanche di pensare di chiedere a me di farlo, questa volta tocca a te", disse l'assistente spaventata al detective PM.
</p><p>"Va bene, vado io questa volta. Non pu&ograve; essere troppo difficile".
</p><p>La trapezista rise fra s&eacute; e s&eacute;. "Sar&agrave; spiacevolmente sorpreso", pens&ograve;, "c'&egrave; un motivo per cui tutti mi acclamano, non &egrave; roba per tutti." Lei ritorn&ograve; al suo palo e risal&igrave;, e il detective PM sal&igrave; l'altro palo vicino a dove si trovavano. La trapezista aggiust&ograve; le corde del suo trapezio, per non ripetere lo stesso errore, e grid&ograve;, "Dopo 3 dar&ograve; il via, e ci lanceremo insieme."
</p><p>Il detective PM annu&igrave; di aver capito, ma sembrava alla trapezista di essere pi&ugrave; occupato dal pensiero del salto che stava per fare, ed eventuali conseguenze di un incontro troppo ravvicinato con la terra. "Questo &egrave; il suo problema, non il mio", pens&ograve; la trapezista, e poi url&ograve;, "1, 2, 3, via!"
</p><p>In perfetta armonia il detective PM part&igrave; allo stesso tempo della trapezista, e poco tempo dopo si incrociarono in fondo ai propri semicerchi. Nell'attimo che erano vicini, il detective PM chiese rapidamente, "Dove &egrave; la casa di Norm?"
</p><p>Dopo la risalita, ritornarono in retromarcia e, trovatisi nuovamente vicini, la trapezista rispose ancora pi&ugrave; rapidamente, "Non ha casa, solo una tenda qui."
</p><p>Ancora una pausa per salire e scendere, e questa volta il detective PM chiese, "Come &egrave; la tenda della palla umana?"
</p><p>La trapezista si stuf&ograve; di questo dialogo interminabile che interferiva con la sua prova, e al prossimo giro salt&ograve; dal suo trapezio e afferr&ograve; le caviglie del detective PM. "Mi scusi se mi sono permessa questa intimit&agrave;, ma mi pare che sia pi&ugrave; semplice chiacchierare in questo modo. Basta che non molli la presa. Comunque, la tenda della palla umana &egrave; particolare, ha delle curve piuttosto degli angoli." Fece una pausa per lanciarsi di nuovo, girarsi, e finire sulle spalle del detective PM. "Infatti, a nessuno piace andare a trovarlo, e lui raramente va nelle tende degli altri, perch&eacute; non ci sta."
</p><p>Il detective PM inizi&ograve; a cambiare colore, in modo che la faccia somigliasse ai suoi vestiti. "Forse &egrave; sufficiente cos&igrave;, grazie. Lei &egrave; stata meravigliosa. Mi dica come posso scendere?"
</p><p>La trapezista non era sorpresa che non reggeva, n&eacute; che la trovava meravigliosa. "Basta seguirmi, fare quello che faccio io. E soprattutto&hellip;" A questo punto la trapezista part&igrave; e solo qualche parola fu udibile. "Importante&hellip; cercare&hellip; rette."
</p><p>Queste ultime parole misero il detective PM in confusione, perch&eacute; in realt&agrave; la trapezista atterr&ograve; in un tipo di ragnatela di corde che per&ograve; era circolare, con solo alcune corde rette come i raggi dei cerchi concentrici. Mentre continuava a oscillare come un pendolo, cerc&ograve; invano delle rette su cui atterrare senza farsi tanto male. Alla fine, decise di mirare i raggi dei cerchi, perch&eacute; avendo eliminato tutte le forme impossibili, perch&eacute; non avevano nessuna retta, i cerchi che sono rimasti, anche se improbabili, dovevano essere il vero significato delle rette. Cos&igrave; anche lui part&igrave; come la trapezista, ma con trepidazione e insicurezza. Nonostante tutto, riusc&igrave; a beccare uno dei raggi, a cui afferr&ograve; con tutta la sua forza.
</p><p>"Bravo, bravo quasi quanto me", gli si quasi compliment&ograve; la trapezista.
</p><p>"Grazie, ma avevo qualche dubbio che fossero le rette a cui si riferiva, io avrei chiamato le corde cerchi piuttosto di rette."
</p><p>"Detectivino, &egrave; una rete!", sbott&ograve; l'assistente. "Quando farai controllare gli orecchi? &Egrave; la terza volta oggi che sbagli le consonanti doppie. Con una 't', rete; con due 't', rette. Il caro carro del nono nonno. Senti la differenza?"
</p><p>Il detective PM si ferm&ograve; un attimo per concentrarsi, poi esplose di gioia. "Sei un genio! Certo che &egrave; cos&igrave;. Quello che hai detto incastra l'ultimo pezzo del puzzle. Chiamiamo tutti qui nel tendone, e risolviamo il caso."
</p><p>"Il caro carro del nono nonno &egrave; cos&igrave; importante?", si interrog&ograve; l'assistente stupita.
</p><p>&nbsp;
</p><p>"Questa &egrave; la parte che mi piace di pi&ugrave;", pens&ograve; l'assistente. Era il motivo per cui le piaceva tanto seguire il detective PM. Non tanto per aiutarlo, anche se era pure un onore e piacevole, ma per ascoltarlo mentre spiegava tutto. La sua mente brillante coglieva tutti gli indizi rilevanti, scartava i fatti non importanti, collegava le sue osservazioni con la sua vasta conoscenza del mondo naturale, e cos&igrave; riusciva a dedurre una spiegazione elegante di ogni caso. Mentre tutti quelli del circo si sistemavano nel tendone, l'assistente avvist&ograve; anche il giudice in avvicinamento. Non trovando il detective PM, il giudice chiese all'assistente come proseguissero le indagini.
</p><p>"&Egrave; arrivato giusto in tempo", rispose, "il detective PM sta per rivelare tutto. Se vuole sedersi qui in tribuna, credo che fra poco lui arriver&agrave; per spiegare il caso."
</p><p>Il giudice si accomod&ograve;, e subito dopo le luci si abbassarono e "Marcia dei gladiatori" risuon&ograve; fastidiosamente dagli altoparlanti. Una voce romb&ograve; da fuori scena, "Signore e signori, grazie per essere venuti al nostro spettacolo di 'Chi l'ha fatto?' Ecco il nostro presentatore per stasera, io!" Un riflettore si accese, puntato verso l'entrata del tendone, dove il detective PM camminava verso il centro della pista, sorridendo e accogliendo tutti gli applausi che per&ograve; esistevano solo nella sua immaginazione. L'assistente voleva incoraggiarlo, ma dopo aver battuto le mani due volte, vide l'impassibilit&agrave; degli altri e si ferm&ograve; imbarazzata.
</p><p>"Grazie per l'accoglienza", prosegu&igrave; il detective PM indifferente all'indifferenza del suo pubblico. "Siamo qui per chiarire alcuni aspetti del decesso di Norm, in modo particolare come &egrave; morto, chi l'ha fatto, e perch&eacute;. Vi stupirete, vi meraviglierete, sarete scioccati, &hellip;"
</p><p>L'assistente inizi&ograve; ad agitarsi, non era il detectivino che conosceva, sembrava di aver preso in prestito il vocabolario del direttore del circo. "Va bene, abbiamo capito. Dicci come &egrave; successo!"
</p><p>Il detective PM inciamp&ograve; nella sua presentazione, e avendo dimenticato a che punto fosse, riprese il suo discorso con il suo tipico modo di parlare.
</p><p>"OK, come &egrave; morto Norm? Elucido. &Egrave; stato trovato in un campo con nessun segno di esserci arrivato nel terreno intorno a lui. Quindi era arrivato via aerea, una deduzione che mi sembrava impossibile quando ho controllato il cadavere stamattina. Per&ograve;, guarda caso, il circo dove lavorava era vicino. Parlando con voi, era chiaro che nessun di voi fosse capace di lanciare Norm fino al campo. Il cannone lanciava 40 metri, da una parte del tendone all'altra, l'uomo pi&ugrave; forte non poteva lanciare una persona molto distante, e il trapezio fa il suo giro dentro il tendone. Per&ograve;, lavorando insieme, era possibile. L'uomo pi&ugrave; forte mi ha gentilmente rivelato che &egrave; in grado di sollevare un furgone con le corde. E se un furgone, perch&eacute; non il cannone, che ha lo stesso peso? Quindi l'uomo pi&ugrave; forte, con l'aiuto della trapezista, ha legato il cannone al trapezio alzandolo 20 metri, fino alla piattaforma da cui parte la trapezista. A questo punto Norm &egrave; entrato nel cannone, la palla umana ha girato il cannone affinch&eacute; fosse verticale e ha preparato lo sparo con il timer. Tutto era pronto, e il cannone fu lanciato dalla piattaforma. Allora, una massa M a 20 metri di altezza ha 200M joule di energia potenziale, che al punto pi&ugrave; basso viene convertito in 200M joule di energia cinetica, che &egrave; la met&agrave; della massa per il quadrato della velocit&agrave;, quindi il cannone aveva una velocit&agrave; orizzontale di 20 metri per secondo. In questo momento il cannone ha sparato, dando a Norm, oltre alla velocit&agrave; orizzontale di 20 metri per secondo, anche una velocit&agrave; verticale di 20 metri per secondo, come ho calcolato prima quando parlavo con la palla di cannone umana. Fra parentesi, il cannone &egrave; rimasto attaccato alle corde probabilmente per non poco tempo, tirando e allungando le corde, che spiega perch&eacute; la trapezista &egrave; arrivata per terra quando ha usato il suo trapezio per la prima volta oggi. Proseguendo, un oggetto lanciato a questa velocit&agrave; arriva a 80 metri. Siccome &egrave; stato sparato dal centro del tendone, ha viaggiato 20 metri per arrivare alla fine del tendone, altri 10 metri per il confine del circo, e poi altri 50 metri sopra il campo, arrivando proprio dove &egrave; stato trovato Norm."
</p><p>Tutti rimasero stupiti, meravigliati e scioccati, e probabilmente altri aggettivi se l'assistente non avesse bloccato il vocabolario del detective PM durante la sua presentazione iniziale. Tuttavia, l'assistente fu la prima a reagire, con un fortissimo "bravo!", seguita dagli altri. Nel baccano da tifo dalla tribuna di stadio, alcuni gridavano "brillante", altri "incredibile", il direttore del circo cos&igrave; tanti sinonimi che &egrave; impossibile riportare tutti, la palla umana "no", l'uomo pi&ugrave; forte "per&ograve;", la trapezista "ma", il mimo "&hellip;" gesticolando freneticamente, il domatore di leoni "povero Norm", i leoni "rrrrr", e cos&igrave; via. Poi sopra tutti questi, silenziando il fracasso con la sua voce bassa, forte, e autorevole, fu il giudice con un semplice, "Basta!". Raccolta l'attenzione di tutti, dichiar&ograve; solennemente, "Se &egrave; cos&igrave;, dichiaro la palla umana, l'uomo pi&ugrave; forte del mondo, e la trapezista in arresto per l'omicidio di Norm. La giustizia sar&agrave; fatta."
</p><p>L'assistente era contenta che il caso fosse risolto, ma poi con un colpo di scena il detective PM aggiunse, "Non &egrave; cos&igrave; semplice, non &egrave; del tutto la risposta giusta."
</p><p>L'assistente chiese stupita, "Questo ragionamento brillante, &egrave; sbagliato? Non &egrave; successo cos&igrave;? Perch&eacute; ce l'ha raccontato se non &egrave; giusto?"
</p><p>"&Egrave; solo una parte della storia, un punto di vista della realt&agrave;. Perch&eacute; dobbiamo considerare anche come Norm &egrave; finito dentro un cannone a 20 metri di altezza. Non &egrave; un luogo dove si trova per caso."
</p><p>"Forse &egrave; stato reso privo di sensi con la violenza, oppure &egrave; stato drogato."
</p><p>"Per&ograve; il cadavere era completamente privo di qualsiasi segno anormale. Questo &egrave; la prima cosa che ho osservato, cio&egrave; non ho visto niente."
</p><p>"Ma lui ci ha chiesto di farlo", sussurr&ograve; la trapezista, un sussurro cos&igrave; potente che zitt&igrave; tutti, almeno fino alle altre giustificazioni delle proprie azioni. "Per&ograve; Norm ci ha spiegato quello che dovevamo fare per lanciarlo nel campo", disse l'uomo pi&ugrave; forte. "No, non siamo stati noi, Norm mi ha pagato per farlo", dichiar&ograve; la palla umana.
</p><p>"Ecco, una dichiarazione interessante." Il detective ripart&igrave; con la prossima parte della sua esposizione. "Per una bella parte della giornata, sono stato sviato da un mio difetto. Avevo capito che la morte di Norm aveva a che fare con la sua casa. Per&ograve;, come la mia geniale assistente che mi &egrave; sempre di grande aiuto mi ha ricordato&hellip;" A questo punto l'assistente arross&igrave; - era bello sentirsi apprezzata, soprattutto da una persona ammirata come il detective PM. "&hellip;a volte non riesco a sentire bene le consonanti doppie. L'indizio non era la casa di Norm, ma piuttosto la cassa di Norm, i soldi che aveva incassato dal suo lavoro al circo. Ha detto", rivolgendosi alla palla umana, "che non aveva visto Norm dopo che Norm ha lasciato la cena. Per&ograve; la verit&agrave; &egrave; che l'ha incontrato poco dopo, quando ha consegnato la sua cassa con dentro, se non mi sbaglio, 5000 soldi."
</p><p>"S&igrave;, &egrave; vero", confess&ograve; la palla umana. "La prima volta che mi ha chiesto di lanciarlo - non di ucciderlo, solo lanciarlo dal mio cannone dondolante - ho detto di no. Non &egrave; un giocattolo, gli ho detto. Ma ha insistito, insistito anche con la promessa dei soldi. A quel punto non ho potuto resistere, i soldi mi piacciono troppo. Cos&igrave; abbiamo concordato."
</p><p>"Dunque anche se Lei sapeva che spararlo da un cannone lanciato da&nbsp;20 metri di altezza senza una rete non era molto salutare, per l'amore del denaro ha acconsentito a scaraventarlo alla sua probabile morte."
</p><p>"E Lei" - toccava allora all'uomo pi&ugrave; forte - "era geloso del successo di Norm."
</p><p>"Non mi far&agrave; ammettere niente", replic&ograve;.
</p><p>"Certamente, Lei &egrave; troppo bravo per me, come quando &egrave; riuscito a nascondermi il fatto che non pu&ograve; lanciare una persona lontano, ma che pu&ograve; sollevare un oggetto pesante con le corde."
</p><p>"Non l'ho nascosto, anzi gliel'ho detto, perch&eacute; sapevo che non era importante, che non avrebbe mai capito. Come pu&ograve; uno come te capire lo stress di essere il numero uno del mondo, quando tutte le nullit&agrave; cercano di trascinare gi&ugrave; quelli che sono meritevolmente al top. Norm non era niente, non aveva niente di cui vantarsi, e doveva essere messo al suo posto giusto prima di diventare popolare, pi&ugrave; popolare di me. Cos&igrave; ero d'accordo di mandarlo al nulla."
</p><p>"Va bene, non cercher&ograve; pi&ugrave; di strappare da Lei le sue motivazioni. Invece, trapezista, perch&eacute;?"
</p><p>"So che non &egrave; una cosa bella, ma voglio essere sempre approvata e affermata. La gente deve dire quanto brava sono. E lo dicono, perch&eacute; lo sono. Ma Norm, no. All'inizio, era forse perch&eacute; non si esprime molto. Ha sempre un'espressione cos&igrave;, non lo so&hellip;"
</p><p>"Normale?", sugger&igrave; il detective PM.
</p><p>"S&igrave;, normale, che gli impediva di sperimentare l'estasi che sentono gli altri che mi vedono esibire. Poi ultimamente, sembrava qualcosa che faceva apposta. Veniva a farsi vedere da me, si metteva in prima fila, e mi guardava impassibile, mentre tutti gli altri si complimentavano con me e mi applaudivano. Mi infastidiva, mi faceva male, e mi veniva la voglia di fare male a lui."
</p><p>"Cos&igrave; abbiamo tre moventi diversi - denaro, gelosia, vendetta. Per&ograve; tutti hanno agito istigati da Norm, che ha chiesto, e in alcuni casi sedotto e provocato, queste tre persone a fare quello che lui voleva. E poi c'era il quarto movente: il desiderio di Norm di essere libero, libero dal suo carattere di essere normale, libero dalle aspettative altrui di come doveva essere, libero di volare."
</p><p>"Ma ha scoperto a suo danno che non poteva liberarsi dalla gravit&agrave;." Subito l'assistente si pent&igrave; di averlo detto, ma fare la battuta era pi&ugrave; forte di lei, anche quando non era appropriata. Neanche lei poteva essere libera da quello che era, e a volte le dispiaceva.
</p><p>"Grazie assistente, ma non &egrave; il momento per sdrammatizzare. Ironicamente, nel tentativo di liberarsi dal suo carattere, si &egrave; approfittato e ha manipolato il carattere degli altri (da cui loro non si potevano liberare), facendo in modo che non potevano rifiutare la sua offerta, anche se sapevano che ci&ograve; avrebbe portato alla sua morte. Quindi, di chi &egrave; la colpa della morte di Norm? Era omicidio o suicidio? I tre sono colpevoli e responsabili, oppure innocenti e Norm &egrave; responsabile, se sono stati tentati ad agire?"
</p><p>"Un bel dilemma", rispose l'assistente, riflettendo sulla risposta.
</p><p>"Niente affatto", aggiunse il giudice, "la giustizia &egrave; chiara che&hellip;"
</p><p>"Aspettate", interruppe il detective PM, "non abbiamo ancora finito. Il direttore del circo era ovviamente a conoscenza del piano di Norm."
</p><p>"S&igrave;, ci&ograve; &egrave; veritiero", ammise il direttore. "Norm si &egrave; confidato con il sottoscritto ieri pomeriggio. Naturalmente, ero sbalordito, sconcertato, esterrefatto. Ho tentato a indurlo ad astenersi, ma non ho conseguito la rinuncia. Perci&ograve; ho deliberato di indulgere la sua aspirazione, ma di fare in modo che mancasse, fallisse, e non raggiungesse il suo traguardo. Ho sollecitato il palloncinista a gonfiare copiosi palloncini e a ubicarli nella traiettoria di Norm all'entrata del tendone. Per&ograve; non &egrave; andato bene, ignoro perch&eacute;. Per questo motivo ero stupito, sorpreso, stupefatto quando mi ha detto stamattina che era estinto, tramontato, spento."
</p><p>All'assistente dispiacque questa novit&agrave;. C'&egrave; stata un'opportunit&agrave; per salvare Norm, che &egrave; sfumata per qualche motivo. Per&ograve;, per il detective PM era un'altra opportunit&agrave; per esporre tutti i suoi ragionamenti.
</p><p>"Credo di poter spiegare quello che &egrave; successo. Elucido. Non so se Lei lo sappia, n&eacute; se succeda sempre, ma stanotte i pappagalli erano nel tendone."
</p><p>"Vero. Volte pappagalli liberi", strill&ograve; la pappagallista.
</p><p>"Proprio ieri notte quando il palloncinista ha disposto tutti i palloncini colorati in aria nel tendone, i pappagalli erano in volo. Sono stati addestrati per il loro numero di scoppiare i palloncini (che non riescono a distinguere da qualsiasi cerchio colorato, come ho sperimentato in carne e ossa) quando li vedono, per ottenere del cibo. Quindi hanno scoppiato tutti i palloncini, che doveva essere per loro una grande delusione&hellip;"
</p><p>"No", afferm&ograve; Pappa tristemente, "cibo", complet&ograve; Gallo.
</p><p>"&hellip;e che il palloncinista ha raccolto stamattina prima che il direttore potesse vederli."
</p><p>"Quindi, Norm poteva essere salvato", pens&ograve; l'assistente ad alta voce, "ma per un crudele combinazione di avvenimenti casuali, &egrave; invece morto. Cio&egrave;, &egrave; stato un incidente? O un omicidio o un suicidio? Un bel trilemma."
</p><p>"Aspettate tutti", grid&ograve; il giudice quasi arrabbiato. "Prima dice che la morte di Norm &egrave; stata un omicidio, poi che &egrave; stata un suicidio, e adesso che &egrave; stata un incidente? Ti ho chiesto stamattina di dirmi quale di questi tre possibilit&agrave; era, e adesso mi dice che &egrave; stata tutte e tre allo stesso tempo? &Egrave; inaccettabile!"
</p><p>"S&igrave;, forse tutti e tre allo stesso tempo, oppure pu&ograve; essere una qualsiasi delle tre possibilit&agrave;, dipende dal punto di vista", rispose con calma il detective PM.
</p><p>"Ma la giustizia non pu&ograve; dipendere dal punto di vista! Una cosa &egrave; giusta o sbagliata e basta. Qualcosa &egrave; successo o non &egrave; successo."
</p><p>"Per&ograve; i fatti possono essere interpretati in modo diverso da persone diverse."
</p><p>"Allora, che cos'&egrave; la giustizia?"
</p><p>"Non lo so, non tocca a me decidere. Lei &egrave; il giudice, io sono solo un detective PM che scopre quello che &egrave; successo."
</p><p>"Per&ograve;, detectivino", offr&igrave; l'assistente esitante, "&egrave; giusto quello che dici, che la giustizia dipende dal punto di vista? Perch&eacute; qualcuno potrebbe dire, 'Secondo il mio punto di vista, giusto e sbagliato sono realt&agrave; oggettive'. E tu non puoi obiettare."
</p><p>"Non lo so, come ho detto non mi occupo di congetture filosofiche."
</p><p>"Anche se in tutte le scelte che fai nella vita, devi avere una filosofia del giusto per farti decidere. Se io ti dico che questa &egrave; una sedia, o pensi che io abbia ragione e ti ci siedi sopra o pensi che &egrave; un'opinione personale e non ti ci siedi nel caso che non lo sia."
</p><p>"Basta vaneggiare! Se volete sapere quale possibilit&agrave; &egrave; quella giusta, mettiamo la questione al voto. Chi pensa che la morte di Norm sia un suicidio venga da questa parte, che sia un omicidio da quella parte, e che sia un incidente di l&agrave;."
</p><p>Scoppi&ograve; una confusione colossale pi&ugrave; che mai, il che era impressionante per un circo abituato allo scoppio di palloncini e canoni, a folle nel delirio, ad animali che fanno tanti versi, a diversi numeri eseguiti contemporaneamente, e a molto di pi&ugrave;. La palla da cannone umana, l'uomo pi&ugrave; forte del mondo, e la trapezista votarono, naturalmente, per il suicidio. Cominciarono a insultare e minacciare quelli che votarono per l'omicidio, come il domatore di leoni. Lui era troppo gentile per rispondere, ma Sofficina non pens&ograve; due volte e rugg&igrave; prepotentemente. Il direttore del circo e il palloncinista votarono invece per l'incidente, ma il pappagallista, insieme con Pappa e Gallo, non volevano prendere la colpa e si misero con il domatore - fino a quando Micio li guard&ograve; leccandosi le labbra, e decisero di cambiare idea in omicidio. Uno dei gemelli siamesi pensava all'omicidio e l'altro all'incidente, e discussero animatamente fra di loro senza risolvere la questione di dove andare, e finirono a prendersi a pugni. I pagliacci semplicemente girarono intorno sui loro monocicli, suonando il clacson e schizzando acqua dai fiori finti che indossavano. Il mimo cerc&ograve; inutilmente di farsi sentire, poi si arrese e si un&igrave; al domatore. Tutti gli altri dipendenti del circo espressero la propria opinione. Quando tutti trovarono il proprio posto, l'assistente cont&ograve; e dichiar&ograve; un pareggio: un quarto per l'omicidio, un quarto per il suicidio, un quarto per l'incidente, e un quarto astenuti.
</p><p>"Visto che non si pu&ograve; decidere la giustizia con un voto popolare?", url&ograve; il giudice. "Quello che &egrave; giusto non pu&ograve; cambiare di giorno in giorno o di luogo in luogo, o se chiediamo a persone diverse. Anche la mia opinione personale su quello che &egrave; giusto pu&ograve; cambiare in base alle mie esperienze. Inoltre, come possiamo noi che siamo spesso ingiusti decidere quello che &egrave; giusto? Per questo sono un giudice che fa valere la giustizia della legge, che non dipende n&eacute; dalle mie opinioni n&eacute; dalla mia ingiustizia. Comunque, mi sono stufato di tutta questa discussione. Nel nome della legge, dichiaro in arresto per l'omicidio di Norm ieri notte la palla da cannone umana, l'uomo pi&ugrave; forte del mondo, e la trapezista. Sar&agrave; la legge in tribunale che decider&agrave; se sono colpevoli o giusti. Grazie detective PM, &egrave; stato prodigioso e magnifico a rivelare la verit&agrave;, anche se di meno a rivelare la giustizia."
</p><p>Con queste parole il giudice part&igrave; per ritornare in paese, insieme con gli accusati. Gli altri non sapevano che cosa fare e scambiarono qualche parola in modo cordiale e imbarazzato, prima di ritornare man mano alle loro tende. Appena il detective PM e l'assistente rimasero soli, lei gli disse, "Ancora una volta, sei stato bravissimo, detectivino. Ti faccio tanto di cappello."
</p><p>"Perch&eacute; mi vuoi dare tanti tuoi capelli?"
</p>
<h2>Note su "Detective PM"</h2>
<p>Ci sono diversi modi per raccontare una storia. In una narrativa in prima persona un personaggio, di solito ma non sempre il protagonista, racconta quello che fa e osserva, con i suoi pensieri. <i>Propiziatore</i> &egrave; di questo tipo. In una narrativa in terza persona, un narratore esterno alla storia racconta gli eventi. Pu&ograve; essere un narratore cosiddetto onnisciente, che sa tutto (incluso i pensieri di tutti i personaggi), oppure un narratore con punto di vista limitato, o soggettivo (che sa i pensieri solo di un personaggio, e racconta quello che fa e osserva, con i suoi pensieri, ma nella terza persona) o oggettivo (solo i fatti, come un giornalista). <i>Mercenario della Giustizia</i> &egrave; una narrativa in terza persona con punto di vista limitato soggettivo, mentre <i>Direttore della Giustizia</i> e <i>Assistente</i> sono narrative in terza persona con narratore onnisciente. Questo racconto invece usa una tecnica narrativa particolare: &egrave; in terza persona con punto di vista limitato soggettivo, ma le diverse sezioni del racconto utilizzano il punto di vista di personaggi diversi. Questo &egrave; perch&eacute; il racconto esplora il tema di diversi punti di vista degli stessi eventi, e dove sta la verit&agrave; se tutti pensano dello stesso evento in modo diverso.
</p><p>&nbsp;
</p><p>La libert&agrave; come comunemente capita, di poter fare tutto quello che si vuole, non esiste. Come Norm scopr&igrave;, dobbiamo sempre agire secondo le leggi fisiche. Pi&ugrave; seriamente, siamo costretti anche ad agire secondo la nostra natura, come sar&agrave; approfondito dal domatore di leoni.
</p><p>&nbsp;
</p><p>PM, nel nome/titolo Detective PM, in realt&agrave; sta per postmoderno. Infatti, questo personaggio &egrave; nato nella mia immaginazione quando ho cercato di pensare come sarebbe un detective che non credesse nella verit&agrave; assoluta, che quello che &egrave; importante &egrave; quello che &egrave; vero per l'individuo. Si vede questa caratteristica nelle risposte del detective PM quando gli altri dicono quello che pensano sia il significato di 'PM', nella sua conclusione se la morte di Norm era un omicidio, un suicidio, o un incidente, e in vari altri posti. Nel racconto, non &egrave; sempre coerente con questa opinione, ma non credo che nessuno possa essere coerente con una tale teoria epistemologica.
</p><p>&nbsp;
</p><p>La difesa del propiziatore da parte del giudice &egrave; una conseguenza degli eventi in <i>Propiziatore</i>. Il suo atteggiamento verso i mercenari di giustizia e quello dell'assistente verso i propiziatori sono spiegati in altri racconti.
</p><p>&nbsp;
</p><p>I palloncini in forma di vombato e del teatro dell'opera di Sydney tradiscono le mie origini australiane.
</p><p>&nbsp;
</p><p>"Elementare, mio caro Watson" (in inglese: "Elementary, my dear Watson") &egrave; una delle frasi pi&ugrave; celebri di Sherlock Holmes, e i personaggi fanno qualche gioco di parole con questa frase. In realt&agrave;, la frase non &egrave; in nessuno dei racconti originali di Sherlock Holmes, ma &egrave; stata detta spesso nei film di Sherlock Holmes degli anni 40 del secolo scorso, e cos&igrave; &egrave; diventata famosa.
</p><p>&nbsp;
</p><p>"L'unica cosa peggiore di non raggiungere il proprio obiettivo, &egrave; di raggiungerlo e scoprire di rimanere insoddisfatto." Una perla di saggezza. Quando cerchiamo la realizzazione e la soddisfazione in qualsiasi cosa (lavoro, famiglia, sesso, soldi, fama, bella figura, approvazione, eccetera) che non &egrave; Dio, quella cosa diventa un idolo. Spesso sono cose buone che Dio ha creato per il nostro godimento, ma non per dare un significato nella nostra vita quando le otteniamo. Solo Dio pu&ograve; fare quello, e se cerchiamo la soddisfazione in quello che Dio ha creato, saremo sempre delusi.
</p><p>&nbsp;
</p><p>"Un leopardo non pu&ograve; cambiare le sue macchie". Il domatore di leoni si riferisce a Geremia 13:23 - gli Israeliti avrebbero continuato a fare il male, perch&eacute; era la loro natura. L'unica speranza era che qualcun altro cambiasse la loro natura, come il domatore fece per i leoni con il suo amore, e come Dio promise di fare agli Israeliti in Geremia 31:33-34; Ezechiele 36:26-27. Similmente per noi, non siamo liberi di sempre fare il bene; nonostante tutta la nostra buona volont&agrave;, facciamo anche del male. Cos&igrave; siamo schiavi al peccato, ma Dio ci libera affinch&eacute; serviamo lui (Romani 6:16-23). Per&ograve;, non siamo completamente liberati dalla natura peccaminosa, anche se non siamo pi&ugrave; schiavi al peccato - non vogliamo peccare ma pecchiamo lo stesso. Questa &egrave; la riflessione del domatore di leoni dopo che involontariamente fa male all'assistente, che segue Romani 7:14-24. Per&ograve;, volendo ma non conoscendo qualcuno che lo potesse liberare, il domatore non cita l'ultimo versetto del brano, Romani 7:25 - Ges&ugrave; Cristo al suo ritorno ci liberer&agrave; anche dalla natura peccaminosa, dandoci un nuovo corpo trasformato e spirituale (1Corinzi 15:42-44), che non pecca ed &egrave; incorruttibile.
</p><p>&nbsp;
</p><p>I calcoli del detective PM: Se g &egrave; l'accelerazione dovuta alla gravit&agrave; (10 per una risposta approssimativa), la velocit&agrave; verticale dopo t secondi &egrave; V/&radic;2 - gt, e quindi l'altezza &egrave; Vt/&radic;2 - gt&sup2;/2. Arriva per terra quando l'altezza &egrave; 0, cio&egrave; all'inizio (t=0) e quando V/&radic;2 = gt/2, cio&egrave; dopo t = &radic;2 V / g secondi. La distanza orizzontale trascorsa in quel tempo &egrave; la velocit&agrave; orizzontale per il tempo, cio&egrave; V/&radic;2 per &radic;2 V / g = V&sup2; / g. Siccome sappiamo che arriva a 40 metri, la velocit&agrave; iniziale &egrave; &radic;(40g) = 20 metri per secondo, o 20 x 60 x 60 metri per ora, o 20 x 3600 / 1000 chilometri per ora, cio&egrave; 72 chilometri per ora. Similmente, per arrivare a 100 metri, la velocit&agrave; iniziale dovrebbe essere &radic;(100g) x 3,6 = 113,8 chilometri per ora.
</p><p>&nbsp;
</p><p>La palla umana afferm&ograve; della distanza alla rete, "So che &egrave; giusta per me e basta. Stiamo per scoprire se la misura giusta per me &egrave; anche giusta per gli altri." In alcuni casi, quello che &egrave; giusto per una persona pu&ograve; non essere giusto per un'altra persona. Per esempio, quando si parla di preferenze o caratteristiche personali, come il gusto migliore del gelato o quanto lontano si va quando sparato da un cannone. Per&ograve;, non quando si parla di fatti esterni: la frase "questo gelato &egrave; alla fragola" &egrave; giusta o non &egrave; giusta indipendentemente di quello che possiamo pensare. Se non esiste Dio o comunque un altro punto di riferimento esterno, anche l'etica e la moralit&agrave; diventano gusti personali. Ma se Dio esiste, non &egrave; pi&ugrave; cos&igrave; perch&eacute; quello che &egrave; giusto &egrave; deciso da quello che onora lui come Dio, non da quello che piace a una persona in quel momento.
</p><p>&nbsp;
</p><p>"Alla fine, decise di mirare i raggi dei cerchi, perch&eacute; avendo eliminato tutte le forme impossibili, perch&eacute; non avevano nessuna retta, i cerchi che sono rimasti, anche se improbabili, dovevano essere il vero significato delle rette." - Un altro riferimento ad una frase celebre di Sherlock Holmes, che questa volta appare nei racconti originali: "Quando hai escluso l'impossibile, ci&ograve; che resta, per quanto improbabile, deve essere la verit&agrave;" (in inglese: "When you have eliminated the impossible, whatever remains, however improbable, must be the truth").
</p><p>&nbsp;
</p><p>Altri calcoli del detective PM: Ha spiegato come ha calcolato, usando la legge di conservazione dell'energia, che Norm aveva una velocit&agrave; orizzontale di 20 metri per secondo al momento del lancio, oltre ai 20 metri per secondo verticali che sono stati calcolati qui sopra. La velocit&agrave; totale, secondo Pitagora, &egrave; quindi &radic;(20&sup2;+20&sup2;) metri per secondo. Come calcato prima, la distanza orizzontale trascorsa &egrave; il quadrato della velocit&agrave; diviso per g (cio&egrave; 10), che &egrave; 80 metri. Le distanze (tendone lungo 40 metri, poi 10 metri all'entrata del circo, e 50 metri nel campo) sono state menzionate in vari punti del racconto.
</p><p>&nbsp;
</p><p>"Qualcuno potrebbe dire, 'Secondo il mio punto di vista, giusto e sbagliato sono realt&agrave; oggettive'." - Filosoficamente e logicamente, l'affermazione che non esiste una verit&agrave; assoluta non pu&ograve; reggere, perch&eacute; si contraddice - l'affermazione stessa vuole esprimere una verit&agrave; assoluta, per cui, se l'affermazione fosse vera, sarebbe falsa!
</p><p>&nbsp;
</p><p>Il giudice, nella sua frustrazione, nel suo ultimo discorso esprime la sua idea riguardo alla giustizia basata sulla legge, nonostante quello che aveva imparato in <i>Propiziatore</i>. Come tutti noi, non riesce a trasformare istantaneamente la propria vita per essere coerente con quello che crede. Nei racconti successivi, cambier&agrave; maggiormente il suo modo di pensare e agire.
</p>
<?
require("../piede.php");
?>
