<?
$descriz = "Direttore della Giustizia: uno dei Racconti della Giustizia";
$key = "direttore della giustizia, racconti della giustizia";
$titolo = "Direttore della Giustizia";
$sezione = "Strumenti";
$sezioneurl = "/racconti_giustizia/";
require("../capo.php");
?>
<h1>Direttore della Giustizia</h1>
<p>La sentinella strizz&ograve; gli occhi per capire meglio chi si avvicinava al paese. Il tramonto del sole lo abbagliava, per cui era solo quando furono vicini che si rese conto che c'era pi&ugrave; di una persona che viaggiavano lunga la strada. Due, quattro, no una decina di persone nel gruppo. Anzi, una che camminava davanti e gli altri la seguivano ad una distanza rispettosa. Quella che guidava il gruppo aveva un vestito verde, no sembrava blu, anzi arancione&hellip; Vesti colorate e lunghe, poi quando era pi&ugrave; vicina pareva una donna con capelli tinti. Camminava in modo altezzoso, sicura di s&eacute; e della sua importanza. Alcuni di quelli dietro di lei avevano delle armi vistose. "No, non di nuovo", pens&ograve; la sentinella angosciata, "ci sono dei guai in vista". Mand&ograve; un messaggio infausto al giudice del paese, "Il direttore della giustizia sta ritornando".
</p><p>&nbsp;
</p><p>Il giudice, tremante, si prepar&ograve; per ricevere il direttore della giustizia alle porte spalancate del tribunale. Di solito il giudice di un paese non vedeva il direttore della giustizia in tutta la sua vita. Invece era gi&agrave; la seconda volta per lui, e la prima volta era venuta per condannarlo. Che cosa voleva da lui? Perch&eacute; ce l'aveva con lui? In quel momento il direttore della giustizia entr&ograve; con tutto il suo seguito.
</p><p>"Benvenuta Direttore della Giustizia al nostro paese umile e giusto. Che piacere rivederla! Come possiamo essere al servizio di Lei?"
</p><p>"Giudice, grazie per il benvenuto. Non si deve preoccupare, non sono venuta per accusarla. Piuttosto, possiamo parlare in privato?"
</p><p>"Certo", rispose il giudice piuttosto perplesso. "Possiamo ritirarci nella mia sala da pranzo privata, mentre i suoi&hellip;"
</p><p>"Colleghi?", sugger&igrave; il direttore della giustizia.
</p><p>"S&igrave;, colleghi", prosegu&igrave; il giudice con il dubbio che gli uomini muscolosi con le armi vistose fossero veramente i colleghi dell'ufficio del direttore della giustizia, "possono mangiare nella mensa con i miei&hellip; colleghi."
</p><p>"Bene, andiamo Giudice."
</p><p>&nbsp;
</p><p>Come era sua abitudine, il direttore della giustizia, nel momento che arriv&ograve; nella sala da pranzo con il giudice, prese controllo della conversazione. Per&ograve;, il suo discorso non fin&igrave; come avrebbe voluto.
</p><p>"Giudice, sa che io difendo, sostengo, e confermo la giustizia nella nostra gloriosa e giusta Nazione da anni. Ho fatto valere la legge, e ho fatto causa a chi non era giusto, come Lei sa bene. Per&ograve;, recentemente, io&hellip; Veda, io ho fatto&hellip;" La voce inizi&ograve; a vacillare, e cos&igrave; anche la sicurezza del direttore della giustizia in s&eacute; stessa. "Ho fatto una cosa terribile."
</p><p>"Che cosa ha fatto?"
</p><p>"Io&hellip;" Il direttore della giustizia cominci&ograve; addirittura a singhiozzare, che mise in imbarazzo il giudice. Era abituato a tali manifestazioni di emozioni in tribunale, ma poteva stare sopra i sentimenti nel suo ruolo di giudice. Qui invece, doveva rispondere a livello personale.
</p><p>"Io non capisco, mi dica quello che vuole che io faccia."
</p><p>"Giudice, io sono colpevole." Ormai piangeva dirotto. "Mi arrendo alla giustizia, mi metto nelle sue mani. Mi faccia quello che &egrave; giusto."
</p><p>La trasformazione dal direttore della giustizia prepotente alla donna distrutta fu veloce e raccapricciante. Per quanto tempo aveva mantenuto la sua figura arrogante e aggressiva, tenendo dentro tutta la tristezza e il dolore? Non era sorprendente che fosse esplosa come una bomba, con tutte le emozioni che sgorgavano come una cascata.
</p><p>"Ma perch&eacute; me? Perch&eacute; ha fatto tutto questo viaggio per dirlo proprio a me?"
</p><p>"So che abbiamo avuto delle differenze d'opinione nel passato e che Le ho fatto male", disse il direttore della giustizia fra le lacrime e i pianti, "ma non per questo non La rispetto. So che Lei fa valere la legge e la giustizia in modo imparziale, che niente Le impedisce di eseguire il giusto giudizio, senza favoritismo. Mi fidavo solo di Lei, che mi avrebbe condannato, come &egrave; giusto."
</p><p>"Direttore", disse con un mezzo tentativo di toccarla per consolarla - si chiedeva cosa dovesse fare per fermare il fiume di lacrime - "sono un uomo cambiato. Nessuno pu&ograve; sperimentare quello che mi &egrave; successo l'ultima volta che &egrave; venuta senza essere trasformato. Vedo la giustizia in modo diverso adesso."
</p><p>"No!", url&ograve; il direttore della giustizia. "Anche Lei mi deluder&agrave;! Prima io e adesso anche Lei. La supplico, faccia cadere tutto il peso della legge su di me senza piet&agrave;, perch&eacute; non la merito."
</p><p>"Ma perch&eacute;, cosa ha fatto?"
</p><p>"Io ho&hellip;" Per&ograve;, al pensiero del suo crimine, la disperazione la sopraffece di nuovo, e scoppi&ograve; in strilli e urli inconsolabili. Il giudice, non sapendo cosa dire, usc&igrave; silenziosamente, lasciandola nella sua disperazione, e pi&ugrave; tardi mand&ograve; uno dei dipendenti del tribunale per accompagnare il direttore della giustizia ad una stanza dove poteva dormire.
</p><p>&nbsp;
</p><p>Il giudice era perplesso. In questo caso, aveva un'accusata e un verdetto di colpevolezza, ma nessun crimine. Come poteva eseguire un giudizio ed eventuale punizione senza sapere quello che era stato fatto? Una cosa era chiara, il direttore della giustizia non sarebbe stata d'aiuto. In ogni cosa, il giudice non voleva assistere mai pi&ugrave; ad una scena del genere. In questi casi impossibili, il giudice sapeva che c'era sola una strada da percorrere, per cui presto la mattina seguente usc&igrave; dal tribunale e intraprese la sua strada preferita, che conduceva alla casa del suo grande amico.
</p><p>&nbsp;
</p><p>Il giudice buss&ograve; gentilmente. Nessuna risposta. Sorrise, perch&eacute; conosceva bene questo gioco. Il suo amico faceva finta di non sentire, bastava insistere e dire qualcosa di interessante per attirare l'attenzione dell'amico. "Buon giorno. C'&egrave; un bellissimo sole oggi. O almeno ci sar&agrave; dopo l'alba, che dovrebbe arrivare fra pochissimo. Abbiamo tante cose interessanti da scoprire oggi."
</p><p>Una voce usc&igrave; debolmente dalla casa, "Sempre Lei, giudice? Perch&eacute; mi infastidisce continuamente? Aspetti, cosa ha detto dell'alba?"
</p><p>"Che ci sar&agrave; una bellissima alba fra pochi minuti, vale la pena non perderla. I colori saranno magnifici, e dar&agrave; una carica per il resto della giornata."
</p><p>"Noooooo&hellip;."
</p><p>"Venga fuori, comunque la disturbo perch&eacute; ho un altro caso interessantissimo per Lei."
</p><p>"Come il caso del pescatore ambidestro con una mano sola, con ho risolto in meno di un'ora? O l'elefante volante, in appena dieci minuti? O l'alibi dei gemelli monozigoti, che ho capito senza neppur alzarmi dal letto?"
</p><p>"No, molto pi&ugrave; interessante, molto pi&ugrave; difficile."
</p><p>"E quale sarebbe questo reato interessante e difficile da risolvere?"
</p><p>"Non lo so."
</p><p>Il detective PM cap&igrave; che non avrebbe ricevuto una risposta sensata dal giudice mentre si gridavano attraverso la porta, doveva parlargli personalmente per avere un discorso ragionevole. Un caso senza reato, cosa dice?! Quindi si rotol&ograve; dal letto, nel buio della stanza e con gli occhi ancora mezzo chiusi dal sonno, prese e indoss&ograve; i primi vestiti che riusc&igrave; a trovare frugando fra gli oggetti ammucchiati sul pavimento e sui mobili. Apr&igrave; la porta, e fu subito travolto dai bagliori dei pungenti raggi del sole appena alzato, di colori rosso, giallo, e arancione. Il giudice lo guard&ograve; e disse impressionato, "Mi piace la sua moda sempre&hellip; originale. E anche a tema per quest'ora."
</p><p>Il detective PM abbass&ograve; gli occhi, e vide che aveva messo una maglietta al posto dei pantaloni, mentre sopra c'era una maglietta vecchia e poco lavata, che era diventata un miscuglio di colori: rosso, giallo, arancione, e alcuni non identificabili. Il detective PM riflett&eacute; per un attimo. Aveva una scelta: poteva ammettere il suo errore, oppure fingere di essere vestito cos&igrave; apposta. Meglio non perdere faccia: scelse la seconda opzione.
</p><p>"S&igrave;, sono i miei vestiti preferiti per quest'ora del giorno."
</p><p>"Mi perdoni per aver chiesto di nuovo la sua collaborazione&hellip;"
</p><p>"No", interruppe bruscamente il detective PM.
</p><p>"No cosa?"
</p><p>"No, non La perdono. C'&egrave; perdono solo per aver fatto uno sbaglio. Non posso perdonare qualcuno che pensa di aver fatto la cosa giusta. Ha commesso un errore venendo a svegliarmi in quest'ora non esistente? Non lo far&agrave; pi&ugrave;?"
</p><p>"In realt&agrave;, no. Ha ragione, lo farei di nuovo se fosse necessario. Se posso ricominciare: Mi dispiace di averla svegliato, ma il bisogno che ho del suo aiuto per un caso &egrave; maggior del disturbo che ho recato."
</p><p>"Cos&igrave; va meglio. E che cosa &egrave; questa storia di un caso con un reato sconosciuto."
</p><p>"Veda, ieri &egrave; venuta a trovarmi&hellip;" (forse era meglio celare l'identit&agrave; del Direttore della Giustizia per il momento) "una donna. Era in lacrime, perch&eacute; diceva di aver commesso un crimine terribile, e ha pure confessato la sua colpevolezza. Per&ograve; &egrave; cos&igrave; sconvolta, e il pensiero del reato le fa cos&igrave; tanto male, che non riesce a dirmi quello che ha fatto. Ho bisogno di Lei per scoprire il crimine, in modo che io possa decidere la punizione adeguata."
</p><p>"Sicuramente &egrave; un caso&hellip; diverso dai soliti. Penso di poter dedicare un'oretta del mio tempo per scoprire la verit&agrave;. Suppongo che Lei abbia gi&agrave; chiamato la mia assistente", con un piccolo desiderio che non l'avesse gi&agrave; fatto.
</p><p>"No, non volevo prendere per scontato la sua risposta. Ma siccome insiste, possiamo passare a prenderla mentre andiamo al tribunale."
</p><p>"Non si scomodi, non &egrave; necessario."
</p><p>"Non si preoccupi, &egrave; il minimo che io possa fare dopo averla scomodata a quest'ora. In ogni caso, un punto di vista femminile potrebbe essere utile."
</p><p>Il detective PM sospir&ograve;. Era quasi riuscito a sbarazzarci del cinismo dell'assistente senza dover prenderne la colpa. Forse la prossima volta.
</p><p>&nbsp;
</p><p>Il giudice buss&ograve; cortesemente alla porta dell'assistente. Quando apr&igrave; la porta, l'assistente fu subito abbagliata dalla luce e non vide chi c'era. "Scusate, &egrave; solo l'alba? Chi mi disturba a quest'ora?"
</p><p>"Mi scusi, assistente, ma il detective PM ha bisogno del suo aiuto per un caso complicato e importante. Ci pu&ograve; accompagnare al tribunale?"
</p><p>Gradualmente gli occhi si misero a fuoco e si adattarono allo sfolgorio di colori caldi, e l'assistente si rese conto che non doveva lottare contro l'alba ma contro i vestiti del detective PM. "Sempre il solito pavone che vuole esibirsi!", osserv&ograve;. "Devo prendere anch'io una maglietta orrenda per stare al gioco? Anzi, due magliette?", si corresse guardando anche quello che il detective PM usava come pantaloni. "No, meglio non metterlo in imbarazzo con i miei vestiti ancora pi&ugrave; agghiaccianti. Va bene questi vestiti semplici di casa. Per&ograve;, aspettate un attimo e prender&ograve; la cartella con gli attrezzi dell'indagine." L'assistente rientr&ograve; in casa, e il detective pens&ograve; con un sospiro, "Perch&eacute; mi prende sempre in giro? Quando avr&ograve; la forza per sbarazzarmi di lei? La vorrei licenziare, ma non ci riesco."
</p><p>&nbsp;
</p><p>Il detective PM non andava spesso al tribunale. Lo trovava soffocante, troppo rigido, come se ci fosse solo un'unica verit&agrave; e un'unica giustizia. Preferiva lavorare alla scena del crimine, o cercare i colpevoli mentre erano ancora in libert&agrave;. In questo caso, forse sarebbe bastata una breve chiacchierata con la donna per capire il crimine, poi sarebbe potuto uscire di nuovo, risolvere il caso, e magari fare un pisolino prima di pranzo. Il giudice li condusse attraverso le stanze del tribunale prima di arrivare ad una porta con una guardia.
</p><p>"Non l'ha messa nella prigione, anzi sembra una stanza per gli ospiti importanti, eppure ha messo una guardia alla porta?", chiese il detective PM al giudice.
</p><p>"Fino a quando non &egrave; accusata di un reato, che non posso fare senza sapere il reato di cui accusarla, lei &egrave; libera di andarsene. La guardia invece &egrave; la sua, non la mia."
</p><p>"Ha una guardia personale? Ma chi &egrave; questa donna?"
</p><p>"Adesso ve la presento."
</p><p>Entrarono nella stanza, che era infatti piuttosto lussuosa. La donna era sdraiata sul letto, pancia in gi&ugrave;, e non si muoveva tranne per fare qualche singhiozzo. Alcuni piatti di ottimo cibo erano lasciati ordinatamente e non toccati sul tavolino, e tutta la biancheria della stanza non era usata.
</p><p>"Questi sono il detective PM e la sua assistente, che sono venuti per aiutarmi con il suo caso. E questa signora &egrave;&hellip;" Il giudice non voleva ancora rivelare la vera identit&agrave; della donna, ma si accorse che non aveva un modo per presentarla.
</p><p>"Mi chiamavo Otsuig, ma non pi&ugrave;", offr&igrave; la donna, che era un sollievo per il giudice perch&eacute; non aveva svelato il suo ufficio.
</p><p>Un pensiero volava nel cervello del detective PM, appena fuori della zona dei ricordi chiari. Quei capelli con una miriade di tinte e sfumature, le vesti lunghe, colorate, e poco pratiche. Aveva sentito delle storie di una tale donna da qualche parte, ma dove? Quale prigioniero sta nella stanza migliore del tribunale con la propria guardia? Dai, era un detective, anzi IL detective PM, doveva essere in grado di dedurre la sua identit&agrave;. E allo stesso fare una buona figura.
</p><p>"Assistente, dammi subito il libro delle persone importanti della nostra Nazione."
</p><p>L'assistente frug&ograve; nella sua cartella, e tir&ograve; fuori un libro pesante. Il detective PM sfogli&ograve; velocemente le pagine, e trov&ograve; la pagina con la foto che si ricordava. Era proprio lei! "Il direttore della giustizia?! No, no, e ancora no! Non se ne parla affatto. Non voglio avere niente a che fare con quella&hellip; creatura! Il mostro del tribunale, la strega della legge!"
</p><p>"Davvero, Lei &egrave; il Direttore della Giustizia?", chiese l'assistente con gli occhi e la bocca spalancati. "Lei &egrave; il mio eroe! Non ho mai pensato di incontrarla, io che sono una semplice assistente. Ha sempre fatto osservare e praticare la giustizia nella nostra Nazione, proteggendo gli sfruttati. Senza di Lei, ci sarebbe solo il caos."
</p><p>"Non pi&ugrave;, cara." L'entusiasmo dell'assistente risvegli&ograve; leggermente la personalit&agrave; del direttore della giustizia. "Non solo non sono pi&ugrave; il Direttore della Giustizia, non sono pi&ugrave; Otsuig, e non osservo n&eacute; pratico la giustizia, tantomeno farla osservare. Sono senza ufficio e senza nome, sono nessuno."
</p><p>L'assistente si avvicin&ograve; al letto e prese la mano del direttore della giustizia. "Non si preoccupi, il Detective PM pu&ograve; risolvere qualsiasi caso e scoprire la verit&agrave; di questo reato di cui Lei &egrave; ingiustamente accusata."
</p><p>"Non capisce", ribatt&eacute; il direttore della giustizia. "Sono io che mi accuso, io so che sono colpevole, chiedo soltanto di essere processata, condannata, e punita per il mio crimine."
</p><p>"E quale sarebbe questo crimine?"
</p><p>Subito si riscaten&ograve; in un pianto furioso, e il corpo del direttore della giustizia fremeva e tremava dall'emozione. L'assistente si avvicin&ograve; ancora di pi&ugrave;, diede un abbraccio al direttore della giustizia, e disse, "Va bene, capisco che non lo vuole dire. Il Detective PM qui, lui scoprir&agrave; e risolver&agrave; il problema." Il pianto e l'abbraccio durarono cinque minuti, durante i cui il giudice e il detective si guardarono le scarpe, fuori dalla finestra, le unghie delle mani - qualsiasi cosa per non dover interagire con queste emozioni. Inoltre, il detective PM era ancora a suo disagio stare nella presenza del direttore della giustizia, e voleva scappare il primo possibile.
</p><p>Infine, il direttore della giustizia chiese, "Ma cosa vogliono dire le lettere PM?"
</p><p>Il detective PM, contento di ritornare ad un terreno conosciuto, rispose, "Secondo Lei, che pu&ograve; essere?"
</p><p>"Nel mio ufficio, sta per 'primo medio', cio&egrave; il livello pi&ugrave; alto dei dirigenti di livello intermedio."
</p><p>"Pu&ograve; essere per Lei, come dico sempre, ogni risposta &egrave; giusta. Intanto, credo di aver tutte le informazioni di cui ho bisogno, almeno tutte le informazioni utili che riuscir&ograve; ad aver da Lei, e la saluto", rispose il detective PM prima di fare una fuga veloce, seguito pi&ugrave; lentamente dal giudice e poi dall'assistente.
</p><p>&nbsp;              
</p><p>Nel corridoio, il detective PM interrog&ograve; subito il giudice: "Perch&eacute; non mi ha detto che era il direttore della giustizia? Non voglio fare niente per aiutarla!"
</p><p>"Mi dispiace, ma &egrave; il mio diritto come giudice di fare cos&igrave; se aiuta a ottenere la giustizia. Ho pensato che forse avrebbe reagito cos&igrave;, quindi non ho detto tutta la verit&agrave;, ma senza mentire. Ma pensi cos&igrave;, forse sar&agrave; l'opportunit&agrave; per togliersi dal suo ufficio." Il giudice non pensava n&eacute; voleva che ci&ograve; sarebbe successo, anche se supponeva che fosse possibile. Non era una bugia, secondo lui, ma un adescamento affinch&eacute; il detective PM collaborasse. Il giudice lo conosceva bene, e sapeva come farlo fare quello che voleva. E il giudice voleva sistemare tutto prima che qualche mercenario della giustizia sentisse del direttore della giustizia ed eseguisse la propria giustizia verso di lei.
</p><p>"Pu&ograve; darsi&hellip; Sono disposto ad aiutarla, se di conseguenza viene sbattuta dietro le sbarre. Quindi, quando &egrave; arrivata qui?"
</p><p>"Ieri sera, al tramonto."
</p><p>"Allora, la capitale della Nazione della Giustizia sta ad un giorno di cammino da qui, per cui secondo i miei stupefacenti calcoli &egrave; partita presto ieri mattina. Ha probabilmente fatto qualcosa di veramente malvagio l'altro ieri, possibilmente molto presto ieri mattina. Dobbiamo indagare sui suoi impegni di due giorni fa, controllare la sua agenda, parlare con tutti quelli che l'hanno vista in quel periodo. Dove cominciare? Vediamo&hellip;"
</p><p>Le guardie migliori sono quelli che non si vedono, non perch&eacute; sono invisibili ma perch&eacute; non sono notate. Per&ograve; sono pronte per entrare in azione quando ce n'&egrave; la necessit&agrave;. Infatti, nessuno dei tre aveva fatto caso che una delle guardie del direttore della giustizia era ancora l&igrave; nel corridoio e che ascoltava tutto, pur facendo finta di non sentire.
</p><p>"Chiedo perdono per il disturbo, ma forse vi posso aiutare, signori".
</p><p>"Chi ha parlato? Da dove viene questa voce?", chiese il detective PM guardandosi intorno. "Ah, certo, la guardia. Ma non devi chiedere perdono se non ha fatto niente di sbagliato verso di me. Sai tutto quello che il direttore della giustizia ha fatto recentemente, giusto?"
</p><p>"S&igrave;, &egrave; cos&igrave;. Ha cominciato di piangere ieri sera dopo l'ultimo caso del giorno, poi tutta la notte ha pianto e gridato. Presto stamane &egrave; partita senza chiamarci, e tutti noi che viaggiamo con lei si sono sbrigati per seguirla."
</p><p>"Ottimo! E quale era questo ultimo caso del giorno."
</p><p>"Non lo so, noi guardie non assistiamo ai casi, rimaniamo fuori. Per&ograve; i impiegati che hanno venuto con lei ve lo potr&agrave; dire."
</p><p>"Grazie guardia. Giudice, ci porti agli impiegati!"
</p><p>&nbsp;
</p><p>Trovarono gli impiegati del direttore della giustizia nella mensa del tribunale. Sembravano quasi tre gemelli monozigoti. Anche se non esisteva una divisa nell'Ufficio della Giustizia, erano tutti vestiti nello stesso modo, ordinati e seri. Avevano tutti e tre i capelli pettinati da una parte, con la riga. Il giudice present&ograve; loro il detective PM e l'assistente. L'impiegato pi&ugrave; anziano rispose, "Piacere, io sono l'Impiegato PM, e questi sono i miei colleghi Impiegato SM e Impiegato TM."
</p><p>"Suppongo che io possa decidere per che cosa stanno PM, SM, e TM", afferm&ograve; l'assistente, fiera della sua abilit&agrave; di aver capito subito. "Allora, secondo me sono&hellip;"
</p><p>"Certo che no, sono i nostri titoli. Io sono nella prima categoria del rango medio dell'Ufficio della Giustizia, e i miei colleghi sono della seconda e della terza categoria. Come possiamo esservi d'aiuto? Vi dispiace se continuiamo a mangiare mentre parliamo?"
</p><p>"Niente affatto", rispose il detective PM. "Anzi cogliamo l'opportunit&agrave; per mettere qualcosa sotto i denti anche noi. Assistente, hai portato qualcosa, giusto?"
</p><p>"Certamente", rispose felice di potersi sfamare, e tir&ograve; fuori dalla cartella due piatti con le posate, e poi la carne e la verdura. "Mi dispiace Giudice, ma ho cibo solo per due."
</p><p>"Non &egrave; un problema, posso farmi portare qualcosa nel mio ufficio pi&ugrave; tardi. Per il momento voglio risolvere questa situazione delicata in cui mi trovo. Impiegati, prima di tutto grazie per il vostro aiuto. Stiamo cercando di capire che cosa ha fatto il Direttore della Giustizia, e cosa l'ha ridotta in questo stato. Ci pare che sia successo qualcosa nell'ultimo caso di due giorni fa. Ci potete illuminare su quello che &egrave; accaduto in quel momento?"
</p><p>"Prima di tutto", rispose l'impiegato PM, "il Direttore della Giustizia non valuta i casi, non &egrave; un giudice. Dico bene?", chiese conferma all'impiegato SM.
</p><p>"Giusto", replic&ograve; il collega.    
</p><p>"Allora, valuta piuttosto come viene applicata la giustizia, sentendo dubbi dei giudici e mandando loro indicazioni. Che, se non erro, &egrave; dove Lei, Giudice, si &egrave; scontrato con il Direttore della Giustizia nel passato."
</p><p>"Non erra, collega. Qual era l'accusa di nuovo?", chiese l'impiegato SM all'impiegato TM.
</p><p>L'impiegato TM spost&ograve; alcune carte prima di trovare la risposta, e poi disse solennemente, "L'accusa &egrave; stata ingiustizia verso l'illustre Nazione e le sue istituzioni".
</p><p>"Ingiustizia verso l'illustre Nazione e le sue istituzioni", rifer&igrave; l'impiegato SM.
</p><p>"Grazie, Impiegato SM. Ingiustizia verso l'illustre Nazione e le sue istruzioni", disse al giudice.
</p><p>"Me lo ricordo bene, ma sono una persona diversa adesso", ribatt&eacute; il giudice.
</p><p>"Quindi il ruolo del Direttore della Giustizia", prosegu&igrave; come se il giudice non avesse parlato, "&egrave; di verificare che la giustizia sia fatta in generale, piuttosto di occuparsi di casi particolari."
</p><p>Il detective PM cerc&ograve; di ritornare al punto. "Conosciamo bene come il direttore della giustizia esercita il suo immenso potere, ma con chi ha parlato alla fine della giornata dell'altro ieri, e che cosa &egrave; successo?"
</p><p>"Allora, il nome ve lo posso dire. Si chiamava&hellip;", e guard&ograve; l'impiegato SM senza dire una parola, che si gir&ograve; e guard&ograve; l'impiegato TM, che intese la domanda silenziosa. Spost&ograve; di nuovo alcune carte, trov&ograve; il nome, guard&ograve; l'impiegato SM senza dire una parola, che si gir&ograve; a sua volta e guard&ograve; l'impiegato PM, che intese la risposta silenziosa. "Si chiamava Ecilpmes. Per&ograve; non sappiamo quello che sia successo. Si &egrave; presentato al nostro ufficio alla fine della giornata, naturalmente abbiamo registrato la sua presenza con nome e indirizzo, ma poi quando il Direttore della Giustizia l'ha visto, l'ha invitato ad entrare con lei nell'ufficio privato del Direttore, senza neanche la nostra presenza per consigliare."
</p><p>"N&eacute; per comunicare richieste per informazioni", aggiunse l'impiegato SM.
</p><p>"N&eacute; per verbalizzare l'incontro", aggiunse l'impiegato TM.
</p><p>"Poi dopo una mezz'ora Ecilpmes &egrave; uscito", prosegu&igrave; l'impiegato PM. "Poco dopo, forse 10 minuti, anche il Direttore della Giustizia &egrave; uscita per andare a casa, accompagnata da qualche guardia come consueto, ma abbiamo notato che piangeva mentre usciva."
</p><p>"Grazie per il racconto", disse il giudice sinceramente. Si gir&ograve; e chiese "Cosa ne pensa?" al detective PM, che si gir&ograve; e chiese all'assistente, "Cosa ne pensi?" L'assistente, sorpresa di essere interpellata, riusc&igrave; solo a balbettare, "Che ne so io?" Poi pens&ograve; di un commento spiritosa e aggiunse, "Non siamo mica come Qui, Quo, e Qua davanti a noi."
</p><p>Il detective PM si gir&ograve; e guard&ograve; il giudice, "Penso che andremo a trovare Ecilpmes, che ci potr&agrave; spiegare quello che &egrave; successo e perch&eacute; il direttore della giustizia si comporta in modo strano. Ormai &egrave; troppo tardi per partire oggi, ci metteremo in viaggio domani mattina."
</p><p>"Purtroppo, non potr&ograve; accompagnarvi", chiar&igrave; il giudice, "ho gi&agrave; dovuto rimandare alcuni casi oggi, e non potr&ograve; mancare domani. Mi aspetter&ograve; un resoconto e spiegazione dopodomani. Intanto, cercher&ograve; di tenere tranquilla il Direttore della Giustizia."
</p><p>&nbsp;
</p><p>Mentre il detective PM e l'assistente ritornavano a casa, l'assistente osserv&ograve;, "Questo caso non &egrave; cos&igrave; divertente come gli altri, per esempio quello dell'uomo normale."
</p><p>"S&igrave;, &egrave; vero", il detective PM concord&ograve;, "a volte ci vuole un altro stile per spiegare o risolvere un caso, soprattutto quando ci sono altri elementi pi&ugrave; seri presenti".
</p><p>&nbsp;
</p><p>Quando il detective arriv&ograve; a casa sua, pens&ograve;, "Questa volta non mi trover&ograve; impreparato! Sceglier&ograve; adesso i vestiti per domani". Perlustr&ograve; il suo armadio per trovare qualcosa di decente, che era pi&ugrave; difficile di quanto immaginasse. "I vestiti variopinti con i grandi cerchi? No, non sono andati bene l'ultima volta. Il completo in sei sfumature di bianco? Forse &egrave; po' insipido per i miei gusti. Quella camicia sembra adatta - ma, c'&egrave; solo una manica, adesso che ci penso era rimasta dal caso del pescatore con una mano solo, non avrei dovuto lasciarla con i miei vestiti. Ma aspetta, non era l'altro braccio che mancava? Ah, dimenticavo, era ambidestro, portava tutti e due i tipi di camicia. La pi-shirt?" Era una sua invenzione, come una t-shirt ma con un rettangolo verticale tagliato e tolto sia davanti sia dietro, in modo che il resto alla maglietta somigliasse al pi greco. Non aveva mai capito perch&eacute; non fosse diventata popolare, neanche fra i suoi amici matematici che aveva conosciuto durante i suoi studi (era una delle sue cinque lauree). "Fino a quando diventer&agrave; di moda &egrave; forse meglio non indossarla." Dopo non aver trovato niente di indossabile nell'armadio, si ricord&ograve; che aveva trovato in mansarda una scatola con alcuni vestiti che appartenevano all'ultimo proprietario della casa. "Chi sa, magari ci sar&agrave; qualcosa?" Corse su per le scale e tir&ograve; fuori la scatola. "Vestito da donna, no. Giacca e cravatta, mai le indosser&ograve;! Pigiama&hellip; non &egrave; male. No, questa volta esco con vestiti per il giorno. Aspetta, cosa abbiamo qua? Una camicia rossa e pantaloni bianchi eleganti, ancora con le etichette del negozio. Potrebbero andare! L'assistente non avr&agrave; niente da dire questa volta quando vedr&agrave; la mia eleganza naturale." Li prov&ograve;, e gli stavano a pennello. Poi fece un grosso starnuto. Erano pieni di polvere. Bisognava lavarli prima di domani. "Per fortuna", ragion&ograve; il detective PM, "anch'io mi posso lavare, anche se non sono ancora passati quattro giorni dall'ultima volta. Posso risparmiare un bel po' di tempo e di acqua facendo tutto insieme."
</p><p>Il detective PM prepar&ograve; un bel bagno caldo, versando nell'acqua un po' di bagnoschiuma, lo shampoo, un balsamo, e una tazza piena di detersivo per i vestiti. Poi decide che ci voleva anche l'ammorbidente, siccome i vestiti erano stati piegati da tanto tempo, e che comunque dopo tutto quella distanza che aveva camminato quel giorno, le sue articolazioni erano un po' rigide e gli facevano male. Si abbass&ograve; lentamente nella vasca e si rilass&ograve;, lasciando agire tutti i chimici sul suo corpo e sui suoi bellissimi nuovi vestiti. Che bello era stare l&agrave;, tranquillo, senza interruzioni, senza l'assistente con lo insultava, senza&hellip;
</p><p>Si risvegli&ograve; bruscamente quando sent&igrave; qualcuno bussare, seguito dalla voce dell'assistente, "Detectivino!"
</p><p>"Perch&eacute; mi disturba adesso, non ci dobbiamo vedere domani mattina?", si indign&ograve;, e poi sent&igrave; un brivido. L'acqua era freddissima. "Ma secondo la legge del raffreddamento di Newton, con temperatura iniziale di 40 gradi, temperatura ambiente di 18 gradi", pens&ograve; continuando con i calcoli mentali, "sono passate delle ore. &Egrave; gi&agrave; mattina!"
</p><p>Il detective PM balz&ograve; dalla vasca, asciug&ograve; s&eacute; stesso e i suoi vestiti il pi&ugrave; veloce possibile ma con gli occhi ancora socchiusi dal sonno, gridando, "Arrivo! Preparo alcune&hellip; cose". Si infil&ograve; le pantofole che trov&ograve; per terra e si affrett&ograve; fuori.
</p><p>"Buon giorno, mio detectivino", lo salut&ograve; l'assistente, "riesci sempre a stupire con il suo senso della moda".
</p><p>Il detective PM, momentaneamente compiaciuto per il presunto complimento, si guard&ograve; orgogliosamente per la prima volta, ma l'orgoglio si trasform&ograve; rapidamente in orrore quando si accorse dell'effetto del suo lungo lavaggio. Gli scuri non vanno mescolati con i chiari, n&eacute; in lavatrice n&eacute; in vasca da bagno. Tutto il rosso della camicia era sbiadito, e non soltanto i pantaloni contenevano diverse tonalit&agrave; di rosa, ma anche la faccia e le braccia del detective PM. Il detersivo non sciolto aveva lasciato macchie sui vestiti in forma di fiori, animali ("&egrave; un bradipo?", chiese l'assistente indicando la spalla destra), e simboli segreti di popoli antichi persi da millenni.
</p><p>Il detective PM, sconsolato, stronc&ograve; ogni discussione e salut&ograve; la sua assistente solo con, "Andiamo".
</p><p>&nbsp;
</p><p>Camminarono insieme senza parlare per quasi un'ora prima che l'assistente, stufa e annoiata, decidesse di rompere il muro di silenzio fra di loro. "Che cosa ha fatto il Direttore della Giustizia di cos&igrave; terribile, secondo te? Hai capito qualcosa con il tuo grande intelletto e intuito?"
</p><p>Il detective PM era contento del complimento e per l'opportunit&agrave; di parlare di quello di cui era l'esperto (e non dei suoi vestiti), seppellendo il lieve sospetto che era un commento sarcastico, perch&eacute; l'alternativa della sincerit&agrave; gli faceva stare peggio.
</p><p>"Ovviamente &egrave; stato qualcosa di grosso e di grave. Un omicidio?"
</p><p>"Ma non &egrave; una tipa da omicida", ribatt&eacute; l'assistente.
</p><p>"&Egrave; vero, doveva essere qualcosa che in qualche modo &egrave; stata costretta a fare contro la sua volont&agrave;. Non necessariamente con la forza, ma con qualcosa che ha scoperto di essere pi&ugrave; importante della giustizia."
</p><p>"Pi&ugrave; importante della giustizia? Non esiste, &egrave; il fondamento della nostra esistenza e della nostra gloriosa Nazione!"
</p><p>"Certo, noi lo sappiamo, ma se in un momento di confusione o di debolezza il direttore della giustizia l'avesse dimenticato, spiegherebbe perch&eacute; ha infranto la legge, e perch&eacute; adesso &egrave; cos&igrave; distrutta e disperata. Forse possiamo pensare a qualche reato durante il nostro viaggio. Hai portato il codice della giustizia?"
</p><p>"Naturalmente", rispose l'assistente con un sorriso, contenta di poter assistere. "Ho l'edizione deluxe e completa in 18 volumi, rilegata in pelle. Quale volume ti serve?"
</p><p>"Voglio dare un'occhiata all'indice, che contiene l'elenco di crimini."
</p><p>"Sar&agrave; fatto!" L'assistente rovist&ograve; nella sua cartella, mormorando a s&eacute; stessa, "il volume 4, il 9, Cenerentola, devo mettere un po' di ordine qui dentro". Poi ad alta voce, "Ecco, il volume 18 del codice della giustizia."
</p><p>"Cominciamo dall'inizio: abbandono degli animali (no, non aveva un animale), abbandono dei minori (neppure un figlio), abuso dei mezzi di correzione (non credo), abuso di mercato (improbabile), abuso di potere (questa &egrave; una possibilit&agrave;), abuso edilizio (dove abitava?), tanti altri reati di abuso, adescamento, aggiotaggio (non so neanche cosa sia!), alterazione di monete, alto tradimento, ammutinamento, associazione per delinquere, associazione sovversiva, attentato, aucupio, &hellip;"
</p><p>"Per&ograve; detectivino, non riusciremo mai a trovare quello giusto da un elenco cos&igrave; lungo. Ce ne sono troppi!"
</p><p>"Non sono troppi per la nostra giusta Nazione. Le persone scoprono sempre nuovi modi per fare cose ingiuste agli altri, o qualche scappatoia in quello che &egrave; proibito, per cui ci vogliono sempre pi&ugrave; limiti su ogni dettaglio della vita. Ma hai ragione, sono troppi per decidere quale abbia fatto il direttore della giustizia, &egrave; uno spreco di tempo", rispose il detective PM, restituendo il libro all'assistente. "Lasciami riflettere un po' sulle possibilit&agrave;." Cos&igrave; proseguirono per il resto del viaggio con il detective PM avvolto nei suoi pensieri, e l'assistente che si chiedeva che cosa stesse pensando quel meraviglioso cervello.
</p><p>&nbsp;
</p><p>Il detective PM e l'assistente si avvicinarono alla capitale della Nazione della Giustizia verso il tramonto. L'assistente non ci era mai andata, e si meravigli&ograve; della meravigliosa vista della citt&agrave;. Era costruita su ben sette colline, e su ogni collina c'era un tribunale. Sei colline circondavano la collina pi&ugrave; alta, su cui ergeva il pi&ugrave; grande e maestoso tribunale che avesse mai visto. Davano un senso di ordine, che tutto andava bene, che niente di ingiusto poteva sopravvivere. I colori del tramonto dietro il tribunale mettevano in risalto la severit&agrave; del bianco e nero della struttura; sembravano adornare la citt&agrave; come una magnifica corona. Pur essendo abbastanza distante dalla citt&agrave;, potevano percepire i rumori della vita e delle attivit&agrave; della gente. In confronto, il loro paese era moribondo.
</p><p>"Detectivino, &egrave;&hellip; &egrave;&hellip; incredibile!" Le mancavano le parole per descrivere lo splendore della capitale.
</p><p>Il detective PM aveva viaggiato per la capitale qualche volta nel passato, e si ricordava che aveva avuto una simile impressione le prime volte che l'aveva vista. Ormai ci era un po' abituato e non lo colpiva come prima, ma sperimentando la vista indirettamente attraverso gli occhi dell'assistente, anche lui si meravigli&ograve; di nuovo della bellezza della capitale, come le sue prime volte. "Purtroppo", riflett&eacute; a s&eacute; stesso, "prendiamo per scontato quello che &egrave; giusto e bello, lo svalutiamo per accettare e vivere nella mediocrit&agrave;."
</p><p>"Gi&agrave;", era l'unica cosa che il detective PM &egrave; riuscito a dire, senza sporgersi troppo nel manifestare le sue emozioni. Poi pens&ograve; che l'assistente meritasse qualcosa di pi&ugrave; dopo essersi esposta, dopo averlo aiutato ad apprezzare nuovamente la vista della capitale, e soprattutto che la capitale meritasse di essere glorificata per la sua&hellip; gloria, e aggiunse, "&Egrave; veramente una vista meravigliosa, grazie per avermi restituito il piacere di ammirare la bellezza piuttosto di solo notarla."
</p><p>L'assistente, non abituata ad affermazioni simili da parte del detective PM, lo guard&ograve; curiosamente. Cosa gli era successo?
</p><p>&nbsp;
</p><p>Cercarono l'indirizzo che l'impiegato PM aveva dato loro, spingendosi attraverso la gente che affollava tutte le strade. Prima passarono un quartiere residenziale, dove sembrava che tutti fossero fuori per chiacchierare, fare commissioni, o andare da un'altra parte. Tutti in movimento, sempre impegnati a fare qualcosa, che creava un gran caos e pi&ugrave; confusione che nel paese del detective PM e della sua assistente. Inoltre, la presenza della polizia era molto vistosa: era impossibile trovare un posto pubblico in cui non c'era almeno un poliziotto visibile. Cos&igrave; la giustizia era mantenuta in una citt&agrave; con molte pi&ugrave; possibilit&agrave; di ingiustizia che in un paese piccolo. Per&ograve;, non avvertivano un'atmosfera di paura n&eacute; di sfiducia verso la polizia; anzi, la gente salutava e sorrideva ai poliziotti, perch&eacute; erano persone giuste che non dovevano temere la giustizia.
</p><p>Dopo il quartiere residenziale, passarono per una zona commerciale, una zona industriale, e infine un quartiere pi&ugrave; mal ridotto in cui vivevano gli operai dell'industria. Qui c'era meno gente in giro, perch&eacute; avevano meno da fare. Chiesero indicazioni a qualche passante, e trovarono la via di Ecilpmes, che era poco pi&ugrave; di un vicolo. Le case in questa via non erano mantenute bene, con pezzi che cadevano, spazzatura per terra, e tutte le porte e finestre ben chiuse e barricate. Una ragazza che giocava da sola nella strada gli indic&ograve; la casa di Ecilpmes. Il detective PM buss&ograve;, ma non ci fu nessuna risposta. Buss&ograve; di nuovo, ma ancora niente. Esamin&ograve; la semplice serratura, e cap&igrave; che la poteva scassinare. "Passami la mia forchetta di plastica con un rebbio mancante."
</p><p>"Mi dispiace, non l'ho portata oggi. Ma sono stata brava a portare tutto il resto, no? Il cibo, i piatti, il codice&hellip;"
</p><p>"Non mi interessa! La forchetta di plastica con un rebbio mancante &egrave; l'attrezzo pi&ugrave; importante e utile di un detective! Come pensi che io posso risolvere un caso senza la mia forchetta? Con il tuo dispiacere? Perch&eacute; non l'hai portata?"
</p><p>"Sono veramente mortificata! Per&ograve;, non c'era spazio nella cartella, sai, &egrave; un po' piccola. Ma hai ragione, ho sbagliato io, dovevo mettere la forchetta invece di un'altra cosa. Mi puoi perdonare questa volta?"
</p><p>"Stai scherzando?", rispose il detective PM infuriato. "Il perdono non serve per niente, non far&agrave; apparire magicamente la mia forchetta, e rimarremo chiusi fuori."
</p><p>L'assistente era ancora pi&ugrave; mortificata per la rabbia del detective PM che per aver dimenticato la forchetta. Ci era voluto poco per trasformare i sentimenti teneri che aveva espresso avvicinandosi alla capitale nella solita chiusura verso di lei. Cerc&ograve; almeno di rimediare con un consiglio per la loro difficolt&agrave;.
</p><p>"Sai, una volta il Giudice mi ha raccontato quello che fa quando lui bussa e tu non rispondi. Ha detto che ti manipola, approfittando del tuo punto debole, cio&egrave; la curiosit&agrave; e il bisogno di essere affermato come bravo detective. Cos&igrave; ti grida attraverso la porta che &egrave; un caso interessante e difficile e importante, e prima o poi vieni fuori".
</p><p>"Davvero &egrave; cos&igrave;? Sono cos&igrave; debole e prevedibile?", rispose il detective PM sorpreso, ancora un po' arrabbiato, e leggermente incredulo. "Sar&agrave; vero?", medit&ograve; tra s&eacute; e s&eacute;. "Posso capire le motivazioni degli altri ma non di me stesso, sono un libro aperto agli altri? Dovr&ograve; parlarne con il giudice quando avr&ograve; risolto il caso, che sicuramente riuscir&ograve; a fare."
</p><p>Continu&ograve; il suo ragionamento ad alta voce. "Comunque, non sappiamo niente di Ecilpmes per adescarlo. Solo che conosce il direttore della giustizia. Proviamo&hellip;"
</p><p>Grid&ograve; alla porta, "Vogliamo parlarti del direttore della giustizia". Ancora silenzio. Poi ebbe un lampo di intuizione. "Di Otsuig."
</p><p>Alla menzione del nome, sentirono qualche rumore da dentro la casa: due passi, un oggetto spostato, una gola schiarita. Poi una voce, "Come sai il suo nome?"
</p><p>"Me l'ha detto, quando mi ha chiesto il mio aiuto per risolvere i suoi problemi." Non era del tutto giusto quello che aveva detto, ma doveva per forza parlare con Ecilpmes, e sembrava un'esca efficace.
</p><p>Sentirono il movimento di una chiave nella serratura e lo spostamento di alcune sbarre, e finalmente la porta si apr&igrave; per rivelare un uomo di mezz'et&agrave;, i capelli grigi pettinati diritti. In contrasto al degrado del quartiere, l'uomo aveva un aspetto ordinato, pur con vestiti semplici, non colorati. Dietro la porta mezza aperta, era possibile intravedere una stanza con pochi ma essenziali e funzionali mobili.
</p><p>"Quali problemi ha Otsuig?", l'uomo interruppe l'analisi del detective PM.
</p><p>"Ah, s&igrave;, Otsuig. &Egrave; venuta al mio paese, dove ha alcuni amici" - di nuovo, non proprio giusto, ma necessario - "perch&eacute; le &egrave; successo qualcosa di brutto. Non sappiamo che cosa di preciso, ma siamo venuti qui alla capitale per indagare sull'avvenimento, per sapere meglio come aiutarla." Aggiunse a s&eacute; stesso, "Come mai un uomo cos&igrave; conosce il nome del direttore della giustizia? E come si permette di usarlo?"
</p><p>"Entrate quindi", invit&ograve; l'uomo aprendo completamente la porta. "Io sono Ecilpmes. Voi?"
</p><p>"Io sono il Detective PM, e lei &egrave; la mia assistente."
</p><p>"PM, come un Poliziotto Magnifico?"
</p><p>"Se ti piace, va bene."
</p><p>"Ma dove sono finite le mie buone maniere?! Siediti pure, volete qualcosa da mangiare?"
</p><p>Il detective PM stava per sedersi, quando Ecilpmes prese la sedia e l'ha offerta all'assistente. "Prima le signore. Scusate, non ho molti ospiti, e ho solo una sedia. Se mi permettete, cerco del cibo in cucina."
</p><p>Usc&igrave; dalla stanza, lasciando l'assistente seduta e il detective PM in piedi. Il detective PM colse l'opportunit&agrave; per esaminare la stanza per raccogliere degli indizi, per capire quello che questo uomo semplice aveva fatto per distruggere una persona cos&igrave; potente e sicura di s&eacute; come il direttore della giustizia. Per dire la verit&agrave;, in questa casa disadorna c'era poco da esaminare. La sedia e un tavolino, una luce debole, un paio di immagini in una cornice di legno rustico di una famiglia con due figli, e una scatola con alcuni attrezzi per un lavoro manuale che il detective PM non riusc&igrave; a capire. Ecilpmes rientr&ograve;, e offr&igrave; un piatto con del pane condito e una brocca d'acqua. "Siete fortunati, avevo fatto un po' di spesa proprio questo pomeriggio."
</p><p>"Magari dopo", rispose il detective mentre l'assistente, affamata dopo il lungo viaggio quel giorno, stendeva la mano per prendere qualsiasi cosa; si ritir&ograve; subito la mano mentre la sua pancia si ribellava.
</p><p>Il detective PM si ferm&ograve;, e gli venne in mente il pensiero che quelle immagini erano importanti. Chi sono queste persone? La moglie e i figli di Ecilpmes? No, la carta era vecchia e l'immagine sbiadita. "Sar&agrave; lui piuttosto il figlio? Poi gli altri&hellip; E la familiarit&agrave; con il direttore della giustizia?" Azzard&ograve; un'ipotesi, "Il direttore della giustizia non &egrave; per caso tua sorella?"
</p><p>"S&igrave;, certo, ha 18 mesi meno di me. Eccoci nell'immagine che stai guardando."
</p><p>Era difficile per il detective PM pensare al direttore della giustizia come una bambina. "Come era quella sgargiante tiranna della giustizia da piccola?", pens&ograve;. "Magari non &egrave; sempre stata come &egrave; adesso, forse era una delinquente, o un maschiaccio, o una ragazza superficiale. Possibilmente Ecilpmes sa qualche segreto nascosto del direttore della giustizia, qualche crimine orrendo che ha commesso da giovane. Forse ha minacciato di rivelarlo, o cercato di ricattarla - senz'altro gli servirebbero dei soldi per sistemarsi per bene. Dovr&ograve; stare attento a come lo interrogo, per farsi incastrare senza che se ne renda conto."
</p><p>In quel momento, l'assistente sbott&ograve;, "Sai quale crimine orrendo ha commesso il Direttore della Giustizia? Perch&eacute; dice di aver fatto qualcosa di terribile".
</p><p>"Otsuig commettere un crimine?! Stai scherzando? &Egrave; la persona pi&ugrave; giusta che esista!"
</p><p>Sfumato quell'approccio di interrogazione, il detective PM prov&ograve; in un altro modo. "Eravate vicini da piccoli?"
</p><p>"S&igrave;, quando eravamo bambini e poi ragazzi, pi&ugrave; amici di noi non si poteva essere. Ci chiamavano 'i gemelli', bench&eacute; la differenza in et&agrave;, perch&eacute; facevamo tutto insieme, stavamo sempre insieme, ci piacevano le stesse cose. Che risate abbiamo fatto, che gioia stare insieme, &hellip;" Il volume della voce diminu&igrave; mentre Ecilpmes era preso dal momento di nostalgia piacevole.
</p><p>"Hai detto quando eravate bambini e ragazzi. E dopo, da giovani? Adesso?"
</p><p>La faccia di Ecilpmes mut&ograve; perch&eacute; la nostalgia divenne meno piacevole. "Verso l'inizio dell'adolescenza, ci siamo pian piano allontanati. Non era una decisione presa da nessuno di noi, ma una tendenza naturale causata da come crescevamo diversamente, da come cambiavamo. Diventava sempre pi&ugrave; evidente la sua intelligenza, anzi la sua genialit&agrave;, e la sua sensibilit&agrave; per la giustizia, e ha cominciato a impegnarsi in molti movimenti giovanili (e non) per promuovere e combattere per la giustizia. E riusciva e spiccava in tutto quello che faceva. Mentre io, io, ma come vedete, io sono un uomo semplice, mi piacciono le cose semplici, e riesco solo a fare le cose semplici. Cos&igrave; i nostri interessi e le nostre abilit&agrave; si sono separati, come pur noi stessi. Inoltre, lei ha meritatamente ricevuto tanto, cose che io non ho ricevuto perch&eacute; non mi servivano. L'educazione, l'opportunit&agrave; di viaggiare per conoscere altre realt&agrave;, contatti con le menti migliori della citt&agrave; e della Nazione. Mentre io sono andato a lavorare nella fabbrica senza finire la scuola."
</p><p>"Posso immaginare che i vostri genitori abbiano preferito il direttore della giustizia." Il detective PM non riusciva a chiamarla Otsuig, anche quando parlava di lei quando non era il direttore della giustizia, quando era piccola; sarebbe sembrato cos&igrave; innaturale dare a quel mostro un nome.
</p><p>"No, no, al contrario. Eravamo una famiglia semplice, ma l'amore dei nostri genitori era incondizionato, come deve sempre essere il vero amore. L'amore non &egrave; per quello che si pu&ograve; ottenere, ma per quello che si pu&ograve; dare, e il pap&agrave; e la mamma ci hanno dato lo stesso affetto." Prese una delle immagini, e la abbracci&ograve;. "&Egrave; vero che per molti anni ho biasimato i miei per quello che mi &egrave; successo, ma &egrave; stata solo una scusa per dare la colpa a qualcun altro. Difficilmente ammettiamo che un nostro problema, un nostro errore, una nostra difficolt&agrave;, &egrave; colpa nostra. Preferiamo razionalizzare o incolpare gli altri."
</p><p>"Dici che qualcosa ti &egrave; successo. Il direttore della giustizia ti ha fatto male?"
</p><p>"No, mi sono fatto male da solo. Sono diventato geloso, invidioso, con tanto rancore che lei era cos&igrave; e io no."
</p><p>"Era naturale, credo. Tutti risponderebbero in quel modo."
</p><p>"Forse era naturale, ma non mi d&agrave; ragione; era comunque ingiusto. Otsuig non mi ha mai fatto del male, anzi continuava ad aiutarmi e sostenermi e incoraggiarmi. Non meritava per niente i miei brutti sentimenti verso di lei. Cos&igrave; mi sono sentito male per anni, fino a qualche giorno fa. Mi sono reso conto di essere stato uno sciocco. Certo, quando ho tirato i dati della vita, mi &egrave; uscito un numero bassissimo. Ma come rispondo dipende solo da me, non dai dadi, non dai genitori, non da nessun altro. Potevo decidere di vivere bene e tranquillo, o farmi male e vivere nel risentimento."
</p><p>"Fino a qualche giorno fa, dici? E questo &egrave; il motivo per cui sei andato a parlare con il direttore della giustizia nel suo ufficio due giorni fa?"
</p><p>"Esatto. Ho ammesso il mio rancore verso di lei, che ero stato ingiusto nel mio rapporto con lei. Sapete, non se ne era mai resa conto! Non avevo mai fatto niente di male a lei, era solo tutto nella mia testa, ma era ingiusto comunque."
</p><p>"Ma quando ha saputo, ti ha fatto qualcosa di terribile, giusto?"
</p><p>"Niente affatto! Non poteva essere pi&ugrave; comprensibile, pi&ugrave; gentile. Forse un po' sorpresa per cominciare, ma poi mi ha detto che non faceva niente, che non era importante. Ci siamo saluti pi&ugrave; amici di prima."
</p><p>Il detective PM medit&ograve; su questo. L'assistente, che cercava sempre di cogliere l'opportunit&agrave; delle pause per inserire un commento, osserv&ograve;, "Quindi non sei molto utile".
</p><p>"Mi dispiace di non potervi aiutare", si rammaric&ograve;.
</p><p>"Al contrario", contraddisse il detective PM. "Abbiamo ristretto il tempo in cui &egrave; successo quello che &egrave; successo ad un periodo di dieci minuti fra l'uscita di Ecilpmes e quando il direttore della giustizia torn&ograve; a casa."
</p><p>"Un periodo di tempo in cui &egrave; stata completamente da sola, in cui non pot&eacute; fare un granch&eacute;. Davvero questo ci aiuta?"
</p><p>"Infatti, un classico enigma della camera chiusa - solo che sappiamo chi ha commesso il crimine, ma non il crimine commesso n&eacute; come."
</p><p>"Mi dispiace interrompervi ma&hellip;", inizi&ograve; a dire Ecilpmes.
</p><p>"Ti dispiace sempre cos&igrave; spesso?", interruppe l'assistente.
</p><p>"S&igrave;, quando faccio una cosa che so &egrave; spiacevole per gli altri, ma che devo fare comunque, per cui non posso che chiedere di scusarmi. Come dicevo, mi dispiace interrompere, ma &egrave; tardi per me, mi dovr&ograve; alzare presto domani per andare a lavorare. Dove starete voi stasera?"
</p><p>Il detective PM e l'assistente si guardarono, e lei osserv&ograve;, "Con tutto il tuo gran intelletto, non hai pensato che staremo qui per la notte, vero detectivino?"
</p><p>Prima che il detective PM potesse rispondere, Ecilpmes propose, "Nessun problema! Siete i miei ospiti, mi ha fatto piacere conoscere degli amici di mia sorella." Il detective PM abbass&ograve; lo sguardo - "amico" non era proprio la parola che avrebbe usato, ma rimase in silenzio. "Un amico di Otsuig &egrave; un amico mio! Tu", rivolgendosi all'assistente, "puoi dormire in camera mia, e noi maschi in questa stanza. Mi dispiace, ma &egrave; tutto quello che ho. E non ho del pigiama da offrirvi."
</p><p>"Non &egrave; un problema", ridacchi&ograve; l'assistente, "il detectivino &egrave; abituato a dormire con i vestiti e uscire con il pigiama."
</p><p>Si sistemarono per la notte, Ecilpmes per terra e il detective PM sulla sedia, dove non poteva dormire per la scomodit&agrave;, per il russare di Ecilpmes, e per i pensieri che gli frullavano nella testa. Che cosa ha potuto fare di cos&igrave; terribile in dieci minuti, e per lo pi&ugrave; da sola? Qual &egrave; la cosa pi&ugrave; ingiusta che poteva fare? Che cos'&egrave; l'ingiustizia? Questi pensieri lo perseguitarono per diverse ore, fino a quando il sonno li sopraffece. Per&ograve; poco dopo (o almeno sembrava cos&igrave; al detective PM), Ecilpmes si alz&ograve; e grid&ograve;, "Buon giorno a tutti! Io devo uscire adesso, sono gi&agrave; in ritardo per il lavoro. Potete trovare qualcosa da mangiare in cucina, insomma fate come se foste a casa vostra. Quando uscite, prendete una forchetta di plastica e chiudete a forchetta la porta - potete tenervi la forchetta. Grazie, &egrave; stato un piacere conoscervi", e poi corse fuori della casa.
</p><p>Il detective PM e l'assistente cercarono in cucina, ma la cosa pi&ugrave; commestibile che trovarono furono le foglie sull'albero fuori dalla finestra. Decisero di prendere qualcosa per strada mentre tornavano al loro paese. Il detective raccolse una forchetta di plastica e, quando erano fuori, ruppe un rebbio, us&ograve; la forchetta nella serratura per chiudere la porta, e diede la forchetta all'assistente, tutto senza dire una parola. Mentre la metteva nella cartella, l'assistente si lament&ograve; con il detective, "Dai detectivino, non ce l'hai ancora con me per la storia della forchetta? Dimenticala, non hai ascoltato quello che Ecilpmes ha detto? Serbare il rancore non serve per niente, solo per farti stare male."
</p><p>"Ma quello che hai fatto era ingiusto", replic&ograve; il detective PM arrabbiato, "e non posso fare finta che non lo fosse, che non fosse importante, sarebbe&hellip; Infatti se Ecilpmes&hellip; e poi se il direttore della giustizia&hellip;"
</p><p>L'assistente cap&igrave; quello che stava succedendo, era gi&agrave; successo altre volte. Il suo cervello elaborava dati ad una velocit&agrave; superiore a quello che la bocca poteva esprimere, che voleva dire che iniziava a comprendere la situazione. Dopo pochi secondi, il detective PM sorrise e si congratul&ograve; con l'assistente. "Grazie, come sempre, senza il tuo aiuto che avrei potuto risolvere il caso. Andiamo subito, non c'&egrave; tempo da perdere."
</p><p>&nbsp;
</p><p>Partendo presto e saltando la colazione e il pranzo a causa del desiderio di elucidare a tutti quello che era successo, il detective PM rientr&ograve; nel suo paese nel primo pomeriggio, seguito poco dopo dall'assistente che a stento teneva il passo. Si velocizz&ograve; ancora di pi&ugrave; sulla strada che saliva verso il tribunale posto in cima alla collina pi&ugrave; alta del paese. Raggiunto la porta del tribunale, chiese ad uno dei dipendenti che il giudice fosse informato del suo arrivo, e che tutti gli interessati fossero presenti nella sala di giudizio, dove avrebbe esposto il caso fra 15 minuti. Cos&igrave; si riunirono nella sala il giudice, il direttore della giustizia (ancora in lacrime), l'assistente, gli impiegati PM, SM, e TM, e la guardia nelle prime file, e qualche altro spettatore sulle panche nella parte posteriore della sala. Il detective PM li stava aspettando sul palco, al posto dove il giudice era solito sedersi quando deliberava i casi, sotto la grande freccia in su, simbolo della Nazione della Giustizia.
</p><p>"Signore e signori", esord&igrave; il detective PM con una voce bassa e buffa. Voleva creare un ambiente solenne, ma non era bravo a impersonare gli altri, e il tentativo di replicare un processo con la voce maestosa del giudice cre&ograve; piuttosto un'atmosfera ridicola. Il fatto che portava da due giorni gli stessi vestiti rovinati di rosso sbiadito e con macchie di rosa, indossati anche per due notti e un bagno, non contribuiva alla creazione di un clima serio. "Vi ho convocati oggi per spiegare un gran mistero. Elucido. Abbiamo qui presente un criminale che ha confessato di aver commesso un agghiacciante crimine, che deve essere processato, condannato, e punito secondo la nostra giusta legge."
</p><p>"&Egrave; vero!", grid&ograve; angosciosamente il direttore della giustizia.
</p><p>"Sappiamo chi ha commesso il crimine, dove - nel suo ufficio - e quando - nei dieci minuti fra l'uscita dall'ufficio da parte di suo fratello e l'uscita del direttore della giustizia."
</p><p>"Fratello?", esclam&ograve; l'impiegato PM sorpreso. "Quell'uomo era suo fratello?", chiese all'impiegato SM. "Quell'uomo era suo fratello?", ripet&eacute; l'impiegato SM all'impiegato TM. L'impiegato TM controll&ograve; le sue carte, e rispose, "Non lo so, pu&ograve; darsi, ha lasciato solo il suo nome e indirizzo, non la sua parentela." L'impiegato SM spieg&ograve;, "Non lo so&hellip;", ma il detective PM intervenne, "Tutti gli altri hanno sentito, grazie, se l'impiegato PM non ha sentito consiglio di prendere un apparecchio acustico. Ma dopo le mie indagini e grazie al mio intelletto, sono riuscito a risolvere il caso. Purtroppo, ho impiegato pi&ugrave; tempo del solito, ma ho perso due giorni in viaggi alla e dalla capitale della nostra giustissima Nazione. Mi dispiace per il ritardo nella risoluzione. Cio&egrave;, non mi dispiace, non era colpa mia, c'&egrave; una ragione per il ritardo, &egrave; quello che &egrave; successo."
</p><p>"Allora", prosegu&igrave; il detective PM, "il direttore della giustizia afferma di aver fatto qualcosa di terribile. Il vostro errore era pensare che fosse qualcosa che era terribile secondo voi. Piuttosto, come &egrave; comune per incastrare i criminali, come il direttore della giustizia, bisogna entrare nella mentalit&agrave; storta e perversa della malvagit&agrave;, e pensare come pensano loro. Quindi, mi sono chiesto: quale sarebbe, secondo il direttore della giustizia, l'atto peggiore che poteva compiere? In realt&agrave;, non sarebbe un atto, ma un rinnegamento dei propri valori, diventare quello contro cui aveva sempre combattuto. In altre parole, preferire l'ingiustizia alla giustizia. Ti accuso", guardando direttamente alla donna, "di essere un direttore dell'ingiustizia!"
</p><p>Con un sussulto, le persone che ascoltavano reagirono con sorpresa, e poi erano scandalizzate. "Che non sia!", "Impossibile", "Non pu&ograve; essere vero", "Come si permette di parlare cos&igrave;?".
</p><p>"Silenzio!", tuon&ograve; il giudice. "Questo &egrave; sempre il mio tribunale, ed esiguo l'ordine. Detective PM, questa &egrave; un'accusa grave, e se &egrave; falsa creer&agrave; molti guai per lei. Ha le prove di quanto afferma?"
</p><p>"&Egrave; tutto vero, il detective PM ha capito tutto", conferm&ograve; il direttore della giustizia. "Adesso sono Otsuigni, il Direttore dell'Ingiustizia, e sono pronta per le conseguenze."
</p><p>"Anch'io voglio che subisca le conseguenze", aggiunse il detective PM, cercando di aiutare.
</p><p>"Per&ograve; non c'&egrave; ancora nessun crimine per cui pu&ograve; essere processata, figuriamoci condannata", pronunci&ograve; il giudice. "Sa quello che ha provocato questo cambiamento nel Direttore della Giustizia, detective PM?"
</p><p>"Certo. Ha avuto l'inizio con una conversazione con suo fratello quattro giorni fa. Ho parlato con lui ieri sera, e mi ha raccontato tutto. Che aveva serbato rancore verso il direttore dell'ingiustizia, che la odiava per quello che era, per quello che aveva ricevuto che lui invece non aveva ricevuto. &Egrave; andato da lei per dirle che gli dispiaceva e per chiedere scusa, e il direttore dell'ingiustizia ha risposto che era tutto a posto, non era un problema, e si sono riconciliati."
</p><p>Dopo una pausa di qualche secondo, in cui tutti guardarono in silenzio il detective PM con il suo sorriso compiaciuto aspettandosi ulteriori spiegazioni, l'assistente decise di intromettersi. "Tutto questo anch'io lo so, c'ero anch'io quando abbiamo parlato con il fratello. Ma non spiega perch&eacute; il Direttore della Giustizia &egrave; cos&igrave; disperata adesso."
</p><p>"Per me, &egrave; sufficiente, si capisce subito. Ma per voi altri, elucido ulteriormente. Poco dopo che il fratello era uscito, il direttore dell'ingiustizia si &egrave; resa conto di quello che aveva fatto. Il suo affetto per suo fratello le aveva annebbiato la mente, e senza pensarci ha affermato che l'atteggiamento ingiusto del fratello nei suoi confronti non era importante. Cio&egrave;, lo ha&hellip;"
</p><p>"L'ho perdonato!!!", url&ograve; il direttore della giustizia con una voce che quasi rompeva i timpani di tutti. Essendosi tolto questo peso dallo stomaco, si sentiva pi&ugrave; libera di descrivere e confessare. "Ho sempre voluto bene a mio fratello, e quando mi ha parlato dei suoi sentimenti negativi passati, non ho potuto non abbracciarlo e promettergli che gli vorr&ograve; sempre bene. Sono dopo che &egrave; andato via che mi sono resa conto della gravit&agrave; di quello che avevo detto e fatto. Avevo cancellato anni di ingiustizia! Il vero 'io' si &egrave; manifestato quando ho abbassato la guardia. Non la facciata del giustissimo direttore della giustizia, ma Otsuigni che abbraccia l'ingiustizia e fa finta che non importi."
</p><p>"Grazie per la confessione", concluse il detective PM. "Tocca a Lei adesso giudice, per darle la punizione che le spetta."
</p><p>"La ringrazio per tutto il suo lavoro e impegno per chiarire questa situazione strana", replic&ograve; il giudice alzandosi in piedi per prendere controllo dell'incontro. "Per&ograve; in realt&agrave; non so per che cosa condannarla. Perdonare qualcuno non &egrave; un reato nella nostra illustre Nazione. Anch'io sono stato perdonato, e mi ha trasformato la vita."
</p><p>"Anche se non &egrave; contro la legge, ha sentito quello che il direttore dell'ingiustizia ha detto? &Egrave; stata ingiusta! Nella nostra magnifica Nazione, ci&ograve; basta per essere condannato, come anche Lei sa personalmente."
</p><p>"Ma il perdono &egrave; veramente ingiusto?" disse una voce a basso volume, ma con forza e autorit&agrave;, dagli spettatori in fondo alla sala di giudizio. "Non &egrave; piuttosto il giusto atteggiamento?"
</p><p>Tutti si girarono per capire chi osava interrompere un incontro nella sala del giudizio. L'uomo era vestito con un mantello e copricapo scuri, in modo che fosse molto difficile decifrare la sua forma o aspetto. Per&ograve;, la sua provocazione ebbe un effetto immediato: la guardia chiese l'ordine e silenzio nella sala; l'impiegato PM chiese all'impiegato SM di verbalizzare l'intervento per un'eventuale denuncia, che lo chiese all'impiegato TM; il direttore della giustizia era incuriosita e ci fu possibilmente, appena, l'esordio di un sorriso; il giudice sembrava imbarazzato o forse preoccupato per la piega degli eventi; ma la reazione pi&ugrave; grande fu quella del detective PM che, furioso per la sfida alla condanna del direttore della giustizia che l'avrebbe tolta di mezzo, strill&ograve;, "Come ti permetti?! Le persone che assistono ad un processo non possono interferire con il corso della giustizia".
</p><p>"Prima di tutto, questo non &egrave; un processo. Secondo, ho l'autorizzazione del giudice di interferire ogniqualvolta che io ritengo sia utile."
</p><p>La voce dell'estraneo suonava familiare al direttore della giustizia, e ogni parola le impartiva pi&ugrave; fiducia che sapeva chi era. L'ultima affermazione dell'uomo conferm&ograve; i suoi sospetti, e quindi mentre il detective PM girava verso il giudice per esigere una spiegazione, il direttore della giustizia esclam&ograve; con un sorriso raggiante, "Agap! Che bello rivederti! Sei la cosa migliore che mi &egrave; capitato da giorni."
</p><p>"&Egrave; un piacere anche per me, direttore della giustizia, anche se avrei preferito incontrarla in circostanze migliori."
</p><p>"Non sono pi&ugrave; il Direttore della Giustizia, sono semplicemente Otsuigni, come tu sei ora Agap e non pi&ugrave; il Propiziatore."
</p><p>"Un propiziatore?! No, no, e ancora no! Non se ne parli affatto. Allontanate quell'uomo crudele, che distrugge le famiglie per un capriccio personale", schiamazz&ograve; l'assistente.
</p><p>La furia della svolta inaspettata sciocc&ograve; gli altri. Il detective PM, che aveva sentito opinioni negative di propiziatori da parte dell'assistente nel passato, le chiese, "Ma che cosa hai contro i propiziatori?"
</p><p>"Mi dispiace per lo sfogo", si scus&ograve;, "ma i propiziatori hanno fatto male prima, e mi stanno sullo stomaco. &Egrave; colpa loro." Spieg&ograve; in modo incontenibile, con una voce sempre pi&ugrave; alta e una faccia sempre pi&ugrave; rossa, "Sapete, quando ero piccola, la mia famiglia ebbe una contesa con un vicino. Non sono al corrente di tutti i dettagli, ma aveva iniziato un'attivit&agrave; con mio padre, che aveva investito i nostri soldi. Per&ograve; non avevamo mai visto un ritorno per quell'investimento, n&eacute; tanta attivit&agrave;, solo un vicino che aveva cominciato a comprare mobili e vestiti di lusso. Mio padre stava per staccare il rapporto, quando di punto in bianco apparve un propiziatore. 'Tutto bene', disse. 'Non preoccupiamoci di quello che &egrave; successo nel passato. Vogliamo essere tutti amici. Andate avanti cos&igrave;.' Quindi mio padre continu&ograve; il rapporto di amicizia e finanziario, sostenendo quell'attivit&agrave; fittizia, fino a quando il vicino si era appropriato di tutto: soldi, beni, anche la nostra casa divent&ograve; propriet&agrave; del vicino. Siamo rimasti senza niente, e di pi&ugrave;, mia madre non ce la faceva pi&ugrave; e lasci&ograve; mio padre. Da quel momento non mi sono pi&ugrave; fidata di nessuno, tutti sbagliano e meritano il mio sdegno, soprattutto i propiziatori, che mascherano l'ingiustizia perch&eacute;&hellip; perch&eacute;&hellip; in realt&agrave; non so neanche perch&eacute;. E la prima persona che dice, 'Mi dispiace', che non serve un tubo, prender&agrave; un&hellip;", afferr&ograve; il primo oggetto che trov&ograve; nella cartella del detective PM e lo fece vedere minacciosamente, "prender&agrave; uno stivale in testa." 
</p><p>Dopo questo sbotto, il silenzio tuon&ograve; nella sala enorme. Agap, ormai avvicinatosi al gruppo, sussurr&ograve;, "Questa non &egrave; la via dei propiziatori. Forse lui ha sbagliato, forse hai frainteso, forse mille cose. Nessuno pu&ograve; cambiare il passato, ma dobbiamo vivere nel presente e per il futuro."
</p><p>"Avete sentito? Il propiziatore, che fa finta di non esserlo, vuole mascherare l'ingiustizia del collega. Come tutti i propiziatori, pensano solo a loro stessi!", url&ograve; l'assistente.
</p><p>"No, non voglio e non vogliamo mascherare l'ingiustizia. Anzi, un propiziatore si sforza di smascherare l'ingiustizia, affinch&eacute; possa essere affrontata e risolta nel processo della guarigione, piuttosto di essere un peso e un impedimento alla riconciliazione. Quello che &egrave; successo a te e alla tua famiglia &egrave; inaccettabile e intollerabile. Non voglio convincerti diversamente, n&eacute; che l'altro propiziatore abbia fatto bene. Voglio, e credo di poter dire che tutti noi vogliamo, solo che tu stia bene nei tuoi rapporti con tutti."
</p><p>L'assistente medit&ograve; su questo, e sul discorso di Ecilpmes che l'aveva colpita, un uomo semplice con forse pi&ugrave; saggezza del detective PM, nonostante la sua grande conoscenza. Nella sua agitazione, stava per fare un commento pungente al detective PM per ricordarselo, ma si blocc&ograve;. "Perch&eacute;? Perch&eacute; voglio umiliare il Detective PM? Per farmi stare bene perch&eacute; cos&igrave; sembro superiore? Sarebbe comunque solo un sentimento fugace, perch&eacute; non basato sulla realt&agrave;. Dopo dovr&ograve; farlo di nuovo e di nuovo, a tutte le persone a cui voglio bene. E dopo tutto quello, non riavr&ograve; la mia famiglia e il vicino non sar&agrave; punito." Disse invece,
</p><p>"Detective PM, chiedo scusa per tutte le volte che ti ho insultato o ti ho preso in giro. Non era giusto, e non lo voglio fare mai pi&ugrave;. Sei la persona pi&ugrave; in gamba che io conosca, e ti ammiro per quello che fai. Mi puoi perdonare?"
</p><p>Per molti anni, gli studiosi che hanno analizzato questo incontro cruciale nella storia della Nazione della Giustizia hanno dibattuto la questione: chi era pi&ugrave; scioccato da questa affermazione, il detective PM, l'assistente, o uno degli altri presenti. Tanti libri sono stati scritti e tante conferenze svolte senza mai concordare.
<br />- L'assistente si meravigli&ograve; di s&eacute; stessa, non riusciva a credere che potesse dire una cosa del genere, ma tuttavia sent&igrave; un fardello cadere dalla sua anima. Era libera!
<br />- Il detective PM non aveva mai sentito prima di allora parole gentili dall'assistente, che lui voleva licenziare ma non aveva il coraggio. Forse non era cos&igrave; cattiva quanto poteva sembrare.
<br />- Agap fu stupito che qualcuno fosse trasformato cos&igrave; velocemente.
<br />- Il giudice sorrise alla conferma del potere del propiziatore.
<br />- Il direttore della giustizia fu sbalordita che l'assistente fosse riuscita a togliersi di dosso le catene che le legavano. Lo poteva fare anche lei?
<br />- L'impiegato PM chiese all'impiegato SM che chiese all'impiegato TM se avesse scritto tutto, che fortunatamente per i futuri storici aveva fatto.
</p><p>Toccava al detective PM dire qualcosa per rispondere all'assistente, ma era rimasto senza parole. Il giudice, mentre tutti erano distratti dal dialogo fra l'assistente e il propiziatore, aveva ripreso il suo posto che il detective PM aveva occupato in precedenza, e poi cerc&ograve; di riprendere anche la sua autorit&agrave; nel suo tribunale, pronunciando, "Agap ha ragione quando dice di essere autorizzato di intervenire nei processi ogniqualvolta ritiene sia utile. Chiarisco. Dopo il mio processo, quando Agap sacrific&ograve; tutto per me, non aveva pi&ugrave; niente. Cos&igrave; lo cercai e, quando lo trovai, lo invitai a stare con me al tribunale. Gli diedi un rifugio, ed anche vitto e alloggio; in ricompensa, mi aiut&ograve; tanto. Prima di tutto, mi riconcili&ograve; con il mio passato come mercenario della giustizia" - una confessione che produsse diversi sussulti di sorpresa - "e poi mi assistette a esercitare la giustizia in questo paese come Giudice. Non una giustizia basata sulla mera osservanza della legge, ma una giustizia fondata sull'essere giusti l'uno verso l'altro. Perch&eacute; io sono un uomo diverso adesso. Qualcuno che &egrave; stato graziato, come me, non pu&ograve; non essere diverso, deve mostrare la stessa grazia verso gli altri. La presenza di Agap nel paese, pur in pratica invisibile a quasi tutti, &egrave; stato fondamentale per rendere il paese pi&ugrave; giusto. Inoltre, posso dire che &egrave; diventato un amico, qualcuno con cui mi posso confidare, qualcuno che mi pu&ograve; sostenere nei momenti difficili."
</p><p>Il discorso del giudice diede al detective PM il tempo per ravvivarsi. "Basta con queste storie strazianti di tutto quello che abbiamo sofferto nel passato. Dimenticate e superate, dico io! Comunque, siamo qui per condannare e punire il direttore dell'ingiustizia per l'ingiustizia, anzi per alto tradimento contro la nostra Nazione della Giustizia. Lei, pi&ugrave; di tutti i cittadini, doveva sapere meglio!"
</p><p>"Chiedo solo un attimo, detective PM, per parlare nella mia difesa", disse il direttore della giustizia con uno stato d'animo in bilico fra la tristezza e la contentezza, come pure il suo nome e il suo titolo erano in bilico a quel punto. "Agap, puoi ripetere il tuo intervento originale?"
</p><p>"Certamente, signora. Ho messo in dubbio l'affermazione che il perdono &egrave; ingiusto, e ho proposto piuttosto che &egrave; il giusto atteggiamento".
</p><p>"Per&ograve;, quando ho perdonato, ho dato un colpo di spugna all'ingiustizia del mio caro fratello. Era come se lui avesse potuto farla franca, con l'ingiustizia impunita. Cio&egrave;, avevo chiamato bene il male, che per qualcuno nella mia posizione &egrave; peggiore di fare il male. Guai a me!" Riattacc&ograve; con i singhiozzi raccontando quello che aveva fatto e pensato.
</p><p>"Direttore, il Suo sbaglio non era perdonare, ma considerare il perdono in quel modo. Quando perdoniamo, non assolviamo. Non diciamo che l'ingiustizia fatta non era importante, e non diciamo che era giusta. Quando perdoniamo, non assolviamo ma assorbiamo. Non assolviamo l'ingiustizia, assorbiamo l'ingiustizia. Diciamo, 'Tu mi hai fatto male, vivo con quel male, ma ti vorr&ograve; bene lo stesso, non cambier&ograve; il mio atteggiamento verso di te'. Senza rancore, senza vendetta, senza castigo, senza pagamento. Questo &egrave; il modo in cui l'assistente ha perdonato. Far&agrave; male per sempre quello che il vicino (e forse il propiziatore) hanno fatto alla sua famiglia, ma ha deciso di assorbire quel male e vivere come se non fosse successo, pur sapendo che &egrave; successo. Naturalmente, a volte &egrave; possibile che qualcuno altro assorba la nostra ingiustizia invece della persona verso cui abbiamo agito in modo ingiusto, giusto?", rivolgendosi al giudice con un mezzo sorriso.
</p><p>"Decisamente s&igrave;, grazie caro amico."
</p><p>"Posso anche spiegare in un altro modo. 'Perdonare' a qualcuno &egrave; 'per donare' a quella persona. Perdonare &egrave; per donare. Quando faccio un dono ad un amico, chi paga? Pago io, ma l'amico riceve il bene. Anche se anch'io ricevo qualcosa, diventando una persona migliore donando. Cos&igrave; quando perdono: io pago, l'altro riceve il bene dell'ingiustizia perdonata, ma io sto meglio come persona."
</p><p>"Posso capire tutto questo, ma perch&eacute; dici che perdonare &egrave; il giusto atteggiamento?", il direttore continu&ograve; a indagare. "Se non punire l'ingiustizia &egrave; giusto, che cos'&egrave; la giustizia?"
</p><p>"Sicuramente, secondo la legge, il perdono &egrave; ingiusto. Vedete sopra la testa del giudice, sul muro c'&egrave; il simbolo della giustizia nella nostra Nazione: una freccia che va diritto in su senza deviare n&eacute; a sinistra n&eacute; a destra. La legge funziona cos&igrave;, &egrave; uguale per tutti: se si &egrave; ingiusti, si paga, senza eccezioni. Per&ograve;, anche Lei sa che non &egrave; tutto qui. Come ha detto nella Sua ultima visita a questo paese, oltre alla giustizia legale, osservando le leggi, bisogna essere giusti, con i giusti rapporti con gli altri. E il giusto rapporto con Suo fratello era di mantenere l'amicizia, anzi impegnarsi di pi&ugrave; a parlare con lui, aiutarlo, &hellip; Insomma, essere una sorella e non solo il Direttore della Giustizia. Certo, se si vuole bene ad una persona, si deve anche aiutarla a non fare cose ingiuste, spiegando i suoi sbagli e correggendola. Altrimenti sarebbe davvero mascherare l'ingiustizia."
</p><p>"Questo vuol dire che devo perdonare tutti? Che nessuno va mai punito per la propria ingiustizia?"
</p><p>"No. Fra altro, io non posso perdonare (cio&egrave; assorbire) l'ingiustizia fatta agli altri. Se una persona fa male ad un altro, io devo difendere con tutti i miei sforzi quello che ha subito l'ingiustizia, e fare s&igrave; che non succeda pi&ugrave;. Per questo esistono i tribunali come questo. Devo essere giusto anche in questo modo. In altre parole, devo praticare la giustizia e amare la misericordia. Allora, cosa pensa: di che cosa sar&agrave; Lei il Direttore, della Giustizia o dell'Ingiustizia?"
</p><p>Tutti si fermarono per ascoltare la risposta, su cui dipendeva il destino non solo di molti degli individui presenti, ma anche dell'intera Nazione. Il direttore aveva molti pensieri contrastanti. Cosa sarebbe meglio per s&eacute; stessa? Ma pensare cos&igrave; sarebbe ingiusto. Piuttosto, cosa sarebbe meglio per la Nazione? Quale decisione promuoverebbe maggiormente la giustizia della Nazione? Quando smise di pensare prima di tutto a s&eacute; stessa, come se fosse il centro della Nazione attorno a cui ruotava tutto - era vero che fosse la persona pi&ugrave; importante della Nazione, ma non doveva pensare cos&igrave; - la decisione divent&ograve; molto pi&ugrave; facile.
</p><p>Pronunci&ograve; maestosamente e ufficialmente, "La mia sentenza &egrave; che io non sar&ograve; pi&ugrave; il Direttore della Giustizia."
</p><p>Il detective PM applaud&igrave;, poi smorz&ograve; l'allegria quando tutti lo guardarono con disapprovazione.
</p><p>"Rimarr&ograve; invece nel Dipartimento della Giustizia come Vicedirettore della Giustizia." Il detective PM non riusc&igrave; a nascondere la sua semi-delusione. "Il mio primo atto come Vicedirettore della Giustizia &egrave; di nominare Agap Iurtla all'ufficio di Propiziatore della Giustizia. O forse Direttore della Propiziazione. Non lo so, possiamo lavorare sul nome dopo. Agap Iurtla, accetta questo ufficio che Le &egrave; stato conferito?"
</p><p>"Sarebbe un onore, Vicedirettore della Giustizia."
</p><p>"Un onore che ha meritato, Direttore-Propiziatore, e sar&agrave; un onore per tutti noi essere guidati da Lei. Non c'&egrave; nessuno come Lei nella Nazione, che capisce e promuove la giustizia di tutti noi."
</p><p>&nbsp;
</p><p>Mentre il giudice, gli impiegati, e la guardia si congratularono con il Propiziatore-Direttore e diedero il bentornato alla Vicedirettore, il detective PM usc&igrave; di nascosto, seguito dall'assistente. "Il nostro lavoro qui &egrave; finito", afferm&ograve; il detective, girando la testa per un attimo per parlare con l'assistente.
</p><p>"Davvero? Non hai ancora risposto alla mia domanda. Mi puoi perdonare per tutte le cose ingiuste che ti ho detto?"
</p><p>Ecco, la domanda che il detective PM voleva che non fosse posta. Aveva scoperto tanto tempo fa che il modo migliore per evitare una cosa non voluta era di decidere che non esisteva.
</p><p>"Detective PM, mi senti?"
</p><p>Ma era una domanda che non voleva andare via. Il detective PM continu&ograve; a meditare, "Perdono? Posso perdonare? Voglio perdonare? Non lo so&hellip; Non fa parte del mio carattere, ma forse c'era qualcosa in quello che ha detto il propiziatore. Siccome &egrave; riuscito a cambiare l'ex-direttore, non poteva essere del tutto ingiusto! Ma io sono pi&ugrave; intelligente del propiziatore, come pu&ograve; aver ragione e io no? E perdonare vuol dire esporsi, aprirsi all'altro, che non ho mai fatto."
</p><p>Quello che il detective PM riusc&igrave; a dire era, "Sei una brava persona con tante buone qualit&agrave;, leale, sempre utile e un gran aiuto per le mie indagini. Ma a volte, tante volte, mi hai fatto rimanere male con le tue battute. Mi piacerebbe ricominciare da capo, provare un rapporto nuovo e magari migliore. Per&ograve;, non riesco proprio a perdonare, forse fra un po' quando il tuo bene avr&agrave; sopraffatto il male che mi hai fatto. Ma per il momento, non riesco a pronunciare quelle parole. Comunque, mi dispiace per tutto."
</p><p>Non poteva guardare l'assistente negli occhi mentre lo diceva, ma dopo aver finito si gir&ograve; verso di lei di nuovo, giusto in tempo per vedere uno stivale volare verso di lui.
</p>
<h2>Note su "Direttore della Giustizia"</h2>
<p>Oltre alla giustizia, questo racconto considera anche i temi della scusa, del perdono, e del ravvedimento. Tante volte nel racconto, i personaggi sono dispiaciuti per un'azione, oppure si scusano. Per&ograve;, non sempre sono scuse vere. Infatti, quando diciamo che ci scusiamo, spesso non &egrave; una scusa vera, perch&eacute; &egrave; davvero difficile ammettere di aver sbagliato e che la colpa &egrave; solo nostra. Alcune delle scappatoie che usiamo per chiedere scusa senza ammettere la nostra colpevolezza sono:
</p><p><i>Quello che ho fatto non era in realt&agrave; sbagliato:</i>
</p><ul><li>Razionalizzazione (inventare delle ragioni per cui l'ho fatto)
</li><li>Sono fatto cos&igrave;, &egrave; la mia natura
</li><li>I miei genitori mi hanno cresciuto cos&igrave;; la societ&agrave; mi ha reso cos&igrave;
</li><li>Non fa male a nessuno
</li><li>Tutti lo fanno
</li><li>&Egrave; divertente
</li><li>&Egrave; il mio diritto
</li><li>Quelli con il potere (Dio, la nazione, il datore di lavoro, il professore) creano delle regole per reprimere la mia libert&agrave; e mantenere il proprio potere
</ul><p><i>Quello che ho fatto era sbagliato ma non era grave:</i>
</p><ul><li>Aggiungere, "ma tu hai fatto&hellip;"
</li><li>Tanto sar&ograve; perdonato
</li><li>Faccio tante altre cose giuste
</li></ul>
<p>La maggior parte di queste scappatoie &egrave; menzionata da qualcuno nel racconto.
</p><p>La mia linea guida &egrave; che se "mi dispiace" o "scusami" sono seguiti dalle parole "ma" o "per&ograve;", non &egrave; un vero dispiacere o una vera scusa.
</p><p>&nbsp;
</p><p>"Benvenuta Direttore della Giustizia al nostro paese umile e giusto." C'&egrave; una differenza sottile con la formula di benvenuto che il giudice ha fatto al propiziatore, che riflette parzialmente i cambiamenti nel modo di pensare del giudice fra i due racconti.
</p><p>&nbsp;
</p><p>Il caso dei gemelli monozigoti &egrave; abbastanza semplice: un gemello commette un reato, mentre l'altro si fa vedere cospicuamente in giro, in modo da creare un alibi. Chi non sa che ci siano due gemelli crede che chi ha commesso il resto sia innocente perch&eacute; ha un alibi. Gli altri due casi non esistono, sono menzionati solo per creare un po' di stranezza.
</p><p>&nbsp;
</p><p>La guardia parla in modo sgrammaticale. Non sono errori dell'autore, ma indica un pi&ugrave; basso livello di educazione in confronto con gli altri personaggi.
</p><p>&nbsp;
</p><p>La "pi-shirt" era in realt&agrave; una mia idea, con alcuni amici, molti anni fa. Naturalmente l'idea &egrave; rimasta sulla carta, non le abbiamo mai create e sicuramente non le abbiamo mai indossate!
</p><p>&nbsp;
</p><p>&Egrave; impossibile codificare la giustizia, perch&eacute; la vita &egrave; troppo complicata per avere una regola per ogni possibile situazione. Le&nbsp;613 leggi dell'Antico Testamento non erano sufficienti, neanche le molto di pi&ugrave; leggi del codice italiano. Se qualcuno vuole fare il male in modo legale, di solito trova un modo, che induce alla creazione di ancora altre leggi. Questo &egrave; uno dei motivi per cui la giustizia non pu&ograve; essere solo l'osservanza di certe regole, come viene detto diverse volte in questi racconti.
</p><p>&nbsp;
</p><p>Ci abituiamo troppo velocemente alla bellezza e alla magnificenza - di certi luoghi naturali, di un fiore, del coniuge, addirittura di Dio. A volte ci vuole lo sguardo di qualcuno che guarda per la prima volta per aiutarci ad apprezzare quello che abbiamo iniziato a dare per scontato. In ogni caso, dobbiamo imparare a meravigliarci della grandezza e della bellezza del nostro Dio ogni giorno, senza abituarci mai! Vivere con questa bellezza pu&ograve; trasformarci la vita, come ha fatto (temporaneamente) al detective PM.
</p><p>&nbsp;
</p><p>"Erano persone giuste che non dovevano temere la giustizia" - Romani 13:3-4.
</p><p>&nbsp;
</p><p>"Ho tirato i dati della vita" - un modo di dire nella Nazione della Giustizia, che sta per la fortuna o la sfortuna che una persona ha avuto nella sua vita.
</p><p>&nbsp;
</p><p>"Aveva sentito opinioni negative da parte dell'assistente nel passato" - per esempio nel racconto Detective PM, quando stavano per andare dal campo al circo.
</p><p>&nbsp;
</p><p>"Chiedo scusa per tutte le volte che ti ho insultato o ti ho preso in giro. Non era giusto, e non lo voglio fare mai pi&ugrave;". Il vero ravvedimento, come questo, consiste in due cose: ammettere di avere sbagliato chiedendo scusa, e fare un'inversione di marcia decidendo di non volerlo pi&ugrave; fare. Certo, sbaglieremo ancora e cadremo negli stessi peccati, ma invece di chiedere scusa e poi rifarlo volentieri alla prossima opportunit&agrave;, dobbiamo non desiderare di fare quello che abbiamo capito di essere ingiusto.
</p><p>&nbsp;
</p><p>"Qualcuno che &egrave; stato graziato, come me, non pu&ograve; non essere diverso, deve mostrare la stessa grazia agli altri." Per il contrario di questa affermazione (se non mostriamo grazia, non abbiamo ricevuto la grazia), leggi Matteo 6:12-15; 18:21-35.
</p><p>&nbsp;
</p><p>La presenza di Agap nel paese &egrave; simile a (ma non uguale a) la presenza di Ges&ugrave; nella chiesa adesso, fra la sua morte e la sua seconda venuta quando sar&agrave; di nuovo visibile. &Egrave; una presenza invisibile ma reale, mentre aiuta e sostiene chi lo segue. Nei racconti, Agap &egrave; stato presente fra il suo sacrificio e scomparsa (nel primo racconto) e la sua esaltazione (alla fine di questo racconto); nella realt&agrave;, Ges&ugrave; &egrave; presente fra la sua esaltazione (l'ascensione, poco dopo la sua morte sacrificale e risurrezione) e il suo ritorno.
</p><p>&nbsp;
</p><p>"Avevo chiamato bene il male&hellip; Guai a me!" Un'allusione a Isaia 5:20, anche se il versetto non parla del perdono, ma di quelli che invertono i valori di Dio perch&eacute; credono che Dio non far&agrave; niente contro la loro iniquit&agrave;.
</p><p>&nbsp;
</p><p>"Decisamente s&igrave;, grazie caro amico." Il mio primo impulso era di scrivere a questo punto, "Grazie a Dio", ma naturalmente non potevo in questo racconto. Per&ograve;, la nostra reazione quando ci ricordiamo che Ges&ugrave; ha assorbito la nostra ingiustizia e la nostra punizione deve essere il ringraziamento e la lode a Dio.
</p><p>&nbsp;
</p><p>"Fra altro, io non posso perdonare (cio&egrave; assorbire) l'ingiustizia fatta agli altri." Per esempio, Ges&ugrave; spiega in Matteo 5:38-48 quello che dobbiamo fare quando qualcuno ci fa male, non quando qualcuno fa male ad un'altra persona.
</p><p>&nbsp;
</p><p>"Praticare la giustizia e amare la misericordia." Michea 6:8 - il resto del versetto contiene altre istruzioni importanti per la nostra vita che non potevo includere in questo racconto.
</p><p>&nbsp;
</p><p>"Aveva scoperto tanto tempo fa che il modo migliore per evitare una cosa non voluta era di decidere che non esisteva." Una citazione dall'inizio del racconto Detective PM. Un'epistemologia postmoderna estrema - se non esiste per me, non esiste affatto, e lo posso ignorare.
</p><p>&nbsp;
</p><p>Ci sono persone come il detective PM che, davanti alla grazia, si induriscono. Non vogliono accettare che hanno bisogno del perdono e/o non vogliono perdonare. Non vogliono che la loro bravura non conti davanti a Dio. Per&ograve; c'&egrave; ancora speranza anche per loro, come per tutti. Chiss&agrave; se nel futuro anche il detective PM imparer&agrave; la vera giustizia?
</p>
<?
require("../piede.php");
?>
