<?
$descriz = "Mercenario della Giustizia: uno deiRacconti della Giustizia";
$key = "mercenario della giustizia, racconti della giustizia";
$titolo = "Mercenario della Giustizia";
$sezione = "Strumenti";
$sezioneurl = "/racconti_giustizia/";
require("../capo.php");
?>
<h1>Mercenario della Giustizia</h1>

<p>Aprile. Quanto odiava quel mese ipocrita. Dopo la pioggia recente e con l'arrivo del sole che gioiosamente illuminava e riscaldava tutto dopo il lungo inverno, i fiori erano spuntati ed emettevano un piacevole profumo, l'erba era di colore verde acceso, gli uccelli cantavano, e le api ronzavano diffondendo la vita. Anche la gente che passava gli salutava con un sorriso, sempre di buon umore, come se la vita dura dei mesi precedenti non fosse esistita. L'uomo, invece, era il contrario. Dentro era nero. Di aspetto, era robusto e muscoloso, e la faccia emanava determinazione, tenacia, e durezza. Mostr&ograve; queste caratteristiche nel suo lavoro di riportare la giustizia, anche con la forza. Con quel compito non c'entravano i fronzoli della primavera. L'uomo sapeva che questa vitalit&agrave; era tutta una messa in scena. Fra pochi mesi, il sole cocente avrebbe bruciato tutto, e tutto si sarebbe seccato, poi tutto il colore sarebbe caduto dagli alberi, e infine tutto e tutti sarebbero diventati freddi come lo era lui. Sapeva anche che, nonostante il suo impegno e il suo lavoro, le persone sarebbero rimaste ingiuste, nonostante i momenti di speranza primaverili.
</p><p>&nbsp;
</p><p>Mentre si avvicinava alla prossima citt&agrave;, non salut&ograve; nessuno. Sperava di trovare qualche lavoro l&igrave;, perch&eacute; da alcune settimane nessuno l'aveva ingaggiato mentre girava di citt&agrave; in citt&agrave;, e i soldi cominciavano a scarseggiare. Dopo essere entrato nel paese, si ferm&ograve; nella piazza principale, che aveva delle panchine intorno ad una fontana decorata da una statua di una freccia rivolta in su. Bevette un po', ma us&ograve; l'acqua soprattutto per togliere la sporcizia dei segni della nuova vita primaverile che si era attaccata alla faccia e alle mani durante il viaggio. Sentendosi purificato, si sedette per riposarsi e osservare i passanti.
</p><p>Vide alcuni che vennero per prendere l'acqua, come lui; altri che correvano con grande fretta da una parte della piazza all'altra, come se il destino del mondo dipendesse dal loro tempestivo arrivo; alcuni bambini giocavano insieme in un angolo della piazza, con un bambino vistosamente escluso dal gioco. Nessuno di questi interessava all'uomo. Alcuni salutavano amici e conoscenti in cui imbattevano mentre passavano per la piazza. L'uomo cerc&ograve; di origliare qualche conversazione per captare delle informazioni utili. Per&ograve; erano tutte conversazioni banali di persone superficiali che si salutavano e dicevano niente in mille parole. Avendo sprecato un'ora della sua vita, l'uomo decise di alzarsi per cercare una sistemazione per la notte, ma dopo qualche passo sent&igrave; due signori chiacchierare.
</p><p>"Hai sentito quello che &egrave; successo al tribunale oggi? Hanno condannato Alleb e dato ragione ad Atturb."
</p><p>"No, che vergogna! Sono sempre i benestanti che vincono. Hanno il potere e hanno i soldi, cos&igrave; i giudici pensano che abbiano anche la giustizia."
</p><p>"S&igrave;, mi dispiace soprattutto per Alleb. Tutto quello che ha sofferto, e adesso anche questo."
</p><p>Incuriosito, l'uomo pens&ograve; che fosse opportuno cogliere il momento. "Scusatemi, non sono di qua. Chi sono Atturb e Alleb?"
</p><p>Il primo signore spieg&ograve;, "Alleb vive qui vicino, nella seconda strada a sinistra laggi&ugrave;", indicando una via che scendeva dalla piazza. "Possiede poco, ma aveva una bellissima collana."
</p><p>"Atturb invece", prosegu&igrave; il secondo signore, "vive in questo magnifico palazzo che puoi vedere dall'altra parte della piazza. Anzi, abita in una parte del palazzo, tutto il resto &egrave; occupato dai suoi servi e dipendenti. Non le manca niente. Possiede un'infinit&agrave; di gioielli. Per&ograve; voleva proprio quella di Alleb. Forse per invidia, non poteva accettare che una povera avesse una migliore di lei, oppure per avarizia perch&eacute; voleva tutto. Non lo so. Ma so che ha mandato degli uomini per prendere la colonna con la forza."
</p><p>"Li ho pure visti arrivare da Alleb", conferm&ograve; il compagno.
</p><p>"Non sono riusciti a prendere la colonna, non posso immaginare la pressione e le minacce, anche fisiche, che Alleb ha sicuramente dovuto subire. Per&ograve; &egrave; forte e ha resistito, quindi Atturb le ha fatto causa. Nessun giudice deciderebbe contro Atturb, &egrave; troppo importante e potente. Probabilmente il giudice ha anche ricevuto un bel regalo di ringraziamento. Non c'&egrave; la giustizia."
</p><p>"Vi ringrazio per la spiegazione", chiuse l'uomo. "Veramente &egrave; un'ingiustizia."
</p><p>&nbsp;
</p><p>Quando i due signori si erano allontanati, l'uomo cambi&ograve; direzione a scese per la via indicata e prese la seconda strada a sinistra. Era un vicolo cieco corto, in cui le case sui due lati sembravano di inclinarsi l'una verso l'altra, creando un'atmosfera scura e cupa. Una banda di giovani sussurrava in fondo alla strada, come se complottassero insieme, e chiaramente non volevano essere disturbati. Siccome non c'erano altre persone a cui chiedere informazioni, l'uomo non aveva scelta e grid&ograve;, "Alleb, sei qui?"
</p><p>Ripet&eacute; la chiamata alcuni secondi pi&ugrave; tardi, il che gli procur&ograve; degli sguardi minacciosi dai giovani. Dopo il terzo grido, i giovani iniziarono ad avvicinarglisi, ma una finestra apr&igrave;, e una luce splend&eacute; nelle tenebre - in parte la luce da dentro la casa, ma maggiormente da una faccia che sembrava risplendere. Una voce dolcissima allegger&igrave; il clima pesante, "Sono io Alleb, come posso essere d'aiuto?"
</p><p>Quando i giovani videro e sentirono Alleb, si inchinarono con rispetto e ritornarono in fondo al vicolo. L'uomo invece rispose, "Sono invece io che voglio aiutare te, Alleb, ma non voglio espormi qui pubblicamente. Possiamo conversare in modo pi&ugrave; discreto?"
</p><p>"Certo, entra dentro", replic&ograve; la voce gentile.
</p><p>La faccia spar&igrave; e riapparse alla porta che apr&igrave;, e la stessa voce accogliente lo invit&ograve;, "Prego, vieni".
</p><p>L'uomo entr&ograve; con gioia - la simpatia di Alleb rendeva piacevole l'idea di trascorrere del tempo con lei. Quando era in casa, e vedeva non solo la faccia di Alleb ma tutto il suo corpo, desiderava ancora di pi&ugrave; stare con lei. Aveva una ventina di anni, qualche anno di meno di lui. Lo splendore del viso, lui osserv&ograve;, faceva parte di un corpo brillante, che sembrava illuminare tutta la stanza con la sua presenza. Era vestita in modo semplice, come ci si aspetterebbe dalla casa semplice, ma elegante, che dava un tocco di classe all'ambiente. I capelli biondi arrivavano alle spalle. L'allegria del suo sorriso catturava tutti e li contagiava con la stessa felicit&agrave;. Quando l'uomo guard&ograve; nei suoi occhi grandi e azzurri, vide una porta verso la simpatia e tenerezza che capiva risiedevano in lei.
</p><p>L'uomo si riprese e esord&igrave; con una piccola tosse. "Prima di tutto, lascia che mi presenti e che io spieghi il motivo per cui ti ho cercata. Sono un mercenario della giustizia&hellip;"
</p><p>"Mercenario della giustizia? Che cosa &egrave;?", interruppe Alleb.
</p><p>"Sono persone che si battono per la giustizia. Riconoscono che non si ottiene la giustizia sempre nei modi tradizionali, come i tribunali e la mediazione, e impongono la giustizia dove regna ancora l'ingiustizia. Come forse nel tuo caso. Ho sentito che Atturb ti ha rubato una collana, e non avevi modo per difenderti. Neanche il tribunale ti voleva concedere la giustizia. Io invece potrei renderti la giustizia che ti spetta."
</p><p>Gli occhi si illuminarono ancora di pi&ugrave; per la speranza che le era stata offerta, che la rendeva sempre pi&ugrave; attraente al mercenario della giustizia. Con uno sguardo di completa innocenza, incontaminata dall'ingiustizia della societ&agrave; che le circondava e che, purtroppo, si approfittava della sua semplicit&agrave;, Alleb rispose sorpresa, "Lo faresti per me? Ma io non lo merito, non sono nessuno. Come pu&ograve; uno come te farmi questo grande favore? E poi, se sei un mercenario, vuol dire che dovr&ograve; anche pagarti per il tuo aiuto? Come vedi, io non ho niente, la nostra famiglia &egrave; povera, e l'unica cosa di valore che avevamo ci &egrave; stata sottratta da Atturb."
</p><p>"S&igrave;, lo farei per te, cio&egrave; per la giustizia, perch&eacute; combatto sempre quando c'&egrave; l'ingiustizia, lotto per gli oppressi. Inoltre, anche se di solito vengo pagato per i miei servizi come mercenario, non &egrave; necessario, e posso aiutarti gratuitamente. Per&ograve;, ci sarebbe una cosa&hellip;". Il mercenario esitava, forse non era giusto chiedere in questa situazione, ma dall'altra parte aveva veramente bisogno. "Non vorrei importunare ma&hellip; Senti, stavo per cercare un alloggio quando ho sentito del tuo caso, e sono venuto immediatamente da te. Adesso fa tardi&hellip; Se non &egrave; un disturbo&hellip; mi servirebbe un posto per dormire stanotte&hellip;"
</p><p>"Sembri un uomo perbene e onesto, ma mi dispiace, purtroppo nella nostra piccola casa siamo gi&agrave; stretti."
</p><p>"Capisco, non dovevo neanche chiedere."
</p><p>"Certo che dovevi chiedere! Invece mio zio abita da solo in una casa grande, proprio qua di fronte a me, e senza dubbio ti vorr&agrave; ospitare quando avr&ograve; spiegato la situazione. Aspetta qui e gli vado a parlare."
</p><p>Quando Alleb usc&igrave;, era come se qualcuno avesse abbassato le luci. Al mercenario la casa sembrava pi&ugrave; tenebrosa senza di lei. Faceva pure pi&ugrave; freddo, e per la prima volta sent&igrave; il pessimo odore entrare dalla strada. Colse l'opportunit&agrave; di guardare meglio intorno. La casa, pur essendo vecchia e malridotta, conteneva dei bei mobili, con alcuni oggetti raffinati che decoravano la stanza. Ovviamente, pens&ograve; il mercenario della giustizia, anche se &egrave; povera, Alleb era una persona per bene e graziosa, che creava la bellezza dovunque andasse. 
</p><p>Le sue riflessioni furono arrestate dal ritorno di Alleb. "Tutto bene", annunci&ograve; con un sorriso genuino. Sembrava di essere felice quanto il mercenario della giustizia dell'esito della sua richiesta. "Mio zio sar&agrave; contentissimo di aver un po' di compagnia stasera, e anche dopo se vuoi. Prendi le tue cose e vieni con me, e te lo presenter&ograve;." Mentre faceva strada verso la casa dello zio, la mano di Alleb sfior&ograve; il braccio del mercenario della giustizia, che percep&igrave; una sensazione nuova e piacevole, un calore non soltanto sulla pelle ma anche interiormente, che inizi&ograve; a sciogliere la freddezza che sentiva.
</p><p>&nbsp;
</p><p>Lo zio aveva una casa pi&ugrave; grande e bella, anche se il contenuto della casa era pi&ugrave; povero. C'era una stanza libera, e il mercenario della giustizia ci port&ograve; tutto il suo bagaglio. Alleb lo salut&ograve; per la notte, e sugger&igrave; di trovarsi la mattina prima che il mercenario della giustizia andasse da Atturb, una proposta che gli piacque molto. Dopo il lungo viaggio di quel giorno, il mercenario della giustizia era stanco, ed anche lui si ritir&ograve; nella sua camera per la notte.
</p><p>Per&ograve;, nonostante la stanchezza, non riusc&igrave; a dormire quella notte. Non riusciva a togliersi dalla mente Alleb. La faccia e il sorriso che gioiosamente illuminavano tutto, il tocco che riscaldava l'inverno del suo spirito, il piacevole profumo&hellip; "Che cosa vuol dire? Che cosa &egrave; successo?", si interrog&ograve;. Solo dopo diverse ore soccombette al sonno intenso, e sogn&ograve; di lei e di loro insieme.
</p><p>&nbsp;
</p><p>Il mercenario della giustizia si svegli&ograve; molto pi&ugrave; tardi del solito, e lo zio lo salut&ograve; e gli offr&igrave; una colazione abbondante. "Alleb ti sta aspettando a casa sua", rifer&igrave; al mercenario della giustizia, "ma non c'&egrave; fretta, mangia con calma". Mentre mangiava, consider&ograve; i suoi piani per il giorno. Non doveva essere difficile, sarebbe andato da Atturb per insistere che facesse la cosa giusta, e se necessario, con intimidazioni, minacce, o la forza. Poi avrebbe riportato la collana ad Alleb, che sarebbe stata molto riconoscente. E poi loro avrebbero&hellip; Basta, che cosa pensava? Poi avrebbe finito il suo ingaggio, e ne avrebbe cercato un altro, no? Perch&eacute; pensava di loro insieme anche dopo aver finito il suo compito? Intanto, avrebbe trascorrere un po' di tempo con Alleb quella mattina per&hellip; per&hellip; Non si ricordava perch&eacute;. Non gli servivano altre informazioni o aiuto. "Tanto male non fa", si giustific&ograve; con un sorriso. Forse aiuterebbe anche a distrarlo dallo strano mal di pancia che aveva iniziato a sperimentare, con tanta agitazione come se ci fossero dei piccoli animali che ballavano dentro lo stomaco.
</p><p>&nbsp;
</p><p>Quando il mercenario della giustizia buss&ograve; alla casa di Alleb, lo invit&ograve; a fare una passeggiata con lei, per vedere il paese e passare il tempo prima che Atturb lo potesse vedere. Il mercenario della giustizia era contento di scoprire il paese, che non aveva mai visitato prima, soprattutto con una guida locale come Alleb. Passeggiarono per il mercato, la scuola, i negozi principali, chiacchierando delle loro esperienze passate e degli interessi. Il mercenario della giustizia scopr&igrave; che ogni cosa che menzionava fu entusiasticamente condivisa da Alleb, che rendeva pi&ugrave; facile e gradevole conversare con lei. Arrivarono al tribunale, che come sempre era posto sul punto pi&ugrave; alto del paese. Il viso di Alleb mut&ograve;, da sorridente e luminoso a imbronciato e cupo. "L&igrave; &egrave; dove sono stata imbrogliata", osserv&ograve; sinteticamente. Il suo malumore era contagioso, e anche il mercenario della giustizia sent&igrave; un disprezzo per quell'istituzione della giustizia che non recava la giustizia. "Andiamo via da questo luogo velenoso", sugger&igrave; Alleb, "c'&egrave; un bel parco qui vicino che ci far&agrave; stare meglio".
</p><p>Raggiunsero il parco, dove si sedettero su una panchina con una bellissima vista panoramica del paese sottostante e il verde lussureggiante della campagna intorno. I profumi dei fiori recentemente sbocciati, il suono gentile degli uccelli che volavano giocosamente fra gli alberi, e la tranquillit&agrave; del posto, lontano dalle attivit&agrave; del paese, confortarono e tranquillizzarono il mercenario della giustizia. Vedeva tutto in modo diverso. La primavera non era ipocrita, ma era la vera vita, una festa della natura per la bont&agrave; della creazione. Inoltre, lui stesso si sentiva diverso, spensierato, senza il peso dell'obbligo che si era imposto di far valere la giustizia. Anzi, non era spensierato; pensava piuttosto di altre cose. In quel momento, la giustizia non era dominante nella sua mente, c'erano la bellezza di quel posto che accarezzava tutti i suoi sensi e la sensazione piacevole di poter riposare. E naturalmente c'era anche Alleb, che rendeva il quadro perfetto. In quel momento, Alleb prese la mano del mercenario della giustizia nella sua e la strinse. Tutti i sentimenti dimenticati, trascurati, e repressi del mercenario della giustizia, risvegliatisi da quando aveva conosciuto Alleb e che dopo avevano bollito sotto la superficie, esplosero in quel momento in un'estasi di gioia per averla vicina a lui. Si sentiva un uomo diverso dal cupo duro che era di solito. Il mercenario della giustizia si gir&ograve; sulla panchina, abbracci&ograve; Alleb e la baci&ograve;. Subito sent&igrave; la risposta delle mani di Alleb che esploravano la sua schiena e i suoi capelli, le labbra che accoglievano le sue, i piedi che strofinavano le sue gambe. Il mercenario della giustizia non capiva quello che gli era successo, ma gli piaceva quello che sperimentava. Per&ograve;, mentre si lasciava trasportare dal piacere, un piccolo prurito rimaneva in fondo alla sua mente, che gli diceva di riflettere ulteriormente. Non riusc&igrave; a grattare quel prurito, che crebbe nel suo cervello fino a sopraffare il sovraccarico di sentimenti che rifiutavano ogni ragionamento.
</p><p>Il mercenario della giustizia si allontan&ograve; leggermente da Alleb, e mormor&ograve; dispiaciuto, "Non &egrave; giusto, mi dispiace, non dovevo farti questo."
</p><p>"Perch&eacute; lo dici? Io voglio, credo che anche tu lo voglia. Che cosa pu&ograve; essere pi&ugrave; giusto di fare quello che vogliamo?", sussurr&ograve; Alleb seducentemente nell'orecchio del mercenario della giustizia, mentre con il dito gli strofinava gentilmente il braccio.
</p><p>"S&igrave;, lo voglio, mi piace", rispose tremolante e si avvicin&ograve; di nuovo a quel dolce viso e poi si ritir&ograve;. "Ma io sono qui per renderti giustizia, non per gratificare i miei desideri. Non &egrave; giusto", balbett&ograve; incertamente, cercando di convincere s&eacute; stesso pi&ugrave; che Alleb.
</p><p>"Mi vuoi veramente fare giustizia? Faresti di tutto per il mio bene? Sacrificheresti tutto per me?"
</p><p>"Da quando ti ho vista ieri sera, ho pensato solo a te. S&igrave;, voglio fare tutto per te, e non per me. Per questo non riesco&hellip;"
</p><p>"Ti chiedo quindi di rinunciare alle idee rigide della giustizia, e fare per me quello che io vorrei. Cos&igrave; farai la cosa giusta per me, e tu avrai quello che tu vuoi. Non puoi dire di no."
</p><p>"S&igrave;&hellip; cio&egrave; no&hellip; Non &egrave; cos&igrave; semplice. Che cos'&egrave; la giustizia? Non lo so, sono confuso. Forse &egrave; meglio se torniamo a casa tua, e poi andr&ograve; da Atturb per completare il mio incarico."
</p><p>"Sono solo un lavoro per te? Non sono pi&ugrave; di quello?", singhiozz&ograve; Alleb mentre una lacrima scendeva sulla sua guancia. Si alz&ograve; e inizi&ograve; a camminare. Il mercenario della giustizia corse per raggiungerla e prov&ograve; a prendere la sua mano con la sua, ma Alleb ritir&ograve; la sua. Proseguirono in silenzio. Era molto diverso dalla gioiosa chiacchierata di poco tempo fa, e il mercenario della giustizia si chiedeva quale rapporto veramente volesse, quale fosse il rapporto giusto.
</p><p>&nbsp;
</p><p>Quando arrivarono alla casa di Alleb, lei afferm&ograve; con freddezza, "Vai da Atturb adesso."
</p><p>"Mi serve solo la mia arma", rispose il mercenario della giustizia e fece qualche passo per seguire Alleb a casa sua, ma lei lo blocc&ograve;. "&Egrave; da mio zio, vai a prenderla." Poi come un ripensamento, aggiunse, "Mi dispiace, sei un uomo buono e giusto." Gli diede un bacino sulla guancia, che lo prese alla sprovvista, ma prima che potesse reagire Alleb entr&ograve; in casa sua e chiuse la porta. Il mercenario della giustizia sospir&ograve;. Non c'era altro da fare che affrontare Atturb, forse cos&igrave; avrebbe potuto rivedere Alleb con una buona notizia. Buss&ograve; dallo zio, che gli apr&igrave; la porta senza invitarlo dentro. Quando il mercenario della giustizia gli chiese la sua arma, lo zio entr&ograve; dentro casa e la riport&ograve; al mercenario della giustizia, sbattendo la porta in faccia. "Perch&eacute; &egrave; cos&igrave; sgarbato adesso? Non ha ancora potuto parlare con Alleb." Scacci&ograve; quei pensieri dalla sua testa, perch&eacute; con la sua arma in mano, si sentiva un uomo diverso. Dava un senso di potere, di poter avere quello che voleva, e cos&igrave; aumentava la fiducia in s&eacute;. In realt&agrave;, aveva dovuto usare l'arma raramente. Di solito far vedere l'arma o minacciare di usarla erano abbastanza per persuadere gli altri di fare quello che il mercenario della giustizia insisteva era la cosa giusta da fare. Mise l'arma sotto i vestiti - l'effetto sorpresa di tirarla fuori era sempre molto efficace - e incammin&ograve; verso la casa di Atturb.
</p><p>&nbsp;
</p><p>Il mercenario della giustizia ritorn&ograve; alla piazza dove si era fermato quando era arrivato in paese. Il contrasto del palazzo di Atturb con la piccola casa di Alleb non poteva essere pi&ugrave; evidente. L'edificio occupava tre lati della spaziosa piazza, e il giardino con le fontane creava un'atmosfera pacifica. Consisteva di tre piani, e le bandiere colorate che sventolavano sopra il tetto sembravano giocare insieme. Il mercenario della giustizia non sapeva cosa fare - non poteva semplicemente gridare il nome come aveva fatto davanti alla casa di Alleb. Cos&igrave; dopo alcuni minuti di indecisione, si avvicin&ograve; alla porta centrale del lato dell'edificio in mezzo. Prima che bussasse, la porta fu aperta, e un uomo distinto gli chiese educatamente, "Buona sera signore, desidera?"
</p><p>Il mercenario, ancora incerto di come doveva comportarsi, si fece coraggio e, utilizzando la sua voce pi&ugrave; formale, rispose, "Vorrei parlare con la signora Atturb".
</p><p>"Certamente signore, se vuole accomodarsi nel salotto, mi informer&ograve; se &egrave; presente."
</p><p>Nonostante i divani, poltrone, e altri mobili di lusso nel salotto, il mercenario della giustizia rimase in piedi, per non essere in svantaggio di altezza quando sarebbe entrata Atturb. Bisognava dominare fisicamente per poter anche dominare comandando di eseguire la giustizia. Mentre si preparava per l'incontro, l'uomo riapparse e annunci&ograve;, "La signora Atturb la vedr&agrave; adesso", invitando il mercenario della giustizia a proseguire nella stanza successiva. Il mercenario cammin&ograve; a grandi passi attraverso la porta, che l'uomo, seguendolo, chiuse dietro di loro.
</p><p>"Buona sera, io sono Atturb, come posso essere d'aiuto a Lei?", inizi&ograve; la donna seduta dietro un'imponente scrivania. Alla vista di Atturb, il mercenario della giustizia si blocc&ograve;. Non aveva mai visto una persona cos&igrave; mal ridotta nella sua vita - anche quelli che lui personalmente aveva mal ridotto combattendo. La faccia era macchiata da nevi di vari colori, anche se era difficile vederli chiaramente a causa delle rughe che attraversavano il viso. Un nevo in particolare si avvicinava all'occhio sinistro, che come risultato rimaneva mezzo chiuso. La bocca era storta, e dalla parte pi&ugrave; larga si vedevano alcuni denti che mancavano e altri che crescevano diagonalmente. Il naso asimmetrico terminava non con una verruca, ma due. Il mercenario della giustizia la consider&ograve; ripugnante, ma seppell&igrave; i suoi sentimenti per poter sembrare pi&ugrave; forte.
</p><p>"Io sono un mercenario della giustizia, e sono qui per costringerla a agire giustamente." Prese la sua arma da dove era nascosta sotto i suoi vestiti e cominci&ograve; a maneggiarla minacciosamente davanti ad Atturb. Per&ograve;, prima che potesse incutere paura, l'uomo si avvicin&ograve; silenziosamente da dietro e abilmente sottrasse l'arma dal mercenario della giustizia.
</p><p>"Grazie maestro di palazzo, la faccia consegnare al giudice. Le chiedo scuso", disse rivolgendosi di nuovo al mercenario della giustizia, "ma non &egrave; permesso portare queste armi nel nostro paese. Quando lascer&agrave; il paese, potr&agrave; rivolgersi al giudice che le riconsegner&agrave; l'arma."
</p><p>"Lo stesso giudice con cui si &egrave; messa in combutta, che ha corrotto per ottenere l'ingiustizia? Fate tutto per sfruttare la gente per il proprio bene."
</p><p>"Sono accuse pesanti", rispose Atturb ancora placata ma leggermente perplessa. "Mi pu&ograve; gentilmente spiegare quale ingiustizia avrei fatto? Vediamo se possiamo risolvere l'equivoco."
</p><p>"Non c'&egrave; nessun equivoco. Sono venuto per riprendere una collana che ha ingiustamente rubato dal legittimo proprietario."
</p><p>Per la prima volta, la calma di Atturb fu disturbata, non da uno scatto di ira come il mercenario della giustizia si aspettava, ma da quello che pareva la tristezza.
</p><p>"O Alleb, Alleb, ma perch&eacute; cos&igrave;?", sussurr&ograve; Atturb a s&eacute; stessa, guardando gi&ugrave; per terra invece di guardare il mercenario della giustizia che le stava davanti. Alz&ograve; la testa di nuovo e spieg&ograve;, "Le cose non stanno come le hanno detto. In realt&agrave;, quella collana &egrave; la mia, e Alleb me l'ha rubata un giorno al mercato. Fra i suoi multipli talenti, &egrave; anche una borseggiatrice abile. Di solito non mi sarei preoccupata molto, non &egrave; una delle pi&ugrave; costose che possiedo, ma quella collana era la preferita di mia madre e me l'ha data poco prima di morire. Il suo valore sentimentale &egrave; inestimabile per me. Cos&igrave; ho mandato alcuni uomini per supplicare Alleb di restituirmi la collana. Ero disposta anche di pagarla per la collana o di darle una migliore pur di riavere la collana di mia madre, ma lei ha rifiutato, insistendo che era la sua collana per non dover ammettere di aver rubato la mia. La mia ultima possibilit&agrave; era di portarla in tribunale, e il giudice naturalmente mi ha dato ragione. Anche se" - qui la sua spiegazione divent&ograve; pi&ugrave; emozionale - "non so ancora se vedr&ograve; mai pi&ugrave; la mia collana. Se non ha risposto alla ricompensa che le ho offerto, risponder&agrave; all'ordine del giudice?"
</p><p>"Una bella favola. Perch&eacute; dovrei crederla? Quello che Alleb mi ha detto sembrava molto pi&ugrave; verosimile."
</p><p>"Ah, s&igrave;, Alleb pu&ograve; essere molto&hellip; persuasiva e convincente quando vuole. E vuole quando &egrave; al suo vantaggio. Lasci che le racconto una storia." Atturb si alz&ograve; lentamente dalla sua sedia dietro l'enorme scrivania, prese un bastone, e zoppic&ograve; verso una delle poltrone sparse nella stanza. "Non mi piace questa formalit&agrave;. Possiamo darci del tu adesso? Voglio raccontare qualcosa di personale di me e di Alleb. Siediti qui davanti a me."
</p><p>Quando Atturb era in piedi - anche se "in piedi" era un modo molto generoso per descrivere il suo stato, perch&eacute; era esageratamente bassa e piegata in avanti, e cos&igrave; la sua altezza in piedi era simile a quella quando era seduta - il mercenario della giustizia cap&igrave; che la ripugnanza della sua faccia era estesa a tutto il suo corpo. Aveva una gamba pi&ugrave; corta dell'altra, le dita rigide a causa, presumibilmente, dell'artrite, e un gobbo sulla spalla destra. Il mercenario della giustizia si sedette, cercando di resistere di mostrare qualsiasi reazione a quello che vedeva. Probabilmente non riusc&igrave;, perch&eacute; Atturb gli chiese, "Mi trovi orribile, giusto?", con un sorriso che la imbruttiva ulteriormente.
</p><p>"No, no, certo di no, solo che io&hellip; voglio dire&hellip;" In realt&agrave; non sapeva quello che voleva dire, la confusione aumentava e perdeva la fiducia in s&eacute; che era necessaria per un mercenario della giustizia svolgere il suo compito.
</p><p>"Non ti preoccupare, so che per quanto riguardo l'aspetto i dadi della vita mi hanno tirato dei pessimi numeri - addirittura negativi se fosse possibile. Sono nata cos&igrave;, e le mie malattie durante l'infanzia sicuramente non hanno aiutato. Dall'altra parte, non mi &egrave; andato male per quanto riguardo il resto della vita, non solo quello che vedi qui intorno", indicando vagamente tutta la casa, "ma anche in altri modi. Per&ograve;, parliamo prima di Alleb. Ti ha detto per caso che eravamo compagne a scuola?"
</p><p>Il mercenario era sbalordito da questa affermazione, e prima di pensare bene a quello che stava per dire, lo neg&ograve;, "Non pu&ograve; essere giusto, hai pi&ugrave; di 40 anni!"
</p><p>Atturb fece un altro sorriso brutto, anche se cercava di alleggerire la discussione. "Non si parla dell'et&agrave; delle donne! Ma s&igrave;, sembro leggermente pi&ugrave; vecchia di quanto sono in realt&agrave;. Colpa di queste malattie&hellip; Forse puoi immaginare il tormento che ho ricevuto a scuola. O forse no, mi sembri il tipo da tormentatore piuttosto di tormentato."
</p><p>Il mercenario della giustizia arross&igrave;, perch&eacute; era vero. Siccome Atturb aveva parlato quasi tutto il tempo dell'incontro e si &egrave; aperta svelando i suoi difetti, il mercenario della giustizia pens&ograve; che dovesse anche parlare un po' di s&eacute;. Anche perch&eacute;, con l'atteggiamento amichevole e accogliente di Atturb, gli veniva facile chiacchierare. Si apr&igrave; e sciolse un po' della sua durezza, pi&ugrave; di quanto aveva fatto da anni. "Ammetto, anch'io prendevo in giro quelli che erano diversi, mentre io ero uno dei forti. Mi vergogno di come ero, perch&eacute; non era giusto, non &egrave; quello che vorrei essere adesso."
</p><p>"Abbiamo tutti scheletri nell'armadio di cui ci vergogniamo. Ci&ograve; non ci giustifica, ma dobbiamo essere realistici a proposito delle nostre mancanze, delle nostre ingiustizie. Io, per esempio, per cercare una briciola di autostima, deridevo gli altri perch&eacute; erano poveri. Mentre la mia famiglia era ricca e potente. Che vergogna, non era neanche merito mio se ero ricca, ma nonostante ci&ograve; pensavo di essere migliore per quel motivo."
</p><p>"Nei miei viaggi come mercenario della giustizia, ho spesso visto persone cos&igrave;, che pensavano di essere superiori (anche per i motivi pi&ugrave; banali) e cos&igrave; giustificate a fare quello che vogliono agli altri. Per&ograve;, per dire la verit&agrave;, quando pensavo cos&igrave;, a volte mi veniva il dubbio che in realt&agrave; io non ero diverso da loro: io pensavo di essere superiore a quelli che si ritenevano superiori agli altri. Questa mia presunta superiorit&agrave; mi giustificava di far valere la giustizia su loro. Ma il mio atteggiamento non era forse uguale a quello degli altri? Ho deciso che era meglio non pensarci, perch&eacute; non sapevo risolvere il problema, e non volevo mettere in dubbio la mia vocazione. Ma se fosse tutto basata su un'ipocrisia&hellip;?" 
</p><p>"Non devi sopprimere i tuoi dubbi, forse &egrave; la coscienza che ti sta richiamando ad una giustizia migliore. Ma dove sono finite le mie buone maniere?! Maestro, ci porti per favore del t&egrave;?"
</p><p>"Subito", e senza un suono usc&igrave; dalla stanza.
</p><p>"Non serve pi&ugrave; la tua guardia del corpo?", chiese incuriosito il mercenario della giustizia.
</p><p>"Non credo. Hai ancora l'intenzione di farmi male?"
</p><p>"No, no, mi dispiace per quello che ho fatto prima." Come gli era venuto in mente di minacciare una donna cos&igrave; gentile e graziosa e indifesa&hellip; e forse anche giusta?
</p><p>"Non fa niente, diciamo che era un fraintendimento e dimentichiamo tutto. Comunque, ritorniamo a me e Alleb. Tutti noi siamo dotati in alcuni modi, e mancanti in altri. Io non ho un aspetto attraente, ma dall'altra parte sono nata nella famiglia pi&ugrave; ricca del paese. Alleb &egrave; il contrario: &egrave; bellissima e simpatica" e aggiunse ironicamente e giocosamente fra parentesi, "(forse l'hai notato)", poi prosegu&igrave;, "ma era di una famiglia indigente. Malgrado queste differenze, saremmo potute essere amiche. Per&ograve;, c'era un'altra differenza, e c'&egrave; tutt'ora, che decretava che non ci saremmo mai trovate bene insieme."
</p><p>"Qual &egrave; questa differenza?"
</p><p>Il quel momento il maestro del palazzo rientr&ograve; con il rinfresco. Atturb chiacchier&ograve; affabilmente con lui e con il mercenario della giustizia per preparare e offrire il cibo, mantenendo alta la tensione sulla domanda lasciata appesa nell'aria. Quando il mercenario della giustizia non poteva pi&ugrave; resistere, interruppe, "La differenza? Era l'intelligenza, i passatempi, gli interessi?"
</p><p>"Lo scopo della nostra vita. Abbiamo tutte e due diverse qualit&agrave; positive, ma per che cosa le volevamo usare, e per cosa le usiamo? Quante volte abbiamo parlato della giustizia insieme, ma sempre con opinioni divergenti. Per Alleb, la cosa giusta da fare era quello che era giusta per lei, che era per il suo vantaggio. Ed era molto abile a utilizzare le sue doti per manipolare le persone a fare quello che voleva."
</p><p>Il mercenario della giustizia riflett&eacute; sulla sua discussione con Alleb sulla giustizia, e si &egrave; reso conto che anche lui era stato manipolato per fare quello che lei voleva. "Confesso che anch'io forse sono stato stregato da lei. Per&ograve;, quando ha cercato di convincermi, anzi sedurmi, di fare quello che non volevo, ho capito che c'era qualcosa che non andava, che non era giusto."
</p><p>"Se hai resistito al suo fascino, mi complimento con te. Ci sono pochi che ci riescono. Vuol dire che il tuo impegno per la giustizia &egrave; molto forte, che pu&ograve; superare i propri piaceri. Lo ammiro in un uomo."
</p><p>In quel momento gli sguardi si incrociarono, e il mercenario della giustizia vide il riflesso di s&eacute; stesso negli occhi di Atturb. Poi chiese, "Invece, come hai usato la tua ricchezza?"
</p><p>"Per me, la cosa giusta da fare &egrave; quella che &egrave; giusto per gli altri, non per me stessa. &Egrave; vero che io abbia pi&ugrave; mezzi finanziari per farlo che altri, ma tutti hanno la possibilit&agrave; di servire gli altri con quello che hanno se vogliono, anche Alleb. Naturalmente, quando ero piccola, compagna di Alleb, non avevo grandi possibilit&agrave;, ma da qualche anno, da quando sono morti i miei genitori e ho ereditato tutto questo, ho deciso di usarlo non per me stessa ma per altri. &Egrave; giusto cos&igrave;."
</p><p>Il mercenario della giustizia si meravigli&ograve; del discorso di Atturb. Era come pensava lui, ma non era mai riuscito a esprimere il suo pensiero in modo cos&igrave; semplice. Lui pure ha sempre voluto aiutare altri a ottenere la giustizia, costi quello che costi, anche se i suoi metodi erano diversi, secondo le sue possibilit&agrave; diverse.
</p><p>Atturb prosegu&igrave;, ignara delle riflessioni del mercenario della giustizia. "Con queste visioni della vita diametralmente opposte, naturalmente non andavamo d'accordo spesso. Quando eravamo insieme, io cercavo di usare le nostre capacit&agrave; per dare qualche beneficio agli altri, mentre Alleb cercava di approfittarsi degli altri per trarne qualche beneficio per s&eacute; stessa, con un piccolo sorriso o un tocco leggero. E alla fine ci separavamo per fare cose diverse."
</p><p>L'accenno al sorriso e al tocco di Alleb fece rabbrividire momentaneamente il mercenario della giustizia, e il pensiero di Alleb e il ricordo del piacere che sentiva lo dominarono nuovamente. Lei era ancora il suo cliente, il mercenario della giustizia razionalizz&ograve;, e la doveva difendere. Forse era Atturb che lo manipolava con i suoi bei discorsi, piuttosto di Alleb con il suo bellissimo viso e corpo. C'era una parte della spiegazione di Atturb che era inverosimile, e forse la smentiva.
</p><p>"Hai detto di aver mandato alcuni uomini per supplicare Alleb di restituirti la collana, pagandola. Eppure, affermi di usare la tua ricchezza per la giustizia. Come pu&ograve; essere giusto ricompensare un ladro per la sua ingiustizia? Qualcosa non mi quadra."
</p><p>"Capisco la tua perplessit&agrave;. Era una scelta che mi tormentava. Io voglio cercare il bene delle persone, costi quello che costi&hellip; a me. Se so che qualcuno ha rubato da un'altra persona, o comunque le ha fatto male, non posso aiutare quello che ha fatto male e trascurare quello che ha subito il torto. Devo fare bene all'oppresso, questo &egrave; la giustizia sociale. Per&ograve;, se sono io che subisco il torto, io posso scegliere di portare e assorbire quel torto per il bene dell'altro. Quindi, invece di strapparle la collana con la forza o farla andare in prigione, le ho supplicato e poi ho chiesto al giudice solo di decidere di chi era.
</p><p>"Ma se vuoi bene ad Alleb, non &egrave; giusto incoraggiarla a rubare, dandole un premio che vale pi&ugrave; di quello che ha rubato! Cos&igrave; continuer&agrave; con la sua ingiustizia."
</p><p>"Infatti, era quello il mio tormento", rispose Atturb con la testa e la voce leggermente abbassate, forse dalla vergogna. "Che cosa era meglio per Alleb? Ho preso la decisione ingiusta? Ma forse niente che potevo fare l'avrebbe veramente aiutata. Non lo so, sono ancora perplessa per la scelta. &Egrave; possibile che a volte non ci sia nessuna scelta giusta? Comunque, sospetto di aver fatto la scelta sbagliata, ma non volevo creare dei guai per una persona con cui ho condiviso la mia giovent&ugrave;. A volte le emozioni hanno il sopravvento sulla ragione quando dobbiamo decidere quello che &egrave; giusto da fare. Non sei d'accordo, mercenario della giustizia?"
</p><p>Con l'ultima domanda, la testa e la voce di Atturb ripresero la loro posizione normale, e il tentativo del sorriso ritorn&ograve;, anche se sembrava pi&ugrave; un sorriso ironico che gioioso. L'accenno alle emozioni fece ricordare di nuovo al mercenario della giustizia quello che era successo con Alleb. &Egrave; stato accecato dalla sua bellezza e simpatia in modo di agire ingiustamente? Aveva rischiato di commettere un'ingiustizia, e cos&igrave; di doversi punire? Come l'avrebbe fatto? Poi, si rese conto, improvvisamente e sorprendentemente, che aveva anche iniziato a sperimentare gli stessi sentimenti con Atturb che aveva sperimentato con Alleb. Gli piaceva stare con lei. I discorsi sulla giustizia gli facevano bene: pensavano spesso nello stesso modo, che era raro con le persone con cui parlava di solito, e quando non erano d'accordo, capiva che probabilmente lei aveva ragione. Voleva continuare a chiacchierare con Atturb per ore, si sentiva un uomo diverso, capace di esprimere le sue idee, con un rinnovato desiderio per la giustizia e non soltanto per essere pagato per farla valere. Atturb sarebbe un grande aiuto per lui combattere per la giustizia, e lui&hellip; E lui&hellip; Poteva aiutare Atturb nel suo impegno per la giustizia? Forse non cos&igrave; come era in quel momento il mercenario della giustizia, ma stava cos&igrave; bene con lei che era anche disposto a cambiare, a rinunciare al suo lavoro da mercenario della giustizia, se cos&igrave; poteva assisterla a portare la giustizia nel paese.
</p><p>Il mercenario della giustizia si espose, "Mi piace parlare con te della giustizia, magari potremo approfondire ulteriormente prossimamente&hellip;" Lasci&ograve; la frase e il pensiero sospesi in aria, sperando che Atturb li avrebbe afferrati.
</p><p>"&hellip;e pur a me &egrave; stato un piacere, e vorrei proseguire la discussione nel futuro", afferr&ograve; Atturb. "Trovo poche persone a cui posso parlare della giustizia, molti vogliono solo agire senza riflettere. Potremo anche, oltre a chiacchierare, anche magari collaborare insieme&hellip;", lasciando pure lei il pensiero sospeso.
</p><p>"Sarebbe senz'altro un'ottima idea", rispose il mercenario della giustizia entusiasticamente. Subito dopo aver pronunciato queste parole, riflett&eacute; che forse era sembrato troppo entusiasta per la situazione in cui si trovava. Raccolse i suoi pensieri e sentimenti, si mise composto, e disse in modo formale, "Per&ograve; prima dovr&ograve; sistemare questa faccenda con Alleb. Sentir&ograve; quello che avr&agrave; da dire, e far&ograve; valere la giustizia a tutte e due."
</p><p>"Se riuscirai a stabilire un rapporto giusto fra noi, mi farai un gran favore. Arrivederci e a dopo, poco dopo spero."
</p><p>&nbsp;
</p><p>Il maestro di palazzo accompagn&ograve; il mercenario della giustizia alla porta, da cui si mise in cammino per la casa di Alleb, lasciato solo con i suoi pensieri e le sue emozioni. Quando pens&ograve; ad Alleb, subito fu inondato dalla gioia perch&eacute; l'avrebbe rivista presto. Per&ograve;, se non era giusta? Gli sarebbe piaciuta ancora? Ma forse aveva dei dubbi solo perch&eacute; aveva appena parlato con Atturb, magari in realt&agrave; Alleb era giusta. Poi, avendo pensato di nuovo ad Atturb, un'altra onda di gioia lo travolse. Che bello era parlare con lei! Forse Atturb era giusta. Ma come potevano i sentimenti mutarsi in base a cui pensava? Come poteva il suo senso della giustizia dipende dall'ultima persona con cui ha parlato? "Sono cos&igrave; inaffidabile?", riflett&eacute; il mercenario della giustizia perplesso e confuso.
</p><p>Con questi pensieri, arriv&ograve; al vicolo buio di Alleb. Sembrava ancora pi&ugrave; cupo e ostile della sera precedente. I giovani sussurravano ancora in fondo al vicolo, e lo guardavano minacciosamente. La casa di Alleb era completamente chiusa, e non usciva neanche un sottile raggio di luce. Il mercenario della giustizia buss&ograve; alla porta, ma nessuno rispose. La mancanza di una risposta aument&ograve; la sua confusione. Non aveva promesso di trovarsi a casa? Il mercenario della giustizia non vedeva l'ora di fissare gli occhi di nuovo sulla sua dolce bellezza, ma se lei non volesse vedere lui&hellip;? Grid&ograve;, "Alleb, sei qui?" come aveva fatto la sera precedente, ma il silenzio tuon&ograve; nel vuoto, sia del vicolo sia del suo cuore. Pass&ograve; dall'altra parte della strada, buss&ograve; e grid&ograve; allo zio, ma nuovamente gli rimase tutto chiuso. Non era pi&ugrave; voluto da quelle parti. Intanto, i giovani si erano avvicinati.
</p><p>"Oi, tu, cosa vuoi? Questo &egrave; il nostro territorio."
</p><p>"Vorrei parlare con Alleb."
</p><p>"Certo, tutti vogliono parlare con Alleb. Ma non puoi. Lei non ti vuole. Vattene."
</p><p>"Ma mi ha promesso che ci saremmo rivisti&hellip;"
</p><p>Uno dei giovani prese un coltello, "Hai sentito quello che abbiamo detto? Vattene."
</p><p>Per istinto, il mercenario della giustizia prov&ograve; a prendere la sua arma, ma poi si rese conto di non averla pi&ugrave;. "Dovrei solo prendere le mie cose dallo zio di Alleb, poi vado."
</p><p>"Sei proprio sordo! Siccome non ti serve l'orecchio, te lo tolgo." Il giovane salt&ograve; in avanti brandendo il coltello. Il mercenario della giustizia era comunque addestrato, e i suoi riflessi lo fecero schivare il colpo, in modo che il coltello non recidesse l'orecchio ma solo gli tagliasse la faccia. Anche gli altri giovani lo attaccarono, ma il mercenario della giustizia reag&igrave; con i pugni. Era pi&ugrave; bravo a combattere che i giovani e riusc&igrave; a evitare la maggior parte dei colpi, ma erano troppi e con coltelli, e lui prese alcune ferite e cicatrici sulla faccia e sulle braccia. Poi scapp&ograve; a gambe levate, seguito dalle grida e dagli urli di vittoria da parte dei giovani.
</p><p>&nbsp;
</p><p>Il mercenario della giustizia girovag&ograve; nelle strade del paese tutta la notte. Non aveva pi&ugrave; niente. Avrebbe potuto riprendere la sua arma, ma non gli interessava pi&ugrave;. Non aveva neanche Alleb, e si vergognava di ritornare da Atturb dopo quello che aveva fatto. Non solo non aveva nessun possesso n&eacute; nessuna persona, ma neanche nessun lavoro e nessuna giustizia. Tutto quello su cui aveva costruito la sua vita, e la sua imposizione della giustizia dove c'era l'ingiustizia, era una bugia e una fregatura. Lui era ingiusto, e le sue idee erano dettate dai suoi sentimenti e non da quello che era giusto. Era troppo coinvolto per riuscire a capire quello che era giusto, e sicuramente per farla valere. Non poteva presentarsi da Atturb, che era sempre stata giusta, con tutta la sua ingiustizia. Si sentiva sporco. Magari ci fosse dell'acqua per togliere la sua sporcizia, la sua ingiustizia, e cos&igrave; purificarlo!
</p><p>Che cosa poteva fare come ingiusto per portare la giustizia? Chi capiva veramente la giustizia? Si ricord&ograve; in quel momento il giudice del paese, che aveva decretato una sentenza giusta, anche quando molti (come anche il mercenario della giustizia) pensavano che fosse ingiusta. Il giudice non doveva decidere quello che era giusto, c'era gi&agrave; la legge che lo decideva per lui. Le emozioni e i sentimenti non confondevano un giudice, doveva solo cercare i fatti e far valere un codice esterno al giudice. Questo s&igrave; era il lavoro per lui! Non era pi&ugrave; un mercenario della giustizia, ma sarebbe diventato un giudice.
</p><p>&nbsp;
</p><p>Quando i primi raggi del sole segnalarono l'alba e l'inizio di un nuovo giorno, l'uomo con i pensieri chiariti e la confusione riordinata dichiar&ograve;, "Oggi comincio una nuova vita. Ero ingiusto, da ora in poi sar&ograve; giusto". Si sentiva un uomo nuovo, rifiorito, e si allontan&ograve; dal paese risolutamente.
</p>
<h2>Note su "Mercenario della Giustizia"</h2>
<p>Il tema di questo racconto, oltre alla giustizia, &egrave; l'amore, anche se questa parola non &egrave; mai usata nel racconto. Il motivo &egrave; che la parola "amore" ha tanti significati al giorno d'oggi, ma sono spesso lontani dal significato del termine nella Bibbia. Il racconto esplora diversi tipi di "amore", per esempio il colpo di fulmine, un'infatuazione o una cotta, che non dura se non si trasforma in un altro rapporto pi&ugrave; profondo. Poi c'&egrave; l'innamoramento, che spesso dura diversi anni, ma anche esso di solito si esaurisce prima o poi. L'amore nella Bibbia va oltre il romanticismo, anche se non lo esclude. L'amore inizia con l'amore di Dio per noi, mostrato soprattutto nella morte di Ges&ugrave; per noi, e come conseguenza anche noi dobbiamo amare gli altri nello stesso modo (1Giovanni 4:10-11). Questo amore &egrave; un impegno per il bene dell'altro, pi&ugrave; del proprio bene; &egrave; essere disposti a dare tutto per l'altro. Solo questo amore non verr&agrave; mai meno (1Corinzi 13:8), mentre l'infatuazione e l'innamoramento cesseranno.
</p><p>Noi dobbiamo amare Dio e gli altri con tutto quello che abbiamo (Luca 10:27; 1Giovanni 4:21). Dio nella sua infinita grandezza pu&ograve; amare tutti cos&igrave;; noi invece non possiamo sacrificare tutto per tutti, non abbiamo abbastanza tempo n&eacute; soldi n&eacute; altre cose da dare. Per&ograve;, chi &egrave; sposato ha un rapporto speciale in cui pu&ograve; mostrare questo amore profondo, dando s&eacute; stesso per il coniuge per il perfezionamento dell'altro (Efesini 5:25-33). 
</p><p>&nbsp;
</p><p>Una delle mie poesie preferite &egrave; <i>The Waste Land</i> (in italiano, <i>La terra desolata</i>) di T. S. Eliot. Inizia cos&igrave;:<br />
April is the cruellest month, breeding<br />
Lilacs out of the dead land<br />
cio&egrave;<br />
Aprile &egrave; il mese pi&ugrave; crudele, allevando<br />
Lill&agrave; dalla terra morta<br />
La poesia fu pubblicata nel 1922, poco dopo la prima guerra mondiale, con pensiero modernista e pessimista. Secondo Eliot, la primavera sembrava di portare nuova vita, ma in realt&agrave; l'umanit&agrave; era in crisi, se non gi&agrave; morta. Cambi&ograve; idea, ed anche il messaggio e i temi delle sue poesie, dopo la sua conversione al cristianesimo cinque anni pi&ugrave; tardi. Il mercenario della giustizia trovava aprile similmente ipocrita e ingannevole, anche se, come Eliot, ha cambiato idea durante il racconto. Anzi, lui viene cambiato quando sperimenta il rinnovo della primavera nella propria vita.
</p><p>&nbsp;
</p><p>Il racconto dei due signore della collana somiglia a quello di Natan in 2Samuele 12:1-12, anche se alla fine questo racconto &egrave; molto diverso.
</p><p>&nbsp;
</p><p>La descrizione come una luce che splende nelle tenebre &egrave; un'allusione a Giovanni 1:5 (anche Genesi 1:4-5; Salmo 112:4; 2Corinzi 4:6), ma anche qui &egrave; un confronto ingannevole. Anche Satana si traveste da angelo di luce (2Corinzi 11:14).
</p><p>&nbsp;
</p><p>Nella scena nel parco, Alleb afferma ironicamente la definizione giusta dell'amore - fare tutto per il bene dell'amato, sacrificare tutto per l'altro. Per&ograve;, la perversit&agrave; umana pu&ograve; abusare un tale amore perfetto, approfittandosi per manipolare chi ama per fini ingiusti, come fa Alleb. Un tale atteggiamento &egrave; pi&ugrave; comune, purtroppo, fra gli uomini, anche i mariti, che fanno male (fisicamente e/o psicologicamente) alle donne che li amano, dominandole e schiacciandole ingiustamente. Un segno di un tale rapporto di abuso &egrave; frasi di ricatto emotivo come, "se mi amassi veramente, tu faresti&hellip;" o "se fossi una brava moglie, tu faresti&hellip;".
</p><p>&nbsp;
</p><p>"I dadi della vita mi hanno tirato dei pessimi numeri" - un modo di dire nella Nazione della Giustizia, che sta per la fortuna o la sfortuna che una persona ha avuto nella sua vita.
</p><p>&nbsp;
</p><p>La confessione dal mercenario della giustizia che dubitava della sua vocazione, perch&eacute; pensava di essere superiore, come pensavano quelli che giudicava, viene da una storia che ho sentito di un predicatore che parlava della parabola del fariseo e del pubblicano in Luca 18:9-14. Dopo aver spiegato perch&eacute; il pubblicano &egrave; stato giustificato ma non il fariseo (perch&eacute; il fariseo era persuaso di essere giusto e disprezza il pubblicano), il predicatore concluse con la preghiera, "O Dio, ti ringraziamo che noi non siamo come il fariseo", citando inavvertitamente Luca 18:11 e rendendosi come il fariseo. Quando chiudiamo la porta al nostro orgoglio, trova sempre una finestra per rientrare nella nostra vita.
</p><p>&nbsp;
</p><p>Le difficolt&agrave; di Atturb di essere amica di Alleb vengono da 2Corinzi 6:14-7:1. &Egrave; difficile accompagnare qualcuno nella vita se volete andare in direzioni diverse o con mezzi diversi. Questo &egrave; vero dell'amicizia, del lavoro, e soprattutto del matrimonio. Cos&igrave; il mercenario della giustizia si chiedeva se potesse stare con Alleb o Atturb - l'infatuazione non &egrave; una base solida su cui costruire una vita insieme. Naturalmente, bisogna amare (nel senso biblico) tutti, anche quelli con cui non andiamo d'accordo. Per&ograve; per costruire una vita insieme, ci vuole di pi&ugrave;.
</p><p>&nbsp;
</p><p>Il tormento di Atturb riguardo alla cosa giusta da fare ad Alleb &egrave; una riflessione su Matteo 5:38-48. Non dobbiamo amare solo i nostri amici, ma anche i nemici. Se Dio ci ha amati cos&igrave; tanto mentre eravamo i suoi nemici che Ges&ugrave; &egrave; morto per noi (Romani 5:6-10), come possiamo noi fare diversamente? &Egrave; difficile amare i nemici, &egrave; altrettanto difficile capire quale sia il modo migliore per amarli. Dare loro quello che vogliono subendo il torto, oppure agendo affinch&eacute; il nemico facesse quello che &egrave; giusto? Bisogna riflettere su ogni singolo caso. Quello che &egrave; chiaro &egrave; che non dobbiamo mai rendere male per male (Romani 12:17), solo l'amore per il male. In ogni caso, Ges&ugrave; si riferiva alle ingiustizie fatte a noi. Come ha affermato Atturb, dobbiamo sempre contrastare l'ingiustizia fatta agli altri.
</p><p>&nbsp;
</p><p>Questo racconto &egrave; un prequel al racconto <i>Propiziatore</i>; cio&egrave;, racconta quello che &egrave; successo prima di <i>Propiziatore</i> e spiega alcuni dei suoi avvenimenti. Anche se non &egrave; detto in modo esplicito, il mercenario della giustizia &egrave; riuscito a diventare un giudice, proprio quello di <i>Propiziatore</i> e i racconti successivi. Infatti, la descrizione dell'uomo nel primo paragrafo di questo racconto &egrave; uguale a come il propiziatore lo descrive quando lo incontra (tranne le ferite e cicatrici, che riceve alla fine di questo racconto). Un filo rosso che unisce i racconti &egrave; il desiderio del mercenario della giustizia / giudice di creare la giustizia. Quello che &egrave; diverso &egrave; che pensa di crearla in diversi modi. Vuole imporre la giustizia con la forza in <i>Mercenario della Giustizia</i>, poi vuole fare osservare la legge in <i>Propiziatore</i>, in cui impara l'importanza di rapporti giusti, che pian piano mette in pratica nella sua vita negli anni che seguono, soprattutto nel racconto <i>Direttore della Giustizia</i>. Anche se questo racconto viene prima cronologicamente, non volevo che fosse il primo racconto letto perch&eacute; il mercenario della giustizia / giudice passa da un'idea sbagliata ad un'idea parzialmente corretta della giustizia, e non volevo che sembrasse la risposta finale, il che sarebbe potuto succedere se fosse il primo racconto della serie.
</p><p>&nbsp;
</p><p>"Lui era ingiusto, e le sue idee erano dettate dai suoi sentimenti e non da quello che era giusto. Era troppo coinvolto per riuscire a capire quello che era giusto, e sicuramente per farla valere." Queste riflessioni sulla giustizia da parte del mercenario della giustizia sono manifestate in, per esempio, il suo ultimo discorso (come giudice) alla fine di <i>Detective PM</i>.
</p><p>&nbsp;
</p><p>"Non poteva presentarsi da Atturb, che era sempre stata giusta, con tutta la sua ingiustizia. Si sentiva sporco. Magari ci fosse dell'acqua per togliere la sua sporcizia, la sua ingiustizia, e cos&igrave; purificarlo!" Questo &egrave; il problema fondamentale di ognuno di noi: come possiamo noi ingiusti presentarci davanti al Dio giusto, puro, e santo? La risposta &egrave; che Ges&ugrave; Cristo ci lava dall'ingiustizia e ci purifica. Non cancella la nostra ingiustizia, ma lo trasferisce da noi a s&eacute; stesso. Il mercenario della giustizia, quando sarebbe diventato un giudice, l'avrebbe imparato nel racconto <i>Propiziatorio</i>.
</p>
<?
require("../piede.php");
?>
