<?
$descriz = "Propiziatore: uno dei Racconti della Giustizia";
$key = "propiziatore, racconti della giustizia";
$titolo = "Propiziatore";
$sezione = "Strumenti";
$sezioneurl = "/racconti_giustizia/";
require("../capo.php");
?>
<h1>Propiziatore</h1>

<p>Il paese a cui mi avvicinavo sembrava uguale a tutti gli altri che aveva visto durante il mio viaggio. Le vecchie mura che davano una falsa speranza piuttosto di una vera difesa contro un attacco. Qualche albero che lottava per farsi vedere in mezzo agli edifici ammucchiati uno sopra l'altro sulla collina. Il grigio deprimente che caratterizzava la pittura delle case. In cima, elevato e onorato, il tribunale, la mia destinazione. Non avrei mai potuto immagine che quello che mi sarebbe successo in quel paese sarebbe molto diverso dalla mia esperienza negli altri luoghi del mio giro.
</p><p>Il sole batteva e mi faceva girare la testa. La polvere sollevata dai passi degli altri viaggiatori che incrociavo entrava dappertutto - nei vestiti, negli occhi, nella bocca. Ero stanco perch&eacute; avevo camminato per due giorni per arrivare al paese. Non mi piaceva viaggiare. Per&ograve; quando vidi da lontano il paese, mi si rinfranc&ograve; il cuore - non perch&eacute; segnava la fine del viaggio, ma perch&eacute; era pieno di gente in dolore e con rapporti infranti, e il mio desiderio era di dare riposo dove c'erano lotte, guarigione dove c'erano le ferite del passato.
</p><p>Il mio passo si velocizz&ograve;, e sembr&ograve; che entrassi subito nel paese. Dalla strada intrapresa in solitudine, passai subito al rumore di un paese. Sentii una donna affacciata ad una finestra che gridava ad un'amica dall'altra parte della strada, una comitiva che chiacchierava socievolmente all'angolo della strada, dei bambini che giocavano rincorrendosi&hellip; Ma poi persi il buon umore che la gente del paese mi aveva dato, quando vidi un bambino seduto vicino agli altri che giocavano, ma che non partecipava. Non c'era niente di particolare del bambino, almeno per quanto riguardo l'aspetto esteriore. Aveva i vestiti tipici della sua et&agrave;, la faccia e il corpo erano normali.
</p><p>Mi avvicinai lentamente, e mi sedetti accanto a lui e osservai il gioco con lui. Dopo un minuto di silenzio, gli chiesi, "A che cosa giocano quei bambini? Non capisco il gioco".
</p><p>"Acchiappa due", rispose bruscamente.
</p><p>"Che cosa si deve fare?"
</p><p>"Correre e formare delle coppie, poi si riparte".
</p><p>Lasciai trascorrere di nuovo qualche momento di silenzio, poi posi la domanda che volevo in realt&agrave; chiedere. "Perch&eacute; non stai giocando con loro?"
</p><p>A questa domanda, tutta l'emozione repressa dentro il bambino scoppi&ograve;, e si mise a piangere. "Nessuno vuole fare una coppia con me, &egrave; inutile che gioco, perdo sempre."
</p><p>"Come mai?"
</p><p>"Sono tutti cattivi!", rispose fra un singhiozzo e un altro. Capii che ci sarebbe voluto molto tempo per avere una risposta soddisfacente, e in ogni caso avrebbe sempre giustificato le sue azioni dando la colpa agli altri. Trovo questo atteggiamento quasi sempre nel mio lavoro - tutti pensano di essere giusti perch&eacute; ci sono motivi per quello che hanno fatto, la colpa &egrave; sempre degli altri. Con questo atteggiamento (da tutte e due le parti), &egrave; difficile riconciliare le persone.
</p><p>Andai quindi dai ragazzi che giocavano. Mi abbassai per poterli guardare negli occhi, e chiesi loro perch&eacute; l'altro bambino non potesse giocare con loro. Per alcuni secondi vidi soltanto espressioni di rabbia, di disgusto, e di odio. Poi quello che sembrava essere il pi&ugrave; grande rispose, "Non ci piace! Invece di giocare, ci critica, ci prende in giro. Nessuno si diverte quando c'&egrave; lui."
</p><p>Avrei potuto spiegare che anche loro criticavano il bambino, come accusavano lui di fare, che neanche loro erano giusti. Ma pur essendo un'osservazione giusta, sapevo che non era il modo per arrivare alla riconciliazione. Mettermi sopra di loro per fare il giudice, per decidere il giusto e il torto, come se io fossi l'unico giusto, non avrebbe cambiato quello che pensavano degli altri. N&eacute; quello che pensavano di s&eacute; stessi. Dovevo inserirmi nel loro mondo, capire quello che si sentivano, e subire quello che faceva loro male. Cos&igrave; gli chiesi, "Quale male vi ha fatto?"
</p><p>Questa domanda li fece pensare, non erano abituati a riflettere sui loro sentimenti. "Beh&hellip; mi sento come una piccola", propose una ragazza dopo una piccola pausa. "Ci fa arrabbiare", sugger&igrave; un bambino. "Non mi lascia fare quello che io voglio fare", offr&igrave; un altro.
</p><p>"Quindi non vi d&agrave; pugni, non vi fa male al corpo."
</p><p>"No, non cos&igrave;, siamo in troppi e sappiamo difenderci", rispose il pi&ugrave; grande orgogliosamente.
</p><p>"Grazie per avermi raccontato questo, continuate a giocare e torner&ograve; fra poco."
</p><p>Ritornai dal bambino escluso, e gli spiegai che avrebbe potuto giocare di nuovo con gli altri, se volesse. Subito gli occhi si accesero; in realt&agrave; era quello che voleva. "Per&ograve;", continuai, "devi capire che li trattavi male e promettere di non farlo pi&ugrave;. Altrimenti non vorrebbero pi&ugrave; giocare con te. &Egrave; quello che vuoi?"
</p><p>"No", rispose abbassando il capo.
</p><p>"Bene, andiamo a chiedere scusa."
</p><p>Andammo insieme verso gli altri bambini. Spiegai loro la situazione, e il bambino chiese scusa e promise di smettere di parlare male degli altri.
</p><p>"Ma ci hai fatto male! Fa male ancora quando pensiamo alle tue brutte parole. Non possiamo giocare con te."
</p><p>Questo era il mio segnale per scendere in campo veramente. "Posso essere di aiuto, ragazzi. Tutto il dolore che vi sentite, tutta la rabbia, tutto il disprezzo, voglio che lo versiate su di me."
</p><p>I bambini rimasero sbigottiti. Dopo qualche secondo, una bambina sussurr&ograve; timidamente, "Sei cattivo!"
</p><p>"Ancora", li incoraggiai.
</p><p>Gli altri bambini pian piano presero coraggio e cominciarono a insultarmi. "Sei brutto". "Vai via, idiota". "Non sei nessuno".
</p><p>Il bambino che era stato escluso si un&igrave; al coro. "Non sei uno di noi, non ti vogliamo vedere imbecille."
</p><p>Gli altri si congratularono con lui per un'ottima offesa, e lui faceva parte del gruppo nuovamente. Riconciliazione compiuta. Proseguirono con tutti gli insulti che conoscevano. Le loro parole mi riportarono indietro alla mia infanzia, quando ero stato l'oggetto di tanti insulti. Non ero mai stato popolare, ero sempre stato diverso. Volevo aiutare gli altri invece di appartenere alla banda pi&ugrave; forte, e questo dava fastidio. Non sapendo come relazionarsi con me, gli altri si approfittavano per farsi sentire grande sulle mie spalle. In un vortice di immagini e suoni presenti che si mescolavano con quelli passati, sentivo le parole dei bambini, ma con la voce dei miei compagni di una volta che mi prendevano in giro. I vecchi sentimenti risalirono in superficie, e non potei non evitare qualche lacrima.
</p><p>Quando videro il mio dolore gocciolare lungo la mia guancia, risero e derisero e intensificarono il loro scherno. "Che femminuccia!", e molti altri termini ancora pi&ugrave; pesanti, che mi rattristano ancora adesso solo pensando a quello che dissero quei bambini, sia in questo paese sia nella mia infanzia.
</p><p>Mi ritirai con testa abbassata, non riuscendo pi&ugrave; a guardarli negli occhi, e me ne andai mentre i bambini continuavano gioiosamente a lanciare termini volgari, e pure qualche sassolino, nella mia direzione. Allora loro erano forti, io ero solo e debole. Abbandonai il posto con lo stesso sentimento che avevo visto nel bambino escluso quando ero arrivato.
</p><p>&nbsp;
</p><p>Mentre parlavo con i bambini, avevo notato alcuni adulti che si fermarono a guardare, e poi sussurravano l'uno all'altro. Quando ripresi la strada verso il tribunale, cominciarono a chiamare altri, e i sussurri si trasformarono in frasi corti a bassa voce, di cui colsi solo qualche parola&hellip; "propiziatore", "arrivato", "ci aiuter&agrave;", "avete sentito", e cos&igrave; via. In poco tempo, si form&ograve; una piccola folla che mi seguiva e che gridava, "Il propiziatore &egrave; qui!" Le grida viaggiarono pi&ugrave; velocemente di me, e dopo un paio di minuti vidi davanti a me un coro sempre pi&ugrave; forte del passaparola, che si muoveva come un'onda, inarrestabile e irresistibile, verso la mia destinazione al centro del paese.
</p><p>Con questo accompagnamento, finalmente arrivai al tribunale. Le voci erano arrivate molto prima di me, per cui non c'era bisogno di bussare; subito le porte maestose furono spalancate e mi trovai davanti ad un uomo robusto e muscoloso, con ferite e cicatrici evidenti sulla faccia e sulle braccia. La faccia emanava determinazione e tenacia. Questo era un uomo che prendeva sul serio il suo lavoro di riportare la giustizia, con la legge e con la forza. Supposi che fosse in precedenza un mercenario della giustizia; se fosse cos&igrave;, avrebbe avuto molto bisogno di un propiziatore, sia per quello che aveva fatto sia per quello che aveva subito. Per&ograve;, non era il momento per parlare delle sue problematiche e dei suoi disagi.
</p><p>"Benvenuto Propiziatore al mio paese umile e giusto", tuon&ograve;, prendendo per scontato che io ero quello che aveva sentito.
</p><p>"La ringrazio, sono infatti un propiziatore. E Lei &egrave;&hellip;", risposi, non volendo affermare quello che non mi era stato riferito.
</p><p>"Mille scuse Propiziatore, mi ero distratto dalla gioia e dall'entusiasmo di aver un Propiziatore tra di noi, e non mi sono presentato come dovevo. Io sono il Giudice di questo paese. Cerco e creo la giustizia in ogni parte della vita dei nostri cittadini. Sono fiero di affermare che cos&igrave; la giustizia regna qui come in nessun altro luogo della nostra splendida Nazione della Giustizia."
</p><p>Potevo permettere l'iperbole in tali circostanze, ma sembrava comunque un uomo molto pomposo. Sicuramente ci&ograve; era dovuto in parte al suo ufficio e alla figura che doveva presentare agli altri per guadagnare il loro rispetto, ma dava comunque l'impressione di credersi davvero pi&ugrave; giusto degli altri a causa della giustizia che imponeva.
</p><p>"Ma dove sono finite le mie buone maniere?!", prosegu&igrave;. "Deve essere stanco e sporco dal viaggio, Propiziatore. Venga con me e si riposi".
</p><p>Lo seguii attraverso alcune delle stanze laterali dell'ingresso, fino a una piccola camera da letto dove potei rinfrescarmi lontano dalla folla che continuava a esultare davanti al tribunale. Uscii dalla mia stanza per raggiungere il giudice in una sala da pranzo, dove ci avevano preparato una cena semplice. Il giudice continu&ograve; il suo discorso.
</p><p>"Quando due persone del paese non sono d'accordo, vengono da me per capire quale dei due &egrave; giusta. La mia decisione stabilisce la giustizia. Inoltre, a volte vedo situazioni di ingiustizia nel paese, e intervengo anche senza essere interpellato. In questo modo tutti vivono tranquilli, sapendo che la giustizia esiste e sar&agrave; imposta. Per&ograve;&hellip;", abbassando la sua voce, anche se eravamo soli, e con essa abbass&ograve; anche la sua vanit&agrave;, "c'&egrave; qualche caso che mi mette in difficolt&agrave;. Pur aver stabilito e pronunciato quello che &egrave; giusto, alcuni rimangono scontenti, perch&eacute; vogliono non soltanto sapere di avere ragione, ma di non sentirsi perdenti nonostante il fatto di essere nel giusto. Credo che Lei ci possa aiutare affinch&eacute;&hellip;", ritornando al tono di voce di prima, "tutti possano vivere tranquillamente sapendo che la giustizia esiste, &egrave; fatta, ed &egrave; migliore".
</p><p>Approfittai di un respiro fra le frasi per parlare al giudice per solo la seconda volta. "&Egrave; buono essere convinti con la giustizia sia stata fatta. Per&ograve; l'ingiustizia lascia sempre delle conseguenze bruttissime che non vengono cancellate da una semplice dichiarazione di quello che &egrave; giusto o ingiusto. Il mio desiderio &egrave; di propiziare le persone ferite da un'ingiustizia, renderle favorevoli a chi le ha fatto un'ingiustizia, e cos&igrave; raggiungere la riconciliazione."
</p><p>"Beh, pu&ograve; darsi", sput&ograve; il giudice, "ma secondo me la giustizia &egrave; la giustizia; quando so che &egrave; fatta, quando la legge &egrave; osservata o la dovuta punizione scontata, sono gi&agrave; soddisfatto. Poi, quello che mi racconta sembra la vendetta. Ho visto tanti casi in cui le persone sarebbero state contente solo se avessero potuto fatto del male a chi aveva fatto loro un torto. E in questo paese", prosegu&igrave; con un tono cupo e minaccioso, "non sopporto n&eacute; permetto le vendette. Non si pu&ograve; sistemare un'ingiustizia con un'altra ingiustizia, e la violenza non impone mai la giustizia".
</p><p>"Capisco quello che dice", lo placai. "Per&ograve; non dobbiamo pensare alla vendetta ma alla retribuzione. Non &egrave; quanto male dobbiamo fare a chi ha fatto l'ingiustizia, ma quello che dobbiamo dare a chi ha subito il torto per soddisfarlo e propiziarlo. Per&ograve;, nella maggior parte dei casi, neanche la retribuzione &egrave; possibile o non funziona; la strada per la pace &egrave; spesso che chi subisce il torto deve assorbire e sopportare l'ingiustizia."
</p><p>"Vendetta, retribuzione - arrampicarsi sugli specchi", sbuff&ograve;. "Per me alla fine sono la stessa cosa."
</p><p>"Se non siamo attenti, diventano la stessa cosa", ammisi, "soprattutto per noi umani che abbiamo motivi misti e non riusciamo a togliere la nostra sete di superiorit&agrave; sugli altri da quello che facciamo."
</p><p>Vidi che il giudice non era molto convinto e cambiai il discorso, e abbiamo parlato di altro per il resto della serata.
</p><p>&nbsp;
</p><p>Il giorno seguente, mi svegliai con il rumore di tante persone indaffarate. Mi preparai e uscii nel corridoio, dove uno dei dipendenti mi inform&ograve; che il primo caso sarebbe iniziato fra 20 minuti. Camminai con calma verso la sala di giudizio del tribunale. Quando entrai, notai che l'architettura della sala era come tutte le sale di giudizio dei paesi che avevo visto nei miei viaggi: rettangolare con soffitto alto, con un piccolo palco con solo una sedia per il giudice, due banchi con delle sedie per le due parti, e panche per quelli che assistevano nella parte posteriore della sala e lungo i due lati. Per&ograve;, non avevo mai visto prima di allora una sala decorata cos&igrave; tanto. Era dipinta di bianco e nero con evidenti forti contrasti, piuttosto dei tipici colori chiari per rilassare le persone presenti. Dappertutto c'era il solito simbolo della giustizia, una freccia rivolta in su e che non deviava n&eacute; a sinistra n&eacute; a destra. La sedia del giudice non era una semplice sedia come le altre, ma una poltrona che sembrava quasi un trono. Era completamente bianca. Sopra la sedia, e quindi anche sopra la testa del giudice, c'era la freccia pi&ugrave; grande di tutte. Anche, anzi soprattutto, il giudice doveva sottomettersi alla giustizia.
</p><p>Mi accomodai nella prima fila dietro i due banchi. Poco dopo arrivarono due signore che si sedettero, seguite dal giudice. Il giudice apr&igrave; il caso, chiedendo alle signore di esporre i loro casi. La prima, sui 50 anni e piccolina, vestita in modo elegante, accus&ograve; l'altra di aver rubato dei soldi da lei sul posto di lavoro. Effettivamente, la sua borsa vuota fu ritrovata fra i possessi della seconda signora. L'altra signora, giovane e con i capelli in aria, si difese dicendo solo che non aveva idea di come la borsa fosse arrivata dentro la sua. Per&ograve;, quando dei testimoni raccontarono di aver visto la seconda signora frugare nelle cose della prima, che il giorno successivo aveva un nuovo vestito costoso, e che da tempo le due donne litigavano con parole aspre e insulti reciproci, la colpevolezza della giovane sembrava chiara. A questo punto, intervenne il giudice.
</p><p>"Come pronunciai nel processo, dichiaro l'accusata colpevole di furto. &Egrave; gi&agrave; stata condannata e punita. Siamo nuovamente qui perch&eacute; l'accusatrice sostiene che la pena non sia sufficiente."
</p><p>"Ci puoi scommettere", interpose la signora urlando. "Voglio indietro anche i miei soldi".
</p><p>"Per&ograve; la giustizia &egrave; stata eseguita", rispose il giudice con un tono severo, e una minaccia sottintesa che lei non doveva pretendere altro. Una minaccia che l'accusatrice non cap&igrave; o scelse di non capire.
</p><p>"Ma io non voglio solo la Sua giustizia. Io voglio i miei soldi!"
</p><p>"Ecco Propiziatore, questo &egrave; il motivo per cui abbiamo riaperto il caso quando &egrave; arrivato. La giustizia &egrave; stata fatta, ma l'accusatrice non &egrave; stata accontentata."
</p><p>"Capisco giudice", parlai per la prima volta. "Chiedo permesso di parlare con le signore".
</p><p>"Pu&ograve; parlare con loro".
</p><p>Iniziai con l'accusata. "Prima di tutto, come ti chiami?"
</p><p>"Elam, illustrissimo egregio signor Propiziatore ".
</p><p>"Non servono tutti gli aggettivi, Elam, basta propiziatore. Perch&eacute; hai rubato i soldi?"
</p><p>"Non ho rubato niente. Qualcuno ha nascosto la sua borsa nella mia, forse &egrave; stata lei stessa", indicando l'altra donna con un movimento della testa e disprezzo nello sguardo. "Sarebbe qualcosa che quella delinquente sarebbe in grado di fare".
</p><p>"A chi dai del delinquente? Tu che non sei altro che una sporca ladra!"
</p><p>Prima che tutto degenerasse in una battaglia di insulti urlati, mi rivolsi all'accusatrice, "E come ti chiami tu?".
</p><p>"Anip, Propiziatore. E quella", indicando l'altra donna, "&egrave; una bugiarda, una ladra, una calunniatrice, &hellip;"
</p><p>"Canaglia", url&ograve; Elam, interrompendo.
</p><p>"Basta, signore. Io non sono qui per decidere quello che siete", sussurrai per provare una seconda volta a evitare le grida reciproche. Non era pi&ugrave; il caso di continuare con una discussione pubblica, e mi sedetti accanto ad Anip per parlarle in privato.
</p><p>"Quanti soldi hai perso?"
</p><p>"Non lo so, non ho contato esattamente, ma saranno 500, forse 600."
</p><p>"E se ricevessi questi soldi da Elam, la questione sarebbe chiusa per te?"
</p><p>Anip riflett&eacute; qualche secondo, e rispose pensierosamente, "Sarebbe un risarcimento per i danni subiti, non vorrei pi&ugrave; di quanto ho perso. Per&ograve;, lei rimarrebbe la mia nemica."
</p><p>"&Egrave; quello che vuoi, avere una nemica per tutta la vita?"
</p><p>"Forse no, vorrei magari avere un rapporto giusto, tranquillo."
</p><p>Andai da Elam, e le feci la stessa domanda, "Vuoi combattere contro Anip per tutta la vita? Oppure vuoi star bene con gli altri?"
</p><p>Anche Elam rispose riflettendo su quello che voleva veramente, "Suppongo che in fin dei conti, preferirei non essere sempre in guerra."
</p><p>"Allora", risposi, "un rapporto vero deve essere fondato sulla verit&agrave; e non sull'inganno, altrimenti non &egrave; giusto. La verit&agrave; delle nostre imperfezioni che sopportiamo a vicenda, non la finzione che saremo sempre bravi l'uno verso l'altro. Se vuoi la pace, devi pagarne il costo, e il prezzo &egrave; la verit&agrave;."
</p><p>"Cio&egrave; devo dire quello che ho fatto in realt&agrave;?"
</p><p>"Esatto. Per&ograve; qualsiasi persona malvagia pu&ograve; raccontare le cose malvagie che ha fatto, ma rimane un nemico degli altri. Bisognerebbe anche capire che erano cose sbagliate, e desiderare non farle pi&ugrave;."
</p><p>"Ho capito, mi pare giusto."
</p><p>"E poi, c'&egrave; la questione del denaro. Se veramente pensi di aver sbagliato, la prova di questo sar&agrave; che restituirai i soldi presi."
</p><p>"Questo sar&agrave; un problema", rispose Elam, e il sorriso che avevo visto cominciare a apparire spar&igrave; nuovamente. "La verit&agrave; &egrave; che ho gi&agrave; speso quei soldi e non li potr&ograve; restituire, non ho pi&ugrave; niente."
</p><p>Io feci qualche calcolo nella mia mente. Avevo portato 1000 con me per sostenermi durante il mio viaggio. Gi&agrave; avevo spesa quasi 400 fino a quel giorno, mi rimanevano poco pi&ugrave; di 600. Per quanto tempo avrei potuto continuare con gli spiccioli che mi sarebbero rimasti? Non potevo fare una simile sciocchezza! Forse potevo troncare il viaggio e rientrare subito&hellip; Ma che cosa sarebbe successo a tutti quelli delle altre citt&agrave; che avevano bisogno della riconciliazione, del propiziatore? No, era una follia. Poi guardai di nuovo Elam e Anip e vidi l'odio inizia a sciogliersi, vidi la speranza di un nuovo inizio, e un fremito di compassione mi travolse. Non potei resistere, era nella mia natura rispondere ai bisogni relazionali in cui mi imbattevo, non potevo farci niente e sbottai, "Non ti preoccupare, ci penser&ograve; io".
</p><p>Elam, colta alla sprovvista, balbett&ograve;, "C-c-cosa? P-p-perch&eacute;? Per me?"
</p><p>"Per voi", risposi semplicemente.
</p><p>Mentre ritornavo da Anip, frugai nella mia borsa raccogliendo il denaro che avevo messo da parte. 500&hellip; 550&hellip; 580&hellip; finalmente trovai l'ultima moneta e le consegnai 600. "Ecco la restituzione di quello che hai perso. Inoltre, Elam vuole dirti qualcosa", spiegai ad Anip, facendo un gesto per chiedere a Elam di venire.
</p><p>"S&igrave;&hellip; aah&hellip; ciao Anip", inizi&ograve; Elam, imbarazzata. Sapevo quello che dovevo dire, ma era comunque difficile esprimere i suoi pensieri davanti ad Anip e a tutto il tribunale. "Vedi, mi dispiace per quello che &egrave; successo, per&ograve;&hellip;".
</p><p>"Se c'&egrave; un 'per&ograve;', non &egrave; pi&ugrave; chiedere scusa ma una scusa per giustificarsi", sussurrai gentilmente a Elam.
</p><p>"S&igrave;, s&igrave;, certo. Chiedo scusa per quello che ho fatto, mi sono sbagliata. Non lo voglio fare pi&ugrave;."
</p><p>"Accetto le tue scuse e i tuoi soldi", rispose Anip cortesemente. "Per me, la questione &egrave; chiusa e possiamo cercare di essere amiche."
</p><p>Subito un applauso scoppi&ograve; fra quelli che guardavano i processi. Poi iniziarono gli urli, "Evviva", "Bravo". Infine, uno grid&ograve;, "Pro-pi-zia-to-re, pro-pi-zia-to-re", e poi una seconda persona si un&igrave;, poi alcuni altri, fino a quando tutti erano uniti in un coro da stadio. Tutta questa acclamazione mi mise in imbarazzo e cercai senza successo di nascondermi. Non facevo il propiziatore per essere onorato dagli altri, lo facevo per aiutare gli estraniati. Volevo che loro fossero onorati, non io.
</p><p>&nbsp;
</p><p>Il giudice riusc&igrave; a stento a silenziare tutti e chiam&ograve; un intervallo per farli calmare. Durante la pausa, mi si avvicin&ograve; e disse, "Ben fatto, la giustizia &egrave; stata fatta in questo caso."
</p><p>"Grazie, ed anche la riconciliazione, ora il rapporto &egrave; ristabilito fra di loro, c'&egrave; un rapporto giusto."
</p><p>"Per&ograve;, non voglio mettere in dubbio quello che ha fatto, ma se posso chiedere, che cosa sarebbe successo se la signora accusata non avesse ammesso la sua colpa o non avesse voluto impegnarsi a non farlo pi&ugrave;? O se la signora accusatrice non avesse accettato i soldi come risarcimento o non voluto l'accusata come amica?
</p><p>"Questo &egrave; la limitazione del mio lavoro", ammisi al giudice. "Posso fare del tutto per incoraggiare, persuadere e convincere di riconciliarsi, ma se non c'&egrave; il desiderio da una parte, non succeder&agrave;. Non posso cambiare il carattere delle persone, e la tendenza di alcuni, di molti, &egrave; di tenersi al male. Se avessi un modo per cambiare il carattere, lo farei, ma purtroppo non ce l'ho!"
</p><p>Intuii che il giudice era leggermente contento di questa notizia, anche se cerc&ograve; di nascondere i suoi sentimenti. "Almeno io non ho questa limitazione, io posso sempre imporre la giustizia anche se non c'&egrave; il desiderio di fare quello che &egrave; giusto. Ora possiamo tornare ai casi."
</p><p>&nbsp;
</p><p>Riprendemmo con la considerazione del secondo caso. Un uomo aveva ucciso accidentalmente il cane amatissimo di un altro. I due signori erano d'accordo che era successo cos&igrave;. Il giudice obblig&ograve; il primo a risarcire il danno, acquistando un nuovo cane. L'altro uomo espresse la sua contentezza di aver un nuovo cane, ma, ovviamente trattenendo la sua tristezza e forse qualche lacrima, aggiunse che gli sarebbe mancato il suo compagno. Era possibile sostituire un cane, ma non un amico. A questo punto interruppi la discussione.
</p><p>"E se l'altro signore potesse non solo sapere ma anche capire il tuo dolore, aiuterebbe?"
</p><p>"Non lo so", replic&ograve;, "non vedo come potrebbe restituirmi quello che ho perso".
</p><p>"Certo, &egrave; impossibile ridarti quello o cancellare i brutti sentimenti. Per&ograve; un dolore condiviso &egrave; un dolore dimezzato. Quello che suggerisco &egrave; di piangere insieme con qualcuno, sentirsi compreso, e aver qualcuno che pu&ograve; simpatizzare con te nelle difficolt&agrave;".
</p><p>L'uomo si raddrizz&ograve; con queste parole e afferm&ograve; orgogliosamente, "Mica voglio piangere! Per&ograve;", con una voce leggermente pi&ugrave; tremante, "se ci fosse qualcuno cos&igrave;&hellip;".
</p><p>"Propongo", mi rivolsi al giudice, "oltre al risarcimento, anche il soggiorno della solidariet&agrave;".
</p><p>"Che cosa &egrave;?", mormor&ograve; all'idea che la sua punizione non era sufficiente.
</p><p>"In questo caso, il colpevole dovr&agrave; soggiornare con l'altro signore, per capire il suo rapporto con il nuovo cane e iniziare a vedere quello che ha perso con la morte dell'altro animale. Inoltre, quello che ha perso il cane avr&agrave; qualcuno che lo potr&agrave; consolare".
</p><p>"Interessante", disse il giudice, palesemente riflettendo sulla mia proposta. "E se", aggiunse dopo una piccola pausa per raccogliere i suoi pensieri, "il colpevole non &egrave; in grado di consolare l'altro? Se non riesce a sentire quello che sente l'altro?"
</p><p>"S&igrave;, questo succede a volte", confermai. "Propongo quindi che anch'io far&ograve; il soggiorno della solidariet&agrave; insieme con i due signori. Cos&igrave; al massimo quello che ha ucciso il cane vedr&agrave; e capir&agrave; il dolore, e io potr&ograve; simpatizzare, perch&eacute; anch'io so cosa vuol dire subire una tale perdita. Ho perso tanti cari quando ero piccolo e poi quando ero giovane. Sono rimasto senza genitori che mi amavano, senza amici&hellip; E poi da quando sono diventato un propiziatore, ho lasciato tutto, la mia bella casa e la famiglia, i fratelli e le sorelle, per amor degli altri."
</p><p>"Per me &egrave; possibile, se cos&igrave; il signore &egrave; accontentato", sentenzi&ograve; il giudice, indicando quello che aveva perso il cane, che annu&igrave; positivamente. "Dichiaro il caso chiuso e che la giustizia &egrave; stata eseguita".
</p><p>&nbsp;
</p><p>Ci fu un'altra pausa prima del prossimo caso. Chiacchieravo con quello che aveva perso il cane, per conoscerlo e capire meglio come avrei potuto aiutarlo, quando una donna irruppe nella sala e grid&ograve;, "Dove &egrave; il Giudice di questo paese?". Era chiaro che volesse mostrare subito la sua importanza. Non era vestita come tutti gli altri, ma con vesti lunghe, colorate, e poco pratiche. Nella sala semplice di bianco e nero, lei era un'esplosione di colore che la faceva notare immediatamente. L'abbigliamento colpiva l'occhio subito. I capelli avevano una miriade di tinte e sfumature. Teneva in mano tanti libri e carte, che portava in modo ufficiale. Dietro di lei c'erano altre tre persone con altre carte e vestiti elaborati, pur meno della donna, e qualche guardia vestita semplicemente ma con arme vistose.
</p><p>Dopo appena un paio di secondi, ripet&eacute;, "Ho chiesto, dove &egrave; il Giudice? Non si fa aspettare una persona con me!".
</p><p>Il giudice si alz&ograve; e disse in modo autorevole, "Sono io il Giudice, e esiguo ordine nel mio tribunale come pure nel mio paese".
</p><p>Se sperava di spaventare e calmare la donna con questa affermazione, non ebbe l'effetto desiderato. La donna voleva imporre la sua superiorit&agrave; e non poteva permettersi di fare qualcosa che il giudice aveva comandato. "Sono il Direttore della Giustizia ". Rabbrividii a queste parole. I dipendenti dell'Ufficio della Giustizia uscivano di rado dai loro comodi uffici, e quando lo facevano era solo per casi seri. Inoltre, siccome era venuto il Direttore stesso, lo consideravano molto seriamente. Non avevo mai visto il Direttore della Giustizia in tutti i miei viaggi. Ero sicuro che non volevo vederlo neanche allora - qualsiasi cosa che sarebbe successo sarebbe finito male.
</p><p>"Giudice, Lei &egrave; accusato di ingiustizia verso la nostra eccellente Nazione della Giustizia e verso le sue istituzioni. Il processo inizier&agrave; subito. Si sieda adesso!", indicando il banco degli accusati mentre lei e i suoi impiegati popolarono l'altro banco.
</p><p>La perplessit&agrave; del giudice si mut&ograve; in confusione, e esit&ograve; un momento mentre pens&ograve; a quello che doveva fare o dire. Quel momento era troppo per il Direttore della Giustizia, che fece valere la sua importanza gridando di nuovo, "Ho detto di sedersi!"
</p><p>Il giudice si sedette in silenzio, si era gi&agrave; arreso alla prepotenza del Direttore della Giustizia.
</p><p>"Bene, possiamo cominciare", disse con un tono ufficiale. "L'accusa &egrave; ingiustizia verso l'illustre Nazione e le sue istituzioni. Come risponde a questa accusa?"
</p><p>"N-n-non lo so&hellip; Insomma, i-io&hellip; Ma&hellip;", borbott&ograve; il giudice, incerto di quello che poteva o doveva dire, completamente perso in questa situazione in cui non aveva pi&ugrave; il controllo dello svolgimento degli eventi. "P-posso dire di aver sempre ubbidito alle leggi, cio&egrave; alle leggi della nostra bellissima Nazione."
</p><p>"Non ne ho dubbio. Anche se alcuni giudici approfittano della loro posizione per infrangere le leggi per il proprio beneficio, ogni relazione che la riguarda che abbiamo ricevuto riferisce che Lei ha osservato le nostre leggi. Ma ci&ograve; non la discolpa dall'accusa di ingiustizia. Non ha altro da dire per giustificarsi?"
</p><p>"Mi accusa di essere ingiusto anche se ho fatto tutte le cose giuste?!" Un filo di agitazione inizi&ograve; a manifestarsi, non so se fosse per la disperazione o per la rabbia.
</p><p>"Esatto, signor Giudice", rispose con un mezzo sorriso. Stava godendo mettere il giudice in difficolt&agrave; e in disagio.
</p><p>"Ma che cos'&egrave; la giustizia?"
</p><p>"La giustizia, mio caro Giudice&hellip;", e allora divent&ograve; condiscendente, umiliando il giudice ulteriormente, "la giustizia non &egrave; fare cose giuste ma piuttosto essere giusto. Vuol dire essere, vivere, pensare, relazionarsi quello che si &egrave;, non solo fare quello che si &egrave;. Un re &egrave; giusto quando vive come un re dovrebbe. Un Direttore della Giustizia &egrave; giusto quando vive come Direttore della Giustizia. Un cittadino comune &egrave; giusto quando vive come cittadino. E un giudice &egrave; giusto solo se &egrave; come un giudice deve essere".
</p><p>"E come deve essere un giudice?"
</p><p>"Un giudice deve collaborare alla creazione di una nazione giusta, lavorando nel suo paese, con giustizia verso i residenti del paese ma anche con giusti rapporti con il resto della nazione. &Egrave; proprio qui che Lei non &egrave; stato giusto, essendo mancante verso l'eccelsa Nazione".
</p><p>"Non ho fatto niente di ingiusto! Mi dica di quale atto sono accusato", interruppe il giudice disperatamente.
</p><p>"Non capisce ancora, signor Giudice. Lei non &egrave; accusato di nessuno atto ingiusto, ma di essere ingiusto. Invece di promuovere una nazione giusta, Lei ha lavorato per la creazione di un paese giusto. Lei ha voluto il suo", sottolineando l'ultima parola, "paese giusto. Lei voleva essere riconosciuto come colui che decide, mantiene, e impone la giustizia, sia dai suoi cittadini sia dagli altri paesi della nostra giusta Nazione. Insomma, era tutto per Lei, non per la Nazione. Mettere i propri interessi, i propri desideri, e il proprio onore sopra quelli della Nazione &egrave; un rapporto ingiusto con la Nazione".
</p><p>"Cercare la giustizia non pu&ograve; mai essere ingiusto!", dichiar&ograve; il giudice con fermezza. Cominciava a riprendersi dopo la scossa iniziale dell'entrata e dell'accusa del Direttore della Giustizia.
</p><p>"Giusto. Ma si pu&ograve; essere ingiusti cercando la giustizia. Risponda a questa domanda: quale ruolo aveva l'intera sublime Nazione della Giustizia nel suo impegno per la giustizia?"
</p><p>"Certo, so che la nostra stupenda nazione esiste, e che &egrave; giusta. Per&ograve; qui ci sono io, io sono la giustizia e non qualche entit&agrave; lontana che non si interessa degli affari nel mio paese."
</p><p>"Si sbaglia, Giudice. L'illustre Nazione ha mandato tante notizie al paese, che ha ignorato, e voleva sentire da Lei come va l'esercizio del suo ufficio, per poterla aiutare, informazioni che non ha mai mandato. Pensava e cercava di farcela da solo, per ricavarne l'onore, piuttosto di riconoscere la superiorit&agrave; della grandiosa Nazione che l'ha messo in questa posizione."
</p><p>Ci fu un lungo silenzio. Il giudice non seppe rispondere. I suoi schemi per valutare la giustizia e l'ingiustizia erano stati spazzati via. Nella sua mente, c'era la confusione. Non riusciva a formare pensieri coerenti che potevano essere espressi in parole. Finalmente, sbott&ograve; e balbett&ograve;, "I-I-Io ingiusto? Forse n-n-non ho pensato a, a, alla nazione. Ma non ha sba-sbagliato."
</p><p>"Invece il tuo atteggiamento &egrave; stato esaminato e valutato dalle massime autorit&agrave;", dichiar&ograve; solennemente il Direttore della Giustizia, "che l'hanno trovato colpevole di non aver onorato la nostra brillante e maestosa Nazione della Giustizia. Sar&agrave; spogliato del suo ufficio di giudice."
</p><p>La reazione del giudice fu immediata, semplice, e appassionata. "No!"
</p><p>Fino a quel punto, ero rimasto in silenzio, sbalordito dagli avvenimenti. Leggermente ripreso, chiesi di poter dire qualcosa.
</p><p>"Chi osa interrompere un processo del Dipartimento della Giustizia! Chi &egrave; Lei?" Mentre gridava indignata, sussurr&ograve; ai suoi impiegati di scrivere la mia identit&agrave; e quello che avevo fatto, per un processo futuro.
</p><p>"Chiedo scusa per l'intrusione, Direttore della Giustizia. Sono un propiziatore. Sono arrivato in questo paese ieri e mi &egrave; stato chiesto di aiutare in alcuni casi."
</p><p>L'atteggiamento del Direttore della Giustizia mut&ograve; subito da prepotente a conciliatore. "Non sapevo che ci fosse un Propiziatore presente. &Egrave; un compito essenziale per la nostra Nazione mantenere giusti rapporti fra le persone. Sono io che devo chiedere scusa, non sono stata giusta nei suoi confronti. Mi fa molto piacere che Lei sia presente per questo processo importante, forse ci sar&agrave; di aiuto".
</p><p>"Infatti, credo che sia importante, ed &egrave; il mio desiderio, propiziarla, Direttore&hellip;"
</p><p>"Me? Propiziare me? Io non ho bisogno di essere propiziata. Io sono sopra tali sentimenti. Io semplicemente rappresento la nostra gloriosa e giusta Nazione."
</p><p>"Ha ragione, Direttore della Giustizia, mi sono espresso male. Piuttosto, potrei e vorrei propiziare la Nazione che Lei rappresenta, Lei potr&agrave; accettare la mia offerta per conto della Nazione della Giustizia."
</p><p>"Una proposta interessante, Propiziatore. Non ho mai sentito di una tale propiziazione. Sono curiosa, che cosa propone di preciso?"
</p><p>"Di solito, quando due individui sono in conflitto, propizio la parte offesa mettendomi nei panni del colpevole. Do soddisfazione all'altra parte al posto del colpevole, che forse non pu&ograve; rendere quella soddisfazione. Per&ograve; questo caso &egrave; diverso, la parte offesa &egrave; la nostra magnifica Nazione, onorata da tutti meritevolmente. Qualsiasi offesa contro questa gloria &egrave; gravissima, e un cittadino normale non potrebbe mai pagare quel prezzo. Io, come persona, come Agap Iurtla, ho da offrire solo la mia ingiustizia, che pu&ograve; sostituire e soddisfare solo altri ingiusti. Solo la Nazione stessa &egrave; abbastanza gloriosa e giusta da soddisfare s&eacute; stessa. Oppure qualcuno come la sua rappresentante. Direttore della Giustizia, &egrave; disposta, per conto della Nazione, a rinunciare alla sua posizione affinch&eacute; il giudice possa rimanere giudice della citt&agrave;, e l'offesa contro la Nazione pagata?"
</p><p>"Non ci pensi affatto!"
</p><p>"Certo, lo immaginavo. Per&ograve; io", dichiarando solennemente alzandomi in piedi, "Propiziatore della Gloriosa Nazione della Giustizia, incaricato e autorizzato dalla stessa Nazione a eseguire la Volont&agrave; della Nazione di creare la giustizia e dei giusti in ogni luogo e ambito della Nazione, con tutto il potere della suddetta Nazione che rappresento, con la presente dichiaro che il Giudice di questo paese &egrave; colpevole dell'ingiustizia di cui &egrave; stato accusato oggi, ma che la Nazione prende la punizione su di s&eacute; stessa, tramite il summenzionato Propiziatore, che deporr&agrave; la sua posizione, il suo ruolo, la sua autorit&agrave; con effetto immediato."
</p><p>Nel momento di stupore silenzioso che segu&igrave; il mio discorso, lasciai il mio posto di onore in prima fila e andai a mettermi in fondo alla sala, con gli altri spettatori in piedi. Mentre ci camminavo, ci fu un sussulto di sorpresa da parte di tutti, dopo di cui la Direttore della Giustizia mi grid&ograve;, "Propiziatore, che cosa fa? Non pu&ograve; fare cos&igrave;!"
</p><p>In un primo momento, non risposi e proseguii la mia camminata. Siccome tutti mi guardavano come se dovessi rispondere, sussurrai semplicemente, "Non c'&egrave; nessun Propiziatore qui."
</p><p>"Va bene, posso fare questo Suo gioco. Abur, Arab, &hellip;"
</p><p>"Agap, Direttore della Giustizia, e mi dia del tu adesso."
</p><p>"Va bene Agap, ma sei sicuro che &egrave; proprio quello che vuoi?"
</p><p>Questa domanda mi cre&ograve; uno scompiglio di sentimenti, un parapiglia di pensieri. Che cosa volevo veramente, nel mio profondo? Da quando ero piccolo, da quando soffriva la mancanza di famiglia e amici, da quando subivo gli insulti e il disprezzo degli altri, ho voluto aiutare la gente a non soffrire come me, ho voluto ripristinare i rapporti infranti. Certo, ricevere il nome Propiziatore mi ha dato una certa importanza nella societ&agrave;, la gente mi stima e mi onora. Ma non sono cose mi interessano, a cui voglio aggrapparmi gelosamente. Per&ograve;, se non sono propiziatore, posso ancora propiziare? Chi sono, un propiziatore, o uno che propizia? Non lo so. Ma so che non posso non aiutare gli altri. Non ci riesco! Se fosse possibile, avrei scelto un altro modo. Ero in agonia pensando a quello che mi sarebbe successo, ma soprattutto a quello che sarebbe successo agli altri. Guardai Elam e Anip, pensai al bambino che avevo conosciuto quella mattina, tutte care persone normali che avevano bisogno della propiziazione, il mio cuore era per loro. Poi c'era il giudice...&hellip; Orgoglioso, sicuro di s&eacute;, potente. Potevo abbandonare tutti per uno come lui? Almeno che perdessi il mio titolo per qualcuno che veramente lo meritava! Per&ograve; a questo punto mi rimproverai. Perch&eacute; giudicavo? Certo che lui ne aveva bisogno, esattamente come gli altri, e probabilmente anche maggiormente. I benestanti, quelli a cui la vita sembra andare sempre bene, hanno difficolt&agrave; nei rapporti come tutti. Fissai gli occhi sul giudice per l'ultima volta, ebbi compassione di lui, e risposi al Direttore della Giustizia, "S&igrave;. Non voglio non essere pi&ugrave; un propiziatore, ma sono sicuro che il mio desiderio di propiziare la Nazione della Giustizia nei confronti del giudice &egrave; pi&ugrave; forte del desiderio di essere propiziatore".
</p><p>"Cos&igrave; sia", tuon&ograve; il Direttore formalmente. "Agap Iurtla, sei stato ritenuto colpevole di ingiustizia verso l'illustre Nazione e le sue istituzioni. Sarai destituito dell'ufficio di Propiziatore, con effetto immediato. Guardia, portalo alla sua camera, e domani mattina assicurati che parta dalla citt&agrave;."
</p><p>Una delle guardie del Direttore apparve subito al mio fianco, mi prese il braccio e mi accompagn&ograve; alla mia stanza. Mentre camminavamo, aveva una faccia senza espressione e si muoveva in modo molto rigido, come se marciasse. Arrivati alla destinazione e chiusa la porta, la Guardia si rilass&ograve;.
</p><p>"A me, mi dispiace per quello che ti &egrave; successo. Non ho capito tutto di quello che avete detto, ma era una grande cosa che hai fatto per il Giudice. Cosa pensi di fare adesso?"
</p><p>"Non lo so, sono ancora sconvolto e stanco per tutto quello che &egrave; successo. Voglio solo riposarmi adesso e poi ci penser&ograve;."
</p><p>"OK. Sai, il Direttore della Giustizia &egrave; una tipa difficile. Disprezza noi guardie perch&eacute; noi non siamo a suo livello, ci tratta male. Come ha fatto male anche a te. A volte la odio per quello che fa a noi e agli altri."
</p><p>"Grazie, me lo ricorder&ograve;. Per&ograve;, l'odio non &egrave; la giusta risposta quando qualcuno ci fa del male. Sappiamo che sbaglia quando dice che tu sei inferiore, ma non devi permettere che la sua opinione influenzi la realt&agrave; di come sei. Invece, tu devi essere superiore, non disprezzandola ma piuttosto facendo sempre del bene a lei, anche se ti costa tanto."
</p><p>"&Egrave; vero, gi&agrave; mi sento meglio verso di lei."
</p><p>"Per&ograve; adesso voglio veramente riposarmi, &egrave; stata una giornata lunga e faticosa, ho speso tutto."
</p><p>"Certo, certo, ti lascio e ci vedremo la mattina."
</p><p>&nbsp;
</p><p>Nonostante la stanchezza, non riuscii a dormire quella notte. Mille pensieri e centinaia di domande mi frullarono per la testa. Avevo fatto la cosa giusta? Volevo veramente rinunciare ad essere un propiziatore? Rinunciare a quello che ero? Ma che cosa ero, un propiziatore o qualcuno che propiziava? Cos&igrave; mi misi a scrivere questo testo per chiarire le mie idee. Non so chi lo legger&agrave;, forse nessuno, ma scriverlo mi ha aiutato. Per me, c'&egrave; una fine ingiusta, perch&eacute; non ho ricevuto quello che meritavo. Per&ograve;, come risultato la Nazione &egrave; pi&ugrave; giusta, con persone con rapporti giusti. Un sacrificio che sono ben disposto a fare.
</p><p>&nbsp;
</p><p>- - - - -
</p><p>&nbsp;
</p><p>Sono la Guardia. Quando sono venuto per accompagnare il Propiziatore fuori citt&agrave;, non c'era pi&ugrave;. Aveva gi&agrave; partito da solo. Ho trovato solo questo libretto con quello che ha scritto da quando &egrave; venuto ha aiutare la nostra citt&agrave;. Non o capito tutto quello che ha scritto, ma so che se ci sarebbero pi&ugrave; persone come lui, la nostra nazione sarebbe pi&ugrave; meglio. Veramente, quest'uomo era giusto!
</p>
<h2>Note su "Propiziatore"</h2>

<p>'Propiziare' non &egrave; una parola molto conosciuta in italiano, per cui potrebbe essere utile spiegarla qui. In generale, vuol dire 'rendere ben disposto'. In altre parole, se qualcuno ce l'ha con me, posso cercare di propiziarlo affinch&eacute; non sia pi&ugrave; arrabbiato con me. Nelle religioni, la parola &egrave; spesso usata con il senso di placare un dio che &egrave; arrabbiato con me, di solito con dei sacrifici, per ottenere la sua benedizione.
</p><p>Nella Bibbia, il coperchio dell'arca del patto nel tabernacolo che Mos&egrave; fece costruire era chiamato il propiziatorio, perch&eacute; era il luogo dove Dio veniva propiziato (Esodo 25:17-22; Ebrei 9:5) affinch&eacute; potesse dimorare con gli Israeliti. Questa propiziazione viene adempiuta da Ges&ugrave;, che &egrave; un sacrificio propiziatorio (la sua morte propizia Dio verso noi), che dimostra la giustizia di Dio, perch&eacute; in questo modo la nostra ingiustizia viene punita (presa da Ges&ugrave;) e Dio pu&ograve; dimorare con noi (Romani 3:25; 1Giovanni 2:2; 4:10).
</p><p>Nello stesso modo, il propiziatore del racconto propizia le persone che hanno subito un'ingiustizia (spesso con un sacrificio, perch&eacute; qualcuno deve pagare il prezzo dell'ingiustizia) per ripristinare il rapporto fra le persone. In questo modo &egrave; simile a Ges&ugrave; Cristo, ed anche in alcuni altri modi come vengono spiegati da queste note, anche se, diversamente da Ges&ugrave;, il propiziatorio non &egrave; perfetto, e non ogni caratteristica del propiziatore va considerata come un parallelo alla vita di Ges&ugrave;.
</p><p>&nbsp;
</p><p>L'incontro con i bambini riflette sulle scuse e sul ravvedimento, un tema considerato diverse volte in questo racconto e negli altri, soprattutto nel racconto Direttore della Giustizia. Una vera scusa, o confessione di aver sbagliato, senza 'se' e senza 'ma', &egrave; veramente difficile, perch&eacute; vogliamo spesso pensare e fare credere che quello che abbiamo fatto non era veramente sbagliato perch&eacute; c'erano delle motivazioni - meglio ancora se possiamo trasferire la colpa a qualcun altro. Il ravvedimento invece &egrave; un cambio di direzione, ed &egrave; composto da un dispiacere per quello che &egrave; stato fatto nel passato e un desiderio di non farlo pi&ugrave; (anche se, siccome rimaniamo esseri imperfetti, probabilmente lo faremo di nuovo). 
</p><p>&nbsp;
</p><p>Il giudice e il propiziatore parlano insieme del prezzo della giustizia e del perdono. Anche questo &egrave; un tema importante in questi racconti, soprattutto questo e Direttore della Giustizia. Se l'ingiusto non pu&ograve; pagare le conseguenze della sua ingiustizia, il giusto rimarr&agrave; sempre insoddisfatto e l'ingiusto non ha speranza di perdono? 
</p><p>&nbsp;
</p><p>Elam e Anip forniscono una risposta semplice (non esauriente) alla domanda precedente: qualcun altro pu&ograve; pagare per l'ingiusto. Ci vogliono comunque, come il giudice osserv&ograve;, una vera scusa e ravvedimento da parte dell'ingiusto, e disponibilit&agrave; da parte di quello offeso di accettare la scusa, il ravvedimento, e il pagamento. Per noi che offendiamo Dio, la disponibilit&agrave; da parte sua c'&egrave; sempre, come anche l'offerta da parte di Ges&ugrave; Cristo di pagare; tocca a noi ammettere la nostra colpa e impegnarci a non farlo pi&ugrave;. Il propiziatore ammise che era la limitazione del suo lavoro. Per&ograve;, anche qui Dio opera: pu&ograve; anche cambiare il nostro carattere per renderci capaci di cercare la riconciliazione. Questo &egrave; uno dei temi di Detective PM.
</p><p>&nbsp;
</p><p>Il caso dei due uomini approfondisce l'opera di Ges&ugrave;, che non &egrave; una mera transazione commerciale. Ges&ugrave; pu&ograve; anche simpatizzare con noi nelle nostre debolezze (Ebrei 4:15). Infatti, &egrave; diventato simile a noi in ogni cosa, per essere un misericordioso e fedele sommo sacerdote nelle cose che riguardano Dio, per compiere l'espiazione dei peccati del popolo. Infatti, poich&eacute; egli stesso ha sofferto la tentazione, pu&ograve; venire in aiuto di quelli che sono tentati (Ebrei 2:17-18). In questo versetto, la parola "espiazione" &egrave; la stessa usata per "propiziazione", ma si espia (togliere la colpa) un'azione mentre si propizia (rendere ben disposto) una persona.
</p><p>&nbsp;
</p><p>Il discorso fra il direttore della giustizia e il giudice illustra la differenza fra gli atti ingiusti e l'ingiustizia, fra i peccati e il peccato. Essere giusti vuol dire vivere anche con i rapporti giusti, in modo particolare con Dio. Anche se possiamo forse dichiarare di aver fatto poche cose sbagliate, quello che conta &egrave; il nostro rapporto con Dio. L'abbiamo sempre e in ogni modo onorato come supremo sovrano dell'universo, e in modo particolare della nostra vita? Perch&eacute; questo &egrave; l'unico giusto rapporto con colui che &egrave; il supremo sovrano dell'universo e di noi. Tutta la nostra vita &egrave; orientata verso la sua gloria? In questo il giudice era mancante: era impegnatissimo nella giustizia legale nel suo paese, ma era per la sua visione personale della giustizia e non considerava il rapporto con la nazione (che rappresenta parzialmente Dio in questo racconto).
</p><p>Il giudice afferm&ograve;, "Certo, so che la nostra stupenda nazione esiste, e che &egrave; giusta. Per&ograve; qui ci sono io, io sono la giustizia e non qualche entit&agrave; lontana che non si interessa degli affari nel mio paese." Questo &egrave; l'atteggiamento di molti adesso, che credono che Dio esista ed &egrave; buona, ma che lui sia molto distante e che non abbia voce in come devono vivere la propria vita. La risposta del direttore della giustizia &egrave; un'allusione a Marco 12:1-9.
</p><p>Il sacrificio del propiziatore per il giudice &egrave; un parallelo alla morte sacrificale di Ges&ugrave; Cristo per noi. La nostra offesa del Dio onnipotente non dandogli la gloria che gli spetta &egrave; cos&igrave; grande (perch&eacute; Dio &egrave; cos&igrave; grande) che nessuna opera umana potrebbe mai pagare la nostra riconciliazione. In ogni caso, dobbiamo prima cercare di riconciliare il nostro rapporto con Dio prima di pensare a quello degli altri. Solo Dio stesso pu&ograve; pagare un prezzo cos&igrave; alto; solo Ges&ugrave; Cristo, Dio incarnato, l'uomo perfetto, pu&ograve; pagare per noi non dovendo pagare per s&eacute; stesso.
</p><p>Anche se Ges&ugrave; era anche Dio, e voleva fare questo sacrificio per amore di noi, gli costava caro, e i pensieri del propiziatorio su quello che voleva veramente riflettono quelli di Ges&ugrave; nel giardino di Getsemani in Marco 14:32-42.
</p><p>&nbsp;
</p><p>Questo racconto si concentra su quello che fece e pens&ograve; il propiziatore, e le conseguenze per lui. Naturalmente, le sue azioni ebbero un effetto anche sulla vita del giudice. I cambiamenti per il giudice sono approfonditi nel racconto Direttore della Giustizia.
</p><p>&nbsp;
</p><p>La guardia parla proprio cos&igrave;, non sono i miei errori grammaticali! Quando la guardia scrive, fa anche errori di ortografia, che non sono evidenti quando parla e qualcun altro scrive quello che dice. La sua ultima frase &egrave; un riferimento alla dichiarazione della guardia alla croce di Ges&ugrave;, cio&egrave; il centurione che sicuramente non aveva capito tutto ma che disse di Ges&ugrave;, "Veramente, quest'uomo era figlio di Dio!" (Marco 15:39).
</p>
<?
require("../piede.php");
?>
