USE laparola_testo;

DROP TABLE IF EXISTS Studi;
CREATE TABLE Studi (id_s MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, id_a MEDIUMINT UNSIGNED NOT NULL, titolo VARCHAR(255) NOT NULL, libro1 TINYINT UNSIGNED NOT NULL, capitolo1 TINYINT UNSIGNED NOT NULL, versetto1 TINYINT UNSIGNED NOT NULL, libro2 TINYINT UNSIGNED NOT NULL, capitolo2 TINYINT UNSIGNED NOT NULL, versetto2 TINYINT UNSIGNED NOT NULL, testo TEXT, data DATE NOT NULL, indirizzo VARCHAR(255));
ALTER TABLE Studi ADD KEY key_v1(libro1,capitolo1,versetto1);
ALTER TABLE Studi ADD KEY key_v2(libro2,capitolo2,versetto2);
ALTER TABLE Studi ADD KEY key_d(data);

DROP TABLE IF EXISTS Autori;
CREATE TABLE Autori (id_a MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL, nome VARCHAR(255) NOT NULL, password CHAR(16) NOT NULL, email VARCHAR(255) NOT NULL, emailpubblico ENUM('N','S') DEFAULT 'S', sito VARCHAR(255), descrizione TEXT);

DROP TABLE IF EXISTS Voti;
CREATE TABLE Voti (id_s MEDIUMINT UNSIGNED NOT NULL, id_a MEDIUMINT UNSIGNED NOT NULL, voto TINYINT NOT NULL);
ALTER TABLE Voti ADD PRIMARY KEY key_voto(id_s,id_a);

LOAD DATA LOCAL INFILE "studi.txt" INTO TABLE Studi FIELDS TERMINATED BY '|' (id_a,titolo,libro1,capitolo1,versetto1,libro2,capitolo2,versetto2,testo,data,indirizzo);

LOAD DATA LOCAL INFILE "autori.txt" INTO TABLE Autori FIELDS TERMINATED BY '|' (nome,password,email,emailpubblico,sito,descrizione);

LOAD DATA LOCAL INFILE "voti.txt" INTO TABLE Voti FIELDS TERMINATED BY '|' (id_s,id_a,voto);
