//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaParola.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimaDirectory {
            get {
                return ((string)(this["UltimaDirectory"]));
            }
            set {
                this["UltimaDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InterfacciaLingua {
            get {
                return ((string)(this["InterfacciaLingua"]));
            }
            set {
                this["InterfacciaLingua"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maximized")]
        public global::System.Windows.Forms.FormWindowState PrincipaleWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["PrincipaleWindowState"]));
            }
            set {
                this["PrincipaleWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MostraVersioni {
            get {
                return ((string)(this["MostraVersioni"]));
            }
            set {
                this["MostraVersioni"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MostraVersioniScelte {
            get {
                return ((string)(this["MostraVersioniScelte"]));
            }
            set {
                this["MostraVersioniScelte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FormatoFontNome {
            get {
                return ((string)(this["FormatoFontNome"]));
            }
            set {
                this["FormatoFontNome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float FormatoFontDimensione {
            get {
                return ((float)(this["FormatoFontDimensione"]));
            }
            set {
                this["FormatoFontDimensione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontStileGrassetto {
            get {
                return ((bool)(this["FormatoFontStileGrassetto"]));
            }
            set {
                this["FormatoFontStileGrassetto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontStileCorsivo {
            get {
                return ((bool)(this["FormatoFontStileCorsivo"]));
            }
            set {
                this["FormatoFontStileCorsivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontStileSotto {
            get {
                return ((bool)(this["FormatoFontStileSotto"]));
            }
            set {
                this["FormatoFontStileSotto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LibriAbbUsate {
            get {
                return ((string)(this["LibriAbbUsate"]));
            }
            set {
                this["LibriAbbUsate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LibriNomi {
            get {
                return ((string)(this["LibriNomi"]));
            }
            set {
                this["LibriNomi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LibriAbbRiconosciute {
            get {
                return ((string)(this["LibriAbbRiconosciute"]));
            }
            set {
                this["LibriAbbRiconosciute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FormatoFontRifNome {
            get {
                return ((string)(this["FormatoFontRifNome"]));
            }
            set {
                this["FormatoFontRifNome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float FormatoFontRifDimensione {
            get {
                return ((float)(this["FormatoFontRifDimensione"]));
            }
            set {
                this["FormatoFontRifDimensione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FormatoFontRifStileGrassetto {
            get {
                return ((bool)(this["FormatoFontRifStileGrassetto"]));
            }
            set {
                this["FormatoFontRifStileGrassetto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontRifStileCorsivo {
            get {
                return ((bool)(this["FormatoFontRifStileCorsivo"]));
            }
            set {
                this["FormatoFontRifStileCorsivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontRifStileSotto {
            get {
                return ((bool)(this["FormatoFontRifStileSotto"]));
            }
            set {
                this["FormatoFontRifStileSotto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FormatoRifTipo {
            get {
                return ((int)(this["FormatoRifTipo"]));
            }
            set {
                this["FormatoRifTipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FormatoRifPosto {
            get {
                return ((int)(this["FormatoRifPosto"]));
            }
            set {
                this["FormatoRifPosto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FormatoRifFormato {
            get {
                return ((int)(this["FormatoRifFormato"]));
            }
            set {
                this["FormatoRifFormato"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoRifApice {
            get {
                return ((bool)(this["FormatoRifApice"]));
            }
            set {
                this["FormatoRifApice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FormatoTestoBibbia {
            get {
                return ((int)(this["FormatoTestoBibbia"]));
            }
            set {
                this["FormatoTestoBibbia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpzioniPanello {
            get {
                return ((string)(this["OpzioniPanello"]));
            }
            set {
                this["OpzioniPanello"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimaBibbia {
            get {
                return ((string)(this["UltimaBibbia"]));
            }
            set {
                this["UltimaBibbia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImportaDirectory {
            get {
                return ((string)(this["ImportaDirectory"]));
            }
            set {
                this["ImportaDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RicercaVersione {
            get {
                return ((string)(this["RicercaVersione"]));
            }
            set {
                this["RicercaVersione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RicercaRicerchePrecedenti {
            get {
                return ((string)(this["RicercaRicerchePrecedenti"]));
            }
            set {
                this["RicercaRicerchePrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MostraBraniPrecedenti {
            get {
                return ((string)(this["MostraBraniPrecedenti"]));
            }
            set {
                this["MostraBraniPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MiscRichiesteMemorizzate {
            get {
                return ((int)(this["MiscRichiesteMemorizzate"]));
            }
            set {
                this["MiscRichiesteMemorizzate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrincipaleSfogliaBraniPrecedenti {
            get {
                return ((string)(this["PrincipaleSfogliaBraniPrecedenti"]));
            }
            set {
                this["PrincipaleSfogliaBraniPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Size PrincipaleWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["PrincipaleWindowSize"]));
            }
            set {
                this["PrincipaleWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point PrincipaleWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["PrincipaleWindowLocation"]));
            }
            set {
                this["PrincipaleWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImportaFilePrecedenti {
            get {
                return ((string)(this["ImportaFilePrecedenti"]));
            }
            set {
                this["ImportaFilePrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float FormatoFontRicercaDimensione {
            get {
                return ((float)(this["FormatoFontRicercaDimensione"]));
            }
            set {
                this["FormatoFontRicercaDimensione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FormatoFontRicercaNome {
            get {
                return ((string)(this["FormatoFontRicercaNome"]));
            }
            set {
                this["FormatoFontRicercaNome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FormatoFontRicercaStileSotto {
            get {
                return ((bool)(this["FormatoFontRicercaStileSotto"]));
            }
            set {
                this["FormatoFontRicercaStileSotto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontRicercaStileCorsivo {
            get {
                return ((bool)(this["FormatoFontRicercaStileCorsivo"]));
            }
            set {
                this["FormatoFontRicercaStileCorsivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontRicercaStileGrassetto {
            get {
                return ((bool)(this["FormatoFontRicercaStileGrassetto"]));
            }
            set {
                this["FormatoFontRicercaStileGrassetto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrincipaleSfogliaRicerchePrecedenti {
            get {
                return ((string)(this["PrincipaleSfogliaRicerchePrecedenti"]));
            }
            set {
                this["PrincipaleSfogliaRicerchePrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrincipaleBarraDiStato {
            get {
                return ((bool)(this["PrincipaleBarraDiStato"]));
            }
            set {
                this["PrincipaleBarraDiStato"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpzioniStessaFinestra {
            get {
                return ((bool)(this["OpzioniStessaFinestra"]));
            }
            set {
                this["OpzioniStessaFinestra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImportaDirectoryPrecedenti {
            get {
                return ((string)(this["ImportaDirectoryPrecedenti"]));
            }
            set {
                this["ImportaDirectoryPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImportaXMLDirectory {
            get {
                return ((string)(this["ImportaXMLDirectory"]));
            }
            set {
                this["ImportaXMLDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FormatoFontColore {
            get {
                return ((global::System.Drawing.Color)(this["FormatoFontColore"]));
            }
            set {
                this["FormatoFontColore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FormatoFontRifColore {
            get {
                return ((global::System.Drawing.Color)(this["FormatoFontRifColore"]));
            }
            set {
                this["FormatoFontRifColore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FormatoFontRicercaColore {
            get {
                return ((global::System.Drawing.Color)(this["FormatoFontRicercaColore"]));
            }
            set {
                this["FormatoFontRicercaColore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Commentari {
            get {
                return ((string)(this["Commentari"]));
            }
            set {
                this["Commentari"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpzioniIpertestoTooltip {
            get {
                return ((bool)(this["OpzioniIpertestoTooltip"]));
            }
            set {
                this["OpzioniIpertestoTooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChiaveVersione {
            get {
                return ((string)(this["ChiaveVersione"]));
            }
            set {
                this["ChiaveVersione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChiaveBraniPrecedenti {
            get {
                return ((string)(this["ChiaveBraniPrecedenti"]));
            }
            set {
                this["ChiaveBraniPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChiaveIpertesto {
            get {
                return ((bool)(this["ChiaveIpertesto"]));
            }
            set {
                this["ChiaveIpertesto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChiaveOrdine {
            get {
                return ((int)(this["ChiaveOrdine"]));
            }
            set {
                this["ChiaveOrdine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChiaveParoleRadici {
            get {
                return ((int)(this["ChiaveParoleRadici"]));
            }
            set {
                this["ChiaveParoleRadici"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ChiaveNumeroMinimo {
            get {
                return ((int)(this["ChiaveNumeroMinimo"]));
            }
            set {
                this["ChiaveNumeroMinimo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChiaveNonRadiciComuni {
            get {
                return ((bool)(this["ChiaveNonRadiciComuni"]));
            }
            set {
                this["ChiaveNonRadiciComuni"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string ChiaveRadiciComuni {
            get {
                return ((string)(this["ChiaveRadiciComuni"]));
            }
            set {
                this["ChiaveRadiciComuni"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimaDirectoryImmagini {
            get {
                return ((string)(this["UltimaDirectoryImmagini"]));
            }
            set {
                this["UltimaDirectoryImmagini"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfoPrecedenti {
            get {
                return ((string)(this["InfoPrecedenti"]));
            }
            set {
                this["InfoPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrincipaleComandiPrecedenti {
            get {
                return ((string)(this["PrincipaleComandiPrecedenti"]));
            }
            set {
                this["PrincipaleComandiPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrincipaleBSPrincipale {
            get {
                return ((bool)(this["PrincipaleBSPrincipale"]));
            }
            set {
                this["PrincipaleBSPrincipale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrincipaleBSFormato {
            get {
                return ((bool)(this["PrincipaleBSFormato"]));
            }
            set {
                this["PrincipaleBSFormato"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrincipaleBSOrdine {
            get {
                return ((bool)(this["PrincipaleBSOrdine"]));
            }
            set {
                this["PrincipaleBSOrdine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrincipaleBSComando {
            get {
                return ((bool)(this["PrincipaleBSComando"]));
            }
            set {
                this["PrincipaleBSComando"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CartelleDaCercare {
            get {
                return ((string)(this["CartelleDaCercare"]));
            }
            set {
                this["CartelleDaCercare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FormatoFontGrecoNome {
            get {
                return ((string)(this["FormatoFontGrecoNome"]));
            }
            set {
                this["FormatoFontGrecoNome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float FormatoFontGrecoDimensione {
            get {
                return ((float)(this["FormatoFontGrecoDimensione"]));
            }
            set {
                this["FormatoFontGrecoDimensione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FormatoFontGrecoColore {
            get {
                return ((global::System.Drawing.Color)(this["FormatoFontGrecoColore"]));
            }
            set {
                this["FormatoFontGrecoColore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontGrecoStileCorsivo {
            get {
                return ((bool)(this["FormatoFontGrecoStileCorsivo"]));
            }
            set {
                this["FormatoFontGrecoStileCorsivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontGrecoStileGrassetto {
            get {
                return ((bool)(this["FormatoFontGrecoStileGrassetto"]));
            }
            set {
                this["FormatoFontGrecoStileGrassetto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontGrecoStileSotto {
            get {
                return ((bool)(this["FormatoFontGrecoStileSotto"]));
            }
            set {
                this["FormatoFontGrecoStileSotto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Times New Roman")]
        public string FormatoFontEbraicoNome {
            get {
                return ((string)(this["FormatoFontEbraicoNome"]));
            }
            set {
                this["FormatoFontEbraicoNome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public float FormatoFontEbraicoDimensione {
            get {
                return ((float)(this["FormatoFontEbraicoDimensione"]));
            }
            set {
                this["FormatoFontEbraicoDimensione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color FormatoFontEbraicoColore {
            get {
                return ((global::System.Drawing.Color)(this["FormatoFontEbraicoColore"]));
            }
            set {
                this["FormatoFontEbraicoColore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontEbraicoStileCorsivo {
            get {
                return ((bool)(this["FormatoFontEbraicoStileCorsivo"]));
            }
            set {
                this["FormatoFontEbraicoStileCorsivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontEbraicoStileGrassetto {
            get {
                return ((bool)(this["FormatoFontEbraicoStileGrassetto"]));
            }
            set {
                this["FormatoFontEbraicoStileGrassetto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoFontEbraicoStileSotto {
            get {
                return ((bool)(this["FormatoFontEbraicoStileSotto"]));
            }
            set {
                this["FormatoFontEbraicoStileSotto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AggiornamentoManuale {
            get {
                return ((bool)(this["AggiornamentoManuale"]));
            }
            set {
                this["AggiornamentoManuale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int AggiornamentoGiorni {
            get {
                return ((int)(this["AggiornamentoGiorni"]));
            }
            set {
                this["AggiornamentoGiorni"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2006-01-01")]
        public global::System.DateTime AggiornamentoUltimo {
            get {
                return ((global::System.DateTime)(this["AggiornamentoUltimo"]));
            }
            set {
                this["AggiornamentoUltimo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AggiornamentoTestiNascosti {
            get {
                return ((string)(this["AggiornamentoTestiNascosti"]));
            }
            set {
                this["AggiornamentoTestiNascosti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DizionarioInglese {
            get {
                return ((string)(this["DizionarioInglese"]));
            }
            set {
                this["DizionarioInglese"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DizionarioItaliano {
            get {
                return ((string)(this["DizionarioItaliano"]));
            }
            set {
                this["DizionarioItaliano"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DizionarioGreco {
            get {
                return ((string)(this["DizionarioGreco"]));
            }
            set {
                this["DizionarioGreco"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DizionarioEbraico {
            get {
                return ((string)(this["DizionarioEbraico"]));
            }
            set {
                this["DizionarioEbraico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DizionarioTooltip {
            get {
                return ((bool)(this["DizionarioTooltip"]));
            }
            set {
                this["DizionarioTooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AggiornamentoProxyHost {
            get {
                return ((string)(this["AggiornamentoProxyHost"]));
            }
            set {
                this["AggiornamentoProxyHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AggiornamentoProxyPorta {
            get {
                return ((int)(this["AggiornamentoProxyPorta"]));
            }
            set {
                this["AggiornamentoProxyPorta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AggiornamentoProxyNomeUtente {
            get {
                return ((string)(this["AggiornamentoProxyNomeUtente"]));
            }
            set {
                this["AggiornamentoProxyNomeUtente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AggiornamentoProxyPassword {
            get {
                return ((string)(this["AggiornamentoProxyPassword"]));
            }
            set {
                this["AggiornamentoProxyPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AggiornamentoProxyDominio {
            get {
                return ((string)(this["AggiornamentoProxyDominio"]));
            }
            set {
                this["AggiornamentoProxyDominio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimaBibbiaCompleta {
            get {
                return ((string)(this["UltimaBibbiaCompleta"]));
            }
            set {
                this["UltimaBibbiaCompleta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LetturaUltima {
            get {
                return ((string)(this["LetturaUltima"]));
            }
            set {
                this["LetturaUltima"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LetturaGiorniOffset {
            get {
                return ((int)(this["LetturaGiorniOffset"]));
            }
            set {
                this["LetturaGiorniOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LetturaVersione {
            get {
                return ((string)(this["LetturaVersione"]));
            }
            set {
                this["LetturaVersione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LetturaAvvio {
            get {
                return ((bool)(this["LetturaAvvio"]));
            }
            set {
                this["LetturaAvvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MiscNuovaVersione {
            get {
                return ((bool)(this["MiscNuovaVersione"]));
            }
            set {
                this["MiscNuovaVersione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MiscArrangementDefault {
            get {
                return ((string)(this["MiscArrangementDefault"]));
            }
            set {
                this["MiscArrangementDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MiscArrangementDefaultType {
            get {
                return ((int)(this["MiscArrangementDefaultType"]));
            }
            set {
                this["MiscArrangementDefaultType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DizionarioLatino {
            get {
                return ((string)(this["DizionarioLatino"]));
            }
            set {
                this["DizionarioLatino"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("highlighter")]
        public string EvidenziaTipo {
            get {
                return ((string)(this["EvidenziaTipo"]));
            }
            set {
                this["EvidenziaTipo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color EvidenziaColore {
            get {
                return ((global::System.Drawing.Color)(this["EvidenziaColore"]));
            }
            set {
                this["EvidenziaColore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrincipaleFontPreferiti {
            get {
                return ((string)(this["PrincipaleFontPreferiti"]));
            }
            set {
                this["PrincipaleFontPreferiti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RicercaBraniPrecedenti {
            get {
                return ((string)(this["RicercaBraniPrecedenti"]));
            }
            set {
                this["RicercaBraniPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|||||||||")]
        public string SegnalibriVeloci {
            get {
                return ((string)(this["SegnalibriVeloci"]));
            }
            set {
                this["SegnalibriVeloci"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PrincipaleClipboardTempo {
            get {
                return ((int)(this["PrincipaleClipboardTempo"]));
            }
            set {
                this["PrincipaleClipboardTempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PrincipaleClipboardLunghezzaMassima {
            get {
                return ((int)(this["PrincipaleClipboardLunghezzaMassima"]));
            }
            set {
                this["PrincipaleClipboardLunghezzaMassima"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrincipaleClipboardAttivo {
            get {
                return ((bool)(this["PrincipaleClipboardAttivo"]));
            }
            set {
                this["PrincipaleClipboardAttivo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImportaEswordPrecedenti {
            get {
                return ((string)(this["ImportaEswordPrecedenti"]));
            }
            set {
                this["ImportaEswordPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImportaEswordDirectory {
            get {
                return ((string)(this["ImportaEswordDirectory"]));
            }
            set {
                this["ImportaEswordDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoInstallati {
            get {
                return ((string)(this["VideoInstallati"]));
            }
            set {
                this["VideoInstallati"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChiaveConRiferimenti {
            get {
                return ((bool)(this["ChiaveConRiferimenti"]));
            }
            set {
                this["ChiaveConRiferimenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PrincipaleMassimoVociMenu {
            get {
                return ((int)(this["PrincipaleMassimoVociMenu"]));
            }
            set {
                this["PrincipaleMassimoVociMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-9999")]
        public int ReadingsLocationX {
            get {
                return ((int)(this["ReadingsLocationX"]));
            }
            set {
                this["ReadingsLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ListaTestiFormato {
            get {
                return ((int)(this["ListaTestiFormato"]));
            }
            set {
                this["ListaTestiFormato"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ListaTestiOrdine {
            get {
                return ((int)(this["ListaTestiOrdine"]));
            }
            set {
                this["ListaTestiOrdine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1|2|4|10")]
        public string ListaTestiColonneSelezionate {
            get {
                return ((string)(this["ListaTestiColonneSelezionate"]));
            }
            set {
                this["ListaTestiColonneSelezionate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-9999")]
        public int ReadingsLocationY {
            get {
                return ((int)(this["ReadingsLocationY"]));
            }
            set {
                this["ReadingsLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadingsSizeX {
            get {
                return ((int)(this["ReadingsSizeX"]));
            }
            set {
                this["ReadingsSizeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReadingsSizeY {
            get {
                return ((int)(this["ReadingsSizeY"]));
            }
            set {
                this["ReadingsSizeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EsportaVersione {
            get {
                return ((string)(this["EsportaVersione"]));
            }
            set {
                this["EsportaVersione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EsportaTipoBibbia {
            get {
                return ((int)(this["EsportaTipoBibbia"]));
            }
            set {
                this["EsportaTipoBibbia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EsportaTipoCollezione {
            get {
                return ((int)(this["EsportaTipoCollezione"]));
            }
            set {
                this["EsportaTipoCollezione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EsportaDirectory {
            get {
                return ((string)(this["EsportaDirectory"]));
            }
            set {
                this["EsportaDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpzioniIpertestoTooltipInTooltip {
            get {
                return ((bool)(this["OpzioniIpertestoTooltipInTooltip"]));
            }
            set {
                this["OpzioniIpertestoTooltipInTooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MostraAlterna {
            get {
                return ((bool)(this["MostraAlterna"]));
            }
            set {
                this["MostraAlterna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FormatoTitoliVisualizzati {
            get {
                return ((bool)(this["FormatoTitoliVisualizzati"]));
            }
            set {
                this["FormatoTitoliVisualizzati"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FormatoRifContestoRicerche {
            get {
                return ((bool)(this["FormatoRifContestoRicerche"]));
            }
            set {
                this["FormatoRifContestoRicerche"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MostraDefinizioni {
            get {
                return ((bool)(this["MostraDefinizioni"]));
            }
            set {
                this["MostraDefinizioni"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChiaveDefinizioni {
            get {
                return ((bool)(this["ChiaveDefinizioni"]));
            }
            set {
                this["ChiaveDefinizioni"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SimiliVersione {
            get {
                return ((string)(this["SimiliVersione"]));
            }
            set {
                this["SimiliVersione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SimiliBraniPrecedenti {
            get {
                return ((string)(this["SimiliBraniPrecedenti"]));
            }
            set {
                this["SimiliBraniPrecedenti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SimiliVersetti {
            get {
                return ((bool)(this["SimiliVersetti"]));
            }
            set {
                this["SimiliVersetti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SimiliNumeroMassimo {
            get {
                return ((int)(this["SimiliNumeroMassimo"]));
            }
            set {
                this["SimiliNumeroMassimo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DizionarioSpagnolo {
            get {
                return ((string)(this["DizionarioSpagnolo"]));
            }
            set {
                this["DizionarioSpagnolo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QuizGiusto {
            get {
                return ((int)(this["QuizGiusto"]));
            }
            set {
                this["QuizGiusto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QuizSbagliato {
            get {
                return ((int)(this["QuizSbagliato"]));
            }
            set {
                this["QuizSbagliato"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MostraAltezza {
            get {
                return ((int)(this["MostraAltezza"]));
            }
            set {
                this["MostraAltezza"] = value;
            }
        }
    }
}
