<?
$descriz = "Guida allo studio della Bibbia: Altri libri profetici prima dell'esilio";
$key = "pentateuco,sommario,studio,studio biblico,guida,McGarvey";
$titolo = "Guida allo studio della Bibbia 9. Altri libri profetici prima dell'esilio";
$sezione = "Articoli";
$sezioneurl = "/intro/";
require("../capo.php");
include("../funzioni.php");
?>
<h1><a href="guida_studio_bibbia.php">Guida allo studio della Bibbia</a></h1>

<h2>9. Altri libri profetici prima dell'esilio</h2>
<p>Nel precedente riassunto storico abbiamo tralasciato alcuni libri, che possono essere considerati meglio in sezioni separate. Prima di tutto, i libri profetici. Ce ne sono sette, e ne parleremo in ordine cronologico (per quanto &egrave; possibile determinarlo).</p>
<h3>1. Michea</h3>
<p>Il ministero di questo profeta fu nei regni di Iotam, Acaz e Ezechia; fu quindi contemporaneo con Isaia, che profetizz&ograve; sotto gli stessi re. Chiam&ograve; il suo libro "Parola del Signore, rivolta a Michea, il Morastita. Visione che egli ebbe riguardo a Samaria e a Gerusalemme" (Michea 1:1). Predice la caduta di tutte e due le citt&agrave;, e rimprovera la gente per i peccati che stanno portando la loro distruzione. Predice anche la restaurazione del popolo, ed &egrave; lui che proferisce la chiara profezia della citt&agrave; di nascita di Ges&ugrave; Cristo, e che fu citata ad Erode dagli scribi quando i magi arrivarono a Gerusalemme (Matteo 2:1-6, Marco 5:1-2). Siccome profetizz&ograve; per cos&igrave; tanto tempo, &egrave; quasi certo che il suo piccolo libro contenga solo una piccola parte dei suoi oracoli profetici.</p>
<h3>2. Naum</h3>
<p>Questo scrittore non ci dice quando profetizz&ograve;, ma il suo libro si chiama, "Oracolo su Ninive" (Naum 1:1), ed &egrave; una profezia della caduta e desolazione di quella antica citt&agrave;. Fu pronunciata dopo che gli Assiri (di cui Ninive era la capitale) ebbero invaso Giuda per l'ultima volta (Naum 1:9-15), e ci&ograve; fu fatto da Sennacherib nel regno di Ezechia. Fra questo e la caduta di Ninive 20 anni dopo (nel 625 a.C.) Naum profetizz&ograve;; non possiamo fissare la data della scrittura del libro pi&ugrave; precisamente. Il suo piccolo libro apre con un magnifico tributo alla maest&agrave; e potenza di Geova, e la sua descrizione della battaglia dell'ultimo assedio di Ninive &egrave; cos&igrave; vivida da sembrare una di un testimone oculare.</p>
<h3>3. Abacuc</h3>
<p>Questo profeta, come Naum, non ci dice quando profetizz&ograve;; ma le sue prime frasi dimostrano che era in un periodo di generale empiet&agrave;, e quando l'invasione dei Caldei, che predice, sarebbe successo nella vita di colui a chi parla. Ci&ograve; corrisponde al periodo malvagio nell'ultima parte del regno di Manasse o all'inizio di quello di Giosia, perch&eacute; fu un periodo di empiet&agrave; e ci volevano solo da 25 a 40 anni prima dell'invasione dei Caldei. Allora i Caldei erano ancora sottomessi agli Assiri, e non c'era una possibilit&agrave; umana che diventassero potenti. La preghiera di Abacuc, che si trova nell'ultima parte del suo libro (Abacuc 3:1-19), &egrave; una delle espressioni pi&ugrave; pie nell'intera Bibbia.</p>
<h3>4. Sofonia</h3>
<p>Questo profeta spiega la sua genealogia andando indietro di quattro generazioni, fino a Ezechia; e siccome l'unico uomo importante di quel nome era il re Ezechia, si suppone che il profeta appartenesse alla famiglia reale. Profetizz&ograve; durante il regno di Giosia (Sofonia 1:1), ma non &egrave; scritto in quale parte del regno. Se &egrave; stato nei primi 13 anni precedette Geremia (Geremia 1:2), e ci&ograve; &egrave; quasi certo quando consideriamo il contenuto del suo libro, perch&eacute; descrive varie forme di idolatria che la gente di Gerusalemme e di Giuda faceva (Sofonia 1:4-6), e che furono abolite da Giosia nel dodicesimo anno del suo regno. I primi due capitoli e una parte del terzo denunciano Gerusalemme per le sue iniquit&agrave; e predicono giudizi distruttivi che verranno per questo motivo. Anche le nazioni adiacenti sono incluse, soprattutto quelle che erano state nemiche dei Giudei. L'ultima met&agrave; del terzo capitolo contiene una predizione della liberazione d'Israele dalle calamit&agrave; imminenti e della prosperit&agrave; futura. Siccome il popolo ascolt&ograve; questo appello profetico nella prima parte del regno di Giosia, il quale veniva dalle labbra di un parente del re, &egrave; probabile che influenzasse grandemente il re affinch&eacute; intraprendesse la riforma di cui il suo regno &egrave; noto. Il libro andrebbe letto dopo aver letto dei regni di Manasse e di Amon (2Re 21:1-26; 2Cronache 33:1-25), e prima di leggere quello di Giosia (2Re 22:1-23:30; 2Cronache 34:1-35:27). Esamina da vicino lo stato della societ&agrave; quando Giosia cominci&ograve; a regnare (quando aveva 12 anni), ed aiuta a spiegare il fatto sorprendente che sebbene suo padre e suo nonno fossero idolatri e commisero molte azioni malvagie, lui intraprese un cammino contrario rovesciando l'idolatria che avevano stabilito e riportando la gente all'adorazione di Geova.</p>
<h3>5. Abdia</h3>
<p>Questo libro molto breve &egrave; intitolato "Visione di Abdia" (Abdia 1). Non abbiamo informazioni sulla storia personale di questo profeta. La prima parte del libro (Abdia 1-16) &egrave; una denuncia ad Edom per l'animosit&agrave; che aveva mostrato verso i Giudei quando Gerusalemme fu distrutta dai Caldei sotto Nabucodonosor, e una predizione di punizione per questo nemico innaturale verso un popolo imparentato con loro. Fu quindi scritto dopo quell'evento e prima della punizione predetta. Una simile denuncia di Edom da parte di Geremia (Geremia 49:7-22) contiene alcune delle stesse frase utilizzate da Abdia, dimostrando che uno di questi profeti copi&ograve; dall'altro. Siccome scrissero in quasi esattamente lo stesso periodo, non &egrave; possibile sapere quale dei due copi&ograve;.
</p><p>
Nel resto del libro c'&egrave; una profezia della conquista di Edom da parte dei Giudei (Abdia 17-21), che fu adempiuta dopo il ritorno dai Giudei dall'esilio in Babilonia. Ezechiele, che era pure un contemporaneo di Abdia, ha una profezia simile (Ezechiele 25:12-14).
</p><p>
Non &egrave; detto niente di questa ostilit&agrave; di Edom nei libri storici, ma appare non solo negli scritti di questi tre profeti ma anche nel Salmo 137, scritto in cattivit&agrave; o poco dopo la sua fine, in cui l'autore dice:<br />
"Ric&ograve;rdati, Signore, dei figli di Edom,<br />
che nel giorno di Gerusalemme<br />
dicevano: &laquo;Spianatela, spianatela,<br />
fin dalle fondamenta!&raquo;" (Salmo 137:7)</p>
<h3>6. Ezechiele</h3>
<p>Questo profeta, come Geremia, era un sacerdote (Ezechiele 1:3). Fu chiamato ad essere profeta nel quinto anno della cattivit&agrave; del re Ioiachin, che corrisponde con il quinto anno del regno di Sedechia, l'ultimo re di Gerusalemme. Era in quel tempo fra i prigionieri nel paese dei Caldei (Ezechiele 1:3), e senza dubbio era uno di quelli portati via con Ioiachin da Nabucodonosor. Quando inizi&ograve; a profetizzare, Geremia profetizzava gi&agrave; da 30 anni; e siccome Ezechiele aveva allora 30 anni (Ezechiele 1:1), era cresciuto con l'insegnamento di Geremia. Continu&ograve; a profetizzare fino al ventisettesimo anno della cattivit&agrave; di Ioiachin (Ezechiele 29:17), e forse di pi&ugrave;. I suoi primi sei o sette anni si sovrapposero agli ultimi di Geremia, e durante quel periodo lavoravano insieme, uno a Gerusalemme e l'altro vicino a Babilonia, e tutti e due predicevano la caduta del regno di Giuda e esortavano il popolo a ravvedersi. La prima met&agrave; del libro di Ezechiele, cio&egrave; 24 dei suoi 48 libri, parla di questo. Utilizza moltissimi simboli strani, con parole e con azioni, ed alcuni di cui sono molto difficili da interpretare. Ma insegna anche in modo molto semplice alcune lezioni di grande importanza, non solo per la sua epoca ma anche per ogni generazione dell'umanit&agrave;. Il lettore distinguer&agrave; facilmente i capitoli che contengono queste lezioni, e dovrebbe studiarli fino a quando diventano molto familiari.
</p><p>
La seconda met&agrave; del libro contiene predizioni che riguardano la ristorazione di Israele e di Giuda, e il loro futuro nel proprio paese. In questa parte ci sono descrizioni e simboli ancora pi&ugrave; misteriosi che nella prima parte; alcuni di cui non sono mai stati interpretati in modo soddisfacente. Come gli altri profeti, d&agrave; poche informazioni sulla sua storia personale, e non si sa niente per quanto riguardo la sua morte. Se avesse vissuto fino all'et&agrave; di 100 anni avrebbe visto la fine della cattivit&agrave;; ma siccome ci&ograve; &egrave; molto improbabile, probabilmente mor&igrave; in Babilonia.</p>
<h3>7. Gioele</h3>
<p>Non si sa niente della storia personale di Gioele, tranne che era il figlio Petuel (Gioele 1:1). Diversamente dalla maggior parte dei profeti, non dice in quale regno o regni profetizz&ograve;, e cos&igrave; le indicazioni di data nel suo libro sono cos&igrave; indefinite che i commentatori si differiscono molto per quanto riguardo la data di scrittura; alcuni dicono che &egrave; fra i primi, altri fra gli ultimi dei profeti. Fortunatamente, il valore del libro per noi non dipende dalla data esatta.
</p><p>
La prima parte del libro (Gioele 1:1-11, 17) contiene una predizione di un'invasione di locuste pi&ugrave; grande di quelle mai viste da generazioni precedenti nel paese di Giuda (Gioele 1:2-3). La descrizione &egrave; molto vivida, come se la scena passasse davanti agli occhi del profeta. Il linguaggio utilizzato in diverse parti della descrizione &egrave; tale da far capire ad alcuni interpreti che tutto sia un'immagine simbolica di eserciti umani.
</p><p>
Dopo questa invasione il profeta predice una condizione prospera per il paese (Gioele 2:17-27), e poi lo spargimento dello Spirito Santo. L'apostolo Pietro nel giorno della Pentecoste cit&ograve; la profezia, affermando che era allora in parte adempiuta (Gioele 2:28-32; confronta Atti 2:16-31). Questa &egrave; la caratteristica pi&ugrave; notevole della profezia di Gioele. Gli fu dato fra tutti i profeti di fare la profezia pi&ugrave; chiara del grand'evento che inaugur&ograve; il regno di Dio sulla terra.
</p><p>
Il resto del libro contiene una profezia del giudizio di Dio sulle nazioni che circondavano Giuda per le crudelt&agrave; che avevano versato su quel popolo. Il libro non menziona affatto il regno di Israele, e questo fatto, insieme a quello che tutti i riferimenti locali sono a Giuda, dimostrano che il profeta viveva nel regno meridionale. Non c'&egrave; un periodo particolare della storia a cui il libro si riferisce.
</p>
<p><a href="guida_domande.php#9">Domande di ripasso</a></p>
<p>Continua: <a href="libri_poetici.php">10. I libri poetici</a></p>
<?
require("../piede.php");
?>