<?
$descriz = "Guida allo studio della Bibbia: Le epistole cattoliche e l'Apocalisse";
$key = "epistole cattoliche,epistole,lettere,lettere cattoliche,apocalisse,giacomo,pietro,giovanni,giuda,studio,studio biblico,guida,McGarvey";
$titolo = "Guida allo studio della Bibbia 16. Le epistole cattoliche e l'Apocalisse";
$sezione = "Articoli";
$sezioneurl = "/intro/";
require("../capo.php");
include("../funzioni.php");
?>
<h1><a href="guida_studio_bibbia.php">Guida allo studio della Bibbia</a></h1>

<h2>16. Le epistole cattoliche e l'Apocalisse</h2>
<p>
La parola "cattolica" significa universale, nel senso che queste lettere sono indirizzate a tutti e non a una sola persona o una chiesa. 2Giovanni e 3Giovanni sono incluse in questa categoria, bench&eacute; indirizzata ad un individuo, perch&eacute; non si voleva classificarle separatamente da 1Giovanni. Ci sono quindi sette epistole cattoliche, di cui parleremo ora nell'ordine in cui le troviamo nella Bibbia.
</p>
<h3>1. Giacomo</h3>
<p>
C'erano tre discepoli eminenti chiamati Giacomo: gli apostoli Giacomo figlio di Zebedeo e Giacomo figlio di Alfeo, e Giacomo il fratello del Signore. Si crede che fosse l'ultimo menzionato l'autore dell'epistola. Dal tempo della carcerazione di Pietro da parte di Erode nel 44 d.C., fino alla morte di Giacomo nel 62, sembra che abitasse continuamente nella citt&agrave; di Gerusalemme come capo di quella chiesa nell'assenza degli apostoli (Atti 12:17; 15:13; 21:17-18; Galati 1:18-19; 2:9-12).
<p></p>
L'epistola &egrave; scritta "alle dodici trib&ugrave; che sono disperse nel mondo", che significa quelli delle 12 trib&ugrave; dispersi in paesi oltre la Palestina (Giacomo 1:1). Il contenuto dell'epistola dimostra che erano i Cristiani giudei della dispersione. C'erano pochi tali Cristiani fino a quando gli apostoli avevano predicato per molti anni e fatto molti convertiti in molti paesi. Di conseguenza la data dell'epistola doveva essere vicina alla fine della vita di Giacomo, ma &egrave; impossibile sapere esattamente in quale anno. I fratelli che hanno ricevuto la lettera subivano la persecuzione, e lo scopo dello scrittore era di incoraggiarli a pazientemente sopportare le loro afflizioni. Questo scopo pervade l'epistola. Allo stesso tempo molti avvertimenti e ammonimenti sono introdotti, i quali sono adatti a tutti i tempi e luoghi. L'epistola &egrave; nota in modo particolare per la lezione sul controllo della lingua. Tocca anche brevemente il tema della giustificazione, dimostrando che non siamo giustificati da opere della legge, come anche Paolo abbondantemente insegna, la giustificazione risulta in quelle opere che appartengono all'ubbidienza della fede.
<p></p>
L'epistola &egrave; sempre stata ammirata per l'eleganza dello stile in cui &egrave; scritta, essendo superiore in questo aspetto agli altri scritti del Nuovo Testamento.
</p>
<h3>2. Prima Pietro</h3>
<p>
Pietro si rivolge in parte agli stessi discepoli a cui Giacomo scrive. Sono "forestieri dispersi nel Ponto, nella Galazia, nella Cappadocia, nell'Asia e nella Bitinia" (1Pietro 1:1). Queste erano le province settentrionali e occidentali di quello che adesso chiamiamo la Turchia, ed erano incluse nella dispersione pi&ugrave; generale menzionata da Giacomo. Le province furono evangelizzate da Paolo e dai suoi colleghi. Lo scopo principale dell'epistola &egrave; simile a quello di Giacomo, cio&egrave; di incoraggiare questi fratelli a sopportare la persecuzione che stavano subendo, e per prepararli alle persecuzioni future. Il sentimento dell'epistola rivela una maturit&agrave; di carattere cristiano che rende Pietro diverso da come &egrave; descritto nei Vangeli. Qualcuno che lo conosceva solo dai Vangeli lo riconoscerebbe a stento; questo fatto &egrave; una forte evidenza della potenza trasformatrice di una vita cristiana.
</p>
<h3>3. Seconda Pietro</h3>
<p>
In questa epistola l'apostolo si rivolge alle stesse persone, e per lo pi&ugrave; con lo stesso scopo (2Pietro 3:1-2). &Egrave; notevole soprattutto per due predizioni che contiene, la prima nel secondo capitolo riguardo ai falsi insegnanti che sarebbero venuti nella chiesa, e la seconda, nel terzo capitolo, tratta la venuta di Cristo in giudizio e la distruzione del cielo e della terra attuali.
<p></p>
Molti scrittori, sia antichi, sia moderni, hanno espresso dubbi sulla genuinit&agrave; di questa epistola, ma i loro ragionamenti non sono mai riusciti a convincere la maggioranza dei credenti. Dalla prima fino all'ultima parola &egrave; degna della penna di un apostolo, e nessuna epistola pi&ugrave; positivamente afferma chi &egrave; il suo autore.
</p>
<h3>4. Prima Giovanni</h3>
<p>
Questa epistola non &egrave; rivolta ad un gruppo particolare di discepoli, e quindi nel senso pi&ugrave; stretto &egrave; cattolica o generale. Dopo il primo paragrafo, in cui lo scrittore spiega in modo enfatico la pienezza della testimonianza apostolica alla risurrezione di Ges&ugrave;, l'epistola &egrave; piena di esortazioni ad evitare il peccato e di amarsi l'uno l'altro. Il dovere di amare &egrave; qui pi&ugrave; ripetuto che in qualsiasi altra porzione del Nuovo Testamento, e questo ha portato alcuni a descrivere Giovanni come 'apostolo dell'amore'. Era evidentemente molto vecchio quando la scrisse, perch&eacute; si rivolge a tutti i discepoli, di qualsiasi et&agrave;, come "figlioli" e "figlioli miei" (1Giovanni 2:1,12,13,18,28; 3:7,18; 4:4; 5:21). Ci&ograve; mette l'epistola fra gli ultimi libri del Nuovo Testamento, ma non &egrave; possibile fissare la sua data con pi&ugrave; precisione. C'&egrave; qualche incertezza se fu scritta prima o dopo il Vangelo secondo Giovanni.
</p>
<h3>5. Seconda Giovanni</h3>
<p>
In questa breve nota, lo scrittore si designa con il titolo "l'anziano" (2Giovanni 1). Un uomo, per essere conosciuto con questo titolo, doveva essere noto per un'et&agrave; avanzata oltre quella degli altri con cui era associato. Giovanni sopravvisse per molti anni su tutti gli altri apostoli, e probabilmente prima della sua morte era il pi&ugrave; vecchio membro della chiesa. Per questo motivo tutti l'avrebbero naturalmente riconosciuto con questo titolo, soprattutto gli amici pi&ugrave; intimi. La persona principale a cui fu rivolta questa nota, "la Signora eletta" (2Giovanni 1), era una signora non solo nel senso generale, ma era un'aristocratica. Questa &egrave; il significato della parola greca (kuria) tradotta signora.
<p></p>
Siccome questa signora e i suoi figli avevano anche un grande zelo e ospitalit&agrave;, uomini corrotti cercavano la sua ospitalit&agrave;, per poter sfruttare il fatto di essere stato il suo ospite e per poi imporsi su gli altri. Lo scopo principale di questa epistola era di avvertirla di questa possibilit&agrave;. L'apostolo si aspettava di andarla a trovare fra breve, e questo spiega la brevit&agrave; dell'epistola. Fra parentesi, apprendiamo che l'epistola non fu scritta su pergamena ma su carta. Probabilmente fu presto copiata su un materiale pi&ugrave; duraturo, altrimenti sarebbe perita.
</p>
<h3>6. Terza Giovanni</h3>
<p>
Un'altra breve nota dall'anziano (3Giovanni 1), indirizzata ad un fratello chiamato Gaio, che sembra essere noto nella chiesa quanto la Signora eletta della seconda epistola (2Giovanni 1), e per le stesse eccellenti qualit&agrave;. Era particolarmente bravo a "provvedere al viaggio" dei fratelli che passavano da lui andando a campi distanti (3Giovanni 6). Lo scopo dell'epistola era di complimentarlo per questo, e per avvertirlo di un certo Diotrefe, che "aspira di avere il primato" (3Giovanni 9), e che si era opposto anche all'autorit&agrave; dell'apostolo. Fa capire a Gaio che tratter&agrave; questo reprobo secondo quello che merita quando visita quella chiesa (3Giovanni 10). Ha molto da dire a Gaio, come pure alla signora eletta, ma lo rimanda fino a quando potr&agrave; parlare "faccia a faccia" (3Giovanni 14).
<p></p>
Queste due note personali sono di grande valore in quanto rivelano i rapporti amorevoli esistenti fra l'apostolo anziano e i suoi colleghi fedeli, sia uomini sia donne, ed anche la condotta ingiusta di uomini non convertiti che erano entrati nella chiesa. Quest'ultimo fatto dovrebbe impedirci di essere sorpreso o scoraggiato quando vediamo la stessa cosa adesso.
</p>
<h3>7. Giuda</h3>
<p>
L'autore si chiama "il fratello di Giacomo" (Giuda 1), e gli studiosi adesso credono che volesse dire il fratello di quel Giacomo che era un fratello del Signore. Se era cos&igrave;, era anche un fratello del Signore, ma siccome il Signore era asceso in cielo, era pi&ugrave; giusto chiamarsi fratello di Giacomo che fratello di Ges&ugrave;. Dichiara che lo scopo della sua epistola era di esortare i fratelli a combattere strenuamente per la fede trasmessa ai santi una volta per sempre, dato il fatto che molti uomini malvagi erano entrati nella chiesa e che corrompevano la fede e la moralit&agrave; dei fratelli. Le sue denunce su queste persone ci ricorda di denunce simili di uomini malvagi fatte dai profeti dell'Antico Testamento, e di quelle del nostro Signore agli scribi e ai farisei ipocriti. Somigliano ancora di pi&ugrave; al secondo capitolo di 2Pietro. Ricorda ai fratelli che gli apostoli avevano predetto la comparsa di tali persone, e che la loro venuta non doveva quindi essere una sorpresa. Conclude con una benedizione che &egrave; una delle pi&ugrave; belle tra tutti i libri.
</p>
<h3>8. L'Apocalisse</h3>
<p>
La parola "apocalisse" vuol dire rivelazione. Infatti il titolo che l'autore d&agrave; al suo libro, trovato nel primo versetto, &egrave; "Rivelazione di Ges&ugrave; Cristo, che Dio gli diede per mostrare ai suoi servi le cose che devono avvenire tra breve, e che egli ha fatto conoscere mandando il suo angelo al suo servo Giovanni. Lui ha attestato come parola di Dio e testimonianza di Ges&ugrave; Cristo tutto ci&ograve; che ha visto" (Apocalisse 1:1-2). Siccome aveva lo scopo di mostrare le cose che dovevano "avvenire tra breve", il suo contenuto deve essere per lo pi&ugrave; profetico.
<p></p>
Questo titolo completo &egrave; seguito da un saluto alle "sette chiese di Asia" (Apocalisse 1:4), simile al saluto solito delle epistole, e poi da una dossologia. La parte principale del libro apre con il racconto della visione di Giovanni sull'isola di Patmo del Signore Ges&ugrave; in gloria. Il Signore gli comanda di scrivere quello che detta, e seguono sette brevi epistole dal Signore alle sette chiese di Asia. La parola Asia significa la provincia romana di cui Efeso era il capoluogo. Guardando un atlante biblico, il lettore trover&agrave; le sette citt&agrave; in cui queste chiese si trovavano, che formavano quasi un cerchio. Se questo libro fu scritto nel 96 all'incirca, come Ireneo afferma nel secondo secolo, Ges&ugrave; era andato in cielo circa 62 anni prima, e queste chiese esistevano da quasi 40 anni. (Per&ograve;, alcuni studiosi credono che Apocalisse risalga al 68 d.C., poco dopo la persecuzione di Nerone e durante la prima parte della guerra giudea, che si conclude con la caduta di Gerusalemme nel 70 d.C. Ci&ograve; renderebbe l'Apocalisse il primo libro di Giovanni.) Dopo l'esperienza di questo lungo periodo il Signore dett&ograve; una lettera ad ogni chiesa per fargli sapere quello che pensava della loro condotta, e per dare avvertimenti ed esortazioni per il futuro. Quando l'epistola fu letta pubblicamente in ogni chiesa, doveva essere un'occasione indimenticabile. Leggendo queste sette epistole dobbiamo pensare anche alla nostra chiesa, e quando le condizioni sono simili dovremmo sentire gli stessi ammonimenti e raccomandazioni.
<p></p>
Dopo aver scritto le parole delle sette epistole ricevute dal Signore, Giovanni vide una porta aperta in cielo, e all'invito di una voce ci entr&ograve;, e ebbe una visione della gloria di Dio pi&ugrave; trascendente di qualsiasi altra data ad un profeta o ad un apostolo prima. Poi segu&igrave; una visione di un libro sigillato con sette sigilli, che nessuno in cielo era degno di aprire tranne "il leone della trib&ugrave; di Giuda" (Apocalisse 5:5), un titolo noto del nostro Signore Ges&ugrave; Cristo. Quando prese il libro nella sua mano, grande gloria gli fu ascritta da tutti gli abitanti del cielo, e mentre apriva i sette sigilli seguirono dopo ogni sigillo una visione simbolica di qualcosa che sarebbe successo sulla terra (Apocalisse 4:1-7:17). Quando il settimo sigillo fu aperto sette angeli apparvero con sette trombe. Suonarono le loro trombe una dopo l'altra, e seguirono sette altri eventi (Apocalisse 8:1-9:19). Il resto del libro (Apocalisse 12:1-22:21) &egrave; riempito da una serie di visioni diverse e elaborate che concludono con una visione dell'ultimo giudizio e della nuova Gerusalemme dove i santi abiteranno nella presenza di Dio per sempre. Cos&igrave; la Bibbia, che inizia con una visione della creazione degli attuali cielo e terra, in cui &egrave; nato il peccato e il Redentore dal peccato, chiude con una visione di un nuovo cielo e una nuova terra dove i redenti dal peccato di ogni nazione, famiglia e lingua abiteranno per sempre in giustizia e felicit&agrave;. La promessa ad Abraamo non &egrave; mai stata dimenticata da quando &egrave; stata annunciata in Ur dei Caldei, ed &egrave; ora adempiuta dalla benedizione che viene sulle persone di tutte le nazioni tramite il seme di Abraamo.
</p>
<p><a href="guida_domande.php#16">Domande di ripasso</a></p>
<p>Continua: <a href="breve_ripasso.php">17. Un breve ripasso</a></p>
<?
require("../piede.php");
?>