<?
$descriz = "Guida allo studio della Bibbia: Le epistole di Paolo";
$key = "paolo,epistole,lettere,romani,corinzi,galati,efesini,filippesi,colossesi,tessalonicesi,timoteo,tito,filemone,ebrei,studio,studio biblico,guida,McGarvey";
$titolo = "Guida allo studio della Bibbia 15. Le epistole di Paolo";
$sezione = "Articoli";
$sezioneurl = "/intro/";
require("../capo.php");
include("../funzioni.php");
?>
<h1><a href="guida_studio_bibbia.php">Guida allo studio della Bibbia</a></h1>

<h2>15. Le epistole di Paolo</h2>
<p>
Paolo era non solo il pi&ugrave; grande apostolo per quanto riguardo i suoi sforzi e le sue sofferenze, ma era anche lo scrittore pi&ugrave; prolifico del Nuovo Testamento. I suoi scritti occupano quasi un quarto di tutto il Testamento. Non sono nella Bibbia nell'ordine in cui sono stati scritti. Originalmente circolavano, come tutti i libri del NT, come documenti separati; e quando furono raccolti in volumi pi&ugrave; grandi, furono messi pi&ugrave; o meno nell'ordine della grandezza dei libri (come per i libri profetici) e non in ordine cronologico. Menzioneremo la data della loro composizione, quando &egrave; conosciuta; perch&eacute; &egrave; importante prima di leggere un'epistola sapere chi la scrisse, quando, a chi e in quali circostanze.
</p><p>
Alcuni ritengono che Paolo sia il vero fondatore del cristianesimo, cio&egrave; che predicasse un sistema che non era l'intento di Cristo. L'affermazione &egrave; falsa: era l'intento del Capo della Chiesa che fosse il compito di Paolo elaborare e spiegare in modo pi&ugrave; completo gli insegnamenti divini di Ges&ugrave;, e di aggiungere molto alla rivelazione della volont&agrave; di Dio che era prima annunciata da Ges&ugrave;. Nessuno pu&ograve; quindi capire completamente la dottrina di Cristo senza l'aiuto dell'esposizione da parte di Paolo. Dunque &egrave; importante per tutti studiare attentamente le sue epistole.
</p>
<h3>1. Romani</h3>
<p>
Bench&eacute; l'epistola ai Romani non fu la prima scritta da Paolo, &egrave; ben messa come la prima, e la prima dopo gli Atti, perch&eacute; il suo tema principale &egrave; una discussione della base per cui un peccatore &egrave; giustificato davanti a Dio, ed &egrave; giusto per un peccatore che prima possibile, dopo essersi convertito al Signore, conosca bene questo tema. Passare dagli Atti a Romani &egrave; il prossimo passo in avanti che si deve prendere.
</p><p>
L'epistola va letta insieme con i capitoli 20 e 21 di Atti, da cui il lettore pu&ograve; capire che &egrave; stata scritta a Corinto poco prima dell'ultimo viaggio di Paolo a Gerusalemme. Essendo scritta ad una chiesa che conteneva molti membri maturi con esperienze ricche e varie, le sue discussioni di temi importanti sono pi&ugrave; profonde di quelle delle altre lettere.
</p><p>
Il tema principale dell'epistola &egrave; la grande dottrina della giustificazione per fede. L'apostolo dimostra che la base della nostra giustificazione davanti a Dio &egrave; la nostra fede nel Signore Ges&ugrave; Cristo, e non le opere della legge. Fu spinto a questa discussione dall'insegnamento di certi Giudei che dicevano che siamo giustificati se osserviamo perfettamente la legge. L'apostolo dedica i primi 11 capitoli della sua lettera all'esposizione di questa dottrina e per rifiutare delle obiezioni; il resto contiene esortazioni e il racconto delle esperienze interessanti di s&eacute; stesso e di altri. Ci sono alcune cose nella parte dottrinale che non sono adatte alla mente di bambini, ma tutti possono leggere con profitto l'ultima parte.
</p>
<h3>2. Prima Corinzi</h3>
<p>
Alcuni commenti scritti nell'ultimo capitolo di questa epistola, collegato con il capitolo 19 di Atti, fanno capire dove era l'apostolo quando la scrisse. La fondazione della chiesa a Corinto &egrave; descritta in Atti 18, e questi due capitoli di Atti vanno letti prima di iniziare lo studio della lettera. Non ci sono molte informazioni in quei capitoli sullo stato della chiesa quando l'epistola fu scritta; per questo dobbiamo leggere soprattutto l'epistola stessa. Mentre la leggiamo, troviamo le circostanze che richiedevano la scrittura dell'epistola. Sono tutte di natura pratica, diversi tipi di condotta sbagliata che apparirono nella chiesa dopo la partenza di Paolo. Per questo motivo &egrave; una delle epistole pi&ugrave; importante per il regolamento della vita e del comportamento di una chiesa.
</p>
<h3>3. Seconda Corinzi</h3>
<p>
Confrontando 2Corinzi 1:8-11; 2:12-13; 8:5-7 con Atti 19:23-20:1, impariamo il luogo e le circostanze della scrittura di questa epistola. Paolo aveva sentito tramite Tito, che &egrave; menzionato qui per la prima volta, gli effetti della sua prima lettera alla chiesa, e questa informazione gli fece scrivere la seconda. La condizione della chiesa, insieme con il grande pericolo attraverso cui l'apostolo era appena passato ad Efeso, causano una depressione nel suo spirito, e come conseguenza questa &egrave; l'epistola pi&ugrave; triste del Nuovo Testamento. Rivela pi&ugrave; di qualsiasi altra epistola di Paolo, o delle narrative di Atti, le profondit&agrave; di tristezza e sofferenza per cui questo apostolo continuamente attraversava nella sua missione ai Gentili. La vita interiore di Paolo &egrave; rivelata di pi&ugrave; qua che altrove, e questo &egrave; il valore principale dell'epistola.
</p><p>
Un'epistola persa scritta prima di 1Corinzi &egrave; menzionata in 1Corinzi 5:9, e forse un'altra lettera persa &egrave; menzionata in 2Corinzi 2:4; 7:8; questi versetti non sembrano riferirsi a 1Corinzi.
</p>
<h3>4. Galati</h3>
<p>
C'&egrave; poco in questa epistola per indicare l'anno o il posto in cui fu scritta. La sorpresa che lo scrittore esprime che i Galati si siano cos&igrave; velocemente deviati ad un altro vangelo (Galati 1:6) dimostra che era scritto poco dopo una visita, ma non si sa quale visita fosse. Era venuto dalla Galazia a Efeso, e dopo due anni e tre mesi l&igrave;, and&ograve; in Macedonia e Grecia (Atti 18:23; 19:1,21-22; 20:1-2). Alcuni studiosi ritengono che abbia scritto l'epistola mentre era ancora ad Efeso, il che vorrebbe dire meno di tre anni da quando ne era partito; altri pensano invece che l'abbia scritto dopo aver raggiunto Corinto qualche mese dopo.
</p><p>
Non sappiamo niente delle chiese della Galazia oltre quello che impariamo dall'epistola; ma da essa apprendiamo alcuni fatti molti importanti riguardo a come avevano ricevuto Paolo, il loro rapporto con lui, ed anche la causa della loro alienazione da lui.
</p><p>
Opponendosi a certi falsi insegnanti che erano Cristiani nominali e che pervertivano la verit&agrave;, Paolo insegna qui, come in Romani, che la base della nostra giustificazione davanti a Dio &egrave; la fede ubbidiente, e non le opere della legge. La discussione &egrave; breve ma chiara, e segue con degli insegnamenti ed esortazioni ammirevoli, sempre necessarie sui doveri pratici della vita cristiana.
</p>
<h3>5. Efesini</h3>
<p>
C'&egrave; un dubbio che l'epistola debba portare il titolo 'Agli Efesini', perch&eacute; mancano i saluti personali che sono abbondanti nelle altre lettere di Paolo a chiese che fond&ograve;, e ci&ograve; sarebbe inspiegabile se avesse scritto ad una chiesa in cui lavor&ograve; per pi&ugrave; di due anni - pi&ugrave; tempo che in qualsiasi altra chiesa. Lo scrittore parla delle fede di questi fratelli come se fosse una cosa che aveva sentito e non di conoscenza personale (Efesini 1:15-16); e si riferisce al fatto di essere apostolo ai Gentili come una cosa che avevano sentito da altri, e forse non lo sapevano affatto (Efesini 3:1-4). Con queste indicazioni concorda il fatto che in alcune copie molto antiche dell'epistola le parole "a Efeso" nel saluto (Efesini 1:1) mancano. Si suppone adesso che fosse un tipo di lettera circolare, spedita a diverse chiese (fra cui quella di Efeso), e che il nome Efeso fosse inserito in alcune copie a causa del fatto che Efeso era la citt&agrave; principale a cui fu spedita. Fu scritta mentre Paolo era un prigioniero a Roma (Efesini 3:1; 4:1; 6:18-20).
</p><p>
L'epistola inizia con delle grandi affermazioni sull'eterno proposito e sulla preconoscenza di Dio per quanto riguarda Cristo e la sua opera di redenzione, ed anche riguardo alla chiamata dei Gentili a partecipare con l'antico popolo di Dio alla sua grazia. Questa parte conclude con il terzo capitolo e la preghiera di Paolo per i fratelli che ricevettero la lettera, ci&ograve; che chiude questo capitolo, &egrave; uno dei brani pi&ugrave; impressionante in tutti i suoi scritti. Va studiata come modello di preghiera seria e sentimento alto. Il resto dell'epistola &egrave; di carattere pratico, trattando l'unit&agrave; della chiesa, la sua crescita in ogni virt&ugrave;, e la vita cristiana di ogni classe di discepolo. Particolarmente ragguardevole e di valore &egrave; il brano nell'ultimo capitolo, dove l'apostolo paragona i pezzi dell'armatura portata da un soldato di allora con i vari doveri e privilegi di un Cristiano nella sua lotta contro il potere delle tenebre. Il combattimento e l'atletica sono le immagini preferiti di Paolo, perch&eacute; in tutti e due, come pure nella vita cristiana, una persona deve sforzarsi di fare del suo miglior per evitare di essere sconfitto.
</p>
<h3>6. Filippesi</h3>
<p>
Il racconto della fondazione della chiesa a Filippi &egrave; dato in Atti 16:6-40, e va letto prima di studiare questa epistola. I seguenti fatti: che Paolo era in prigione quando la scrisse (Filippesi 1:12-13), che il pretorio (la guardia di corpo dell'imperatore a Roma) ebbe sentito la sua predicazione (Filippesi 1:13-14), e che manda ai Filippesi il saluto di alcuni della casa di Cesare (Filippesi 4:22) indicano chiaramente che l'epistola fu scritta, come Efesini, mentre Paolo era un prigioniero a Roma. Questa &egrave; la carcerazione menzionata alla fine di Atti. Il motivo della sua scrittura era che un fratello chiamato Epafrodito, essendo venuto da Filippi a Roma per portare un contributo per le necessit&agrave; di Paolo (Filippesi 4:10-20), si ammal&ograve;, e i Filippesi avevano sentito che era stato vicino alla morte. Cos&igrave; Paolo lo rimand&ograve; a Filippi, e senza dubbio gli fece portare l'epistola (Filippesi 2:19-30). L'epistola &egrave; piena di simpatia tenera, e non c'&egrave; neanche uno rimprovero alla chiesa, ma molte esortazione calorose.
</p>
<h3>7. Colossesi</h3>
<p>
Questa &egrave; un'altra lettera della carcerazione, di cui ce ne sono quattro: Efesini, Filippesi, Colossesi e Filemone. Che Paolo fosse in prigione quando scrisse &egrave; visto dai suoi commenti in Colossesi 4:2-4,18. Sembra che abbia spedito l'epistola tramite Tichico, il quale port&ograve; anche Efesini (Colossesi 4:8; Efesini 6:21-22), il che dimostra che furono scritte e spedite insieme. Questo spiega il fatto che le epistole si somigliano molto, pi&ugrave; di qualsiasi altre due.
</p><p>
Il primo capitolo di questa epistola contiene una delle pi&ugrave; grandi spiegazioni della gloria del nostro Signore Ges&ugrave; Cristo nel Nuovo Testamento. Abbonda anche in esortazioni all'attivit&agrave; e allo zelo cristiani, che sono rafforzati dall'esempio dell'apostolo.
</p>
<h3>8. Prima Tessalonicesi</h3>
<p>
Venendo a questa epistola andiamo indietro nel tempo, dalla carcerazione di Paolo menzionata alla fine di Atti alla sua prima visita a Corinto, descritta in Atti 18:1-18, perch&eacute; era durante questa visita che l'epistola fu scritta. La sua opera a Tessalonica &egrave; descritta in "Atti 17:1-9. And&ograve; da l&igrave; a Berea (Atti 17:10) e poi ad Atene (Atti 17:15), e poi a Corinto (Atti 18:1). L&igrave;, Sila e Timoteo, che aveva lasciato prima, lo raggiunsero (Atti 18:5), e nell'epistola dice, "Ma ora Timoteo &egrave; ritornato...". questo dimostra che l'epistola fu scritta subito dopo l'arrivo di Timoteo. Ci&ograve; avvenne, secondo la cronologia calcolata dal libro degli Atti, nell'anno 52 d.C. Cos&igrave; &egrave; la prima delle epistole di Paolo, ed anche il primo libro del Nuovo Testamento. Per&ograve;, alcuni studiosi ritengono che l'epistola di Giacomo fosse scritta nel 50 all'incirca; il tale caso sarebbe il primo libro scritto del Nuovo Testamento.
</p><p>
L'epistola dimostra che la chiesa di Tessalonica subiva una grande persecuzione, ma che si comportava in modo di diffondere la luce del Vangelo nelle comunit&agrave; circostanti (1Tessalonicesi 1:2-10). Questi discepoli fedeli erano solo parzialmente istruiti nella dottrina cristiana, e avevano dubbi riguardo ai fratelli defunti. Ci&ograve; port&ograve; Paolo a dare loro una delle pi&ugrave; chiare lezioni possibili sulla risurrezione dei morti, affinch&eacute; potessero confortarsi (1Tessalonicesi 4:13-18). Queste stesse parole sono state un conforto ai santi da allora fino ad ora, ed sono state usate come testo per molti funerali.
</p>
<h3>9. Seconda Tessalonicesi</h3>
<p>
Sembra che questa epistola fosse scritta poco dopo la prima alla stessa chiesa, perch&eacute; la persecuzione menzionata nella prima era ancora in corso (2Tessalonicesi 1:2-3), e lo stato generale della chiesa non era cambiato. Fu scritta quando lo scrittore era preoccupato riguardo alla liberazione da "uomini molesti e malvagi" (2Tessalonicesi 3:2), ci&ograve; sarebbe d'accordo con una scrittura durante l'intervallo fra il suo ritiro dalla sinagoga a Corinto alla casa di Giusto, e l'assicurazione datagli dal Signore che nessuno gli avrebbe fatto del male (Atti 18:5-10). I temi pi&ugrave; importanti discussi sono il destino dei malvagi, la seconda venuta del Signore e la venuta dell'"uomo di peccato" menzionato qui dall'apostolo (2Tessalonicesi 2:3). Contiene anche delle istruzioni molto chiare e forti che riguardano cosa la chiesa dovrebbe fare con quelli che si comportano in modo disordinatamente. La fine dimostra che Paolo scriveva i saluti delle sue epistole con la propria mano come "segno" della sua genuinit&agrave; (2Tessalonicesi 3:17). Aveva l'abitudine, come abbiamo visto in Romani, di dettare le sue lettere ad uno scriba, ma la sua scrittura nel saluto le identificavano come le sue.
</p>
<h3>10. Prima Timoteo</h3>
<p>
Quando Paolo scrisse questa epistola aveva lasciato Timoteo ad Efeso ed era andato in Macedonia (1Timoteo 1:3). Durante il periodo della sua vita raccontato negli Atti degli Apostoli, non fece mai questo. Solo una volta and&ograve; da Efeso in Macedonia, e in quella occasione aveva mandato Timoteo prima di lui (Atti 19:21-22; 20:1). Siccome Atti segue la sua vita fino alla carcerazione a Roma, avrebbe dovuto fare questa visita ad Efeso dopo quella carcerazione. Doveva essere quindi rilasciato da prigione, come si aspettava, e fatto dei viaggi di nuovo per la sua opera missionaria.
</p><p>
Questa epistola &egrave; stata scritta soprattutto per l'istruzione di un evangelista, cio&egrave; Timoteo, e riguardo alla sua opera nelle chiese. Dovrebbe dunque essere studiato approfonditamente da ogni predicatore del Vangelo per la propria guida e istruzione. Ma una grande parte dell'istruzione data riguarda i doveri di tutti quelli che servono nella chiesa, e cos&igrave; l'epistola &egrave; per loro quanto lo &egrave; per i predicatori. Inoltre, gli altri membri delle chiese non possono sapere come comportarsi verso i responsabili e predicatori se non sanno quali sono i loro doveri e responsabilit&agrave;; in questo modo la lettera &egrave; utile per tutti in chiesa. Per una conoscenza dei dettagli pratici sull'organizzazione della chiesa, dipendiamo da questa epistola pi&ugrave; che da qualsiasi altra.
</p><p>
Sarebbe saggio per lo studente di questa epistola, e di 2Timoteo, prendere una chiave biblica e trovare tutti i versetti in cui Timoteo appare nel Nuovo Testamento, per conoscere bene tutto quello che &egrave; scritto di lui. &Egrave; una delle persone pi&ugrave; interessanti menzionate nel Nuovo Testamento.
</p>
<h3>11. Seconda Timoteo</h3>
<p>
Paolo &egrave; nuovamente un prigioniero (2Timoteo 1:8,16-18; 2:9); &egrave; la carcerazione che terminer&agrave; con la sua morte (2Timoteo 4:6-8,16-18). &Egrave; l'ultima cosa scritta da Paolo che noi abbiamo, ci&ograve; le impartisce un interesse particolare come ultime parole di un uomo di Dio. Parla soprattutto di cose personali, siccome tutte le grandi dottrine erano spiegate in documenti precedenti. La tristezza della sua situazione &egrave; indirettamente rivelata, soprattutto nel primo capitolo. Le esortazioni a Timoteo, e a tutti i fratelli, sono fra le pi&ugrave; emozionanti di Paolo, e la predizione della grande apostasia che occupa il terzo capitolo sembra un grido di disperazione per il futuro della chiesa, ma il grido di trionfo con cui si avvicina alla sua morte nel quarto capitolo ha emozionato le anime dei santi quanto quasi nessun altro brano della Bibbia. Se ci emoziona in un periodo cos&igrave; lontano, immaginiamo quanto ha dovuto infiammare il cuore dei suoi colleghi, compagni e convertiti. Era ansioso di rivedere Timoteo prima di morire, e lo supplic&ograve; di venire prima dell'inverno e di portare un mantello che aveva lasciato a Troas, di cui avrebbe avuto bisogno nella fredda prigione se il tempo invernale sarebbe arrivato prima della sua esecuzione. Voleva anche qualcosa da leggere, e pensava di scrivere di pi&ugrave;, per cui chiese a Timoteo di portare dei libri e le pergamene che aveva lasciato a Troas (2Timoteo 4:13-21). Nessuno pu&ograve; leggere questa epistola attentamente senza risultare migliore e pi&ugrave; saggio.
</p>
<h3>12. Tito</h3>
Si sa poco di Tito. Non &egrave; menzionato in Atti; tutto quello che sappiamo di lui si trova in quattro delle epistole di Paolo. Accompagn&ograve; Paolo e Barnaba da Antiochia a Gerusalemme al tempo della conferenza sulla circoncisione (Galati 2:1); fu dopo mandato da Paolo mentre era ad Efeso per una missione importante a Corinto (2Corinzi 2:12-13; 7:5-7; 8:16-23; 12:18); era con Paolo nell'isola di Creta dopo il rilascio dell'apostolo dalla sua carcerazione romana, dove lasci&ograve; Tito per mettere in ordine le cose che rimanevano ancora da fare nella chiesa fondata l&agrave; (Tito 1:5); e era con Paolo a Roma durante la sua ultima carcerazione, ma da l&igrave; and&ograve; a Dalmazia prima della morte di Paolo (2Timoteo 4:10).
</p><p>
Era ancora in Creta quando questa epistola gli fu scritta (Tito 1:5), ma Paolo gli richiese di andare a Nicopoli appena era arrivato un altro evangelista per sostituirlo (Tito 3:12). Lo scopo dell'epistola &egrave; molto simile a quello di 1Timoteo, cio&egrave; di istruire Tito come evangelista per la sua opera fra le chiese, e allo stesso tempo impartire indirettamente la stessa istruzione alle chiesa. &Egrave; importante che nuovi predicatori lo studino, come pure tutti quelli che vogliono servire nella chiesa. Il suo primo capitolo, insieme con il terzo di 1Timoteo, fornisce delle istruzioni sulle qualifiche necessarie per gli anziani della chiesa, e siccome tutti i membri della chiesa dovrebbero ogni tanto selezionare queste persone, questi brani dovrebbe essere conosciuti da tutti.
</p>
<h3>13. Filemone</h3>
<p>
Questa &egrave; una delle epistole della carcerazione, cio&egrave; della prima carcerazione a Roma (Filemone 1,13). Fu scritta per Onesimo, uno schiavo di Filemone, che era scappato dal suo padrone, arrivato a Roma e convertito al Signore tramite la predicazione di Paolo, e da un po' di tempo assisteva Paolo nel suo ministero (Filemone 10-15). Paolo suggerisce a Filemone che sarebbe giusto liberare Onesimo, e promette di pagare personalmente quello che Onesimo gli deve (Filemone 17-21). Apprendiamo indirettamente da Colossesi che Onesimo era di Colosse (Colossesi 4:9), e cos&igrave; pure il suo padrone Filemone. Filemone era un uomo di grande benevolenza e apparentemente ricco. Una chiesa si riuniva in casa sua (Filemone 2-7).
</p>
<h3>14. Ebrei</h3>
<p>
Molti hanno sempre ritenuto che questa epistola sia di Paolo, ma dal secondo secolo fino al presente molti studiosi hanno dubitato o rinnegato che l'autore sia Paolo. Tre scrittori, tutti nati nel secondo secolo d.C. ma attivi all'inizio del terzo, sono rappresentativi delle opinioni presenti fino ad adesso. Origene disse che i pensieri erano di Paolo, ma non lo stile. Non riusc&igrave; a decidere chi l'aveva scritta. Clemente di Alessandria era dell'opinione che Paolo l'avesse scritto in ebraico, e che fu tradotta in greco da Luca. Pensava che lo stile fosse di Luca, ma i pensieri di Paolo. Tertulliano la ascrisse a Barnaba. Nei tempi pi&ugrave; recenti, Lutero sugger&igrave; che fosse scritta da Apollo, e alcuni studiosi hanno propagato questa opinione. Forse la questione non sar&agrave; mai risolta. Ma bench&eacute; ci sono diverse opinioni su che fosse stato autore, tutti gli studiosi credenti sono d'accordo che fu scritta da qualcuno del gruppo apostolico, e che il suo contenuto deve essere accettato come vero e autorevole.
</p><p>
La comunit&agrave; a cui fu scritta &egrave; sconosciuta quanto l'autore, sebbene sia chiaro dal contenuto era che indirizzata soprattutto ad una comunit&agrave; di Giudei cristiani, e cos&igrave; anche per tutti tali credenti. Era piuttosto difficile nella prima generazione della chiesa convincere i Giudei che diventavano Cristiani di lasciare completamente quelle parti della loro vecchia religione che erano adempiute da quella nuova, e alcuni erano propensi a ritornare al giudaismo dopo aver accettato la fede cristiana. L'epistola fu scritta per tali persone. L'argomento principale &egrave; la superiorit&agrave; di Cristo come sacerdote su Aaronne, e la superiorit&agrave; del suo sacrificio di s&eacute; stesso sulla legge. Dimostra infatti non solo la superiorit&agrave; di Cristo, ma che il sacerdozio di Aaronne e i sacrifici della legge non dovevano essere pi&ugrave; osservati. Dimostra anche che tutti i riti della legge che dipendevano da questo sacerdozio e da questi sacrifici erano passati con essi.
</p><p>
Mentre questo era lo scopo principale del libro, il suo valore non &egrave; limitato a quello che dice ai Giudei, perch&eacute; molti insegnamenti e esortazioni pratiche sono adatti all'istruzione e all'edificazione di ogni tipo di discepolo in ogni et&agrave; e paese. Le sue esortazioni, gli esempi e gli avvertimenti, come il suo argomento principale, sono tratti quasi esclusivamente dai libri dell'Antico Testamento, e nessuno che non conosce questi libri (soprattutto i libri della legge di Mos&egrave;) pu&ograve; capire l'epistola. Per studiare l'epistola, ci si deve riferire quasi sempre, usando la memoria, i riferimenti incrociati, o una chiave biblica, ai libri di Mos&egrave;. Accanto all'epistola ai Romani, &egrave; generalmente ritenuta la pi&ugrave; importante epistola nel Nuovo Testamento per la spiegazione delle dottrine di Cristo.
</p>
<p><a href="guida_domande.php#15">Domande di ripasso</a></p>
<p>Continua: <a href="epistole_cattoliche_apocalisse.php">16. Le epistole cattoliche e l'Apocalisse</a></p>
<?
require("../piede.php");
?>