<?
$descriz = "Guida allo studio della Bibbia: Il regno di Giuda continuato (2Re 18-25; 2Cronache 29-36)";
$key = "regno,giuda,regno di giuda,davide,studio,studio biblico,guida,McGarvey";
$titolo = "Guida allo studio della Bibbia 8. Il regno di Giuda continuato (2Re 18-25; 2Cronache 29-36)";
$sezione = "Articoli";
$sezioneurl = "/intro/";
require("../capo.php");
include("../funzioni.php");
?>
<h1><a href="guida_studio_bibbia.php">Guida allo studio della Bibbia</a></h1>

<h2>8. Il regno di Giuda continuato (2Re 18-25; 2Cronache 29-36)</h2>
<p>
Questa storia del regno di Giuda, dalla caduta d'Israele fino alla sua, si trova nel libro di 2Re, dal capitolo 18 fino alla fine, e in 2Cronache, dal capitolo 29 fino alla fine. Una parte si trova anche nei libri dei profeti che scrissero durante quel periodo, soprattutto Isaia e Geremia. Questo periodo dur&ograve; circa 130 anni e include i regni di otto re. Di questi re, due regnarono solo tre mesi e uno solo due anni. Il primo, Ezechia, era un buon re, il migliore dal tempo della divisione del regno. Prima per&ograve; ci furono due re, Iotam e Acaz, che erano molto malvagi, e con la loro malvagia influenza il popolo era diventato molto corrotto. Era quindi molto difficile per Ezechia indurre il popolo a vivere di nuovo secondo a legge di Mos&egrave;. Come riconoscimento divino della sua fedelt&agrave;, il suo regno fu segnalato da una delle liberazione pi&ugrave; incredibili che Israele abbia mai sperimentato. Fu la distruzione miracolosa di notte di un enorme esercito sotto Sennacherib, il re d'Assiria, che aveva invaso il paese mentre faceva guerra contro Egitto, e richiedeva l'arresa di Gerusalemme.
</p><p>
Durante il regno di Ezechia la carriera pubblica di Isaia venne ad una conclusione. Fu chiamato ad essere profeta nell'anno che il re Uzzia mor&igrave;, e i suoi primi discorsi profetici denunciavano la malvagit&agrave; del popolo nei regni di Iotam e Acaz. Bisogna leggere questi discorsi insieme con i racconti nei libri di 2Re e 2Cronache di questi due re. Mentre questi libri danno la storia politica, Isaia svela lo stato della societ&agrave; della gente, e mostra quanto orrenda era. Isaia era il costante sostenitore e consigliere di Ezechia in tutte le sue buone imprese, e molti capitoli del suo libro, fino al 39, vanno studiati insieme con il regno di Ezechia. Gli ultimi 27 capitoli guardano avanti alla cattivit&agrave; di Giuda e la liberazione da essa, mentre molti brani in ogni parte del libro guardano avanti al tempo del Messia.
</p><p>
Il buon regno di Ezechia fu seguito da quello di Manasse, il pi&ugrave; malvagio di tutti i re di Giuda. Il suo regno dur&ograve; 55 anni. La vera religione era completamente abolita, e tutte le forme di idolatria conosciute fra le nazioni vicine furono adottate. Il tempio di Dio fu reso il centro di queste abominazioni. Un'intera generazione di Giudei crebbe alla maturit&agrave;, ed alcuni alla vecchiaia, senza la possibilit&agrave; di conoscere il vero Dio o avere qualsiasi conoscenza della Scritture. Amon, il figlio e successore di Manasse, continu&ograve; nelle vie di suo padre, aggiungendo ancora due anni a questo periodo di apostasia. Quando Giosia, il prossimo re, inizi&ograve; a regnare, aveva solo otto anni, e 12 anni furono aggiunti a questo periodo scuro prima che raggiungesse un'et&agrave; per tentare una riforma vigorosamente. Per la provvidenza di Dio, e forse attraverso il profeta Sofonia (vedi il capitolo 9), fu portato sotto certe influenze che lo condussero alla restaurazione della vera adorazione e all'abolizione dell'idolatria. Quando aveva 18 anni e il regno dell'oscurit&agrave; e dell'ignoranza durava gi&agrave; da 75 anni, una copia della legge di Dio fu trovata nel tempio e leggendola sia il re sia il popolo si resero conto del loro peccato e dei loro antenati. Il re fece uno sforzo grande per portare il popolo al ravvedimento e per restaurarlo al favore di Dio, e sembra che abbia avuto successo. Ma il profeta Geremia, che inizi&ograve; a profetizzare nel tredicesimo anno di Giosia, e che us&ograve; tutta la sua influenza come profeta per sostenere il re, denunci&ograve; pubblicamente che la riforma del popolo era finta e non veniva dal cuore. I primi 20 capitoli del suo libro vanno studiati insieme con la storia del regno di Giosia, perch&eacute; spiegano in modo molto vivace lo stato della societ&agrave; e della religione. Questo profeta predisse ripetutamente la caduta del regno come conseguenza dei peccati. Giosia e Geremia furono tutti e due giovani quando cominciarono a lavorare insieme per la salvezza del popolo, e quasi mai due giovani hanno combattuto con cos&igrave; tanto coraggio con quasi un'intera nazione unita contro di loro.
</p><p>
Giosia fu l'ultimo re di Giuda che cerc&ograve; di impedire la sorte che veniva sulla nazione secondo le parole di molti profeti. La sua fine fu tragica, perch&eacute; fu ucciso in una battaglia contro il re di Egitto, che marciava con un esercito attraverso il paese di Giuda per combattere contro Assiria, con cui Giosia aveva fatto un'alleanza di amicizia. Ci furono solo 22 anni fra la sua morte e l'inizio della cattivit&agrave; predetta, e in questi anni ci furono i regni di tre dei suoi figli e uno nipote, e tutti e quattro respinsero il consiglio di Dio dato tramite Geremia, e persistettero nella malvagit&agrave; che allora caratterizzava quasi tutto il popolo. In tutto questo periodo, Geremia era l'uomo pi&ugrave; vistoso della nazione, non come consigliere e sostenitore dei re, come nel regno di Giosia, ma come la voce di Dio, parlando costantemente contro la malvagit&agrave; del re e dei sudditi. Tutto il suo libro, dal capitolo 21 fino alla fine, va letto attentamente insieme con i regni di questi quattro re. Purtroppo, questi capitoli non sono stati raccolti in ordine cronologico, ma l'introduzione di quasi ogni discorso profetico ci dice in quale anno del regno di quale re fu pronunciato. Nessuna persona nella Bibbia &egrave; spiegata in modo pi&ugrave; eroico di Geremia. &Egrave; stato chiamato il profeta piangente, a causa della grande tristezza che sentiva per i guai che venivano sul suo popolo, che non credeva alle sue predizioni. Soffr&igrave; molta violenza da parte loro. Il piccolo libro chiamato Lamentazioni &egrave; un'espressione in poesia del suo lamento per Gerusalemme quando finalmente cadde nelle mani nei pagani.
</p>
<p><a href="guida_domande.php#8">Domande di ripasso</a></p>
<p>Continua: <a href="altri_libri_profetici_prima_esilio.php">9. Altri libri profetici prima dell'esilio</a></p>
<?
require("../piede.php");
?>