<?
$descriz = "Guida allo studio della Bibbia: La storia di Israele dalla morte di Mos&egrave; a quella di Davide";
$key = "israele,storia,mos&egrave;,davide,studio,studio biblico,guida,McGarvey";
$titolo = "Guida allo studio della Bibbia 5. La storia di Israele dalla morte di Mos&egrave; a quella di Davide";
$sezione = "Articoli";
$sezioneurl = "/intro/";
require("../capo.php");
include("../funzioni.php");
?>
<h1><a href="guida_studio_bibbia.php">Guida allo studio della Bibbia</a></h1>

<h2>5. La storia di Israele dalla morte di Mos&egrave; a quella di Davide</h2>
<p>
Mentre i 12 libri storici che seguono il Pentateuco ci danno, come abbiamo detto in un capitolo precedente, una storia quasi continua fino alla fine del periodo dell'Antico Testamento, lo studio di questo periodo &egrave; facilitato considerandolo in diversi periodi in cui si divide in modo naturale. Scegliamo prima di tutto la divisione nominata nel titolo di questo capitolo, che spiegheremo dando una sintesi dei libri in cui la storia &egrave; trovata.
</p>
<h3>1. Giosu&egrave;</h3>
<p>
Questo libro &egrave; cos&igrave; chiamato non perch&eacute; Giosu&egrave; lo scrisse, bench&eacute; sia possibile, ma perch&eacute; lui ne &egrave; il protagonista.
</p><p>
Il libro &egrave; diviso in tre parti. La prima inizia dove il Pentateuco ha finito con Israele sulla riva orientale del Giordano, e descrive il loro passaggio meraviglioso del fiume, e la sua conquista con due campagne militari del paese di Canaan, con l'eccezione di alcuni altri popoli. Questi furono cos&igrave; indeboliti che non potevano impedire agli Ebrei di stabilirsi nel paese. Ci&ograve; port&ograve; all'adempimento definitivo della promessa ad Abraamo che Dio gli avrebbe dato il paese come eredit&agrave; per la sua discendenza. Questa parte include i primi 12 capitoli.
</p><p>
La seconda parte, dal capitolo 13 al 22, d&agrave; la posizione delle diverse trib&ugrave;, in modo particolare nominando le citt&agrave; nel loro territorio. Si pu&ograve; considerare questi capitoli la geografia biblica della Palestina. Lo studente adesso dovrebbe prendere una buona cartina e imparare la posizione di ogni trib&ugrave;, e di tutte le citt&agrave; principali, le montagne, le pianure, i laghi e i fiumi.
</p><p>
La parte finale, composta dai ventitreesimo e ventiquattresimo capitoli, &egrave; composta da due discorsi di addio da parte di Giosu&egrave;, uno agli ufficiali principali di Israele, l'altro ad un'assemblea di tutto il popolo, e da un breve racconto dalla morte e della sepoltura di Giosu&egrave; e di Eleazar il sacerdote. Accenna anche alla sepoltura delle ossa di Giuseppe, che erano stati portati dall'Egitto. Israele allora fu stabilito come nazione nella terra promessa, e le promesse che riguardano la terra che erano state fatte ad Abraamo e ripetute ad Isacco e Giacobbe erano adempiute.
</p>
<h3>2. Giudici</h3>
<p>
Questo libro apre con un racconto delle azioni separate delle diverse trib&ugrave; che spingeva fuori i Cananei che erano rimasti nel loro territorio dopo la morte di Giosu&egrave;, bench&eacute; contenga anche la ripetizione di una conquista dalla trib&ugrave; di Giuda fatta prima della morte di Giosu&egrave;. Poi, in un tipo di prefazione, l'autore nei prossimi due capitoli narra le continue apostasie e liberazioni che formano la storia del resto del libro. Questi due capitoli possono essere chiamati Parte 1. Poi segue la Parte 2, i capitoli dal 3 al 16, in cui a volte una trib&ugrave; e a volte molte trib&ugrave; caddero in idolatria, furono assoggettate e molto bersagliati dai loro nemici, fino a quando si ravvidero e gridarono a Dio. Poi furono liberate sotto la leadership di un giudice suscitato dal Signore per quello scopo. Rimasero nella paura di Dio fino a quando il giudice mor&igrave;, dopodich&eacute; gli stessi eventi si ripeterono fino alla dodicesima volta. Non c'era un governo centrale; ma quando un tale governo era necessario, giudici furono provvidenzialmente suscitati e i racconti che abbiamo di essi qui, diedero il nome Giudici a questo libro.
</p><p>
La terza parte del libro, i capitoli da 17 al 21, danno due eventi che l'autore non aveva scritto prima per non interrompere il discorso principale del libro. Il primo mostra come un'adorazione idolatra fu stabilita a Dan, e ci continu&ograve; per diversi secoli. L'altro spiega come l'intera nazione venne insieme per punire un gran reato, quando la citt&agrave; e la trib&ugrave; che la conteneva rifiutarono di punirlo.
</p><p>
Lo scopo generale del libro dei Giudici &egrave; di mostrare il funzionamento delle leggi civili e religiose durante i primi tre o quattro secoli delle esperienze di Israele. Ci fu un fallimento relativo, come &egrave; vero di tutte le nazioni sia antiche sia moderne; ma sotto questa disciplina divina molti uomini e donne virtuosi furono sviluppati.
</p>
<h3>3. Rut</h3>
<p>
Gli eventi romantici di questo bel racconto si svolsero durante il governo dei giudici in Israele (Rut 1:1), e uno dei suoi scopi, l'unico che appare fino a quando l'ultimo paragrafo ne rivela un altro, &egrave; di presentare una descrizione migliore della vita sotto i giudici di quella che troviamo nel libro dei Giudici. Lo fa in modo molto incantevole. Ma alla conclusione del libro comprendiamo che il libro voleva anche dimostrare che una donna moabita divenne un antenata di Davide, e spiegare le circostanze interessanti per cui era successo. Non poteva essere scritto prima del regno di Davide, perch&eacute; era il regno di Davide che cre&ograve; interesse per la sua genealogia.
</p>
<h3>4. 1Samuele</h3>
<p>
Questo libro inizia con l'ultimo dei giudici e conclude con la morte del primo re. Contiene quindi il racconto del cambiamento nella forma del governo, mostra come la degenerazione politica e religiosa, che accadeva verso la fine del regno dei giudici, arriv&ograve; fino al suo punto pi&ugrave; basso: la corruzione morale del sacerdozio. A questo punto il popolo aborr&igrave; i sacrifici di Geova a causa della malvagit&agrave; dei sacerdoti che li offrivano. Mostra anche che la degradazione politica raggiunse il suo punto pi&ugrave; basso con la degradazione religiosa, e che poi l'arca del patto, che era il simbolo della presenza di Dio con Israele, fu catturata e portata via dai loro nemici, i Filistei. Questo introdusse un'irregolarit&agrave; nell'adorazione da parte di quelli che continuarono a servire Dio, e port&ograve; ad una richiesta dal popolo per un re che li avrebbe governati. Questa richiesta fu trattata come un peccato del popolo, perch&eacute; erano i loro peccati, e non un difetto nella forma di governo che Dio aveva dato loro, che aveva portato al fallimento. Tuttavia, Dio aveva previsto il risultato e aveva gi&agrave; provveduto, e di conseguenza diede loro un re, Saul il figlio di Chis. Nel frattempo il profeta Samuele aveva portato una grande riforma religiosa fra il popolo, e se Saul fosse stato un fedele servo di Dio, lo stato dell'intera nazione sarebbe stato migliore. Ma sebbene Saul fosse un guerriero valoroso, e vincesse molto battaglie, gir&ograve; le spalle a Dio in molte cose, e la sua carriera fin&igrave; con la sua morte sul campo di battaglia. Il suo regno si concluse, come pure il regno dei giudici, in una sconfitta che lasci&ograve; il popolo ancora una volta soggetto ai Filistei, illustrando il principio che la giustizia esalta una nazione, mentre il peccato &egrave; una disgrazia per ogni popolo. Questa &egrave; la lezione principale in questa parte della storia di Israele. Il libro dimostra anche come Dio prepar&ograve; un altro uomo, Davide, per sostituire Saul e per regnare in modo pi&ugrave; degno di lui. Racconta anche la vita del pi&ugrave; grande profeta di Israele dai tempi di Mos&egrave;, perch&eacute; Samuele era non solo un uomo molto buono, ma anche un ottimo leader, che con la guida di Dio scelse e unse tutti e due i re Saul e Davide, e fino alla sua morte, per cui tutta la nazione era in lutto, entrambi i re e tutto il popolo lo cercarono per consiglio in ogni crisi. Da quel periodo in poi gli uomini sollecitati per rappresentare Dio sono i profeti, come lo furono fino ad allora i giudici.
</p>
<h3>5. 2Samuele</h3>
<p>
Nella Bibbia ebraica i due libri di Samuele sono uno solo, e la storia passa dal primo al secondo senza interruzione. La separazione fu fatta per dividere questo libro lungo, che forse non stava su un rotolo unico nell'antichit&agrave;. Non sono chiamati Samuele perch&eacute; Samuele li scrisse, ma perch&eacute; era il protagonista negli eventi raccontati. Mor&igrave; prima della fine del libro di 1Samuele. Il libro di 2Samuele apre con la salita di Davide al trono, prima della trib&ugrave; di Giuda, e poi dopo una guerra di sette anni di tutto Israele. La storia allora raggiunge il punto in cui un'altra delle antiche promesse di Dio fu adempiuta, come era stato promesso a Giacobbe, "Una nazione, anzi una moltitudine di nazioni discender&agrave; da te" (Genesi 35:11); e Giuda fu indicato come il figlio di Giacobbe tramite cui questa promessa sarebbe stata adempiuta. Infatti nella profezia data a Giuda mentre Giacobbe stava per morire, disse, "Lo scettro non sar&agrave; rimosso da Giuda finch&eacute; venga colui al quale esso appartiene" (Genesi 49:10). In adempimento di questa promessa, Davide, un discendente di Giuda secondo la genealogia data nel libro di Rut, era il re, e la sua discendenza avrebbe regnato dopo di lui. Questo &egrave; lo scopo principale del libro. Dimostra anche, nella carriera di Davide, ancora pi&ugrave; che in quella di Saul, che la prosperit&agrave; aspetta un re mentre serve Dio, e l'avversit&agrave; invece viene con la disubbidienza. Infatti questo libro, a partire dal momento in cui Davide prende il trono, si divide in due parti molte diverse, che possiamo chiamare 'La prosperit&agrave; del regno di Davide' (capitoli 5-10) e 'L'avversit&agrave; di Davide (capitoli 12-24). Le due sezioni sono separate dal grande peccato che &egrave; stato associato con Davide dal giorno in cui fu scoperto fino ad adesso. La stessa lezione &egrave; insegnata nelle carriere di molti uomini importanti collegati con Davide. Ci&ograve; rende 2Samuele uno dei libri pi&ugrave; profittevoli per la lettura e riflessione nell'Antico Testamento.
</p><p>
Questo libro dimostra anche che il regno di Davide fu il periodo di maggiore attivit&agrave; letteratura in Israele, perch&eacute; pubblica alcune dei poemi di Davide collega la storia con il contenuto del libro dei Salmi, di cui molti furono scritte da lui. Impariamo anche dal libro delle Cronache che i profeti Samuele, Natan e Gad furono scrittori di azioni che inclusero "le prime e le ultime" (1Cronache 29:29-30). &Egrave; molto probabile che in questo periodo i libri di Rut e Giudici, e una grande parte di Samuele, siano stati scritti. Anche il libro del Giusto, che &egrave; menzionato solo due volte, una volta per dire che conteneva un racconto del comando di Giosu&egrave; di fermare il sole e la luna, e una volta per dire che conteneva il lamento da parte di Davide per la morte di Saul, fu probabilmente scritto in questo periodo, dato che non &egrave; menzionato nessun evento successivo. Era evidentemente un libro di gran valore e autorit&agrave;, sebbene fosse permesso che fosse perso.
</p><p>
Durante il regno di Davide, il lettore dovrebbe osservare che i messaggeri scelti da Dio per dichiarare la sua volont&agrave; di tanto in tanto, sia riguardo al governo sia riguardo alla moralit&agrave;, continuavano a esercitare autorit&agrave; anche sul re. Ci&ograve; fu vero soprattutto di Natan e Gad, di cui sappiamo poco oltre questo.
</p>
<p><a href="guida_domande.php#5">Domande di ripasso</a></p>
<p>Continua: <a href="regno_salomone_divisione.php">6. Il regno di Salomone e la divisione del regno</a></p>
<?
require("../piede.php");
?>