<?
$descriz = "Testimonianze sulla potenza della Bibbia, la Parola di Dio";
$key = "testimonianza,testimonianze";
$titolo = "Testimonianze";
$sezione = "Articoli";
$sezioneurl = "/intro/";
require("../capo.php");
?>
<h1>Testimonianze</h1>
<p class="primalettera">La Bibbia ha avuto un profondo effetto su molte persone nella storia. Qui ho raccolto alcuni esempi, per illustrare che non &egrave; solo un libro morto, ma che quando agisce ci pu&ograve; trasformare ancora oggi.</p>

<h2>Un racconto di Christy Wilson</h2>
<p>Christy Wilson fu un missionario in Afganistan per 35 anni. Mentre aspettava di poterci andare come insegnante di inglese, and&ograve; alla cerimonia di apertura dei giochi olimpici di Londra nel 1948. Lui racconta:</p>
<p>Ero nella tribuna, guardando le squadre delle diverse nazioni che marciavano davanti al re. Come tradizione, prima c'era la Grecia, e poi le altre nazioni in ordine alfabetico. Poi fui stupito quando arriv&ograve; Afganistan. Non sapevo che questo paese isolato partecipasse ai giochi. Fui entusiasta a vedere questi atleti inaspettati. Ma allo stesso tempo, sentivo un peso, desiderava fortemente di trovare un modo di raggiungere gli Afgani con il Vangelo. Pregai per loro mentre marciavano nello stadio, che potevo raggiungerli mentre erano ancora a Londra.</p>
<p>Il giorno seguente, and&ograve; alla Societ&agrave; Biblica e chiesi se avessero qualche Nuovo Testamento in persiano. Era la lingua pi&ugrave; vicina al dialetto dell'Afganistan. Risposero di s&igrave;. Chiesi alla Societ&agrave; Biblica se potessero dare una copia del Nuovo Testamento a tutti gli atleti afgani, siccome non erano disponibili nella loro nazione. Alla Societ&agrave; &egrave; piaciuta molto questa idea; anzi, proposero di dare un Nuovo Testamento a tutti gli atleti nella propria lingua. Offrirono pure di stampare ogni Testamento con il simbolo olimpico di cinque cerchi in oro. Cos&igrave; ci fu una distribuzione della Bibbia a tutti gli atleti.</p>
<p>Alcuni anni dopo, quando insegnavo inglese a Kabul in Afganistan, uno dei miei studenti chiese di vedermi in privato. Dopo la classe facemmo una passeggiata nel giardino della scuola. Quando eravamo da soli, mi disse che stava leggendo un libro interessante e che voleva pormi alcune domande sul libro. Dalla sua tasca tir&ograve; una copia del Nuovo Testamento in lingua persiana. Sulla copertina c'era il simbolo olimpico stampato in oro!</p>
<p>Uno degli altri afgani lo aveva portato da Londra e lo aveva prestato allo studente. Gli atleti afgani non vinsero nessuna medaglia d'oro, ma avevano ricevuto qualcosa di molto pi&ugrave; prezioso - la Parola di Dio.</p>
<p>Non so, alla fine, quello che sia successo a quello studente. Ma so che il Signore piant&ograve; un seme nel suo cuore e che Lui avrebbe continuato di operare in lui. Come dice Davide nei Salmi, le Scritture sono:</p>
<cite>sono pi&ugrave; desiderabili dell'oro, anzi, pi&ugrave; di molto oro finissimo;<br />
sono pi&ugrave; dolci del miele, anzi, di quello che stilla dai favi.<br />
Anche il tuo servo &egrave; da esse ammaestrato;<br />
v'&egrave; gran ricompensa a osservarli. (Salmo 19:10-11)</cite>
<p>C'&egrave; pi&ugrave; da desiderare che l'oro olimpico!</p>

<h2>Pastore Vsevolod Lytkin della Siberia</h2>
<p>I suoi professori erano professori atei all'universit&agrave; che insegnarono il loro figlio di &quot;pensare per s&eacute; stesso&quot;. Mentre adolescente, rifletteva molto su questioni spirituali. Ma quando i comunisti gli dissero che non c'era un dio, pens&ograve; che ci potesse un Dio e cos&igrave; inizi&ograve; una ricerca per materiale da leggere dove avrebbe potuto trovare qualche risposta.</p>
<p>Gli unici libri di religione disponibile alla biblioteca locale erano atei, ma citavano spesso versetti biblici per prenderli in giro o per contraddirli. La sua scoperta pi&ugrave; grande fu delle enciclopedie sull'ateismo da cui copi&ograve; ogni versetto della Bibbia a mano.</p>
<p>Fra poco cominci&ograve; a pregare Dio e gli chiese di perdonare i suoi peccati.</p>
<cite>La Parola di Dio non &egrave; incatenata (2Timoteo 2:9)</cite>

<h2>Subhan</h2>
<p>Un musulmano, Subhan studiava per diventare un sacerdote. Nella sua scuola, sentiva spesso i suoi professori attaccare il cristianesimo. Ma un giorno, tornando a casa, not&ograve; un foglietto per terra. Fu una pagina del Vangelo secondo Matteo, che descriveva la crocifissione e morte di Ges&ugrave;.</p>
<cite>Dio mio, Dio mio, perch&eacute; mi hai abbandonato?</cite>
<p>Lesse queste parole ripetutamente, perch&eacute; lo stupivano. Gli avevano insegnato che in realt&agrave; Ges&ugrave; Cristo non fu crocifisso, che fu invece Giuda. Ges&ugrave; era asceso in cielo prima della crocifissione.</p>
<p>Subhan continuava a leggere e rileggere quella frase. "Non sono le parole di Giuda", pens&ograve;. "Giuda avrebbe saputo perch&eacute; Dio l'aveva abbandonato. Non sono le parole di un uomo malvagio. Sono le parole di un uomo buono. Solo un uomo buono avrebbe chiesto, 'Dio mio, Dio mio, perch&eacute; mi hai abbandonato?'".</p>
<p>Ad un tratto, seppe che era veramente Cristo che era morto sulla croce, non Giuda. E accett&ograve; Ges&ugrave; come suo Salvatore.</p>
<p>Poco dopo, fu espulso dalla sua scuola musulmana, e anni dopo divent&ograve; il vescovo metodista in India.</p>

<h2>Rabbi Slostowski</h2>
<p>Come professore ad un seminario a Tel Aviv, odiava il Signore Ges&ugrave; Cristo. Il suo odio era cos&igrave; grande che critic&ograve; aspramente un giovane studente che leggeva un Nuovo Testamento in ebraico. Il giovane rispose dandogli una copia. Quella notte, il rabbino, da solo in camera sua, rimase sveglio fino alle tre leggendo del Nazareno che disse di essere il Messia. Lo Spirito Santo lo guid&ograve; alla verit&agrave;, e pi&ugrave; tardi disse, "Io ho gi&agrave; trovato pi&ugrave; di 200 brani del Nuovo Testamento che dimostrano che senza dubbio Ges&ugrave; &egrave; veramente il Messia.</p>

<h2>Ramad</h2>
<p>Ramad era un ladro di India. Una volta, mentre rubava, not&ograve; un piccolo libro nero che conteneva delle pagine sottili, perfette per fare delle sigarette, e lo prese.</p>
<p>Ogni sera strappava una pagina, la rotolava, ci metteva dentro del tabacco e fumava. Osservando che le piccole parole sulle pagine erano nella sua lingua, inizi&ograve; a leggerle prima di fare le sue sigarette. Una sera dopo aver letto una pagina, si inginocchi&ograve; e chiese al Signore Ges&ugrave; di perdonargli i peccati e di salvarlo. Poi si arrese alla polizia, che se ne stup&igrave;. Ramad il ladro divent&ograve; un seguace di Ges&ugrave; Cristo. E nella prigione in cui fu messo per i suoi crimini, condusse molti al Salvatore. La Parola di Dio divent&ograve; per Ramad <cite>la potenza di Dio per la salvezza (Romani 1:16)</cite>.</p>

<h2>San Agostino</h2>
<p>Nella primavera del 372, Agostino, uno dei pi&ugrave; pii dei Padri della Chiesa, quando aveva 31 anni, entr&ograve; nel suo giardino vicino Milano, molto turbato. I peccati della sua giovent&ugrave; - trascorsa in sensualit&agrave; e empiet&agrave; - pesavano sulla sua anima. Steso sotto un fico, gemendo e gridando con molte lacrime, ud&igrave;, da una casa vicina, una voce giovane che diceva e ripeteva, &quot;Tolle, lege, tolle, lege!&quot; (&quot;Prendi, leggi, prendi, leggi&quot;). Capendo questa voce come un'ammonizione divina, ritorn&ograve; a dove aveva lasciato il suo amico Alipio, per procurare il rotolo delle epistole di Paolo, che poco tempo prima aveva lasciato. &quot;Afferrai il rotolo&quot, disse descrivendo l'evento, &quot;lo aprii e lessi in silenzio il capitolo che mi capit&ograve;&quot;. Fu il tredicesimo capitolo di Romani.</p>
<cite>Comportiamoci onestamente, come in pieno giorno, senza gozzoviglie e ubriachezze; senza immoralit&agrave; e dissolutezza; senza contese e gelosie; ma rivestitevi del Signore Ges&ugrave; Cristo e non abbiate cura della carne per soddisfarne i desideri. (Romani 13:13-14)</cite>
<p>Tutto fu deciso da una parola. &quot;Non volli leggere pi&ugrave;&quot;, disse, &quot;e non ce n'era neanche bisogno; ogni dubbio fu bandito.&quot; La stella mattina era apparsa nel suo cuore. Ges&ugrave; lo aveva conquistato. Mor&igrave; nel suo 86o anno, dopo aver scritto molti libri importanti sul cristianesimo. Nella sua giovent&ugrave; scrisse favole poetiche e drammi, ma dopo la sua conversione dedic&ograve; la sua energia al servizio di Dio.</p>

<h2>Martin Lutero</h2>
<p>Quando era un giovane monaco, era assalito da tentazioni. Spesso non mangiava, beveva o dormiva per il conflitto che causavano nella sua mente, e pensava di essere abbandonato da Dio, come se Dio fosse il suo nemico. Un anno prima della sua morte, scrisse, "Dal tempo che frequentavo le scuole, sentivano mentre studiavo le epistole di San Paolo, un'ansiet&agrave; incredibile di capire il significato dell'epistola ai Romani. Ero bloccato da una frase:</p>
<cite>Poich&eacute; in esso [il Vangelo] la giustizia di Dio &egrave; rivelata. (Romani 1:17)</cite>
<p>Odiavo quella parola, la giustizia di Dio, perch&eacute; la capivo di quella giustizia attiva, mediante cui Dio era giusto e punisce gli ingiusti e i peccatori. Comportandomi come un monaco senza biasimo, ma disturbato dalla coscienza del peccatore, e incapace di sentirmi giustificato davanti a Dio, non potevo amare, anzi devo confessare, odiavo questo Dio giusto, il vendicatore del peccato. Ero arrabbiato, e mormoravo a me stesso, se non proprio bestemmiavo. Non basta, dicevo, che i peccati infelici, gi&agrave; persi eternamente a causa del peccato originale, sono sopraffatti da innumerevoli guai dalla Legge del decalogo, ma deve Dio continuare ad ammassare sofferenze, e minacciarci nel Vangelo con la sua giustizia e la sua ira?</p>
<p>Mentre meditavo giorno e notte sulle parole, <cite>Poich&eacute; in esso la giustizia di Dio &egrave; rivelata da fede a fede, com'&egrave; scritto: &laquo;Il giusto per fede vivr&agrave;&raquo;,</cite> Dio finalmente ha avuto piet&agrave; di me. Percepii che la giustizia Dio &egrave; quella giustizia mediante cui l'uomo giusto, tramite la bont&agrave; di Dio, vive, cio&egrave;, per FEDE; e che il significato del brano &egrave; che il Vangelo rivela la giustizia di Dio, una giustizia passiva, tramite cui la misericordia di Dio ci giustifica per fede. Mi sentii come se fossi nato di nuovo, e sembr&ograve; che entrassi per la porta del Paradiso. Un po' di tempo dopo, lessi l'opera di San Agostino, 'Della Lettera e dello Spirito', e scoprii, contrariamente alle mie aspettative, che anche lui dice che la giustizia di Dio &egrave; quella che Dio ci imputa giustificandoci."</p>

<h2>John Wesley</h2>
<p>Wesley divent&ograve; un diacono della Chiesa di Inghilterra nel 1725, e circa tre anni dopo divent&ograve; un prete. Nel 1735, viaggi&ograve; in America per predicare il cristianesimo. Cos&igrave; lo troviamo un ministro del Vangelo, predicatore da pi&ugrave; di 10 anni, completamente onesto e sincero, ma senza un cambiamento di cuore. Desiderando qualcosa di pi&ugrave; di essere dotto, lo cerc&ograve; nelle buone opere. Ecco come raccont&ograve; la sua esperienza:</p>
<p>Nel 1730 iniziai a visitare i carceri, ad aiutare i poveri e malati, ed a fare il buono che potevo ai corpi e alle anime degli altri. Rimossi le superficialit&agrave;, e qualche necessit&agrave;, della vita. La primavera seguente cominciai a osservare i digiuni di mercoled&igrave; e venerd&igrave; spesso osservati nella chiesa primitiva - non mangiavo prima delle 3 del pomeriggio. Allora non sapevo che cosa potessi fare di pi&ugrave;. Combattei diligentemente contro ogni peccato. Non tralasciai nessuna forma di autorinnegamento che era lecita. Usavo attentamente, sia in pubblico che in privato, ogni mezzo di grazia ad ogni opportunit&agrave;. Ma tutto questo lo sapevo di essere niente, se non fosse diretto verso una piet&agrave; interiore. Cos&igrave; cercai l'immagine di Dio, facendo la sua volont&agrave;, non la mia. Eppure, dopo diversi anni comportandomi in questo modo, quando mi trovai vicino alla morte, scoprii che questa grazia non mi dava nessun conforto, n&eacute; la sicurezza di essere accettato da Dio. Rimasi molto sorpreso, non credendo che per tutto questo tempo aveva costruito sulla sabbia, n&eacute; considerando che <cite>nessuno pu&ograve; porre altro fondamento oltre a quello gi&agrave; posto, cio&egrave; Cristo Ges&ugrave;</cite> (1Corinzi 3:11).
<p>Poco dopo, un uomo contemplativo mi convinse ancora di pi&ugrave; che le opere esteriori, se sole, non sono niente. Consigli&ograve; la preghiera interna, ed esercizi simili, come il mezzo pi&ugrave; efficace di purificare l'anima e di unirla a Dio. Per dire la verit&agrave;, questi esercizi furono in realt&agrave; la ricerca della mia giustizia, tanto quanto le mie buone opere ma con un altro nome. In questo modo raffinato di fidarmi delle mie opere e della mia giustizia (inculcata cos&igrave; zelosamente da scrittori mistici), proseguii pesantemente, non trovando nessun conforto o aiuto. Non conoscendo la giustizia di Cristo che, per mezzo di una fede vivente in lui, porta la salvezza <cite>di chiunque crede</cite> (Romani 1:16), cercai di stabilire la mia giustizia, e cos&igrave; mi affaticai nel fuoco tutti i miei giorni. In questo stato, combattevo di continuo ma non conquistavo. Prima, aveva volontariamente servito il peccato; allora non era volontariamente, ma lo servivo ancora. Combattevo contro il peccato, ma non ero liberato da esso, n&eacute; avevo la testimonianza dello Spirito con il mio spirito, e, infatti, non poteva averla perch&eacute; la cercavo non per fede, ma mediante le opere della legge.</p>
<p>Quando ritornai in Inghilterra in gennaio 1738, ero convinto che la causa dei miei problemi era l'incredulit&agrave;, e che ottenere una fede vera e vivente era la cosa di cui avevo bisogno. Ma non fissavo ancora questa fede sul suo oggetto giusto; volevo dire solo una fede in Dio, non fede in o mediante Cristo. Non sapevo di essere totalmente senza questa fede, solo che non ne avevo abbastanza. Quando quindi sentii che la vera fede in Cristo aveva due frutti, il dominio sul peccato e una pace costante da un senso di perdono, mi stupii, e pensai che fosse un nuovo Vangelo. Se fosse cos&igrave;, chiaramente non avevo fede. Ma non volevo esserne convinto.</p>
<p>Cos&igrave; consultai le Scritture. Quando misi da parte le aggiunte di altri, e considerai semplicemente le Parole di Dio, confrontandole, spiegando i brani difficili con quelli pi&ugrave; semplici, trovai quanto parlavano tutti contro di me. Fui completamente convinto e, per la grazia di Dio, risolsi di cercare la vera fede fino alla fine<br />
1. rinunciando ogni dipendenza, anche parziale, sulle mie opere o sulla mia giustizia, su cui avevo in realt&agrave; la mia salvezza fin dalla mia giovent&ugrave;, e<br />
2. aggiungendo all'utilizzo costante di tutti gli altri mezzi di grazia, la preghiera continua per questa cosa, la fede che giustifica e salva, una dipendenza totale sul sangue di Cristo sparso per me, una fiducia in lui come mio Cristo, la mia unica giustificazione, santificazione e redenzione.</p>
<p>Continuai cos&igrave; a cercarla (bench&eacute; con una strana indifferenza, freddezza e ritornando frequentemente al peccato) fino al 24 maggio, quando aprii il mio Testamento a queste parole: <cite>Ci sono state elargite le sue preziose e grandissime promesse perch&eacute; per mezzo di esse voi diventaste partecipi della natura</cite> (2Pietro 1:4). Dopo aver chiuso il libro, lo aprii di nuovo alle parole, <cite>Tu non sei lontano dal regno di Dio</cite> (Marco 12:34). Nel pomeriggio dello stesso giorno fui invitato ad andare alla cattedrale di San Paolo. L'inno fu, "Dal profondo ho chiamato te, o Signore; Signore, ascolta la mia voce". La sera andai non molto volontariamente ad un'associazione, dove qualcuno leggeva il prefazio di Lutero all'epistola ai Romani. Alle 9.15 circa, mentre descriveva il cambiamento che Dio opera nel cuore mediante la fede in Cristo, mi sentii il cuore stranamente riscaldato. Mi sentii che veramente mi fidavo in Cristo, in solo Cristo, per la salvezza: e un'assicurazione mi fu data, che aveva preso i miei peccati, anche i miei, e mi ha salvato dalla legge del peccato e della morte.</p>

<p><strong>Nota:</strong> Le seguenti due testimonianze sono prese dal libro <em>Desiderare Dio</em> di <a href="http://www.passaggio.org/">Passaggio</a>, pagine 154-156.</p>
<h2>Little Bilney</h2>
<p>Uno dei primi riformati inglesi, nato nel 1495, studiava legge ed era esteriormente rigoroso nei suoi sforzi verso la religione. Ma dentro non c'era vita. Poi gli capit&ograve; di ricevere una traduzione latina del Nuovo Testamento greco di Erasmo. Ecco cosa successe:</p>
<cite>Per caso incrociai questa frase di S. Paolo (Oh, che frase dolce e confortante per l'anima mia!) in 1Timoteo 1: &quot;Certa &egrave; quest'affermazione e degna di essere pienamente accettata: che Cristo Ges&ugrave; &egrave; venuto nel mondo per salvare i peccatori, dei quali io sono il primo&quot;. Questa frase, attraverso l'istruzione di Dio e la sua opera interiore, che allora non percepivo, rallegr&ograve; a tal punto il mio cuore, essendo prima ferito dalla colpa dei miei peccati e quasi nella disperazione, che... immediatamente... sentii uno straordinario sollievo e quiete, cos&igrave; che &quot;le mie ossa ammaccate saltarono di gioia&quot;. Dopo di questo, le Scritture divennero per me pi&ugrave; piacevoli del miele o del nido d'api.</cite>

<h2>Tokichi Ichii</h2>
<p>Ichii era un uomo impiccato per omicidio a Tokio nel 1918. Era stato incarcerato pi&ugrave; di venti volte ed era conosciuto per avere la crudelt&agrave; di una tigre. In un'occasione, dopo aver attaccato una guardia, venne imbavagliato e legato, e il suo corpo venne sospeso cos&igrave; che &quot;le dita dei piedi toccavano a fatica in terra&quot;. Ma testardamente si rifiutava di dirsi dispiaciuto per quello che aveva fatto.</p>
<p>Poco prima di essere condannato a morte, a Tokichi venne inviato un Nuovo Testamento da parte di due missionarie cristiane, dalla signora West e dalla signora McDonald. Dopo una visita da parte di West, inizi&ograve; a leggere la storia del processo e dell'esecuzione di Ges&ugrave;. La sua attenzione fu attirata dalla frase &quot;E Ges&ugrave; disse: &laquo;Padre, perdona loro perch&eacute; non sanno quello che fanno&raquo;&quot;. Questa frase trasform&ograve; la sua vita.</p>
<cite>Mi fermai: ero stato colpito al cuore, come da un chiodo di dieci centimetri. Cosa mi aveva rivelato il versetto? Posso chiamarlo l'amore del cuore di Cristo? Posso chiamarlo la sua compassione? Non so come chiamarlo. So solo che con un cuore indescrivibilmente grato avevo creduto.</cite>
<p>Tokichi era stato condannato a morte e accett&ograve; questo fatto come &quot;il giusto, imparziale giudizio di Dio&quot. Ora la stessa Parola che lo aveva portato alla fede lo sosteneva anche in una maniera meravigliosa. Vicino alla fine, West gli indic&ograve; le parole di 2Corinzi 6:8-10 riguardo alla sofferenza del giusto. Quelle parole lo commossero profondamente, ed egli scrisse:</p>
<cite>&quot;Come afflitti, eppure sempre allegri&quot. La gente dir&agrave; che devo avere un cuore molto addolorato perch&eacute; aspetto ogni giorno l'esecuzione della mia pena di morte. Non &egrave; cos&igrave;. Non provo n&eacute; dolore, n&eacute; angoscia, n&eacute; sofferenza. Chiuso in una cella di due metri per tre, sono infinitamente pi&ugrave; felice di quando ero nel peccato, quando non conoscevo Dio. Giorno e notte... io parlo con Ges&ugrave; Cristo.<br />
&quot;Come poveri, eppure arricchendo molti&quot. Ci&ograve; sicuramente non si applica alla vita malvagia che conducevo prima di pentirmi. Ma, forse in futuro, qualcuno nel mondo potrebbe sentire che il malfattore pi&ugrave; disperato, che sia mai vissuto, si pent&igrave; dei suoi peccati e venne salvato dalla potenza di Cristo, e anche lui potrebbe raggiungere il pentimento. Allora succederebbe che io, bench&eacute; povero, potrei rendere molti ricchi.</cite>
<p>La Parola lo sostenne fino alla fine; sul patibolo, con umilt&agrave; e scrupolo, profer&igrave; le ultime parole: &quot;La mia anima, purificata, oggi ritorna alla Citt&agrave; di Dio&quot.</p>

<h2>Io</h2>
<p>Ho pensato che potesse essere utile aggiungere l'effetto della Bibbia sulla mia vita.</p>
<p>Io sono cresciuto abbastanza religioso, frequentando una chiesa come bambino (mandato ai miei genitori, che ritenevano che fosse giusto che io ricevessi un insegnamento spirituale, anche se loro non ci andavano quasi mai). Ma sentire non &egrave; comprendere, e bench&eacute; io sia sicuro che mi insegnarono l'importanza di un rapporto vero e personale con Dio; io imparai i fatti della Bibbia senza comprendere o accettare il suo messaggio. Ma quando avevo 14 anni, alcuni insegnanti della mia scuola mi spiegarono il messaggio della Bibbia, che ero separato da Dio a causa della mia ribellione contro di lui, e che la mia unica speranza per diventare un amico di Dio era di credere in Ges&ugrave; Cristo, che &egrave; morto prendendo la punizione per la mia ribellione. Avendo capito il messaggio della Bibbia, lo credetti e mi fidai di Ges&ugrave; come mio Salvatore e Signore.</p>
<p>I primi anni della mia vita di seguace di Cristo furono, per&ograve;, molto aridi, perch&eacute; non leggevo la Bibbia e quindi non riceveva insegnamento, riprensione, correzione, educazione o preparazione per ogni opera buona (2Timoteo 3:16-17), e perch&eacute; non avevo comunione con altri che credevano nella Bibbia per essere aiutato da loro. Ma dopo qualche anno cominciai a frequentare un gruppo di giovani della mia chiesa locale, dove ogni settimana studiavamo la Bibbia insieme, e, dopo l'incoraggiamento in una predica una domenica, iniziai a leggere la Bibbia ogni giorno per me stesso. Cos&igrave;, mentre le altre testimonianze su questa pagina illustrano l'effetto della Parola di Dio su diverse persone quando credettero, io voglio testimoniare che la Bibbia &egrave; essenziale anche per quelli che sono gi&agrave; Cristiani, perch&eacute; o direttamente o indirettamente (tramite insegnanti della Bibbia) &egrave; il modo in cui si cresce come discepolo di Cristo, perch&eacute;, come ha detto Ges&ugrave;,</p>
<cite>Se perseverate nella mia parola, siete veramente miei discepoli (Giovanni 8:31).</cite>
<?
require("../piede.php");
?>