<?
$descriz = "Guida allo studio della Bibbia: I Vangeli e gli Atti";
$key = "vangeli,atti,matteo,marco,luca,giovanni,studio,studio biblico,guida,McGarvey";
$titolo = "Guida allo studio della Bibbia 14. I Vangeli e gli Atti";
$sezione = "Articoli";
$sezioneurl = "/intro/";
require("../capo.php");
include("../funzioni.php");
?>
<h1><a href="guida_studio_bibbia.php">Guida allo studio della Bibbia</a></h1>

<h2>14. I Vangeli e gli Atti</h2>
<p>
Questi non sono i primi libri scritti nel Nuovo Testamento perch&eacute;, come vedremo pi&ugrave; avanti, alcune delle lettere di Paolo furono scritte prima; ma sono primi nell'ordine degli eventi che raccontano, e per questo motivo occupano giustamente la prima parte del Nuovo Testamento. Avendo descritto in precedenza il loro piano generale, adesso li consideriamo separatamente.
</p>
<h3>1. Matteo</h3>
<p>
Questo scrittore presenta Ges&ugrave; nel primo versetto del libro come "figlio di Davide, figlio di Abraamo" (Matteo 1:1). Con questo titolo Matteo afferma che Ges&ugrave; &egrave; il discendente promesso di Davide che si sarebbe seduto sul suo trono e avrebbe regnato per sempre, e ricorda anche la promessa antica ad Abraamo di un discendente in cui tutte le nazioni sarebbero state benedette. In altre parole, &egrave; presentato come il Messia, cio&egrave; il Cristo, e dimostra che lo scopo principale di Matteo era di spiegare Ges&ugrave; come Messia, piuttosto di sottolineare la sua divinit&agrave;. Con questo concorda il contenuto del libro; perch&eacute; mentre il fatto che Ges&ugrave; &egrave; il Figlio di Dio non &egrave; affatto trascurato nella narrativa, anzi &egrave; chiaramente spiegato, il fatto che &egrave; Messia &egrave; lo scopo principale. Per questo motivo ci sono molte citazioni dall'Antico Testamento di predizioni e di tipi adempiuti nella persona e nell'opera di Ges&ugrave;. Matteo ha pi&ugrave; citazioni di tutti e tre gli altri Vangeli messi insieme. In armonia con questo scopo Matteo dedica pi&ugrave; spazio degli altri Vangeli all'insegnamento di Ges&ugrave;; molto pi&ugrave; della met&agrave; del libro &egrave; composta da discorsi, oltre i molti commenti fatti da Ges&ugrave; durante conversazioni con amici e nemici. Infatti, uno scrittore cristiano del secondo secolo chiam&ograve; questo libro "Gli oracoli", volendo dire affermazioni divine. Ci&ograve; fu un tentativo di dare un nome al libro derivato dalla maggior parte del suo contenuto. come conseguenza di questa caratteristica del libro, e per il fatto che &egrave; all'inizio del Nuovo Testamento, Matteo &egrave; letto di pi&ugrave; ed &egrave; pi&ugrave; conosciuto degli altri Vangeli.
</p><p>
Il libro si divide in modo naturale in tre parti: la prima (Matteo 1:1-4:12) d&agrave; la genealogia di Ges&ugrave;, la sua nascita, alcuni degli eventi della sua infanzia, il suo battesimo e la sua tentazione; la seconda il suo ministero nella Galilea (Matteo 4:13-19:1); e la terza gli eventi dalla sua partenza dalla Galilea fino alla sua risurrezioni dei morti (Matteo 19:1-28:20). L'ultima parte, sebbene occupi solo sei mesi dei tre anni del suo ministero, &egrave; lunga quasi quanto il racconto dell'intero periodo prima, dimostrando l'importanza secondo l'autore delle sofferenze, della morte e della risurrezione del Signore.
</p><p>
Il Vangelo secondo Matteo fu rivolto soprattutto ai Giudei, e quindi usa il contenuto dell'Antico Testamento che ha a che fare con la vita di Cristo. &Egrave; il Vangelo nazionale, e i suoi temi sono Ges&ugrave; il Messia, il maestro e il re respinto.
</p>
<h3>2. Marco</h3>
<p>
Questo scrittore non era un apostolo, ma era il figlio di una donna di Gerusalemme chiamata Maria, nella casa di cui i primi Cristiani si riunivano (Atti 12:12). Lei era la zia di Barnaba, dato che Marco era suo cugino (Colossesi 4:10). Essendo cresciuto a Gerusalemme, dove sua madre aveva un ruolo importante nella chiesa, doveva conoscere gli apostoli, e probabilmente anche Ges&ugrave;. Alcuni dei primi scrittori cristiani dicono che per scrivere il suo Vangelo si serv&igrave; del racconto di Ges&ugrave; che Pietro dava nei suoi discorsi, e diverse cose nella narrativa confermano questo, soprattutto il fatto che racconta chiaramente tutto quello di negativo che Pietro disse o fece, e omette quasi tutto quello di positivo. Era cos&igrave; che Pietro avrebbe voluto se fosse cos&igrave; modesto che supponiamo che lui fosse.
</p><p>
Marco presenta Ges&ugrave; subito come Figlio di Dio, dicendo nella prima frase del suo libro, "Inizio del vangelo di Ges&ugrave; Cristo Figlio di Dio" (Marco 1:1). Questo dimostra che il suo scopo principale era di dimostrare la divinit&agrave; di Ges&ugrave;, invece di dimostrare che era il Messia. In questo &egrave; diverso da Matteo, e per raggiungere il suo scopo dedica molto pi&ugrave; spazio ai miracoli pi&ugrave; degli altri tre Vangeli, dato che sono questi, piuttosto che le profezie adempiute, che dimostrano la sua divinit&agrave;. Inizia in modo diverso da Matteo, in quanto comincia con la predicazione di Giovanni il battista mentre Matteo comincia con la genealogia e la nascita di Ges&ugrave;.
</p><p>
Nessuno che conosce il Vangelo secondo Matteo pu&ograve; leggere Marco senza notare che sono molto simili nei fatti che raccontano, e a volte anche nelle parole utilizzate. Ma un confronto attento riveler&agrave; che in quasi tutti questi casi Marco ha qualche fatto addizionale che distingue il suo racconto da quello di Matteo. Lo studente dovrebbe sempre stare attento a queste differenze, perch&eacute; mostrano non solo le differenze fra i due autori, ma sono necessari per una conoscenza completa degli eventi che descrivono. Possiamo dire lo stesso per quanto riguardo tutti gli avvenimenti raccontati da tre o da tutti e quattro i Vangeli. Studia tutti, e unisci i dettagli dati da ognuno.
</p><p>
Il libro di Marco &egrave; diviso in due parti. La prima parte racconta il ministero nella Galilea, come la seconda parte di Matteo; la seconda parte, dopo alcune conversazioni oltre il fiume Giordano, racconta le ultime azioni a Gerusalemme. A questa seconda parte, bench&eacute; raccontasse il periodo di solo sei mesi, Marco dedica sette dei suoi 16 capitoli, cos&igrave; dimostrando, similmente a Matteo, che era la parte della vita di Ges&ugrave; pi&ugrave; importante per i lettori. Luca e Giovanni hanno uno schema simile.
</p><p>
Il Vangelo secondo Marco &egrave; stato chiamato il Vangelo di Potenza. Ges&ugrave; fa miracoli ed &egrave; l'incarnazione di potenza. Come tale, il libro era adatto alla mentalit&agrave; romana, per cui la potenza era importante.
</p>
<h3>3. Luca</h3>
<p>
Il terzo Vangelo &egrave; diverso dai primi due, anche se Matteo e Marco sono diversi. Narra alcuni eventi gi&agrave; descritti negli altri due, ma il tema dell'autore &egrave; piuttosto diverso. Confrontando i suoi racconti con quelli degli altri due Vangeli, le differenze a volte sembrano contraddizioni, e sono state dichiarate tali da alcuni. Ma non &egrave; giusto accusare due o pi&ugrave; scrittori di contraddirsi, ci&ograve; significherebbe accusarne uno di aver errato, quando un'ipotesi ragionevole permetterebbe di capire che tutte le loro affermazioni sono vere. A volte dobbiamo studiare molto attentamente per trovare una tale ipotesi, ma dovremmo farlo quando possiamo, e non dobbiamo essere troppo veloci ad accusare loro di contraddizioni. Ci&ograve; &egrave; giusto verso tutti gli scrittori e oratori, e dovremmo ancora di pi&ugrave; fare cos&igrave; verso gli scrittori ispirati del Nuovo Testamento.
</p><p>
La prima parte del Vangelo secondo Luca, come quello di Matteo, tratta la prima parte della vita di Ges&ugrave;, concludendo con la sua tentazione; lo spazio usato &egrave; pi&ugrave; o meno uguale a quello usato da Matteo, ma Luca lo riempie con eventi quasi tutti diversi da quelli raccontati da Matteo. Per imparare tutto quello che possiamo su questa parte della vita del nostro Signore, dobbiamo studiare la prima parte di Luca insieme con quella di Matteo, e lo studente farebbe bene a farlo prima di leggere oltre in questo Vangelo.
</p><p>
Nella seconda parte, Luca presta la sua attenzione, come Matteo e Marco, al ministero di Ges&ugrave; nella Galilea, non dicendo niente di alcuni viaggi a Gerusalemme fatti in questo periodo di cui abbiamo conoscenza dal Vangelo secondo Giovanni. Questa sezione va da Luca 4:14 a Luca 9:62, che &egrave; pi&ugrave; corta della stessa sezione in Matteo e Marco. Poi segue la parte di Luca in cui lo scrittore ci d&agrave; informazioni nuove; questa sezione &egrave; tutta molto istruttiva. Questa parte include i capitoli dal 10 al 18, cio&egrave; pi&ugrave; lungo delle altre parti. La sua ultima o quarta parte, come quella degli altri due Vangeli, racconta gli eventi degli ultimi sei mesi, ed &egrave; composta dagli ultimi sei capitoli.
</p><p>
Luca era un medico, un fatto che impariamo da Paolo (Colossesi 4:14); e siccome Paolo in questo brano lo distingue da quelli che "provengono dai circoncisi" (Colossesi 4:10,14), si deduce che Luca era un Gentile. Se &egrave; cos&igrave;, era l'unico Gentile che ha scritto una parte del Nuovo Testamento. Come Marco, non era un apostolo, e come conseguenza non scrisse come testimone oculare; ma ci informa, nel primo paragrafo del libro, che ottenne le sue informazioni da testimoni oculari, e che controll&ograve; tutto fino dall'inizio. Siccome il suo libro &egrave; indirizzato ad un certo Teofilo, che &egrave; un nome greco, sembra che abbia scritto soprattutto per un pubblico greco. Si rivolge a Teofilo con il titolo "illustre" (Luca 1:3), il solito modo per rivolgersi ad un uomo di alto grado nel mondo politico, per cui sembra che almeno alcune tali persone facessero parte della chiesa quando il Vangelo secondo Luca fu scritto.
</p><p>
Tutti e tre questi Vangeli furono scritti non prima del 60 d.C.
</p><p>
Il Vangelo secondo Luca &egrave; la sua introduzione alla storia della chiesa primitiva e del ministero di Paolo, cio&egrave; il libro degli Atti. Il Vangelo sottolinea l'amore e la compassione di Ges&ugrave; per l'umanit&agrave;. &Egrave; il Vangelo della societ&agrave;.
</p>
<h3>4. Giovanni</h3>
<p>
Il quarto Vangelo &egrave; molto diverso dagli altri tre, che sono piuttosto simili tra di loro. I primi tre sono chiamati dagli studiosi 'sinottici', cio&egrave; che hanno lo stesso punto di vista. Ma Giovanni evit&ograve; di scrivere quello che gli altri avevano scritto, in modo che ci siano pochi eventi in comune; e quando ci sono, lui racconta dettagli che gli altri omettono. Questa differenza &egrave; spiegata dal fatto che, scrivendo dopo, Giovanni aveva visto quello che gli altri avevano scritto e non voleva ripeterlo. Gli altri senza dubbio scrissero di quelli avvenimenti nella vita del Salvatore che erano stati raccontati dagli apostoli nella loro predicazione.
</p><p>
Il Vangelo di Giovanni &egrave; l'unico che &egrave; cronologico. Contando le feste dei Giudei che Ges&ugrave; frequent&ograve; menzionate in questo Vangelo, accertiamo che ci furono tre anni dalla visita a Gerusalemme menzionata nel secondo capitolo fino a quella in cui fu crocifisso. Se sapessimo quanto tempo pass&ograve; dal suo battesimo a quella prima visita, sapremmo la durata precisa del suo ministero; ma a quel punto non c'&egrave; una cronologia.
</p><p>
Giovanni inizia con una dichiarazione molto profonda dell'esistenza eterna e divina di Ges&ugrave; prima del suo avvento nel mondo; e in armonia con questo inizio fa della divinit&agrave; del Signore il tema pi&ugrave; importante del suo libro, piuttosto che presentare Ges&ugrave; come Messia. In questo &egrave; simile a Marco, ma diversamente da Marco menziona relativamente poco i miracoli, e usa invece come evidenza principalmente quello che Ges&ugrave; disse di s&eacute; stesso. Come conseguenza, troviamo Ges&ugrave; in questo Vangelo parla di pi&ugrave; di s&eacute; stesso come Figlio di Dio che negli altri Vangeli.
</p><p>
Un fatto incredibile del Vangelo secondo Giovanni &egrave; che tutti gli eventi che racconta si svolsero in un totale di solo 30 giorni, bench&eacute; il periodo dal primo all'ultimo fu di pi&ugrave; di 30 anni. In Marco troviamo gli eventi di solo sette o otto giorni di pi&ugrave;, se escludiamo i 40 della tentazione, e in Luca e Matteo meno di 100. Uno qualsiasi dei quattro, stampato separatamente, farebbe un piccolo libretto.
</p><p>
Il Vangelo secondo Giovanni &egrave; il Vangelo universale, il Vangelo dell'incarnazione, il Vangelo di conoscenza spirituale. &Egrave; il Vangelo del cuore di Cristo, in confronto con la scrittura pi&ugrave; obiettiva dei Sinottici.
</p>
<h3>5. Atti degli Apostoli</h3>
<p>
Questo libro giustamente segue i quattro Vangeli nel nostro Nuovo Testamento stampato, non perch&eacute; fu scritto dopo, perch&eacute; in realt&agrave; fu scritto nello stesso periodo dei primi tre Vangeli, e molto prima del quarto; ma perch&eacute; invece gli eventi raccontati si svolsero subito dopo quelli dei Vangeli. Dopo la risurrezione, che conclude tutti i Vangeli, Ges&ugrave; diede agli apostoli il loro mandato di andare e predicare, avendo loro proibito di fare cos&igrave; mentre era ancora vivo. Questo libro narra i loro viaggi e la loro predicazione al mondo in ubbidienza a questo comando. Inoltre, spiega come persone che sentivano la predicazione apostolica furono portati a Cristo e diventarono membri della sua chiesa. Come i Vangeli hanno lo scopo di convincere le persone che Ges&ugrave; &egrave; il Cristo, il Figlio di Dio, che &egrave; il primo passo per diventare un Cristiano, cos&igrave; questo libro spiega gli altri passi che gli apostoli richiedevano loro di prendere. per questi motivi, questo libro che racconta soprattutto delle conversioni &egrave; il libro da leggere dopo i Vangeli.
</p><p>
Questo libro spiega come chiese furono fondate dagli apostoli, e come alcune questioni molto importanti furono decise. In queste cose &egrave; una guida che ispira per tutto il futuro. Narra anche alcune delle azioni pi&ugrave; nobili dei primi discepoli per il nostro incoraggiamento, e delle peggiori per il nostro avvertimento.
</p><p>
Come i Vangeli, il libro degli Atti omette molto di pi&ugrave; di quanto racconta, perch&eacute; dopo un breve racconto delle attivit&agrave; di tutti gli apostoli a Gerusalemme, parla soprattutto dell'opera di Pietro e poi, dal tredicesimo capitolo, diventa come una biografia seguendo quasi esclusivamente l'opera dell'apostolo Paolo. Quest'ultima caratteristica era anche dovuta, dal punto di vista umano, al fatto che l'autore conosceva meglio l'opera di Paolo che quella degli altri apostoli, e dal punto di vista divino al fatto che l'opera di Paolo, dopo che era diventato apostolo, era pi&ugrave; grande e pi&ugrave; importante di quella degli altri. Dalla natura del suo contenuto, quindi, troviamo che il libro non &egrave; gli Atti degli apostoli, ma il titolo corretto sarebbe Alcuni atti di alcuni apostoli. Il fatto che pochi atti sono raccontati pu&ograve; essere dedotto dal fatto che sebbene parla di un periodo di circa 30 anni dalla risurrezione di Cristo fino all'anno 63 d.C., il contenuto occupa lo spazio di solo un piccolo libretto.
</p>
<p><a href="guida_domande.php#14">Domande di ripasso</a></p>
<p>Continua: <a href="epistole_paolo.php">15. Le epistole di Paolo</a></p>
<?
require("../piede.php");
?>