//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaParola {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LaParolaRisorse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LaParolaRisorse() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaParola.LaParolaRisorse", typeof(LaParolaRisorse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        internal static string AboutCaption {
            get {
                return ResourceManager.GetString("AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete all the bookmarks in this file?.
        /// </summary>
        internal static string BookmarkDelete {
            get {
                return ResourceManager.GetString("BookmarkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file already exists. Replace it?.
        /// </summary>
        internal static string BookmarkFileExists {
            get {
                return ResourceManager.GetString("BookmarkFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error opening the file: {0}.
        /// </summary>
        internal static string BookmarkImportFileError {
            get {
                return ResourceManager.GetString("BookmarkImportFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imported Bookmarks.
        /// </summary>
        internal static string BookmarkImportName {
            get {
                return ResourceManager.GetString("BookmarkImportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No Bible references were found..
        /// </summary>
        internal static string BookmarkImportNoReference {
            get {
                return ResourceManager.GetString("BookmarkImportNoReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error accessing the web page: {0}.
        /// </summary>
        internal static string BookmarkImportWebError {
            get {
                return ResourceManager.GetString("BookmarkImportWebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address of the web page:.
        /// </summary>
        internal static string BookmarkImportWebInputCaption {
            get {
                return ResourceManager.GetString("BookmarkImportWebInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Import from a Web page.
        /// </summary>
        internal static string BookmarkImportWebInputTitle {
            get {
                return ResourceManager.GetString("BookmarkImportWebInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New.
        /// </summary>
        internal static string BookmarkNew {
            get {
                return ResourceManager.GetString("BookmarkNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add &amp;Bible.
        /// </summary>
        internal static string BrowseAddBible {
            get {
                return ResourceManager.GetString("BrowseAddBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add &amp;Commentary.
        /// </summary>
        internal static string BrowseAddCommentary {
            get {
                return ResourceManager.GetString("BrowseAddCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Back.
        /// </summary>
        internal static string BrowseBack {
            get {
                return ResourceManager.GetString("BrowseBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Forward.
        /// </summary>
        internal static string BrowseForward {
            get {
                return ResourceManager.GetString("BrowseForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Bookmark .
        /// </summary>
        internal static string BrowsePopupBookmark {
            get {
                return ResourceManager.GetString("BrowsePopupBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Copy.
        /// </summary>
        internal static string BrowsePopupCopy {
            get {
                return ResourceManager.GetString("BrowsePopupCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In&amp;formation on .
        /// </summary>
        internal static string BrowsePopupInfoVerse {
            get {
                return ResourceManager.GetString("BrowsePopupInfoVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Information on .
        /// </summary>
        internal static string BrowsePopupInfoWord {
            get {
                return ResourceManager.GetString("BrowsePopupInfoWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a N&amp;ote on .
        /// </summary>
        internal static string BrowsePopupNoteVerse {
            get {
                return ResourceManager.GetString("BrowsePopupNoteVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Note on .
        /// </summary>
        internal static string BrowsePopupNoteWord {
            get {
                return ResourceManager.GetString("BrowsePopupNoteWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Print Selection.
        /// </summary>
        internal static string BrowsePopupPrint {
            get {
                return ResourceManager.GetString("BrowsePopupPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Search.
        /// </summary>
        internal static string BrowsePopupSearch {
            get {
                return ResourceManager.GetString("BrowsePopupSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a to.
        /// </summary>
        internal static string BrowseTo {
            get {
                return ResourceManager.GetString("BrowseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You need to choose a word, not an asterisk..
        /// </summary>
        internal static string ChooseWordErrorWordNotChosen {
            get {
                return ResourceManager.GetString("ChooseWordErrorWordNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type &quot;help&quot; at the command line for the allowed commands and syntax..
        /// </summary>
        internal static string CommandlineGetHelp {
            get {
                return ResourceManager.GetString("CommandlineGetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This is a list of the possible commands for the command line, with the necessary syntax.\par
        ///The words in {\i italics} have to be substitued with whatever you want to use.\par
        ///The parts in [square brackets] are optional.\par
        ///For {\i text}, you can use the name of a translation of the Bible or collection of notes (and only in that case you         ///
        ///have to correctly type the upper and lower case letters) or the abbreviation of a translation or collection. If one         ///
        ///is not given, the last translation is used (th [stringa troncata]&quot;;.
        /// </summary>
        internal static string CommandlineHelp {
            get {
                return ResourceManager.GetString("CommandlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There is a syntax error in the command..
        /// </summary>
        internal static string CommandlineSyntaxError {
            get {
                return ResourceManager.GetString("CommandlineSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The command {0} is unknown..
        /// </summary>
        internal static string CommandlineUnknownCommand {
            get {
                return ResourceManager.GetString("CommandlineUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} is not a Bible version or collection of notes..
        /// </summary>
        internal static string CommandlineUnknownText {
            get {
                return ResourceManager.GetString("CommandlineUnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Concordance created..
        /// </summary>
        internal static string ConcordanceCompleted {
            get {
                return ResourceManager.GetString("ConcordanceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creating the concordance:.
        /// </summary>
        internal static string ConcordanceCurrent {
            get {
                return ResourceManager.GetString("ConcordanceCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Concordance of.
        /// </summary>
        internal static string ConcordanceTitle {
            get {
                return ResourceManager.GetString("ConcordanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Definitions shown..
        /// </summary>
        internal static string DefinitionsCompleted {
            get {
                return ResourceManager.GetString("DefinitionsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finding the definitions:.
        /// </summary>
        internal static string DefinitionsCurrent {
            get {
                return ResourceManager.GetString("DefinitionsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file {0} could not be opened: {1}.
        /// </summary>
        internal static string EditorErrorCantOpenFile {
            get {
                return ResourceManager.GetString("EditorErrorCantOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file {0} could not be saved: {1}.
        /// </summary>
        internal static string EditorErrorCantSaveFile {
            get {
                return ResourceManager.GetString("EditorErrorCantSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file {0} could not be opened: {1}.
        /// </summary>
        internal static string EditorErrorCantStartFile {
            get {
                return ResourceManager.GetString("EditorErrorCantStartFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The search item &apos;{0}&apos; was not found..
        /// </summary>
        internal static string EditorFindNotFound {
            get {
                return ResourceManager.GetString("EditorFindNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Line: {0} Col: {1}.
        /// </summary>
        internal static string EditorPosition {
            get {
                return ResourceManager.GetString("EditorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save the changes to {0}?.
        /// </summary>
        internal static string EditorSaveChanges {
            get {
                return ResourceManager.GetString("EditorSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text Files (*.rtf; *.txt)|*.rtf;*.txt|All Files (*.*)|*.*.
        /// </summary>
        internal static string EditorSaveFilter {
            get {
                return ResourceManager.GetString("EditorSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text exported..
        /// </summary>
        internal static string ExportCompleted {
            get {
                return ResourceManager.GetString("ExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exporting the text:.
        /// </summary>
        internal static string ExportCurrent {
            get {
                return ResourceManager.GetString("ExportCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Image Files (*.bmp; *.gif; *.ico; *.jpg; *.png; *.tif)|*.bmp;*.gif;*.ico;*.jpg;*.png;*.tif|All Files (*.*)|*.*.
        /// </summary>
        internal static string ImagesFilter {
            get {
                return ResourceManager.GetString("ImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The collection of notes to which this image is linked ({0}) was not found..
        /// </summary>
        internal static string ImmaginiCollezioneNonTrovata {
            get {
                return ResourceManager.GetString("ImmaginiCollezioneNonTrovata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Writing of {0} completed..
        /// </summary>
        internal static string ImportCompleted {
            get {
                return ResourceManager.GetString("ImportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Writing {0}:.
        /// </summary>
        internal static string ImportCurrent {
            get {
                return ResourceManager.GetString("ImportCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose the directory that contains the files with the notes:.
        /// </summary>
        internal static string ImportDirectoryDescription {
            get {
                return ResourceManager.GetString("ImportDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error in the imported file: {0}.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error in the line {1} in the file radici_diverse: {0}.
        /// </summary>
        internal static string ImportErrorDifferentRoots {
            get {
                return ResourceManager.GetString("ImportErrorDifferentRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file is password protected, and this program can not import such files..
        /// </summary>
        internal static string ImportErrorPassword {
            get {
                return ResourceManager.GetString("ImportErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a e-Sword Files (*.bbl; *.cmt; *.dct; *.top)|*.bbl; *.cmt; *.dct; *.top|All Files (*.*)|*.*.
        /// </summary>
        internal static string ImportEswordFilter {
            get {
                return ResourceManager.GetString("ImportEswordFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text Files (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        internal static string ImportTextFilter {
            get {
                return ResourceManager.GetString("ImportTextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unrecognised code: {0}.
        /// </summary>
        internal static string ImportUnknownCode {
            get {
                return ResourceManager.GetString("ImportUnknownCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a XML Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string ImportXmlFilter {
            get {
                return ResourceManager.GetString("ImportXmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bible.
        /// </summary>
        internal static string InformationBible {
            get {
                return ResourceManager.GetString("InformationBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All.
        /// </summary>
        internal static string InformationBiblesAll {
            get {
                return ResourceManager.GetString("InformationBiblesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bookmarks.
        /// </summary>
        internal static string InformationBookmarks {
            get {
                return ResourceManager.GetString("InformationBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Collection.
        /// </summary>
        internal static string InformationCollection {
            get {
                return ResourceManager.GetString("InformationCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All.
        /// </summary>
        internal static string InformationCommentariesAll {
            get {
                return ResourceManager.GetString("InformationCommentariesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Commentary.
        /// </summary>
        internal static string InformationCommentary {
            get {
                return ResourceManager.GetString("InformationCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Concordance.
        /// </summary>
        internal static string InformationConcordance {
            get {
                return ResourceManager.GetString("InformationConcordance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Definitions.
        /// </summary>
        internal static string InformationDefinitions {
            get {
                return ResourceManager.GetString("InformationDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Image.
        /// </summary>
        internal static string InformationImage {
            get {
                return ResourceManager.GetString("InformationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a External Links.
        /// </summary>
        internal static string InformationLinks {
            get {
                return ResourceManager.GetString("InformationLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Note.
        /// </summary>
        internal static string InformationNote {
            get {
                return ResourceManager.GetString("InformationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parallel Passages.
        /// </summary>
        internal static string InformationParallels {
            get {
                return ResourceManager.GetString("InformationParallels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a References.
        /// </summary>
        internal static string InformationReferences {
            get {
                return ResourceManager.GetString("InformationReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Similar Passages.
        /// </summary>
        internal static string InformationSimilar {
            get {
                return ResourceManager.GetString("InformationSimilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure that you want to delete {0}?.
        /// </summary>
        internal static string LinksConfirmDelete {
            get {
                return ResourceManager.GetString("LinksConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error deleting the file {0}: {1}.
        /// </summary>
        internal static string LinksErrorDelete {
            get {
                return ResourceManager.GetString("LinksErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error writing to the file {0}: {1}.
        /// </summary>
        internal static string LinksErrorWritingLinksErrorWriting {
            get {
                return ResourceManager.GetString("LinksErrorWritingLinksErrorWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a written.
        /// </summary>
        internal static string LinksWritten {
            get {
                return ResourceManager.GetString("LinksWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CSV Files (*.csv)|*.csv|All Files (*.*)|*.*.
        /// </summary>
        internal static string ListTextsFilterCsv {
            get {
                return ResourceManager.GetString("ListTextsFilterCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a HTML Files (*.html; *.htm)|*.html;*.htm|All Files (*.*)|*.*.
        /// </summary>
        internal static string ListTextsFilterHtml {
            get {
                return ResourceManager.GetString("ListTextsFilterHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RTF Files (*.rtf)|*.rtf|All Files (*.*)|*.*.
        /// </summary>
        internal static string ListTextsFilterRtf {
            get {
                return ResourceManager.GetString("ListTextsFilterRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text Files (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        internal static string ListTextsFilterText {
            get {
                return ResourceManager.GetString("ListTextsFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a XML Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string ListTextsFilterXml {
            get {
                return ResourceManager.GetString("ListTextsFilterXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text.
        /// </summary>
        internal static string ListTextsText {
            get {
                return ResourceManager.GetString("ListTextsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All.
        /// </summary>
        internal static string MainAllBibles {
            get {
                return ResourceManager.GetString("MainAllBibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All.
        /// </summary>
        internal static string MainAllCommentaries {
            get {
                return ResourceManager.GetString("MainAllCommentaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error writing to the file {0}: {1}.
        /// </summary>
        internal static string MainArrangementError {
            get {
                return ResourceManager.GetString("MainArrangementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Arrangement.
        /// </summary>
        internal static string MainArrangementNewName {
            get {
                return ResourceManager.GetString("MainArrangementNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Arrangement of the Windows.
        /// </summary>
        internal static string MainArrangementSaveCaption {
            get {
                return ResourceManager.GetString("MainArrangementSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a What do you want to call this new window arrangement?.
        /// </summary>
        internal static string MainArrangementSaveQuestion {
            get {
                return ResourceManager.GetString("MainArrangementSaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It was not possible to save to disk changes to the following texts: {0}.
        /// </summary>
        internal static string MainErrorChangesNotSaved {
            get {
                return ResourceManager.GetString("MainErrorChangesNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error opening {0}: {1}.
        /// </summary>
        internal static string MainLinksErrorCommandFailed {
            get {
                return ResourceManager.GetString("MainLinksErrorCommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;All the Texts.
        /// </summary>
        internal static string MainListTexts {
            get {
                return ResourceManager.GetString("MainListTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New link.
        /// </summary>
        internal static string MainMakeHypertextCaption {
            get {
                return ResourceManager.GetString("MainMakeHypertextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To what passage, note or file do you want to create a link?.
        /// </summary>
        internal static string MainMakeHypertextQuestion {
            get {
                return ResourceManager.GetString("MainMakeHypertextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No name.
        /// </summary>
        internal static string MainNewEditorCaption {
            get {
                return ResourceManager.GetString("MainNewEditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No file containing the text of the Bible was found. You need to install a Bible..
        /// </summary>
        internal static string MainNoBible {
            get {
                return ResourceManager.GetString("MainNoBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The notes that have been changed are being saved. Please wait..
        /// </summary>
        internal static string MainNoteChanged {
            get {
                return ResourceManager.GetString("MainNoteChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set bookmark.
        /// </summary>
        internal static string MainQuickBookmarkSetCaption {
            get {
                return ResourceManager.GetString("MainQuickBookmarkSetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a At which verse do you want to create a bookmark?.
        /// </summary>
        internal static string MainQuickBookmarkSetQuestion {
            get {
                return ResourceManager.GetString("MainQuickBookmarkSetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error whilst checking the most recent version on Internet: {0}.
        /// </summary>
        internal static string MainUpdateNotConnected {
            get {
                return ResourceManager.GetString("MainUpdateNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No updates available: you have the most recent version of the program..
        /// </summary>
        internal static string MainUpdateNoUpdate {
            get {
                return ResourceManager.GetString("MainUpdateNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a http://www.laparola.net/program/video.php.
        /// </summary>
        internal static string MainVideoAddress {
            get {
                return ResourceManager.GetString("MainVideoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The text {0} has been copied to {1}..
        /// </summary>
        internal static string ManageNotesCopied {
            get {
                return ResourceManager.GetString("ManageNotesCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copy of {0}.
        /// </summary>
        internal static string ManageNotesCopyOf {
            get {
                return ResourceManager.GetString("ManageNotesCopyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The text {0} has been deleted..
        /// </summary>
        internal static string ManageNotesDeleted {
            get {
                return ResourceManager.GetString("ManageNotesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The collection must have been save after having been modified in order to export in this format. Close and reopen the program, and try again..
        /// </summary>
        internal static string ManageNotesErrorModified {
            get {
                return ResourceManager.GetString("ManageNotesErrorModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during the coping of the text {1}: {0}.
        /// </summary>
        internal static string ManageNotesErrorNotCopied {
            get {
                return ResourceManager.GetString("ManageNotesErrorNotCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during the deletion of the text {1}: {0}.
        /// </summary>
        internal static string ManageNotesErrorNotDeleted {
            get {
                return ResourceManager.GetString("ManageNotesErrorNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during the exporting of the text {1}: {0}.
        /// </summary>
        internal static string ManageNotesErrorNotExported {
            get {
                return ResourceManager.GetString("ManageNotesErrorNotExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during the joining of the texts to create {1}: {0}.
        /// </summary>
        internal static string ManageNotesErrorNotJoined {
            get {
                return ResourceManager.GetString("ManageNotesErrorNotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during the renaming of the text {1}: {0}.
        /// </summary>
        internal static string ManageNotesErrorNotRenamed {
            get {
                return ResourceManager.GetString("ManageNotesErrorNotRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The text {0} has been exported to.
        /// </summary>
        internal static string ManageNotesExported {
            get {
                return ResourceManager.GetString("ManageNotesExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rename.
        /// </summary>
        internal static string ManageNotesRenameCaption {
            get {
                return ResourceManager.GetString("ManageNotesRenameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The text {0} has been renamed to {1}..
        /// </summary>
        internal static string ManageNotesRenamed {
            get {
                return ResourceManager.GetString("ManageNotesRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a What is the new name of the text?.
        /// </summary>
        internal static string ManageNotesRenameQuestion {
            get {
                return ResourceManager.GetString("ManageNotesRenameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bl&amp;ack.
        /// </summary>
        internal static string MiscBlack {
            get {
                return ResourceManager.GetString("MiscBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close.
        /// </summary>
        internal static string MiscClose {
            get {
                return ResourceManager.GetString("MiscClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm.
        /// </summary>
        internal static string MiscConfirm {
            get {
                return ResourceManager.GetString("MiscConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string MiscError {
            get {
                return ResourceManager.GetString("MiscError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Information.
        /// </summary>
        internal static string MiscInfo {
            get {
                return ResourceManager.GetString("MiscInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add a directory to look in for program files:.
        /// </summary>
        internal static string OptionsAddDirectory {
            get {
                return ResourceManager.GetString("OptionsAddDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to use the default names of the books in the Bible in this new language?.
        /// </summary>
        internal static string OptionsChangeLanguage {
            get {
                return ResourceManager.GetString("OptionsChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to reload the settings of the program that were current when it was opened?.
        /// </summary>
        internal static string OptionsReload {
            get {
                return ResourceManager.GetString("OptionsReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to cancel all the changes that you have made to the settings?.
        /// </summary>
        internal static string OptionsReset {
            get {
                return ResourceManager.GetString("OptionsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Tab.
        /// </summary>
        internal static string ParagraphTabs {
            get {
                return ResourceManager.GetString("ParagraphTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type the value of the new tab (in centimetres)..
        /// </summary>
        internal static string ParagraphTabsNew {
            get {
                return ResourceManager.GetString("ParagraphTabsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The verse {0} was not found in these parallel passages..
        /// </summary>
        internal static string ParallelPassagesVerseNotFound {
            get {
                return ResourceManager.GetString("ParallelPassagesVerseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I could not understand the reference {0}..
        /// </summary>
        internal static string ParallelPassagesVerseNotUnderstood {
            get {
                return ResourceManager.GetString("ParallelPassagesVerseNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set of Parallel Texts.
        /// </summary>
        internal static string ParallelTextsSaveCaption {
            get {
                return ResourceManager.GetString("ParallelTextsSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a What do you want to call this set of texts?.
        /// </summary>
        internal static string ParallelTextsSaveQuestion {
            get {
                return ResourceManager.GetString("ParallelTextsSaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Always.
        /// </summary>
        internal static string QuizAlways {
            get {
                return ResourceManager.GetString("QuizAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Answer.
        /// </summary>
        internal static string QuizAnswer {
            get {
                return ResourceManager.GetString("QuizAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This quiz asks you many different questions on the Bible, each with four possible answers.\par\par For each question, click on the answer that you think is correct, or type a number from 1 to 4..
        /// </summary>
        internal static string QuizInstructions {
            get {
                return ResourceManager.GetString("QuizInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Question.
        /// </summary>
        internal static string QuizQuestion {
            get {
                return ResourceManager.GetString("QuizQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right.
        /// </summary>
        internal static string QuizRight {
            get {
                return ResourceManager.GetString("QuizRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right Answer.
        /// </summary>
        internal static string QuizRightAnswer {
            get {
                return ResourceManager.GetString("QuizRightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Score.
        /// </summary>
        internal static string QuizScore {
            get {
                return ResourceManager.GetString("QuizScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wrong.
        /// </summary>
        internal static string QuizWrong {
            get {
                return ResourceManager.GetString("QuizWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wrong Answer.
        /// </summary>
        internal static string QuizWrongAnswer {
            get {
                return ResourceManager.GetString("QuizWrongAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No daily reading plans were found. You can install new plans using the Update command of the program..
        /// </summary>
        internal static string ReadingsErrorNoPlan {
            get {
                return ResourceManager.GetString("ReadingsErrorNoPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search for.
        /// </summary>
        internal static string SearchBookmarksDescription1 {
            get {
                return ResourceManager.GetString("SearchBookmarksDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a in.
        /// </summary>
        internal static string SearchBookmarksDescription2 {
            get {
                return ResourceManager.GetString("SearchBookmarksDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The brackets are incorrect..
        /// </summary>
        internal static string SearchBrackets {
            get {
                return ResourceManager.GetString("SearchBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search completed..
        /// </summary>
        internal static string SearchCompleted {
            get {
                return ResourceManager.GetString("SearchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Searching:.
        /// </summary>
        internal static string SearchCurrent {
            get {
                return ResourceManager.GetString("SearchCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You need to type an expression to search for..
        /// </summary>
        internal static string SearchExpressionEmpty {
            get {
                return ResourceManager.GetString("SearchExpressionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New verse list.
        /// </summary>
        internal static string SearchNewVerseListCaption {
            get {
                return ResourceManager.GetString("SearchNewVerseListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type the name of the new verse list:.
        /// </summary>
        internal static string SearchNewVerseListQuestion1 {
            get {
                return ResourceManager.GetString("SearchNewVerseListQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type the reference of the new verse list:.
        /// </summary>
        internal static string SearchNewVerseListQuestion2 {
            get {
                return ResourceManager.GetString("SearchNewVerseListQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The square brackets are incorrect or are nested..
        /// </summary>
        internal static string SearchSquareBrackets {
            get {
                return ResourceManager.GetString("SearchSquareBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Syntax error at about character number {0}..
        /// </summary>
        internal static string SearchSyntax {
            get {
                return ResourceManager.GetString("SearchSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a time.
        /// </summary>
        internal static string SearchTime {
            get {
                return ResourceManager.GetString("SearchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a times.
        /// </summary>
        internal static string SearchTimes {
            get {
                return ResourceManager.GetString("SearchTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Text created..
        /// </summary>
        internal static string ShowCompleted {
            get {
                return ResourceManager.GetString("ShowCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creating the text:.
        /// </summary>
        internal static string ShowCurrent {
            get {
                return ResourceManager.GetString("ShowCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Similar passages shown..
        /// </summary>
        internal static string SimilarCompleted {
            get {
                return ResourceManager.GetString("SimilarCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finding similar passages:.
        /// </summary>
        internal static string SimilarCurrent {
            get {
                return ResourceManager.GetString("SimilarCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Passages similar to .
        /// </summary>
        internal static string SimilarTitle {
            get {
                return ResourceManager.GetString("SimilarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open the Bible program with today&apos;s reading..
        /// </summary>
        internal static string StartupReadingsDescription {
            get {
                return ResourceManager.GetString("StartupReadingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Daily Reading.
        /// </summary>
        internal static string StartupReadingsTitle {
            get {
                return ResourceManager.GetString("StartupReadingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Program|Update|Text|Bible|Commentary|Dictionary|Notes|Book|Parallels|External Link|Bookmarks|Daily Readings|Tutorial|Parallel Texts.
        /// </summary>
        internal static string UpdateComponentTypes {
            get {
                return ResourceManager.GetString("UpdateComponentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hide.
        /// </summary>
        internal static string UpdateHide {
            get {
                return ResourceManager.GetString("UpdateHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New.
        /// </summary>
        internal static string UpdateNew {
            get {
                return ResourceManager.GetString("UpdateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Don&apos;t update.
        /// </summary>
        internal static string UpdateNoUpdate {
            get {
                return ResourceManager.GetString("UpdateNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error opening the update program: {0}.
        /// </summary>
        internal static string UpdateProgramNotRun {
            get {
                return ResourceManager.GetString("UpdateProgramNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update now.
        /// </summary>
        internal static string UpdateUpdateNow {
            get {
                return ResourceManager.GetString("UpdateUpdateNow", resourceCulture);
            }
        }
    }
}
